PROGRAM TESTDIFF

USE OPENACC
USE CUBLAS

IMPLICIT NONE
! roundup differences   !!     no roundup differences
! 30        70          !!    30       30     15                                                    
! 11772     11772       !!    289600   1800   992                                                 
! 2806      2806        !!    72400    440    220                                                  
! 3080      3080        !!    72400    460    276                                                   
! 2806      2806        !!    72400    440    220                                                   
! 3080      3080        !!    72400    460    276                                                   
!
INTEGER , PARAMETER           :: NFLEVG=70 
INTEGER , PARAMETER           :: NSPEC= 11772
INTEGER , PARAMETER           :: NSPEC0=2806
INTEGER , PARAMETER           :: NSPEC1=3080
INTEGER , PARAMETER           :: NSPEC2=2806
INTEGER , PARAMETER           :: NSPEC3=3080
DOUBLE PRECISION, DIMENSION(NSPEC,NFLEVG)   :: DATAIN
DOUBLE PRECISION, DIMENSION(NSPEC0,NFLEVG)  :: DATAIN0
DOUBLE PRECISION, DIMENSION(NSPEC1,NFLEVG)  :: DATAIN1
DOUBLE PRECISION, DIMENSION(NSPEC2,NFLEVG)  :: DATAIN2
DOUBLE PRECISION, DIMENSION(NSPEC3,NFLEVG)  :: DATAIN3
DOUBLE PRECISION, DIMENSION(NSPEC)   :: DATAOUT
DOUBLE PRECISION, DIMENSION(NSPEC0)  :: DATAOUT0
DOUBLE PRECISION, DIMENSION(NSPEC1)  :: DATAOUT1
DOUBLE PRECISION, DIMENSION(NSPEC2)  :: DATAOUT2
DOUBLE PRECISION, DIMENSION(NSPEC3)  :: DATAOUT3
DOUBLE PRECISION, DIMENSION(NFLEVG)  :: SIMI

DOUBLE PRECISION,PARAMETER   :: ALPHA=1.0
DOUBLE PRECISION,PARAMETER   :: BETA=0.0

INTEGER            :: JSP,JLEV,DEV,COUNTER,INCR
DOUBLE PRECISION   :: AMPLITUDE

INCR=1
DEV=0
COUNTER=0 
AMPLITUDE=0.0

CALL ACC_SET_DEVICE_NUM(DEV,ACC_DEVICE_NVIDIA)
CALL ACC_INIT(ACC_DEVICE_NVIDIA)

CALL RANDOM_NUMBER(DATAIN)
CALL RANDOM_NUMBER(SIMI)

DATAIN0(1:NSPEC0,1:NFLEVG)=DATAIN(1:NSPEC0,1:NFLEVG)
DATAIN1(1:NSPEC1,1:NFLEVG)=DATAIN(NSPEC0+1:NSPEC0+NSPEC1,1:NFLEVG)
DATAIN2(1:NSPEC2,1:NFLEVG)=DATAIN(NSPEC0+NSPEC1+1:NSPEC0+NSPEC1+NSPEC2,1:NFLEVG)
DATAIN3(1:NSPEC3,1:NFLEVG)=DATAIN(NSPEC0+NSPEC1+NSPEC2+1:NSPEC0+NSPEC1+NSPEC2+NSPEC3,1:NFLEVG)

!$ACC DATA COPYIN(DATAIN,DATAIN0,DATAIN1,DATAIN2,DATAIN3,SIMI) &
!$ACC& COPYOUT(DATAOUT,DATAOUT0,DATAOUT1,DATAOUT2,DATAOUT3)

WRITE (0,*) "avant multiplications "
!$ACC HOST_DATA USE_DEVICE(DATAIN,DATAIN0,DATAIN1,DATAIN2,DATAIN3,SIMI,&
!$ACC& DATAOUT,DATAOUT0,DATAOUT1,DATAOUT2,DATAOUT3)
CALL CUBLASDGEMV('N',NSPEC,NFLEVG,ALPHA,DATAIN,NSPEC,SIMI,INCR,BETA,DATAOUT,INCR)
CALL CUBLASDGEMV('N',NSPEC0,NFLEVG,ALPHA,DATAIN0,NSPEC0,SIMI,INCR,BETA,DATAOUT0,INCR)
CALL CUBLASDGEMV('N',NSPEC1,NFLEVG,ALPHA,DATAIN1,NSPEC1,SIMI,INCR,BETA,DATAOUT1,INCR)
CALL CUBLASDGEMV('N',NSPEC2,NFLEVG,ALPHA,DATAIN2,NSPEC2,SIMI,INCR,BETA,DATAOUT2,INCR)
CALL CUBLASDGEMV('N',NSPEC3,NFLEVG,ALPHA,DATAIN3,NSPEC3,SIMI,INCR,BETA,DATAOUT3,INCR)
!$ACC END HOST_DATA
!$ACC WAIT

WRITE (0,*) "apres multiplications "

!$ACC END DATA

DO JSP=1,NSPEC0
  IF (DATAOUT(JSP)/=DATAOUT0(JSP)) THEN
    WRITE(0,*) "JSP OUT OUT0 ",JSP
    WRITE (0,'(E30.20)') DATAOUT(JSP)
    WRITE (0,'(E30.20)') DATAOUT0(JSP)
    COUNTER=COUNTER+1
    AMPLITUDE=MAX(AMPLITUDE,ABS(DATAOUT0(JSP)-DATAOUT(JSP)))
  ENDIF
ENDDO
WRITE (0,*) "fin boucle0"

DO JSP=1,NSPEC1
  IF (DATAOUT(NSPEC0+JSP)/=DATAOUT1(JSP)) THEN
    WRITE(0,*) "JSP OUT OUT1 ",JSP
    WRITE (0,'(E30.20)') DATAOUT(NSPEC0+JSP)
    WRITE (0,'(E30.20)') DATAOUT1(JSP)
    COUNTER=COUNTER+1
    AMPLITUDE=MAX(AMPLITUDE,ABS(DATAOUT1(JSP)-DATAOUT(NSPEC0+JSP)))
  ENDIF
ENDDO
WRITE (0,*) "fin boucle1"

DO JSP=1,NSPEC2
  IF (DATAOUT(NSPEC0+NSPEC1+JSP)/=DATAOUT2(JSP)) THEN
    WRITE(0,*) "JSP OUT OUT2 ",JSP
    WRITE (0,'(E30.20)') DATAOUT(NSPEC0+NSPEC1+JSP)
    WRITE (0,'(E30.20)') DATAOUT2(JSP)
    COUNTER=COUNTER+1
    AMPLITUDE=MAX(AMPLITUDE,ABS(DATAOUT2(JSP)-DATAOUT(NSPEC0+NSPEC1+JSP)))
  ENDIF
ENDDO

WRITE (0,*) "fin boucle 2"

DO JSP=1,NSPEC3
  IF (DATAOUT(NSPEC0+NSPEC1+NSPEC2+JSP)/=DATAOUT3(JSP)) THEN
    WRITE(0,*) "JSP OUT OUT3 ",JSP
    WRITE (0,'(E30.20)') DATAOUT(NSPEC0+NSPEC1+NSPEC2+JSP)
    WRITE (0,'(E30.20)') DATAOUT3(JSP)
    COUNTER=COUNTER+1
    AMPLITUDE=MAX(AMPLITUDE,ABS(DATAOUT3(JSP)-DATAOUT(NSPEC0+NSPEC1+NSPEC2+JSP)))
  ENDIF
ENDDO

WRITE (0,*) "fin boucle 3"

WRITE (0,*) "Number of differences ",COUNTER," length ",NSPEC
WRITE (0,*) "Maximum difference : "
WRITE (0,'(E30.20)') AMPLITUDE


END PROGRAM TESTDIFF
