PROGRAM MAIN

USE PARKIND1, ONLY : JPIM, JPRB

IMPLICIT NONE

INTEGER(KIND=JPIM)               :: KLX
INTEGER(KIND=JPIM)               :: KLXS 
INTEGER(KIND=JPIM)               :: KVX 
INTEGER(KIND=JPIM)               :: KVXS
INTEGER(KIND=JPIM)               :: KIX 
INTEGER(KIND=JPIM)               :: KIXS
INTEGER(KIND=JPIM)               :: KT1
INTEGER(KIND=JPIM)               :: KT2
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PA(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PB(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PC(:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PD(:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PE(:,:)
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PY(:,:,:) 
REAL(KIND=JPRB)   ,ALLOCATABLE   :: PX(:,:,:) 

#include "mxture.h"

CHARACTER*256 :: CLFILE
INTEGER :: I1, I2, I3

CALL GETARG (1, CLFILE)

OPEN (77, FILE=TRIM (CLFILE), FORM='UNFORMATTED')

READ (77) KLX
READ (77) KLXS 
READ (77) KVX 
READ (77) KVXS
READ (77) KIX 
READ (77) KIXS
READ (77) KT1
READ (77) KT2

ALLOCATE (PA(KLX,KVX))
ALLOCATE (PB(KLX,KVX)) 
ALLOCATE (PC(KLX,KVX)) 
ALLOCATE (PD(KLX,KVX))
ALLOCATE (PE(KLX,KVX))
ALLOCATE (PY(KIXS,KLX,KVXS))
ALLOCATE (PX(KIXS,KLX,KVXS))

READ (77) PA
READ (77) PB
READ (77) PC
READ (77) PD
READ (77) PE
READ (77) PY
READ (77) PX

CLOSE (77)

CALL MXTURE (KLX,KLXS,KVX,KVXS,KIX,KIXS,KT1,KT2,PA,PB,PC,PD,PE,PY,PX)

DO I1 = 1, KIXS
  DO I2 = 1, KLX
    DO I3 = 1, KVXS 
      WRITE (*, '(I4," ",I4," ",I4," ",E30.20," ",E30.20)') &
     & I1, I2, I3, PY(I1,I2,I3), PX(I1,I2,I3)
    ENDDO
  ENDDO
ENDDO


END
