SUBROUTINE MXTURE(KLX,KLXS,KVX,KVXS,KIX,KIXS,KT1,KT2,PA,PB,PC,PD,PE,PY,PX)

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KLX
INTEGER(KIND=JPIM),INTENT(IN)    :: KLXS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KVX 
INTEGER(KIND=JPIM),INTENT(IN)    :: KVXS
INTEGER(KIND=JPIM),INTENT(IN)    :: KIX 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIXS
INTEGER(KIND=JPIM),INTENT(IN)    :: KT1
INTEGER(KIND=JPIM),INTENT(IN)    :: KT2
REAL(KIND=JPRB)   ,INTENT(IN)    :: PA(KLX,KVX) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PB(KLX,KVX) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PC(KLX,KVX) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PD(KLX,KVX)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PE(KLX,KVX)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PY(KIXS,KLX,KVXS) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PX(KIXS,KLX,KVXS) 

INTEGER(KIND=JPIM) :: JI, JL, JV, IIXL, IIX

LOGICAL :: LLOMP

LLOMP = .FALSE.

IIXL=MAX(2,KIX)
IIX=KIX-MOD(KIX,2)

!$OMP PARALLEL PRIVATE(JI,JV,JL) IF (LLOMP)

DO JI=1,IIX,2
  !$OMP DO SIMD
  DO JV=1,KVX
    DO JL=3,KLX
      PY(JI,JL,JV)=(PY(JI,JL,JV)-PC(JL-2,JV)*PY(JI,JL-2,JV)&
       &-PB(JL-1,JV)*PY(JI,JL-1,JV))/PA(JL,JV)
    ENDDO
  ENDDO
ENDDO

!$OMP END PARALLEL

END SUBROUTINE MXTURE
