PROGRAM MASTER

IMPLICIT NONE

INTEGER, PARAMETER :: JPRB = 8

TYPE TVETA1
  REAL(KIND=JPRB), ALLOCATABLE :: VETAH(:)
END TYPE 

TYPE GEOMETRY1
  TYPE(TVETA1), POINTER :: YRVETA => NULL()
END TYPE

TYPE (GEOMETRY1) ::YDGEOMETRY

!$ACC SERIAL 
print *, ALLOCATED (YDGEOMETRY%YRVETA%VETAH)
!$ACC END SERIAL

END PROGRAM MASTER
