PROGRAM POINTER_PTRS

IMPLICIT NONE

TYPE REAL_PTR
  REAL,POINTER :: P(:)
END TYPE REAL_PTR

REAL, ALLOCATABLE, TARGET :: A(:,:,:)
TYPE (REAL_PTR),ALLOCATABLE :: PTRS(:)

INTEGER :: KLEV,KSPEC,KFLDS,ID
REAL, POINTER :: ZZ1 (:)

KLEV = 2
KSPEC = 10
KFLDS = 1

ALLOCATE (A (KLEV, KSPEC, KFLDS))

WRITE(*,"(I3,A,z16.16)") 1, ": 0x", LOC (A (1, 1, 1))
WRITE(*,"(I3,A,z16.16)") 2, ": 0x", LOC (A (2, 1, 1))
PRINT *

PTRS = ALLOCATE_AND_ASSIGN_PTRS (A, KLEV, KFLDS)

DO ID = 1, SIZE(PTRS)
  ZZ1 => PTRS(ID)%P
  WRITE(*,"(I3,A,z16.16)") ID, ": 0x", LOC (ZZ1 (1))
ENDDO
PRINT *

DEALLOCATE(A)
DEALLOCATE(PTRS)

CONTAINS

SUBROUTINE ASSIGN_PTRS (PTRS, A, KLEV, KFLDS)

TYPE (REAL_PTR), INTENT(INOUT) :: PTRS (:)
REAL, TARGET :: A (:,:,:)
INTEGER :: KLEV,KFLDS

REAL, POINTER :: ZZ1 (:)
INTEGER :: ID, JLEV, JFLD

ID = 1
DO JLEV = 1,KLEV
 DO JFLD = 1,KFLDS
   PTRS(ID)%P => A (JLEV,:,JFLD)
   ID = ID + 1
 ENDDO
ENDDO

DO ID = 1, SIZE(PTRS)
  ZZ1 => PTRS(ID)%P
  WRITE(*,"(I3,A,z16.16)") ID, ": 0x", LOC (ZZ1 (1))
ENDDO
PRINT *

END SUBROUTINE

FUNCTION ALLOCATE_AND_ASSIGN_PTRS (A, KLEV, KFLDS) RESULT (PTRS)

REAL, ALLOCATABLE, TARGET :: A(:,:,:)
INTEGER :: KLEV, KFLDS
TYPE (REAL_PTR), ALLOCATABLE :: PTRS (:)

ALLOCATE (PTRS (KLEV*KFLDS))
CALL ASSIGN_PTRS (PTRS, A, KLEV, KFLDS)

END FUNCTION

END PROGRAM POINTER_PTRS
