PROGRAM MAIN

TYPE CPG_SL2_TYPE
  REAL (KIND=8), POINTER, CONTIGUOUS :: ZVIEW (:,:) => NULL ()
  REAL (KIND=8), POINTER, CONTIGUOUS :: ZDATA (:,:,:) => NULL ()
END TYPE 

INTEGER (KIND=4) :: IBL 

TYPE (CPG_SL2_TYPE) :: YDCPG_SL2

ALLOCATE (YDCPG_SL2%ZDATA (10, 10, 2))

DO IBL = 1, 2

WRITE (0, *) " IBL = ", IBL 

YDCPG_SL2%ZVIEW => YDCPG_SL2%ZDATA (:,:,IBL)

YDCPG_SL2%ZVIEW = 0.
WRITE (0, *) " ZDATA (:,:,1) = ", YDCPG_SL2%ZDATA (1,1,1)
YDCPG_SL2%ZVIEW = 1.
WRITE (0, *) " ZDATA (:,:,1) = ", YDCPG_SL2%ZDATA (1,1,1)

ENDDO

END 

