
MODULE MODI_DEFAULT_CROCUS

INTERFACE

SUBROUTINE DEFAULT_CROCUS (HSNOWDRIFT, OSNOWDRIFT_SUBLIM, OSNOW_&
&ABS_ZENITH, HSNOWMETAMO, HSNOWRAD, OATMORAD, OSNOWSYTRON, HSNOWF&
&ALL, HSNOWCOND, HSNOWHOLD, HSNOWCOMP, HSNOWZREF, OSNOWCOMPACT_BO&
&OL, OSNOWMAK_BOOL, OPRODSNOWMAK, OSNOWMAK_PROP, OSNOWTILLER, OSE&
&LF_PROD)
IMPLICIT NONE
CHARACTER (*), INTENT (OUT)::HSNOWDRIFT
LOGICAL, INTENT (OUT)::OSNOWDRIFT_SUBLIM
LOGICAL, INTENT (OUT)::OSNOW_ABS_ZENITH
LOGICAL, INTENT (OUT)::OATMORAD
LOGICAL, INTENT (OUT)::OSNOWSYTRON
CHARACTER (*), INTENT (OUT)::HSNOWMETAMO, HSNOWRAD, HSNOWFALL, H&
&SNOWCOND, HSNOWHOLD, HSNOWCOMP, HSNOWZREF
LOGICAL, INTENT (OUT)::OSNOWCOMPACT_BOOL
LOGICAL, DIMENSION (:), INTENT (OUT)::OPRODSNOWMAK
LOGICAL, INTENT (OUT)::OSNOWMAK_BOOL
LOGICAL, INTENT (OUT)::OSNOWMAK_PROP
LOGICAL, INTENT (OUT)::OSNOWTILLER
LOGICAL, INTENT (OUT)::OSELF_PROD
ENDSUBROUTINE DEFAULT_CROCUS

END INTERFACE

END MODULE

