MODULE MODD_IO_SURF_ARO

!TYPE SURFEX_FIELD_BUF_CACHE
!END TYPE

!TYPE (SURFEX_FIELD_BUF_CACHE) :: YSURFEX_CACHE_OUT           

CONTAINS

SUBROUTINE SURFEX_FIELD_BUF_ADD
USE GEOMETRY_MOD, ONLY : GEOMETRY
END SUBROUTINE SURFEX_FIELD_BUF_ADD

END MODULE MODD_IO_SURF_ARO

