MODULE MODD_IO_SURF_ARO

TYPE SURFEX_FIELD_BUF_CACHE
  LOGICAL :: LDUMMY  = .FALSE.
END TYPE

TYPE (SURFEX_FIELD_BUF_CACHE) :: YSURFEX_CACHE_OUT           

INTERFACE SURFEX_FIELD_BUF_ADD
  MODULE PROCEDURE SURFEX_FIELD_BUF_ADD_Y1
END INTERFACE

CONTAINS

SUBROUTINE SURFEX_FIELD_BUF_FIX2DF (YDGEOMETRY)
USE GEOMETRY_MOD ,ONLY : GEOMETRY
TYPE(GEOMETRY),    INTENT (IN) :: YDGEOMETRY
END SUBROUTINE SURFEX_FIELD_BUF_FIX2DF 

SUBROUTINE SURFEX_FIELD_BUF_ADD_Y1(YDSC)
USE GEOMETRY_MOD, ONLY : GEOMETRY
TYPE (SURFEX_FIELD_BUF_CACHE), INTENT (INOUT) :: YDSC
END SUBROUTINE SURFEX_FIELD_BUF_ADD_Y1

END MODULE MODD_IO_SURF_ARO

