SUBROUTINE WRITE_SURFL0_ARO(HREC,OFIELD,KRESP,HCOMMENT)

USE MODD_IO_SURF_ARO,  ONLY: SURFEX_FIELD_BUF_ADD, YSURFEX_CACHE_OUT

IMPLICIT NONE
CHARACTER(LEN=*),   INTENT(IN)  :: HREC     
LOGICAL,            INTENT(IN)  :: OFIELD   
INTEGER,            INTENT(IN)  :: KRESP    
CHARACTER(LEN=100), INTENT(IN)  :: HCOMMENT 

CALL SURFEX_FIELD_BUF_ADD (YSURFEX_CACHE_OUT)

END SUBROUTINE WRITE_SURFL0_ARO
