MODULE MODE_SEAICE_SICE_SNOW
USE MODE_SEAICE_SICE

IMPLICIT NONE
PRIVATE

TYPE, PUBLIC :: SNOW_RESPONSE_t
  INTEGER :: RESP_SIZE
  REAL, POINTER, DIMENSION(:) :: &
    HEAT_FLUX, &
    WATER_FLUX
END TYPE SNOW_RESPONSE_t

TYPE, PUBLIC :: SICE_SNOW_t
  INTEGER :: NUM_LAYERS !< Number of snow layers
  INTEGER :: NUM_POINTS
  REAL, POINTER, DIMENSION(:) :: &
    ALBEDO,     & !< Snow albedo
    THRUFAL,    & !< Rate that liquid water leaves snow pack:
    GRND_FLUX,  & !< Soil/snow interface heat flux
    EVAP_COR      !< Evaporation/sublimation correction term
  REAL, POINTER, DIMENSION( :, : ) :: &
    HEAT,       & !< Snow layers heat content
    RHO,        & !< Snow layers averaged density
    SWE,        & !< Snow layers liquid Water Equivalent
    AGE,        & !< Snow grain age
    LIQ_WATER,  & !< Snow layes liquid water content
    T,          & !< Snow layers temperature
    DZ            !< Snow layers thickness
  REAL, POINTER, DIMENSION( : ) :: &
    DZ_TOT        !< Total snow thickness

  TYPE( MODEL_FIELD ), ALLOCATABLE :: MF(:)

  CONTAINS
    PROCEDURE, PASS :: INIT
    PROCEDURE, PASS :: PREP
    PROCEDURE, PASS :: ASSIM
    PROCEDURE, PASS :: RUN
    PROCEDURE, PASS :: DEALLOC

    PROCEDURE, PASS :: EXISTS
    PROCEDURE, PASS :: GET_RESPONSE
    PROCEDURE, PASS :: GET_MODEL_FIELDS

    PROCEDURE, PASS :: ALLOCA

    PROCEDURE, PASS, PRIVATE :: RUN_INTERNAL
    PROCEDURE, PASS, PRIVATE :: POST_RUN
    PROCEDURE, PASS, PRIVATE :: SAFETY_GUARD
END TYPE SICE_SNOW_t

CONTAINS

SUBROUTINE INIT(THIS, HPROGRAM)
IMPLICIT NONE
  CLASS(SICE_SNOW_t) ::THIS
  CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM

END SUBROUTINE INIT

SUBROUTINE PREP(THIS, KLU, HPROGRAM, HATMFILE, HATMFILETYPE, HPGDFILE, HPGDFILETYPE)
IMPLICIT NONE
  CLASS(SICE_SNOW_t) :: THIS
  INTEGER, INTENT(IN) :: KLU
  CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  !< program calling surf. schemes
  CHARACTER(LEN=28),  INTENT(IN)  :: HATMFILE    !< name of the Atmospheric file
  CHARACTER(LEN=6),   INTENT(IN)  :: HATMFILETYPE!< type of the Atmospheric file
  CHARACTER(LEN=28),  INTENT(IN)  :: HPGDFILE    !< name of the PGD file
  CHARACTER(LEN=6),   INTENT(IN)  :: HPGDFILETYPE!< type of the PGD file

END SUBROUTINE PREP

SUBROUTINE ASSIM(THIS)
IMPLICIT NONE
  CLASS(SICE_SNOW_t) :: THIS
END SUBROUTINE ASSIM

SUBROUTINE RUN(THIS, PTSTEP, FORC, PTG, PD_G, PSOILCOND, PALB)
IMPLICIT NONE
  CLASS(SICE_SNOW_t) :: THIS
  REAL, INTENT(IN) :: PTSTEP
  TYPE(SEA_ICE_FORCING_t), INTENT(IN) :: FORC
  REAL, INTENT(IN) :: PTG(:)
  REAL, INTENT(IN) :: PD_G(:)
  REAL, INTENT(IN) :: PSOILCOND(:)
  REAL, INTENT(IN) :: PALB(:)

  INTEGER :: JJ, JWRK
  INTEGER :: ISIZE_SNOW
  INTEGER :: NMASK(THIS%NUM_POINTS)
  REAL, DIMENSION(FORC%KSIZE) :: &
    ZSNOW, &
    ZSNOWFALL, &
    ZSNOWH, &
    ZSNOWH1, &
    ZSNOWSWE_1D

END SUBROUTINE RUN

SUBROUTINE RUN_INTERNAL(THIS, FORC, PTSTEP, PTG, PD_G, PSOILCOND, PALB, KSIZE_SNOW, KMASK)
IMPLICIT NONE
  CLASS(SICE_SNOW_t) :: THIS
  TYPE(SEA_ICE_FORCING_t), INTENT(IN) :: FORC
  REAL, INTENT(IN) :: PTSTEP
  REAL, INTENT(IN) :: PTG(:)
  REAL, INTENT(IN) :: PD_G(:)
  REAL, INTENT(IN) :: PSOILCOND(:)
  REAL, INTENT(IN) :: PALB(:)
  INTEGER, INTENT(IN) :: KSIZE_SNOW
  INTEGER, INTENT(IN) :: KMASK(KSIZE_SNOW)

  REAL, DIMENSION(KSIZE_SNOW) :: &
    ZP_ALB,         &
    ZP_CDSNOW,      &
    ZP_CHSNOW,      &
    ZP_D_G,         &
    ZP_DELHEATN,    &
    ZP_DELHEATN_SFC,&
    ZP_DIRCOSZW,    &
    ZP_EMISNOW,     &
    ZP_EVAP,        &
    ZP_EVAPCOR,     &
    ZP_EXNA,        &
    ZP_EXNS,        &
    ZP_FOREST,      & ! Fraction of forest
    ZP_GFLUXSNOW,   &
    ZP_GFLXCOR,     &
    ZP_GRNDFLUX,    &
    ZP_GSFCSNOW,    &
    ZP_HPSNOW,      &
    ZP_HSNOW,       &
    ZP_LAT,         &
    ZP_LEL3L,       &
    ZP_LES3L,       &
    ZP_LON,         &
    ZP_LSTT,        &
    ZP_LVTT,        &
    ZP_LW_RAD,      &
    ZP_LWNETSNOW,   &
    ZP_PEQ_A_COEF,  &
    ZP_PEQ_B_COEF,  &
    ZP_PET_A_COEF,  &
    ZP_PET_B_COEF,  &
    ZP_PEW_A_COEF,  &
    ZP_PEW_B_COEF,  &
    ZP_PS,          &
    ZP_PSN3L,       &
    ZP_QA,          &
    ZP_QS,          &
    ZP_RHOA,        &
    ZP_RI,          &
    ZP_RNSNOW,      &
    ZP_RRSNOW,      &
    ZP_SNDRIFT,     &
    ZP_SNOWALB,     &
    ZP_SNOWHMASS,   &
    ZP_SNOWSFCH,    &
    ZP_SOILCOND,    &
    ZP_SOILCOR,     &
    ZP_SRSNOW,      &
    ZP_SW_RAD,      &
    ZP_SWNETSNOW,   &
    ZP_SWNETSNOWS,  &
    ZP_TA,          &
    ZP_TG,          &
    ZP_THRUFAL,     &
    ZP_UREF,        &
    ZP_USTARSNOW,   &
    ZP_VEGTYPE,     & ! Fraction of permanent snow
    ZP_VMOD,        &
    ZP_Z0EFF,       &
    ZP_Z0HNAT,      &
    ZP_Z0NAT,       &
    ZP_ZENITH,      &
    ZP_ZREF


  REAL, DIMENSION(KSIZE_SNOW, THIS%NUM_LAYERS) :: &
    ZP_SNOWAGE,     &
    ZP_SNOWDZ,      &
    ZP_SNOWGRAN1,   &
    ZP_SNOWGRAN2,   &
    ZP_SNOWHEAT,    &
    ZP_SNOWHIST,    &
    ZP_SNOWLIQ,     &
    ZP_SNOWRHO,     &
    ZP_SNOWSWE,     &
    ZP_SNOWTEMP


END SUBROUTINE RUN_INTERNAL

SUBROUTINE POST_RUN(THIS, FORC, PTSTEP, PSNOWH, PSNOWSWE_1D)
IMPLICIT NONE
  CLASS(SICE_SNOW_t) :: THIS
  TYPE(SEA_ICE_FORCING_t), INTENT(IN) :: FORC
  REAL, INTENT(IN) :: PTSTEP
  REAL, INTENT(IN) :: PSNOWH(FORC%KSIZE)
  REAL, INTENT(IN) :: PSNOWSWE_1D(FORC%KSIZE)

  INTEGER :: JJ, JWRK
  INTEGER :: M
  REAL, DIMENSION(FORC%KSIZE) :: &
    ZSNOWD, &
    ZSNOWABLAT_DELTA, &
    PEVAP
  LOGICAL :: LREMOVE_SNOW(FORC%KSIZE)

END SUBROUTINE POST_RUN

SUBROUTINE SAFETY_GUARD(THIS)
IMPLICIT NONE
  CLASS(SICE_SNOW_t), INTENT(IN) :: THIS

  REAL, PARAMETER :: ZCHECK_TEMP = 50.0
  INTEGER :: JWRK, JJ
END SUBROUTINE SAFETY_GUARD

FUNCTION EXISTS(THIS) RESULT (RES)
IMPLICIT NONE
  CLASS(SICE_SNOW_t), INTENT(IN) :: THIS
  LOGICAL :: RES(THIS%NUM_POINTS)

  INTEGER :: JJ, JWRK
  REAL :: ZSNOWD(THIS%NUM_POINTS)
END FUNCTION EXISTS

SUBROUTINE DEALLOC(THIS)
IMPLICIT NONE
  CLASS(SICE_SNOW_t) :: THIS
END SUBROUTINE DEALLOC

SUBROUTINE GET_RESPONSE(THIS, M, RESPONSE, PTSUR, PALB, PDEPTH)
IMPLICIT NONE
  CLASS(SICE_SNOW_t) :: THIS
  INTEGER, INTENT(IN) :: M
  TYPE(SNOW_RESPONSE_t), INTENT(OUT), OPTIONAL :: RESPONSE
  REAL, INTENT(OUT), OPTIONAL :: PTSUR(M)
  REAL, INTENT(OUT), OPTIONAL :: PALB(M)
  REAL, INTENT(OUT), OPTIONAL :: PDEPTH(M) !< Total snow thickness
END SUBROUTINE GET_RESPONSE

SUBROUTINE ALLOCA(THIS)
IMPLICIT NONE
  CLASS(SICE_SNOW_t) :: THIS
END SUBROUTINE ALLOCA

SUBROUTINE GET_MODEL_FIELDS( THIS, MF )
IMPLICIT NONE
  CLASS(SICE_SNOW_t), INTENT(IN) :: THIS
  TYPE( MODEL_FIELD ), ALLOCATABLE, INTENT( OUT ) :: MF(:)

  INTEGER, PARAMETER :: NUM_FIELDS = 12

END SUBROUTINE GET_MODEL_FIELDS
END MODULE MODE_SEAICE_SICE_SNOW


