MODULE ACPY_MOD

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8

INTERFACE ACPY
  MODULE PROCEDURE ACPY_R8_1D
  MODULE PROCEDURE ACPY_R8_2D
END INTERFACE

PRIVATE

PUBLIC :: ACPY

CONTAINS

SUBROUTINE ACPY_R8_1D (JLON, PL, PR) 

!$acc routine (ACPY_R8_1D) seq

REAL (KIND=JPRB) :: PL (:,:), PR (:,:)
INTEGER (KIND=JPIM) :: JLON

PL (JLON, :) = PR (JLON, :)

END SUBROUTINE

SUBROUTINE ACPY_R8_2D (JLON, PL, PR) 

!$acc routine (ACPY_R8_2D) seq

REAL (KIND=JPRB) :: PL (:,:,:), PR (:,:,:)
INTEGER (KIND=JPIM) :: JLON

PL (JLON, :, :) = PR (JLON, :, :)

END SUBROUTINE

END MODULE

