PROGRAM MAIN_ACPY

USE NVTX
USE ACPY_MOD

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8

INTEGER :: NPROMA, KLEV, NGPBLKS, KSPPN2D
REAL(KIND=JPRB), POINTER  :: PSTRCU(:,:,:)
REAL(KIND=JPRB), POINTER  :: PSTRCV(:,:,:)

INTEGER :: JLON, JBLK, ITIME
INTEGER :: NPROMA, NGPBLKS

NPROMA = 32
KLEV = 105
NGPBLKS = 1
KSPPN2D = 0

ALLOCATE (PSTRCU(NPROMA,KLEV+1,NGPBLKS))
ALLOCATE (PSTRCV(NPROMA,KLEV+1,NGPBLKS))

WRITE (0, *) " NPROMA = ", NPROMA, " NGPBLKS = ", NGPBLKS, " KLEV = ", KLEV


!$ACC ENTER DATA CREATE (PSTRCU, PSTRCV)

DO ITIME = 1, 2

CALL NVTXSTARTRANGE ("ACPY")

!$ACC PARALLEL LOOP GANG PRIVATE (JBLK) VECTOR_LENGTH (NPROMA)

DO JBLK = 1, NGPBLKS

!$ACC LOOP VECTOR PRIVATE (JLON)

  DO JLON = 1, NPROMA

    CALL ACPY (JLON, PSTRCU (:,:, JBLK), PSTRCV (:,:, JBLK))

  ENDDO

!$ACC END LOOP

ENDDO

!$ACC END PARALLEL LOOP

CALL NVTXENDRANGE

ENDDO

END
