INTERFACE

SUBROUTINE ACPBL_WIND(YDCST,YDPHY2,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
& PAPHI,PAPHIF,PU,PV,&
& PCLPH,&
& KCLPH,PVEIN,PUGST,PVGST)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMCST   , ONLY : TCST
USE YOMPHY2  , ONLY : TPHY2
IMPLICIT NONE
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TPHY2),INTENT(IN) :: YDPHY2
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB)   ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN) :: PCLPH(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCLPH(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT) :: PVEIN(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT) :: PUGST(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT) :: PVGST(KLON)
END SUBROUTINE ACPBL_WIND


SUBROUTINE ACPBL_WIND_OPENACC (YDCST, YDPHY2, KIDIA, KFDIA, KLON, KTDIA, KLEV&
&, PAPHI, PAPHIF, PU, PV, PCLPH, KCLPH, PVEIN, PUGST, PVGST, YDSTACK)
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMCST,ONLY:TCST
USE YOMPHY2,ONLY:TPHY2
USE FXTRAN_ACDC_STACK_MOD
USE FXTRAN_ACDC_ABORT_MOD
IMPLICIT NONE
!$ACC ROUTINE (ACPBL_WIND_OPENACC) SEQ
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TPHY2), INTENT (IN)::YDPHY2
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KTDIA
REAL (KIND=JPRB), INTENT (IN)::PAPHI (KLON, 0:KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPHIF (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PCLPH (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCLPH (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PVEIN (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PUGST (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PVGST (KLON)
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK

END SUBROUTINE ACPBL_WIND_OPENACC






END INTERFACE
