INTERFACE
SUBROUTINE APL_ARPEGE_INIT (YDCST, YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS,  &
& YDMF_PHYS_SURF, YDVARS, YDGEOMVARS, YDMODEL, KMOC_CLPH, KNLAB_CVPP, PAER, PAERINDS, PAIPCMT, PALBD,    &
& PALBP, PALPHA1, PCEMTR, PCFATH, PCFAU, PCFBTH, PCFBU, PCFBV, PCOEFA, PCONDCVPPI, PCONDCVPPL, PCTRSO,   &
& PDECRD, PDIFCVPPQ, PDIFCVPPS, PDIFCVPPU, PDIFCVPPV, PDIFWQ, PDIFWS, PEDMFQ, PEDMFS, PEDMFU, PEDMFV,    &
& PEPS0, PEPSNEB, PFPCOR, PKQLROV, PKQROV, PKTROV, PKUROV, PLVT, PMF_UP, PMRIPP, PNEBC0, PNEBCH,         &
& PNEBDIFF, PNEBS, PNEBS0, PNEB_CVPP, PPFL_FPLCH, PPFL_FPLSH, PPOID, PPRODTH_CVPP, PQC_DET_PCMT, PQI,    &
& PQIC, PQICE, PQL, PQLC, PQLIS, PQLIS0, PQLI_CVP, PQLI_CVPP, PQO3, PQR, PQS, PQV, PSC_FCLL,             &
& PSC_FCLN, PSC_FEVI, PSC_FEVN, PSEDIQI, PSEDIQL, PSFSWDIF, PSFSWDIR, PSUDU, PTENHA, PTENQVA, PTENT,     &
& PTRSOD, PTRSODIF, PTRSODIR, PUNEBH, PXDROV, PXHROV, PXQRO, PXTRO, PXTROV, PXURO, PXUROV)
USE PARKIND1, ONLY : JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD &
                       , ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE YOMGEOMVARS,            ONLY : TGEOMVARS
USE TYPE_MODEL         , ONLY : MODEL
USE YOMCST,              ONLY : TCST
IMPLICIT NONE
TYPE(TCST)                    ,INTENT(IN)     :: YDCST
TYPE(MF_PHYS_BASE_STATE_TYPE) ,INTENT(IN)     :: YDMF_PHYS_BASE_STATE
TYPE(CPG_BNDS_TYPE)           ,INTENT(IN)     :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)           ,INTENT(IN)     :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE)           ,INTENT(INOUT)  :: YDCPG_MISC
TYPE(MF_PHYS_TYPE)            ,INTENT(INOUT)  :: YDMF_PHYS
TYPE(MF_PHYS_SURF_TYPE)       ,INTENT(INOUT)  :: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES)         ,INTENT(INOUT)  :: YDVARS
TYPE(TGEOMVARS)               ,INTENT(IN)     :: YDGEOMVARS
TYPE(MODEL)                   ,INTENT(IN)     :: YDMODEL
INTEGER(KIND=JPIM)            ,INTENT(OUT)    :: KMOC_CLPH(YDCPG_OPTS%KLON)
INTEGER(KIND=JPIM)            ,INTENT(OUT)    :: KNLAB_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PAER(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,6)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PAERINDS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PAIPCMT(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PALBD(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PALBP(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PALPHA1(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCEMTR(YDCPG_OPTS%KLON,0:1)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFATH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFAU(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFBTH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFBU(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFBV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCOEFA(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCONDCVPPI(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCONDCVPPL(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCTRSO(YDCPG_OPTS%KLON,0:1)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDECRD(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDIFCVPPQ(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDIFCVPPS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDIFCVPPU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDIFCVPPV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDIFWQ(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDIFWS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PEDMFQ(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PEDMFS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PEDMFU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PEDMFV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PEPS0
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PEPSNEB
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PFPCOR(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PKQLROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PKQROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PKTROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PKUROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PLVT(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PMF_UP(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PMRIPP(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PNEBC0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PNEBCH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PNEBDIFF(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PNEBS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PNEBS0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PNEB_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PPFL_FPLCH(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PPFL_FPLSH(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PPOID(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PPRODTH_CVPP(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQC_DET_PCMT(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQI(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQIC(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQICE(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQL(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQLC(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQLIS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQLIS0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQLI_CVP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQLI_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQO3(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQR(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSC_FCLL(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSC_FCLN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSC_FEVI(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSC_FEVN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSEDIQI(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSEDIQL(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSFSWDIF(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSFSWDIR(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSUDU(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PTENHA(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PTENQVA(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PTENT(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PTRSOD(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PTRSODIF(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PTRSODIR(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PUNEBH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PXDROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PXHROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PXQRO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PXTRO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PXTROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PXURO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PXUROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
END SUBROUTINE APL_ARPEGE_INIT




SUBROUTINE APL_ARPEGE_INIT_PARALLEL (YDCST, YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC&
&, YDMF_PHYS, YDMF_PHYS_SURF, YDVARS, YDGEOMVARS, YDMODEL, YD_KMOC_CLPH, YD_KNLAB_CVPP, YD_PAER,&
& YD_PAERINDS, YD_PAIPCMT, YD_PALBD, YD_PALBP, YD_PALPHA1, YD_PCEMTR, YD_PCFATH, YD_PCFAU, YD_PCFBTH&
&, YD_PCFBU, YD_PCFBV, YD_PCOEFA, YD_PCONDCVPPI, YD_PCONDCVPPL, YD_PCTRSO, YD_PDECRD, YD_PDIFCVPPQ&
&, YD_PDIFCVPPS, YD_PDIFCVPPU, YD_PDIFCVPPV, YD_PDIFWQ, YD_PDIFWS, YD_PEDMFQ, YD_PEDMFS, YD_PEDMFU&
&, YD_PEDMFV, PEPS0, PEPSNEB, YD_PFPCOR, YD_PKQLROV, YD_PKQROV, YD_PKTROV, YD_PKUROV, YD_PLVT, YD_PMF_UP&
&, YD_PMRIPP, YD_PNEBC0, YD_PNEBCH, YD_PNEBDIFF, YD_PNEBS, YD_PNEBS0, YD_PNEB_CVPP, YD_PPFL_FPLCH&
&, YD_PPFL_FPLSH, YD_PPOID, YD_PPRODTH_CVPP, YD_PQC_DET_PCMT, YD_PQI, YD_PQIC, YD_PQICE, YD_PQL,&
& YD_PQLC, YD_PQLIS, YD_PQLIS0, YD_PQLI_CVP, YD_PQLI_CVPP, YD_PQO3, YD_PQR, YD_PQS, YD_PQV, YD_PSC_FCLL&
&, YD_PSC_FCLN, YD_PSC_FEVI, YD_PSC_FEVN, YD_PSEDIQI, YD_PSEDIQL, YD_PSFSWDIF, YD_PSFSWDIR, YD_PSUDU&
&, YD_PTENHA, YD_PTENQVA, YD_PTENT, YD_PTRSOD, YD_PTRSODIF, YD_PTRSODIR, YD_PUNEBH, YD_PXDROV, YD_PXHROV&
&, YD_PXQRO, YD_PXTRO, YD_PXTROV, YD_PXURO, YD_PXUROV)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMGEOMVARS,ONLY:TGEOMVARS
USE TYPE_MODEL,ONLY:MODEL
USE YOMCST,ONLY:TCST
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (TGEOMVARS), INTENT (IN)::YDGEOMVARS
TYPE (MODEL), INTENT (IN)::YDMODEL
CLASS (FIELD_2IM), POINTER :: YD_KMOC_CLPH
CLASS (FIELD_3IM), POINTER :: YD_KNLAB_CVPP
CLASS (FIELD_4RB), POINTER :: YD_PAER
CLASS (FIELD_3RB), POINTER :: YD_PAERINDS
CLASS (FIELD_2RB), POINTER :: YD_PAIPCMT
CLASS (FIELD_3RB), POINTER :: YD_PALBD
CLASS (FIELD_3RB), POINTER :: YD_PALBP
CLASS (FIELD_3RB), POINTER :: YD_PALPHA1
CLASS (FIELD_3RB), POINTER :: YD_PCEMTR
CLASS (FIELD_3RB), POINTER :: YD_PCFATH
CLASS (FIELD_3RB), POINTER :: YD_PCFAU
CLASS (FIELD_3RB), POINTER :: YD_PCFBTH
CLASS (FIELD_3RB), POINTER :: YD_PCFBU
CLASS (FIELD_3RB), POINTER :: YD_PCFBV
CLASS (FIELD_3RB), POINTER :: YD_PCOEFA
CLASS (FIELD_3RB), POINTER :: YD_PCONDCVPPI
CLASS (FIELD_3RB), POINTER :: YD_PCONDCVPPL
CLASS (FIELD_3RB), POINTER :: YD_PCTRSO
CLASS (FIELD_2RB), POINTER :: YD_PDECRD
CLASS (FIELD_3RB), POINTER :: YD_PDIFCVPPQ
CLASS (FIELD_3RB), POINTER :: YD_PDIFCVPPS
CLASS (FIELD_3RB), POINTER :: YD_PDIFCVPPU
CLASS (FIELD_3RB), POINTER :: YD_PDIFCVPPV
CLASS (FIELD_2RB), POINTER :: YD_PDIFWQ
CLASS (FIELD_2RB), POINTER :: YD_PDIFWS
CLASS (FIELD_3RB), POINTER :: YD_PEDMFQ
CLASS (FIELD_3RB), POINTER :: YD_PEDMFS
CLASS (FIELD_3RB), POINTER :: YD_PEDMFU
CLASS (FIELD_3RB), POINTER :: YD_PEDMFV
REAL (KIND=JPRB), INTENT (OUT)::PEPS0
REAL (KIND=JPRB), INTENT (OUT)::PEPSNEB
CLASS (FIELD_3RB), POINTER :: YD_PFPCOR
CLASS (FIELD_3RB), POINTER :: YD_PKQLROV
CLASS (FIELD_3RB), POINTER :: YD_PKQROV
CLASS (FIELD_3RB), POINTER :: YD_PKTROV
CLASS (FIELD_3RB), POINTER :: YD_PKUROV
CLASS (FIELD_3RB), POINTER :: YD_PLVT
CLASS (FIELD_3RB), POINTER :: YD_PMF_UP
CLASS (FIELD_3RB), POINTER :: YD_PMRIPP
CLASS (FIELD_3RB), POINTER :: YD_PNEBC0
CLASS (FIELD_3RB), POINTER :: YD_PNEBCH
CLASS (FIELD_3RB), POINTER :: YD_PNEBDIFF
CLASS (FIELD_3RB), POINTER :: YD_PNEBS
CLASS (FIELD_3RB), POINTER :: YD_PNEBS0
CLASS (FIELD_3RB), POINTER :: YD_PNEB_CVPP
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FPLCH
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FPLSH
CLASS (FIELD_3RB), POINTER :: YD_PPOID
CLASS (FIELD_3RB), POINTER :: YD_PPRODTH_CVPP
CLASS (FIELD_3RB), POINTER :: YD_PQC_DET_PCMT
CLASS (FIELD_3RB), POINTER :: YD_PQI
CLASS (FIELD_3RB), POINTER :: YD_PQIC
CLASS (FIELD_3RB), POINTER :: YD_PQICE
CLASS (FIELD_3RB), POINTER :: YD_PQL
CLASS (FIELD_3RB), POINTER :: YD_PQLC
CLASS (FIELD_3RB), POINTER :: YD_PQLIS
CLASS (FIELD_3RB), POINTER :: YD_PQLIS0
CLASS (FIELD_3RB), POINTER :: YD_PQLI_CVP
CLASS (FIELD_3RB), POINTER :: YD_PQLI_CVPP
CLASS (FIELD_3RB), POINTER :: YD_PQO3
CLASS (FIELD_3RB), POINTER :: YD_PQR
CLASS (FIELD_3RB), POINTER :: YD_PQS
CLASS (FIELD_3RB), POINTER :: YD_PQV
CLASS (FIELD_2RB), POINTER :: YD_PSC_FCLL
CLASS (FIELD_2RB), POINTER :: YD_PSC_FCLN
CLASS (FIELD_2RB), POINTER :: YD_PSC_FEVI
CLASS (FIELD_2RB), POINTER :: YD_PSC_FEVN
CLASS (FIELD_3RB), POINTER :: YD_PSEDIQI
CLASS (FIELD_3RB), POINTER :: YD_PSEDIQL
CLASS (FIELD_3RB), POINTER :: YD_PSFSWDIF
CLASS (FIELD_3RB), POINTER :: YD_PSFSWDIR
CLASS (FIELD_2RB), POINTER :: YD_PSUDU
CLASS (FIELD_3RB), POINTER :: YD_PTENHA
CLASS (FIELD_3RB), POINTER :: YD_PTENQVA
CLASS (FIELD_3RB), POINTER :: YD_PTENT
CLASS (FIELD_2RB), POINTER :: YD_PTRSOD
CLASS (FIELD_3RB), POINTER :: YD_PTRSODIF
CLASS (FIELD_3RB), POINTER :: YD_PTRSODIR
CLASS (FIELD_3RB), POINTER :: YD_PUNEBH
CLASS (FIELD_2RB), POINTER :: YD_PXDROV
CLASS (FIELD_2RB), POINTER :: YD_PXHROV
CLASS (FIELD_3RB), POINTER :: YD_PXQRO
CLASS (FIELD_3RB), POINTER :: YD_PXTRO
CLASS (FIELD_3RB), POINTER :: YD_PXTROV
CLASS (FIELD_3RB), POINTER :: YD_PXURO
CLASS (FIELD_3RB), POINTER :: YD_PXUROV

END SUBROUTINE APL_ARPEGE_INIT_PARALLEL




END INTERFACE
