INTERFACE
SUBROUTINE APL_ARPEGE_RADIATION (YDMF_PHYS_BASE_STATE, YDCFU, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS,      &
& YDCPG_MISC, YDGPAR, YDMF_PHYS, YDTRC, YDRADF, YDMF_PHYS_SURF, YDVARS, YDGEOMVARS, YDMODEL, PCLCT_RAD, PALBDIR, PDECRD, PAER,&
& PAERINDS, PALBD, PALBP, PQCO2, PCEMTR, PCTRSO, PFLU_EMIS, PFLU_QSAT, PQO3, PQR, PQS, PQV, PRDG_MU0,  &
& PRDG_SOLO, PRDG_MU0LU, PRDG_MU0M, PSFSWDIF, PSFSWDIR, PSUDU, PTENT, PTRSOD, PTRSODIF, PTRSODIR)
USE PARKIND1, ONLY : JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE
USE YOMGPAR            , ONLY : TGPAR
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD &
                       , ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE YOMGEOMVARS,            ONLY : TGEOMVARS
USE TYPE_MODEL         , ONLY : MODEL
USE YOMCFU             , ONLY : TCFU
USE YOMTRC             , ONLY : TTRC
USE YOMRADF            , ONLY : TRADF
IMPLICIT NONE
TYPE(MF_PHYS_BASE_STATE_TYPE) ,INTENT(IN)     :: YDMF_PHYS_BASE_STATE
TYPE(TCFU)                    ,INTENT(IN)     :: YDCFU
TYPE(GEOMETRY)                ,INTENT(IN)     :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE)           ,INTENT(IN)     :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)           ,INTENT(IN)     :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE)           ,INTENT(INOUT)  :: YDCPG_MISC
TYPE(TGPAR)                   ,INTENT(INOUT)  :: YDGPAR
TYPE(MF_PHYS_TYPE)            ,INTENT(INOUT)  :: YDMF_PHYS
TYPE(TRADF)                   ,INTENT(INOUT)  :: YDRADF
TYPE(TTRC)                    ,INTENT(INOUT)  :: YDTRC
TYPE(MF_PHYS_SURF_TYPE)       ,INTENT(INOUT)  :: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES)         ,INTENT(INOUT)  :: YDVARS
TYPE(TGEOMVARS)               ,INTENT(IN)     :: YDGEOMVARS
TYPE(MODEL)                   ,INTENT(IN)     :: YDMODEL
REAL(KIND=JPRB)               ,INTENT(IN)     :: PCLCT_RAD(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PALBDIR(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PDECRD(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PAER(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,6)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PAERINDS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PALBD(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PALBP(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQCO2(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCEMTR(YDCPG_OPTS%KLON,0:1)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCTRSO(YDCPG_OPTS%KLON,0:1)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PFLU_EMIS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PFLU_QSAT(YDCPG_OPTS%KLON,1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQO3(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQR(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PRDG_MU0(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PRDG_SOLO(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PRDG_MU0LU(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PRDG_MU0M(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSFSWDIF(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSFSWDIR(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PSUDU(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PTENT(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PTRSOD(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PTRSODIF(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PTRSODIR(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
END SUBROUTINE APL_ARPEGE_RADIATION




SUBROUTINE APL_ARPEGE_RADIATION_PARALLEL (YDMF_PHYS_BASE_STATE, YDCFU, YDGEOMETRY, YDCPG_BNDS&
&, YDCPG_OPTS, YDCPG_MISC, YDGPAR, YDMF_PHYS, YDTRC, YDRADF, YDMF_PHYS_SURF, YDVARS, YDGEOMVARS&
&, YDMODEL, YD_PCLCT_RAD, YD_PALBDIR, YD_PDECRD, YD_PAER, YD_PAERINDS, YD_PALBD, YD_PALBP&
&, YD_PQCO2, YD_PCEMTR, YD_PCTRSO, YD_PFLU_EMIS, YD_PFLU_QSAT, YD_PQO3, YD_PQR, YD_PQS&
&, YD_PQV, YD_PRDG_MU0, YD_PRDG_SOLO, YD_PRDG_MU0LU, YD_PRDG_MU0M, YD_PSFSWDIF, YD_PSFSWDIR&
&, YD_PSUDU, YD_PTENT, YD_PTRSOD, YD_PTRSODIF, YD_PTRSODIR)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE
USE YOMGPAR,ONLY:TGPAR
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMGEOMVARS,ONLY:TGEOMVARS
USE TYPE_MODEL,ONLY:MODEL
USE YOMCFU,ONLY:TCFU
USE YOMTRC,ONLY:TTRC
USE YOMRADF,ONLY:TRADF
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (TCFU), INTENT (IN)::YDCFU
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (TGPAR), INTENT (INOUT)::YDGPAR
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (TRADF), INTENT (INOUT)::YDRADF
TYPE (TTRC), INTENT (INOUT)::YDTRC
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (TGEOMVARS), INTENT (IN)::YDGEOMVARS
TYPE (MODEL), INTENT (IN)::YDMODEL
CLASS (FIELD_2RB), POINTER :: YD_PCLCT_RAD
CLASS (FIELD_2RB), POINTER :: YD_PALBDIR
CLASS (FIELD_2RB), POINTER :: YD_PDECRD
CLASS (FIELD_4RB), POINTER :: YD_PAER
CLASS (FIELD_3RB), POINTER :: YD_PAERINDS
CLASS (FIELD_3RB), POINTER :: YD_PALBD
CLASS (FIELD_3RB), POINTER :: YD_PALBP
CLASS (FIELD_3RB), POINTER :: YD_PQCO2
CLASS (FIELD_3RB), POINTER :: YD_PCEMTR
CLASS (FIELD_3RB), POINTER :: YD_PCTRSO
CLASS (FIELD_2RB), POINTER :: YD_PFLU_EMIS
CLASS (FIELD_3RB), POINTER :: YD_PFLU_QSAT
CLASS (FIELD_3RB), POINTER :: YD_PQO3
CLASS (FIELD_3RB), POINTER :: YD_PQR
CLASS (FIELD_3RB), POINTER :: YD_PQS
CLASS (FIELD_3RB), POINTER :: YD_PQV
CLASS (FIELD_2RB), POINTER :: YD_PRDG_MU0
CLASS (FIELD_2RB), POINTER :: YD_PRDG_SOLO
CLASS (FIELD_2RB), POINTER :: YD_PRDG_MU0LU
CLASS (FIELD_2RB), POINTER :: YD_PRDG_MU0M
CLASS (FIELD_3RB), POINTER :: YD_PSFSWDIF
CLASS (FIELD_3RB), POINTER :: YD_PSFSWDIR
CLASS (FIELD_2RB), POINTER :: YD_PSUDU
CLASS (FIELD_3RB), POINTER :: YD_PTENT
CLASS (FIELD_2RB), POINTER :: YD_PTRSOD
CLASS (FIELD_3RB), POINTER :: YD_PTRSODIF
CLASS (FIELD_3RB), POINTER :: YD_PTRSODIR

END SUBROUTINE APL_ARPEGE_RADIATION_PARALLEL




END INTERFACE
