INTERFACE
SUBROUTINE APL_ARPEGE_SHALLOW_CONVECTION_AND_TURBULENCE (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, &
& YDCPG_MISC, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, YDDDH, KNLAB_CVPP, PCDROV, PCHROV, PCOEFN,           &
& PCONDCVPPI, PCONDCVPPL, PDIFCVPPQ, PDIFCVPPS, PEPS, PFLU_CD, PFLU_CH, PKQLROV, PKQROV, PKTROV,       &
& PKUROV, PKUROV2,PMSC_LSCPE, PNBVNO, PNEBS, PNEBS0, PNEB_CVPP, PPFL_FPLCH, PPFL_FTKE, PPFL_FTKEI,     &
& PPRODTH_CVPP, PQI, PQIC, PQL, PQLC, PQLIS, PQLIS0, PQLI_CVPP, PQV, PQR, PQS, PTKE1, PXTROV, PXUROV,  &
& PUSLE, PKCLS, PECTCLS, PPRODTH, PEDMFQ, PEDMFS, PEDMFU, PEDMFV, PMF_UP)
USE PARKIND1, ONLY : JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE TYPE_MODEL         , ONLY : MODEL
USE DDH_MIX            , ONLY : TYP_DDH
USE MF_PHYS_SURFACE_TYPE_MOD  &
                       , ONLY : MF_PHYS_SURF_TYPE
IMPLICIT NONE
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT(IN)    :: YDMF_PHYS_BASE_STATE
TYPE(CPG_BNDS_TYPE),            INTENT(IN)    :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),            INTENT(IN)    :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE),            INTENT(INOUT) :: YDCPG_MISC
TYPE(MF_PHYS_TYPE),             INTENT(INOUT) :: YDMF_PHYS
TYPE(MF_PHYS_SURF_TYPE),        INTENT(IN)    :: YDMF_PHYS_SURF
TYPE(MODEL),                    INTENT(IN)    :: YDMODEL
TYPE(TYP_DDH),                  INTENT(INOUT) :: YDDDH
INTEGER(KIND=JPIM),             INTENT(OUT)   :: KNLAB_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PCDROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PCHROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PCOEFN(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PCONDCVPPI(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PCONDCVPPL(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PDIFCVPPQ(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PDIFCVPPS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PEPS
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_CD (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_CH (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PKQLROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PKQROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PKTROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PKUROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PKUROV2(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PMSC_LSCPE (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PNBVNO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PNEBS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PNEBS0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PNEB_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PPFL_FPLCH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PPFL_FTKE (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PPFL_FTKEI (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PPRODTH_CVPP(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQI(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQIC(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQL(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQLC(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PQLIS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PQLIS0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(INOUT) :: PQLI_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQR(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PQS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PTKE1(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PXTROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PXUROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PUSLE(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PKCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PECTCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(OUT)   :: PPRODTH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PEDMFQ(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PEDMFS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PEDMFU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PEDMFV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(OUT)   :: PMF_UP(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
END SUBROUTINE APL_ARPEGE_SHALLOW_CONVECTION_AND_TURBULENCE




SUBROUTINE APL_ARPEGE_SHALLOW_CONVECTION_AND_TURBULENCE_PARALLEL (YDMF_PHYS_BASE_STATE, YDCPG_BNDS&
&, YDCPG_OPTS, YDCPG_MISC, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, YDDDH, YD_KNLAB_CVPP, YD_PCDROV&
&, YD_PCHROV, YD_PCOEFN, YD_PCONDCVPPI, YD_PCONDCVPPL, YD_PDIFCVPPQ, YD_PDIFCVPPS, PEPS, YD_PFLU_CD&
&, YD_PFLU_CH, YD_PKQLROV, YD_PKQROV, YD_PKTROV, YD_PKUROV, YD_PKUROV2, YD_PMSC_LSCPE, YD_PNBVNO&
&, YD_PNEBS, YD_PNEBS0, YD_PNEB_CVPP, YD_PPFL_FPLCH, YD_PPFL_FTKE, YD_PPFL_FTKEI, YD_PPRODTH_CVPP&
&, YD_PQI, YD_PQIC, YD_PQL, YD_PQLC, YD_PQLIS, YD_PQLIS0, YD_PQLI_CVPP, YD_PQV, YD_PQR, YD_PQS&
&, YD_PTKE1, YD_PXTROV, YD_PXUROV, YD_PUSLE, YD_PKCLS, YD_PECTCLS, YD_PPRODTH, YD_PEDMFQ, YD_PEDMFS&
&, YD_PEDMFU, YD_PEDMFV, YD_PMF_UP)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE DDH_MIX,ONLY:TYP_DDH
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_SURF_TYPE), INTENT (IN)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (TYP_DDH), INTENT (INOUT)::YDDDH
CLASS (FIELD_3IM), POINTER :: YD_KNLAB_CVPP
CLASS (FIELD_2RB), POINTER :: YD_PCDROV
CLASS (FIELD_2RB), POINTER :: YD_PCHROV
CLASS (FIELD_3RB), POINTER :: YD_PCOEFN
CLASS (FIELD_3RB), POINTER :: YD_PCONDCVPPI
CLASS (FIELD_3RB), POINTER :: YD_PCONDCVPPL
CLASS (FIELD_3RB), POINTER :: YD_PDIFCVPPQ
CLASS (FIELD_3RB), POINTER :: YD_PDIFCVPPS
REAL (KIND=JPRB), INTENT (IN)::PEPS
CLASS (FIELD_2RB), POINTER :: YD_PFLU_CD
CLASS (FIELD_2RB), POINTER :: YD_PFLU_CH
CLASS (FIELD_3RB), POINTER :: YD_PKQLROV
CLASS (FIELD_3RB), POINTER :: YD_PKQROV
CLASS (FIELD_3RB), POINTER :: YD_PKTROV
CLASS (FIELD_3RB), POINTER :: YD_PKUROV
CLASS (FIELD_3RB), POINTER :: YD_PKUROV2
CLASS (FIELD_3RB), POINTER :: YD_PMSC_LSCPE
CLASS (FIELD_3RB), POINTER :: YD_PNBVNO
CLASS (FIELD_3RB), POINTER :: YD_PNEBS
CLASS (FIELD_3RB), POINTER :: YD_PNEBS0
CLASS (FIELD_3RB), POINTER :: YD_PNEB_CVPP
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FPLCH
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FTKE
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FTKEI
CLASS (FIELD_3RB), POINTER :: YD_PPRODTH_CVPP
CLASS (FIELD_3RB), POINTER :: YD_PQI
CLASS (FIELD_3RB), POINTER :: YD_PQIC
CLASS (FIELD_3RB), POINTER :: YD_PQL
CLASS (FIELD_3RB), POINTER :: YD_PQLC
CLASS (FIELD_3RB), POINTER :: YD_PQLIS
CLASS (FIELD_3RB), POINTER :: YD_PQLIS0
CLASS (FIELD_3RB), POINTER :: YD_PQLI_CVPP
CLASS (FIELD_3RB), POINTER :: YD_PQV
CLASS (FIELD_3RB), POINTER :: YD_PQR
CLASS (FIELD_3RB), POINTER :: YD_PQS
CLASS (FIELD_3RB), POINTER :: YD_PTKE1
CLASS (FIELD_3RB), POINTER :: YD_PXTROV
CLASS (FIELD_3RB), POINTER :: YD_PXUROV
CLASS (FIELD_3RB), POINTER :: YD_PUSLE
CLASS (FIELD_2RB), POINTER :: YD_PKCLS
CLASS (FIELD_2RB), POINTER :: YD_PECTCLS
CLASS (FIELD_3RB), POINTER :: YD_PPRODTH
CLASS (FIELD_3RB), POINTER :: YD_PEDMFQ
CLASS (FIELD_3RB), POINTER :: YD_PEDMFS
CLASS (FIELD_3RB), POINTER :: YD_PEDMFU
CLASS (FIELD_3RB), POINTER :: YD_PEDMFV
CLASS (FIELD_3RB), POINTER :: YD_PMF_UP

END SUBROUTINE APL_ARPEGE_SHALLOW_CONVECTION_AND_TURBULENCE_PARALLEL




END INTERFACE
