INTERFACE
SUBROUTINE APL_ARPEGE(YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS,  &
& YDCPG_MISC, YDGPAR, YDCPG_PHY0, YDMF_PHYS, YDTRC, YDRADF, YDCPG_DYN0, YDMF_PHYS_SURF, YDCPG_SL2, YDVARS, YDGEOMVARS, YDCFU,&
& YDXFU, YDMODEL, YDDDH, YDPHYSMWAVE)
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE, CPG_DYN_TYPE, &
& CPG_PHY_TYPE
USE YOMGPAR            , ONLY : TGPAR
USE CPG_SL2_TYPE_MOD   , ONLY : CPG_SL2_TYPE
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD  &
& , ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE YOMGEOMVARS,         ONLY : TGEOMVARS
USE MF_PHYS_BASE_STATE_TYPE_MOD &
& , ONLY : MF_PHYS_BASE_STATE_TYPE
USE MF_PHYS_NEXT_STATE_TYPE_MOD &
& , ONLY : MF_PHYS_NEXT_STATE_TYPE
USE TYPE_MODEL         , ONLY : MODEL
USE DDH_MIX            , ONLY : TYP_DDH
USE YOE_PHYS_MWAVE     , ONLY : TEPHYSMWAVE
USE YOMCFU             , ONLY : TCFU
USE YOMXFU             , ONLY : TXFU
USE YOMTRC             , ONLY : TTRC
USE YOMRADF            , ONLY : TRADF
IMPLICIT NONE
TYPE(MF_PHYS_BASE_STATE_TYPE) ,INTENT(IN)     :: YDMF_PHYS_BASE_STATE
TYPE(MF_PHYS_NEXT_STATE_TYPE) ,INTENT(INOUT)  :: YDMF_PHYS_NEXT_STATE
TYPE(GEOMETRY)                ,INTENT(IN)     :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE)           ,INTENT(IN)     :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)           ,INTENT(IN)     :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE)           ,INTENT(INOUT)  :: YDCPG_MISC
TYPE(TGPAR)                   ,INTENT(INOUT)  :: YDGPAR
TYPE(CPG_PHY_TYPE)            ,INTENT(IN)     :: YDCPG_PHY0
TYPE(MF_PHYS_TYPE)            ,INTENT(INOUT)  :: YDMF_PHYS
TYPE(TTRC)                    ,INTENT(INOUT)  :: YDTRC
TYPE(TRADF)                   ,INTENT(INOUT)  :: YDRADF
TYPE(CPG_DYN_TYPE)            ,INTENT(IN)     :: YDCPG_DYN0
TYPE(MF_PHYS_SURF_TYPE)       ,INTENT(INOUT)  :: YDMF_PHYS_SURF
TYPE(CPG_SL2_TYPE)            ,INTENT(INOUT)  :: YDCPG_SL2
TYPE(FIELD_VARIABLES)         ,INTENT(INOUT)  :: YDVARS
TYPE(TGEOMVARS)               ,INTENT(IN)     :: YDGEOMVARS
TYPE(TCFU)                    ,INTENT(IN)     :: YDCFU
TYPE(TXFU)                    ,INTENT(IN)     :: YDXFU
TYPE(MODEL)                   ,INTENT(IN)     :: YDMODEL
TYPE(TYP_DDH)                 ,INTENT(INOUT)  :: YDDDH
TYPE(TEPHYSMWAVE)             ,INTENT(INOUT)  :: YDPHYSMWAVE
END SUBROUTINE APL_ARPEGE







END INTERFACE
