INTERFACE
SUBROUTINE APL_WIND_GUST (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, &
& YDVARS, YDGEOMVARS, YDXFU, YDMODEL, KMOC_CLPH, PBLH, PDCAPE)
USE PARKIND1, ONLY : JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE YOMGEOMVARS,            ONLY : TGEOMVARS
USE TYPE_MODEL         , ONLY : MODEL
USE YOMXFU             , ONLY : TXFU
IMPLICIT NONE
TYPE(MF_PHYS_BASE_STATE_TYPE) ,INTENT(IN)     :: YDMF_PHYS_BASE_STATE
TYPE(CPG_BNDS_TYPE)           ,INTENT(IN)     :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)           ,INTENT(IN)     :: YDCPG_OPTS
TYPE(MF_PHYS_TYPE)            ,INTENT(INOUT)  :: YDMF_PHYS
TYPE(FIELD_VARIABLES)         ,INTENT(INOUT)  :: YDVARS
TYPE(TGEOMVARS)               ,INTENT(IN)     :: YDGEOMVARS
TYPE(TXFU)                    ,INTENT(IN)     :: YDXFU
TYPE(MODEL)                   ,INTENT(IN)     :: YDMODEL
INTEGER(KIND=JPIM)            ,INTENT(OUT)    :: KMOC_CLPH(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PBLH(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDCAPE(YDCPG_OPTS%KLON)
END SUBROUTINE APL_WIND_GUST




SUBROUTINE APL_WIND_GUST_PARALLEL (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS&
&, YDVARS, YDGEOMVARS, YDXFU, YDMODEL, YD_KMOC_CLPH, YD_PBLH, YD_PDCAPE)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMGEOMVARS,ONLY:TGEOMVARS
USE TYPE_MODEL,ONLY:MODEL
USE YOMXFU,ONLY:TXFU
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (TGEOMVARS), INTENT (IN)::YDGEOMVARS
TYPE (TXFU), INTENT (IN)::YDXFU
TYPE (MODEL), INTENT (IN)::YDMODEL
CLASS (FIELD_2IM), POINTER :: YD_KMOC_CLPH
CLASS (FIELD_2RB), POINTER :: YD_PBLH
CLASS (FIELD_2RB), POINTER :: YD_PDCAPE

END SUBROUTINE APL_WIND_GUST_PARALLEL




END INTERFACE
