INTERFACE
SUBROUTINE APL_ARPEGE_SURFACE (YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC, &
& YDGPAR, YDMF_PHYS, YDMF_PHYS_SURF, YDVARS, YDGEOMVARS, YDMODEL, PALBD, PALBP, PALPHA1, PCDROV,     &
& PCEROV, PCFATH, PCFAU, PCFBTH, PCFBU, PCFBV, PCHROV, PCOEFA, PCOEFN, PCP, PDIFEXT, PDIFWQ, PDIFWS, &
& PDQSTS, PDSA_CPS, PDSA_LHS, PDTMSE, PEDMFQ, PEDMFS, PEDMFU, PEDMFV, PFLU_CD, PFLU_CDN, PFLU_EMIS,  &
& PFLU_FEVI, PFLU_NEIJ, PFLU_QSATS, PFLU_VEG, PHQ, PHTR, PHU, PKQLROV, PKQROV, PKTROV, PKUROV, PLVT, &
& PMF_UP, PNEBCH, PNEBDIFF, PNEBS, PPOID, PQI, PQICE, PQL, PQV, PRDG_MU0, PRDG_MU0N, PRHGMT,         &
& PSC_FCLL, PSC_FCLN, PSC_FEVI, PSC_FEVN, PSFSWDIF, PSFSWDIR, PSGROUPEL, PSRAIN, PSSNOW, PSTATI,     &
& PTSN, PXDROV, PXHROV, PXQRO, PXTRO, PXTROV, PXURO, PXUROV)
USE PARKIND1, ONLY : JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE
USE YOMGPAR            , ONLY : TGPAR
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD  &
                       , ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE YOMGEOMVARS        , ONLY : TGEOMVARS
USE TYPE_MODEL         , ONLY : MODEL
IMPLICIT NONE
TYPE(MF_PHYS_BASE_STATE_TYPE) ,INTENT(IN)     :: YDMF_PHYS_BASE_STATE
TYPE(GEOMETRY)                ,INTENT(IN)     :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE)           ,INTENT(IN)     :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)           ,INTENT(IN)     :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE)           ,INTENT(INOUT)  :: YDCPG_MISC
TYPE(TGPAR)                   ,INTENT(INOUT)  :: YDGPAR
TYPE(MF_PHYS_TYPE)            ,INTENT(INOUT)  :: YDMF_PHYS
TYPE(MF_PHYS_SURF_TYPE)       ,INTENT(INOUT)  :: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES)         ,INTENT(INOUT)  :: YDVARS
TYPE(TGEOMVARS)               ,INTENT(IN)     :: YDGEOMVARS
TYPE(MODEL)                   ,INTENT(IN)     :: YDMODEL
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PALBD(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PALBP(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PALPHA1(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PCDROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PCEROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFATH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFAU(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFBTH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFBU(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCFBV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PCHROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCOEFA(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PCOEFN(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PCP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDIFEXT(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG,YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDIFWQ(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDIFWS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PDQSTS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PDSA_CPS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PDSA_LHS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PDTMSE
REAL(KIND=JPRB)               ,INTENT(IN)     :: PEDMFQ(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PEDMFS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PEDMFU(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PEDMFV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PFLU_CD(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PFLU_CDN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PFLU_EMIS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PFLU_FEVI(YDCPG_OPTS%KLON,1:YDCPG_OPTS%KTSSG+1)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PFLU_NEIJ(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PFLU_QSATS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PFLU_VEG(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PHQ(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PHTR(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PHU(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PKQLROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PKQROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PKTROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PKUROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PLVT(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PMF_UP(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PNEBCH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PNEBDIFF(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PNEBS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PPOID(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQI(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQICE(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQL(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PRDG_MU0(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PRDG_MU0N(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PRHGMT
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSC_FCLL(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSC_FCLN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSC_FEVI(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PSC_FEVN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PSFSWDIF(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PSFSWDIR(YDCPG_OPTS%KLON,YDCPG_OPTS%KSW)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PSGROUPEL(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PSRAIN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PSSNOW(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PSTATI
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PTSN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PXDROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PXHROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PXQRO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PXTRO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PXTROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PXURO(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PXUROV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
END SUBROUTINE APL_ARPEGE_SURFACE




SUBROUTINE APL_ARPEGE_SURFACE_PARALLEL (YDMF_PHYS_BASE_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS&
&, YDCPG_MISC, YDGPAR, YDMF_PHYS, YDMF_PHYS_SURF, YDVARS, YDGEOMVARS, YDMODEL, YD_PALBD, YD_PALBP&
&, YD_PALPHA1, YD_PCDROV, YD_PCEROV, YD_PCFATH, YD_PCFAU, YD_PCFBTH, YD_PCFBU, YD_PCFBV, YD_PCHROV&
&, YD_PCOEFA, YD_PCOEFN, YD_PCP, YD_PDIFEXT, YD_PDIFWQ, YD_PDIFWS, YD_PDQSTS, YD_PDSA_CPS, YD_PDSA_LHS&
&, PDTMSE, YD_PEDMFQ, YD_PEDMFS, YD_PEDMFU, YD_PEDMFV, YD_PFLU_CD, YD_PFLU_CDN, YD_PFLU_EMIS, YD_PFLU_FEVI&
&, YD_PFLU_NEIJ, YD_PFLU_QSATS, YD_PFLU_VEG, YD_PHQ, YD_PHTR, YD_PHU, YD_PKQLROV, YD_PKQROV, YD_PKTROV&
&, YD_PKUROV, YD_PLVT, YD_PMF_UP, YD_PNEBCH, YD_PNEBDIFF, YD_PNEBS, YD_PPOID, YD_PQI, YD_PQICE, YD_PQL&
&, YD_PQV, YD_PRDG_MU0, YD_PRDG_MU0N, PRHGMT, YD_PSC_FCLL, YD_PSC_FCLN, YD_PSC_FEVI, YD_PSC_FEVN&
&, YD_PSFSWDIF, YD_PSFSWDIR, YD_PSGROUPEL, YD_PSRAIN, YD_PSSNOW, PSTATI, YD_PTSN, YD_PXDROV, YD_PXHROV&
&, YD_PXQRO, YD_PXTRO, YD_PXTROV, YD_PXURO, YD_PXUROV)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE
USE YOMGPAR,ONLY:TGPAR
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMGEOMVARS,ONLY:TGEOMVARS
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (TGPAR), INTENT (INOUT)::YDGPAR
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (TGEOMVARS), INTENT (IN)::YDGEOMVARS
TYPE (MODEL), INTENT (IN)::YDMODEL
CLASS (FIELD_3RB), POINTER :: YD_PALBD
CLASS (FIELD_3RB), POINTER :: YD_PALBP
CLASS (FIELD_3RB), POINTER :: YD_PALPHA1
CLASS (FIELD_2RB), POINTER :: YD_PCDROV
CLASS (FIELD_2RB), POINTER :: YD_PCEROV
CLASS (FIELD_3RB), POINTER :: YD_PCFATH
CLASS (FIELD_3RB), POINTER :: YD_PCFAU
CLASS (FIELD_3RB), POINTER :: YD_PCFBTH
CLASS (FIELD_3RB), POINTER :: YD_PCFBU
CLASS (FIELD_3RB), POINTER :: YD_PCFBV
CLASS (FIELD_2RB), POINTER :: YD_PCHROV
CLASS (FIELD_3RB), POINTER :: YD_PCOEFA
CLASS (FIELD_3RB), POINTER :: YD_PCOEFN
CLASS (FIELD_3RB), POINTER :: YD_PCP
CLASS (FIELD_4RB), POINTER :: YD_PDIFEXT
CLASS (FIELD_2RB), POINTER :: YD_PDIFWQ
CLASS (FIELD_2RB), POINTER :: YD_PDIFWS
CLASS (FIELD_2RB), POINTER :: YD_PDQSTS
CLASS (FIELD_2RB), POINTER :: YD_PDSA_CPS
CLASS (FIELD_2RB), POINTER :: YD_PDSA_LHS
REAL (KIND=JPRB), INTENT (IN)::PDTMSE
CLASS (FIELD_3RB), POINTER :: YD_PEDMFQ
CLASS (FIELD_3RB), POINTER :: YD_PEDMFS
CLASS (FIELD_3RB), POINTER :: YD_PEDMFU
CLASS (FIELD_3RB), POINTER :: YD_PEDMFV
CLASS (FIELD_2RB), POINTER :: YD_PFLU_CD
CLASS (FIELD_2RB), POINTER :: YD_PFLU_CDN
CLASS (FIELD_2RB), POINTER :: YD_PFLU_EMIS
CLASS (FIELD_3RB), POINTER :: YD_PFLU_FEVI
CLASS (FIELD_2RB), POINTER :: YD_PFLU_NEIJ
CLASS (FIELD_2RB), POINTER :: YD_PFLU_QSATS
CLASS (FIELD_2RB), POINTER :: YD_PFLU_VEG
CLASS (FIELD_2RB), POINTER :: YD_PHQ
CLASS (FIELD_2RB), POINTER :: YD_PHTR
CLASS (FIELD_2RB), POINTER :: YD_PHU
CLASS (FIELD_3RB), POINTER :: YD_PKQLROV
CLASS (FIELD_3RB), POINTER :: YD_PKQROV
CLASS (FIELD_3RB), POINTER :: YD_PKTROV
CLASS (FIELD_3RB), POINTER :: YD_PKUROV
CLASS (FIELD_3RB), POINTER :: YD_PLVT
CLASS (FIELD_3RB), POINTER :: YD_PMF_UP
CLASS (FIELD_3RB), POINTER :: YD_PNEBCH
CLASS (FIELD_3RB), POINTER :: YD_PNEBDIFF
CLASS (FIELD_3RB), POINTER :: YD_PNEBS
CLASS (FIELD_3RB), POINTER :: YD_PPOID
CLASS (FIELD_3RB), POINTER :: YD_PQI
CLASS (FIELD_3RB), POINTER :: YD_PQICE
CLASS (FIELD_3RB), POINTER :: YD_PQL
CLASS (FIELD_3RB), POINTER :: YD_PQV
CLASS (FIELD_2RB), POINTER :: YD_PRDG_MU0
CLASS (FIELD_2RB), POINTER :: YD_PRDG_MU0N
REAL (KIND=JPRB), INTENT (IN)::PRHGMT
CLASS (FIELD_2RB), POINTER :: YD_PSC_FCLL
CLASS (FIELD_2RB), POINTER :: YD_PSC_FCLN
CLASS (FIELD_2RB), POINTER :: YD_PSC_FEVI
CLASS (FIELD_2RB), POINTER :: YD_PSC_FEVN
CLASS (FIELD_3RB), POINTER :: YD_PSFSWDIF
CLASS (FIELD_3RB), POINTER :: YD_PSFSWDIR
CLASS (FIELD_2RB), POINTER :: YD_PSGROUPEL
CLASS (FIELD_2RB), POINTER :: YD_PSRAIN
CLASS (FIELD_2RB), POINTER :: YD_PSSNOW
REAL (KIND=JPRB), INTENT (IN)::PSTATI
CLASS (FIELD_2RB), POINTER :: YD_PTSN
CLASS (FIELD_2RB), POINTER :: YD_PXDROV
CLASS (FIELD_2RB), POINTER :: YD_PXHROV
CLASS (FIELD_3RB), POINTER :: YD_PXQRO
CLASS (FIELD_3RB), POINTER :: YD_PXTRO
CLASS (FIELD_3RB), POINTER :: YD_PXTROV
CLASS (FIELD_3RB), POINTER :: YD_PXURO
CLASS (FIELD_3RB), POINTER :: YD_PXUROV

END SUBROUTINE APL_ARPEGE_SURFACE_PARALLEL




END INTERFACE
