INTERFACE
SUBROUTINE APL_ARPEGE_CLOUDINESS (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC,        &
& YDMF_PHYS, YDVARS, YDGEOMVARS, YDMODEL, LDREDPR, PAIPCMT, PBLH, PDECRD, PFLU_QSAT, PMSC_QW, PNEBC0, &
& PNEBCH, PNEBS, PNEBS0, PNEB_CVPP, PPFL_FPLCH, PQI, PQL, PQLIS, PQLIS0, PQLI_CVP, PQLI_CVPP, PQV, &
& PUNEBH, PCLCT_RAD, YDSTA)
USE PARKIND1, ONLY : JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD       , ONLY : CPG_MISC_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE YOMGEOMVARS,            ONLY : TGEOMVARS
USE TYPE_MODEL         , ONLY : MODEL
USE YOMSTA             , ONLY : TSTA
IMPLICIT NONE
TYPE(MF_PHYS_BASE_STATE_TYPE) ,INTENT(IN)     :: YDMF_PHYS_BASE_STATE
TYPE(CPG_BNDS_TYPE)           ,INTENT(IN)     :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE)           ,INTENT(IN)     :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE)           ,INTENT(INOUT)  :: YDCPG_MISC
TYPE(MF_PHYS_TYPE)            ,INTENT(INOUT)  :: YDMF_PHYS
TYPE(FIELD_VARIABLES)         ,INTENT(INOUT)  :: YDVARS
TYPE(TGEOMVARS)               ,INTENT(IN)     :: YDGEOMVARS
TYPE(MODEL)                   ,INTENT(IN)     :: YDMODEL
LOGICAL                       ,INTENT(IN)     :: LDREDPR
REAL(KIND=JPRB)               ,INTENT(IN)     :: PAIPCMT(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PBLH(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PDECRD(YDCPG_OPTS%KLON)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PFLU_QSAT(YDCPG_OPTS%KLON,1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PMSC_QW(YDCPG_OPTS%KLON,1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PNEBC0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(INOUT)  :: PNEBCH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PNEBS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PNEBS0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PNEB_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PPFL_FPLCH(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQI(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQL(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQLIS(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PQLIS0(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQLI_CVP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQLI_CVPP(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PQV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(IN)     :: PUNEBH(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB)               ,INTENT(OUT)    :: PCLCT_RAD(YDCPG_OPTS%KLON)
TYPE(TSTA)                    ,INTENT(IN)     :: YDSTA
END SUBROUTINE APL_ARPEGE_CLOUDINESS




SUBROUTINE APL_ARPEGE_CLOUDINESS_PARALLEL (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDCPG_MISC&
&, YDMF_PHYS, YDVARS, YDGEOMVARS, YDMODEL, LDREDPR, YD_PAIPCMT, YD_PBLH, YD_PDECRD, YD_PFLU_QSAT,&
& YD_PMSC_QW, YD_PNEBC0, YD_PNEBCH, YD_PNEBS, YD_PNEBS0, YD_PNEB_CVPP, YD_PPFL_FPLCH, YD_PQI, YD_PQL&
&, YD_PQLIS, YD_PQLIS0, YD_PQLI_CVP, YD_PQLI_CVPP, YD_PQV, YD_PUNEBH, YD_PCLCT_RAD, YDSTA)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD,ONLY:CPG_MISC_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE YOMGEOMVARS,ONLY:TGEOMVARS
USE TYPE_MODEL,ONLY:MODEL
USE YOMSTA,ONLY:TSTA
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_MISC_TYPE), INTENT (INOUT)::YDCPG_MISC
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (TGEOMVARS), INTENT (IN)::YDGEOMVARS
TYPE (MODEL), INTENT (IN)::YDMODEL
LOGICAL, INTENT (IN)::LDREDPR
CLASS (FIELD_2RB), POINTER :: YD_PAIPCMT
CLASS (FIELD_2RB), POINTER :: YD_PBLH
CLASS (FIELD_2RB), POINTER :: YD_PDECRD
CLASS (FIELD_3RB), POINTER :: YD_PFLU_QSAT
CLASS (FIELD_3RB), POINTER :: YD_PMSC_QW
CLASS (FIELD_3RB), POINTER :: YD_PNEBC0
CLASS (FIELD_3RB), POINTER :: YD_PNEBCH
CLASS (FIELD_3RB), POINTER :: YD_PNEBS
CLASS (FIELD_3RB), POINTER :: YD_PNEBS0
CLASS (FIELD_3RB), POINTER :: YD_PNEB_CVPP
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FPLCH
CLASS (FIELD_3RB), POINTER :: YD_PQI
CLASS (FIELD_3RB), POINTER :: YD_PQL
CLASS (FIELD_3RB), POINTER :: YD_PQLIS
CLASS (FIELD_3RB), POINTER :: YD_PQLIS0
CLASS (FIELD_3RB), POINTER :: YD_PQLI_CVP
CLASS (FIELD_3RB), POINTER :: YD_PQLI_CVPP
CLASS (FIELD_3RB), POINTER :: YD_PQV
CLASS (FIELD_3RB), POINTER :: YD_PUNEBH
CLASS (FIELD_2RB), POINTER :: YD_PCLCT_RAD
TYPE (TSTA), INTENT (IN)::YDSTA

END SUBROUTINE APL_ARPEGE_CLOUDINESS_PARALLEL




END INTERFACE
