INTERFACE
SUBROUTINE APL_ARPEGE_OCEANIC_FLUXES (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDMF_PHYS, YDMF_PHYS_SURF, &
& YDMODEL, LDHMT, PCDROV, PCEROV, PCHROV, PDPHIT, PDPHIV, PDSA_RS, PFLU_CD, PFLU_CDN, PFLU_CH, PFLU_QSATS)
USE PARKIND1, ONLY : JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD &
                       , ONLY : MF_PHYS_SURF_TYPE
USE TYPE_MODEL         , ONLY : MODEL
IMPLICIT NONE
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT(IN)    :: YDMF_PHYS_BASE_STATE
TYPE(CPG_BNDS_TYPE),            INTENT(IN)    :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),            INTENT(IN)    :: YDCPG_OPTS
TYPE(MF_PHYS_TYPE),             INTENT(INOUT) :: YDMF_PHYS
TYPE(MF_PHYS_SURF_TYPE),        INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(MODEL),                    INTENT(IN)    :: YDMODEL
LOGICAL,                        INTENT(IN)    :: LDHMT
REAL(KIND=JPRB),                INTENT(INOUT) :: PCDROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PCEROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PCHROV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PDPHIT(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PDPHIV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PDSA_RS (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PFLU_CD (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PFLU_CDN (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(INOUT) :: PFLU_CH (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_QSATS (YDCPG_OPTS%KLON)
END SUBROUTINE APL_ARPEGE_OCEANIC_FLUXES




SUBROUTINE APL_ARPEGE_OCEANIC_FLUXES_PARALLEL (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS&
&, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, LDHMT, YD_PCDROV, YD_PCEROV, YD_PCHROV, YD_PDPHIT&
&, YD_PDPHIV, YD_PDSA_RS, YD_PFLU_CD, YD_PFLU_CDN, YD_PFLU_CH, YD_PFLU_QSATS)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
LOGICAL, INTENT (IN)::LDHMT
CLASS (FIELD_2RB), POINTER :: YD_PCDROV
CLASS (FIELD_2RB), POINTER :: YD_PCEROV
CLASS (FIELD_2RB), POINTER :: YD_PCHROV
CLASS (FIELD_2RB), POINTER :: YD_PDPHIT
CLASS (FIELD_2RB), POINTER :: YD_PDPHIV
CLASS (FIELD_2RB), POINTER :: YD_PDSA_RS
CLASS (FIELD_2RB), POINTER :: YD_PFLU_CD
CLASS (FIELD_2RB), POINTER :: YD_PFLU_CDN
CLASS (FIELD_2RB), POINTER :: YD_PFLU_CH
CLASS (FIELD_2RB), POINTER :: YD_PFLU_QSATS

END SUBROUTINE APL_ARPEGE_OCEANIC_FLUXES_PARALLEL




END INTERFACE
