INTERFACE
SUBROUTINE APL_ARPEGE_HYDRO_BUDGET (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDGPAR,         &
& YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, PC3, PCN, PDSA_C1, PDSA_C2, PFLU_FEVI, PFLU_NEIJ, PFLU_VEG, &
& PFPLSL, PFPLSN, PWFC, PWLMX, PWPMX, PWSEQ, PWSMX)
USE PARKIND1, ONLY : JPIM, JPRB
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE YOMGPAR            , ONLY : TGPAR
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD  &
                       , ONLY : MF_PHYS_SURF_TYPE
USE TYPE_MODEL         , ONLY : MODEL
IMPLICIT NONE
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT(IN)    :: YDMF_PHYS_BASE_STATE
TYPE(CPG_BNDS_TYPE),            INTENT(IN)    :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),            INTENT(IN)    :: YDCPG_OPTS
TYPE(TGPAR),                    INTENT(INOUT) :: YDGPAR
TYPE(MF_PHYS_TYPE),             INTENT(INOUT) :: YDMF_PHYS
TYPE(MF_PHYS_SURF_TYPE),        INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(MODEL),                    INTENT(IN)    :: YDMODEL
REAL(KIND=JPRB),                INTENT(IN)    :: PC3(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PCN(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PDSA_C1 (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PDSA_C2 (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_FEVI (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KTSSG+1)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_NEIJ (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PFLU_VEG (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PFPLSL(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PFPLSN(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),                INTENT(IN)    :: PWFC(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PWLMX(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PWPMX(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PWSEQ(YDCPG_OPTS%KLON)
REAL(KIND=JPRB),                INTENT(IN)    :: PWSMX(YDCPG_OPTS%KLON)
END SUBROUTINE APL_ARPEGE_HYDRO_BUDGET




SUBROUTINE APL_ARPEGE_HYDRO_BUDGET_PARALLEL (YDMF_PHYS_BASE_STATE, YDCPG_BNDS, YDCPG_OPTS, YDGPAR&
&, YDMF_PHYS, YDMF_PHYS_SURF, YDMODEL, YD_PC3, YD_PCN, YD_PDSA_C1, YD_PDSA_C2, YD_PFLU_FEVI, YD_PFLU_NEIJ&
&, YD_PFLU_VEG, YD_PFPLSL, YD_PFPLSN, YD_PWFC, YD_PWLMX, YD_PWPMX, YD_PWSEQ, YD_PWSMX)
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE YOMGPAR,ONLY:TGPAR
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY:MF_PHYS_SURF_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (TGPAR), INTENT (INOUT)::YDGPAR
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_SURF_TYPE), INTENT (INOUT)::YDMF_PHYS_SURF
TYPE (MODEL), INTENT (IN)::YDMODEL
CLASS (FIELD_2RB), POINTER :: YD_PC3
CLASS (FIELD_2RB), POINTER :: YD_PCN
CLASS (FIELD_2RB), POINTER :: YD_PDSA_C1
CLASS (FIELD_2RB), POINTER :: YD_PDSA_C2
CLASS (FIELD_3RB), POINTER :: YD_PFLU_FEVI
CLASS (FIELD_2RB), POINTER :: YD_PFLU_NEIJ
CLASS (FIELD_2RB), POINTER :: YD_PFLU_VEG
CLASS (FIELD_3RB), POINTER :: YD_PFPLSL
CLASS (FIELD_3RB), POINTER :: YD_PFPLSN
CLASS (FIELD_2RB), POINTER :: YD_PWFC
CLASS (FIELD_2RB), POINTER :: YD_PWLMX
CLASS (FIELD_2RB), POINTER :: YD_PWPMX
CLASS (FIELD_2RB), POINTER :: YD_PWSEQ
CLASS (FIELD_2RB), POINTER :: YD_PWSMX

END SUBROUTINE APL_ARPEGE_HYDRO_BUDGET_PARALLEL




END INTERFACE
