MODULE CPG_SL2_TYPE_MOD

!$ACDC methods --methods-list=host,wipe,copy --skip-components cpg --field-api --field-api-class cpg

USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_REGISTRY_MOD
USE PARKIND1, ONLY : JPRB, JPIM, JPIB

IMPLICIT NONE



TYPE CPG_SL2_TYPE
  LOGICAL :: LOWNED = .FALSE.
  INTEGER (KIND=JPIM) :: NLEV = -1
  INTEGER (KIND=JPIB) :: ISIZE = 0
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_DATA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DBBC1 (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_DBBC1 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DPHI1 (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_DPHI1 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: USI (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_USI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VSI (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_VSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TSI (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_TSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PDSI (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_PDSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VDSI (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_VDSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SPSI (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_SPSI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VVEL (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_VVEL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: URL (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_URL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VRL (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_VRL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WRL (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_WRL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: URL5 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_URL5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VRL5 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_VRL5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WRL5 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_WRL5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: USI5 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_USI5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VSI5 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_VSI5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: U15 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_U15 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: V15 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_V15 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T15 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_T15 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q15 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_Q15 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPA (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_KAPPA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPAT (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_KAPPAT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPAM (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_KAPPAM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPAH (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_KAPPAH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPA5 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_KAPPA5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAPPAT5 (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_KAPPAT5 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWF (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_GWF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GDW (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_GDW => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWS (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_GWS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STDDISU (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_STDDISU => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STDDISV (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_STDDISV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: STDDISW (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_STDDISW => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZRL (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_ZRL => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_SL2_TYPE_INIT
  PROCEDURE :: CONFORM => CPG_SL2_TYPE_CONFORM
  PROCEDURE :: RESIZE => CPG_SL2_TYPE_RESIZE
  PROCEDURE :: SYNC_HOST => CPG_SL2_TYPE_SYNC_HOST
  PROCEDURE :: SET => CPG_SL2_TYPE_SET
  PROCEDURE :: SET_HOST_PARALLEL => CPG_SL2_TYPE_SET_HOST_PARALLEL
  PROCEDURE :: SET_DEVICE_PARALLEL => CPG_SL2_TYPE_SET_DEVICE_PARALLEL
  PROCEDURE :: UPDATE_VIEW => CPG_SL2_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_SL2_TYPE_FINAL
END TYPE CPG_SL2_TYPE

REAL(KIND=JPRB),    PRIVATE, SAVE, TARGET :: ZDUM1 (1), ZDUM2 (1, 1)

CONTAINS

SUBROUTINE CPG_SL2_TYPE_INIT (SELF, REGISTRY, NLEV, YDTPTRSLB2 &
                                & , PERSISTENT, PB2)

USE PTRSLB2, ONLY : TPTRSLB2
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_SL2_TYPE)                               :: SELF
TYPE (FIELD_REGISTRY),              INTENT (IN)    :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TPTRSLB2),                    INTENT (IN)    :: YDTPTRSLB2
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PB2 (:, :, :)

END SUBROUTINE CPG_SL2_TYPE_INIT

SUBROUTINE CPG_SL2_TYPE_RESIZE (SELF, REGISTRY, NLEV, YDTPTRSLB2, PERSISTENT)

USE PTRSLB2, ONLY : TPTRSLB2

CLASS (CPG_SL2_TYPE)                               :: SELF
TYPE (FIELD_REGISTRY),              INTENT (IN)    :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TPTRSLB2),                    INTENT (IN)    :: YDTPTRSLB2
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

IF (.NOT. SELF%CONFORM (REGISTRY, NLEV, YDTPTRSLB2, PERSISTENT)) THEN
  CALL SELF%FINAL
  CALL SELF%INIT (REGISTRY, NLEV, YDTPTRSLB2, PERSISTENT)
ENDIF

END SUBROUTINE CPG_SL2_TYPE_RESIZE

LOGICAL FUNCTION CPG_SL2_TYPE_CONFORM (SELF, REGISTRY, NLEV, YDTPTRSLB2, PERSISTENT) RESULT (LLCONFORM)

USE PTRSLB2, ONLY : TPTRSLB2
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_SL2_TYPE)                               :: SELF
TYPE (FIELD_REGISTRY),              INTENT (IN)    :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TPTRSLB2),                    INTENT (IN)    :: YDTPTRSLB2
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

LOGICAL :: LLPERSISTENT

LLCONFORM = .FALSE.

LLPERSISTENT = .FALSE.
IF (PRESENT (PERSISTENT)) LLPERSISTENT = PERSISTENT

IF (.NOT. ASSOCIATED (SELF%ZDATA)) RETURN

IF (SELF%NLEV /= NLEV) RETURN

IF (SIZE (SELF%ZDATA, 1) /= REGISTRY%GEOM%YRDIM%NPROMA) RETURN
IF (SIZE (SELF%ZDATA, 2) /= YDTPTRSLB2%NFLDSLB2) RETURN

IF (LLPERSISTENT) THEN
  IF (SIZE (SELF%ZDATA, 3) /= REGISTRY%GEOM%YRDIM%NGPBLKS) RETURN
ELSE
  IF (SIZE (SELF%ZDATA, 3) /= OML_MAX_THREADS ()) RETURN
ENDIF

LLCONFORM = .TRUE.

END FUNCTION CPG_SL2_TYPE_CONFORM

SUBROUTINE CPG_SL2_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_SL2_TYPE)        :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_SL2_TYPE_UPDATE_VIEW

SUBROUTINE CPG_SL2_TYPE_FINAL (SELF)
CLASS (CPG_SL2_TYPE)          :: SELF

END SUBROUTINE CPG_SL2_TYPE_FINAL

SUBROUTINE CPG_SL2_TYPE_SYNC_HOST (SELF)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

CLASS (CPG_SL2_TYPE) :: SELF

REAL (KIND=JPRB), POINTER :: PTR2 (:,:), PTR3 (:,:,:)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

END SUBROUTINE CPG_SL2_TYPE_SYNC_HOST

SUBROUTINE CPG_SL2_TYPE_SET (SELF, YDCPG_OPTS, YDCPG_BNDS, PVALUE)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE

CLASS (CPG_SL2_TYPE) :: SELF
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)   :: YDCPG_BNDS
REAL (KIND=JPRB), INTENT(IN) :: PVALUE

INTEGER (KIND=JPIM) :: JFLD, JROF

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL2_TYPE_SET', 0, ZHOOK_HANDLE)

#ifdef __PGI

DO JFLD = 1, SIZE (SELF%ZVIEW, 2)
  DO JROF = 1, SIZE (SELF%ZVIEW, 1)
    SELF%ZVIEW (JROF, JFLD) = PVALUE
  ENDDO
ENDDO

#else

SELF%ZVIEW = PVALUE

#endif

IF (LHOOK) CALL DR_HOOK ('CPG_SL2_TYPE_SET', 1, ZHOOK_HANDLE)

END SUBROUTINE

SUBROUTINE CPG_SL2_TYPE_SET_HOST_PARALLEL (SELF, YDCPG_OPTS, YDCPG_BNDS, PVALUE)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE

CLASS (CPG_SL2_TYPE) :: SELF
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)   :: YDCPG_BNDS
REAL (KIND=JPRB), INTENT(IN) :: PVALUE

INTEGER (KIND=JPIM) :: JBLK

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL2_TYPE_SET_HOST_PARALLEL', 0, ZHOOK_HANDLE)

CALL SELF%SYNC_HOST

!$OMP PARALLEL DO PRIVATE (JBLK)
DO JBLK = 1, YDCPG_OPTS%KGPBLKS
  SELF%ZDATA (:,:,JBLK) = PVALUE
ENDDO
!$OMP END PARALLEL DO

IF (LHOOK) CALL DR_HOOK ('CPG_SL2_TYPE_SET_HOST_PARALLEL', 1, ZHOOK_HANDLE)

END SUBROUTINE

SUBROUTINE CPG_SL2_TYPE_SET_DEVICE_PARALLEL (SELF, YDCPG_OPTS, YDCPG_BNDS, PVALUE)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE

CLASS (CPG_SL2_TYPE) :: SELF
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)   :: YDCPG_BNDS
REAL (KIND=JPRB), INTENT(IN) :: PVALUE

REAL (KIND=JPRB), POINTER :: Z2 (:,:), Z3 (:,:,:)
INTEGER (KIND=JPIM) :: JROF, JBLK

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE


END SUBROUTINE

END MODULE CPG_SL2_TYPE_MOD

