
MODULE CPG_SL1B_TYPE_MOD

!$ACDC methods --methods-list=host,wipe,copy --skip-components cpg --field-api --field-api-class cpg

USE FIELD_MODULE
USE FIELD_REGISTRY_MOD
USE PARKIND1, ONLY : JPRB, JPIM, JPIB
USE YOM_YGFL, ONLY : TYPE_GFL_COMP

IMPLICIT NONE




ABSTRACT INTERFACE 
  LOGICAL FUNCTION FUN_GREP (YDCOMP, YDMODEL)
    USE YOM_YGFL, ONLY : TYPE_GFL_COMP
    USE TYPE_MODEL, ONLY : MODEL
    TYPE (TYPE_GFL_COMP), INTENT (IN) :: YDCOMP
    TYPE (MODEL),  INTENT (IN) :: YDMODEL
  END FUNCTION FUN_GREP
END INTERFACE

PRIVATE :: FUN_GREP


PRIVATE :: GREPVARSB

TYPE CPG_SL1B_2D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_F (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P_F => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_SPF (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P_SPF => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_SP (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P_SP => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_P (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P_P => NULL ()

END TYPE

TYPE CPG_SL1B_3D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_F (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P_F => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_SPF (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P_SPF => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_SP (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P_SP => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P_P (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P_P => NULL ()

  TYPE (TYPE_GFL_COMP) :: YCOMP
END TYPE


TYPE CPG_SL1B_TYPE
  LOGICAL :: LOWNED = .FALSE.
  INTEGER (KIND=JPIM) :: NLEV = -1
  INTEGER (KIND=JPIB) :: ISIZE = 0
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_DATA => NULL ()
  TYPE (CPG_SL1B_3D_TYPE) :: U9
  TYPE (CPG_SL1B_3D_TYPE) :: V9
  TYPE (CPG_SL1B_3D_TYPE) :: T9
  TYPE (CPG_SL1B_3D_TYPE) :: PD9
  TYPE (CPG_SL1B_3D_TYPE) :: VD9
  TYPE (CPG_SL1B_3D_TYPE) :: NHX9
  TYPE (CPG_SL1B_3D_TYPE) :: UR0
  TYPE (CPG_SL1B_3D_TYPE) :: VR0
  TYPE (CPG_SL1B_3D_TYPE) :: ZR0
  TYPE (CPG_SL1B_3D_TYPE) :: WR0
  TYPE (CPG_SL1B_3D_TYPE) :: UR00
  TYPE (CPG_SL1B_3D_TYPE) :: VR00
  TYPE (CPG_SL1B_3D_TYPE) :: ZR00
  TYPE (CPG_SL1B_3D_TYPE) :: WR00
  TYPE (CPG_SL1B_3D_TYPE) :: WRA
  TYPE (CPG_SL1B_3D_TYPE) :: UR9
  TYPE (CPG_SL1B_3D_TYPE) :: VR9
  TYPE (CPG_SL1B_3D_TYPE) :: DBBC9
  TYPE (CPG_SL1B_3D_TYPE) :: DPHI9
  TYPE (CPG_SL1B_2D_TYPE) :: GWS9
  TYPE (CPG_SL1B_3D_TYPE) :: U0
  TYPE (CPG_SL1B_3D_TYPE) :: V0
  TYPE (CPG_SL1B_3D_TYPE) :: T0
  TYPE (CPG_SL1B_3D_TYPE) :: PD0
  TYPE (CPG_SL1B_3D_TYPE) :: VD0
  TYPE (CPG_SL1B_3D_TYPE) :: C9
  TYPE (CPG_SL1B_2D_TYPE) :: SP9
  TYPE (CPG_SL1B_2D_TYPE) :: SP0
  TYPE (CPG_SL1B_3D_TYPE) :: C0
  TYPE (CPG_SL1B_3D_TYPE) :: UP9
  TYPE (CPG_SL1B_3D_TYPE) :: VP9
  TYPE (CPG_SL1B_3D_TYPE) :: TP9
  TYPE (CPG_SL1B_3D_TYPE) :: U9_SI
  TYPE (CPG_SL1B_3D_TYPE) :: V9_SI
  TYPE (CPG_SL1B_3D_TYPE) :: T9_SI
  TYPE (CPG_SL1B_3D_TYPE) :: PD9_SI
  TYPE (CPG_SL1B_3D_TYPE) :: VD9_SI
  TYPE (CPG_SL1B_3D_TYPE) :: C9_SI
  TYPE (CPG_SL1B_3D_TYPE) :: UF9
  TYPE (CPG_SL1B_3D_TYPE) :: VF9
  TYPE (CPG_SL1B_3D_TYPE) :: TF9
  TYPE (CPG_SL1B_3D_TYPE) :: VDF9
  TYPE (CPG_SL1B_3D_TYPE) :: U9_NL
  TYPE (CPG_SL1B_3D_TYPE) :: V9_NL
  TYPE (CPG_SL1B_3D_TYPE) :: T9_NL
  TYPE (CPG_SL1B_3D_TYPE) :: PD9_NL
  TYPE (CPG_SL1B_3D_TYPE) :: VD9_NL
  TYPE (CPG_SL1B_3D_TYPE) :: C9_NL
  TYPE (CPG_SL1B_3D_TYPE) :: ZR9
  TYPE (CPG_SL1B_3D_TYPE) :: Z9
  TYPE (CPG_SL1B_3D_TYPE) :: Z0
  TYPE (CPG_SL1B_3D_TYPE) :: ZP9

  TYPE (CPG_SL1B_3D_TYPE) :: Q
  TYPE (CPG_SL1B_3D_TYPE) :: I
  TYPE (CPG_SL1B_3D_TYPE) :: L
  TYPE (CPG_SL1B_3D_TYPE) :: IMF
  TYPE (CPG_SL1B_3D_TYPE) :: LMF
  TYPE (CPG_SL1B_3D_TYPE) :: HLMF
  TYPE (CPG_SL1B_3D_TYPE) :: HIMF
  TYPE (CPG_SL1B_3D_TYPE) :: LCONV
  TYPE (CPG_SL1B_3D_TYPE) :: ICONV
  TYPE (CPG_SL1B_3D_TYPE) :: RCONV
  TYPE (CPG_SL1B_3D_TYPE) :: SCONV
  TYPE (CPG_SL1B_3D_TYPE) :: IRAD
  TYPE (CPG_SL1B_3D_TYPE) :: LRAD
  TYPE (CPG_SL1B_3D_TYPE) :: S
  TYPE (CPG_SL1B_3D_TYPE) :: R
  TYPE (CPG_SL1B_3D_TYPE) :: G
  TYPE (CPG_SL1B_3D_TYPE) :: H
  TYPE (CPG_SL1B_3D_TYPE) :: TKE
  TYPE (CPG_SL1B_3D_TYPE) :: TTE
  TYPE (CPG_SL1B_3D_TYPE) :: EFB1
  TYPE (CPG_SL1B_3D_TYPE) :: EFB2
  TYPE (CPG_SL1B_3D_TYPE) :: EFB3
  TYPE (CPG_SL1B_3D_TYPE) :: A
  TYPE (CPG_SL1B_3D_TYPE) :: AMF
  TYPE (CPG_SL1B_3D_TYPE) :: WMFC
  TYPE (CPG_SL1B_3D_TYPE) :: HLCFMF
  TYPE (CPG_SL1B_3D_TYPE) :: HICFMF
  TYPE (CPG_SL1B_3D_TYPE) :: O3
  TYPE (CPG_SL1B_3D_TYPE) :: SRC
  TYPE (CPG_SL1B_3D_TYPE) :: MXL
  TYPE (CPG_SL1B_3D_TYPE) :: SHTUR
  TYPE (CPG_SL1B_3D_TYPE) :: FQTUR
  TYPE (CPG_SL1B_3D_TYPE) :: FSTUR
  TYPE (CPG_SL1B_3D_TYPE) :: CPF
  TYPE (CPG_SL1B_3D_TYPE) :: SPF
  TYPE (CPG_SL1B_3D_TYPE) :: CVGQ
  TYPE (CPG_SL1B_3D_TYPE) :: QVA
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: GHG (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: CHEM (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: AERO (:)
  TYPE (CPG_SL1B_3D_TYPE) :: LRCH4
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: FORC (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: EZDIAG (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: ERA40 (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: NOGW (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: EMIS3D (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: EDRP (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: SLDIA (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: AERAOT (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: AERLISI (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: AEROUT (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: AEROCLIM (:)
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: UVP (:)
  TYPE (CPG_SL1B_3D_TYPE) :: PHYCTY
  TYPE (CPG_SL1B_3D_TYPE) :: RSPEC
  TYPE (CPG_SL1B_3D_TYPE) :: SDSAT
  TYPE (CPG_SL1B_3D_TYPE) :: CVV
  TYPE (CPG_SL1B_3D_TYPE) :: RKTH
  TYPE (CPG_SL1B_3D_TYPE) :: RKTQV
  TYPE (CPG_SL1B_3D_TYPE) :: RKTQC
  TYPE (CPG_SL1B_3D_TYPE) :: UOM
  TYPE (CPG_SL1B_3D_TYPE) :: UAL
  TYPE (CPG_SL1B_3D_TYPE) :: DOM
  TYPE (CPG_SL1B_3D_TYPE) :: DAL
  TYPE (CPG_SL1B_3D_TYPE) :: UEN
  TYPE (CPG_SL1B_3D_TYPE) :: MO
  TYPE (CPG_SL1B_3D_TYPE) :: UNEBH
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: LIMA (:)
  TYPE (CPG_SL1B_3D_TYPE) :: FSD
  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: EXT (:)
  TYPE (CPG_SL1B_3D_TYPE) :: THRAD

  TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: GFL (:)


CONTAINS
  PROCEDURE :: INIT => CPG_SL1B_TYPE_INIT
  PROCEDURE :: FINAL => CPG_SL1B_TYPE_FINAL
  PROCEDURE :: SYNC_HOST => CPG_SL1B_TYPE_SYNC_HOST

  PROCEDURE :: UPDATE_VIEW => CPG_SL1B_TYPE_UPDATE_VIEW
  PROCEDURE :: SET_HOST_PARALLEL => CPG_SL1B_TYPE_SET_HOST_PARALLEL
  PROCEDURE :: SET_DEVICE_PARALLEL => CPG_SL1B_TYPE_SET_DEVICE_PARALLEL


  PROCEDURE :: SET => CPG_SL1B_TYPE_SET
  PROCEDURE :: SHUFFLE => CPG_SL1B_TYPE_SHUFFLE
  PROCEDURE :: SHUFFLE_HOST_PARALLEL => CPG_SL1B_TYPE_SHUFFLE_HOST_PARALLEL
  PROCEDURE :: SHUFFLE_DEVICE_PARALLEL => CPG_SL1B_TYPE_SHUFFLE_DEVICE_PARALLEL


END TYPE CPG_SL1B_TYPE

REAL(KIND=JPRB), PRIVATE, SAVE, TARGET :: ZDUM1 (1), ZDUM2 (1, 1)

CONTAINS


SUBROUTINE GREPVARSB (YDCPG_SL1B, YDMODEL, COND, YDVARS_LIST)
USE TYPE_MODEL, ONLY : MODEL
TYPE(CPG_SL1B_TYPE), INTENT(INOUT) :: YDCPG_SL1B
TYPE(MODEL), INTENT(IN) :: YDMODEL
PROCEDURE (FUN_GREP) :: COND
TYPE (CPG_SL1B_3D_TYPE), ALLOCATABLE :: YDVARS_LIST (:)

INTEGER (KIND=JPIM) :: ISIZE, JFLD, IPNTR

ISIZE = 0

IF (COND (YDMODEL%YRML_GCONF%YGFL%YQ, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YI, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YL, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YIMF, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YLMF, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YHLMF, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YHIMF, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YLCONV, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YICONV, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRCONV, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSCONV, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YIRAD, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YLRAD, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YS, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YR, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YG, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YH, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YTKE, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YTTE, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YEFB1, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YEFB2, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YEFB3, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YA, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YAMF, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YWMFC, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YHLCFMF, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YHICFMF, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YO3, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSRC, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YMXL, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSHTUR, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YFQTUR, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YFSTUR, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YCPF, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSPF, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YCVGQ, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YQVA, YDMODEL)) ISIZE = ISIZE + 1
IF (ALLOCATED (YDCPG_SL1B%GHG)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%GHG)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YGHG(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%CHEM)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%CHEM)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YCHEM(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AERO)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AERO)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAERO(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YLRCH4, YDMODEL)) ISIZE = ISIZE + 1
IF (ALLOCATED (YDCPG_SL1B%FORC)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%FORC)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YFORC(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%EZDIAG)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%EZDIAG)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YEZDIAG(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%ERA40)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%ERA40)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YERA40(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%NOGW)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%NOGW)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YNOGW(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%EMIS3D)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%EMIS3D)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YEMIS3D(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%EDRP)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%EDRP)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YEDRP(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%SLDIA)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%SLDIA)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YSLDIA(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AERAOT)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AERAOT)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAERAOT(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AERLISI)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AERLISI)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAERLISI(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AEROUT)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AEROUT)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAEROUT(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AEROCLIM)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AEROCLIM)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAEROCLIM(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%UVP)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%UVP)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YUVP(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YPHYCTY, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRSPEC, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSDSAT, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YCVV, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRKTH, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRKTQV, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRKTQC, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YUOM, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YUAL, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YDOM, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YDAL, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YUEN, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YMO, YDMODEL)) ISIZE = ISIZE + 1
IF (COND (YDMODEL%YRML_GCONF%YGFL%YUNEBH, YDMODEL)) ISIZE = ISIZE + 1
IF (ALLOCATED (YDCPG_SL1B%LIMA)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%LIMA)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YLIMA(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YFSD, YDMODEL)) ISIZE = ISIZE + 1
IF (ALLOCATED (YDCPG_SL1B%EXT)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%EXT)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YEXT(JFLD), YDMODEL)) ISIZE = ISIZE + 1
  ENDDO
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YTHRAD, YDMODEL)) ISIZE = ISIZE + 1

ALLOCATE (YDVARS_LIST (ISIZE))

IPNTR = 1

IF (COND (YDMODEL%YRML_GCONF%YGFL%YQ, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%Q
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YI, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%I
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YL, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%L
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YIMF, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%IMF
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YLMF, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%LMF
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YHLMF, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%HLMF
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YHIMF, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%HIMF
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YLCONV, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%LCONV
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YICONV, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%ICONV
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRCONV, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%RCONV
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSCONV, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%SCONV
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YIRAD, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%IRAD
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YLRAD, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%LRAD
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YS, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%S
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YR, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%R
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YG, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%G
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YH, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%H
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YTKE, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%TKE
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YTTE, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%TTE
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YEFB1, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%EFB1
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YEFB2, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%EFB2
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YEFB3, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%EFB3
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YA, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%A
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YAMF, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%AMF
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YWMFC, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%WMFC
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YHLCFMF, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%HLCFMF
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YHICFMF, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%HICFMF
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YO3, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%O3
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSRC, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%SRC
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YMXL, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%MXL
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSHTUR, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%SHTUR
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YFQTUR, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%FQTUR
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YFSTUR, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%FSTUR
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YCPF, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%CPF
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSPF, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%SPF
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YCVGQ, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%CVGQ
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YQVA, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%QVA
  IPNTR = IPNTR + 1
ENDIF
IF (ALLOCATED (YDCPG_SL1B%GHG)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%GHG)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YGHG(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%GHG(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%CHEM)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%CHEM)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YCHEM(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%CHEM(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AERO)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AERO)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAERO(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%AERO(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YLRCH4, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%LRCH4
  IPNTR = IPNTR + 1
ENDIF
IF (ALLOCATED (YDCPG_SL1B%FORC)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%FORC)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YFORC(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%FORC(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%EZDIAG)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%EZDIAG)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YEZDIAG(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%EZDIAG(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%ERA40)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%ERA40)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YERA40(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%ERA40(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%NOGW)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%NOGW)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YNOGW(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%NOGW(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%EMIS3D)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%EMIS3D)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YEMIS3D(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%EMIS3D(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%EDRP)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%EDRP)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YEDRP(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%EDRP(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%SLDIA)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%SLDIA)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YSLDIA(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%SLDIA(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AERAOT)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AERAOT)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAERAOT(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%AERAOT(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AERLISI)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AERLISI)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAERLISI(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%AERLISI(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AEROUT)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AEROUT)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAEROUT(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%AEROUT(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%AEROCLIM)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%AEROCLIM)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YAEROCLIM(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%AEROCLIM(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (ALLOCATED (YDCPG_SL1B%UVP)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%UVP)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YUVP(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%UVP(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YPHYCTY, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%PHYCTY
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRSPEC, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%RSPEC
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YSDSAT, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%SDSAT
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YCVV, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%CVV
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRKTH, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%RKTH
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRKTQV, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%RKTQV
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YRKTQC, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%RKTQC
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YUOM, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%UOM
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YUAL, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%UAL
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YDOM, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%DOM
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YDAL, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%DAL
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YUEN, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%UEN
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YMO, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%MO
  IPNTR = IPNTR + 1
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YUNEBH, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%UNEBH
  IPNTR = IPNTR + 1
ENDIF
IF (ALLOCATED (YDCPG_SL1B%LIMA)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%LIMA)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YLIMA(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%LIMA(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YFSD, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%FSD
  IPNTR = IPNTR + 1
ENDIF
IF (ALLOCATED (YDCPG_SL1B%EXT)) THEN
  DO JFLD = 1, SIZE (YDCPG_SL1B%EXT)
    IF (COND (YDMODEL%YRML_GCONF%YGFL%YEXT(JFLD), YDMODEL)) THEN
      YDVARS_LIST (IPNTR) = YDCPG_SL1B%EXT(JFLD)
      IPNTR = IPNTR + 1
    ENDIF
  ENDDO
ENDIF
IF (COND (YDMODEL%YRML_GCONF%YGFL%YTHRAD, YDMODEL)) THEN
  YDVARS_LIST (IPNTR) = YDCPG_SL1B%THRAD
  IPNTR = IPNTR + 1
ENDIF
    
END SUBROUTINE GREPVARSB 

SUBROUTINE CPG_SL1B_TYPE_INIT (SELF, REGISTRY, NLEV, YDTPTRSLB1 &
                                 & , YDMODEL &
                                 & , YGFL &
                                 & , PERSISTENT &
                                 & , PB1 &
                                 & , KBLKMIN &
                                 & , KBLKMAX &
                                 & )

USE PTRSLB1, ONLY : TPTRSLB1
USE OML_MOD, ONLY: OML_MAX_THREADS

USE YOM_YGFL  , ONLY : TYPE_GFLD
USE TYPE_MODEL, ONLY : MODEL
USE EINT_MOD  , ONLY : SL_STRUCT

CLASS (CPG_SL1B_TYPE),TARGET                 :: SELF
TYPE (FIELD_REGISTRY),              INTENT (IN)    :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TPTRSLB1),                    INTENT (IN)    :: YDTPTRSLB1
TYPE (TYPE_GFLD),                   INTENT (IN)    :: YGFL
TYPE (MODEL),               TARGET, INTENT (IN)    :: YDMODEL
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PB1 (:,:,:)
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

END SUBROUTINE CPG_SL1B_TYPE_INIT

SUBROUTINE CPG_SL1B_TYPE_FINAL (SELF)
CLASS (CPG_SL1B_TYPE)          :: SELF

INTEGER (KIND=JPIM) :: JGFL


END SUBROUTINE CPG_SL1B_TYPE_FINAL

SUBROUTINE CPG_SL1B_TYPE_SYNC_HOST (YDCPG_SL1B)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

CLASS (CPG_SL1B_TYPE) :: YDCPG_SL1B

INTEGER (KIND=JPIM) :: JGFL

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SYNC_HOST', 0, ZHOOK_HANDLE)

CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%U9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%V9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%T9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%PD9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VD9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%NHX9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%UR0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VR0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%ZR0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%WR0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%UR00)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VR00)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%ZR00)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%WR00)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%WRA)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%UR9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VR9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%DBBC9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%DPHI9)
CALL CPG_SL1B_2D_TYPE_SYNC_HOST (YDCPG_SL1B%GWS9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%U0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%V0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%T0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%PD0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VD0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%C9)
CALL CPG_SL1B_2D_TYPE_SYNC_HOST (YDCPG_SL1B%SP9)
CALL CPG_SL1B_2D_TYPE_SYNC_HOST (YDCPG_SL1B%SP0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%C0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%UP9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VP9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%TP9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%U9_SI)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%V9_SI)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%T9_SI)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%PD9_SI)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VD9_SI)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%C9_SI)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%UF9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VF9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%TF9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VDF9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%U9_NL)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%V9_NL)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%T9_NL)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%PD9_NL)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%VD9_NL)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%C9_NL)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%ZR9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%Z9)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%Z0)
CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%ZP9)

DO JGFL = 1, SIZE (YDCPG_SL1B%GFL)
  CALL CPG_SL1B_3D_TYPE_SYNC_HOST (YDCPG_SL1B%GFL (JGFL))
ENDDO

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SYNC_HOST', 1, ZHOOK_HANDLE)

CONTAINS

SUBROUTINE CPG_SL1B_2D_TYPE_SYNC_HOST (YDF2D)

TYPE (CPG_SL1B_2D_TYPE) :: YDF2D

REAL (KIND=JPRB), POINTER :: PTR (:,:)

END SUBROUTINE CPG_SL1B_2D_TYPE_SYNC_HOST  

SUBROUTINE CPG_SL1B_3D_TYPE_SYNC_HOST (YDF3D)

TYPE (CPG_SL1B_3D_TYPE) :: YDF3D

REAL (KIND=JPRB), POINTER :: PTR (:,:,:)

END SUBROUTINE CPG_SL1B_3D_TYPE_SYNC_HOST
END SUBROUTINE CPG_SL1B_TYPE_SYNC_HOST

SUBROUTINE CPG_SL1B_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)
CLASS (CPG_SL1B_TYPE)     :: SELF
INTEGER(KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

INTEGER (KIND=JPIM) :: JGFL

CONTAINS

SUBROUTINE NULLIFY_F3DB (YDF3D)

TYPE (CPG_SL1B_3D_TYPE), INTENT (INOUT) :: YDF3D

IF (.NOT. ASSOCIATED (YDF3D%F_P)) YDF3D%P => ZDUM2
IF (.NOT. ASSOCIATED (YDF3D%F_P_F)) YDF3D%P_F => ZDUM2
IF (.NOT. ASSOCIATED (YDF3D%F_P_SPF)) YDF3D%P_SPF => ZDUM2
IF (.NOT. ASSOCIATED (YDF3D%F_P_SP)) YDF3D%P_SP => ZDUM2
IF (.NOT. ASSOCIATED (YDF3D%F_P_P)) YDF3D%P_P => ZDUM2

END SUBROUTINE NULLIFY_F3DB

SUBROUTINE CPG_SL1B_TYPE_UPDATE_VIEW_F3D (YDF3D)

TYPE (CPG_SL1B_3D_TYPE), INTENT (INOUT) :: YDF3D

END SUBROUTINE CPG_SL1B_TYPE_UPDATE_VIEW_F3D

END SUBROUTINE CPG_SL1B_TYPE_UPDATE_VIEW


SUBROUTINE CPG_SL1B_TYPE_SET (YDCPG_SL1B, YDCPG_OPTS, YDCPG_BNDS, PVALUE)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE

CLASS (CPG_SL1B_TYPE) :: YDCPG_SL1B
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)   :: YDCPG_BNDS
REAL(KIND=JPRB), INTENT(IN) :: PVALUE

INTEGER (KIND=JPIM) :: JFLD, JROF

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SET', 0, ZHOOK_HANDLE)

#ifdef __PGI

DO JFLD = 1, SIZE (YDCPG_SL1B%ZVIEW, 2)
  DO JROF = 1, SIZE (YDCPG_SL1B%ZVIEW, 1)
    YDCPG_SL1B%ZVIEW (JROF, JFLD) = PVALUE
  ENDDO
ENDDO

#else

YDCPG_SL1B%ZVIEW = PVALUE

#endif

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SET', 1, ZHOOK_HANDLE)

END SUBROUTINE CPG_SL1B_TYPE_SET

SUBROUTINE CPG_SL1B_TYPE_SET_HOST_PARALLEL (YDCPG_SL1B, YDCPG_OPTS, YDCPG_BNDS, PVALUE)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE

CLASS (CPG_SL1B_TYPE) :: YDCPG_SL1B
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)   :: YDCPG_BNDS
REAL(KIND=JPRB), INTENT(IN) :: PVALUE

INTEGER (KIND=JPIM) :: JBLK

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SET_HOST_PARALLEL', 0, ZHOOK_HANDLE)

CALL YDCPG_SL1B%SYNC_HOST

!$OMP PARALLEL DO PRIVATE (JBLK)
DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX
  YDCPG_SL1B%ZDATA (:,:,JBLK) = PVALUE
ENDDO
!$OMP END PARALLEL DO

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SET_HOST_PARALLEL', 1, ZHOOK_HANDLE)

END SUBROUTINE CPG_SL1B_TYPE_SET_HOST_PARALLEL

SUBROUTINE CPG_SL1B_TYPE_SET_DEVICE_PARALLEL (YDCPG_SL1B, YDCPG_OPTS, YDCPG_BNDS, PVALUE)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE

CLASS (CPG_SL1B_TYPE) :: YDCPG_SL1B
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)   :: YDCPG_BNDS
REAL(KIND=JPRB), INTENT(IN) :: PVALUE

INTEGER (KIND=JPIM) :: JGFL

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SET_DEVICE_PARALLEL', 0, ZHOOK_HANDLE)

CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%U9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%V9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%T9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%PD9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VD9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%NHX9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%UR0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VR0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%ZR0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%WR0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%UR00)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VR00)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%ZR00)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%WR00)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%WRA)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%UR9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VR9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%DBBC9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%DPHI9)
CALL CPG_SL1_2D_TYPE_SET (YDCPG_SL1B%GWS9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%U0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%V0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%T0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%PD0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VD0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%C9)
CALL CPG_SL1_2D_TYPE_SET (YDCPG_SL1B%SP9)
CALL CPG_SL1_2D_TYPE_SET (YDCPG_SL1B%SP0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%C0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%UP9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VP9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%TP9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%U9_SI)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%V9_SI)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%T9_SI)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%PD9_SI)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VD9_SI)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%C9_SI)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%UF9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VF9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%TF9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VDF9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%U9_NL)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%V9_NL)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%T9_NL)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%PD9_NL)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%VD9_NL)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%C9_NL)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%ZR9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%Z9)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%Z0)
CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%ZP9)

DO JGFL = 1, SIZE (YDCPG_SL1B%GFL)
  CALL CPG_SL1_3D_TYPE_SET (YDCPG_SL1B%GFL (JGFL))
ENDDO

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SET_DEVICE_PARALLEL', 1, ZHOOK_HANDLE)

CONTAINS

SUBROUTINE CPG_SL1_2D_TYPE_SET (YDF2D)

TYPE (CPG_SL1B_2D_TYPE) :: YDF2D

END SUBROUTINE CPG_SL1_2D_TYPE_SET
SUBROUTINE CPG_SL1_3D_TYPE_SET (YDF3D)

TYPE (CPG_SL1B_3D_TYPE) :: YDF3D

REAL (KIND=JPRB), POINTER :: ZF (:,:,:)

END SUBROUTINE CPG_SL1_3D_TYPE_SET

END SUBROUTINE CPG_SL1B_TYPE_SET_DEVICE_PARALLEL


SUBROUTINE CPG_SL1B_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B, YDSL, YDCPG_OPTS, YDCPG_BNDS, YDCPG_SL1F)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE EINT_MOD           , ONLY : SL_STRUCT
USE CPG_SL1F_TYPE_MOD  , ONLY : CPG_SL1F_TYPE

CLASS (CPG_SL1B_TYPE)             :: YDCPG_SL1B
TYPE(SL_STRUCT)     ,INTENT(IN)   :: YDSL
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)   :: YDCPG_BNDS
CLASS (CPG_SL1F_TYPE)             :: YDCPG_SL1F

INTEGER (KIND=JPIM) :: JBLK, JFLD, JROF, JGFL
TYPE(CPG_BNDS_TYPE) :: YLCPG_BNDS

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SHUFFLE_DEVICE_PARALLEL', 0, ZHOOK_HANDLE)

CALL YLCPG_BNDS%INIT (YDCPG_OPTS)

CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%U9, YDCPG_SL1F%U9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%V9, YDCPG_SL1F%V9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%T9, YDCPG_SL1F%T9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%PD9, YDCPG_SL1F%PD9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VD9, YDCPG_SL1F%VD9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%NHX9, YDCPG_SL1F%NHX9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%UR0, YDCPG_SL1F%UR0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VR0, YDCPG_SL1F%VR0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%ZR0, YDCPG_SL1F%ZR0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%WR0, YDCPG_SL1F%WR0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%UR00, YDCPG_SL1F%UR00)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VR00, YDCPG_SL1F%VR00)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%ZR00, YDCPG_SL1F%ZR00)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%WR00, YDCPG_SL1F%WR00)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%WRA, YDCPG_SL1F%WRA)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%UR9, YDCPG_SL1F%UR9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VR9, YDCPG_SL1F%VR9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%DBBC9, YDCPG_SL1F%DBBC9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%DPHI9, YDCPG_SL1F%DPHI9)
CALL CPG_SL1_2D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%GWS9, YDCPG_SL1F%GWS9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%U0, YDCPG_SL1F%U0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%V0, YDCPG_SL1F%V0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%T0, YDCPG_SL1F%T0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%PD0, YDCPG_SL1F%PD0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VD0, YDCPG_SL1F%VD0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%C9, YDCPG_SL1F%C9)
CALL CPG_SL1_2D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%SP9, YDCPG_SL1F%SP9)
CALL CPG_SL1_2D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%SP0, YDCPG_SL1F%SP0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%C0, YDCPG_SL1F%C0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%UP9, YDCPG_SL1F%UP9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VP9, YDCPG_SL1F%VP9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%TP9, YDCPG_SL1F%TP9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%U9_SI, YDCPG_SL1F%U9_SI)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%V9_SI, YDCPG_SL1F%V9_SI)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%T9_SI, YDCPG_SL1F%T9_SI)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%PD9_SI, YDCPG_SL1F%PD9_SI)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VD9_SI, YDCPG_SL1F%VD9_SI)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%C9_SI, YDCPG_SL1F%C9_SI)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%UF9, YDCPG_SL1F%UF9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VF9, YDCPG_SL1F%VF9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%TF9, YDCPG_SL1F%TF9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VDF9, YDCPG_SL1F%VDF9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%U9_NL, YDCPG_SL1F%U9_NL)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%V9_NL, YDCPG_SL1F%V9_NL)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%T9_NL, YDCPG_SL1F%T9_NL)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%PD9_NL, YDCPG_SL1F%PD9_NL)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%VD9_NL, YDCPG_SL1F%VD9_NL)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%C9_NL, YDCPG_SL1F%C9_NL)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%ZR9, YDCPG_SL1F%ZR9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%Z9, YDCPG_SL1F%Z9)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%Z0, YDCPG_SL1F%Z0)
CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%ZP9, YDCPG_SL1F%ZP9)

DO JGFL = 1, SIZE (YDCPG_SL1F%GFL)
  CALL CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDCPG_SL1B%GFL (JGFL), YDCPG_SL1F%GFL (JGFL))
ENDDO

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SHUFFLE_DEVICE_PARALLEL', 1, ZHOOK_HANDLE)

CONTAINS

SUBROUTINE CPG_SL1_2D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDF2DB, YDF2DF)

USE CPG_SL1F_TYPE_MOD, ONLY : CPG_SL1F_2D_TYPE

TYPE (CPG_SL1B_2D_TYPE) :: YDF2DB
TYPE (CPG_SL1F_2D_TYPE) :: YDF2DF

REAL (KIND=JPRB), POINTER :: Z2DB (:,:), Z2DF (:)
INTEGER (KIND=JPIM) :: JBLK, JROF

END SUBROUTINE CPG_SL1_2D_TYPE_SHUFFLE_DEVICE_PARALLEL

SUBROUTINE CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL (YDF3DB, YDF3DF)

USE CPG_SL1F_TYPE_MOD, ONLY : CPG_SL1F_3D_TYPE

TYPE (CPG_SL1B_3D_TYPE) :: YDF3DB
TYPE (CPG_SL1F_3D_TYPE) :: YDF3DF

REAL (KIND=JPRB), POINTER :: Z3DB (:,:,:), Z3DF (:,:)
INTEGER (KIND=JPIM) :: JBLK, JROF, JLEV

END SUBROUTINE CPG_SL1_3D_TYPE_SHUFFLE_DEVICE_PARALLEL

END SUBROUTINE CPG_SL1B_TYPE_SHUFFLE_DEVICE_PARALLEL 

SUBROUTINE CPG_SL1B_TYPE_SHUFFLE_HOST_PARALLEL (YDCPG_SL1B, YDSL, YDCPG_OPTS, YDCPG_BNDS, YDCPG_SL1F)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE EINT_MOD           , ONLY : SL_STRUCT
USE CPG_SL1F_TYPE_MOD  , ONLY : CPG_SL1F_TYPE

CLASS (CPG_SL1B_TYPE)             :: YDCPG_SL1B
TYPE(SL_STRUCT)     ,INTENT(IN)   :: YDSL
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)   :: YDCPG_BNDS
CLASS (CPG_SL1F_TYPE)             :: YDCPG_SL1F

INTEGER (KIND=JPIM) :: JBLK
TYPE(CPG_BNDS_TYPE) :: YLCPG_BNDS

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SHUFFLE_HOST_PARALLEL', 0, ZHOOK_HANDLE)

CALL YDCPG_SL1F%SYNC_HOST
CALL YDCPG_SL1B%SYNC_HOST

CALL YLCPG_BNDS%INIT (YDCPG_OPTS)

!$OMP PARALLEL DO PRIVATE (JBLK) FIRSTPRIVATE (YLCPG_BNDS)
DO JBLK = YDCPG_OPTS%JBLKMIN, YDCPG_OPTS%JBLKMAX

  CALL YLCPG_BNDS%UPDATE (JBLK)

  CALL CPG_SL1B_TYPE_SHUFFLE_PB1 (YDCPG_SL1B%ZDATA (:,:,JBLK), YDSL, YDCPG_OPTS, YLCPG_BNDS, YDCPG_SL1F%ZDATA (:,:))

ENDDO
!$OMP END PARALLEL DO

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SHUFFLE_HOST_PARALLEL', 1, ZHOOK_HANDLE)

END SUBROUTINE CPG_SL1B_TYPE_SHUFFLE_HOST_PARALLEL 

SUBROUTINE CPG_SL1B_TYPE_SHUFFLE (YDCPG_SL1B, YDSL, YDCPG_OPTS, YDCPG_BNDS, YDCPG_SL1F)

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE EINT_MOD           , ONLY : SL_STRUCT
USE CPG_SL1F_TYPE_MOD  , ONLY : CPG_SL1F_TYPE

CLASS (CPG_SL1B_TYPE)             :: YDCPG_SL1B
TYPE(SL_STRUCT)     ,INTENT(IN)   :: YDSL
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)   :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)   :: YDCPG_BNDS
CLASS (CPG_SL1F_TYPE)             :: YDCPG_SL1F

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SHUFFLE', 0, ZHOOK_HANDLE)

CALL CPG_SL1B_TYPE_SHUFFLE_PB1 (YDCPG_SL1B%ZVIEW, YDSL, YDCPG_OPTS, YDCPG_BNDS, YDCPG_SL1F%ZDATA)

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SHUFFLE', 1, ZHOOK_HANDLE)

END SUBROUTINE CPG_SL1B_TYPE_SHUFFLE

SUBROUTINE CPG_SL1B_TYPE_SHUFFLE_PB1 (PB1B, YDSL, YDCPG_OPTS, YDCPG_BNDS, PB1F) 

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE
USE EINT_MOD           , ONLY : SL_STRUCT

REAL (KIND=JPRB)    ,INTENT(IN)    :: PB1B (:,:)
TYPE(SL_STRUCT)     ,INTENT(IN)    :: YDSL
TYPE(CPG_OPTS_TYPE) ,INTENT(IN)    :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN)    :: YDCPG_BNDS
REAL (KIND=JPRB)    ,INTENT(INOUT) :: PB1F (:,:)

INTEGER (KIND=JPIM) :: JFLD, JROF, IFLDSLB1

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SHUFFLE_PB1', 0, ZHOOK_HANDLE)

IFLDSLB1 = SIZE (PB1B, 2)

! Optimization by SIMD, equivalent to vectorization of the outerloop,
! more efficient and portable than machine-dependent prefetching. REK.
#ifndef __ARM_LINUX_COMPILER__
#endif
DO JFLD=1,IFLDSLB1
  !DIR$ NEXTSCALAR
  !DIR$ IVDEP
  !DIR$ NOINTERCHANGE
  !DIR$ LOOP COUNT AVG(16)
  DO JROF=YDCPG_BNDS%KSTGLO,YDCPG_BNDS%KSTGLO+YDCPG_BNDS%KFDIA-1
    PB1F(YDSL%NSLCORE(JROF),JFLD)=PB1B(JROF-YDCPG_BNDS%KSTGLO+1,JFLD)
  ENDDO
ENDDO

IF (LHOOK) CALL DR_HOOK ('CPG_SL1B_TYPE_SHUFFLE', 1, ZHOOK_HANDLE)

END SUBROUTINE CPG_SL1B_TYPE_SHUFFLE_PB1



END MODULE CPG_SL1B_TYPE_MOD


