
MODULE CPG_OPTS_TYPE_MOD
USE PARKIND1,ONLY:JPIM, JPRB
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE YOMCLI,ONLY:TCLI
USE SURFACE_FIELDS_MIX,ONLY:TYPE_SURF_GEN

IMPLICIT NONE


TYPE CPG_DIM_VAR_TYPE
  INTEGER (KIND=JPIM)::ILEVT1I
  INTEGER (KIND=JPIM)::ILEVT1F
ENDTYPE


TYPE CPG_DIMS_VARS_TYPE
  TYPE (CPG_DIM_VAR_TYPE)::U
  TYPE (CPG_DIM_VAR_TYPE)::V
  TYPE (CPG_DIM_VAR_TYPE)::T
  TYPE (CPG_DIM_VAR_TYPE)::SVD
  TYPE (CPG_DIM_VAR_TYPE)::Q
  TYPE (CPG_DIM_VAR_TYPE)::I
  TYPE (CPG_DIM_VAR_TYPE)::L
  TYPE (CPG_DIM_VAR_TYPE)::IMF
  TYPE (CPG_DIM_VAR_TYPE)::LMF
  TYPE (CPG_DIM_VAR_TYPE)::HLMF
  TYPE (CPG_DIM_VAR_TYPE)::HIMF
  TYPE (CPG_DIM_VAR_TYPE)::LCONV
  TYPE (CPG_DIM_VAR_TYPE)::ICONV
  TYPE (CPG_DIM_VAR_TYPE)::RCONV
  TYPE (CPG_DIM_VAR_TYPE)::SCONV
  TYPE (CPG_DIM_VAR_TYPE)::IRAD
  TYPE (CPG_DIM_VAR_TYPE)::LRAD
  TYPE (CPG_DIM_VAR_TYPE)::S
  TYPE (CPG_DIM_VAR_TYPE)::R
  TYPE (CPG_DIM_VAR_TYPE)::G
  TYPE (CPG_DIM_VAR_TYPE)::H
  TYPE (CPG_DIM_VAR_TYPE)::TKE
  TYPE (CPG_DIM_VAR_TYPE)::TTE
  TYPE (CPG_DIM_VAR_TYPE)::EFB1
  TYPE (CPG_DIM_VAR_TYPE)::EFB2
  TYPE (CPG_DIM_VAR_TYPE)::EFB3
  TYPE (CPG_DIM_VAR_TYPE)::A
  TYPE (CPG_DIM_VAR_TYPE)::AMF
  TYPE (CPG_DIM_VAR_TYPE)::WMFC
  TYPE (CPG_DIM_VAR_TYPE)::HLCFMF
  TYPE (CPG_DIM_VAR_TYPE)::HICFMF
  TYPE (CPG_DIM_VAR_TYPE)::O3
  TYPE (CPG_DIM_VAR_TYPE)::SRC
  TYPE (CPG_DIM_VAR_TYPE)::MXL
  TYPE (CPG_DIM_VAR_TYPE)::SHTUR
  TYPE (CPG_DIM_VAR_TYPE)::FQTUR
  TYPE (CPG_DIM_VAR_TYPE)::FSTUR
  TYPE (CPG_DIM_VAR_TYPE)::CPF
  TYPE (CPG_DIM_VAR_TYPE)::SPF
  TYPE (CPG_DIM_VAR_TYPE)::CVGQ
  TYPE (CPG_DIM_VAR_TYPE)::QVA
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::GHG (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::CHEM (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::AERO (:)
  TYPE (CPG_DIM_VAR_TYPE)::LRCH4
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::FORC (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::EZDIAG (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::ERA40 (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::NOGW (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::EMIS3D (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::EDRP (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::SLDIA (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::AERAOT (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::AERLISI (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::AEROUT (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::AEROCLIM (:)
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::UVP (:)
  TYPE (CPG_DIM_VAR_TYPE)::PHYCTY
  TYPE (CPG_DIM_VAR_TYPE)::RSPEC
  TYPE (CPG_DIM_VAR_TYPE)::SDSAT
  TYPE (CPG_DIM_VAR_TYPE)::CVV
  TYPE (CPG_DIM_VAR_TYPE)::RKTH
  TYPE (CPG_DIM_VAR_TYPE)::RKTQV
  TYPE (CPG_DIM_VAR_TYPE)::RKTQC
  TYPE (CPG_DIM_VAR_TYPE)::UOM
  TYPE (CPG_DIM_VAR_TYPE)::UAL
  TYPE (CPG_DIM_VAR_TYPE)::DOM
  TYPE (CPG_DIM_VAR_TYPE)::DAL
  TYPE (CPG_DIM_VAR_TYPE)::UEN
  TYPE (CPG_DIM_VAR_TYPE)::MO
  TYPE (CPG_DIM_VAR_TYPE)::UNEBH
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::LIMA (:)
  TYPE (CPG_DIM_VAR_TYPE)::FSD
  TYPE (CPG_DIM_VAR_TYPE), ALLOCATABLE::EXT (:)
  TYPE (CPG_DIM_VAR_TYPE)::THRAD
  
  
ENDTYPE CPG_DIMS_VARS_TYPE


TYPE CPG_DIMS_SURF_TYPE
  TYPE (TYPE_SURF_GEN)::YSP_SBD
  TYPE (TYPE_SURF_GEN)::YSP_SGD
  TYPE (TYPE_SURF_GEN)::YSP_SLD
  TYPE (TYPE_SURF_GEN)::YSP_RRD
  TYPE (TYPE_SURF_GEN)::YSP_CLD
  TYPE (TYPE_SURF_GEN)::YSP_OMD
  TYPE (TYPE_SURF_GEN)::YSP_EPD
  TYPE (TYPE_SURF_GEN)::YSP_X2D
  TYPE (TYPE_SURF_GEN)::YSP_CID
  TYPE (TYPE_SURF_GEN)::YSD_VFD
  TYPE (TYPE_SURF_GEN)::YSD_VHD
  TYPE (TYPE_SURF_GEN)::YSD_VKD
  TYPE (TYPE_SURF_GEN)::YSD_VPD
  TYPE (TYPE_SURF_GEN)::YSD_VVD
  TYPE (TYPE_SURF_GEN)::YSD_VAD
  TYPE (TYPE_SURF_GEN)::YSD_VND
  TYPE (TYPE_SURF_GEN)::YSD_V2D
  TYPE (TYPE_SURF_GEN)::YSD_V3D
  TYPE (TYPE_SURF_GEN)::YSD_VDD
  TYPE (TYPE_SURF_GEN)::YSD_SMD
  TYPE (TYPE_SURF_GEN)::YSD_WSD
  TYPE (TYPE_SURF_GEN)::YSD_WWD
  TYPE (TYPE_SURF_GEN)::YSD_PFD
  TYPE (TYPE_SURF_GEN)::YSD_XAD
  TYPE (TYPE_SURF_GEN)::YSD_DID
  TYPE (TYPE_SURF_GEN)::YSD_XPD
  TYPE (TYPE_SURF_GEN)::YSD_XP2D
  TYPE (TYPE_SURF_GEN)::YSD_X2D
  TYPE (TYPE_SURF_GEN)::YSD_SFOD
  TYPE (TYPE_SURF_GEN)::YSD_SFLD
  TYPE (TYPE_SURF_GEN)::YSD_VCD
  
  
ENDTYPE


TYPE CPG_BNDS_TYPE
  INTEGER (KIND=JPIM)::KIDIA
  INTEGER (KIND=JPIM)::KFDIA
  INTEGER (KIND=JPIM)::KFDIE
  INTEGER (KIND=JPIM)::KIDIE
  INTEGER (KIND=JPIM)::KBL
  INTEGER (KIND=JPIM)::KSTGLO
  INTEGER (KIND=JPIM)::KLON
  INTEGER (KIND=JPIM)::KGPTOT
  INTEGER (KIND=JPIM)::KGPCOMP
  
  
CONTAINS
  GENERIC :: INIT => CPG_BNDS_TYPE_INIT_OPTS, CPG_BNDS_TYPE_INIT
  PROCEDURE, PRIVATE :: CPG_BNDS_TYPE_INIT_OPTS 
  PROCEDURE, PRIVATE :: CPG_BNDS_TYPE_INIT
  PROCEDURE :: UPDATE => CPG_BNDS_TYPE_UPDATE
  
  
ENDTYPE CPG_BNDS_TYPE


TYPE CPG_SURF_LSET_OPTS_TYPE
  LOGICAL::LSET=.FALSE.
ENDTYPE


TYPE CPG_SURF_SBP_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YQ
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTL
ENDTYPE


TYPE CPG_SURF_SGP_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YA
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YW
ENDTYPE


TYPE CPG_SURF_SLP_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLICT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLMLT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLTLT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLBLT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLSHF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLICD
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLMLD
ENDTYPE


TYPE CPG_SURF_RRP_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YFC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YIC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YFP1
ENDTYPE


TYPE CPG_SURF_CLP_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCLS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YHUCLS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUCLS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVCLS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YNUCLS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YNVCLS
ENDTYPE


TYPE CPG_SURF_OMP_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVO
ENDTYPE


TYPE CPG_SURF_EPP_OPTS_TYPE
ENDTYPE


TYPE CPG_SURF_X2P_OPTS_TYPE
ENDTYPE


TYPE CPG_SURF_CIP_OPTS_TYPE
ENDTYPE


TYPE CPG_SURF_VFD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YZ0F
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YALBF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YEMISF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YGETRL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLSM
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVEG
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVRLAN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVRLDI
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSIG
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YALBSF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLAN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSST
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSSS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLZ0H
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCVL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCO2TYP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCVH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCUR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTVL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTVH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLAIL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLAIH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YFWET
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSOTY
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCLK
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCI
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUCUR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVCUR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YZ0RLF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCGPP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCREC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSDFOR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YALUVP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YALUVD
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YALNIP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YALNID
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YFP1
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSO2DD
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDMSO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YURBF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YFCA1
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YFCA2
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YAERDEP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YAERLTS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YAERSCC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDSF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YNUDM
ENDTYPE


TYPE CPG_SURF_VHD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCCH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSCCH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YBCCH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPBLH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSPSH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YQSH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPCL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPSL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPCN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPSN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YEVA
ENDTYPE


TYPE CPG_SURF_VKD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUDGRO
ENDTYPE


TYPE CPG_SURF_VPD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTPC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YWPC
ENDTYPE


TYPE CPG_SURF_VVD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YARG
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSAB
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YD2
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YIVEG
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YRSMIN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLAI
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YHV
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YZ0H
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YALS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YALV
ENDTYPE


TYPE CPG_SURF_VAD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSEA
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLAN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSOO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDES
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSUL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVOL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSS1
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSS2
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSS3
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDD1
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDD2
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDD3
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YOM1
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YOM2
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YBC1
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YBC2
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSU
ENDTYPE


TYPE CPG_SURF_VND_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTOP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YBAS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YACPR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YACCPR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YACCPR5
ENDTYPE


TYPE CPG_SURF_V2D_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YOCDEP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUSTRC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVSTRC
ENDTYPE


TYPE CPG_SURF_V3D_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDIFM
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDIFT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDIFS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YADVT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YADVS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTRI0
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTRI1
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSWDK
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YZO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YHO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YHO_INV
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUOC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVOC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YOTKE
ENDTYPE


TYPE CPG_SURF_VDD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLSP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YFZRA
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YBLD
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSSHF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSLHF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YNEE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YGPP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YREC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMSL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y10U
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y10V
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y2T
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y2D
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y2SH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSSR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSTR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTSR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTTR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YEWSS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YNSSS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPEV
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCCC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLCC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMCC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YHCC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLGWS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMGWS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YGWD
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMX2T
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMN2T
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YRO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSRO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSSRO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YALB
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YIEWSS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YINSSS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YISSHF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YIE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YINEE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YIGPP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YIREC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YICH4
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCSF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLSSF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMXTPR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMNTPR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTPR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLSRR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCRR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLSSFR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCSFR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPTYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YILSPF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YZ0F
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLZ0H
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVIWVE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVIWVN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCWV
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCLW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCIW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCRW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCSW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCSLW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSSRD
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSTRD
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSSRDC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSTRDC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YBLH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSUND
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSPAR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSUVB
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSFDIR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSCDIR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSDSRP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCAPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMUCAPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMLCAPE50
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMLCAPE100
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPDEPL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCAPES
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTROPOTP
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTSRC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTTRC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSSRC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSTRC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YES
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSMLT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y10FG
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y10FGCV
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YI10FG
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLSPF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTCO3
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVIMD
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSPARC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YSTINC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCBASE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y0DEGL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YM10DEGL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVISIH
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCIN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMLCIN50
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YMLCIN100
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YKINDEX
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTTINDEX
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCBASEA
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCTOPC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YZTWETB0
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YZTWETB1
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y100U
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y100V
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y200U
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y200V
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YZUST
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y10NU
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::Y10NV
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDNDZN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDNDZA
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YDCTB
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTPLB
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTPLT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODSS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODDU
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODOM
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODBC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODSU
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODNI
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODAM
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODSOA
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODVFA
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODVSU
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YODTOACC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YAEPM1
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YAEPM25
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YAEPM10
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUVBED
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUVBEDCS
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLITOTI
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YLICGI
ENDTYPE


TYPE CPG_SURF_SMD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCLBT
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCSBT
ENDTYPE


TYPE CPG_SURF_WSD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCHAR
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCHARHQ
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUSTOKES
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVSTOKES
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTAUOCX
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YTAUOCY
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPHIOC
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YWSEMEAN
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YWSFMEAN
ENDTYPE


TYPE CPG_SURF_WWD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YU10N
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YV10N
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YRHO
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YZIL
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCIF
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YCLK
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUSTRW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVSTRW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YUCURW
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YVCURW
ENDTYPE


TYPE CPG_SURF_PFD_OPTS_TYPE
ENDTYPE


TYPE CPG_SURF_XAD_OPTS_TYPE
ENDTYPE


TYPE CPG_SURF_DID_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YXEDR
ENDTYPE


TYPE CPG_SURF_XPD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPRECIP
ENDTYPE


TYPE CPG_SURF_XP2D_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YPRECIP2
ENDTYPE


TYPE CPG_SURF_X2D_OPTS_TYPE
ENDTYPE


TYPE CPG_SURF_SFOD_OPTS_TYPE
ENDTYPE


TYPE CPG_SURF_SFLD_OPTS_TYPE
ENDTYPE


TYPE CPG_SURF_VCD_OPTS_TYPE
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YA
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YB
  TYPE (CPG_SURF_LSET_OPTS_TYPE)::YC
ENDTYPE


TYPE CPG_OPTS_SURF_TYPE
  TYPE (CPG_SURF_SBP_OPTS_TYPE)::YSP_SB
  TYPE (CPG_SURF_SGP_OPTS_TYPE)::YSP_SG
  TYPE (CPG_SURF_SLP_OPTS_TYPE)::YSP_SL
  TYPE (CPG_SURF_RRP_OPTS_TYPE)::YSP_RR
  TYPE (CPG_SURF_CLP_OPTS_TYPE)::YSP_CL
  TYPE (CPG_SURF_OMP_OPTS_TYPE)::YSP_OM
  TYPE (CPG_SURF_EPP_OPTS_TYPE)::YSP_EP
  TYPE (CPG_SURF_X2P_OPTS_TYPE)::YSP_X2
  TYPE (CPG_SURF_CIP_OPTS_TYPE)::YSP_CI
  TYPE (CPG_SURF_VFD_OPTS_TYPE)::YSD_VF
  TYPE (CPG_SURF_VHD_OPTS_TYPE)::YSD_VH
  TYPE (CPG_SURF_VKD_OPTS_TYPE)::YSD_VK
  TYPE (CPG_SURF_VPD_OPTS_TYPE)::YSD_VP
  TYPE (CPG_SURF_VVD_OPTS_TYPE)::YSD_VV
  TYPE (CPG_SURF_VAD_OPTS_TYPE)::YSD_VA
  TYPE (CPG_SURF_VND_OPTS_TYPE)::YSD_VN
  TYPE (CPG_SURF_V2D_OPTS_TYPE)::YSD_V2
  TYPE (CPG_SURF_V3D_OPTS_TYPE)::YSD_V3
  TYPE (CPG_SURF_VDD_OPTS_TYPE)::YSD_VD
  TYPE (CPG_SURF_SMD_OPTS_TYPE)::YSD_SM
  TYPE (CPG_SURF_WSD_OPTS_TYPE)::YSD_WS
  TYPE (CPG_SURF_WWD_OPTS_TYPE)::YSD_WW
  TYPE (CPG_SURF_PFD_OPTS_TYPE)::YSD_PF
  TYPE (CPG_SURF_XAD_OPTS_TYPE)::YSD_XA
  TYPE (CPG_SURF_DID_OPTS_TYPE)::YSD_DI
  TYPE (CPG_SURF_XPD_OPTS_TYPE)::YSD_XP
  TYPE (CPG_SURF_XP2D_OPTS_TYPE)::YSD_XP2
  TYPE (CPG_SURF_X2D_OPTS_TYPE)::YSD_X2
  TYPE (CPG_SURF_SFOD_OPTS_TYPE)::YSD_SFO
  TYPE (CPG_SURF_SFLD_OPTS_TYPE)::YSD_SFL
  TYPE (CPG_SURF_VCD_OPTS_TYPE)::YSD_VC
  
  
ENDTYPE


TYPE CPG_OPTS_TYPE
  INTEGER (KIND=JPIM)::KLON
  INTEGER (KIND=JPIM)::KFLEVG
  INTEGER (KIND=JPIM)::KGPTOT
  INTEGER (KIND=JPIM)::KGPBLKS
  INTEGER (KIND=JPIM)::KGPCOMP
  INTEGER (KIND=JPIM)::KGPTOTB
  INTEGER (KIND=JPIM)::JBLKMIN
  INTEGER (KIND=JPIM)::JBLKMAX
  INTEGER (KIND=JPIM)::KGL1
  INTEGER (KIND=JPIM)::KGL2
  INTEGER (KIND=JPIM)::NSTEP
  INTEGER (KIND=JPIM)::KTDIA
  INTEGER (KIND=JPIM)::KVCLIS
  INTEGER (KIND=JPIM)::NDTPREC
  INTEGER (KIND=JPIM)::NDTPREC2
  INTEGER (KIND=JPIM)::NDTPRECCUR
  INTEGER (KIND=JPIM)::NDTPRECCUR2
  INTEGER (KIND=JPIM)::KTSSG
  INTEGER (KIND=JPIM)::KGRADIENTS
  INTEGER (KIND=JPIM)::KMAXDRAFT
  INTEGER (KIND=JPIM)::KSW
  INTEGER (KIND=JPIM)::NPROC
  INTEGER (KIND=JPIM)::NCONF
  INTEGER (KIND=JPIM)::N2DINI
  TYPE (CPG_OPTS_SURF_TYPE)::YRSURF_OPTS
  TYPE (CPG_DIMS_SURF_TYPE)::YRSURF_DIMS
  TYPE (CPG_DIMS_VARS_TYPE)::YRVARS_DIMS
  LOGICAL::LCONFX, L_DFISTEP, LFSTEP, LDIAB, LSLPHY, LUSEPB1
  REAL (KIND=JPRB)::ZDT, ZDTPHY, ZTE, ZBETADT
  TYPE (TCLI)::YRCLI
  INTEGER (KIND=JPIM)::NSSSSS
  INTEGER (KIND=JPIM)::NFNUDG
  INTEGER (KIND=JPIM)::NINDAT
  LOGICAL::LAROME
  LOGICAL::LCALLSFX
  LOGICAL::LCORWAT
  LOGICAL::LECMWF
  LOGICAL::LINITER
  LOGICAL::LELAM
  LOGICAL::LNUDG
  LOGICAL::LRPLANE
  LOGICAL::LSFORC
  LOGICAL::LSFORCS
  REAL (KIND=JPRB)::RPLDARE
  REAL (KIND=JPRB)::RPLRG
  REAL (KIND=JPRB)::TOPPRES
  REAL (KIND=JPRB)::RPSTRA
  REAL (KIND=JPRB)::RPTROP
  REAL (KIND=JPRB)::RTSUR
  REAL (KIND=JPRB), ALLOCATABLE::XPNUDG (:)
  
  
  
ENDTYPE CPG_OPTS_TYPE

CONTAINS


  SUBROUTINE CPG_BNDS_TYPE_INIT_OPTS (SELF, YDCPG_OPTS)
    CLASS(CPG_BNDS_TYPE) :: SELF
    TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS


  END SUBROUTINE CPG_BNDS_TYPE_INIT_OPTS

  SUBROUTINE CPG_BNDS_TYPE_INIT (SELF, KLON, KGPTOT)
    CLASS(CPG_BNDS_TYPE) :: SELF
    INTEGER (KIND=JPIM), INTENT (IN) :: KLON
    INTEGER (KIND=JPIM), INTENT (IN) :: KGPTOT


  END SUBROUTINE CPG_BNDS_TYPE_INIT

  SUBROUTINE CPG_BNDS_TYPE_UPDATE(SELF, IBL)
    CLASS(CPG_BNDS_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: IBL

  END SUBROUTINE CPG_BNDS_TYPE_UPDATE







ENDMODULE CPG_OPTS_TYPE_MOD
