MODULE CPG_TYPE_MOD

!$ACDC methods --methods-list=host,wipe,copy --skip-components cpg --field-api --field-api-class cpg

USE FIELD_MODULE
USE FIELD_ARRAY_MODULE
USE FIELD_REGISTRY_MOD
USE PARKIND1, ONLY : JPRB, JPIM, JPIB
USE YOM_YGFL, ONLY : TYPE_GFL_COMP

IMPLICIT NONE

TYPE CPG_XYBDER_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_LNPRL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LNPRL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: LNPRL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_LNPRL => NULL ()
  INTEGER (KIND=JPIM) :: IP_LNPRM = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LNPRM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: LNPRM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_LNPRM => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPHL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPHL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPHL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPHL => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPHM = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPHM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPHM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPHM => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPHPLL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPHPLL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPHPLL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPHPLL => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPHPLM = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPHPLM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPHPLM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPHPLM => NULL ()
  INTEGER (KIND=JPIM) :: IP_COEFD = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: COEFD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: COEFD (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_COEFD => NULL ()
  INTEGER (KIND=JPIM) :: IP_COEFA = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: COEFA (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: COEFA (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_COEFA => NULL ()
  INTEGER (KIND=JPIM) :: IP_COEFAPL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: COEFAPL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: COEFAPL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_COEFAPL => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_XYBDER_TYPE_INIT
  PROCEDURE :: CONFORM => CPG_XYBDER_TYPE_CONFORM
  PROCEDURE :: RESIZE => CPG_XYBDER_TYPE_RESIZE
  PROCEDURE :: UPDATE_VIEW => CPG_XYBDER_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_XYBDER_TYPE_FINAL
END TYPE CPG_XYBDER_TYPE

TYPE CPG_XYB_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_DELP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DELP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DELP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_DELP => NULL ()
  INTEGER (KIND=JPIM) :: IP_RDELP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RDELP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RDELP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RDELP => NULL ()
  INTEGER (KIND=JPIM) :: IP_LNPR = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LNPR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: LNPR (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_LNPR => NULL ()
  INTEGER (KIND=JPIM) :: IP_ALPH = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ALPH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ALPH (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_ALPH => NULL ()
  INTEGER (KIND=JPIM) :: IP_RTGR = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RTGR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RTGR (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RTGR => NULL ()
  INTEGER (KIND=JPIM) :: IP_RPRE = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RPRE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RPRE (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RPRE => NULL ()
  INTEGER (KIND=JPIM) :: IP_RPP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RPP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RPP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RPP => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_XYB_TYPE_INIT
  PROCEDURE :: CONFORM => CPG_XYB_TYPE_CONFORM
  PROCEDURE :: RESIZE => CPG_XYB_TYPE_RESIZE
  PROCEDURE :: UPDATE_VIEW => CPG_XYB_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_XYB_TYPE_FINAL
END TYPE CPG_XYB_TYPE

TYPE CPG_HWIND_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_UH = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: UH (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_UH => NULL ()
  INTEGER (KIND=JPIM) :: IP_VH = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: VH (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_VH => NULL ()
  INTEGER (KIND=JPIM) :: IP_WWI = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WWI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: WWI (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_WWI => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_HWIND_TYPE_INIT
  PROCEDURE :: CONFORM => CPG_HWIND_TYPE_CONFORM
  PROCEDURE :: RESIZE => CPG_HWIND_TYPE_RESIZE
  PROCEDURE :: UPDATE_VIEW => CPG_HWIND_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_HWIND_TYPE_FINAL
END TYPE CPG_HWIND_TYPE

TYPE CPG_RCP_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_CP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: CP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_CP => NULL ()
  INTEGER (KIND=JPIM) :: IP_R = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: R (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_R => NULL ()
  INTEGER (KIND=JPIM) :: IP_KAP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KAP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: KAP (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_KAP => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_RCP_TYPE_INIT
  PROCEDURE :: CONFORM => CPG_RCP_TYPE_CONFORM
  PROCEDURE :: RESIZE => CPG_RCP_TYPE_RESIZE
  PROCEDURE :: UPDATE_VIEW => CPG_RCP_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_RCP_TYPE_FINAL
END TYPE CPG_RCP_TYPE

TYPE CPG_CTY_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_EVEL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EVEL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: EVEL (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_EVEL => NULL ()
  INTEGER (KIND=JPIM) :: IP_VVEL = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: VVEL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: VVEL (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_VVEL => NULL ()
  INTEGER (KIND=JPIM) :: IP_PSDIV = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PSDIV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PSDIV (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PSDIV => NULL ()
  INTEGER (KIND=JPIM) :: IP_PSDVBC = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PSDVBC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PSDVBC (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PSDVBC => NULL ()
  INTEGER (KIND=JPIM) :: IP_DIVDP = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DIVDP (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DIVDP (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_DIVDP => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_CTY_TYPE_INIT
  PROCEDURE :: CONFORM => CPG_CTY_TYPE_CONFORM
  PROCEDURE :: RESIZE => CPG_CTY_TYPE_RESIZE
  PROCEDURE :: UPDATE_VIEW => CPG_CTY_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_CTY_TYPE_FINAL
END TYPE CPG_CTY_TYPE

TYPE CPG_TND_TYPE
  LOGICAL :: LOWNED = .FALSE.
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZVIEW (:,:,:) => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ZDATA (:,:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DATA => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDU = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDU (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDU (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDU => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDV = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDV (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDV => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDU_NOC = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDU_NOC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDU_NOC (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDU_NOC => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDV_NOC = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDV_NOC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDV_NOC (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDV_NOC => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDT = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDT (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDT (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDT => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDPD = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDPD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDPD (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDPD => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDVD = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDVD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDVD (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDVD => NULL ()
  INTEGER (KIND=JPIM) :: IP_TNDGW = -1
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TNDGW (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TNDGW (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_TNDGW => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_TND_TYPE_INIT
  PROCEDURE :: CONFORM => CPG_TND_TYPE_CONFORM
  PROCEDURE :: RESIZE => CPG_TND_TYPE_RESIZE
  PROCEDURE :: UPDATE_VIEW => CPG_TND_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_TND_TYPE_FINAL
END TYPE CPG_TND_TYPE

TYPE CPG_DYN_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: OROGL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: OROGL (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_OROGL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: OROGM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: OROGM (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_OROGM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: OROGLL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: OROGLL (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_OROGLL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: OROGLM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: OROGLM (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_OROGLM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: OROGMM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: OROGMM (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_OROGMM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PHI (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PHI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PRE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PRE (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PRE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHIF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PHIF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PHIF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PREF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PREF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: PREL (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_PREL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: PREM (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_PREM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NHY (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NHY (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_NHY => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWFT (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GWFT (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_GWFT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KENE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: KENE (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_KENE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NHX (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NHX (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_NHX => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHIFL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PHIFL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PHIFL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHIFM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PHIFM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PHIFM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RTL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RTL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RTL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RTM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RTM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RTM => NULL ()
  TYPE (CPG_RCP_TYPE) :: RCP
  TYPE (CPG_CTY_TYPE) :: CTY
  TYPE (CPG_HWIND_TYPE) :: UVH
  TYPE (CPG_XYB_TYPE) :: XYB
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DBBC (:) => NULL ()
!>REAL (KIND=JPRB)                      :: DBBC (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_DBBC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: GWS (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_GWS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWFL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GWFL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_GWFL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWFM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GWFM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_GWFM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: GWT (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: GWT (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_GWT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NHPREF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NHPREF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_NHPREF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NHPREH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NHPREH (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_NHPREH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QCHAL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QCHAL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_QCHAL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QCHAM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QCHAM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_QCHAM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RDPHI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RDPHI (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_RDPHI => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_DYN_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_DYN_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_DYN_TYPE_FINAL
END TYPE CPG_DYN_TYPE

TYPE CPG_PHY_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PRE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PRE (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PRE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PREF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PREF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREHYD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PREHYD (NPROMA, 0:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PREHYD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PREHYDF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PREHYDF (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_PREHYDF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: WL (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_WL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: WM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: WM (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_WM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: W (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: W (NPROMA, 1:NLEV)
  CLASS (FIELD_3RB), POINTER :: F_W => NULL ()
  TYPE (CPG_XYB_TYPE) :: XYB

CONTAINS
  PROCEDURE :: INIT => CPG_PHY_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_PHY_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_PHY_TYPE_FINAL
END TYPE CPG_PHY_TYPE

TYPE CPG_MISC_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: NEB (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: NEB (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_NEB => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QLI (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QLI (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QLI => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QICE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QICE (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QICE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QRAIN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QRAIN (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QRAIN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QSNOW (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QSNOW (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QSNOW => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QGRAUPEL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QGRAUPEL (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_QGRAUPEL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RH (NPROMA, 1:YDCPG_OPTS%KFLEVG)
  CLASS (FIELD_3RB), POINTER :: F_RH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QS (:) => NULL ()
!>REAL (KIND=JPRB)                      :: QS (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_QS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QSOL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: QSOL (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_QSOL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DHSF (:) => NULL ()
!>REAL (KIND=JPRB)                      :: DHSF (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_DHSF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CLCT (:) => NULL ()
!>REAL (KIND=JPRB)                      :: CLCT (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_CLCT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LSM (:) => NULL ()
!>REAL (KIND=JPRB)                      :: LSM (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_LSM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TSOL (:) => NULL ()
!>REAL (KIND=JPRB)                      :: TSOL (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_TSOL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FTCNS (:, :, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FTCNS (NPROMA, 0:YDCPG_OPTS%KFLEVG, 1:6)
  CLASS (FIELD_4RB), POINTER :: F_FTCNS => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: KOZO (:, :, :) => NULL ()
!>REAL (KIND=JPRB)                      :: KOZO (NPROMA, 1:YDCPG_OPTS%KFLEVG, 1:YDCPG_OPTS%KVCLIS)
  CLASS (FIELD_4RB), POINTER :: F_KOZO => NULL ()

CONTAINS
  PROCEDURE :: INIT => CPG_MISC_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_MISC_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_MISC_TYPE_FINAL
END TYPE CPG_MISC_TYPE

TYPE CPG_DDH_TYPE
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: AUX3D (:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_AUX3D => NULL ()
  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: AUX2D (:,:) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_AUX2D => NULL ()

  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DHCV  (:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_DHCV => NULL ()
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: AUXSM (:,:,:) => NULL ()
  CLASS (FIELD_4RB), POINTER :: F_AUXSM => NULL ()
  INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: DDHI (:) => NULL ()
  CLASS (FIELD_2IM), POINTER :: F_DDHI => NULL ()
CONTAINS
  PROCEDURE :: INIT => CPG_DDH_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => CPG_DDH_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => CPG_DDH_TYPE_FINAL
END TYPE CPG_DDH_TYPE

REAL(KIND=JPRB),    PRIVATE, SAVE, TARGET :: ZDUM1 (1), ZDUM2 (1, 1), ZDUM3 (1,1,1)
INTEGER(KIND=JPIM), PRIVATE, SAVE, TARGET :: IDUM1 (1), IDUM2 (1, 1), IDUM3 (1,1,1)

CONTAINS

SUBROUTINE CPG_XYBDER_TYPE_INIT (&
                        &   SELF &
                        & , REGISTRY &
                        & , NLEV &
                        & , YDTXYBDER &
                        & , PERSISTENT &
                        & , PTXYBDER &
                        & , KBLKMIN  &
                        & , KBLKMAX  &
                        & )

USE INTDYN_MOD, ONLY : TXYBDER
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_XYBDER_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TXYBDER),                    INTENT (IN)    :: YDTXYBDER
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTXYBDER (:, :, :, :)
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

END SUBROUTINE CPG_XYBDER_TYPE_INIT

SUBROUTINE CPG_XYBDER_TYPE_RESIZE (SELF, REGISTRY, NLEV, &
                        & YDTXYBDER, PERSISTENT)

USE INTDYN_MOD, ONLY : TXYBDER

CLASS (CPG_XYBDER_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TXYBDER),                    INTENT (IN)    :: YDTXYBDER
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

IF (.NOT. SELF%CONFORM (REGISTRY, NLEV, &
                      & YDTXYBDER, PERSISTENT)) &
THEN
  CALL SELF%FINAL
  CALL SELF%INIT (REGISTRY, NLEV, &
                & YDTXYBDER, PERSISTENT)

ENDIF

END SUBROUTINE CPG_XYBDER_TYPE_RESIZE

LOGICAL FUNCTION CPG_XYBDER_TYPE_CONFORM (SELF, REGISTRY, NLEV, &
                        & YDTXYBDER, PERSISTENT) RESULT (LLCONFORM)

USE INTDYN_MOD, ONLY : TXYBDER
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_XYBDER_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TXYBDER),                    INTENT (IN)    :: YDTXYBDER
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

LOGICAL :: LLPERSISTENT

LLCONFORM = .FALSE.

LLPERSISTENT = .FALSE.
IF (PRESENT (PERSISTENT)) LLPERSISTENT = PERSISTENT

IF (.NOT. ASSOCIATED (SELF%ZDATA)) RETURN


IF (SIZE (SELF%ZDATA, 1) /= REGISTRY%GEOM%YRDIM%NPROMA) RETURN

IF (SIZE (SELF%ZDATA, 2) /= NLEV) RETURN

IF (SIZE (SELF%ZDATA, 3) /= YDTXYBDER%NDIM) RETURN

IF (LLPERSISTENT) THEN
  IF (SIZE (SELF%ZDATA, 4) /= REGISTRY%GEOM%YRDIM%NGPBLKS) RETURN
ELSE
  IF (SIZE (SELF%ZDATA, 4) /= OML_MAX_THREADS ()) RETURN
ENDIF

LLCONFORM = .TRUE.

END FUNCTION CPG_XYBDER_TYPE_CONFORM

SUBROUTINE CPG_XYBDER_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_XYBDER_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_XYBDER_TYPE_UPDATE_VIEW

SUBROUTINE CPG_XYBDER_TYPE_FINAL (SELF)
CLASS (CPG_XYBDER_TYPE)          :: SELF

END SUBROUTINE CPG_XYBDER_TYPE_FINAL

SUBROUTINE CPG_XYB_TYPE_INIT (&
                        &   SELF &
                        & , REGISTRY &
                        & , NLEV &
                        & , YDTXYB &
                        & , PERSISTENT &
                        & , PTXYB &
                        & , KBLKMIN  &
                        & , KBLKMAX  &
                        & )

USE INTDYN_MOD, ONLY : TXYB
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_XYB_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TXYB),                    INTENT (IN)    :: YDTXYB
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTXYB (:, :, :, :)
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

END SUBROUTINE CPG_XYB_TYPE_INIT

SUBROUTINE CPG_XYB_TYPE_RESIZE (SELF, REGISTRY, NLEV, &
                        & YDTXYB, PERSISTENT)

USE INTDYN_MOD, ONLY : TXYB

CLASS (CPG_XYB_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TXYB),                    INTENT (IN)    :: YDTXYB
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

IF (.NOT. SELF%CONFORM (REGISTRY, NLEV, &
                      & YDTXYB, PERSISTENT)) &
THEN
  CALL SELF%FINAL
  CALL SELF%INIT (REGISTRY, NLEV, &
                & YDTXYB, PERSISTENT)

ENDIF

END SUBROUTINE CPG_XYB_TYPE_RESIZE

LOGICAL FUNCTION CPG_XYB_TYPE_CONFORM (SELF, REGISTRY, NLEV, &
                        & YDTXYB, PERSISTENT) RESULT (LLCONFORM)

USE INTDYN_MOD, ONLY : TXYB
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_XYB_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TXYB),                    INTENT (IN)    :: YDTXYB
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

LOGICAL :: LLPERSISTENT

LLCONFORM = .FALSE.

LLPERSISTENT = .FALSE.
IF (PRESENT (PERSISTENT)) LLPERSISTENT = PERSISTENT

IF (.NOT. ASSOCIATED (SELF%ZDATA)) RETURN


IF (SIZE (SELF%ZDATA, 1) /= REGISTRY%GEOM%YRDIM%NPROMA) RETURN

IF (SIZE (SELF%ZDATA, 2) /= NLEV) RETURN

IF (SIZE (SELF%ZDATA, 3) /= YDTXYB%NDIM) RETURN

IF (LLPERSISTENT) THEN
  IF (SIZE (SELF%ZDATA, 4) /= REGISTRY%GEOM%YRDIM%NGPBLKS) RETURN
ELSE
  IF (SIZE (SELF%ZDATA, 4) /= OML_MAX_THREADS ()) RETURN
ENDIF

LLCONFORM = .TRUE.

END FUNCTION CPG_XYB_TYPE_CONFORM

SUBROUTINE CPG_XYB_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_XYB_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_XYB_TYPE_UPDATE_VIEW

SUBROUTINE CPG_XYB_TYPE_FINAL (SELF)
CLASS (CPG_XYB_TYPE)          :: SELF

END SUBROUTINE CPG_XYB_TYPE_FINAL

SUBROUTINE CPG_HWIND_TYPE_INIT (&
                        &   SELF &
                        & , REGISTRY &
                        & , NLEV &
                        & , YDTHWIND &
                        & , PERSISTENT &
                        & , PTHWIND &
                        & , KBLKMIN  &
                        & , KBLKMAX  &
                        & )

USE INTDYN_MOD, ONLY : THWIND
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_HWIND_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (THWIND),                    INTENT (IN)    :: YDTHWIND
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTHWIND (:, :, :, :)
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

END SUBROUTINE CPG_HWIND_TYPE_INIT

SUBROUTINE CPG_HWIND_TYPE_RESIZE (SELF, REGISTRY, NLEV, &
                        & YDTHWIND, PERSISTENT)

USE INTDYN_MOD, ONLY : THWIND

CLASS (CPG_HWIND_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (THWIND),                    INTENT (IN)    :: YDTHWIND
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

IF (.NOT. SELF%CONFORM (REGISTRY, NLEV, &
                      & YDTHWIND, PERSISTENT)) &
THEN
  CALL SELF%FINAL
  CALL SELF%INIT (REGISTRY, NLEV, &
                & YDTHWIND, PERSISTENT)

ENDIF

END SUBROUTINE CPG_HWIND_TYPE_RESIZE

LOGICAL FUNCTION CPG_HWIND_TYPE_CONFORM (SELF, REGISTRY, NLEV, &
                        & YDTHWIND, PERSISTENT) RESULT (LLCONFORM)

USE INTDYN_MOD, ONLY : THWIND
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_HWIND_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (THWIND),                    INTENT (IN)    :: YDTHWIND
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

LOGICAL :: LLPERSISTENT

LLCONFORM = .FALSE.

LLPERSISTENT = .FALSE.
IF (PRESENT (PERSISTENT)) LLPERSISTENT = PERSISTENT

IF (.NOT. ASSOCIATED (SELF%ZDATA)) RETURN


IF (SIZE (SELF%ZDATA, 1) /= REGISTRY%GEOM%YRDIM%NPROMA) RETURN

IF (SIZE (SELF%ZDATA, 2) /= NLEV+1) RETURN

IF (SIZE (SELF%ZDATA, 3) /= YDTHWIND%NDIM) RETURN

IF (LLPERSISTENT) THEN
  IF (SIZE (SELF%ZDATA, 4) /= REGISTRY%GEOM%YRDIM%NGPBLKS) RETURN
ELSE
  IF (SIZE (SELF%ZDATA, 4) /= OML_MAX_THREADS ()) RETURN
ENDIF

LLCONFORM = .TRUE.

END FUNCTION CPG_HWIND_TYPE_CONFORM

SUBROUTINE CPG_HWIND_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_HWIND_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_HWIND_TYPE_UPDATE_VIEW

SUBROUTINE CPG_HWIND_TYPE_FINAL (SELF)
CLASS (CPG_HWIND_TYPE)          :: SELF

END SUBROUTINE CPG_HWIND_TYPE_FINAL

SUBROUTINE CPG_RCP_TYPE_INIT (&
                        &   SELF &
                        & , REGISTRY &
                        & , NLEV &
                        & , YDTRCP &
                        & , PERSISTENT &
                        & , PTRCP &
                        & , KBLKMIN  &
                        & , KBLKMAX  &
                        & )

USE INTDYN_MOD, ONLY : TRCP
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_RCP_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TRCP),                    INTENT (IN)    :: YDTRCP
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTRCP (:, :, :, :)
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

END SUBROUTINE CPG_RCP_TYPE_INIT

SUBROUTINE CPG_RCP_TYPE_RESIZE (SELF, REGISTRY, NLEV, &
                        & YDTRCP, PERSISTENT)

USE INTDYN_MOD, ONLY : TRCP

CLASS (CPG_RCP_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TRCP),                    INTENT (IN)    :: YDTRCP
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

IF (.NOT. SELF%CONFORM (REGISTRY, NLEV, &
                      & YDTRCP, PERSISTENT)) &
THEN
  CALL SELF%FINAL
  CALL SELF%INIT (REGISTRY, NLEV, &
                & YDTRCP, PERSISTENT)

ENDIF

END SUBROUTINE CPG_RCP_TYPE_RESIZE

LOGICAL FUNCTION CPG_RCP_TYPE_CONFORM (SELF, REGISTRY, NLEV, &
                        & YDTRCP, PERSISTENT) RESULT (LLCONFORM)

USE INTDYN_MOD, ONLY : TRCP
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_RCP_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TRCP),                    INTENT (IN)    :: YDTRCP
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

LOGICAL :: LLPERSISTENT

LLCONFORM = .FALSE.

LLPERSISTENT = .FALSE.
IF (PRESENT (PERSISTENT)) LLPERSISTENT = PERSISTENT

IF (.NOT. ASSOCIATED (SELF%ZDATA)) RETURN


IF (SIZE (SELF%ZDATA, 1) /= REGISTRY%GEOM%YRDIM%NPROMA) RETURN

IF (SIZE (SELF%ZDATA, 2) /= NLEV) RETURN

IF (SIZE (SELF%ZDATA, 3) /= YDTRCP%NDIM) RETURN

IF (LLPERSISTENT) THEN
  IF (SIZE (SELF%ZDATA, 4) /= REGISTRY%GEOM%YRDIM%NGPBLKS) RETURN
ELSE
  IF (SIZE (SELF%ZDATA, 4) /= OML_MAX_THREADS ()) RETURN
ENDIF

LLCONFORM = .TRUE.

END FUNCTION CPG_RCP_TYPE_CONFORM

SUBROUTINE CPG_RCP_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_RCP_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_RCP_TYPE_UPDATE_VIEW

SUBROUTINE CPG_RCP_TYPE_FINAL (SELF)
CLASS (CPG_RCP_TYPE)          :: SELF

END SUBROUTINE CPG_RCP_TYPE_FINAL

SUBROUTINE CPG_CTY_TYPE_INIT (&
                        &   SELF &
                        & , REGISTRY &
                        & , NLEV &
                        & , YDTCTY &
                        & , PERSISTENT &
                        & , PTCTY &
                        & , KBLKMIN  &
                        & , KBLKMAX  &
                        & )

USE INTDYN_MOD, ONLY : TCTY
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_CTY_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TCTY),                    INTENT (IN)    :: YDTCTY
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTCTY (:, :, :, :)
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

END SUBROUTINE CPG_CTY_TYPE_INIT

SUBROUTINE CPG_CTY_TYPE_RESIZE (SELF, REGISTRY, NLEV, &
                        & YDTCTY, PERSISTENT)

USE INTDYN_MOD, ONLY : TCTY

CLASS (CPG_CTY_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TCTY),                    INTENT (IN)    :: YDTCTY
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

IF (.NOT. SELF%CONFORM (REGISTRY, NLEV, &
                      & YDTCTY, PERSISTENT)) &
THEN
  CALL SELF%FINAL
  CALL SELF%INIT (REGISTRY, NLEV, &
                & YDTCTY, PERSISTENT)

ENDIF

END SUBROUTINE CPG_CTY_TYPE_RESIZE

LOGICAL FUNCTION CPG_CTY_TYPE_CONFORM (SELF, REGISTRY, NLEV, &
                        & YDTCTY, PERSISTENT) RESULT (LLCONFORM)

USE INTDYN_MOD, ONLY : TCTY
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_CTY_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TCTY),                    INTENT (IN)    :: YDTCTY
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

LOGICAL :: LLPERSISTENT

LLCONFORM = .FALSE.

LLPERSISTENT = .FALSE.
IF (PRESENT (PERSISTENT)) LLPERSISTENT = PERSISTENT

IF (.NOT. ASSOCIATED (SELF%ZDATA)) RETURN


IF (SIZE (SELF%ZDATA, 1) /= REGISTRY%GEOM%YRDIM%NPROMA) RETURN

IF (SIZE (SELF%ZDATA, 2) /= NLEV+1) RETURN

IF (SIZE (SELF%ZDATA, 3) /= YDTCTY%NDIM) RETURN

IF (LLPERSISTENT) THEN
  IF (SIZE (SELF%ZDATA, 4) /= REGISTRY%GEOM%YRDIM%NGPBLKS) RETURN
ELSE
  IF (SIZE (SELF%ZDATA, 4) /= OML_MAX_THREADS ()) RETURN
ENDIF

LLCONFORM = .TRUE.

END FUNCTION CPG_CTY_TYPE_CONFORM

SUBROUTINE CPG_CTY_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_CTY_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_CTY_TYPE_UPDATE_VIEW

SUBROUTINE CPG_CTY_TYPE_FINAL (SELF)
CLASS (CPG_CTY_TYPE)          :: SELF

END SUBROUTINE CPG_CTY_TYPE_FINAL

SUBROUTINE CPG_TND_TYPE_INIT (&
                        &   SELF &
                        & , REGISTRY &
                        & , NLEV &
                        & , YDTTND &
                        & , PERSISTENT &
                        & , PTTND &
                        & , KBLKMIN  &
                        & , KBLKMAX  &
                        & )

USE INTDYN_MOD, ONLY : TTND
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_TND_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TTND),                    INTENT (IN)    :: YDTTND
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT
REAL (KIND=JPRB), OPTIONAL, TARGET, INTENT (IN)    :: PTTND (:, :, :, :)
INTEGER (KIND=JPIM), OPTIONAL,      INTENT (IN)    :: KBLKMIN, KBLKMAX

END SUBROUTINE CPG_TND_TYPE_INIT

SUBROUTINE CPG_TND_TYPE_RESIZE (SELF, REGISTRY, NLEV, &
                        & YDTTND, PERSISTENT)

USE INTDYN_MOD, ONLY : TTND

CLASS (CPG_TND_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TTND),                    INTENT (IN)    :: YDTTND
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

IF (.NOT. SELF%CONFORM (REGISTRY, NLEV, &
                      & YDTTND, PERSISTENT)) &
THEN
  CALL SELF%FINAL
  CALL SELF%INIT (REGISTRY, NLEV, &
                & YDTTND, PERSISTENT)

ENDIF

END SUBROUTINE CPG_TND_TYPE_RESIZE

LOGICAL FUNCTION CPG_TND_TYPE_CONFORM (SELF, REGISTRY, NLEV, &
                        & YDTTND, PERSISTENT) RESULT (LLCONFORM)

USE INTDYN_MOD, ONLY : TTND
USE OML_MOD, ONLY: OML_MAX_THREADS

CLASS (CPG_TND_TYPE)                          :: SELF
TYPE (FIELD_REGISTRY),              INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),                INTENT (IN)    :: NLEV
TYPE (TTND),                    INTENT (IN)    :: YDTTND
LOGICAL, OPTIONAL,                  INTENT (IN)    :: PERSISTENT

LOGICAL :: LLPERSISTENT

LLCONFORM = .FALSE.

LLPERSISTENT = .FALSE.
IF (PRESENT (PERSISTENT)) LLPERSISTENT = PERSISTENT

IF (.NOT. ASSOCIATED (SELF%ZDATA)) RETURN


IF (SIZE (SELF%ZDATA, 1) /= REGISTRY%GEOM%YRDIM%NPROMA) RETURN

IF (SIZE (SELF%ZDATA, 2) /= NLEV) RETURN

IF (SIZE (SELF%ZDATA, 3) /= YDTTND%NDIM) RETURN

IF (LLPERSISTENT) THEN
  IF (SIZE (SELF%ZDATA, 4) /= REGISTRY%GEOM%YRDIM%NGPBLKS) RETURN
ELSE
  IF (SIZE (SELF%ZDATA, 4) /= OML_MAX_THREADS ()) RETURN
ENDIF

LLCONFORM = .TRUE.

END FUNCTION CPG_TND_TYPE_CONFORM

SUBROUTINE CPG_TND_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_TND_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_TND_TYPE_UPDATE_VIEW

SUBROUTINE CPG_TND_TYPE_FINAL (SELF)
CLASS (CPG_TND_TYPE)          :: SELF

END SUBROUTINE CPG_TND_TYPE_FINAL




SUBROUTINE CPG_DYN_TYPE_INIT (SELF &
                                & , KT  &
                                & , REGISTRY &
                                & , NLEV &
                                & , PERSISTENT &
                                & , YDDYNA &
                                &, PHIF &
                                &, PREF &
                                &, PRCP &
                                &, PCTY &
                                &, KBLKMIN &
                                &, KBLKMAX &
                        &)

USE INTDYN_MOD, ONLY : YYTCTY0, YYTRCP0, YYTHW0, YYTXYB0, YYTXYB0_PHY, YYTXYBDER0
USE INTDYN_MOD, ONLY :          YYTRCP9, YYTHW9, YYTXYB9, YYTXYB9_PHY
USE INTDYN_MOD, ONLY : TRCP, TCTY, THWIND, TXYB, TXYBDER


USE YOMDYNA, ONLY : TDYNA

CLASS (CPG_DYN_TYPE)                    :: SELF
INTEGER(KIND=JPIM),           INTENT (IN)    :: KT
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),          INTENT (IN)    :: NLEV
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT
TYPE (TDYNA),                 INTENT (IN)    :: YDDYNA

REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PHIF(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PREF(:, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PRCP(:, :, :, :)
REAL(KIND=JPRB),       INTENT (IN), OPTIONAL, TARGET  :: PCTY(:, :, :, :)

INTEGER(KIND=JPIM), OPTIONAL, INTENT (IN)    :: KBLKMIN
INTEGER(KIND=JPIM), OPTIONAL, INTENT (IN)    :: KBLKMAX

END SUBROUTINE CPG_DYN_TYPE_INIT

SUBROUTINE CPG_DYN_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_DYN_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_DYN_TYPE_UPDATE_VIEW

SUBROUTINE CPG_DYN_TYPE_FINAL (SELF)
CLASS (CPG_DYN_TYPE)         :: SELF

END SUBROUTINE CPG_DYN_TYPE_FINAL




SUBROUTINE CPG_PHY_TYPE_INIT (SELF &
                                & , KT  &
                                & , REGISTRY &
                                & , NLEV &
                                & , PERSISTENT &
                                & , LDMF_PHYS &
                                &, KBLKMIN &
                                &, KBLKMAX &
                        &)

USE INTDYN_MOD, ONLY : YYTCTY0, YYTRCP0, YYTHW0, YYTXYB0, YYTXYB0_PHY, YYTXYBDER0
USE INTDYN_MOD, ONLY :          YYTRCP9, YYTHW9, YYTXYB9, YYTXYB9_PHY
USE INTDYN_MOD, ONLY : TRCP, TCTY, THWIND, TXYB, TXYBDER



CLASS (CPG_PHY_TYPE)                    :: SELF
INTEGER(KIND=JPIM),           INTENT (IN)    :: KT
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
INTEGER (KIND=JPIM),          INTENT (IN)    :: NLEV
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT
LOGICAL, OPTIONAL,            INTENT (IN)    :: LDMF_PHYS


INTEGER(KIND=JPIM), OPTIONAL, INTENT (IN)    :: KBLKMIN
INTEGER(KIND=JPIM), OPTIONAL, INTENT (IN)    :: KBLKMAX

END SUBROUTINE CPG_PHY_TYPE_INIT

SUBROUTINE CPG_PHY_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_PHY_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_PHY_TYPE_UPDATE_VIEW

SUBROUTINE CPG_PHY_TYPE_FINAL (SELF)
CLASS (CPG_PHY_TYPE)         :: SELF

CALL SELF%XYB%FINAL ()

END SUBROUTINE CPG_PHY_TYPE_FINAL




SUBROUTINE CPG_MISC_TYPE_INIT (SELF &
                                & , REGISTRY &
                                & , YDCPG_OPTS &
                                & , PERSISTENT &
                                &, KBLKMIN &
                                &, KBLKMAX &
                        &)


USE CPG_OPTS_TYPE_MOD, ONLY : CPG_OPTS_TYPE


CLASS (CPG_MISC_TYPE)                    :: SELF
TYPE (FIELD_REGISTRY),        INTENT (INOUT) :: REGISTRY
TYPE (CPG_OPTS_TYPE),         INTENT (IN)    :: YDCPG_OPTS
LOGICAL, OPTIONAL,            INTENT (IN)    :: PERSISTENT


INTEGER(KIND=JPIM), OPTIONAL, INTENT (IN)    :: KBLKMIN
INTEGER(KIND=JPIM), OPTIONAL, INTENT (IN)    :: KBLKMAX


END SUBROUTINE CPG_MISC_TYPE_INIT

SUBROUTINE CPG_MISC_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_MISC_TYPE)         :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_MISC_TYPE_UPDATE_VIEW

SUBROUTINE CPG_MISC_TYPE_FINAL (SELF)
CLASS (CPG_MISC_TYPE)         :: SELF

END SUBROUTINE CPG_MISC_TYPE_FINAL

SUBROUTINE CPG_DDH_TYPE_INIT (SELF, REGISTRY, NLEV, PERSISTENT, YDMODEL, YDDDH, KBLKMIN, KBLKMAX)

USE TYPE_MODEL, ONLY : MODEL
USE DDH_MIX, ONLY : TYP_DDH

CLASS (CPG_DDH_TYPE)                             :: SELF
TYPE (FIELD_REGISTRY),            INTENT (IN)    :: REGISTRY
INTEGER (KIND=JPIM),              INTENT (IN)    :: NLEV
LOGICAL, OPTIONAL,                INTENT (IN)    :: PERSISTENT
TYPE (MODEL),                     INTENT (IN)    :: YDMODEL
TYPE (TYP_DDH),                   INTENT (IN)    :: YDDDH
INTEGER (KIND=JPIM), OPTIONAL,    INTENT (IN)    :: KBLKMIN, KBLKMAX

END SUBROUTINE CPG_DDH_TYPE_INIT

SUBROUTINE CPG_DDH_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (CPG_DDH_TYPE)              :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

END SUBROUTINE CPG_DDH_TYPE_UPDATE_VIEW

SUBROUTINE CPG_DDH_TYPE_FINAL (SELF)

CLASS (CPG_DDH_TYPE)              :: SELF

SELF%AUX3D => NULL ()
SELF%AUX2D => NULL ()
SELF%DHCV  => NULL ()
SELF%AUXSM => NULL ()
SELF%DDHI  => NULL ()

END SUBROUTINE CPG_DDH_TYPE_FINAL

END MODULE CPG_TYPE_MOD

