! (C) Copyright 2005- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE DEALLOCATE_IF_ALLOCATED_MOD

!**** DEALLOCATE_IF_ALLOCATED_MOD

!     Purpose.
!     --------
!     The pattern "IF (ALLOCATED(<allocatable>)) DEALLOCATE(>allocatable>)"
!     occurs all over the IFS. With this module, we can just do
!     "CALL DEALLOCATE_IF_ALLOCATED(<allocatable>)".

!**   Interface.
!     ----------

!        CALL DEALLOCATE_IF_ALLOCATED(P)

!        Input required arguments :
!        -------------------------
!           P        -  A allocatable to an array

!     Author.
!     -------
!        Mike Fisher  ECMWF

!     Modifications.
!     --------------
!        Original: 2012-03-01

!     ------------------------------------------------------------------

USE EC_PARKIND  ,ONLY : JPIM, JPRM, JPRD
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

SAVE
PRIVATE
PUBLIC  DEALLOCATE_IF_ALLOCATED

INTERFACE DEALLOCATE_IF_ALLOCATED
  MODULE PROCEDURE &
                 & DEALLOCATE_IF_ALLOCATED_REAL32_1D, &
                 & DEALLOCATE_IF_ALLOCATED_REAL32_2D, &
                 & DEALLOCATE_IF_ALLOCATED_REAL32_3D, &
                 & DEALLOCATE_IF_ALLOCATED_REAL32_4D, &
                 & DEALLOCATE_IF_ALLOCATED_REAL32_5D, &
                 & DEALLOCATE_IF_ALLOCATED_REAL64_1D, &
                 & DEALLOCATE_IF_ALLOCATED_REAL64_2D, &
                 & DEALLOCATE_IF_ALLOCATED_REAL64_3D, &
                 & DEALLOCATE_IF_ALLOCATED_REAL64_4D, &
                 & DEALLOCATE_IF_ALLOCATED_REAL64_5D, &
                 & DEALLOCATE_IF_ALLOCATED_INTEGER_1D, &
                 & DEALLOCATE_IF_ALLOCATED_INTEGER_2D, &
                 & DEALLOCATE_IF_ALLOCATED_INTEGER_3D, &
                 & DEALLOCATE_IF_ALLOCATED_LOGICAL_1D, &
                 & DEALLOCATE_IF_ALLOCATED_LOGICAL_2D, &
                 & DEALLOCATE_IF_ALLOCATED_CHARACTER
END INTERFACE

!     ------------------------------------------------------------------

CONTAINS

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_1D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_1D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_2D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:,:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_2D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_3D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:,:,:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_3D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_3D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_3D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_4D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:,:,:,:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_4D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_4D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_4D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_5D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:,:,:,:,:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_5D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL32_5D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL32_5D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_1D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_1D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_2D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:,:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_2D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_3D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:,:,:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_3D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_3D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_3D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_4D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:,:,:,:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_4D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_4D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_4D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_5D (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:,:,:,:,:), ALLOCATABLE :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_5D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(ZOBJ)) DEALLOCATE(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL64_5D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_REAL64_5D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_INTEGER_1D (KOBJ)
  IMPLICIT NONE
  INTEGER(KIND=JPIM), DIMENSION(:), ALLOCATABLE :: KOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_INTEGER_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(KOBJ)) DEALLOCATE(KOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_INTEGER_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_INTEGER_1D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_INTEGER_2D (KOBJ)
  IMPLICIT NONE
  INTEGER(KIND=JPIM), DIMENSION(:,:), ALLOCATABLE :: KOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_INTEGER_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(KOBJ)) DEALLOCATE(KOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_INTEGER_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_INTEGER_2D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_INTEGER_3D (KOBJ)
  IMPLICIT NONE
  INTEGER(KIND=JPIM), DIMENSION(:,:,:), ALLOCATABLE :: KOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_INTEGER_3D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(KOBJ)) DEALLOCATE(KOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_INTEGER_3D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_INTEGER_3D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_LOGICAL_1D (LDOBJ)
  IMPLICIT NONE
  LOGICAL, DIMENSION(:), ALLOCATABLE :: LDOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_LOGICAL_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(LDOBJ)) DEALLOCATE(LDOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_LOGICAL_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_LOGICAL_1D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ALLOCATED_LOGICAL_2D (LDOBJ)
  IMPLICIT NONE
  LOGICAL, DIMENSION(:,:), ALLOCATABLE :: LDOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_LOGICAL_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(LDOBJ)) DEALLOCATE(LDOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_LOGICAL_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_LOGICAL_2D

!     ------------------------------------------------------------------
SUBROUTINE DEALLOCATE_IF_ALLOCATED_CHARACTER (CDOBJ)
  IMPLICIT NONE
  CHARACTER(LEN=*), DIMENSION(:), ALLOCATABLE :: CDOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ALLOCATED(CDOBJ)) DEALLOCATE(CDOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ALLOCATED_MOD:DEALLOCATE_IF_ALLOCATED_REAL_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ALLOCATED_CHARACTER

END MODULE DEALLOCATE_IF_ALLOCATED_MOD
