! (C) Copyright 2005- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE DEALLOCATE_IF_ASSOCIATED_MOD

!**** DEALLOCATE_IF_ASSOCIATED_MOD

!     Purpose.
!     --------
!     The pattern "IF (ASSOCIATED(<pointer>)) DEALLOCATE(>pointer>)"
!     occurs all over the IFS. With this module, we can just do
!     "CALL DEALLOCATE_IF_ASSOCIATED(<pointer>)".

!**   Interface.
!     ----------

!        CALL DEALLOCATE_IF_ASSOCIATED(P)

!        Input required arguments :
!        -------------------------
!           P        -  A pointer to an array

!     Author.
!     -------
!        Mike Fisher  ECMWF

!     Modifications.
!     --------------
!        Original: 2012-03-01

!     ------------------------------------------------------------------

USE EC_PARKIND  ,ONLY : JPIM, JPRM, JPRD
USE YOMHOOK   ,ONLY : LHOOK, DR_HOOK, JPHOOK

SAVE
PRIVATE
PUBLIC  DEALLOCATE_IF_ASSOCIATED

INTERFACE DEALLOCATE_IF_ASSOCIATED
  MODULE PROCEDURE DEALLOCATE_IF_ASSOCIATED_REAL_1D_SINGLE, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_1D_DOUBLE, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_2D_SINGLE, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_2D_DOUBLE, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_3D_SINGLE, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_3D_DOUBLE, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_4D_SINGLE, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_4D_DOUBLE, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_5D_SINGLE, &
                 & DEALLOCATE_IF_ASSOCIATED_REAL_5D_DOUBLE, &
                 & DEALLOCATE_IF_ASSOCIATED_INTEGER_1D, &
                 & DEALLOCATE_IF_ASSOCIATED_INTEGER_2D, &
                 & DEALLOCATE_IF_ASSOCIATED_INTEGER_3D, &
                 & DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D, &
                 & DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D
END INTERFACE

!     ------------------------------------------------------------------

CONTAINS

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_1D_SINGLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_1D_SINGLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_1D_DOUBLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_1D_DOUBLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_2D_SINGLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:,:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_2D_SINGLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_2D_DOUBLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:,:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_2D_DOUBLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_3D_SINGLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:,:,:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_3D_SINGLE', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_3D_SINGLE', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_3D_SINGLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_3D_DOUBLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:,:,:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_3D_DOUBLE', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_3D_DOUBLE', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_3D_DOUBLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_4D_SINGLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:,:,:,:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_4D_SINGLE', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_4D_SINGLE', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_4D_SINGLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_4D_DOUBLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:,:,:,:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_4D_DOUBLE', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_4D_DOUBLE', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_4D_DOUBLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_5D_SINGLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRM), DIMENSION(:,:,:,:,:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_5D_SINGLE', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_5D_SINGLE', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_5D_SINGLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_5D_DOUBLE (ZOBJ)
  IMPLICIT NONE
  REAL(KIND=JPRD), DIMENSION(:,:,:,:,:), POINTER :: ZOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_5D_DOUBLE', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(ZOBJ)) DEALLOCATE(ZOBJ)
  NULLIFY(ZOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_REAL_5D_DOUBLE', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_REAL_5D_DOUBLE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_1D (KOBJ)
  IMPLICIT NONE
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER :: KOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(KOBJ)) DEALLOCATE(KOBJ)
  NULLIFY(KOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_1D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_2D (KOBJ)
  IMPLICIT NONE
  INTEGER(KIND=JPIM), DIMENSION(:,:), POINTER :: KOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(KOBJ)) DEALLOCATE(KOBJ)
  NULLIFY(KOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_2D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_3D (KOBJ)
  IMPLICIT NONE
  INTEGER(KIND=JPIM), DIMENSION(:,:,:), POINTER :: KOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_3D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(KOBJ)) DEALLOCATE(KOBJ)
  NULLIFY(KOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_INTEGER_3D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_INTEGER_3D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D (LDOBJ)
  IMPLICIT NONE
  LOGICAL, DIMENSION(:), POINTER :: LDOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(LDOBJ)) DEALLOCATE(LDOBJ)
  NULLIFY(LDOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_LOGICAL_1D

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D (LDOBJ)
  IMPLICIT NONE
  LOGICAL, DIMENSION(:,:), POINTER :: LDOBJ
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D', &
                         & 0,ZHOOK_HANDLE)
  IF (ASSOCIATED(LDOBJ)) DEALLOCATE(LDOBJ)
  NULLIFY(LDOBJ)
  IF (LHOOK) CALL DR_HOOK ('DEALLOCATE_IF_ASSOCIATED_MOD:DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D', &
                         & 1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_IF_ASSOCIATED_LOGICAL_2D

END MODULE DEALLOCATE_IF_ASSOCIATED_MOD
