INTERFACE
SUBROUTINE DOTPROD2(YDGEOMETRY,KF,PGP1,PGP2,PPROD)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1  ,ONLY : JPIM, JPRB
IMPLICIT NONE
TYPE(GEOMETRY),     INTENT(IN)  :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN)  :: KF
REAL(KIND=JPRB),    INTENT(IN)  :: PGP1(:,:,:)
REAL(KIND=JPRB),    INTENT(IN)  :: PGP2(:,:,:)
REAL(KIND=JPRB),    INTENT(OUT) :: PPROD
END SUBROUTINE DOTPROD2







END INTERFACE
