
MODULE EASY_NETCDF
USE PARKIND1,ONLY:JPRB, JPIB, JPRM, JPRD
USE RADIATION_IO,ONLY:NULOUT, NULERR, MY_ABORT=>RADIATION_ABORT

IMPLICIT NONE


TYPE NETCDF_FILE
  INTEGER::NCID=-1
  INTEGER::IVERBOSE
  LOGICAL::DO_TRANSPOSE_2D=.FALSE.
  LOGICAL::IS_WRITE_MODE=.FALSE.
  LOGICAL::IS_DEFINE_MODE=.TRUE.
  LOGICAL::IS_DOUBLE_PRECISION=.FALSE.
  LOGICAL::DO_PERMUTE_3D=.FALSE.
  LOGICAL::DO_PERMUTE_4D=.FALSE.
  INTEGER::I_PERMUTE_3D (3)=(/1, 2, 3/)
  INTEGER::I_PERMUTE_4D (4)=(/1, 2, 3, 4/)
  CHARACTER (LEN=511)::FILE_NAME
  
  
  
#ifdef NC_NETCDF4
#endif
  
  
  
  
ENDTYPE NETCDF_FILE

CONTAINS
#ifdef NC_NETCDF4
#endif
ENDMODULE EASY_NETCDF
