MODULE EINT_MOD
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE



TYPE SL_STRUCT
  CHARACTER (LEN=2)::CVER='XX'
  INTEGER (KIND=JPIM)::NSLGROUP=0
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLSTA (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLONL (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLOFF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLPTSWEST (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLPTSEAST (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLEXT (:,:)
  LOGICAL, ALLOCATABLE::LCOMPLAT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NLATGLO (:)
  REAL (KIND=JPRB), ALLOCATABLE::DIST1GP (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLSENDPOS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLRECVPOS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLSENDPTR (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLRECVPTR (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLCOMM (:)
  LOGICAL, ALLOCATABLE::LSLCOMM (:,:)
  INTEGER (KIND=JPIM)::NASLB1=0
  INTEGER (KIND=JPIM)::NASLMASK=0
  INTEGER (KIND=JPIM)::NASLB1_TRUE=0
  INTEGER (KIND=JPIM)::NSLPAD=0
  LOGICAL::LSLT_ARRAYS_INIT=.FALSE.
  LOGICAL::LSLONDEM=.FALSE.
  INTEGER (KIND=JPIM)::NUNUSEDHALO=999999
  REAL (KIND=JPRB)::DISTUNUSEDHALO=999999.0_JPRB
  INTEGER (KIND=JPIM), ALLOCATABLE::MASK_SL1 (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MASK_SL2 (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MASK_SL2T (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MASK_SLD (:)
  INTEGER (KIND=JPIM)::NSLPROCS=0
  INTEGER (KIND=JPIM)::NSLRPT=0
  INTEGER (KIND=JPIM)::NSLSPT=0
  INTEGER (KIND=JPIM)::NSLWIDEN=0
  INTEGER (KIND=JPIM)::NSLWIDES=0
  INTEGER (KIND=JPIM)::NSLWIDEE=0
  INTEGER (KIND=JPIM)::NSLWIDEW=0
  INTEGER (KIND=JPIM)::NSLWIDE=0
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLMAP (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLCORE (:)
  LOGICAL, ALLOCATABLE::LSLCORE (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MASK_SLTOT (:)
  INTEGER (KIND=JPIM)::NDGLG=0
  INTEGER (KIND=JPIM)::NDLON=0
  INTEGER (KIND=JPIM)::NDGSAG=0
  INTEGER (KIND=JPIM)::NDGENG=0
  INTEGER (KIND=JPIM)::NDGSAL=0
  INTEGER (KIND=JPIM)::NDGENL=0
  INTEGER (KIND=JPIM)::NDGSAH=0
  INTEGER (KIND=JPIM)::NDGENH=0
  INTEGER (KIND=JPIM)::NGPTOT=0
  INTEGER (KIND=JPIM)::NDGUXL=0
  INTEGER (KIND=JPIM)::NDLUNG=0
  INTEGER (KIND=JPIM)::NDLUXG=0
  INTEGER (KIND=JPIM)::NDGUNG=0
  INTEGER (KIND=JPIM)::NDGUXG=0
  INTEGER (KIND=JPIM)::NDSUR1=0
  INTEGER (KIND=JPIM)::NDLSUR=0
  INTEGER (KIND=JPIM)::NDGSUR=0
  INTEGER (KIND=JPIM)::NPTRFLOFF=0
  INTEGER (KIND=JPIM)::NFRSTLOFF=0
  INTEGER (KIND=JPIM)::MYFRSTACTLAT=0
  INTEGER (KIND=JPIM)::MYLSTACTLAT=0
  INTEGER (KIND=JPIM), ALLOCATABLE::NLOENG (:)
  INTEGER (KIND=JPIM)::NPROC=0
  INTEGER (KIND=JPIM), ALLOCATABLE::NSTALAT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NADDR (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NOFFLEV (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RLSDEPI (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLEXTPOLFISTA (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLEXTPOLIJPTA (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSLEXTPOLIPTA (:)
  
  
ENDTYPE SL_STRUCT

CONTAINS





ENDMODULE EINT_MOD
