INTERFACE
SUBROUTINE ESPEREE(YDGEOMETRY,KFLSUR,KFIELD,KPROMA,KGPBLKS,PSPEC,PREEL,PREELL,PREELM)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
TYPE(GEOMETRY)     ,INTENT(IN)             :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN)             :: KFLSUR
INTEGER(KIND=JPIM) ,INTENT(IN)             :: KFIELD
INTEGER(KIND=JPIM) ,INTENT(IN)             :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN)             :: KGPBLKS
REAL(KIND=JPRB)    ,INTENT(IN)             :: PSPEC(KFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB)    ,INTENT(OUT)            :: PREEL(KPROMA,KFIELD,KGPBLKS)
REAL(KIND=JPRB)    ,INTENT(OUT) ,OPTIONAL  :: PREELL(KPROMA,KFIELD,KGPBLKS)
REAL(KIND=JPRB)    ,INTENT(OUT) ,OPTIONAL  :: PREELM(KPROMA,KFIELD,KGPBLKS)
END SUBROUTINE ESPEREE







END INTERFACE
