
MODULE FIELD_4IM_DATA_MODULE


USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


PUBLIC :: FIELD_4IM_COPY
PUBLIC :: FIELD_4IM_COPY_FUNC
PUBLIC :: FIELD_4IM_COPY_INTF

ABSTRACT INTERFACE
  SUBROUTINE FIELD_4IM_COPY_INTF (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
    IMPORT :: JPIM
    INTEGER(KIND=JPIM), POINTER :: HST (:,:,:,:), DEV (:,:,:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
  END SUBROUTINE
END INTERFACE

CONTAINS


  FUNCTION FIELD_4IM_COPY_FUNC (HST, DEV) RESULT (FUNC)

    PROCEDURE (FIELD_4IM_COPY_INTF), POINTER :: FUNC 

    INTEGER(KIND=JPIM), POINTER, OPTIONAL :: HST (:,:,:,:), DEV (:,:,:,:)

  END FUNCTION

  SUBROUTINE FIELD_4IM_COPY (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)

    INTEGER(KIND=JPIM), POINTER :: HST (:,:,:,:), DEV (:,:,:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE

    PROCEDURE (FIELD_4IM_COPY_INTF), POINTER :: FUNC 

  END SUBROUTINE

  SUBROUTINE FIELD_4IM_COPY_DIM0_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
  USE OPENACC
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    INTEGER(KIND=JPIM), POINTER :: HST (:,:,:,:), DEV (:,:,:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J, J1, J2, J3, J4
#ifdef _OPENACC
    TYPE(C_DEVPTR) :: DEVPTR
#endif

    END SUBROUTINE

  SUBROUTINE FIELD_4IM_COPY_DIM1_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
  USE OPENACC
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    INTEGER(KIND=JPIM), POINTER :: HST (:,:,:,:), DEV (:,:,:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J, J2, J3, J4
#ifdef _OPENACC
    TYPE(C_DEVPTR) :: DEVPTR
#endif

    END SUBROUTINE

  SUBROUTINE FIELD_4IM_COPY_DIM2_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
  USE OPENACC
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    INTEGER(KIND=JPIM), POINTER :: HST (:,:,:,:), DEV (:,:,:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J, J3, J4
#ifdef _OPENACC
    TYPE(C_DEVPTR) :: DEVPTR
#endif

    END SUBROUTINE

  SUBROUTINE FIELD_4IM_COPY_DIM3_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
  USE OPENACC
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    INTEGER(KIND=JPIM), POINTER :: HST (:,:,:,:), DEV (:,:,:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J, J4
#ifdef _OPENACC
    TYPE(C_DEVPTR) :: DEVPTR
#endif

    END SUBROUTINE

  SUBROUTINE FIELD_4IM_COPY_DIM4_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
  USE OPENACC
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    INTEGER(KIND=JPIM), POINTER :: HST (:,:,:,:), DEV (:,:,:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J
#ifdef _OPENACC
    TYPE(C_DEVPTR) :: DEVPTR
#endif

    END SUBROUTINE




  INTEGER (KIND=JPIM) FUNCTION FIELD_4IM_GET_LAST_CONTIGUOUS_DIMENSION (PTR, AFTER) RESULT (JDIM)
  INTEGER(KIND=JPIM), POINTER :: PTR (:,:,:,:)
  INTEGER (KIND=JPIM) :: AFTER
  INTEGER*8 :: IPREVIOUS_STRIDE, ITHIS_STRIDE, ISIZE
  INTEGER (KIND=JPIM) :: J, LB(4)

  END FUNCTION FIELD_4IM_GET_LAST_CONTIGUOUS_DIMENSION


END MODULE FIELD_4IM_DATA_MODULE
