
MODULE FIELD_GANG_MODULE


USE FIELD_3RM_GANG_MODULE
USE FIELD_4RM_GANG_MODULE
USE FIELD_5RM_GANG_MODULE
USE FIELD_3RD_GANG_MODULE
USE FIELD_4RD_GANG_MODULE
USE FIELD_5RD_GANG_MODULE
USE FIELD_3IM_GANG_MODULE
USE FIELD_4IM_GANG_MODULE
USE FIELD_5IM_GANG_MODULE
USE FIELD_3LM_GANG_MODULE
USE FIELD_4LM_GANG_MODULE
USE FIELD_5LM_GANG_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_3RM_GANG_WRAPPER
PUBLIC :: FIELD_3RM_GANG_OWNER
PUBLIC :: FIELD_4RM_GANG_WRAPPER
PUBLIC :: FIELD_4RM_GANG_OWNER
PUBLIC :: FIELD_5RM_GANG_WRAPPER
PUBLIC :: FIELD_5RM_GANG_OWNER
PUBLIC :: FIELD_3RD_GANG_WRAPPER
PUBLIC :: FIELD_3RD_GANG_OWNER
PUBLIC :: FIELD_4RD_GANG_WRAPPER
PUBLIC :: FIELD_4RD_GANG_OWNER
PUBLIC :: FIELD_5RD_GANG_WRAPPER
PUBLIC :: FIELD_5RD_GANG_OWNER
PUBLIC :: FIELD_3IM_GANG_WRAPPER
PUBLIC :: FIELD_3IM_GANG_OWNER
PUBLIC :: FIELD_4IM_GANG_WRAPPER
PUBLIC :: FIELD_4IM_GANG_OWNER
PUBLIC :: FIELD_5IM_GANG_WRAPPER
PUBLIC :: FIELD_5IM_GANG_OWNER
PUBLIC :: FIELD_3LM_GANG_WRAPPER
PUBLIC :: FIELD_3LM_GANG_OWNER
PUBLIC :: FIELD_4LM_GANG_WRAPPER
PUBLIC :: FIELD_4LM_GANG_OWNER
PUBLIC :: FIELD_5LM_GANG_WRAPPER
PUBLIC :: FIELD_5LM_GANG_OWNER

END MODULE FIELD_GANG_MODULE
