
MODULE FIELD_5RD_FACTORY_MODULE


USE FIELD_5RD_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

INTERFACE FIELD_NEW
  MODULE PROCEDURE FIELD_5RD_NEW_OWNER
  MODULE PROCEDURE FIELD_5RD_NEW_WRAPPER
END INTERFACE

PUBLIC :: FIELD_NEW

INTERFACE FIELD_DELETE
  MODULE PROCEDURE FIELD_5RD_DELETE
END INTERFACE FIELD_DELETE

PUBLIC :: FIELD_DELETE

INTERFACE FIELD_RESIZE
  MODULE PROCEDURE FIELD_5RD_RESIZE
END INTERFACE FIELD_RESIZE

PUBLIC :: FIELD_RESIZE

CONTAINS

SUBROUTINE FIELD_5RD_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR, &
&                                 POOLED)

CLASS(FIELD_5RD), POINTER :: FIELD_PTR
TYPE(FIELD_5RD_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (5)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
REAL(KIND=JPRD), OPTIONAL, INTENT(IN) :: INIT_VALUE
LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
LOGICAL, OPTIONAL,  INTENT(IN) :: POOLED

END SUBROUTINE

SUBROUTINE FIELD_5RD_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA, MAP_DEVPTR, SYNC_ON_FINAL, INITIALIZED)

CLASS(FIELD_5RD), POINTER :: FIELD_PTR
REAL(KIND=JPRD), TARGET, INTENT (IN) :: DATA (:,:,:,:,:)
TYPE(FIELD_5RD_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
LOGICAL, OPTIONAL,  INTENT(IN) :: SYNC_ON_FINAL
LOGICAL, OPTIONAL,  INTENT(IN) :: INITIALIZED

END SUBROUTINE


SUBROUTINE FIELD_5RD_DELETE (FIELD_PTR)

CLASS(FIELD_5RD), POINTER :: FIELD_PTR

END SUBROUTINE

SUBROUTINE FIELD_5RD_RESIZE (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT)

CLASS(FIELD_5RD), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (5)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (5)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT

END SUBROUTINE FIELD_5RD_RESIZE


END MODULE
