
MODULE FIELD_1IM_ARRAY_MODULE

!$ACDC methods --methods-list=host --skip-components cpg --field-api --field-api-class cpg


USE FIELD_1IM_MODULE
USE FIELD_1IM_FACTORY_MODULE
USE FIELD_1IM_UTIL_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

TYPE FIELD_1IM_ARRAY
  CLASS (FIELD_1IM), POINTER :: F_P => NULL ()
  INTEGER(KIND=JPIM), POINTER, CONTIGUOUS :: P_FIELD (:) => NULL()
CONTAINS
  GENERIC :: INIT => INIT_FIELD_1IM_ARRAY_WRAPPER, INIT_FIELD_1IM_ARRAY_OWNER
  PROCEDURE, PRIVATE :: INIT_FIELD_1IM_ARRAY_WRAPPER
  PROCEDURE, PRIVATE :: INIT_FIELD_1IM_ARRAY_OWNER
  PROCEDURE :: RESIZE => RESIZE_FIELD_1IM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_1IM_ARRAY
END TYPE

PUBLIC :: FIELD_1IM_ARRAY


CONTAINS

SUBROUTINE INIT_FIELD_1IM_ARRAY_WRAPPER (SELF, P, LBOUNDS)

CLASS (FIELD_1IM_ARRAY) :: SELF
INTEGER(KIND=JPIM), INTENT (IN), TARGET :: P (:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)

END SUBROUTINE

SUBROUTINE INIT_FIELD_1IM_ARRAY_OWNER (SELF, PERSISTENT, UBOUNDS, LBOUNDS)

CLASS (FIELD_1IM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
LOGICAL,             INTENT (IN), OPTIONAL :: PERSISTENT

END SUBROUTINE

SUBROUTINE RESIZE_FIELD_1IM_ARRAY (SELF, UBOUNDS, LBOUNDS, PERSISTENT)

CLASS (FIELD_1IM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
LOGICAL,             INTENT (IN), OPTIONAL :: PERSISTENT

END SUBROUTINE


SUBROUTINE FINAL_FIELD_1IM_ARRAY (SELF)
CLASS (FIELD_1IM_ARRAY) :: SELF

END SUBROUTINE


END MODULE
