
MODULE FIELD_1LM_UTIL_MODULE


USE FIELD_1LM_MODULE
USE FIELD_1LM_ACCESS_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE


INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_1LM
  MODULE PROCEDURE LOAD_FIELD_1LM_PTR
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_1LM
  MODULE PROCEDURE SAVE_FIELD_1LM_PTR
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_1LM
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_1LM
  MODULE PROCEDURE COPY_FIELD_1LM_PTR
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_1LM
  MODULE PROCEDURE WIPE_FIELD_1LM_PTR
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_1LM
  MODULE PROCEDURE HOST_FIELD_1LM_PTR
END INTERFACE

INTERFACE LEGACY
  MODULE PROCEDURE LEGACY_FIELD_1LM
END INTERFACE


CONTAINS


SUBROUTINE LOAD_FIELD_1LM (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1LM), POINTER :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_1LM (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1LM), POINTER :: YD

END SUBROUTINE

SUBROUTINE DIFF_FIELD_1LM (CDMESS, YD, YO)

CHARACTER (LEN=*), INTENT(IN) :: CDMESS
CLASS (FIELD_1LM), POINTER :: YD, YO

END SUBROUTINE

SUBROUTINE COPY_FIELD_1LM (SELF, LDCREATED)

CLASS (FIELD_1LM), POINTER :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_1LM (SELF, LDDELETED)

CLASS (FIELD_1LM) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_1LM (SELF)
CLASS (FIELD_1LM), POINTER :: SELF

END SUBROUTINE 

SUBROUTINE LEGACY_FIELD_1LM (SELF, KADDRL, KADDRU, KDIR)

USE FIELD_1LM_ACCESS_MODULE

CLASS (FIELD_1LM), POINTER :: SELF
INTEGER*8, INTENT (IN) :: KADDRL
INTEGER*8, INTENT (IN) :: KADDRU
INTEGER,   INTENT (IN) :: KDIR

LOGICAL(KIND=JPLM), POINTER :: PTR (:), DEVPTR (:)
INTEGER*8 :: IADDRL
INTEGER*8 :: IADDRU
INTEGER (KIND=JPIM) :: ILBOUNDS (1)
INTEGER (KIND=JPIM) :: IUBOUNDS (1)

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_1LM_PTR (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1LM_PTR) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_1LM_PTR (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_1LM_PTR) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_1LM_PTR (SELF, LDCREATED)

CLASS (FIELD_1LM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_1LM_PTR (SELF, LDDELETED)

CLASS (FIELD_1LM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_1LM_PTR (SELF)
CLASS (FIELD_1LM_PTR) :: SELF

END SUBROUTINE 


END MODULE
