
MODULE FIELD_2RM_ACCESS_MODULE


USE FIELD_2RM_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


INTERFACE SGET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDONLY_FIELD_2RM
END INTERFACE SGET_DEVICE_DATA_RDONLY

PUBLIC :: SGET_DEVICE_DATA_RDONLY

INTERFACE GET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDONLY_FIELD_2RM
END INTERFACE GET_DEVICE_DATA_RDONLY

PUBLIC :: GET_DEVICE_DATA_RDONLY


INTERFACE SGET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: SGET_HOST_DATA_RDONLY_FIELD_2RM
END INTERFACE SGET_HOST_DATA_RDONLY

PUBLIC :: SGET_HOST_DATA_RDONLY

INTERFACE GET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: GET_HOST_DATA_RDONLY_FIELD_2RM
END INTERFACE GET_HOST_DATA_RDONLY

PUBLIC :: GET_HOST_DATA_RDONLY


INTERFACE SGET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDWR_FIELD_2RM
END INTERFACE SGET_DEVICE_DATA_RDWR

PUBLIC :: SGET_DEVICE_DATA_RDWR

INTERFACE GET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDWR_FIELD_2RM
END INTERFACE GET_DEVICE_DATA_RDWR

PUBLIC :: GET_DEVICE_DATA_RDWR


INTERFACE SGET_HOST_DATA_RDWR
  MODULE PROCEDURE :: SGET_HOST_DATA_RDWR_FIELD_2RM
END INTERFACE SGET_HOST_DATA_RDWR

PUBLIC :: SGET_HOST_DATA_RDWR

INTERFACE GET_HOST_DATA_RDWR
  MODULE PROCEDURE :: GET_HOST_DATA_RDWR_FIELD_2RM
END INTERFACE GET_HOST_DATA_RDWR

PUBLIC :: GET_HOST_DATA_RDWR


REAL(KIND=JPRM), TARGET, SAVE :: DUMMY_FIELD_2RM (1, 1)
!$acc declare create (DUMMY_FIELD_2RM)


CONTAINS


  SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_2RM (PTR, FIELD_PTR) 

    CLASS (FIELD_2RM), POINTER, OPTIONAL :: FIELD_PTR
    REAL(KIND=JPRM), POINTER :: PTR(:,:)

  END SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_2RM

  FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_2RM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_2RM), POINTER :: FIELD_PTR
    REAL(KIND=JPRM), POINTER :: PTR(:,:)

  END FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_2RM



  SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_2RM (PTR, FIELD_PTR) 

    CLASS (FIELD_2RM), POINTER, OPTIONAL :: FIELD_PTR
    REAL(KIND=JPRM), POINTER :: PTR(:,:)

  END SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_2RM

  FUNCTION GET_HOST_DATA_RDONLY_FIELD_2RM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_2RM), POINTER :: FIELD_PTR
    REAL(KIND=JPRM), POINTER :: PTR(:,:)

  END FUNCTION GET_HOST_DATA_RDONLY_FIELD_2RM



  SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_2RM (PTR, FIELD_PTR) 

    CLASS (FIELD_2RM), POINTER, OPTIONAL :: FIELD_PTR
    REAL(KIND=JPRM), POINTER :: PTR(:,:)

  END SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_2RM

  FUNCTION GET_DEVICE_DATA_RDWR_FIELD_2RM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_2RM), POINTER :: FIELD_PTR
    REAL(KIND=JPRM), POINTER :: PTR(:,:)

  END FUNCTION GET_DEVICE_DATA_RDWR_FIELD_2RM



  SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_2RM (PTR, FIELD_PTR) 

    CLASS (FIELD_2RM), POINTER, OPTIONAL :: FIELD_PTR
    REAL(KIND=JPRM), POINTER :: PTR(:,:)

  END SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_2RM

  FUNCTION GET_HOST_DATA_RDWR_FIELD_2RM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_2RM), POINTER :: FIELD_PTR
    REAL(KIND=JPRM), POINTER :: PTR(:,:)

  END FUNCTION GET_HOST_DATA_RDWR_FIELD_2RM



END MODULE FIELD_2RM_ACCESS_MODULE
