 

MODULE FIELD_VARIABLES_MOD

!$ACDC methods --methods-list=crc64,size,host,copy,wipe,legacy --field-api

  ! The FIELD_VARIABLES type provides namespaced access to all core
  ! VARIABLE objects used.
  !
  ! These VARIABLE objects are currently wrappers around GMV and GFL
  ! fields and provide accessor methods to the individual FIELD
  ! storage objects and NPROMA array views (sub-array blocks) in
  ! OpenMP loops. The FIELD_VARIABLES%UPDATE_VIEW(BLOCK_INDEX) utility
  ! ensures that all block pointers provided by the stored variable
  ! objects are pointing to the correct sub-arrry block.

USE PARKIND1, ONLY: JPIM, JPRB
USE VARIABLE_MODULE
USE YOMGMV, ONLY : TGMV
USE YOMGFL, ONLY : TGFL

IMPLICIT NONE

TYPE FIELD_VARIABLES
  TYPE(VARIABLE_3RB) :: U  ! U-wind
  TYPE(VARIABLE_3RB) :: V  ! V-wind
  TYPE(VARIABLE_3RB) :: T  ! Temperature
  TYPE(VARIABLE_3RB) :: DIV  ! Divergence
  TYPE(VARIABLE_3RB) :: VOR  ! Vorticity
  TYPE(VARIABLE_3RB) :: SPD  ! Pressure departure variable
  TYPE(VARIABLE_3RB) :: SVD  ! Vertical div or velocity variable
  TYPE(VARIABLE_3RB) :: CSPDNL  ! 
  TYPE(VARIABLE_3RB) :: CSPNL  ! 
  TYPE(VARIABLE_3RB) :: CSVDPT  ! 
  TYPE(VARIABLE_3RB) :: CTNL  ! 
  TYPE(VARIABLE_3RB) :: CTPT  ! 
  TYPE(VARIABLE_3RB) :: CUNL  ! 
  TYPE(VARIABLE_3RB) :: CUPT  ! 
  TYPE(VARIABLE_3RB) :: CVNL  ! 
  TYPE(VARIABLE_3RB) :: CVPT  ! 
  TYPE(VARIABLE_3RB) :: CVWVNL  ! 
  TYPE(VARIABLE_3RB) :: DPHI  ! 
  TYPE(VARIABLE_3RB) :: EDOT  ! 
  TYPE(VARIABLE_3RB) :: GW  ! 
  TYPE(VARIABLE_3RB) :: NHX  ! 
  TYPE(VARIABLE_3RB) :: NHY  ! 
  TYPE(VARIABLE_3RB) :: SGRTL  ! 
  TYPE(VARIABLE_3RB) :: SGRTM  ! 
  TYPE(VARIABLE_3RB) :: SPDNL  ! 
  TYPE(VARIABLE_3RB) :: SPDNL_SI  ! 
  TYPE(VARIABLE_3RB) :: SPNL  ! 
  TYPE(VARIABLE_3RB) :: SPNL_SI  ! 
  TYPE(VARIABLE_3RB) :: SVDNL_SI  ! 
  TYPE(VARIABLE_3RB) :: TNL  ! 
  TYPE(VARIABLE_3RB) :: TNL_SI  ! 
  TYPE(VARIABLE_3RB) :: UNL  ! 
  TYPE(VARIABLE_3RB) :: UNL_SI  ! 
  TYPE(VARIABLE_3RB) :: VNL  ! 
  TYPE(VARIABLE_3RB) :: VNL_SI  ! 
  TYPE(VARIABLE_3RB) :: VWVNL  ! 
  TYPE(VARIABLE_3RB) :: CURHS  ! 
  TYPE(VARIABLE_3RB) :: CVRHS  ! 
  TYPE(VARIABLE_3RB) :: CTRHS  ! 
  TYPE(VARIABLE_3RB) :: CSPDRHS  ! 
  TYPE(VARIABLE_3RB) :: CSVDRHS  ! 
  TYPE(VARIABLE_3RB) :: NHXNL  ! 
  TYPE(VARIABLE_3RB) :: CNHXNL  ! 
  TYPE(VARIABLE_3RB) :: PCF_U  ! 
  TYPE(VARIABLE_3RB) :: PCF_V  ! 
  TYPE(VARIABLE_3RB) :: PCF_T  ! 
  TYPE(VARIABLE_3RB) :: PCF_SPD  ! 
  TYPE(VARIABLE_3RB) :: PCF_SVD  ! 
  TYPE(VARIABLE_3RB) :: PCF_NHX  ! 
  TYPE(VARIABLE_3RB) :: PCF_SP  ! 
  TYPE(VARIABLE_3RB) :: PCF_CP  ! 
  TYPE(VARIABLE_3RB) :: PCF_UP  ! 
  TYPE(VARIABLE_3RB) :: PCF_VP  ! 
  TYPE(VARIABLE_3RB) :: PCF_TP  ! 
  TYPE(VARIABLE_2RB) :: SP  ! Surface pressure
  TYPE(VARIABLE_2RB) :: SPNL2  ! 
  TYPE(VARIABLE_2RB) :: PREHYDS  ! 
  TYPE(VARIABLE_2RB) :: DBBC  ! 
  TYPE(VARIABLE_2RB) :: CSPPT  ! 
  TYPE(VARIABLE_2RB) :: CSPNL2  ! 
  TYPE(VARIABLE_2RB) :: CSPRHS  ! 
  TYPE(VARIABLE_2RB) :: GWS  ! 
  TYPE(VARIABLE_2RB) :: PCF_BBC  ! 
  TYPE(VARIABLE_2RB) :: PCF_DPHI  ! 
  TYPE(VARIABLE_2RB) :: PCF_GWS  ! 
  TYPE(VARIABLE_3RB) :: Q  ! Specific humidity
  TYPE(VARIABLE_3RB) :: I  ! Ice water
  TYPE(VARIABLE_3RB) :: L  ! Liquid water
  TYPE(VARIABLE_3RB) :: IMF  ! Ice water from shallow convection
  TYPE(VARIABLE_3RB) :: LMF  ! Liquid water from shallow convection
  TYPE(VARIABLE_3RB) :: HLMF  ! High liquid water from shallow convection
  TYPE(VARIABLE_3RB) :: HIMF  ! High ice water from shallow convection
  TYPE(VARIABLE_3RB) :: LCONV  ! Liquid water (CONV. PART)
  TYPE(VARIABLE_3RB) :: ICONV  ! Ice    water (CONV. PART)
  TYPE(VARIABLE_3RB) :: RCONV  ! Rain         (CONV. PART)
  TYPE(VARIABLE_3RB) :: SCONV  ! Snow         (CONV. PART)
  TYPE(VARIABLE_3RB) :: IRAD  ! Radiative cloud Ice water
  TYPE(VARIABLE_3RB) :: LRAD  ! Radiative cloud Liquid water
  TYPE(VARIABLE_3RB) :: S  ! Snow
  TYPE(VARIABLE_3RB) :: R  ! Rain
  TYPE(VARIABLE_3RB) :: G  ! Graupel
  TYPE(VARIABLE_3RB) :: H  ! Hail
  TYPE(VARIABLE_3RB) :: TKE  ! Turbulent Kinetic Energy
  TYPE(VARIABLE_3RB) :: TTE  ! Turbulent Total Energy
  TYPE(VARIABLE_3RB) :: EFB1  ! First variable EFB scheme
  TYPE(VARIABLE_3RB) :: EFB2  ! Second variable EFB scheme
  TYPE(VARIABLE_3RB) :: EFB3  ! Third variable EFB scheme
  TYPE(VARIABLE_3RB) :: A  ! Cloud fraction
  TYPE(VARIABLE_3RB) :: AMF  ! Cloud fraction from shallow convection
  TYPE(VARIABLE_3RB) :: WMFC  ! Weight of the Mass-Flux cloud
  TYPE(VARIABLE_3RB) :: HLCFMF  ! High liquid cloud fraction due to Mass-Flux
  TYPE(VARIABLE_3RB) :: HICFMF  ! High ice cloud fraction due to Mass-Flux
  TYPE(VARIABLE_3RB) :: O3  ! Ozone
  TYPE(VARIABLE_3RB) :: SRC  ! Second-order flux for AROME s"rc"/2Sigma_s2 multiplied by Lambda_3
  TYPE(VARIABLE_3RB) :: MXL  ! Prognostic mixing length
  TYPE(VARIABLE_3RB) :: SHTUR  ! Shear source term for turbulence.
  TYPE(VARIABLE_3RB) :: FQTUR  ! Flux form source term for turbulence - moisture.
  TYPE(VARIABLE_3RB) :: FSTUR  ! Flux form source term for turbulence - enthalpy.
  TYPE(VARIABLE_3RB) :: CPF  ! Convective precipitation flux
  TYPE(VARIABLE_3RB) :: SPF  ! Stratiform precipitation flux
  TYPE(VARIABLE_3RB) :: CVGQ  ! Moisture Convergence for french physics
  TYPE(VARIABLE_3RB) :: QVA  ! Total humidity variation
  TYPE(VARIABLE_3RB), ALLOCATABLE :: GHG (:)  ! Greenhouse Gases
  TYPE(VARIABLE_3RB), ALLOCATABLE :: CHEM (:)  ! Chemistry
  TYPE(VARIABLE_3RB), ALLOCATABLE :: AERO (:)  ! Aerosols
  TYPE(VARIABLE_3RB) :: LRCH4  ! CH4 loss rate (instantaneous field)
  TYPE(VARIABLE_3RB), ALLOCATABLE :: FORC (:)  ! Large scale forcing
  TYPE(VARIABLE_3RB), ALLOCATABLE :: EZDIAG (:)  ! Easy diagnostics
  TYPE(VARIABLE_3RB), ALLOCATABLE :: ERA40 (:)  ! ERA40 diagnostic fields
  TYPE(VARIABLE_3RB), ALLOCATABLE :: NOGW (:)  ! NORO GWD SCHEME
  TYPE(VARIABLE_3RB), ALLOCATABLE :: EMIS3D (:)  ! 3D emission fields for composition
  TYPE(VARIABLE_3RB), ALLOCATABLE :: EDRP (:)  ! Turbulence diagnostics EDR Parameter
  TYPE(VARIABLE_3RB), ALLOCATABLE :: SLDIA (:)  ! SL dynamics diagnostics
  TYPE(VARIABLE_3RB), ALLOCATABLE :: AERAOT (:)  ! Aerosol optical thicknesses
  TYPE(VARIABLE_3RB), ALLOCATABLE :: AERLISI (:)  ! Aerosol lidar simulator
  TYPE(VARIABLE_3RB), ALLOCATABLE :: AEROUT (:)  ! Aerosol outputs
  TYPE(VARIABLE_3RB), ALLOCATABLE :: AEROCLIM (:)  ! Aerosol climatology
  TYPE(VARIABLE_3RB), ALLOCATABLE :: UVP (:)  ! UV-processor output
  TYPE(VARIABLE_3RB) :: PHYCTY  ! PHYS input for MassCTY
  TYPE(VARIABLE_3RB) :: RSPEC  ! Specific gas constant
  TYPE(VARIABLE_3RB) :: SDSAT  ! Standard Deviation of the saturation Depression (Sigma_s)
  TYPE(VARIABLE_3RB) :: CVV  ! Convective Vertical Velocity
  TYPE(VARIABLE_3RB) :: RKTH  ! Rasch-Kristjansson H tendency
  TYPE(VARIABLE_3RB) :: RKTQV  ! Rasch-Kristjansson Qv tendency
  TYPE(VARIABLE_3RB) :: RKTQC  ! Rasch-Kristjansson Qc tendency
  TYPE(VARIABLE_3RB) :: UOM  ! Updraught vert velocity
  TYPE(VARIABLE_3RB) :: UAL  ! Updraught mesh fraction
  TYPE(VARIABLE_3RB) :: DOM  ! Downdraught vert velocity
  TYPE(VARIABLE_3RB) :: DAL  ! Downdraught mesh fraction
  TYPE(VARIABLE_3RB) :: UEN  ! Updraught entrainment
  TYPE(VARIABLE_3RB) :: MO  ! Meso Scale Organisation
  TYPE(VARIABLE_3RB) :: UNEBH  ! pseudo-historic convective
  TYPE(VARIABLE_3RB), ALLOCATABLE :: LIMA (:)  ! LIMA prognostic fields
  TYPE(VARIABLE_3RB) :: FSD  ! PHYS output
  TYPE(VARIABLE_3RB), ALLOCATABLE :: EXT (:)  ! Extra fields
  TYPE(VARIABLE_3RB) :: THRAD  ! Radiation theta tendency

  TYPE(VARIABLE_3RB), ALLOCATABLE :: GFL_PTR (:)

CONTAINS
  ! PROCEDURE :: CLONE => FIELD_VARIABLES_CLONE
  PROCEDURE :: UPDATE_VIEW => FIELD_VARIABLES_UPDATE_VIEW
  PROCEDURE :: FINAL => FIELD_VARIABLES_FINAL
  ! Timestepping utilities
  PROCEDURE :: GFL_PH9TOT0 => FIELD_VARIABLES_GFL_PH9TOT0
  PROCEDURE :: GFL_PH9TOT9 => FIELD_VARIABLES_GFL_PH9TOT9
  PROCEDURE :: GMV_RESET_PH9 => FIELD_VARIABLES_GMV_RESET_PH9
END TYPE FIELD_VARIABLES

CONTAINS




  SUBROUTINE FIELD_VARIABLES_UPDATE_VIEW(SELF, BLOCK_INDEX)
    ! Update the internal data view pointers of all associated variables
    CLASS(FIELD_VARIABLES) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    INTEGER(KIND=JPIM) :: JFLD, INPTR


    INPTR = 1
    CALL SELF%U%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%V%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%T%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%DIV%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%VOR%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SPD%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SVD%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CSPDNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CSPNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CSVDPT%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CTNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CTPT%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CUNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CUPT%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CVNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CVPT%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CVWVNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%DPHI%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%EDOT%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%GW%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%NHX%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%NHY%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SGRTL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SGRTM%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SPDNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SPDNL_SI%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SPNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SPNL_SI%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SVDNL_SI%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%TNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%TNL_SI%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%UNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%UNL_SI%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%VNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%VNL_SI%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%VWVNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CURHS%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CVRHS%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CTRHS%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CSPDRHS%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CSVDRHS%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%NHXNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CNHXNL%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_U%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_V%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_T%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_SPD%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_SVD%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_NHX%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_SP%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_CP%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_UP%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_VP%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_TP%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SP%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%SPNL2%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PREHYDS%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%DBBC%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CSPPT%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CSPNL2%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%CSPRHS%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%GWS%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_BBC%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_DPHI%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%PCF_GWS%UPDATE_VIEW(BLOCK_INDEX)
    CALL SELF%Q%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%Q%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%Q%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%Q%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%Q%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%Q%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%Q%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%Q%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%Q%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%Q%DM9
    INPTR = INPTR + 1
    CALL SELF%I%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%I%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%I%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%I%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%I%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%I%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%I%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%I%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%I%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%I%DM9
    INPTR = INPTR + 1
    CALL SELF%L%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%L%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%L%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%L%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%L%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%L%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%L%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%L%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%L%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%L%DM9
    INPTR = INPTR + 1
    CALL SELF%IMF%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%IMF%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%IMF%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%IMF%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%IMF%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%IMF%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%IMF%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%IMF%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%IMF%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%IMF%DM9
    INPTR = INPTR + 1
    CALL SELF%LMF%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%LMF%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%LMF%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%LMF%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%LMF%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%LMF%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%LMF%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%LMF%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%LMF%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%LMF%DM9
    INPTR = INPTR + 1
    CALL SELF%HLMF%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%HLMF%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%HLMF%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%HLMF%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%HLMF%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%HLMF%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%HLMF%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%HLMF%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%HLMF%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%HLMF%DM9
    INPTR = INPTR + 1
    CALL SELF%HIMF%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%HIMF%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%HIMF%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%HIMF%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%HIMF%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%HIMF%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%HIMF%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%HIMF%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%HIMF%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%HIMF%DM9
    INPTR = INPTR + 1
    CALL SELF%LCONV%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%LCONV%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%LCONV%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%LCONV%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%LCONV%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%LCONV%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%LCONV%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%LCONV%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%LCONV%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%LCONV%DM9
    INPTR = INPTR + 1
    CALL SELF%ICONV%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%ICONV%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%ICONV%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%ICONV%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%ICONV%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%ICONV%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%ICONV%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%ICONV%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%ICONV%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%ICONV%DM9
    INPTR = INPTR + 1
    CALL SELF%RCONV%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%RCONV%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%RCONV%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%RCONV%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%RCONV%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%RCONV%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%RCONV%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%RCONV%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%RCONV%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%RCONV%DM9
    INPTR = INPTR + 1
    CALL SELF%SCONV%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%SCONV%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%SCONV%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%SCONV%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%SCONV%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%SCONV%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%SCONV%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%SCONV%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%SCONV%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%SCONV%DM9
    INPTR = INPTR + 1
    CALL SELF%IRAD%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%IRAD%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%IRAD%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%IRAD%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%IRAD%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%IRAD%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%IRAD%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%IRAD%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%IRAD%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%IRAD%DM9
    INPTR = INPTR + 1
    CALL SELF%LRAD%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%LRAD%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%LRAD%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%LRAD%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%LRAD%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%LRAD%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%LRAD%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%LRAD%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%LRAD%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%LRAD%DM9
    INPTR = INPTR + 1
    CALL SELF%S%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%S%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%S%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%S%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%S%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%S%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%S%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%S%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%S%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%S%DM9
    INPTR = INPTR + 1
    CALL SELF%R%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%R%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%R%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%R%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%R%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%R%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%R%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%R%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%R%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%R%DM9
    INPTR = INPTR + 1
    CALL SELF%G%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%G%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%G%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%G%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%G%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%G%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%G%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%G%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%G%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%G%DM9
    INPTR = INPTR + 1
    CALL SELF%H%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%H%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%H%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%H%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%H%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%H%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%H%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%H%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%H%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%H%DM9
    INPTR = INPTR + 1
    CALL SELF%TKE%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%TKE%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%TKE%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%TKE%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%TKE%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%TKE%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%TKE%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%TKE%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%TKE%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%TKE%DM9
    INPTR = INPTR + 1
    CALL SELF%TTE%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%TTE%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%TTE%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%TTE%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%TTE%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%TTE%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%TTE%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%TTE%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%TTE%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%TTE%DM9
    INPTR = INPTR + 1
    CALL SELF%EFB1%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%EFB1%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%EFB1%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%EFB1%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%EFB1%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%EFB1%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%EFB1%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%EFB1%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%EFB1%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%EFB1%DM9
    INPTR = INPTR + 1
    CALL SELF%EFB2%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%EFB2%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%EFB2%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%EFB2%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%EFB2%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%EFB2%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%EFB2%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%EFB2%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%EFB2%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%EFB2%DM9
    INPTR = INPTR + 1
    CALL SELF%EFB3%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%EFB3%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%EFB3%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%EFB3%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%EFB3%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%EFB3%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%EFB3%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%EFB3%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%EFB3%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%EFB3%DM9
    INPTR = INPTR + 1
    CALL SELF%A%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%A%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%A%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%A%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%A%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%A%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%A%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%A%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%A%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%A%DM9
    INPTR = INPTR + 1
    CALL SELF%AMF%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%AMF%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%AMF%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%AMF%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%AMF%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%AMF%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%AMF%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%AMF%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%AMF%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%AMF%DM9
    INPTR = INPTR + 1
    CALL SELF%WMFC%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%WMFC%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%WMFC%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%WMFC%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%WMFC%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%WMFC%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%WMFC%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%WMFC%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%WMFC%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%WMFC%DM9
    INPTR = INPTR + 1
    CALL SELF%HLCFMF%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%HLCFMF%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%HLCFMF%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%HLCFMF%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%HLCFMF%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%HLCFMF%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%HLCFMF%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%HLCFMF%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%HLCFMF%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%HLCFMF%DM9
    INPTR = INPTR + 1
    CALL SELF%HICFMF%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%HICFMF%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%HICFMF%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%HICFMF%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%HICFMF%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%HICFMF%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%HICFMF%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%HICFMF%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%HICFMF%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%HICFMF%DM9
    INPTR = INPTR + 1
    CALL SELF%O3%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%O3%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%O3%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%O3%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%O3%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%O3%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%O3%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%O3%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%O3%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%O3%DM9
    INPTR = INPTR + 1
    CALL SELF%SRC%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%SRC%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%SRC%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%SRC%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%SRC%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%SRC%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%SRC%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%SRC%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%SRC%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%SRC%DM9
    INPTR = INPTR + 1
    CALL SELF%MXL%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%MXL%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%MXL%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%MXL%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%MXL%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%MXL%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%MXL%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%MXL%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%MXL%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%MXL%DM9
    INPTR = INPTR + 1
    CALL SELF%SHTUR%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%SHTUR%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%SHTUR%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%SHTUR%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%SHTUR%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%SHTUR%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%SHTUR%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%SHTUR%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%SHTUR%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%SHTUR%DM9
    INPTR = INPTR + 1
    CALL SELF%FQTUR%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%FQTUR%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%FQTUR%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%FQTUR%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%FQTUR%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%FQTUR%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%FQTUR%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%FQTUR%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%FQTUR%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%FQTUR%DM9
    INPTR = INPTR + 1
    CALL SELF%FSTUR%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%FSTUR%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%FSTUR%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%FSTUR%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%FSTUR%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%FSTUR%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%FSTUR%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%FSTUR%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%FSTUR%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%FSTUR%DM9
    INPTR = INPTR + 1
    CALL SELF%CPF%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%CPF%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%CPF%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%CPF%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%CPF%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%CPF%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%CPF%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%CPF%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%CPF%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%CPF%DM9
    INPTR = INPTR + 1
    CALL SELF%SPF%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%SPF%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%SPF%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%SPF%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%SPF%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%SPF%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%SPF%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%SPF%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%SPF%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%SPF%DM9
    INPTR = INPTR + 1
    CALL SELF%CVGQ%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%CVGQ%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%CVGQ%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%CVGQ%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%CVGQ%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%CVGQ%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%CVGQ%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%CVGQ%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%CVGQ%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%CVGQ%DM9
    INPTR = INPTR + 1
    CALL SELF%QVA%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%QVA%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%QVA%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%QVA%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%QVA%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%QVA%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%QVA%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%QVA%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%QVA%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%QVA%DM9
    INPTR = INPTR + 1
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%GHG)
      CALL SELF%GHG(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%GHG(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%GHG(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%GHG(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%GHG(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%GHG(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%GHG(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%GHG(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%GHG(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%GHG(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%CHEM)
      CALL SELF%CHEM(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%CHEM(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%CHEM(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%CHEM(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%CHEM(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%CHEM(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%CHEM(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%CHEM(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%CHEM(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%CHEM(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%AERO)
      CALL SELF%AERO(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%AERO(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%AERO(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%AERO(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%AERO(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%AERO(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%AERO(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%AERO(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%AERO(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%AERO(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    CALL SELF%LRCH4%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%LRCH4%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%LRCH4%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%LRCH4%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%LRCH4%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%LRCH4%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%LRCH4%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%LRCH4%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%LRCH4%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%LRCH4%DM9
    INPTR = INPTR + 1
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%FORC)
      CALL SELF%FORC(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%FORC(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%FORC(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%FORC(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%FORC(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%FORC(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%FORC(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%FORC(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%FORC(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%FORC(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%EZDIAG)
      CALL SELF%EZDIAG(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%EZDIAG(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%EZDIAG(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%EZDIAG(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%EZDIAG(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%EZDIAG(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%EZDIAG(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%EZDIAG(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%EZDIAG(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%EZDIAG(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%ERA40)
      CALL SELF%ERA40(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%ERA40(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%ERA40(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%ERA40(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%ERA40(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%ERA40(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%ERA40(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%ERA40(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%ERA40(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%ERA40(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%NOGW)
      CALL SELF%NOGW(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%NOGW(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%NOGW(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%NOGW(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%NOGW(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%NOGW(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%NOGW(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%NOGW(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%NOGW(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%NOGW(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%EMIS3D)
      CALL SELF%EMIS3D(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%EMIS3D(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%EMIS3D(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%EMIS3D(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%EMIS3D(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%EMIS3D(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%EMIS3D(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%EMIS3D(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%EMIS3D(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%EMIS3D(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%EDRP)
      CALL SELF%EDRP(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%EDRP(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%EDRP(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%EDRP(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%EDRP(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%EDRP(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%EDRP(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%EDRP(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%EDRP(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%EDRP(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%SLDIA)
      CALL SELF%SLDIA(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%SLDIA(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%SLDIA(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%SLDIA(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%SLDIA(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%SLDIA(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%SLDIA(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%SLDIA(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%SLDIA(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%SLDIA(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%AERAOT)
      CALL SELF%AERAOT(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%AERAOT(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%AERAOT(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%AERAOT(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%AERAOT(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%AERAOT(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%AERAOT(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%AERAOT(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%AERAOT(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%AERAOT(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%AERLISI)
      CALL SELF%AERLISI(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%AERLISI(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%AERLISI(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%AERLISI(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%AERLISI(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%AERLISI(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%AERLISI(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%AERLISI(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%AERLISI(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%AERLISI(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%AEROUT)
      CALL SELF%AEROUT(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%AEROUT(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%AEROUT(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%AEROUT(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%AEROUT(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%AEROUT(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%AEROUT(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%AEROUT(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%AEROUT(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%AEROUT(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%AEROCLIM)
      CALL SELF%AEROCLIM(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%AEROCLIM(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%AEROCLIM(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%AEROCLIM(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%AEROCLIM(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%AEROCLIM(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%AEROCLIM(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%AEROCLIM(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%AEROCLIM(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%AEROCLIM(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%UVP)
      CALL SELF%UVP(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%UVP(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%UVP(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%UVP(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%UVP(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%UVP(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%UVP(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%UVP(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%UVP(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%UVP(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    CALL SELF%PHYCTY%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%PHYCTY%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%PHYCTY%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%PHYCTY%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%PHYCTY%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%PHYCTY%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%PHYCTY%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%PHYCTY%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%PHYCTY%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%PHYCTY%DM9
    INPTR = INPTR + 1
    CALL SELF%RSPEC%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%RSPEC%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%RSPEC%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%RSPEC%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%RSPEC%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%RSPEC%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%RSPEC%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%RSPEC%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%RSPEC%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%RSPEC%DM9
    INPTR = INPTR + 1
    CALL SELF%SDSAT%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%SDSAT%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%SDSAT%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%SDSAT%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%SDSAT%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%SDSAT%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%SDSAT%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%SDSAT%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%SDSAT%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%SDSAT%DM9
    INPTR = INPTR + 1
    CALL SELF%CVV%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%CVV%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%CVV%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%CVV%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%CVV%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%CVV%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%CVV%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%CVV%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%CVV%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%CVV%DM9
    INPTR = INPTR + 1
    CALL SELF%RKTH%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%RKTH%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%RKTH%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%RKTH%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%RKTH%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%RKTH%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%RKTH%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%RKTH%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%RKTH%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%RKTH%DM9
    INPTR = INPTR + 1
    CALL SELF%RKTQV%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%RKTQV%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%RKTQV%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%RKTQV%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%RKTQV%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%RKTQV%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%RKTQV%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%RKTQV%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%RKTQV%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%RKTQV%DM9
    INPTR = INPTR + 1
    CALL SELF%RKTQC%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%RKTQC%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%RKTQC%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%RKTQC%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%RKTQC%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%RKTQC%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%RKTQC%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%RKTQC%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%RKTQC%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%RKTQC%DM9
    INPTR = INPTR + 1
    CALL SELF%UOM%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%UOM%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%UOM%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%UOM%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%UOM%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%UOM%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%UOM%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%UOM%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%UOM%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%UOM%DM9
    INPTR = INPTR + 1
    CALL SELF%UAL%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%UAL%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%UAL%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%UAL%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%UAL%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%UAL%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%UAL%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%UAL%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%UAL%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%UAL%DM9
    INPTR = INPTR + 1
    CALL SELF%DOM%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%DOM%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%DOM%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%DOM%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%DOM%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%DOM%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%DOM%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%DOM%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%DOM%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%DOM%DM9
    INPTR = INPTR + 1
    CALL SELF%DAL%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%DAL%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%DAL%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%DAL%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%DAL%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%DAL%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%DAL%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%DAL%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%DAL%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%DAL%DM9
    INPTR = INPTR + 1
    CALL SELF%UEN%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%UEN%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%UEN%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%UEN%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%UEN%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%UEN%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%UEN%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%UEN%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%UEN%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%UEN%DM9
    INPTR = INPTR + 1
    CALL SELF%MO%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%MO%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%MO%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%MO%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%MO%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%MO%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%MO%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%MO%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%MO%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%MO%DM9
    INPTR = INPTR + 1
    CALL SELF%UNEBH%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%UNEBH%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%UNEBH%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%UNEBH%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%UNEBH%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%UNEBH%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%UNEBH%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%UNEBH%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%UNEBH%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%UNEBH%DM9
    INPTR = INPTR + 1
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%LIMA)
      CALL SELF%LIMA(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%LIMA(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%LIMA(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%LIMA(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%LIMA(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%LIMA(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%LIMA(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%LIMA(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%LIMA(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%LIMA(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    CALL SELF%FSD%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%FSD%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%FSD%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%FSD%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%FSD%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%FSD%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%FSD%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%FSD%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%FSD%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%FSD%DM9
    INPTR = INPTR + 1
    ! Note, we assume allocation of size 0 for inactive variables!
    DO JFLD=1, SIZE(SELF%EXT)
      CALL SELF%EXT(JFLD)%UPDATE_VIEW(BLOCK_INDEX)
      SELF%GFL_PTR (INPTR)%P => SELF%EXT(JFLD)%P
      SELF%GFL_PTR (INPTR)%T0 => SELF%EXT(JFLD)%T0
      SELF%GFL_PTR (INPTR)%T1 => SELF%EXT(JFLD)%T1
      SELF%GFL_PTR (INPTR)%T9 => SELF%EXT(JFLD)%T9
      SELF%GFL_PTR (INPTR)%PH9 => SELF%EXT(JFLD)%PH9
      SELF%GFL_PTR (INPTR)%DL => SELF%EXT(JFLD)%DL
      SELF%GFL_PTR (INPTR)%DM => SELF%EXT(JFLD)%DM
      SELF%GFL_PTR (INPTR)%DL9 => SELF%EXT(JFLD)%DL9
      SELF%GFL_PTR (INPTR)%DM9 => SELF%EXT(JFLD)%DM9
      INPTR = INPTR + 1
    END DO
    CALL SELF%THRAD%UPDATE_VIEW(BLOCK_INDEX)
    SELF%GFL_PTR (INPTR)%P => SELF%THRAD%P
    SELF%GFL_PTR (INPTR)%T0 => SELF%THRAD%T0
    SELF%GFL_PTR (INPTR)%T1 => SELF%THRAD%T1
    SELF%GFL_PTR (INPTR)%T9 => SELF%THRAD%T9
    SELF%GFL_PTR (INPTR)%PH9 => SELF%THRAD%PH9
    SELF%GFL_PTR (INPTR)%DL => SELF%THRAD%DL
    SELF%GFL_PTR (INPTR)%DM => SELF%THRAD%DM
    SELF%GFL_PTR (INPTR)%DL9 => SELF%THRAD%DL9
    SELF%GFL_PTR (INPTR)%DM9 => SELF%THRAD%DM9
    INPTR = INPTR + 1

  END SUBROUTINE FIELD_VARIABLES_UPDATE_VIEW

  SUBROUTINE FIELD_VARIABLES_FINAL(SELF)
    ! Update the internal data view pointers of all associated variables
    CLASS(FIELD_VARIABLES) :: SELF
    INTEGER(KIND=JPIM) :: I

    CALL SELF%U%FINAL()
    CALL SELF%V%FINAL()
    CALL SELF%T%FINAL()
    CALL SELF%DIV%FINAL()
    CALL SELF%VOR%FINAL()
    CALL SELF%SPD%FINAL()
    CALL SELF%SVD%FINAL()
    CALL SELF%CSPDNL%FINAL()
    CALL SELF%CSPNL%FINAL()
    CALL SELF%CSVDPT%FINAL()
    CALL SELF%CTNL%FINAL()
    CALL SELF%CTPT%FINAL()
    CALL SELF%CUNL%FINAL()
    CALL SELF%CUPT%FINAL()
    CALL SELF%CVNL%FINAL()
    CALL SELF%CVPT%FINAL()
    CALL SELF%CVWVNL%FINAL()
    CALL SELF%DPHI%FINAL()
    CALL SELF%EDOT%FINAL()
    CALL SELF%GW%FINAL()
    CALL SELF%NHX%FINAL()
    CALL SELF%NHY%FINAL()
    CALL SELF%SGRTL%FINAL()
    CALL SELF%SGRTM%FINAL()
    CALL SELF%SPDNL%FINAL()
    CALL SELF%SPDNL_SI%FINAL()
    CALL SELF%SPNL%FINAL()
    CALL SELF%SPNL_SI%FINAL()
    CALL SELF%SVDNL_SI%FINAL()
    CALL SELF%TNL%FINAL()
    CALL SELF%TNL_SI%FINAL()
    CALL SELF%UNL%FINAL()
    CALL SELF%UNL_SI%FINAL()
    CALL SELF%VNL%FINAL()
    CALL SELF%VNL_SI%FINAL()
    CALL SELF%VWVNL%FINAL()
    CALL SELF%CURHS%FINAL()
    CALL SELF%CVRHS%FINAL()
    CALL SELF%CTRHS%FINAL()
    CALL SELF%CSPDRHS%FINAL()
    CALL SELF%CSVDRHS%FINAL()
    CALL SELF%NHXNL%FINAL()
    CALL SELF%CNHXNL%FINAL()
    CALL SELF%PCF_U%FINAL()
    CALL SELF%PCF_V%FINAL()
    CALL SELF%PCF_T%FINAL()
    CALL SELF%PCF_SPD%FINAL()
    CALL SELF%PCF_SVD%FINAL()
    CALL SELF%PCF_NHX%FINAL()
    CALL SELF%PCF_SP%FINAL()
    CALL SELF%PCF_CP%FINAL()
    CALL SELF%PCF_UP%FINAL()
    CALL SELF%PCF_VP%FINAL()
    CALL SELF%PCF_TP%FINAL()
    CALL SELF%SP%FINAL()
    CALL SELF%SPNL2%FINAL()
    CALL SELF%PREHYDS%FINAL()
    CALL SELF%DBBC%FINAL()
    CALL SELF%CSPPT%FINAL()
    CALL SELF%CSPNL2%FINAL()
    CALL SELF%CSPRHS%FINAL()
    CALL SELF%GWS%FINAL()
    CALL SELF%PCF_BBC%FINAL()
    CALL SELF%PCF_DPHI%FINAL()
    CALL SELF%PCF_GWS%FINAL()
    CALL SELF%Q%FINAL()
    CALL SELF%I%FINAL()
    CALL SELF%L%FINAL()
    CALL SELF%IMF%FINAL()
    CALL SELF%LMF%FINAL()
    CALL SELF%HLMF%FINAL()
    CALL SELF%HIMF%FINAL()
    CALL SELF%LCONV%FINAL()
    CALL SELF%ICONV%FINAL()
    CALL SELF%RCONV%FINAL()
    CALL SELF%SCONV%FINAL()
    CALL SELF%IRAD%FINAL()
    CALL SELF%LRAD%FINAL()
    CALL SELF%S%FINAL()
    CALL SELF%R%FINAL()
    CALL SELF%G%FINAL()
    CALL SELF%H%FINAL()
    CALL SELF%TKE%FINAL()
    CALL SELF%TTE%FINAL()
    CALL SELF%EFB1%FINAL()
    CALL SELF%EFB2%FINAL()
    CALL SELF%EFB3%FINAL()
    CALL SELF%A%FINAL()
    CALL SELF%AMF%FINAL()
    CALL SELF%WMFC%FINAL()
    CALL SELF%HLCFMF%FINAL()
    CALL SELF%HICFMF%FINAL()
    CALL SELF%O3%FINAL()
    CALL SELF%SRC%FINAL()
    CALL SELF%MXL%FINAL()
    CALL SELF%SHTUR%FINAL()
    CALL SELF%FQTUR%FINAL()
    CALL SELF%FSTUR%FINAL()
    CALL SELF%CPF%FINAL()
    CALL SELF%SPF%FINAL()
    CALL SELF%CVGQ%FINAL()
    CALL SELF%QVA%FINAL()
    IF (ALLOCATED(SELF%GHG)) THEN
      DO I=1, SIZE(SELF%GHG)
        CALL SELF%GHG(I)%FINAL()
      END DO
      DEALLOCATE(SELF%GHG)
    END IF
    IF (ALLOCATED(SELF%CHEM)) THEN
      DO I=1, SIZE(SELF%CHEM)
        CALL SELF%CHEM(I)%FINAL()
      END DO
      DEALLOCATE(SELF%CHEM)
    END IF
    IF (ALLOCATED(SELF%AERO)) THEN
      DO I=1, SIZE(SELF%AERO)
        CALL SELF%AERO(I)%FINAL()
      END DO
      DEALLOCATE(SELF%AERO)
    END IF
    CALL SELF%LRCH4%FINAL()
    IF (ALLOCATED(SELF%FORC)) THEN
      DO I=1, SIZE(SELF%FORC)
        CALL SELF%FORC(I)%FINAL()
      END DO
      DEALLOCATE(SELF%FORC)
    END IF
    IF (ALLOCATED(SELF%EZDIAG)) THEN
      DO I=1, SIZE(SELF%EZDIAG)
        CALL SELF%EZDIAG(I)%FINAL()
      END DO
      DEALLOCATE(SELF%EZDIAG)
    END IF
    IF (ALLOCATED(SELF%ERA40)) THEN
      DO I=1, SIZE(SELF%ERA40)
        CALL SELF%ERA40(I)%FINAL()
      END DO
      DEALLOCATE(SELF%ERA40)
    END IF
    IF (ALLOCATED(SELF%NOGW)) THEN
      DO I=1, SIZE(SELF%NOGW)
        CALL SELF%NOGW(I)%FINAL()
      END DO
      DEALLOCATE(SELF%NOGW)
    END IF
    IF (ALLOCATED(SELF%EMIS3D)) THEN
      DO I=1, SIZE(SELF%EMIS3D)
        CALL SELF%EMIS3D(I)%FINAL()
      END DO
      DEALLOCATE(SELF%EMIS3D)
    END IF
    IF (ALLOCATED(SELF%EDRP)) THEN
      DO I=1, SIZE(SELF%EDRP)
        CALL SELF%EDRP(I)%FINAL()
      END DO
      DEALLOCATE(SELF%EDRP)
    END IF
    IF (ALLOCATED(SELF%SLDIA)) THEN
      DO I=1, SIZE(SELF%SLDIA)
        CALL SELF%SLDIA(I)%FINAL()
      END DO
      DEALLOCATE(SELF%SLDIA)
    END IF
    IF (ALLOCATED(SELF%AERAOT)) THEN
      DO I=1, SIZE(SELF%AERAOT)
        CALL SELF%AERAOT(I)%FINAL()
      END DO
      DEALLOCATE(SELF%AERAOT)
    END IF
    IF (ALLOCATED(SELF%AERLISI)) THEN
      DO I=1, SIZE(SELF%AERLISI)
        CALL SELF%AERLISI(I)%FINAL()
      END DO
      DEALLOCATE(SELF%AERLISI)
    END IF
    IF (ALLOCATED(SELF%AEROUT)) THEN
      DO I=1, SIZE(SELF%AEROUT)
        CALL SELF%AEROUT(I)%FINAL()
      END DO
      DEALLOCATE(SELF%AEROUT)
    END IF
    IF (ALLOCATED(SELF%AEROCLIM)) THEN
      DO I=1, SIZE(SELF%AEROCLIM)
        CALL SELF%AEROCLIM(I)%FINAL()
      END DO
      DEALLOCATE(SELF%AEROCLIM)
    END IF
    IF (ALLOCATED(SELF%UVP)) THEN
      DO I=1, SIZE(SELF%UVP)
        CALL SELF%UVP(I)%FINAL()
      END DO
      DEALLOCATE(SELF%UVP)
    END IF
    CALL SELF%PHYCTY%FINAL()
    CALL SELF%RSPEC%FINAL()
    CALL SELF%SDSAT%FINAL()
    CALL SELF%CVV%FINAL()
    CALL SELF%RKTH%FINAL()
    CALL SELF%RKTQV%FINAL()
    CALL SELF%RKTQC%FINAL()
    CALL SELF%UOM%FINAL()
    CALL SELF%UAL%FINAL()
    CALL SELF%DOM%FINAL()
    CALL SELF%DAL%FINAL()
    CALL SELF%UEN%FINAL()
    CALL SELF%MO%FINAL()
    CALL SELF%UNEBH%FINAL()
    IF (ALLOCATED(SELF%LIMA)) THEN
      DO I=1, SIZE(SELF%LIMA)
        CALL SELF%LIMA(I)%FINAL()
      END DO
      DEALLOCATE(SELF%LIMA)
    END IF
    CALL SELF%FSD%FINAL()
    IF (ALLOCATED(SELF%EXT)) THEN
      DO I=1, SIZE(SELF%EXT)
        CALL SELF%EXT(I)%FINAL()
      END DO
      DEALLOCATE(SELF%EXT)
    END IF
    CALL SELF%THRAD%FINAL()

  DEALLOCATE (SELF%GFL_PTR)

  END SUBROUTINE FIELD_VARIABLES_FINAL

  SUBROUTINE FIELD_VARIABLES_GFL_PH9TOT0(SELF)
    ! Utility routine that aliases the PH9 field of GLF variables with T0
    CLASS(FIELD_VARIABLES) :: SELF
    INTEGER(KIND=JPIM) :: I

    CALL SELF%Q%PH9TOT0()
    CALL SELF%I%PH9TOT0()
    CALL SELF%L%PH9TOT0()
    CALL SELF%IMF%PH9TOT0()
    CALL SELF%LMF%PH9TOT0()
    CALL SELF%HLMF%PH9TOT0()
    CALL SELF%HIMF%PH9TOT0()
    CALL SELF%LCONV%PH9TOT0()
    CALL SELF%ICONV%PH9TOT0()
    CALL SELF%RCONV%PH9TOT0()
    CALL SELF%SCONV%PH9TOT0()
    CALL SELF%IRAD%PH9TOT0()
    CALL SELF%LRAD%PH9TOT0()
    CALL SELF%S%PH9TOT0()
    CALL SELF%R%PH9TOT0()
    CALL SELF%G%PH9TOT0()
    CALL SELF%H%PH9TOT0()
    CALL SELF%TKE%PH9TOT0()
    CALL SELF%TTE%PH9TOT0()
    CALL SELF%EFB1%PH9TOT0()
    CALL SELF%EFB2%PH9TOT0()
    CALL SELF%EFB3%PH9TOT0()
    CALL SELF%A%PH9TOT0()
    CALL SELF%AMF%PH9TOT0()
    CALL SELF%WMFC%PH9TOT0()
    CALL SELF%HLCFMF%PH9TOT0()
    CALL SELF%HICFMF%PH9TOT0()
    CALL SELF%O3%PH9TOT0()
    CALL SELF%SRC%PH9TOT0()
    CALL SELF%MXL%PH9TOT0()
    CALL SELF%SHTUR%PH9TOT0()
    CALL SELF%FQTUR%PH9TOT0()
    CALL SELF%FSTUR%PH9TOT0()
    CALL SELF%CPF%PH9TOT0()
    CALL SELF%SPF%PH9TOT0()
    CALL SELF%CVGQ%PH9TOT0()
    CALL SELF%QVA%PH9TOT0()
    DO I=1, SIZE(SELF%GHG)
      CALL SELF%GHG(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%CHEM)
      CALL SELF%CHEM(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%AERO)
      CALL SELF%AERO(I)%PH9TOT0()
    END DO
    CALL SELF%LRCH4%PH9TOT0()
    DO I=1, SIZE(SELF%FORC)
      CALL SELF%FORC(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%EZDIAG)
      CALL SELF%EZDIAG(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%ERA40)
      CALL SELF%ERA40(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%NOGW)
      CALL SELF%NOGW(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%EMIS3D)
      CALL SELF%EMIS3D(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%EDRP)
      CALL SELF%EDRP(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%SLDIA)
      CALL SELF%SLDIA(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%AERAOT)
      CALL SELF%AERAOT(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%AERLISI)
      CALL SELF%AERLISI(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%AEROUT)
      CALL SELF%AEROUT(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%AEROCLIM)
      CALL SELF%AEROCLIM(I)%PH9TOT0()
    END DO
    DO I=1, SIZE(SELF%UVP)
      CALL SELF%UVP(I)%PH9TOT0()
    END DO
    CALL SELF%PHYCTY%PH9TOT0()
    CALL SELF%RSPEC%PH9TOT0()
    CALL SELF%SDSAT%PH9TOT0()
    CALL SELF%CVV%PH9TOT0()
    CALL SELF%RKTH%PH9TOT0()
    CALL SELF%RKTQV%PH9TOT0()
    CALL SELF%RKTQC%PH9TOT0()
    CALL SELF%UOM%PH9TOT0()
    CALL SELF%UAL%PH9TOT0()
    CALL SELF%DOM%PH9TOT0()
    CALL SELF%DAL%PH9TOT0()
    CALL SELF%UEN%PH9TOT0()
    CALL SELF%MO%PH9TOT0()
    CALL SELF%UNEBH%PH9TOT0()
    DO I=1, SIZE(SELF%LIMA)
      CALL SELF%LIMA(I)%PH9TOT0()
    END DO
    CALL SELF%FSD%PH9TOT0()
    DO I=1, SIZE(SELF%EXT)
      CALL SELF%EXT(I)%PH9TOT0()
    END DO
    CALL SELF%THRAD%PH9TOT0()
  END SUBROUTINE FIELD_VARIABLES_GFL_PH9TOT0

  SUBROUTINE FIELD_VARIABLES_GFL_PH9TOT9(SELF)
    ! Utility routine that aliases the PH9 field of GLF variables with T9
    CLASS(FIELD_VARIABLES) :: SELF
    INTEGER(KIND=JPIM) :: I

    CALL SELF%Q%PH9TOT9()
    CALL SELF%I%PH9TOT9()
    CALL SELF%L%PH9TOT9()
    CALL SELF%IMF%PH9TOT9()
    CALL SELF%LMF%PH9TOT9()
    CALL SELF%HLMF%PH9TOT9()
    CALL SELF%HIMF%PH9TOT9()
    CALL SELF%LCONV%PH9TOT9()
    CALL SELF%ICONV%PH9TOT9()
    CALL SELF%RCONV%PH9TOT9()
    CALL SELF%SCONV%PH9TOT9()
    CALL SELF%IRAD%PH9TOT9()
    CALL SELF%LRAD%PH9TOT9()
    CALL SELF%S%PH9TOT9()
    CALL SELF%R%PH9TOT9()
    CALL SELF%G%PH9TOT9()
    CALL SELF%H%PH9TOT9()
    CALL SELF%TKE%PH9TOT9()
    CALL SELF%TTE%PH9TOT9()
    CALL SELF%EFB1%PH9TOT9()
    CALL SELF%EFB2%PH9TOT9()
    CALL SELF%EFB3%PH9TOT9()
    CALL SELF%A%PH9TOT9()
    CALL SELF%AMF%PH9TOT9()
    CALL SELF%WMFC%PH9TOT9()
    CALL SELF%HLCFMF%PH9TOT9()
    CALL SELF%HICFMF%PH9TOT9()
    CALL SELF%O3%PH9TOT9()
    CALL SELF%SRC%PH9TOT9()
    CALL SELF%MXL%PH9TOT9()
    CALL SELF%SHTUR%PH9TOT9()
    CALL SELF%FQTUR%PH9TOT9()
    CALL SELF%FSTUR%PH9TOT9()
    CALL SELF%CPF%PH9TOT9()
    CALL SELF%SPF%PH9TOT9()
    CALL SELF%CVGQ%PH9TOT9()
    CALL SELF%QVA%PH9TOT9()
    DO I=1, SIZE(SELF%GHG)
      CALL SELF%GHG(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%CHEM)
      CALL SELF%CHEM(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%AERO)
      CALL SELF%AERO(I)%PH9TOT9()
    END DO
    CALL SELF%LRCH4%PH9TOT9()
    DO I=1, SIZE(SELF%FORC)
      CALL SELF%FORC(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%EZDIAG)
      CALL SELF%EZDIAG(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%ERA40)
      CALL SELF%ERA40(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%NOGW)
      CALL SELF%NOGW(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%EMIS3D)
      CALL SELF%EMIS3D(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%EDRP)
      CALL SELF%EDRP(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%SLDIA)
      CALL SELF%SLDIA(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%AERAOT)
      CALL SELF%AERAOT(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%AERLISI)
      CALL SELF%AERLISI(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%AEROUT)
      CALL SELF%AEROUT(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%AEROCLIM)
      CALL SELF%AEROCLIM(I)%PH9TOT9()
    END DO
    DO I=1, SIZE(SELF%UVP)
      CALL SELF%UVP(I)%PH9TOT9()
    END DO
    CALL SELF%PHYCTY%PH9TOT9()
    CALL SELF%RSPEC%PH9TOT9()
    CALL SELF%SDSAT%PH9TOT9()
    CALL SELF%CVV%PH9TOT9()
    CALL SELF%RKTH%PH9TOT9()
    CALL SELF%RKTQV%PH9TOT9()
    CALL SELF%RKTQC%PH9TOT9()
    CALL SELF%UOM%PH9TOT9()
    CALL SELF%UAL%PH9TOT9()
    CALL SELF%DOM%PH9TOT9()
    CALL SELF%DAL%PH9TOT9()
    CALL SELF%UEN%PH9TOT9()
    CALL SELF%MO%PH9TOT9()
    CALL SELF%UNEBH%PH9TOT9()
    DO I=1, SIZE(SELF%LIMA)
      CALL SELF%LIMA(I)%PH9TOT9()
    END DO
    CALL SELF%FSD%PH9TOT9()
    DO I=1, SIZE(SELF%EXT)
      CALL SELF%EXT(I)%PH9TOT9()
    END DO
    CALL SELF%THRAD%PH9TOT9()
  END SUBROUTINE FIELD_VARIABLES_GFL_PH9TOT9

  SUBROUTINE FIELD_VARIABLES_GMV_RESET_PH9(SELF, YDGMV, YDGFL)
    ! Re-associate the PH9 field pointers of GMV variables
    !
    ! This is needed to ensure that certain time-stepping
    ! schemes pass the right fields into the physics routines.
    CLASS(FIELD_VARIABLES) :: SELF
    TYPE(TGMV), TARGET, INTENT(INOUT) :: YDGMV
    TYPE(TGFL), TARGET, INTENT(INOUT) :: YDGFL

  END SUBROUTINE FIELD_VARIABLES_GMV_RESET_PH9

END MODULE FIELD_VARIABLES_MOD
