MODULE FIELD_5LM_ARRAY_UTIL_MODULE


USE FIELD_5LM_ARRAY_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_5LM_ARRAY
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_5LM_ARRAY
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_5LM_ARRAY
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_5LM_ARRAY
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_5LM_ARRAY
END INTERFACE


CONTAINS


SUBROUTINE LOAD_FIELD_5LM_ARRAY (KLUN, YD)

USE FIELD_5LM_UTIL_MODULE, ONLY : LOAD

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
TYPE (FIELD_5LM_ARRAY) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_5LM_ARRAY (KLUN, YD)

USE FIELD_5LM_UTIL_MODULE, ONLY : SAVE

END SUBROUTINE

SUBROUTINE COPY_FIELD_5LM_ARRAY (SELF, LDCREATED, LDFIELDAPI)

USE FIELD_5LM_UTIL_MODULE, ONLY : COPY

TYPE (FIELD_5LM_ARRAY) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED, LDFIELDAPI

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_5LM_ARRAY (SELF, LDDELETED, LDFIELDAPI)

USE FIELD_5LM_UTIL_MODULE, ONLY : WIPE

TYPE (FIELD_5LM_ARRAY) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED, LDFIELDAPI
LOGICAL :: LLFIELDAPI, LLDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_5LM_ARRAY (SELF)

USE FIELD_5LM_UTIL_MODULE, ONLY : HOST

TYPE (FIELD_5LM_ARRAY) :: SELF

END SUBROUTINE 


END MODULE
