
MODULE FIELD_2RD_ARRAY_MODULE

!$ACDC methods --methods-list=host --skip-components cpg --field-api --field-api-class cpg


USE FIELD_2RD_MODULE
USE FIELD_2RD_FACTORY_MODULE
USE FIELD_2RD_UTIL_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

TYPE FIELD_2RD_ARRAY
  CLASS (FIELD_2RD), POINTER :: F_P => NULL ()
  REAL(KIND=JPRD), POINTER, CONTIGUOUS :: P_FIELD (:,:) => NULL()
  REAL(KIND=JPRD), POINTER :: P (:) => NULL()
CONTAINS
  GENERIC :: INIT => INIT_FIELD_2RD_ARRAY_WRAPPER, INIT_FIELD_2RD_ARRAY_OWNER
  PROCEDURE, PRIVATE :: INIT_FIELD_2RD_ARRAY_WRAPPER
  PROCEDURE, PRIVATE :: INIT_FIELD_2RD_ARRAY_OWNER
  PROCEDURE :: RESIZE => RESIZE_FIELD_2RD_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_2RD_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_2RD_ARRAY
END TYPE

PUBLIC :: FIELD_2RD_ARRAY


CONTAINS

SUBROUTINE INIT_FIELD_2RD_ARRAY_WRAPPER (SELF, P, LBOUNDS)

CLASS (FIELD_2RD_ARRAY) :: SELF
REAL(KIND=JPRD), INTENT (IN), TARGET :: P (:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)

END SUBROUTINE

SUBROUTINE INIT_FIELD_2RD_ARRAY_OWNER (SELF, PERSISTENT, UBOUNDS, LBOUNDS)

CLASS (FIELD_2RD_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
LOGICAL,             INTENT (IN), OPTIONAL :: PERSISTENT

END SUBROUTINE

SUBROUTINE RESIZE_FIELD_2RD_ARRAY (SELF, UBOUNDS, LBOUNDS, PERSISTENT)

CLASS (FIELD_2RD_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
LOGICAL,             INTENT (IN), OPTIONAL :: PERSISTENT

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_2RD_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_2RD_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_2RD_ARRAY (SELF)
CLASS (FIELD_2RD_ARRAY) :: SELF

END SUBROUTINE


END MODULE
