
MODULE FIELD_1RD_ARRAY_MODULE

!$ACDC methods --methods-list=host --skip-components cpg --field-api --field-api-class cpg


USE FIELD_1RD_MODULE
USE FIELD_1RD_FACTORY_MODULE
USE FIELD_1RD_UTIL_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

TYPE FIELD_1RD_ARRAY
  CLASS (FIELD_1RD), POINTER :: F_P => NULL ()
  REAL(KIND=JPRD), POINTER, CONTIGUOUS :: P_FIELD (:) => NULL()
CONTAINS
  GENERIC :: INIT => INIT_FIELD_1RD_ARRAY_WRAPPER, INIT_FIELD_1RD_ARRAY_OWNER
  PROCEDURE, PRIVATE :: INIT_FIELD_1RD_ARRAY_WRAPPER
  PROCEDURE, PRIVATE :: INIT_FIELD_1RD_ARRAY_OWNER
  PROCEDURE :: RESIZE => RESIZE_FIELD_1RD_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_1RD_ARRAY
END TYPE

PUBLIC :: FIELD_1RD_ARRAY


CONTAINS

SUBROUTINE INIT_FIELD_1RD_ARRAY_WRAPPER (SELF, P, LBOUNDS)

CLASS (FIELD_1RD_ARRAY) :: SELF
REAL(KIND=JPRD), INTENT (IN), TARGET :: P (:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)

END SUBROUTINE

SUBROUTINE INIT_FIELD_1RD_ARRAY_OWNER (SELF, PERSISTENT, UBOUNDS, LBOUNDS)

CLASS (FIELD_1RD_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
LOGICAL,             INTENT (IN), OPTIONAL :: PERSISTENT

END SUBROUTINE

SUBROUTINE RESIZE_FIELD_1RD_ARRAY (SELF, UBOUNDS, LBOUNDS, PERSISTENT)

CLASS (FIELD_1RD_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (1)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (1)
LOGICAL,             INTENT (IN), OPTIONAL :: PERSISTENT

END SUBROUTINE


SUBROUTINE FINAL_FIELD_1RD_ARRAY (SELF)
CLASS (FIELD_1RD_ARRAY) :: SELF

END SUBROUTINE


END MODULE
