
MODULE FIELD_2RM_ARRAY_MODULE

!$ACDC methods --methods-list=host --skip-components cpg --field-api --field-api-class cpg


USE FIELD_2RM_MODULE
USE FIELD_2RM_FACTORY_MODULE
USE FIELD_2RM_UTIL_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

TYPE FIELD_2RM_ARRAY
  CLASS (FIELD_2RM), POINTER :: F_P => NULL ()
  REAL(KIND=JPRM), POINTER, CONTIGUOUS :: P_FIELD (:,:) => NULL()
  REAL(KIND=JPRM), POINTER :: P (:) => NULL()
CONTAINS
  GENERIC :: INIT => INIT_FIELD_2RM_ARRAY_WRAPPER, INIT_FIELD_2RM_ARRAY_OWNER
  PROCEDURE, PRIVATE :: INIT_FIELD_2RM_ARRAY_WRAPPER
  PROCEDURE, PRIVATE :: INIT_FIELD_2RM_ARRAY_OWNER
  PROCEDURE :: RESIZE => RESIZE_FIELD_2RM_ARRAY
  PROCEDURE :: FINAL => FINAL_FIELD_2RM_ARRAY
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_FIELD_2RM_ARRAY
END TYPE

PUBLIC :: FIELD_2RM_ARRAY


CONTAINS

SUBROUTINE INIT_FIELD_2RM_ARRAY_WRAPPER (SELF, P, LBOUNDS)

CLASS (FIELD_2RM_ARRAY) :: SELF
REAL(KIND=JPRM), INTENT (IN), TARGET :: P (:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)

END SUBROUTINE

SUBROUTINE INIT_FIELD_2RM_ARRAY_OWNER (SELF, PERSISTENT, UBOUNDS, LBOUNDS)

CLASS (FIELD_2RM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
LOGICAL,             INTENT (IN), OPTIONAL :: PERSISTENT

END SUBROUTINE

SUBROUTINE RESIZE_FIELD_2RM_ARRAY (SELF, UBOUNDS, LBOUNDS, PERSISTENT)

CLASS (FIELD_2RM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)
LOGICAL,             INTENT (IN), OPTIONAL :: PERSISTENT

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_FIELD_2RM_ARRAY (SELF, BLOCK_INDEX)
CLASS (FIELD_2RM_ARRAY) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

END SUBROUTINE

SUBROUTINE FINAL_FIELD_2RM_ARRAY (SELF)
CLASS (FIELD_2RM_ARRAY) :: SELF

END SUBROUTINE


END MODULE
