
MODULE FIELD_5RD_GANG_MODULE

USE FIELD_BASIC_MODULE




USE FIELD_5RD_MODULE
USE FIELD_4RD_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


TYPE, EXTENDS (FIELD_4RD_WRAPPER) :: FIELD_4RD_WRAPPER_HELPER
  CLASS (FIELD_BASIC), POINTER :: PARENT => NULL ()
CONTAINS
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_4RD_DELETE_DEVICE_DATA_WRAPPER_HELPER
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_4RD_CREATE_DEVICE_DATA_WRAPPER_HELPER
  PROCEDURE :: SET_DEVICE_DIRTY => FIELD_4RD_SET_DEVICE_DIRTY_DATA_WRAPPER_HELPER
  PROCEDURE :: GET_DEVICE_DATA => FIELD_4RD_GET_DEVICE_DATA_WRAPPER_HELPER
  PROCEDURE :: GET_HOST_DATA => FIELD_4RD_GET_HOST_DATA_WRAPPER_HELPER
END TYPE

TYPE FIELD_4RD_WRAPPER_HELPER_PTR
  CLASS (FIELD_4RD_WRAPPER_HELPER), POINTER :: PTR => NULL ()
END TYPE


TYPE, EXTENDS (FIELD_5RD_WRAPPER) :: FIELD_5RD_GANG_WRAPPER
  TYPE (FIELD_4RD_WRAPPER_HELPER_PTR), POINTER :: CHILDREN (:) => NULL ()
CONTAINS
  PROCEDURE :: INIT => FIELD_5RD_GANG_WRAPPER_INIT
  PROCEDURE :: FINAL => FIELD_5RD_GANG_WRAPPER_FINAL
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_5RD_GANG_WRAPPER_CREATE_DEVICE_DATA
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_5RD_GANG_WRAPPER_DELETE_DEVICE_DATA
  PROCEDURE :: SET_STATUS => FIELD_5RD_GANG_WRAPPER_SET_STATUS
END TYPE FIELD_5RD_GANG_WRAPPER

PUBLIC :: FIELD_5RD_GANG_WRAPPER


TYPE, EXTENDS (FIELD_5RD_OWNER) :: FIELD_5RD_GANG_OWNER
  TYPE (FIELD_4RD_WRAPPER_HELPER_PTR), POINTER :: CHILDREN (:) => NULL ()
CONTAINS
  PROCEDURE :: INIT => FIELD_5RD_GANG_OWNER_INIT
  PROCEDURE :: FINAL => FIELD_5RD_GANG_OWNER_FINAL
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_5RD_GANG_OWNER_CREATE_DEVICE_DATA
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_5RD_GANG_OWNER_DELETE_DEVICE_DATA
  PROCEDURE :: SET_STATUS => FIELD_5RD_GANG_OWNER_SET_STATUS
END TYPE FIELD_5RD_GANG_OWNER

PUBLIC :: FIELD_5RD_GANG_OWNER


CONTAINS

  SUBROUTINE FIELD_4RD_CREATE_DEVICE_DATA_WRAPPER_HELPER (SELF)
    CLASS(FIELD_4RD_WRAPPER_HELPER) :: SELF

  END SUBROUTINE

  SUBROUTINE FIELD_4RD_DELETE_DEVICE_DATA_WRAPPER_HELPER (SELF)
    CLASS(FIELD_4RD_WRAPPER_HELPER) :: SELF

  END SUBROUTINE

  SUBROUTINE FIELD_4RD_SET_DEVICE_DIRTY_DATA_WRAPPER_HELPER (SELF)

    CLASS (FIELD_4RD_WRAPPER_HELPER) :: SELF

  END SUBROUTINE 

  SUBROUTINE FIELD_4RD_GET_HOST_DATA_WRAPPER_HELPER (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_4RD_WRAPPER_HELPER) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    REAL(KIND=JPRD), POINTER,         INTENT(INOUT) :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    INTEGER(KIND=JPIM)                           :: LBOUNDS(4)

  END SUBROUTINE 

  SUBROUTINE FIELD_4RD_GET_DEVICE_DATA_WRAPPER_HELPER (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_4RD_WRAPPER_HELPER) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    REAL(KIND=JPRD), POINTER,         INTENT(INOUT) :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    INTEGER(KIND=JPIM)                           :: LBOUNDS(4)

  END SUBROUTINE 


  SUBROUTINE FIELD_5RD_GANG_WRAPPER_INIT(SELF, DATA, PERSISTENT, LBOUNDS, MAP_DEVPTR, SYNC_ON_FINAL, INITIALIZED)

    CLASS(FIELD_5RD_GANG_WRAPPER) :: SELF
    REAL(KIND=JPRD), TARGET, INTENT(IN) :: DATA(:,:,:,:,:)
    LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(5)
    LOGICAL, INTENT(IN), OPTIONAL :: MAP_DEVPTR
    LOGICAL, INTENT(IN), OPTIONAL :: SYNC_ON_FINAL
    LOGICAL, INTENT(IN), OPTIONAL :: INITIALIZED

  END SUBROUTINE FIELD_5RD_GANG_WRAPPER_INIT

  SUBROUTINE FIELD_5RD_GANG_OWNER_INIT(SELF, LBOUNDS, UBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR, POOLED)

    CLASS(FIELD_5RD_GANG_OWNER) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(5)
    INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(5)
    LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
    LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
    REAL(KIND=JPRD), OPTIONAL, INTENT(IN) :: INIT_VALUE
    LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
    LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
    LOGICAL, OPTIONAL,  INTENT(IN) :: POOLED

  END SUBROUTINE FIELD_5RD_GANG_OWNER_INIT

  SUBROUTINE FIELD_5RD_GANG_WRAPPER_FINAL(SELF)

    CLASS(FIELD_5RD_GANG_WRAPPER) :: SELF
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)
    INTEGER (KIND=JPIM) :: JFLD
    CLASS (FIELD_4RD_WRAPPER_HELPER), POINTER :: YLF

  END SUBROUTINE FIELD_5RD_GANG_WRAPPER_FINAL

  SUBROUTINE FIELD_5RD_GANG_WRAPPER_DELETE_DEVICE_DATA(SELF)
    ! Delete the copy of this field on GPU device
    CLASS(FIELD_5RD_GANG_WRAPPER) :: SELF

  END SUBROUTINE FIELD_5RD_GANG_WRAPPER_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_5RD_GANG_WRAPPER_CREATE_DEVICE_DATA (SELF)
    CLASS(FIELD_5RD_GANG_WRAPPER) :: SELF
    INTEGER (KIND=JPIM) :: JFLD

  END SUBROUTINE

  SUBROUTINE FIELD_5RD_GANG_WRAPPER_SET_STATUS (SELF, KSTATUS)
    CLASS(FIELD_5RD_GANG_WRAPPER) :: SELF
    INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

  END SUBROUTINE

  SUBROUTINE FIELD_5RD_GANG_OWNER_FINAL(SELF)

    CLASS(FIELD_5RD_GANG_OWNER) :: SELF
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)
    INTEGER (KIND=JPIM) :: JFLD
    CLASS (FIELD_4RD_WRAPPER_HELPER), POINTER :: YLF

  END SUBROUTINE FIELD_5RD_GANG_OWNER_FINAL

  SUBROUTINE FIELD_5RD_GANG_OWNER_DELETE_DEVICE_DATA(SELF)
    ! Delete the copy of this field on GPU device
    CLASS(FIELD_5RD_GANG_OWNER) :: SELF

  END SUBROUTINE FIELD_5RD_GANG_OWNER_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_5RD_GANG_OWNER_CREATE_DEVICE_DATA (SELF)
    CLASS(FIELD_5RD_GANG_OWNER) :: SELF
    INTEGER (KIND=JPIM) :: JFLD

  END SUBROUTINE

  SUBROUTINE FIELD_5RD_GANG_OWNER_SET_STATUS (SELF, KSTATUS)
    CLASS(FIELD_5RD_GANG_OWNER) :: SELF
    INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

  END SUBROUTINE



END MODULE FIELD_5RD_GANG_MODULE
