
MODULE FIELD_UTIL_MODULE



#ifdef PARKIND1_SINGLE


USE FIELD_1RM_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_1RB => LOAD_FIELD_1RM,  LOAD_FIELD_1RM, LOAD,      &
      & LOAD_FIELD_1RB_PTR  => LOAD_FIELD_1RM_PTR,   LOAD_FIELD_1RM_PTR,    &
      & SAVE_FIELD_1RB => SAVE_FIELD_1RM,  SAVE_FIELD_1RM, SAVE,      &
      & SAVE_FIELD_1RB_PTR  => SAVE_FIELD_1RM_PTR,   SAVE_FIELD_1RM_PTR,    &
      & DIFF_FIELD_1RB => DIFF_FIELD_1RM,  DIFF_FIELD_1RM, DIFF,      &
      & COPY_FIELD_1RB => COPY_FIELD_1RM,  COPY_FIELD_1RM, COPY,      &
      & COPY_FIELD_1RB_PTR  => COPY_FIELD_1RM_PTR,   COPY_FIELD_1RM_PTR,    &
      & WIPE_FIELD_1RB => WIPE_FIELD_1RM,  WIPE_FIELD_1RM, WIPE,      &
      & WIPE_FIELD_1RB_PTR  => WIPE_FIELD_1RM_PTR,   WIPE_FIELD_1RM_PTR,    &
      & HOST_FIELD_1RB => HOST_FIELD_1RM,  HOST_FIELD_1RM, HOST,      &
      & HOST_FIELD_1RB_PTR  => HOST_FIELD_1RM_PTR,   HOST_FIELD_1RM_PTR,    &
      & LEGACY_FIELD_1RB => LEGACY_FIELD_1RM,  LEGACY_FIELD_1RM, LEGACY,      &
      & COPY
USE FIELD_2RM_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_2RB => LOAD_FIELD_2RM,  LOAD_FIELD_2RM, LOAD,      &
      & LOAD_FIELD_2RB_PTR  => LOAD_FIELD_2RM_PTR,   LOAD_FIELD_2RM_PTR,    &
      & LOAD_FIELD_2RB_VIEW => LOAD_FIELD_2RM_VIEW,  LOAD_FIELD_2RM_VIEW,   &
      & SAVE_FIELD_2RB => SAVE_FIELD_2RM,  SAVE_FIELD_2RM, SAVE,      &
      & SAVE_FIELD_2RB_PTR  => SAVE_FIELD_2RM_PTR,   SAVE_FIELD_2RM_PTR,    &
      & SAVE_FIELD_2RB_VIEW => SAVE_FIELD_2RM_VIEW,  SAVE_FIELD_2RM_VIEW,   &
      & DIFF_FIELD_2RB => DIFF_FIELD_2RM,  DIFF_FIELD_2RM, DIFF,      &
      & COPY_FIELD_2RB => COPY_FIELD_2RM,  COPY_FIELD_2RM, COPY,      &
      & COPY_FIELD_2RB_PTR  => COPY_FIELD_2RM_PTR,   COPY_FIELD_2RM_PTR,    &
      & COPY_FIELD_2RB_VIEW => COPY_FIELD_2RM_VIEW,  COPY_FIELD_2RM_VIEW,   &
      & WIPE_FIELD_2RB => WIPE_FIELD_2RM,  WIPE_FIELD_2RM, WIPE,      &
      & WIPE_FIELD_2RB_PTR  => WIPE_FIELD_2RM_PTR,   WIPE_FIELD_2RM_PTR,    &
      & WIPE_FIELD_2RB_VIEW => WIPE_FIELD_2RM_VIEW,  WIPE_FIELD_2RM_VIEW,   &
      & HOST_FIELD_2RB => HOST_FIELD_2RM,  HOST_FIELD_2RM, HOST,      &
      & HOST_FIELD_2RB_PTR  => HOST_FIELD_2RM_PTR,   HOST_FIELD_2RM_PTR,    &
      & HOST_FIELD_2RB_VIEW => HOST_FIELD_2RM_VIEW,  HOST_FIELD_2RM_VIEW,   &
      & LEGACY_FIELD_2RB => LEGACY_FIELD_2RM,  LEGACY_FIELD_2RM, LEGACY,      &
      & COPY
USE FIELD_3RM_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_3RB => LOAD_FIELD_3RM,  LOAD_FIELD_3RM, LOAD,      &
      & LOAD_FIELD_3RB_PTR  => LOAD_FIELD_3RM_PTR,   LOAD_FIELD_3RM_PTR,    &
      & LOAD_FIELD_3RB_VIEW => LOAD_FIELD_3RM_VIEW,  LOAD_FIELD_3RM_VIEW,   &
      & SAVE_FIELD_3RB => SAVE_FIELD_3RM,  SAVE_FIELD_3RM, SAVE,      &
      & SAVE_FIELD_3RB_PTR  => SAVE_FIELD_3RM_PTR,   SAVE_FIELD_3RM_PTR,    &
      & SAVE_FIELD_3RB_VIEW => SAVE_FIELD_3RM_VIEW,  SAVE_FIELD_3RM_VIEW,   &
      & DIFF_FIELD_3RB => DIFF_FIELD_3RM,  DIFF_FIELD_3RM, DIFF,      &
      & COPY_FIELD_3RB => COPY_FIELD_3RM,  COPY_FIELD_3RM, COPY,      &
      & COPY_FIELD_3RB_PTR  => COPY_FIELD_3RM_PTR,   COPY_FIELD_3RM_PTR,    &
      & COPY_FIELD_3RB_VIEW => COPY_FIELD_3RM_VIEW,  COPY_FIELD_3RM_VIEW,   &
      & WIPE_FIELD_3RB => WIPE_FIELD_3RM,  WIPE_FIELD_3RM, WIPE,      &
      & WIPE_FIELD_3RB_PTR  => WIPE_FIELD_3RM_PTR,   WIPE_FIELD_3RM_PTR,    &
      & WIPE_FIELD_3RB_VIEW => WIPE_FIELD_3RM_VIEW,  WIPE_FIELD_3RM_VIEW,   &
      & HOST_FIELD_3RB => HOST_FIELD_3RM,  HOST_FIELD_3RM, HOST,      &
      & HOST_FIELD_3RB_PTR  => HOST_FIELD_3RM_PTR,   HOST_FIELD_3RM_PTR,    &
      & HOST_FIELD_3RB_VIEW => HOST_FIELD_3RM_VIEW,  HOST_FIELD_3RM_VIEW,   &
      & LEGACY_FIELD_3RB => LEGACY_FIELD_3RM,  LEGACY_FIELD_3RM, LEGACY,      &
      & COPY
USE FIELD_4RM_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_4RB => LOAD_FIELD_4RM,  LOAD_FIELD_4RM, LOAD,      &
      & LOAD_FIELD_4RB_PTR  => LOAD_FIELD_4RM_PTR,   LOAD_FIELD_4RM_PTR,    &
      & LOAD_FIELD_4RB_VIEW => LOAD_FIELD_4RM_VIEW,  LOAD_FIELD_4RM_VIEW,   &
      & SAVE_FIELD_4RB => SAVE_FIELD_4RM,  SAVE_FIELD_4RM, SAVE,      &
      & SAVE_FIELD_4RB_PTR  => SAVE_FIELD_4RM_PTR,   SAVE_FIELD_4RM_PTR,    &
      & SAVE_FIELD_4RB_VIEW => SAVE_FIELD_4RM_VIEW,  SAVE_FIELD_4RM_VIEW,   &
      & DIFF_FIELD_4RB => DIFF_FIELD_4RM,  DIFF_FIELD_4RM, DIFF,      &
      & COPY_FIELD_4RB => COPY_FIELD_4RM,  COPY_FIELD_4RM, COPY,      &
      & COPY_FIELD_4RB_PTR  => COPY_FIELD_4RM_PTR,   COPY_FIELD_4RM_PTR,    &
      & COPY_FIELD_4RB_VIEW => COPY_FIELD_4RM_VIEW,  COPY_FIELD_4RM_VIEW,   &
      & WIPE_FIELD_4RB => WIPE_FIELD_4RM,  WIPE_FIELD_4RM, WIPE,      &
      & WIPE_FIELD_4RB_PTR  => WIPE_FIELD_4RM_PTR,   WIPE_FIELD_4RM_PTR,    &
      & WIPE_FIELD_4RB_VIEW => WIPE_FIELD_4RM_VIEW,  WIPE_FIELD_4RM_VIEW,   &
      & HOST_FIELD_4RB => HOST_FIELD_4RM,  HOST_FIELD_4RM, HOST,      &
      & HOST_FIELD_4RB_PTR  => HOST_FIELD_4RM_PTR,   HOST_FIELD_4RM_PTR,    &
      & HOST_FIELD_4RB_VIEW => HOST_FIELD_4RM_VIEW,  HOST_FIELD_4RM_VIEW,   &
      & LEGACY_FIELD_4RB => LEGACY_FIELD_4RM,  LEGACY_FIELD_4RM, LEGACY,      &
      & COPY
USE FIELD_5RM_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_5RB => LOAD_FIELD_5RM,  LOAD_FIELD_5RM, LOAD,      &
      & LOAD_FIELD_5RB_PTR  => LOAD_FIELD_5RM_PTR,   LOAD_FIELD_5RM_PTR,    &
      & LOAD_FIELD_5RB_VIEW => LOAD_FIELD_5RM_VIEW,  LOAD_FIELD_5RM_VIEW,   &
      & SAVE_FIELD_5RB => SAVE_FIELD_5RM,  SAVE_FIELD_5RM, SAVE,      &
      & SAVE_FIELD_5RB_PTR  => SAVE_FIELD_5RM_PTR,   SAVE_FIELD_5RM_PTR,    &
      & SAVE_FIELD_5RB_VIEW => SAVE_FIELD_5RM_VIEW,  SAVE_FIELD_5RM_VIEW,   &
      & DIFF_FIELD_5RB => DIFF_FIELD_5RM,  DIFF_FIELD_5RM, DIFF,      &
      & COPY_FIELD_5RB => COPY_FIELD_5RM,  COPY_FIELD_5RM, COPY,      &
      & COPY_FIELD_5RB_PTR  => COPY_FIELD_5RM_PTR,   COPY_FIELD_5RM_PTR,    &
      & COPY_FIELD_5RB_VIEW => COPY_FIELD_5RM_VIEW,  COPY_FIELD_5RM_VIEW,   &
      & WIPE_FIELD_5RB => WIPE_FIELD_5RM,  WIPE_FIELD_5RM, WIPE,      &
      & WIPE_FIELD_5RB_PTR  => WIPE_FIELD_5RM_PTR,   WIPE_FIELD_5RM_PTR,    &
      & WIPE_FIELD_5RB_VIEW => WIPE_FIELD_5RM_VIEW,  WIPE_FIELD_5RM_VIEW,   &
      & HOST_FIELD_5RB => HOST_FIELD_5RM,  HOST_FIELD_5RM, HOST,      &
      & HOST_FIELD_5RB_PTR  => HOST_FIELD_5RM_PTR,   HOST_FIELD_5RM_PTR,    &
      & HOST_FIELD_5RB_VIEW => HOST_FIELD_5RM_VIEW,  HOST_FIELD_5RM_VIEW,   &
      & LEGACY_FIELD_5RB => LEGACY_FIELD_5RM,  LEGACY_FIELD_5RM, LEGACY,      &
      & COPY

USE FIELD_1RD_UTIL_MODULE
USE FIELD_2RD_UTIL_MODULE
USE FIELD_3RD_UTIL_MODULE
USE FIELD_4RD_UTIL_MODULE
USE FIELD_5RD_UTIL_MODULE
USE FIELD_1IM_UTIL_MODULE
USE FIELD_2IM_UTIL_MODULE
USE FIELD_3IM_UTIL_MODULE
USE FIELD_4IM_UTIL_MODULE
USE FIELD_5IM_UTIL_MODULE
USE FIELD_1LM_UTIL_MODULE
USE FIELD_2LM_UTIL_MODULE
USE FIELD_3LM_UTIL_MODULE
USE FIELD_4LM_UTIL_MODULE
USE FIELD_5LM_UTIL_MODULE

#else


USE FIELD_1RD_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_1RB => LOAD_FIELD_1RD,  LOAD_FIELD_1RD, LOAD,      &
      & LOAD_FIELD_1RB_PTR  => LOAD_FIELD_1RD_PTR,   LOAD_FIELD_1RD_PTR,    &
      & SAVE_FIELD_1RB => SAVE_FIELD_1RD,  SAVE_FIELD_1RD, SAVE,      &
      & SAVE_FIELD_1RB_PTR  => SAVE_FIELD_1RD_PTR,   SAVE_FIELD_1RD_PTR,    &
      & DIFF_FIELD_1RB => DIFF_FIELD_1RD,  DIFF_FIELD_1RD, DIFF,      &
      & COPY_FIELD_1RB => COPY_FIELD_1RD,  COPY_FIELD_1RD, COPY,      &
      & COPY_FIELD_1RB_PTR  => COPY_FIELD_1RD_PTR,   COPY_FIELD_1RD_PTR,    &
      & WIPE_FIELD_1RB => WIPE_FIELD_1RD,  WIPE_FIELD_1RD, WIPE,      &
      & WIPE_FIELD_1RB_PTR  => WIPE_FIELD_1RD_PTR,   WIPE_FIELD_1RD_PTR,    &
      & HOST_FIELD_1RB => HOST_FIELD_1RD,  HOST_FIELD_1RD, HOST,      &
      & HOST_FIELD_1RB_PTR  => HOST_FIELD_1RD_PTR,   HOST_FIELD_1RD_PTR,    &
      & LEGACY_FIELD_1RB => LEGACY_FIELD_1RD,  LEGACY_FIELD_1RD, LEGACY,      &
      & COPY
USE FIELD_2RD_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_2RB => LOAD_FIELD_2RD,  LOAD_FIELD_2RD, LOAD,      &
      & LOAD_FIELD_2RB_PTR  => LOAD_FIELD_2RD_PTR,   LOAD_FIELD_2RD_PTR,    &
      & LOAD_FIELD_2RB_VIEW => LOAD_FIELD_2RD_VIEW,  LOAD_FIELD_2RD_VIEW,   &
      & SAVE_FIELD_2RB => SAVE_FIELD_2RD,  SAVE_FIELD_2RD, SAVE,      &
      & SAVE_FIELD_2RB_PTR  => SAVE_FIELD_2RD_PTR,   SAVE_FIELD_2RD_PTR,    &
      & SAVE_FIELD_2RB_VIEW => SAVE_FIELD_2RD_VIEW,  SAVE_FIELD_2RD_VIEW,   &
      & DIFF_FIELD_2RB => DIFF_FIELD_2RD,  DIFF_FIELD_2RD, DIFF,      &
      & COPY_FIELD_2RB => COPY_FIELD_2RD,  COPY_FIELD_2RD, COPY,      &
      & COPY_FIELD_2RB_PTR  => COPY_FIELD_2RD_PTR,   COPY_FIELD_2RD_PTR,    &
      & COPY_FIELD_2RB_VIEW => COPY_FIELD_2RD_VIEW,  COPY_FIELD_2RD_VIEW,   &
      & WIPE_FIELD_2RB => WIPE_FIELD_2RD,  WIPE_FIELD_2RD, WIPE,      &
      & WIPE_FIELD_2RB_PTR  => WIPE_FIELD_2RD_PTR,   WIPE_FIELD_2RD_PTR,    &
      & WIPE_FIELD_2RB_VIEW => WIPE_FIELD_2RD_VIEW,  WIPE_FIELD_2RD_VIEW,   &
      & HOST_FIELD_2RB => HOST_FIELD_2RD,  HOST_FIELD_2RD, HOST,      &
      & HOST_FIELD_2RB_PTR  => HOST_FIELD_2RD_PTR,   HOST_FIELD_2RD_PTR,    &
      & HOST_FIELD_2RB_VIEW => HOST_FIELD_2RD_VIEW,  HOST_FIELD_2RD_VIEW,   &
      & LEGACY_FIELD_2RB => LEGACY_FIELD_2RD,  LEGACY_FIELD_2RD, LEGACY,      &
      & COPY
USE FIELD_3RD_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_3RB => LOAD_FIELD_3RD,  LOAD_FIELD_3RD, LOAD,      &
      & LOAD_FIELD_3RB_PTR  => LOAD_FIELD_3RD_PTR,   LOAD_FIELD_3RD_PTR,    &
      & LOAD_FIELD_3RB_VIEW => LOAD_FIELD_3RD_VIEW,  LOAD_FIELD_3RD_VIEW,   &
      & SAVE_FIELD_3RB => SAVE_FIELD_3RD,  SAVE_FIELD_3RD, SAVE,      &
      & SAVE_FIELD_3RB_PTR  => SAVE_FIELD_3RD_PTR,   SAVE_FIELD_3RD_PTR,    &
      & SAVE_FIELD_3RB_VIEW => SAVE_FIELD_3RD_VIEW,  SAVE_FIELD_3RD_VIEW,   &
      & DIFF_FIELD_3RB => DIFF_FIELD_3RD,  DIFF_FIELD_3RD, DIFF,      &
      & COPY_FIELD_3RB => COPY_FIELD_3RD,  COPY_FIELD_3RD, COPY,      &
      & COPY_FIELD_3RB_PTR  => COPY_FIELD_3RD_PTR,   COPY_FIELD_3RD_PTR,    &
      & COPY_FIELD_3RB_VIEW => COPY_FIELD_3RD_VIEW,  COPY_FIELD_3RD_VIEW,   &
      & WIPE_FIELD_3RB => WIPE_FIELD_3RD,  WIPE_FIELD_3RD, WIPE,      &
      & WIPE_FIELD_3RB_PTR  => WIPE_FIELD_3RD_PTR,   WIPE_FIELD_3RD_PTR,    &
      & WIPE_FIELD_3RB_VIEW => WIPE_FIELD_3RD_VIEW,  WIPE_FIELD_3RD_VIEW,   &
      & HOST_FIELD_3RB => HOST_FIELD_3RD,  HOST_FIELD_3RD, HOST,      &
      & HOST_FIELD_3RB_PTR  => HOST_FIELD_3RD_PTR,   HOST_FIELD_3RD_PTR,    &
      & HOST_FIELD_3RB_VIEW => HOST_FIELD_3RD_VIEW,  HOST_FIELD_3RD_VIEW,   &
      & LEGACY_FIELD_3RB => LEGACY_FIELD_3RD,  LEGACY_FIELD_3RD, LEGACY,      &
      & COPY
USE FIELD_4RD_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_4RB => LOAD_FIELD_4RD,  LOAD_FIELD_4RD, LOAD,      &
      & LOAD_FIELD_4RB_PTR  => LOAD_FIELD_4RD_PTR,   LOAD_FIELD_4RD_PTR,    &
      & LOAD_FIELD_4RB_VIEW => LOAD_FIELD_4RD_VIEW,  LOAD_FIELD_4RD_VIEW,   &
      & SAVE_FIELD_4RB => SAVE_FIELD_4RD,  SAVE_FIELD_4RD, SAVE,      &
      & SAVE_FIELD_4RB_PTR  => SAVE_FIELD_4RD_PTR,   SAVE_FIELD_4RD_PTR,    &
      & SAVE_FIELD_4RB_VIEW => SAVE_FIELD_4RD_VIEW,  SAVE_FIELD_4RD_VIEW,   &
      & DIFF_FIELD_4RB => DIFF_FIELD_4RD,  DIFF_FIELD_4RD, DIFF,      &
      & COPY_FIELD_4RB => COPY_FIELD_4RD,  COPY_FIELD_4RD, COPY,      &
      & COPY_FIELD_4RB_PTR  => COPY_FIELD_4RD_PTR,   COPY_FIELD_4RD_PTR,    &
      & COPY_FIELD_4RB_VIEW => COPY_FIELD_4RD_VIEW,  COPY_FIELD_4RD_VIEW,   &
      & WIPE_FIELD_4RB => WIPE_FIELD_4RD,  WIPE_FIELD_4RD, WIPE,      &
      & WIPE_FIELD_4RB_PTR  => WIPE_FIELD_4RD_PTR,   WIPE_FIELD_4RD_PTR,    &
      & WIPE_FIELD_4RB_VIEW => WIPE_FIELD_4RD_VIEW,  WIPE_FIELD_4RD_VIEW,   &
      & HOST_FIELD_4RB => HOST_FIELD_4RD,  HOST_FIELD_4RD, HOST,      &
      & HOST_FIELD_4RB_PTR  => HOST_FIELD_4RD_PTR,   HOST_FIELD_4RD_PTR,    &
      & HOST_FIELD_4RB_VIEW => HOST_FIELD_4RD_VIEW,  HOST_FIELD_4RD_VIEW,   &
      & LEGACY_FIELD_4RB => LEGACY_FIELD_4RD,  LEGACY_FIELD_4RD, LEGACY,      &
      & COPY
USE FIELD_5RD_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_5RB => LOAD_FIELD_5RD,  LOAD_FIELD_5RD, LOAD,      &
      & LOAD_FIELD_5RB_PTR  => LOAD_FIELD_5RD_PTR,   LOAD_FIELD_5RD_PTR,    &
      & LOAD_FIELD_5RB_VIEW => LOAD_FIELD_5RD_VIEW,  LOAD_FIELD_5RD_VIEW,   &
      & SAVE_FIELD_5RB => SAVE_FIELD_5RD,  SAVE_FIELD_5RD, SAVE,      &
      & SAVE_FIELD_5RB_PTR  => SAVE_FIELD_5RD_PTR,   SAVE_FIELD_5RD_PTR,    &
      & SAVE_FIELD_5RB_VIEW => SAVE_FIELD_5RD_VIEW,  SAVE_FIELD_5RD_VIEW,   &
      & DIFF_FIELD_5RB => DIFF_FIELD_5RD,  DIFF_FIELD_5RD, DIFF,      &
      & COPY_FIELD_5RB => COPY_FIELD_5RD,  COPY_FIELD_5RD, COPY,      &
      & COPY_FIELD_5RB_PTR  => COPY_FIELD_5RD_PTR,   COPY_FIELD_5RD_PTR,    &
      & COPY_FIELD_5RB_VIEW => COPY_FIELD_5RD_VIEW,  COPY_FIELD_5RD_VIEW,   &
      & WIPE_FIELD_5RB => WIPE_FIELD_5RD,  WIPE_FIELD_5RD, WIPE,      &
      & WIPE_FIELD_5RB_PTR  => WIPE_FIELD_5RD_PTR,   WIPE_FIELD_5RD_PTR,    &
      & WIPE_FIELD_5RB_VIEW => WIPE_FIELD_5RD_VIEW,  WIPE_FIELD_5RD_VIEW,   &
      & HOST_FIELD_5RB => HOST_FIELD_5RD,  HOST_FIELD_5RD, HOST,      &
      & HOST_FIELD_5RB_PTR  => HOST_FIELD_5RD_PTR,   HOST_FIELD_5RD_PTR,    &
      & HOST_FIELD_5RB_VIEW => HOST_FIELD_5RD_VIEW,  HOST_FIELD_5RD_VIEW,   &
      & LEGACY_FIELD_5RB => LEGACY_FIELD_5RD,  LEGACY_FIELD_5RD, LEGACY,      &
      & COPY

USE FIELD_1RM_UTIL_MODULE
USE FIELD_2RM_UTIL_MODULE
USE FIELD_3RM_UTIL_MODULE
USE FIELD_4RM_UTIL_MODULE
USE FIELD_5RM_UTIL_MODULE
USE FIELD_1IM_UTIL_MODULE
USE FIELD_2IM_UTIL_MODULE
USE FIELD_3IM_UTIL_MODULE
USE FIELD_4IM_UTIL_MODULE
USE FIELD_5IM_UTIL_MODULE
USE FIELD_1LM_UTIL_MODULE
USE FIELD_2LM_UTIL_MODULE
USE FIELD_3LM_UTIL_MODULE
USE FIELD_4LM_UTIL_MODULE
USE FIELD_5LM_UTIL_MODULE

#endif

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

END MODULE
