
MODULE FIELD_2IM_ACCESS_MODULE


USE FIELD_2IM_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


INTERFACE SGET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDONLY_FIELD_2IM
END INTERFACE SGET_DEVICE_DATA_RDONLY

PUBLIC :: SGET_DEVICE_DATA_RDONLY

INTERFACE GET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDONLY_FIELD_2IM
END INTERFACE GET_DEVICE_DATA_RDONLY

PUBLIC :: GET_DEVICE_DATA_RDONLY


INTERFACE SGET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: SGET_HOST_DATA_RDONLY_FIELD_2IM
END INTERFACE SGET_HOST_DATA_RDONLY

PUBLIC :: SGET_HOST_DATA_RDONLY

INTERFACE GET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: GET_HOST_DATA_RDONLY_FIELD_2IM
END INTERFACE GET_HOST_DATA_RDONLY

PUBLIC :: GET_HOST_DATA_RDONLY


INTERFACE SGET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDWR_FIELD_2IM
END INTERFACE SGET_DEVICE_DATA_RDWR

PUBLIC :: SGET_DEVICE_DATA_RDWR

INTERFACE GET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDWR_FIELD_2IM
END INTERFACE GET_DEVICE_DATA_RDWR

PUBLIC :: GET_DEVICE_DATA_RDWR


INTERFACE SGET_HOST_DATA_RDWR
  MODULE PROCEDURE :: SGET_HOST_DATA_RDWR_FIELD_2IM
END INTERFACE SGET_HOST_DATA_RDWR

PUBLIC :: SGET_HOST_DATA_RDWR

INTERFACE GET_HOST_DATA_RDWR
  MODULE PROCEDURE :: GET_HOST_DATA_RDWR_FIELD_2IM
END INTERFACE GET_HOST_DATA_RDWR

PUBLIC :: GET_HOST_DATA_RDWR


INTEGER(KIND=JPIM), TARGET, SAVE :: DUMMY_FIELD_2IM (1, 1)
!$acc declare create (DUMMY_FIELD_2IM)


CONTAINS


  SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_2IM (PTR, FIELD_PTR) 

    CLASS (FIELD_2IM), POINTER, OPTIONAL :: FIELD_PTR
    INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

  END SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_2IM

  FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_2IM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_2IM), POINTER :: FIELD_PTR
    INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

  END FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_2IM



  SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_2IM (PTR, FIELD_PTR) 

    CLASS (FIELD_2IM), POINTER, OPTIONAL :: FIELD_PTR
    INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

  END SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_2IM

  FUNCTION GET_HOST_DATA_RDONLY_FIELD_2IM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_2IM), POINTER :: FIELD_PTR
    INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

  END FUNCTION GET_HOST_DATA_RDONLY_FIELD_2IM



  SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_2IM (PTR, FIELD_PTR) 

    CLASS (FIELD_2IM), POINTER, OPTIONAL :: FIELD_PTR
    INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

  END SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_2IM

  FUNCTION GET_DEVICE_DATA_RDWR_FIELD_2IM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_2IM), POINTER :: FIELD_PTR
    INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

  END FUNCTION GET_DEVICE_DATA_RDWR_FIELD_2IM



  SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_2IM (PTR, FIELD_PTR) 

    CLASS (FIELD_2IM), POINTER, OPTIONAL :: FIELD_PTR
    INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

  END SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_2IM

  FUNCTION GET_HOST_DATA_RDWR_FIELD_2IM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_2IM), POINTER :: FIELD_PTR
    INTEGER(KIND=JPIM), POINTER :: PTR(:,:)

  END FUNCTION GET_HOST_DATA_RDWR_FIELD_2IM



END MODULE FIELD_2IM_ACCESS_MODULE
