
MODULE FIELD_3RM_UTIL_MODULE


USE FIELD_3RM_MODULE
USE FIELD_3RM_ACCESS_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE


INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_3RM
  MODULE PROCEDURE LOAD_FIELD_3RM_PTR
  MODULE PROCEDURE LOAD_FIELD_3RM_VIEW
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_3RM
  MODULE PROCEDURE SAVE_FIELD_3RM_PTR
  MODULE PROCEDURE SAVE_FIELD_3RM_VIEW
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_3RM
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_3RM
  MODULE PROCEDURE COPY_FIELD_3RM_PTR
  MODULE PROCEDURE COPY_FIELD_3RM_VIEW
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_3RM
  MODULE PROCEDURE WIPE_FIELD_3RM_PTR
  MODULE PROCEDURE WIPE_FIELD_3RM_VIEW
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_3RM
  MODULE PROCEDURE HOST_FIELD_3RM_PTR
  MODULE PROCEDURE HOST_FIELD_3RM_VIEW
END INTERFACE

INTERFACE LEGACY
  MODULE PROCEDURE LEGACY_FIELD_3RM
END INTERFACE


CONTAINS


SUBROUTINE LOAD_FIELD_3RM (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3RM), POINTER :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_3RM (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3RM), POINTER :: YD

END SUBROUTINE

SUBROUTINE DIFF_FIELD_3RM (CDMESS, YD, YO)

CHARACTER (LEN=*), INTENT(IN) :: CDMESS
CLASS (FIELD_3RM), POINTER :: YD, YO

END SUBROUTINE

SUBROUTINE COPY_FIELD_3RM (SELF, LDCREATED)

CLASS (FIELD_3RM), POINTER :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_3RM (SELF, LDDELETED)

CLASS (FIELD_3RM) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_3RM (SELF)
CLASS (FIELD_3RM), POINTER :: SELF

END SUBROUTINE 

SUBROUTINE LEGACY_FIELD_3RM (SELF, KADDRL, KADDRU, KDIR)

USE FIELD_3RM_ACCESS_MODULE

CLASS (FIELD_3RM), POINTER :: SELF
INTEGER*8, INTENT (IN) :: KADDRL
INTEGER*8, INTENT (IN) :: KADDRU
INTEGER,   INTENT (IN) :: KDIR

REAL(KIND=JPRM), POINTER :: PTR (:,:,:), DEVPTR (:,:,:)
INTEGER*8 :: IADDRL
INTEGER*8 :: IADDRU
INTEGER (KIND=JPIM) :: ILBOUNDS (3)
INTEGER (KIND=JPIM) :: IUBOUNDS (3)

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_3RM_VIEW (KLUN, YD)
USE PARKIND1, ONLY : JPIM
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3RM_VIEW) :: YD
! Do nothing
END SUBROUTINE

SUBROUTINE SAVE_FIELD_3RM_VIEW (KLUN, YD)
USE PARKIND1, ONLY : JPIM
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3RM_VIEW) :: YD
! Do nothing
END SUBROUTINE

SUBROUTINE COPY_FIELD_3RM_VIEW (SELF, LDCREATED)
CLASS (FIELD_3RM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED
! Do nothing
END SUBROUTINE 

SUBROUTINE WIPE_FIELD_3RM_VIEW (SELF, LDDELETED)
CLASS (FIELD_3RM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED
! Do nothing
END SUBROUTINE 

SUBROUTINE HOST_FIELD_3RM_VIEW (SELF)
CLASS (FIELD_3RM_VIEW) :: SELF
! Do nothing
END SUBROUTINE 


SUBROUTINE LOAD_FIELD_3RM_PTR (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3RM_PTR) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_3RM_PTR (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3RM_PTR) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_3RM_PTR (SELF, LDCREATED)

CLASS (FIELD_3RM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_3RM_PTR (SELF, LDDELETED)

CLASS (FIELD_3RM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_3RM_PTR (SELF)
CLASS (FIELD_3RM_PTR) :: SELF

END SUBROUTINE 


END MODULE
