
MODULE FIELD_2LM_DATA_MODULE


USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


PUBLIC :: FIELD_2LM_COPY
PUBLIC :: FIELD_2LM_COPY_FUNC
PUBLIC :: FIELD_2LM_COPY_INTF

ABSTRACT INTERFACE
  SUBROUTINE FIELD_2LM_COPY_INTF (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
    IMPORT :: JPIM, JPLM
    LOGICAL(KIND=JPLM), POINTER :: HST (:,:), DEV (:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
  END SUBROUTINE
END INTERFACE

CONTAINS


  FUNCTION FIELD_2LM_COPY_FUNC (HST, DEV) RESULT (FUNC)

    PROCEDURE (FIELD_2LM_COPY_INTF), POINTER :: FUNC 

    LOGICAL(KIND=JPLM), POINTER, OPTIONAL :: HST (:,:), DEV (:,:)

  END FUNCTION

  SUBROUTINE FIELD_2LM_COPY (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)

    LOGICAL(KIND=JPLM), POINTER :: HST (:,:), DEV (:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE

    PROCEDURE (FIELD_2LM_COPY_INTF), POINTER :: FUNC 

  END SUBROUTINE

  SUBROUTINE FIELD_2LM_COPY_DIM0_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
  USE OPENACC
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    LOGICAL(KIND=JPLM), POINTER :: HST (:,:), DEV (:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J, J1, J2
#ifdef _OPENACC
    TYPE(C_DEVPTR) :: DEVPTR
#endif

    END SUBROUTINE

  SUBROUTINE FIELD_2LM_COPY_DIM1_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
  USE OPENACC
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    LOGICAL(KIND=JPLM), POINTER :: HST (:,:), DEV (:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J, J2
#ifdef _OPENACC
    TYPE(C_DEVPTR) :: DEVPTR
#endif

    END SUBROUTINE

  SUBROUTINE FIELD_2LM_COPY_DIM2_CONTIGUOUS (HST, DEV, MAP_DEVPTR, KDIR, QUEUE)
#ifdef _OPENACC
  USE OPENACC
#endif
  USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : INT64
    LOGICAL(KIND=JPLM), POINTER :: HST (:,:), DEV (:,:)
    LOGICAL,                       INTENT (IN) :: MAP_DEVPTR
    INTEGER (KIND=JPIM),           INTENT (IN) :: KDIR
    INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: QUEUE
    INTEGER (KIND=INT64)                       :: ISIZE
    INTEGER :: J
#ifdef _OPENACC
    TYPE(C_DEVPTR) :: DEVPTR
#endif

    END SUBROUTINE




  INTEGER (KIND=JPIM) FUNCTION FIELD_2LM_GET_LAST_CONTIGUOUS_DIMENSION (PTR, AFTER) RESULT (JDIM)
  LOGICAL(KIND=JPLM), POINTER :: PTR (:,:)
  INTEGER (KIND=JPIM) :: AFTER
  INTEGER*8 :: IPREVIOUS_STRIDE, ITHIS_STRIDE, ISIZE
  INTEGER (KIND=JPIM) :: J, LB(2)

  END FUNCTION FIELD_2LM_GET_LAST_CONTIGUOUS_DIMENSION


END MODULE FIELD_2LM_DATA_MODULE
