
MODULE FIELD_2LM_UTIL_MODULE


USE FIELD_2LM_MODULE
USE FIELD_2LM_ACCESS_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE


INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_2LM
  MODULE PROCEDURE LOAD_FIELD_2LM_PTR
  MODULE PROCEDURE LOAD_FIELD_2LM_VIEW
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_2LM
  MODULE PROCEDURE SAVE_FIELD_2LM_PTR
  MODULE PROCEDURE SAVE_FIELD_2LM_VIEW
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_2LM
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_2LM
  MODULE PROCEDURE COPY_FIELD_2LM_PTR
  MODULE PROCEDURE COPY_FIELD_2LM_VIEW
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_2LM
  MODULE PROCEDURE WIPE_FIELD_2LM_PTR
  MODULE PROCEDURE WIPE_FIELD_2LM_VIEW
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_2LM
  MODULE PROCEDURE HOST_FIELD_2LM_PTR
  MODULE PROCEDURE HOST_FIELD_2LM_VIEW
END INTERFACE

INTERFACE LEGACY
  MODULE PROCEDURE LEGACY_FIELD_2LM
END INTERFACE


CONTAINS


SUBROUTINE LOAD_FIELD_2LM (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2LM), POINTER :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_2LM (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2LM), POINTER :: YD

END SUBROUTINE

SUBROUTINE DIFF_FIELD_2LM (CDMESS, YD, YO)

CHARACTER (LEN=*), INTENT(IN) :: CDMESS
CLASS (FIELD_2LM), POINTER :: YD, YO

END SUBROUTINE

SUBROUTINE COPY_FIELD_2LM (SELF, LDCREATED)

CLASS (FIELD_2LM), POINTER :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_2LM (SELF, LDDELETED)

CLASS (FIELD_2LM) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_2LM (SELF)
CLASS (FIELD_2LM), POINTER :: SELF

END SUBROUTINE 

SUBROUTINE LEGACY_FIELD_2LM (SELF, KADDRL, KADDRU, KDIR)

USE FIELD_2LM_ACCESS_MODULE

CLASS (FIELD_2LM), POINTER :: SELF
INTEGER*8, INTENT (IN) :: KADDRL
INTEGER*8, INTENT (IN) :: KADDRU
INTEGER,   INTENT (IN) :: KDIR

LOGICAL(KIND=JPLM), POINTER :: PTR (:,:), DEVPTR (:,:)
INTEGER*8 :: IADDRL
INTEGER*8 :: IADDRU
INTEGER (KIND=JPIM) :: ILBOUNDS (2)
INTEGER (KIND=JPIM) :: IUBOUNDS (2)

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_2LM_VIEW (KLUN, YD)
USE PARKIND1, ONLY : JPIM
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2LM_VIEW) :: YD
! Do nothing
END SUBROUTINE

SUBROUTINE SAVE_FIELD_2LM_VIEW (KLUN, YD)
USE PARKIND1, ONLY : JPIM
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2LM_VIEW) :: YD
! Do nothing
END SUBROUTINE

SUBROUTINE COPY_FIELD_2LM_VIEW (SELF, LDCREATED)
CLASS (FIELD_2LM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED
! Do nothing
END SUBROUTINE 

SUBROUTINE WIPE_FIELD_2LM_VIEW (SELF, LDDELETED)
CLASS (FIELD_2LM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED
! Do nothing
END SUBROUTINE 

SUBROUTINE HOST_FIELD_2LM_VIEW (SELF)
CLASS (FIELD_2LM_VIEW) :: SELF
! Do nothing
END SUBROUTINE 


SUBROUTINE LOAD_FIELD_2LM_PTR (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2LM_PTR) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_2LM_PTR (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_2LM_PTR) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_2LM_PTR (SELF, LDCREATED)

CLASS (FIELD_2LM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_2LM_PTR (SELF, LDDELETED)

CLASS (FIELD_2LM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_2LM_PTR (SELF)
CLASS (FIELD_2LM_PTR) :: SELF

END SUBROUTINE 


END MODULE
