
MODULE FIELD_5RD_ACCESS_MODULE


USE FIELD_5RD_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


INTERFACE SGET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDONLY_FIELD_5RD
END INTERFACE SGET_DEVICE_DATA_RDONLY

PUBLIC :: SGET_DEVICE_DATA_RDONLY

INTERFACE GET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDONLY_FIELD_5RD
END INTERFACE GET_DEVICE_DATA_RDONLY

PUBLIC :: GET_DEVICE_DATA_RDONLY


INTERFACE SGET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: SGET_HOST_DATA_RDONLY_FIELD_5RD
END INTERFACE SGET_HOST_DATA_RDONLY

PUBLIC :: SGET_HOST_DATA_RDONLY

INTERFACE GET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: GET_HOST_DATA_RDONLY_FIELD_5RD
END INTERFACE GET_HOST_DATA_RDONLY

PUBLIC :: GET_HOST_DATA_RDONLY


INTERFACE SGET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDWR_FIELD_5RD
END INTERFACE SGET_DEVICE_DATA_RDWR

PUBLIC :: SGET_DEVICE_DATA_RDWR

INTERFACE GET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDWR_FIELD_5RD
END INTERFACE GET_DEVICE_DATA_RDWR

PUBLIC :: GET_DEVICE_DATA_RDWR


INTERFACE SGET_HOST_DATA_RDWR
  MODULE PROCEDURE :: SGET_HOST_DATA_RDWR_FIELD_5RD
END INTERFACE SGET_HOST_DATA_RDWR

PUBLIC :: SGET_HOST_DATA_RDWR

INTERFACE GET_HOST_DATA_RDWR
  MODULE PROCEDURE :: GET_HOST_DATA_RDWR_FIELD_5RD
END INTERFACE GET_HOST_DATA_RDWR

PUBLIC :: GET_HOST_DATA_RDWR


REAL(KIND=JPRD), TARGET, SAVE :: DUMMY_FIELD_5RD (1, 1, 1, 1, 1)
!$acc declare create (DUMMY_FIELD_5RD)


CONTAINS


  SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_5RD (PTR, FIELD_PTR) 

    CLASS (FIELD_5RD), POINTER, OPTIONAL :: FIELD_PTR
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)

  END SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_5RD

  FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_5RD (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_5RD), POINTER :: FIELD_PTR
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)

  END FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_5RD



  SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_5RD (PTR, FIELD_PTR) 

    CLASS (FIELD_5RD), POINTER, OPTIONAL :: FIELD_PTR
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)

  END SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_5RD

  FUNCTION GET_HOST_DATA_RDONLY_FIELD_5RD (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_5RD), POINTER :: FIELD_PTR
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)

  END FUNCTION GET_HOST_DATA_RDONLY_FIELD_5RD



  SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_5RD (PTR, FIELD_PTR) 

    CLASS (FIELD_5RD), POINTER, OPTIONAL :: FIELD_PTR
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)

  END SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_5RD

  FUNCTION GET_DEVICE_DATA_RDWR_FIELD_5RD (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_5RD), POINTER :: FIELD_PTR
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)

  END FUNCTION GET_DEVICE_DATA_RDWR_FIELD_5RD



  SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_5RD (PTR, FIELD_PTR) 

    CLASS (FIELD_5RD), POINTER, OPTIONAL :: FIELD_PTR
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)

  END SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_5RD

  FUNCTION GET_HOST_DATA_RDWR_FIELD_5RD (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_5RD), POINTER :: FIELD_PTR
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:,:)

  END FUNCTION GET_HOST_DATA_RDWR_FIELD_5RD



END MODULE FIELD_5RD_ACCESS_MODULE
