
MODULE FIELD_ACCESS_MODULE


USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

USE FIELD_1RM_ACCESS_MODULE
USE FIELD_2RM_ACCESS_MODULE
USE FIELD_3RM_ACCESS_MODULE
USE FIELD_4RM_ACCESS_MODULE
USE FIELD_5RM_ACCESS_MODULE
USE FIELD_1RD_ACCESS_MODULE
USE FIELD_2RD_ACCESS_MODULE
USE FIELD_3RD_ACCESS_MODULE
USE FIELD_4RD_ACCESS_MODULE
USE FIELD_5RD_ACCESS_MODULE
USE FIELD_1IM_ACCESS_MODULE
USE FIELD_2IM_ACCESS_MODULE
USE FIELD_3IM_ACCESS_MODULE
USE FIELD_4IM_ACCESS_MODULE
USE FIELD_5IM_ACCESS_MODULE
USE FIELD_1LM_ACCESS_MODULE
USE FIELD_2LM_ACCESS_MODULE
USE FIELD_3LM_ACCESS_MODULE
USE FIELD_4LM_ACCESS_MODULE
USE FIELD_5LM_ACCESS_MODULE

IMPLICIT NONE

END MODULE FIELD_ACCESS_MODULE



