MODULE FIELD_ARRAY_UTIL_MODULE



#ifdef PARKIND1_SINGLE

USE FIELD_2RM_ARRAY_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_2RB_ARRAY => LOAD_FIELD_2RM_ARRAY,  LOAD_FIELD_2RM_ARRAY, LOAD, &
      & SAVE_FIELD_2RB_ARRAY => SAVE_FIELD_2RM_ARRAY,  SAVE_FIELD_2RM_ARRAY, SAVE, &
      & COPY_FIELD_2RB_ARRAY => COPY_FIELD_2RM_ARRAY,  COPY_FIELD_2RM_ARRAY, COPY, &
      & WIPE_FIELD_2RB_ARRAY => WIPE_FIELD_2RM_ARRAY,  WIPE_FIELD_2RM_ARRAY, WIPE, &
      & HOST_FIELD_2RB_ARRAY => HOST_FIELD_2RM_ARRAY,  HOST_FIELD_2RM_ARRAY, HOST, &
      & COPY
USE FIELD_3RM_ARRAY_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_3RB_ARRAY => LOAD_FIELD_3RM_ARRAY,  LOAD_FIELD_3RM_ARRAY, LOAD, &
      & SAVE_FIELD_3RB_ARRAY => SAVE_FIELD_3RM_ARRAY,  SAVE_FIELD_3RM_ARRAY, SAVE, &
      & COPY_FIELD_3RB_ARRAY => COPY_FIELD_3RM_ARRAY,  COPY_FIELD_3RM_ARRAY, COPY, &
      & WIPE_FIELD_3RB_ARRAY => WIPE_FIELD_3RM_ARRAY,  WIPE_FIELD_3RM_ARRAY, WIPE, &
      & HOST_FIELD_3RB_ARRAY => HOST_FIELD_3RM_ARRAY,  HOST_FIELD_3RM_ARRAY, HOST, &
      & COPY
USE FIELD_4RM_ARRAY_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_4RB_ARRAY => LOAD_FIELD_4RM_ARRAY,  LOAD_FIELD_4RM_ARRAY, LOAD, &
      & SAVE_FIELD_4RB_ARRAY => SAVE_FIELD_4RM_ARRAY,  SAVE_FIELD_4RM_ARRAY, SAVE, &
      & COPY_FIELD_4RB_ARRAY => COPY_FIELD_4RM_ARRAY,  COPY_FIELD_4RM_ARRAY, COPY, &
      & WIPE_FIELD_4RB_ARRAY => WIPE_FIELD_4RM_ARRAY,  WIPE_FIELD_4RM_ARRAY, WIPE, &
      & HOST_FIELD_4RB_ARRAY => HOST_FIELD_4RM_ARRAY,  HOST_FIELD_4RM_ARRAY, HOST, &
      & COPY
USE FIELD_5RM_ARRAY_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_5RB_ARRAY => LOAD_FIELD_5RM_ARRAY,  LOAD_FIELD_5RM_ARRAY, LOAD, &
      & SAVE_FIELD_5RB_ARRAY => SAVE_FIELD_5RM_ARRAY,  SAVE_FIELD_5RM_ARRAY, SAVE, &
      & COPY_FIELD_5RB_ARRAY => COPY_FIELD_5RM_ARRAY,  COPY_FIELD_5RM_ARRAY, COPY, &
      & WIPE_FIELD_5RB_ARRAY => WIPE_FIELD_5RM_ARRAY,  WIPE_FIELD_5RM_ARRAY, WIPE, &
      & HOST_FIELD_5RB_ARRAY => HOST_FIELD_5RM_ARRAY,  HOST_FIELD_5RM_ARRAY, HOST, &
      & COPY

USE FIELD_2RD_ARRAY_UTIL_MODULE
USE FIELD_3RD_ARRAY_UTIL_MODULE
USE FIELD_4RD_ARRAY_UTIL_MODULE
USE FIELD_5RD_ARRAY_UTIL_MODULE
USE FIELD_2IM_ARRAY_UTIL_MODULE
USE FIELD_3IM_ARRAY_UTIL_MODULE
USE FIELD_4IM_ARRAY_UTIL_MODULE
USE FIELD_5IM_ARRAY_UTIL_MODULE
USE FIELD_2LM_ARRAY_UTIL_MODULE
USE FIELD_3LM_ARRAY_UTIL_MODULE
USE FIELD_4LM_ARRAY_UTIL_MODULE
USE FIELD_5LM_ARRAY_UTIL_MODULE

#else

USE FIELD_2RD_ARRAY_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_2RB_ARRAY => LOAD_FIELD_2RD_ARRAY,  LOAD_FIELD_2RD_ARRAY, LOAD, &
      & SAVE_FIELD_2RB_ARRAY => SAVE_FIELD_2RD_ARRAY,  SAVE_FIELD_2RD_ARRAY, SAVE, &
      & COPY_FIELD_2RB_ARRAY => COPY_FIELD_2RD_ARRAY,  COPY_FIELD_2RD_ARRAY, COPY, &
      & WIPE_FIELD_2RB_ARRAY => WIPE_FIELD_2RD_ARRAY,  WIPE_FIELD_2RD_ARRAY, WIPE, &
      & HOST_FIELD_2RB_ARRAY => HOST_FIELD_2RD_ARRAY,  HOST_FIELD_2RD_ARRAY, HOST, &
      & COPY
USE FIELD_3RD_ARRAY_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_3RB_ARRAY => LOAD_FIELD_3RD_ARRAY,  LOAD_FIELD_3RD_ARRAY, LOAD, &
      & SAVE_FIELD_3RB_ARRAY => SAVE_FIELD_3RD_ARRAY,  SAVE_FIELD_3RD_ARRAY, SAVE, &
      & COPY_FIELD_3RB_ARRAY => COPY_FIELD_3RD_ARRAY,  COPY_FIELD_3RD_ARRAY, COPY, &
      & WIPE_FIELD_3RB_ARRAY => WIPE_FIELD_3RD_ARRAY,  WIPE_FIELD_3RD_ARRAY, WIPE, &
      & HOST_FIELD_3RB_ARRAY => HOST_FIELD_3RD_ARRAY,  HOST_FIELD_3RD_ARRAY, HOST, &
      & COPY
USE FIELD_4RD_ARRAY_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_4RB_ARRAY => LOAD_FIELD_4RD_ARRAY,  LOAD_FIELD_4RD_ARRAY, LOAD, &
      & SAVE_FIELD_4RB_ARRAY => SAVE_FIELD_4RD_ARRAY,  SAVE_FIELD_4RD_ARRAY, SAVE, &
      & COPY_FIELD_4RB_ARRAY => COPY_FIELD_4RD_ARRAY,  COPY_FIELD_4RD_ARRAY, COPY, &
      & WIPE_FIELD_4RB_ARRAY => WIPE_FIELD_4RD_ARRAY,  WIPE_FIELD_4RD_ARRAY, WIPE, &
      & HOST_FIELD_4RB_ARRAY => HOST_FIELD_4RD_ARRAY,  HOST_FIELD_4RD_ARRAY, HOST, &
      & COPY
USE FIELD_5RD_ARRAY_UTIL_MODULE, ONLY : &
      & LOAD_FIELD_5RB_ARRAY => LOAD_FIELD_5RD_ARRAY,  LOAD_FIELD_5RD_ARRAY, LOAD, &
      & SAVE_FIELD_5RB_ARRAY => SAVE_FIELD_5RD_ARRAY,  SAVE_FIELD_5RD_ARRAY, SAVE, &
      & COPY_FIELD_5RB_ARRAY => COPY_FIELD_5RD_ARRAY,  COPY_FIELD_5RD_ARRAY, COPY, &
      & WIPE_FIELD_5RB_ARRAY => WIPE_FIELD_5RD_ARRAY,  WIPE_FIELD_5RD_ARRAY, WIPE, &
      & HOST_FIELD_5RB_ARRAY => HOST_FIELD_5RD_ARRAY,  HOST_FIELD_5RD_ARRAY, HOST, &
      & COPY

USE FIELD_2RM_ARRAY_UTIL_MODULE
USE FIELD_3RM_ARRAY_UTIL_MODULE
USE FIELD_4RM_ARRAY_UTIL_MODULE
USE FIELD_5RM_ARRAY_UTIL_MODULE
USE FIELD_2IM_ARRAY_UTIL_MODULE
USE FIELD_3IM_ARRAY_UTIL_MODULE
USE FIELD_4IM_ARRAY_UTIL_MODULE
USE FIELD_5IM_ARRAY_UTIL_MODULE
USE FIELD_2LM_ARRAY_UTIL_MODULE
USE FIELD_3LM_ARRAY_UTIL_MODULE
USE FIELD_4LM_ARRAY_UTIL_MODULE
USE FIELD_5LM_ARRAY_UTIL_MODULE

#endif

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

END MODULE
