
MODULE FIELD_3IM_UTIL_MODULE


USE FIELD_3IM_MODULE
USE FIELD_3IM_ACCESS_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE


INTERFACE LOAD
  MODULE PROCEDURE LOAD_FIELD_3IM
  MODULE PROCEDURE LOAD_FIELD_3IM_PTR
  MODULE PROCEDURE LOAD_FIELD_3IM_VIEW
END INTERFACE

INTERFACE SAVE
  MODULE PROCEDURE SAVE_FIELD_3IM
  MODULE PROCEDURE SAVE_FIELD_3IM_PTR
  MODULE PROCEDURE SAVE_FIELD_3IM_VIEW
END INTERFACE

INTERFACE DIFF
  MODULE PROCEDURE DIFF_FIELD_3IM
END INTERFACE

INTERFACE COPY
  MODULE PROCEDURE COPY_FIELD_3IM
  MODULE PROCEDURE COPY_FIELD_3IM_PTR
  MODULE PROCEDURE COPY_FIELD_3IM_VIEW
END INTERFACE

INTERFACE WIPE
  MODULE PROCEDURE WIPE_FIELD_3IM
  MODULE PROCEDURE WIPE_FIELD_3IM_PTR
  MODULE PROCEDURE WIPE_FIELD_3IM_VIEW
END INTERFACE

INTERFACE HOST
  MODULE PROCEDURE HOST_FIELD_3IM
  MODULE PROCEDURE HOST_FIELD_3IM_PTR
  MODULE PROCEDURE HOST_FIELD_3IM_VIEW
END INTERFACE

INTERFACE LEGACY
  MODULE PROCEDURE LEGACY_FIELD_3IM
END INTERFACE


CONTAINS


SUBROUTINE LOAD_FIELD_3IM (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3IM), POINTER :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_3IM (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3IM), POINTER :: YD

END SUBROUTINE

SUBROUTINE DIFF_FIELD_3IM (CDMESS, YD, YO)

CHARACTER (LEN=*), INTENT(IN) :: CDMESS
CLASS (FIELD_3IM), POINTER :: YD, YO

END SUBROUTINE

SUBROUTINE COPY_FIELD_3IM (SELF, LDCREATED)

CLASS (FIELD_3IM), POINTER :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_3IM (SELF, LDDELETED)

CLASS (FIELD_3IM) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_3IM (SELF)
CLASS (FIELD_3IM), POINTER :: SELF

END SUBROUTINE 

SUBROUTINE LEGACY_FIELD_3IM (SELF, KADDRL, KADDRU, KDIR)

USE FIELD_3IM_ACCESS_MODULE

CLASS (FIELD_3IM), POINTER :: SELF
INTEGER*8, INTENT (IN) :: KADDRL
INTEGER*8, INTENT (IN) :: KADDRU
INTEGER,   INTENT (IN) :: KDIR

INTEGER(KIND=JPIM), POINTER :: PTR (:,:,:), DEVPTR (:,:,:)
INTEGER*8 :: IADDRL
INTEGER*8 :: IADDRU
INTEGER (KIND=JPIM) :: ILBOUNDS (3)
INTEGER (KIND=JPIM) :: IUBOUNDS (3)

END SUBROUTINE 


SUBROUTINE LOAD_FIELD_3IM_VIEW (KLUN, YD)
USE PARKIND1, ONLY : JPIM
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3IM_VIEW) :: YD
! Do nothing
END SUBROUTINE

SUBROUTINE SAVE_FIELD_3IM_VIEW (KLUN, YD)
USE PARKIND1, ONLY : JPIM
INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3IM_VIEW) :: YD
! Do nothing
END SUBROUTINE

SUBROUTINE COPY_FIELD_3IM_VIEW (SELF, LDCREATED)
CLASS (FIELD_3IM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED
! Do nothing
END SUBROUTINE 

SUBROUTINE WIPE_FIELD_3IM_VIEW (SELF, LDDELETED)
CLASS (FIELD_3IM_VIEW) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED
! Do nothing
END SUBROUTINE 

SUBROUTINE HOST_FIELD_3IM_VIEW (SELF)
CLASS (FIELD_3IM_VIEW) :: SELF
! Do nothing
END SUBROUTINE 


SUBROUTINE LOAD_FIELD_3IM_PTR (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3IM_PTR) :: YD

END SUBROUTINE

SUBROUTINE SAVE_FIELD_3IM_PTR (KLUN, YD)

USE PARKIND1, ONLY : JPIM

INTEGER (KIND=JPIM), INTENT (IN) :: KLUN
CLASS (FIELD_3IM_PTR) :: YD

END SUBROUTINE

SUBROUTINE COPY_FIELD_3IM_PTR (SELF, LDCREATED)

CLASS (FIELD_3IM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED

END SUBROUTINE 

SUBROUTINE WIPE_FIELD_3IM_PTR (SELF, LDDELETED)

CLASS (FIELD_3IM_PTR) :: SELF
LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED

END SUBROUTINE 

SUBROUTINE HOST_FIELD_3IM_PTR (SELF)
CLASS (FIELD_3IM_PTR) :: SELF

END SUBROUTINE 


END MODULE
