
MODULE FIELD_1LM_ACCESS_MODULE


USE FIELD_1LM_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE


INTERFACE SGET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDONLY_FIELD_1LM
END INTERFACE SGET_DEVICE_DATA_RDONLY

PUBLIC :: SGET_DEVICE_DATA_RDONLY

INTERFACE GET_DEVICE_DATA_RDONLY
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDONLY_FIELD_1LM
END INTERFACE GET_DEVICE_DATA_RDONLY

PUBLIC :: GET_DEVICE_DATA_RDONLY


INTERFACE SGET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: SGET_HOST_DATA_RDONLY_FIELD_1LM
END INTERFACE SGET_HOST_DATA_RDONLY

PUBLIC :: SGET_HOST_DATA_RDONLY

INTERFACE GET_HOST_DATA_RDONLY
  MODULE PROCEDURE :: GET_HOST_DATA_RDONLY_FIELD_1LM
END INTERFACE GET_HOST_DATA_RDONLY

PUBLIC :: GET_HOST_DATA_RDONLY


INTERFACE SGET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: SGET_DEVICE_DATA_RDWR_FIELD_1LM
END INTERFACE SGET_DEVICE_DATA_RDWR

PUBLIC :: SGET_DEVICE_DATA_RDWR

INTERFACE GET_DEVICE_DATA_RDWR
  MODULE PROCEDURE :: GET_DEVICE_DATA_RDWR_FIELD_1LM
END INTERFACE GET_DEVICE_DATA_RDWR

PUBLIC :: GET_DEVICE_DATA_RDWR


INTERFACE SGET_HOST_DATA_RDWR
  MODULE PROCEDURE :: SGET_HOST_DATA_RDWR_FIELD_1LM
END INTERFACE SGET_HOST_DATA_RDWR

PUBLIC :: SGET_HOST_DATA_RDWR

INTERFACE GET_HOST_DATA_RDWR
  MODULE PROCEDURE :: GET_HOST_DATA_RDWR_FIELD_1LM
END INTERFACE GET_HOST_DATA_RDWR

PUBLIC :: GET_HOST_DATA_RDWR


LOGICAL(KIND=JPLM), TARGET, SAVE :: DUMMY_FIELD_1LM (1)
!$acc declare create (DUMMY_FIELD_1LM)


CONTAINS


  SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_1LM (PTR, FIELD_PTR) 

    CLASS (FIELD_1LM), POINTER, OPTIONAL :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

  END SUBROUTINE SGET_DEVICE_DATA_RDONLY_FIELD_1LM

  FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_1LM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_1LM), POINTER :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

  END FUNCTION GET_DEVICE_DATA_RDONLY_FIELD_1LM



  SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_1LM (PTR, FIELD_PTR) 

    CLASS (FIELD_1LM), POINTER, OPTIONAL :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

  END SUBROUTINE SGET_HOST_DATA_RDONLY_FIELD_1LM

  FUNCTION GET_HOST_DATA_RDONLY_FIELD_1LM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_1LM), POINTER :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

  END FUNCTION GET_HOST_DATA_RDONLY_FIELD_1LM



  SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_1LM (PTR, FIELD_PTR) 

    CLASS (FIELD_1LM), POINTER, OPTIONAL :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

  END SUBROUTINE SGET_DEVICE_DATA_RDWR_FIELD_1LM

  FUNCTION GET_DEVICE_DATA_RDWR_FIELD_1LM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_1LM), POINTER :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

  END FUNCTION GET_DEVICE_DATA_RDWR_FIELD_1LM



  SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_1LM (PTR, FIELD_PTR) 

    CLASS (FIELD_1LM), POINTER, OPTIONAL :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

  END SUBROUTINE SGET_HOST_DATA_RDWR_FIELD_1LM

  FUNCTION GET_HOST_DATA_RDWR_FIELD_1LM (FIELD_PTR) RESULT (PTR)
    CLASS (FIELD_1LM), POINTER :: FIELD_PTR
    LOGICAL(KIND=JPLM), POINTER :: PTR(:)

  END FUNCTION GET_HOST_DATA_RDWR_FIELD_1LM



END MODULE FIELD_1LM_ACCESS_MODULE
