
MODULE FIELD_1LM_MODULE


USE OML_MOD, ONLY: OML_MAX_THREADS , OML_MY_THREAD 
USE IEEE_ARITHMETIC, ONLY: IEEE_SIGNALING_NAN
USE FIELD_BASIC_MODULE
#ifdef _OPENACC
USE OPENACC
#endif
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

USE FIELD_1LM_DATA_MODULE, ONLY : FIELD_1LM_COPY_INTF

IMPLICIT NONE

PRIVATE

TYPE, ABSTRACT, EXTENDS (FIELD_BASIC) :: FIELD_1LM
  LOGICAL(KIND=JPLM), POINTER :: PTR(:) => NULL()
  LOGICAL(KIND=JPLM), POINTER, CONTIGUOUS :: DEVPTR(:) => NULL()
  PROCEDURE (FIELD_1LM_COPY_INTF), POINTER, NOPASS :: COPY_FUNC => NULL ()
CONTAINS

  PROCEDURE :: FINAL => FIELD_1LM_FINAL
  PROCEDURE :: FIELD_1LM_FINAL
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_1LM_DELETE_DEVICE_DATA
  PROCEDURE :: GET_DEVICE_DATA_RDONLY => FIELD_1LM_GET_DEVICE_DATA_RDONLY
  PROCEDURE :: GET_DEVICE_DATA_WRONLY => FIELD_1LM_GET_DEVICE_DATA_WRONLY
  PROCEDURE :: GET_DEVICE_DATA_RDWR => FIELD_1LM_GET_DEVICE_DATA_RDWR
  PROCEDURE :: GET_HOST_DATA_RDONLY => FIELD_1LM_GET_HOST_DATA_RDONLY
  PROCEDURE :: GET_HOST_DATA_RDWR => FIELD_1LM_GET_HOST_DATA_RDWR
  PROCEDURE :: SYNC_HOST_RDWR => FIELD_1LM_SYNC_HOST_RDWR
  PROCEDURE :: SYNC_HOST_RDONLY => FIELD_1LM_SYNC_HOST_RDONLY
  PROCEDURE :: SYNC_DEVICE_RDWR => FIELD_1LM_SYNC_DEVICE_RDWR
  PROCEDURE :: SYNC_DEVICE_RDONLY => FIELD_1LM_SYNC_DEVICE_RDONLY
  PROCEDURE :: COPY_OBJECT => FIELD_1LM_COPY_OBJECT
  PROCEDURE :: WIPE_OBJECT => FIELD_1LM_WIPE_OBJECT
  PROCEDURE(GET_DIMS), DEFERRED :: GET_DIMS
  PROCEDURE(RESIZE), DEFERRED :: RESIZE

  PROCEDURE :: GET_DEVICE_DATA => FIELD_1LM_GET_DEVICE_DATA
  PROCEDURE :: GET_HOST_DATA => FIELD_1LM_GET_HOST_DATA
  PROCEDURE, PRIVATE :: FIELD_1LM_GET_HOST_DATA
  PROCEDURE, PRIVATE :: FIELD_1LM_GET_DEVICE_DATA
  PROCEDURE, PRIVATE :: COPY_DATA =>  FIELD_1LM_COPY_DATA
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_1LM_CREATE_DEVICE_DATA
#ifdef __PGI
  PROCEDURE :: SET_STATUS => FIELD_1LM_SET_STATUS
#endif
END TYPE FIELD_1LM

ABSTRACT INTERFACE
  SUBROUTINE GET_DIMS(SELF, LBOUNDS, UBOUNDS)
    USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM
    IMPORT ::  FIELD_1LM
    CLASS(FIELD_1LM),               INTENT(IN) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: LBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: UBOUNDS(1)
  END SUBROUTINE GET_DIMS
  SUBROUTINE RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
    USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM
    IMPORT ::  FIELD_1LM
    CLASS(FIELD_1LM),               INTENT(IN) :: SELF
    INTEGER(KIND=JPIM),           INTENT(IN) :: UBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(1)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT
  END SUBROUTINE RESIZE
END INTERFACE

PUBLIC :: FIELD_1LM

TYPE, EXTENDS(FIELD_1LM) :: FIELD_1LM_WRAPPER
  LOGICAL :: SYNC_ON_FINAL = .TRUE.
CONTAINS
  PROCEDURE :: INIT => FIELD_1LM_WRAPPER_INIT
  PROCEDURE :: FINAL => FIELD_1LM_WRAPPER_FINAL
  PROCEDURE :: GET_DIMS => FIELD_1LM_WRAPPER_GET_DIMS
  PROCEDURE :: RESIZE => FIELD_1LM_WRAPPER_RESIZE
END TYPE FIELD_1LM_WRAPPER

PUBLIC :: FIELD_1LM_WRAPPER

TYPE, EXTENDS(FIELD_1LM) :: FIELD_1LM_OWNER
  INTEGER(KIND=JPIM) :: LBOUNDS(1), UBOUNDS(1)
  LOGICAL :: HAS_INIT_VALUE = .FALSE.
  LOGICAL :: PINNED = .FALSE.
  LOGICAL :: POOLED = .FALSE.
  LOGICAL(KIND=JPLM) :: INIT_VALUE
CONTAINS
  PROCEDURE :: INIT => FIELD_1LM_OWNER_INIT
  PROCEDURE :: FINAL => FIELD_1LM_OWNER_FINAL
  PROCEDURE, PRIVATE :: CREATE_HOST_DATA => FIELD_1LM_OWNER_CREATE_HOST_DATA
  PROCEDURE :: GET_HOST_DATA => FIELD_1LM_OWNER_GET_HOST_DATA
  PROCEDURE :: GET_DEVICE_DATA => FIELD_1LM_OWNER_GET_DEVICE_DATA
  PROCEDURE :: GET_DIMS => FIELD_1LM_OWNER_GET_DIMS
  PROCEDURE :: RESIZE => FIELD_1LM_OWNER_RESIZE
END TYPE FIELD_1LM_OWNER

PUBLIC :: FIELD_1LM_OWNER

TYPE FIELD_1LM_PTR
  CLASS(FIELD_1LM), POINTER :: PTR => NULL()
END TYPE FIELD_1LM_PTR

PUBLIC :: FIELD_1LM_PTR



CONTAINS

  SUBROUTINE FIELD_1LM_WRAPPER_INIT(SELF, DATA, PERSISTENT, LBOUNDS, MAP_DEVPTR, SYNC_ON_FINAL, INITIALIZED)
    USE FIELD_1LM_DATA_MODULE, ONLY : FIELD_1LM_COPY_FUNC

    ! Create FIELD object by wrapping existing data
    CLASS(FIELD_1LM_WRAPPER) :: SELF
    LOGICAL(KIND=JPLM), TARGET, INTENT(IN) :: DATA(:)
    LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
    LOGICAL, INTENT(IN), OPTIONAL :: MAP_DEVPTR
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(1)
    LOGICAL, INTENT(IN), OPTIONAL :: SYNC_ON_FINAL
    LOGICAL, INTENT(IN), OPTIONAL :: INITIALIZED
    
  END SUBROUTINE FIELD_1LM_WRAPPER_INIT

  SUBROUTINE FIELD_1LM_OWNER_INIT (SELF, LBOUNDS, UBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR, POOLED)
    USE FIELD_1LM_DATA_MODULE, ONLY : FIELD_1LM_COPY_FUNC

    CLASS(FIELD_1LM_OWNER) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(1)
    INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
    LOGICAL, OPTIONAL,  INTENT(IN) :: PERSISTENT
    LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
    LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
    LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
    LOGICAL, OPTIONAL,  INTENT(IN) :: POOLED
    LOGICAL(KIND=JPLM), OPTIONAL, INTENT(IN) :: INIT_VALUE
    LOGICAL :: IS_DELAYED
    LOGICAL :: LLPERSISTENT

  END SUBROUTINE FIELD_1LM_OWNER_INIT

  SUBROUTINE FIELD_1LM_OWNER_CREATE_HOST_DATA (SELF)
    ! Create FIELD object by explicitly allocating new data
    CLASS(FIELD_1LM_OWNER) :: SELF

  END SUBROUTINE FIELD_1LM_OWNER_CREATE_HOST_DATA


  SUBROUTINE FIELD_1LM_DELETE_DEVICE_DATA(SELF)
    ! Delete the copy of this field on GPU device
    CLASS(FIELD_1LM) :: SELF

  END SUBROUTINE FIELD_1LM_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_1LM_FINAL(SELF)
    ! Finalizes field and deallocates owned data
    CLASS(FIELD_1LM) :: SELF
  END SUBROUTINE FIELD_1LM_FINAL

  SUBROUTINE FIELD_1LM_WRAPPER_FINAL(SELF)
    ! Finalizes field and deallocates owned data
    CLASS(FIELD_1LM_WRAPPER) :: SELF
  END SUBROUTINE FIELD_1LM_WRAPPER_FINAL

  SUBROUTINE FIELD_1LM_OWNER_FINAL(SELF)
    ! Finalizes field and deallocates owned data
    CLASS(FIELD_1LM_OWNER) :: SELF

  END SUBROUTINE FIELD_1LM_OWNER_FINAL

  SUBROUTINE FIELD_1LM_COPY_OBJECT (SELF, LDCREATED)

  CLASS(FIELD_1LM) :: SELF
  LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED
  LOGICAL :: LLCREATED

  END SUBROUTINE FIELD_1LM_COPY_OBJECT

  SUBROUTINE FIELD_1LM_WIPE_OBJECT (SELF, LDDELETED)

  CLASS(FIELD_1LM) :: SELF
  LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED
  LOGICAL :: LLDELETED

  END SUBROUTINE FIELD_1LM_WIPE_OBJECT

  SUBROUTINE FIELD_1LM_COPY_DATA (SELF, KDIR, QUEUE)

  CLASS(FIELD_1LM) :: SELF
  INTEGER (KIND=JPIM),           INTENT(IN) :: KDIR
  INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN) :: QUEUE
  REAL :: START, FINISH

  END SUBROUTINE FIELD_1LM_COPY_DATA

  SUBROUTINE FIELD_1LM_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE

    LOGICAL(KIND=JPLM), POINTER,          INTENT(INOUT) :: PTR(:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1LM_GET_HOST_DATA

  SUBROUTINE FIELD_1LM_OWNER_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_1LM_OWNER) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    LOGICAL(KIND=JPLM), POINTER,          INTENT(INOUT) :: PTR(:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1LM_OWNER_GET_HOST_DATA

  SUBROUTINE FIELD_1LM_GET_HOST_DATA_RDONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    LOGICAL(KIND=JPLM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1LM_GET_HOST_DATA_RDONLY

  SUBROUTINE FIELD_1LM_SYNC_HOST_RDONLY (SELF, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    LOGICAL(KIND=JPLM), POINTER                        :: ZPTR(:)

  END SUBROUTINE FIELD_1LM_SYNC_HOST_RDONLY

  SUBROUTINE FIELD_1LM_GET_HOST_DATA_RDWR (SELF, PPTR, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    LOGICAL(KIND=JPLM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1LM_GET_HOST_DATA_RDWR

  SUBROUTINE FIELD_1LM_SYNC_HOST_RDWR (SELF, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    LOGICAL(KIND=JPLM), POINTER                        :: ZPTR(:)

  END SUBROUTINE FIELD_1LM_SYNC_HOST_RDWR

  SUBROUTINE FIELD_1LM_CREATE_DEVICE_DATA (SELF)
    CLASS(FIELD_1LM) :: SELF

  END SUBROUTINE

  SUBROUTINE FIELD_1LM_GET_DEVICE_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    LOGICAL(KIND=JPLM), POINTER,          INTENT(INOUT) :: PTR(:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    INTEGER(KIND=JPIM)                           :: LBOUNDS(1)

  END SUBROUTINE FIELD_1LM_GET_DEVICE_DATA


  SUBROUTINE FIELD_1LM_OWNER_GET_DEVICE_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_1LM_OWNER) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    LOGICAL(KIND=JPLM), POINTER,          INTENT(INOUT) :: PTR(:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1LM_OWNER_GET_DEVICE_DATA

  SUBROUTINE FIELD_1LM_GET_DEVICE_DATA_RDONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    LOGICAL(KIND=JPLM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1LM_GET_DEVICE_DATA_RDONLY

  SUBROUTINE FIELD_1LM_GET_DEVICE_DATA_WRONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    LOGICAL(KIND=JPLM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1LM_GET_DEVICE_DATA_WRONLY

  SUBROUTINE FIELD_1LM_SYNC_DEVICE_RDONLY (SELF, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    LOGICAL(KIND=JPLM), POINTER                        :: ZPTR(:)

  END SUBROUTINE FIELD_1LM_SYNC_DEVICE_RDONLY

  SUBROUTINE FIELD_1LM_GET_DEVICE_DATA_RDWR (SELF, PPTR, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    LOGICAL(KIND=JPLM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1LM_GET_DEVICE_DATA_RDWR

  SUBROUTINE FIELD_1LM_SYNC_DEVICE_RDWR (SELF, QUEUE)
    CLASS(FIELD_1LM) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    LOGICAL(KIND=JPLM), POINTER                        :: ZPTR(:)

  END SUBROUTINE FIELD_1LM_SYNC_DEVICE_RDWR

  SUBROUTINE FIELD_1LM_WRAPPER_GET_DIMS (SELF, LBOUNDS, UBOUNDS)
    CLASS(FIELD_1LM_WRAPPER),       INTENT(IN) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: LBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: UBOUNDS(1)
  END SUBROUTINE FIELD_1LM_WRAPPER_GET_DIMS

  SUBROUTINE FIELD_1LM_OWNER_GET_DIMS (SELF, LBOUNDS, UBOUNDS)
    CLASS(FIELD_1LM_OWNER),         INTENT(IN) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: LBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: UBOUNDS(1)
  END SUBROUTINE FIELD_1LM_OWNER_GET_DIMS

  SUBROUTINE FIELD_1LM_WRAPPER_RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)

    CLASS(FIELD_1LM_WRAPPER),       INTENT(IN) :: SELF
    INTEGER(KIND=JPIM),           INTENT(IN) :: UBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(1)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT
  END SUBROUTINE FIELD_1LM_WRAPPER_RESIZE

  SUBROUTINE FIELD_1LM_OWNER_RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
    CLASS(FIELD_1LM_OWNER),         INTENT(IN) :: SELF
    INTEGER(KIND=JPIM),           INTENT(IN) :: UBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(1)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT

  END SUBROUTINE FIELD_1LM_OWNER_RESIZE

#ifdef __PGI
  SUBROUTINE FIELD_1LM_SET_STATUS (SELF, KSTATUS)

  CLASS (FIELD_1LM) :: SELF
  INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS


  END SUBROUTINE FIELD_1LM_SET_STATUS
#endif


END MODULE FIELD_1LM_MODULE
