MODULE FXTRAN_ACDC_GPUMEM_MOD

!
! Copyright 2025 Meteo-France
! All rights reserved
! philippe.marguinaud@meteo.fr
!

IMPLICIT NONE

PRIVATE
PUBLIC :: FXTRAN_ACDC_GPUMEMSTAT, FXTRAN_ACDC_GPUMEMINCR, FXTRAN_ACDC_GPUMEMDECR

INTEGER*8 :: NMETADATA = 0

CONTAINS

SUBROUTINE FXTRAN_ACDC_GPUMEMSTAT (CDFILE, KLINE, CDMESS)

IMPLICIT NONE

CHARACTER (LEN=*) :: CDFILE
INTEGER           :: KLINE
CHARACTER (LEN=*) :: CDMESS

INTEGER*8 :: ISIZE_SMI
INTEGER*8 :: ISIZE_ACC
INTEGER*8 :: IALLOCATED, IDELETED

INTEGER :: MYPROC 

LOGICAL, SAVE :: LLFIRST = .TRUE.

INTEGER*8, PARAMETER :: MB = 1024 * 1024

INTEGER*8 :: ISIZE (8)
CHARACTER*20 :: CLABEL (8)
CHARACTER*32 :: CLENV
CHARACTER*50 :: CLLOCATION

INTEGER*8 ::  IFIELD_API_DEVICE_CUR, IFIELD_API_DEVICE_MAX

INTEGER :: I

CONTAINS

CHARACTER*20 FUNCTION MEMFMT (KSIZE)

INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE

ISIZE = KSIZE / MB

WRITE (MEMFMT, '(I20)') ISIZE

MEMFMT = ADJUSTR (MEMFMT)

END FUNCTION

END SUBROUTINE

SUBROUTINE FXTRAN_ACDC_GPUMEMINCR (KSIZE)

IMPLICIT NONE

INTEGER*8 :: KSIZE

INTEGER*8 :: NMETADATA

NMETADATA = NMETADATA + KSIZE

END SUBROUTINE

SUBROUTINE FXTRAN_ACDC_GPUMEMDECR (KSIZE)

IMPLICIT NONE

INTEGER*8 :: KSIZE

INTEGER*8 :: NMETADATA

NMETADATA = NMETADATA - KSIZE

END SUBROUTINE

END MODULE
