INTERFACE
SUBROUTINE GPNORM2(YDGEOMETRY,KFIELDS,KSTAF,PGP,CDLABEL)
USE GEOMETRY_MOD ,ONLY : GEOMETRY
USE PARKIND1     ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN)    :: KFIELDS
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTAF
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGP(:,:,:)
CHARACTER(LEN=*)  ,INTENT(IN),OPTIONAL :: CDLABEL
END SUBROUTINE GPNORM2







END INTERFACE
