
MODULE IOSTREAM_MIX
USE PARKIND1,ONLY:JPRD, JPIM, JPIB, JPRB
USE PARDIM,ONLY:JPMXGL

IMPLICIT NONE

SAVE


TYPE (TYPE_GRIB_HANDLES)::YGBH
REAL (KIND=JPRB), PARAMETER, PUBLIC::RMDI=HUGE (RMDI)
INTEGER (KIND=JPIM), PARAMETER::JPNONDEF=-99
INTEGER (KIND=JPIB), PARAMETER::JPMAXGRID=2_JPIB*INT (JPMXGL, JPIB)*INT (JPMXGL, JPIB)
INTEGER (KIND=JPIM), PARAMETER::JPMAXCHUNK=8192
INTEGER (KIND=JPIM), PARAMETER::JPFDB=1
INTEGER (KIND=JPIM), PARAMETER::JPCIO=2
INTEGER (KIND=JPIM), PARAMETER::JPFTN=3

TYPE TYPE_IOSTREAM
  INTEGER (KIND=JPIM)::IOTYPE=0
  INTEGER (KIND=JPIM)::IFILE_HANDLE=JPNONDEF
  INTEGER (KIND=JPIM)::IOMASTER=JPNONDEF
  CHARACTER (LEN=1)::CMODE='r'
  CHARACTER (LEN=120)::CPATH
  LOGICAL::LEOF
  INTEGER (KIND=JPIM)::NRECS
  INTEGER (KIND=JPIB)::NBYTES
  LOGICAL::LIOPROC
  LOGICAL::LIOPROCHLP
  LOGICAL::LIOUSEHELP
  LOGICAL::LIONOHELP
  LOGICAL::LNVALS
  INTEGER (KIND=JPIM), ALLOCATABLE::IOPROCS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::IOPROCSHLP (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NUMHLP (:)
  INTEGER (KIND=JPIM)::NUMIOPROCS
  INTEGER (KIND=JPIM)::MIOPROCHLP
  INTEGER (KIND=JPIM)::NUMIOPROCSHLP
  INTEGER (KIND=JPIM)::NVALS
  REAL (KIND=JPRD)::WALLCLOCK
  REAL (KIND=JPRD)::TOTWALL
  LOGICAL::SERIAL
ENDTYPE TYPE_IOSTREAM

INTEGER (KIND=JPIM), PARAMETER::JPRAW=1
INTEGER (KIND=JPIM), PARAMETER::JPSPEC=2
INTEGER (KIND=JPIM), PARAMETER::JPGP=3

TYPE TYPE_3D_MDL_FLDS
  INTEGER (KIND=JPIM)::NUMFLDS
  INTEGER (KIND=JPIM)::NLEVS
  INTEGER (KIND=JPIM), ALLOCATABLE::ILEVS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::IGRIBCODE (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::IBSET (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::ILOCLEV (:)
ENDTYPE TYPE_3D_MDL_FLDS


TYPE TYPE_2D_MDL_FLDS
  INTEGER (KIND=JPIM)::NUMFLDS
  INTEGER (KIND=JPIM), ALLOCATABLE::IGRIBCODE (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::ILEVS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::IBSET (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::ILOCFLD (:)
ENDTYPE TYPE_2D_MDL_FLDS


TYPE TYPE_SPECTRAL_FLD_DEF
  INTEGER (KIND=JPIM)::ISMAX
  INTEGER (KIND=JPIM)::ISPEC2G
  INTEGER (KIND=JPIM)::ISPEC2
  INTEGER (KIND=JPIM)::IMAXSPEC2G
ENDTYPE TYPE_SPECTRAL_FLD_DEF


TYPE TYPE_GRIDPOINT_FLD_DEF
  INTEGER (KIND=JPIM)::IGPTOTG
  INTEGER (KIND=JPIM)::IGPTOT
  INTEGER (KIND=JPIM)::NPROMA
ENDTYPE TYPE_GRIDPOINT_FLD_DEF


TYPE TYPE_IOREQUEST
  INTEGER (KIND=JPIM)::IDATA_TYPE=JPNONDEF
  LOGICAL::LGRIB=.FALSE.
  LOGICAL::LRANDOM_ORDER
  LOGICAL::LFPDIST
  LOGICAL::LINTERP
  LOGICAL::LDISTRIBUTE
  LOGICAL::LDISTHEADER
  LOGICAL::LGEOPRESET
  LOGICAL::LREADALL
  LOGICAL::LINQUIRE
  LOGICAL::LATLONG
  LOGICAL::LINTONLY
  INTEGER (KIND=JPIM)::NTYPE_INTERP
  INTEGER (KIND=JPIM)::NRESOL
  CHARACTER (LEN=3)::CLEVTYPE='SFC'
  TYPE (TYPE_3D_MDL_FLDS)::YMDL_3D
  TYPE (TYPE_2D_MDL_FLDS)::YMDL_2D
  TYPE (TYPE_SPECTRAL_FLD_DEF)::YSPF
  TYPE (TYPE_GRIDPOINT_FLD_DEF)::YGPF
  INTEGER (KIND=JPIM)::ILEV
  INTEGER (KIND=JPIM)::IGRBCODE
  INTEGER (KIND=JPIM), ALLOCATABLE::ILEVS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::IGRBCODES (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::IHAVEFLD (:)
  CHARACTER (LEN=32)::CREPRT
  INTEGER (KIND=JPIM)::IRESOLI
  INTEGER (KIND=JPIM)::NCHUNKSIZE
  INTEGER (KIND=JPIM)::IFIELDS_IO
  INTEGER (KIND=JPIM)::IGRIB_HANDLE
  INTEGER (KIND=JPIM)::IGRIB_HANDLE2
  INTEGER (KIND=JPIM), ALLOCATABLE::IGRIB_OMP_HANDLE (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::IGRIB_OMP_HANDLE2 (:)
  INTEGER (KIND=JPIM)::IVALUES
  INTEGER (KIND=JPIM)::IFIELDS_HAVE
  REAL (KIND=JPRB)::TSTEP
  INTEGER (KIND=JPIM)::IOCOMM
ENDTYPE TYPE_IOREQUEST


TYPE TYPE_INT_VARS
  INTEGER (KIND=JPIM)::NUNDEF
  INTEGER (KIND=JPIM)::NULERR
  INTEGER (KIND=JPIM)::NULOUT
  INTEGER (KIND=JPIM)::MYPROC
  INTEGER (KIND=JPIM)::NPROC
  INTEGER (KIND=JPIB)::IMAXGRID
  INTEGER (KIND=JPIB)::IMAXSPEC2G
  REAL (KIND=JPRB)::RPI
  REAL (KIND=JPRB)::SIPR
  INTEGER (KIND=JPIM)::NREALEN
  INTEGER (KIND=JPIM)::NINTLEN
  INTEGER (KIND=JPIM), ALLOCATABLE::NBSETLEV (:)
  INTEGER (KIND=JPIM)::NBSETSP
  INTEGER (KIND=JPIM)::NFLEVG
  INTEGER (KIND=JPIM)::NSMAX
  INTEGER (KIND=JPIM)::NDGLG
  INTEGER (KIND=JPIM), ALLOCATABLE::NLOENG (:)
  REAL (KIND=JPRB), ALLOCATABLE::VAH (:)
  REAL (KIND=JPRB), ALLOCATABLE::VBH (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLATIG (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NUMPROCFP (:)
  INTEGER (KIND=JPIM)::NFPRGPL
  INTEGER (KIND=JPIM)::NFPRGPG
  INTEGER (KIND=JPIM)::NFPRGPLX
  INTEGER (KIND=JPIM), ALLOCATABLE::NFPMAX (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MSATID (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MSERIES (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MINST (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MCHAN (:)
  REAL (KIND=JPRB), ALLOCATABLE::RCWN (:)
  LOGICAL::LIFS_INTERNAL
ENDTYPE TYPE_INT_VARS

TYPE (TYPE_IOSTREAM)::Y_IOSTREAM_FDB
TYPE (TYPE_INT_VARS)::YIOS
LOGICAL::LPACK_INIT=.FALSE.
INTEGER (KIND=JPIM)::NIOSTREAMC=0
INTEGER (KIND=JPIM)::NOPENIOSTREAMS=0
INTEGER (KIND=JPIM)::NOPENEDIOSTREAMS=0
REAL (KIND=JPRD)::TOTAL_WALLCLOCK=0.0_JPRD
REAL (KIND=JPRD)::WALLCLOCK_OUT=0.0_JPRD
REAL (KIND=JPRD)::TOTWALL_OUT=0.0_JPRD
INTEGER (KIND=JPIM)::NRECS_OUT=0_JPIM
INTEGER (KIND=JPIB)::NBYTES_OUT=0_JPIB
REAL (KIND=JPRD)::WALLCLOCK_IN=0.0_JPRD
REAL (KIND=JPRD)::TOTWALL_IN=0.0_JPRD
INTEGER (KIND=JPIM)::NRECS_IN=0_JPIM
INTEGER (KIND=JPIB)::NBYTES_IN=0_JPIB
INTEGER (KIND=JPIM), ALLOCATABLE, TARGET::NGRIBD (:)
INTEGER (KIND=JPIM), ALLOCATABLE::NGRIBMSG (:)
INTEGER (KIND=JPIM), ALLOCATABLE, TARGET::NGSTA (:)
LOGICAL, ALLOCATABLE::LGRIBDONE (:)


ENDMODULE IOSTREAM_MIX
