

MODULE MF_PHYS_BASE_STATE_TYPE_MOD

!$ACDC methods --methods-list=wipe,copy --field-api --field-api-class cpg

USE PARKIND1, ONLY : JPIM, JPRB
USE CPG_TYPE_MOD, ONLY : CPG_DYN_TYPE, CPG_PHY_TYPE
USE FIELD_MODULE
IMPLICIT NONE

TYPE MF_PHYS_BASE_STATE_3D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:, :) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P => NULL ()

CONTAINS

  PROCEDURE :: INIT_0_3D => MF_PHYS_BASE_STATE_3D_TYPE_INIT_0_3D
  PROCEDURE :: INIT_9_3D => MF_PHYS_BASE_STATE_3D_TYPE_INIT_9_3D

END TYPE MF_PHYS_BASE_STATE_3D_TYPE


TYPE MF_PHYS_STATE_GSP_SG_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: F (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: F (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SG)
  CLASS (FIELD_3RB), POINTER :: F_F => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: A (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: A (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SG)
  CLASS (FIELD_3RB), POINTER :: F_A => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: R (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SG)
  CLASS (FIELD_3RB), POINTER :: F_R => NULL ()
END TYPE MF_PHYS_STATE_GSP_SG_TYPE

TYPE MF_PHYS_STATE_GSP_RR_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:) => NULL ()
!>REAL (KIND=JPRB)                      :: T (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_T => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FC (:) => NULL ()
!>REAL (KIND=JPRB)                      :: FC (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_FC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: W (:) => NULL ()
!>REAL (KIND=JPRB)                      :: W (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_W => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: IC (:) => NULL ()
!>REAL (KIND=JPRB)                      :: IC (NPROMA)
  CLASS (FIELD_2RB), POINTER :: F_IC => NULL ()
END TYPE MF_PHYS_STATE_GSP_RR_TYPE

TYPE MF_PHYS_STATE_GSP_SB_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: Q (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SB)
  CLASS (FIELD_3RB), POINTER :: F_Q => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TL (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: TL (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SB)
  CLASS (FIELD_3RB), POINTER :: F_TL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:,:) => NULL ()
!>REAL (KIND=JPRB)                      :: T (NPROMA, YDCPG_OPTS%YRSURF_DIMS%YSP_GSP_SB)
  CLASS (FIELD_3RB), POINTER :: F_T => NULL ()
END TYPE MF_PHYS_STATE_GSP_SB_TYPE


  TYPE MF_PHYS_BASE_STATE_TYPE

    TYPE (CPG_DYN_TYPE) :: YCPG_DYN
    TYPE (CPG_PHY_TYPE) :: YCPG_PHY

    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: U
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: V
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: T
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: DIV
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: VOR
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SPD
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SVD
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CSPDNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CSPNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CSVDPT
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CTNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CTPT
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CUNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CUPT
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CVNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CVPT
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CVWVNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: DPHI
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: EDOT
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: GW
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: NHX
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: NHY
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SGRTL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SGRTM
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SPDNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SPDNL_SI
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SPNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SPNL_SI
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SVDNL_SI
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: TNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: TNL_SI
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: UNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: UNL_SI
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: VNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: VNL_SI
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: VWVNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CURHS
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CVRHS
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CTRHS
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CSPDRHS
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CSVDRHS
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: NHXNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CNHXNL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_U
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_V
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_T
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_SPD
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_SVD
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_NHX
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_SP
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_CP
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_UP
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_VP
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PCF_TP

    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: Q
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: I
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: L
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: IMF
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: LMF
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: HLMF
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: HIMF
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: LCONV
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: ICONV
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: RCONV
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SCONV
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: IRAD
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: LRAD
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: S
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: R
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: G
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: H
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: TKE
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: TTE
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: EFB1
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: EFB2
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: EFB3
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: A
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: AMF
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: WMFC
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: HLCFMF
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: HICFMF
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: O3
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SRC
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: MXL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SHTUR
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: FQTUR
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: FSTUR
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CPF
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SPF
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CVGQ
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: QVA
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: GHG (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: CHEM (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: AERO (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: LRCH4
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: FORC (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: EZDIAG (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: ERA40 (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: NOGW (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: EMIS3D (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: EDRP (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: SLDIA (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: AERAOT (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: AERLISI (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: AEROUT (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: AEROCLIM (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: UVP (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: PHYCTY
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: RSPEC
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: SDSAT
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: CVV
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: RKTH
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: RKTQV
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: RKTQC
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: UOM
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: UAL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: DOM
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: DAL
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: UEN
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: MO
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: UNEBH
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: LIMA (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: FSD
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE), ALLOCATABLE :: EXT (:)
    TYPE (MF_PHYS_BASE_STATE_3D_TYPE) :: THRAD

    TYPE (MF_PHYS_STATE_GSP_SG_TYPE) :: YGSP_SG
    TYPE (MF_PHYS_STATE_GSP_RR_TYPE) :: YGSP_RR
    TYPE (MF_PHYS_STATE_GSP_SB_TYPE) :: YGSP_SB

CONTAINS

    PROCEDURE :: INIT => MF_PHYS_BASE_STATE_TYPE_INIT
    PROCEDURE :: UPDATE_VIEW => MF_PHYS_BASE_STATE_TYPE_UPDATE_VIEW

  END TYPE MF_PHYS_BASE_STATE_TYPE

CONTAINS

  SUBROUTINE MF_PHYS_BASE_STATE_TYPE_INIT (SELF, YDCPG_DYN0, YDCPG_DYN9, YDCPG_PHY0, YDCPG_PHY9, YDVARS, YDMF_PHYS_SURF, YDMODEL)

    USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
    USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
    USE SC2PRG_MOD         , ONLY : SC2PRG
    USE TYPE_MODEL         , ONLY : MODEL

    CLASS (MF_PHYS_BASE_STATE_TYPE), INTENT(INOUT) :: SELF

    TYPE (CPG_DYN_TYPE),     INTENT(IN) :: YDCPG_DYN0, YDCPG_DYN9
    TYPE (CPG_PHY_TYPE),     INTENT(IN) :: YDCPG_PHY0, YDCPG_PHY9
    TYPE(FIELD_VARIABLES),   INTENT(IN) :: YDVARS
    TYPE(MF_PHYS_SURF_TYPE), INTENT(IN) :: YDMF_PHYS_SURF
    TYPE(MODEL),             INTENT(IN) :: YDMODEL

  END SUBROUTINE MF_PHYS_BASE_STATE_TYPE_INIT

  SUBROUTINE MF_PHYS_BASE_STATE_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

    CLASS (MF_PHYS_BASE_STATE_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

    INTEGER (KIND=JPIM) :: JGFL

  END SUBROUTINE MF_PHYS_BASE_STATE_TYPE_UPDATE_VIEW

  SUBROUTINE MF_PHYS_BASE_STATE_3D_TYPE_INIT_0_3D(SELF, YDV3D)

    USE VARIABLE_MODULE , ONLY : VARIABLE_3RB

    CLASS(MF_PHYS_BASE_STATE_3D_TYPE), INTENT (INOUT) :: SELF
    TYPE(VARIABLE_3RB),                INTENT (IN)    :: YDV3D

    SELF%P   => YDV3D%T0
    SELF%F_P => YDV3D%FT0

  END SUBROUTINE MF_PHYS_BASE_STATE_3D_TYPE_INIT_0_3D

  SUBROUTINE MF_PHYS_BASE_STATE_3D_TYPE_INIT_9_3D(SELF, YDV3D)

    USE VARIABLE_MODULE , ONLY : VARIABLE_3RB

    CLASS(MF_PHYS_BASE_STATE_3D_TYPE), INTENT (INOUT) :: SELF
    TYPE(VARIABLE_3RB),                INTENT (IN)    :: YDV3D

    SELF%P   => YDV3D%T9
    SELF%F_P => YDV3D%FT9

  END SUBROUTINE MF_PHYS_BASE_STATE_3D_TYPE_INIT_9_3D

END MODULE MF_PHYS_BASE_STATE_TYPE_MOD
