INTERFACE
SUBROUTINE MF_PHYS_MOCON (YDCPG_BNDS, YDCPG_OPTS, PRDG_LCVQ, PMOC_CLPH, YDMF_PHYS, YDMF_PHYS_BASE_STATE)
USE PARKIND1, ONLY : JPIM, JPRB
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD   , ONLY : MF_PHYS_TYPE
USE MF_PHYS_BASE_STATE_TYPE_MOD &
                       , ONLY : MF_PHYS_BASE_STATE_TYPE
IMPLICIT NONE
TYPE(CPG_BNDS_TYPE),           INTENT(IN)    :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),           INTENT(IN)    :: YDCPG_OPTS
REAL(KIND=JPRB),               INTENT(IN)    :: PRDG_LCVQ (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
INTEGER (KIND=JPIM),           INTENT(IN)    :: PMOC_CLPH (YDCPG_OPTS%KLON)
TYPE(MF_PHYS_TYPE),            INTENT(INOUT) :: YDMF_PHYS
TYPE(MF_PHYS_BASE_STATE_TYPE), INTENT(IN)    :: YDMF_PHYS_BASE_STATE
END SUBROUTINE MF_PHYS_MOCON




SUBROUTINE MF_PHYS_MOCON_PARALLEL (YDCPG_BNDS, YDCPG_OPTS, YD_PRDG_LCVQ&
&, YD_PMOC_CLPH, YDMF_PHYS, YDMF_PHYS_BASE_STATE)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD,ONLY:MF_PHYS_TYPE
USE MF_PHYS_BASE_STATE_TYPE_MOD,ONLY:MF_PHYS_BASE_STATE_TYPE
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
CLASS (FIELD_3RB), POINTER :: YD_PRDG_LCVQ
CLASS (FIELD_2IM), POINTER :: YD_PMOC_CLPH
TYPE (MF_PHYS_TYPE), INTENT (INOUT)::YDMF_PHYS
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT (IN)::YDMF_PHYS_BASE_STATE

END SUBROUTINE MF_PHYS_MOCON_PARALLEL




END INTERFACE
