MODULE MF_PHYS_NEXT_STATE_TYPE_MOD

!$ACDC methods --methods-list=wipe,copy --field-api --field-api-class cpg

USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_MODULE
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_DIMS_VARS_TYPE
IMPLICIT NONE

TYPE MF_PHYS_NEXT_STATE_2D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:) => NULL ()
  CLASS (FIELD_2RB), POINTER :: F_P => NULL ()
END TYPE MF_PHYS_NEXT_STATE_2D_TYPE

TYPE MF_PHYS_NEXT_STATE_3D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:, :) => NULL ()
  CLASS (FIELD_3RB), POINTER :: F_P => NULL ()
END TYPE MF_PHYS_NEXT_STATE_3D_TYPE

TYPE MF_PHYS_NEXT_STATE_TYPE

  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: U
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: V
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: T
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SVD
  TYPE (MF_PHYS_NEXT_STATE_2D_TYPE) :: SP

  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: Q
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: I
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: L
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: IMF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: LMF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: HLMF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: HIMF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: LCONV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: ICONV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RCONV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SCONV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: IRAD
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: LRAD
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: S
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: R
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: G
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: H
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: TKE
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: TTE
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: EFB1
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: EFB2
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: EFB3
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: A
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: AMF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: WMFC
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: HLCFMF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: HICFMF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: O3
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SRC
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: MXL
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SHTUR
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: FQTUR
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: FSTUR
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: CPF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SPF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: CVGQ
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: QVA
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: GHG (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: CHEM (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AERO (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: LRCH4
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: FORC (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: EZDIAG (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: ERA40 (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: NOGW (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: EMIS3D (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: EDRP (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: SLDIA (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AERAOT (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AERLISI (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AEROUT (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AEROCLIM (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: UVP (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: PHYCTY
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RSPEC
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SDSAT
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: CVV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RKTH
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RKTQV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RKTQC
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: UOM
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: UAL
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: DOM
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: DAL
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: UEN
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: MO
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: UNEBH
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: LIMA (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: FSD
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: EXT (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: THRAD


  TYPE (CPG_DIMS_VARS_TYPE) :: DIMS

CONTAINS

  PROCEDURE :: INIT => MF_PHYS_NEXT_STATE_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_NEXT_STATE_TYPE_UPDATE_VIEW

END TYPE MF_PHYS_NEXT_STATE_TYPE

CONTAINS

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT (SELF, YDCPG_SL1, YDGEOMETRY, YDVARS, YDMODEL)

USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE CPG_SL1_TYPE_MOD   , ONLY : CPG_SL1B_TYPE
USE TYPE_MODEL         , ONLY : MODEL

CLASS (MF_PHYS_NEXT_STATE_TYPE)     :: SELF
TYPE (CPG_SL1B_TYPE),   INTENT (IN) :: YDCPG_SL1
TYPE(GEOMETRY),         INTENT (IN) :: YDGEOMETRY
TYPE (FIELD_VARIABLES), INTENT (IN) :: YDVARS
TYPE(MODEL),            INTENT (IN) :: YDMODEL

CONTAINS

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDV3D, YDN3D)

USE VARIABLE_MODULE, ONLY: VARIABLE_3RB

TYPE (VARIABLE_3RB),               INTENT (IN)    :: YDV3D
TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), INTENT (INOUT) :: YDN3D

YDN3D%P   => YDV3D%T1
YDN3D%F_P => YDV3D%FT1

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDV3D, YDN3D, YDF3D)

USE CPG_SL1_TYPE_MOD, ONLY : CPG_SL1B_3D_TYPE
USE VARIABLE_MODULE , ONLY : VARIABLE_3RB

TYPE (VARIABLE_3RB),               INTENT (IN)    :: YDV3D
TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), INTENT (INOUT) :: YDN3D
TYPE (CPG_SL1B_3D_TYPE),           INTENT (IN)    :: YDF3D

IF (YDV3D%LADV) THEN
  YDN3D%P   => YDF3D%P
  YDN3D%F_P => YDF3D%F_P
ELSE
  YDN3D%P   => YDV3D%T1
  YDN3D%F_P => YDV3D%FT1
ENDIF

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT_3D

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDV3D, YDN3D, YDF3D)

USE CPG_SL1_TYPE_MOD, ONLY : CPG_SL1B_3D_TYPE
USE VARIABLE_MODULE , ONLY : VARIABLE_3RB

TYPE (VARIABLE_3RB),               INTENT (IN)    :: YDV3D
TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), INTENT (INOUT) :: YDN3D
TYPE (CPG_SL1B_3D_TYPE),           INTENT (IN)    :: YDF3D

IF (YDV3D%LADV) THEN
  YDN3D%P   => YDF3D%P_F
  YDN3D%F_P => YDF3D%F_P_F
ELSE
  YDN3D%P   => YDV3D%T1
  YDN3D%F_P => YDV3D%FT1
ENDIF

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)
CLASS (MF_PHYS_NEXT_STATE_TYPE)              :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

INTEGER (KIND=JPIM) :: JGFL

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_UPDATE_VIEW 

END MODULE MF_PHYS_NEXT_STATE_TYPE_MOD
