INTERFACE
SUBROUTINE MF_PHYS_SAVE_PHSURF_PART2 (YDCPG_BNDS, YDCPG_OPTS, PSAV_DDAL, PSAV_DDOM, PSAV_ENTCH,               &
& PSAV_FHPS, PSAV_GZ0F, PSAV_GZ0HF, PSAV_HV, PSAV_PBLH, PSAV_QSH, PSAV_UDAL, PSAV_UDGRO, PSAV_UDOM,           &
& PSAV_UNEBH, PSAV_MO, PGSD_VF_PZ0F, PGSD_VH_PPBLH, PGSD_VH_PQSH, PGSD_VH_PSPSH, PGSD_VK_PUDGRO, PGSD_VV_PHV, &
& PGSD_VV_PZ0H, PDAL_T0, PDOM_T0, PUAL_T0, PUEN_T0, PUNEBH_T0, PUOM_T0, PMO_T0, YDMODEL)
USE PARKIND1, ONLY : JPIM, JPRB
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE TYPE_MODEL         , ONLY : MODEL
IMPLICIT NONE
TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_DDAL  (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_DDOM  (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_ENTCH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_FHPS  (YDCPG_OPTS%KLON)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_GZ0F  (YDCPG_OPTS%KLON)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_GZ0HF (YDCPG_OPTS%KLON)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_HV    (YDCPG_OPTS%KLON)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_PBLH  (YDCPG_OPTS%KLON)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_QSH   (YDCPG_OPTS%KLON)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_UDAL  (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_UDGRO (YDCPG_OPTS%KLON)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_UDOM  (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_UNEBH (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)   :: PSAV_MO    (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB),   INTENT(OUT)  :: PGSD_VF_PZ0F (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),   INTENT(OUT)  :: PGSD_VH_PPBLH (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),   INTENT(OUT)  :: PGSD_VH_PQSH (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),   INTENT(OUT)  :: PGSD_VH_PSPSH (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),   INTENT(OUT)  :: PGSD_VK_PUDGRO (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),   INTENT(OUT)  :: PGSD_VV_PHV (YDCPG_OPTS%KLON)
REAL(KIND=JPRB),   INTENT(OUT)  :: PGSD_VV_PZ0H (YDCPG_OPTS%KLON)
REAL (KIND=JPRB),  INTENT(OUT)  :: PDAL_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(OUT)  :: PDOM_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(OUT)  :: PUAL_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(OUT)  :: PUEN_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(OUT)  :: PUNEBH_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(OUT)  :: PUOM_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(OUT)  :: PMO_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
TYPE(MODEL)       ,INTENT(IN)   :: YDMODEL
END SUBROUTINE MF_PHYS_SAVE_PHSURF_PART2




SUBROUTINE MF_PHYS_SAVE_PHSURF_PART2_PARALLEL (YDCPG_BNDS, YDCPG_OPTS, YD_PSAV_DDAL, YD_PSAV_DDOM,&
& YD_PSAV_ENTCH, YD_PSAV_FHPS, YD_PSAV_GZ0F, YD_PSAV_GZ0HF, YD_PSAV_HV, YD_PSAV_PBLH, YD_PSAV_QSH,&
& YD_PSAV_UDAL, YD_PSAV_UDGRO, YD_PSAV_UDOM, YD_PSAV_UNEBH, YD_PSAV_MO, YD_PGSD_VF_PZ0F, YD_PGSD_VH_PPBLH&
&, YD_PGSD_VH_PQSH, YD_PGSD_VH_PSPSH, YD_PGSD_VK_PUDGRO, YD_PGSD_VV_PHV, YD_PGSD_VV_PZ0H, YD_PDAL_T0&
&, YD_PDOM_T0, YD_PUAL_T0, YD_PUEN_T0, YD_PUNEBH_T0, YD_PUOM_T0, YD_PMO_T0, YDMODEL)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
CLASS (FIELD_3RB), POINTER :: YD_PSAV_DDAL
CLASS (FIELD_3RB), POINTER :: YD_PSAV_DDOM
CLASS (FIELD_3RB), POINTER :: YD_PSAV_ENTCH
CLASS (FIELD_2RB), POINTER :: YD_PSAV_FHPS
CLASS (FIELD_2RB), POINTER :: YD_PSAV_GZ0F
CLASS (FIELD_2RB), POINTER :: YD_PSAV_GZ0HF
CLASS (FIELD_2RB), POINTER :: YD_PSAV_HV
CLASS (FIELD_2RB), POINTER :: YD_PSAV_PBLH
CLASS (FIELD_2RB), POINTER :: YD_PSAV_QSH
CLASS (FIELD_3RB), POINTER :: YD_PSAV_UDAL
CLASS (FIELD_2RB), POINTER :: YD_PSAV_UDGRO
CLASS (FIELD_3RB), POINTER :: YD_PSAV_UDOM
CLASS (FIELD_3RB), POINTER :: YD_PSAV_UNEBH
CLASS (FIELD_3RB), POINTER :: YD_PSAV_MO
CLASS (FIELD_2RB), POINTER :: YD_PGSD_VF_PZ0F
CLASS (FIELD_2RB), POINTER :: YD_PGSD_VH_PPBLH
CLASS (FIELD_2RB), POINTER :: YD_PGSD_VH_PQSH
CLASS (FIELD_2RB), POINTER :: YD_PGSD_VH_PSPSH
CLASS (FIELD_2RB), POINTER :: YD_PGSD_VK_PUDGRO
CLASS (FIELD_2RB), POINTER :: YD_PGSD_VV_PHV
CLASS (FIELD_2RB), POINTER :: YD_PGSD_VV_PZ0H
CLASS (FIELD_3RB), POINTER :: YD_PDAL_T0
CLASS (FIELD_3RB), POINTER :: YD_PDOM_T0
CLASS (FIELD_3RB), POINTER :: YD_PUAL_T0
CLASS (FIELD_3RB), POINTER :: YD_PUEN_T0
CLASS (FIELD_3RB), POINTER :: YD_PUNEBH_T0
CLASS (FIELD_3RB), POINTER :: YD_PUOM_T0
CLASS (FIELD_3RB), POINTER :: YD_PMO_T0
TYPE (MODEL), INTENT (IN)::YDMODEL

END SUBROUTINE MF_PHYS_SAVE_PHSURF_PART2_PARALLEL




END INTERFACE
