INTERFACE
SUBROUTINE MF_PHYS_FPL_PART1 (YDCPG_BNDS, YDCPG_OPTS, PPFL_FPLCH, PPFL_FPLSH, PCPF_T0, PSPF_T0, &
& YDMODEL)
USE PARKIND1, ONLY : JPIM, JPRB
USE CPG_OPTS_TYPE_MOD   , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE TYPE_MODEL         , ONLY : MODEL
IMPLICIT NONE
TYPE(CPG_BNDS_TYPE),INTENT(IN)   :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN)   :: YDCPG_OPTS
REAL (KIND=JPRB),  INTENT(OUT)   :: PPFL_FPLCH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(OUT)   :: PPFL_FPLSH (YDCPG_OPTS%KLON, 0:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)    :: PCPF_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB),  INTENT(IN)    :: PSPF_T0 (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
TYPE(MODEL)       ,INTENT(IN)    :: YDMODEL
END SUBROUTINE MF_PHYS_FPL_PART1




SUBROUTINE MF_PHYS_FPL_PART1_PARALLEL (YDCPG_BNDS, YDCPG_OPTS, YD_PPFL_FPLCH&
&, YD_PPFL_FPLSH, YD_PCPF_T0, YD_PSPF_T0, YDMODEL)
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ACCESS_MODULE
USE FXTRAN_ACDC_PARALLELMETHOD_MOD
USE FXTRAN_ACDC_STACK_MOD
USE YOMHOOK
USE PARKIND1
USE FXTRAN_ACDC_GPUMEM_MOD
IMPLICIT NONE

TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FPLCH
CLASS (FIELD_3RB), POINTER :: YD_PPFL_FPLSH
CLASS (FIELD_3RB), POINTER :: YD_PCPF_T0
CLASS (FIELD_3RB), POINTER :: YD_PSPF_T0
TYPE (MODEL), INTENT (IN)::YDMODEL

END SUBROUTINE MF_PHYS_FPL_PART1_PARALLEL




END INTERFACE
