
MODULE MODD_PARAM_ICE_N
USE MODD_PARAMETERS,ONLY:JPMODELMAX

IMPLICIT NONE


TYPE PARAM_ICE_T
  LOGICAL::LWARM
  LOGICAL::LSEDIC
  LOGICAL::LDEPOSC
  REAL::XVDEPOSC
  CHARACTER (LEN=4)::CPRISTINE_ICE
  CHARACTER (LEN=4)::CSEDIM
  LOGICAL::LRED
  LOGICAL::LFEEDBACKT
  LOGICAL::LEVLIMIT
  LOGICAL::LNULLWETG
  LOGICAL::LWETGPOST
  LOGICAL::LNULLWETH
  LOGICAL::LWETHPOST
  CHARACTER (LEN=4)::CSNOWRIMING
  REAL::XFRACM90
  INTEGER::NMAXITER_MICRO
  REAL::XMRSTEP
  LOGICAL::LCONVHG
  LOGICAL::LCRFLIMIT
  REAL::XTSTEP_TS
  CHARACTER (LEN=80)::CSUBG_RC_RR_ACCR
  CHARACTER (LEN=80)::CSUBG_RR_EVAP
  CHARACTER (LEN=80)::CSUBG_PR_PDF
  CHARACTER (LEN=4)::CSUBG_AUCV_RC
  CHARACTER (LEN=80)::CSUBG_AUCV_RI
  CHARACTER (LEN=80)::CSUBG_MF_PDF
  LOGICAL::LADJ_BEFORE
  LOGICAL::LADJ_AFTER
  LOGICAL::LSEDIM_AFTER
  REAL::XSPLIT_MAXCFL
  LOGICAL::LSNOW_T
  LOGICAL::LPACK_INTERP
  LOGICAL::LPACK_MICRO
  INTEGER::NPROMICRO
  LOGICAL::LCRIAUTI
  REAL::XCRIAUTI_NAM
  REAL::XT0CRIAUTI_NAM
  REAL::XBCRIAUTI_NAM
  REAL::XACRIAUTI_NAM
  REAL::XCRIAUTC_NAM
  REAL::XRDEPSRED_NAM
  REAL::XRDEPGRED_NAM
  LOGICAL::LOCND2
  LOGICAL::LKOGAN
  LOGICAL::LMODICEDEP
  LOGICAL::LEXCLDROP
  REAL, DIMENSION (40)::XFRMIN_NAM
ENDTYPE PARAM_ICE_T

TYPE (PARAM_ICE_T), DIMENSION (JPMODELMAX), TARGET, SAVE::PARAM_ICE_MODEL
TYPE (PARAM_ICE_T), POINTER, SAVE::PARAM_ICEN=>NULL ()
LOGICAL, POINTER::LWARM=>NULL (), LSEDIC=>NULL (), LDEPOSC=>NULL (), LRED=>NULL (), LFEEDBACKT&
&=>NULL (), LEVLIMIT=>NULL (), LNULLWETG=>NULL (), LWETGPOST=>NULL (), LNULLWETH=>NULL (), LWETHPOST&
&=>NULL (), LCONVHG=>NULL (), LCRFLIMIT=>NULL (), LADJ_BEFORE=>NULL (), LADJ_AFTER=>NULL (), LSEDIM_AFTER&
&=>NULL (), LSNOW_T=>NULL (), LPACK_INTERP=>NULL (), LPACK_MICRO=>NULL (), LCRIAUTI=>NULL (), LOCND2&
&=>NULL (), LKOGAN=>NULL (), LMODICEDEP=>NULL (), LEXCLDROP=>NULL ()
REAL, POINTER::XVDEPOSC=>NULL (), XFRACM90=>NULL (), XMRSTEP=>NULL (), XTSTEP_TS=>NULL (), XSPLIT_MAXCFL&
&=>NULL (), XCRIAUTI_NAM=>NULL (), XT0CRIAUTI_NAM=>NULL (), XBCRIAUTI_NAM=>NULL (), XACRIAUTI_NAM&
&=>NULL (), XCRIAUTC_NAM=>NULL (), XRDEPSRED_NAM=>NULL (), XRDEPGRED_NAM=>NULL ()
REAL, DIMENSION (:), POINTER::XFRMIN_NAM=>NULL ()
INTEGER, POINTER::NMAXITER_MICRO=>NULL (), NPROMICRO=>NULL ()
CHARACTER (LEN=4), POINTER::CPRISTINE_ICE=>NULL ()
CHARACTER (LEN=4), POINTER::CSEDIM=>NULL ()
CHARACTER (LEN=4), POINTER::CSNOWRIMING=>NULL ()
CHARACTER (LEN=80), POINTER::CSUBG_RC_RR_ACCR=>NULL ()
CHARACTER (LEN=80), POINTER::CSUBG_RR_EVAP=>NULL ()
CHARACTER (LEN=80), POINTER::CSUBG_PR_PDF=>NULL ()
CHARACTER (LEN=4), POINTER::CSUBG_AUCV_RC=>NULL ()
CHARACTER (LEN=80), POINTER::CSUBG_AUCV_RI=>NULL ()
CHARACTER (LEN=80), POINTER::CSUBG_MF_PDF=>NULL ()
NAMELIST/NAM_PARAM_ICEN/LWARM, LSEDIC, LCONVHG, CPRISTINE_ICE, CSEDIM, LDEPOSC, XVDEPOSC, LRED, LFEEDBACKT&
&, LEVLIMIT, LNULLWETG, LWETGPOST, LNULLWETH, LWETHPOST, CSNOWRIMING, XFRACM90, NMAXITER_MICRO, XMRSTEP&
&, XTSTEP_TS, LADJ_BEFORE, LADJ_AFTER, LCRFLIMIT, XSPLIT_MAXCFL, LSEDIM_AFTER, LSNOW_T, LPACK_INTERP&
&, LPACK_MICRO, NPROMICRO, CSUBG_RC_RR_ACCR, CSUBG_RR_EVAP, CSUBG_PR_PDF, CSUBG_AUCV_RC, CSUBG_AUCV_RI&
&, LCRIAUTI, XCRIAUTI_NAM, XT0CRIAUTI_NAM, XBCRIAUTI_NAM, XACRIAUTI_NAM, XCRIAUTC_NAM, XRDEPSRED_NAM&
&, XRDEPGRED_NAM, LOCND2, LKOGAN, LMODICEDEP, LEXCLDROP, XFRMIN_NAM, CSUBG_MF_PDF
CONTAINS


ENDMODULE MODD_PARAM_ICE_N
