
MODULE MODD_TURB_N
USE MODD_PARAMETERS,ONLY:JPMODELMAX

IMPLICIT NONE


TYPE TURB_T
  REAL::XIMPL
  REAL::XTKEMIN
  REAL::XCED
  REAL::XCTP
  REAL::XCSHF
  REAL::XCHF
  REAL::XCTV
  REAL::XCHV
  REAL::XCHT1
  REAL::XCHT2
  REAL::XCPR1
  REAL::XCADAP
  CHARACTER (LEN=4)::CTURBLEN
  CHARACTER (LEN=4)::CTURBDIM
  LOGICAL::LTURB_FLX
  LOGICAL::LTURB_DIAG
  LOGICAL::LSIG_CONV
  LOGICAL::LHARAT
  LOGICAL::LBL89TOP
  LOGICAL::LRMC01
  CHARACTER (LEN=4)::CTOM
  REAL, DIMENSION (:,:,:), POINTER::XDYP=>NULL ()
  REAL, DIMENSION (:,:,:), POINTER::XTHP=>NULL ()
  REAL, DIMENSION (:,:,:), POINTER::XTR=>NULL ()
  REAL, DIMENSION (:,:,:), POINTER::XDISS=>NULL ()
  REAL, DIMENSION (:,:,:), POINTER::XLEM=>NULL ()
  REAL, DIMENSION (:,:,:), POINTER::XSSUFL_C=>NULL ()
  REAL, DIMENSION (:,:,:), POINTER::XSSVFL_C=>NULL ()
  REAL, DIMENSION (:,:,:), POINTER::XSSTFL_C=>NULL ()
  REAL, DIMENSION (:,:,:), POINTER::XSSRFL_C=>NULL ()
  LOGICAL::LLEONARD
  REAL::XCOEFHGRADTHL
  REAL::XCOEFHGRADRM
  REAL::XALTHGRAD
  LOGICAL::LGOGER
  REAL::XSMAG
  REAL::XCLDTHOLD
  REAL::XLINI
  LOGICAL::LROTATE_WIND
  LOGICAL::LTKEMINTURB
  LOGICAL::LPROJQITURB
  LOGICAL::LSMOOTH_PRANDTL
  REAL::XMINSIGS
  REAL::XBL89EXP, XUSRBL89
  
  
  
  
  
  
  
  
ENDTYPE TURB_T

TYPE (TURB_T), DIMENSION (JPMODELMAX), TARGET, SAVE::TURB_MODEL
TYPE (TURB_T), POINTER, SAVE::TURBN=>NULL ()
REAL, POINTER::XIMPL=>NULL ()
REAL, POINTER::XTKEMIN=>NULL ()
REAL, POINTER::XCED=>NULL ()
REAL, POINTER::XCTP=>NULL ()
REAL, POINTER::XCSHF=>NULL ()
REAL, POINTER::XCHF=>NULL ()
REAL, POINTER::XCTV=>NULL ()
REAL, POINTER::XCHV=>NULL ()
REAL, POINTER::XCHT1=>NULL ()
REAL, POINTER::XCHT2=>NULL ()
REAL, POINTER::XCPR1=>NULL ()
REAL, POINTER::XCADAP=>NULL ()
CHARACTER (LEN=4), POINTER::CTURBLEN=>NULL ()
CHARACTER (LEN=4), POINTER::CTURBDIM=>NULL ()
LOGICAL, POINTER::LTURB_FLX=>NULL ()
LOGICAL, POINTER::LTURB_DIAG=>NULL ()
LOGICAL, POINTER::LSIG_CONV=>NULL ()
LOGICAL, POINTER::LRMC01=>NULL ()
LOGICAL, POINTER::LHARAT=>NULL ()
LOGICAL, POINTER::LBL89TOP=>NULL ()
CHARACTER (LEN=4), POINTER::CTOM=>NULL ()
REAL, DIMENSION (:,:), POINTER::XBL_DEPTH=>NULL ()
REAL, DIMENSION (:,:), POINTER::XSBL_DEPTH=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XWTHVMF=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XDYP=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XTHP=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XTR=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XDISS=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XLEM=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XSSUFL_C=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XSSVFL_C=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XSSTFL_C=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XSSRFL_C=>NULL ()
LOGICAL, POINTER::LLEONARD=>NULL ()
REAL, POINTER::XCOEFHGRADTHL=>NULL ()
REAL, POINTER::XCOEFHGRADRM=>NULL ()
REAL, POINTER::XALTHGRAD=>NULL ()
LOGICAL, POINTER::LGOGER=>NULL ()
REAL, POINTER::XSMAG=>NULL ()
REAL, POINTER::XCLDTHOLD=>NULL ()
REAL, POINTER::XLINI=>NULL ()
LOGICAL, POINTER::LROTATE_WIND=>NULL ()
LOGICAL, POINTER::LTKEMINTURB=>NULL ()
LOGICAL, POINTER::LPROJQITURB=>NULL ()
LOGICAL, POINTER::LSMOOTH_PRANDTL=>NULL ()
REAL, POINTER::XMINSIGS=>NULL ()
REAL, POINTER::XBL89EXP=>NULL (), XUSRBL89=>NULL ()
NAMELIST/NAM_TURBN/XIMPL, CTURBLEN, CTURBDIM, LTURB_FLX, LTURB_DIAG, LSIG_CONV, LRMC01, CTOM&
&, XTKEMIN, XCED, XCTP, XCADAP, LLEONARD, XCOEFHGRADTHL, XCOEFHGRADRM, XALTHGRAD, LGOGER,&
& XSMAG, XCLDTHOLD, XLINI, LHARAT, LPROJQITURB, LSMOOTH_PRANDTL, XMINSIGS, LBL89TOP

INTERFACE
  
  
  
  
  
  
  
ENDINTERFACE

CONTAINS


ENDMODULE MODD_TURB_N
