
MODULE MODD_PARAM_MFSHALL_N
USE MODD_PARAMETERS,ONLY:JPMODELMAX

IMPLICIT NONE


TYPE PARAM_MFSHALL_T
  REAL::XIMPL_MF
  CHARACTER (LEN=4)::CMF_UPDRAFT
  CHARACTER (LEN=4)::CMF_CLOUD
  CHARACTER (LEN=4)::CWET_MIXING
  CHARACTER (LEN=4)::CKIC_COMPUTE
  CHARACTER (LEN=4)::CDETR_DRY_LUP
  LOGICAL::LMIXUV
  LOGICAL::LMIXTKE
  LOGICAL::LMF_FLX
  REAL::XALP_PERT
  REAL::XABUO
  REAL::XBENTR
  REAL::XBDETR
  REAL::XCMF
  REAL::XENTR_MF
  REAL::XCRAD_MF
  REAL::XENTR_DRY
  REAL::XDETR_DRY
  REAL::XDETR_LUP
  REAL::XKCF_MF
  REAL::XKRC_MF
  REAL::XTAUSIGMF
  REAL::XPRES_UV
  REAL::XALPHA_MF
  REAL::XSIGMA_MF
  REAL::XSIGMA_ENV
  REAL::XFRAC_UP_MAX
  REAL::XA1
  REAL::XB
  REAL::XC
  REAL::XBETA1
  REAL::XR
  LOGICAL::LGZ
  REAL::XGZ
  LOGICAL::LTHETAS_MF
  REAL::XLAMBDA_MF
  LOGICAL::LVERLIMUP
  LOGICAL::LPZ_EXP_LOG
  REAL::XBRIO
  REAL::XAADVEC
  LOGICAL::LRELAX_ALPHA_MF
ENDTYPE PARAM_MFSHALL_T

TYPE (PARAM_MFSHALL_T), DIMENSION (JPMODELMAX), TARGET, SAVE::PARAM_MFSHALL_MODEL
TYPE (PARAM_MFSHALL_T), POINTER, SAVE::PARAM_MFSHALLN=>NULL ()
REAL, POINTER::XIMPL_MF=>NULL ()
CHARACTER (LEN=4), POINTER::CMF_UPDRAFT=>NULL ()
CHARACTER (LEN=4), POINTER::CMF_CLOUD=>NULL ()
CHARACTER (LEN=4), POINTER::CWET_MIXING=>NULL ()
CHARACTER (LEN=4), POINTER::CKIC_COMPUTE=>NULL ()
CHARACTER (LEN=4), POINTER::CDETR_DRY_LUP=>NULL ()
LOGICAL, POINTER::LMIXUV=>NULL ()
LOGICAL, POINTER::LMIXTKE=>NULL ()
LOGICAL, POINTER::LMF_FLX=>NULL ()
REAL, POINTER::XALP_PERT=>NULL ()
REAL, POINTER::XABUO=>NULL ()
REAL, POINTER::XBENTR=>NULL ()
REAL, POINTER::XBDETR=>NULL ()
REAL, POINTER::XCMF=>NULL ()
REAL, POINTER::XENTR_MF=>NULL ()
REAL, POINTER::XCRAD_MF=>NULL ()
REAL, POINTER::XENTR_DRY=>NULL ()
REAL, POINTER::XDETR_DRY=>NULL ()
REAL, POINTER::XDETR_LUP=>NULL ()
REAL, POINTER::XKCF_MF=>NULL ()
REAL, POINTER::XKRC_MF=>NULL ()
REAL, POINTER::XTAUSIGMF=>NULL ()
REAL, POINTER::XPRES_UV=>NULL ()
REAL, POINTER::XALPHA_MF=>NULL ()
REAL, POINTER::XSIGMA_MF=>NULL ()
REAL, POINTER::XSIGMA_ENV=>NULL ()
REAL, POINTER::XFRAC_UP_MAX=>NULL ()
REAL, POINTER::XA1=>NULL ()
REAL, POINTER::XB=>NULL ()
REAL, POINTER::XC=>NULL ()
REAL, POINTER::XBETA1=>NULL ()
REAL, POINTER::XR=>NULL ()
LOGICAL, POINTER::LTHETAS_MF=>NULL ()
REAL, POINTER::XLAMBDA_MF=>NULL ()
LOGICAL, POINTER::LGZ=>NULL ()
REAL, POINTER::XGZ=>NULL ()
LOGICAL, POINTER::LVERLIMUP=>NULL ()
LOGICAL, POINTER::LPZ_EXP_LOG=>NULL ()
REAL, POINTER::XBRIO=>NULL ()
REAL, POINTER::XAADVEC=>NULL ()
LOGICAL, POINTER::LRELAX_ALPHA_MF=>NULL ()
NAMELIST/NAM_PARAM_MFSHALLN/XIMPL_MF, CMF_UPDRAFT, CMF_CLOUD, CWET_MIXING, LMIXUV, LMIXTKE&
&, LMF_FLX, XALP_PERT, XABUO, XBENTR, XBDETR, XCMF, XENTR_MF, XCRAD_MF, XENTR_DRY, XDETR_DRY&
&, XDETR_LUP, XKCF_MF, XKRC_MF, XTAUSIGMF, XPRES_UV, XALPHA_MF, XSIGMA_MF, XSIGMA_ENV&
&, XFRAC_UP_MAX, XA1, XB, XC, XBETA1, XR, LTHETAS_MF, LGZ, XGZ, LVERLIMUP, LPZ_EXP_LOG&
&, CKIC_COMPUTE, CDETR_DRY_LUP, XBRIO, XAADVEC, LRELAX_ALPHA_MF
CONTAINS


ENDMODULE MODD_PARAM_MFSHALL_N
