
MODULE MODD_NEB_N
USE MODD_PARAMETERS,ONLY:JPMODELMAX

IMPLICIT NONE


TYPE NEB_T
  REAL::XTMINMIX
  REAL::XTMAXMIX
  LOGICAL::LHGT_QS
  CHARACTER (LEN=1)::CFRAC_ICE_ADJUST
  CHARACTER (LEN=1)::CFRAC_ICE_SHALLOW_MF
  REAL::VSIGQSAT
  CHARACTER (LEN=80)::CCONDENS
  CHARACTER (LEN=4)::CLAMBDA3
  LOGICAL::LSTATNW
  LOGICAL::LSIGMAS
  LOGICAL::LSUBG_COND
  LOGICAL::LCONDBORN
ENDTYPE NEB_T

TYPE (NEB_T), DIMENSION (JPMODELMAX), SAVE, TARGET::NEB_MODEL
TYPE (NEB_T), POINTER, SAVE::NEBN=>NULL ()
REAL, POINTER::XTMINMIX=>NULL (), XTMAXMIX=>NULL ()
LOGICAL, POINTER::LHGT_QS=>NULL ()
CHARACTER (LEN=1), POINTER::CFRAC_ICE_ADJUST=>NULL ()
CHARACTER (LEN=1), POINTER::CFRAC_ICE_SHALLOW_MF=>NULL ()
REAL, POINTER::VSIGQSAT=>NULL ()
CHARACTER (LEN=80), POINTER::CCONDENS=>NULL ()
CHARACTER (LEN=4), POINTER::CLAMBDA3=>NULL ()
LOGICAL, POINTER::LSTATNW=>NULL ()
LOGICAL, POINTER::LSIGMAS=>NULL ()
LOGICAL, POINTER::LSUBG_COND=>NULL ()
LOGICAL, POINTER::LCONDBORN=>NULL ()
NAMELIST/NAM_NEBN/XTMINMIX, XTMAXMIX, LHGT_QS, CFRAC_ICE_ADJUST, CFRAC_ICE_SHALLOW_MF&
&, VSIGQSAT, CCONDENS, CLAMBDA3, LSTATNW, LSIGMAS, LSUBG_COND, LCONDBORN
CONTAINS


ENDMODULE MODD_NEB_N
