
MODULE MODD_PARAM_LIMA
USE MODD_PARAMETERS,ONLY:JPLIMACCNMAX, JPLIMAIFNMAX, NNBCRYSTALMAX

IMPLICIT NONE


TYPE PARAM_LIMA_T
  LOGICAL::LLIMA_DIAG
  LOGICAL::LPTSPLIT
  LOGICAL::LFEEDBACKT
  INTEGER::NMAXITER
  REAL::XMRSTEP
  REAL::XTSTEP_TS
  LOGICAL::LNUCL
  LOGICAL::LSEDI
  LOGICAL::LHHONI
  LOGICAL::LMEYERS
  LOGICAL::LCIBU
  LOGICAL::LRDSF
  LOGICAL::LCRYSTAL_SHAPE
  LOGICAL::LICE_ISC
  INTEGER::NMOM_I
  INTEGER::NMOM_S
  INTEGER::NMOM_G
  INTEGER::NMOM_H
  INTEGER::NMOD_IFN
  REAL, DIMENSION (JPLIMAIFNMAX)::XIFN_CONC
  LOGICAL::LIFN_HOM
  CHARACTER (LEN=8)::CIFN_SPECIES
  CHARACTER (LEN=8)::CINT_MIXING
  INTEGER::NMOD_IMM
  INTEGER::NIND_SPECIE
  INTEGER, DIMENSION (:), ALLOCATABLE::NIMM
  INTEGER, DIMENSION (:), ALLOCATABLE::NINDICE_CCN_IMM
  INTEGER::NSPECIE
  REAL, DIMENSION (:), ALLOCATABLE::XMDIAM_IFN
  REAL, DIMENSION (:), ALLOCATABLE::XSIGMA_IFN
  REAL, DIMENSION (:), ALLOCATABLE::XRHO_IFN
  REAL, DIMENSION (:,:), ALLOCATABLE::XFRAC
  REAL, DIMENSION (:), ALLOCATABLE::XFRAC_REF
  REAL, DIMENSION (:), ALLOCATABLE::XGINC_IFN
  LOGICAL::LSNOW_T
  LOGICAL::LMURAKAMI
  CHARACTER (LEN=4)::CPRISTINE_ICE_LIMA
  CHARACTER (LEN=4)::CHEVRIMED_ICE_LIMA
  REAL::XALPHAI, XNUI, XALPHAS, XNUS, XALPHAG, XNUG
  INTEGER::NNB_CRYSTAL_SHAPE
  CHARACTER (LEN=4), DIMENSION (NNBCRYSTALMAX)::HTYPE_CRYSTAL_SHAPE
  LOGICAL::LSIGMOIDE_G, LSIGMOIDE_NG
  REAL::XSIGMOIDE_G, XMVDMIN_G
  INTEGER::NPHILLIPS
  REAL, DIMENSION (4)::XT0
  REAL, DIMENSION (4)::XDT0
  REAL, DIMENSION (4)::XDSI0
  REAL::XSW0
  REAL::XRHO_CFDC
  REAL, DIMENSION (4)::XH
  REAL, DIMENSION (4)::XAREA1
  REAL::XGAMMA
  REAL, DIMENSION (4)::XTX1
  REAL, DIMENSION (4)::XTX2
  REAL, DIMENSION (:), ALLOCATABLE::XABSCISS, XWEIGHT
  INTEGER::NDIAM
  REAL::XFACTNUC_DEP, XFACTNUC_CON
  REAL::XNDEBRIS_CIBU
  REAL::XPSH_MAX_RDSF
  LOGICAL::LACTI
  LOGICAL::LSEDC
  LOGICAL::LACTIT
  LOGICAL::LDEPOC
  LOGICAL::LACTTKE
  LOGICAL::LADJ
  LOGICAL::LSPRO
  LOGICAL::LKHKO
  LOGICAL::LKESSLERAC
  INTEGER::NMOM_C
  INTEGER::NMOM_R
  INTEGER::NMOD_CCN
  REAL, DIMENSION (JPLIMACCNMAX)::XCCN_CONC
  LOGICAL::LCCN_HOM
  CHARACTER (LEN=8)::CCCN_MODES
  REAL, DIMENSION (:), ALLOCATABLE::XR_MEAN_CCN, XLOGSIG_CCN, XRHO_CCN
  REAL, DIMENSION (:), ALLOCATABLE::XKHEN_MULTI, XMUHEN_MULTI, XBETAHEN_MULTI, XGMULTI
  REAL, DIMENSION (:,:,:), ALLOCATABLE::XCONC_CCN_TOT
  REAL, DIMENSION (:), ALLOCATABLE::XLIMIT_FACTOR
  REAL::XALPHAR, XNUR, XALPHAC, XNUC
  CHARACTER (LEN=3)::HPARAM_CCN='CPB'
  CHARACTER (LEN=3)::HINI_CCN
  CHARACTER (LEN=10), DIMENSION (JPLIMACCNMAX)::HTYPE_CCN
  REAL::XFSOLUB_CCN, XACTEMP_CCN, XAERDIFF, XAERHEIGHT
  REAL::XVDEPOC
  LOGICAL::LSCAV
  LOGICAL::LAERO_MASS
  INTEGER::NDIAMR=20
  INTEGER::NDIAMP=20
  REAL::XT0SCAV=293.15
  REAL::XTREF=273.15
  REAL::XNDO=8.*1.0E6
  REAL::XMUA0=1.711E-05
  REAL::XT_SUTH_A=110.4
  REAL::XMFPA0=6.6E-08
  REAL::XVISCW=1.0E-3
  REAL::XRHO00=1.2041
  REAL::XCEXVT
  REAL, DIMENSION (:), ALLOCATABLE::XRTMIN
  REAL, DIMENSION (:), ALLOCATABLE::XCTMIN
  INTEGER, DIMENSION (7)::NSPLITSED
  REAL, DIMENSION (7)::XLB
  REAL, DIMENSION (7)::XLBEX
  REAL, DIMENSION (7)::XD
  REAL, DIMENSION (7)::XFSEDR
  REAL, DIMENSION (7)::XFSEDC
ENDTYPE PARAM_LIMA_T

TYPE (PARAM_LIMA_T), TARGET, SAVE::PARAM_LIMA
LOGICAL, POINTER::LLIMA_DIAG=>NULL (), LPTSPLIT=>NULL (), LFEEDBACKT=>NULL (), LNUCL=>NULL&
& (), LSEDI=>NULL (), LHHONI=>NULL (), LMEYERS=>NULL (), LCIBU=>NULL (), LRDSF=>NULL (), LCRYSTAL_SHAPE&
&=>NULL (), LICE_ISC=>NULL (), LIFN_HOM=>NULL (), LSNOW_T=>NULL (), LMURAKAMI=>NULL (), LACTI&
&=>NULL (), LSEDC=>NULL (), LACTIT=>NULL (), LDEPOC=>NULL (), LACTTKE=>NULL (), LADJ=>NULL&
& (), LSPRO=>NULL (), LKHKO=>NULL (), LKESSLERAC=>NULL (), LCCN_HOM=>NULL (), LSCAV=>NULL &
&(), LAERO_MASS=>NULL (), LSIGMOIDE_G=>NULL (), LSIGMOIDE_NG=>NULL ()
INTEGER, POINTER::NMAXITER=>NULL (), NMOM_I=>NULL (), NMOM_S=>NULL (), NMOM_G=>NULL (&
&), NMOM_H=>NULL (), NNB_CRYSTAL_SHAPE=>NULL (), NMOD_IFN=>NULL (), NMOD_IMM=>NULL ()&
&, NIND_SPECIE=>NULL (), NSPECIE=>NULL (), NPHILLIPS=>NULL (), NDIAM=>NULL (), NMOM_C&
&=>NULL (), NMOM_R=>NULL (), NMOD_CCN=>NULL (), NDIAMR=>NULL (), NDIAMP=>NULL ()
CHARACTER (LEN=4), DIMENSION (:), POINTER::HTYPE_CRYSTAL_SHAPE
REAL, POINTER::XMRSTEP=>NULL (), XTSTEP_TS=>NULL (), XALPHAI=>NULL (), XNUI=>NULL (), XALPHAS=>NULL&
& (), XNUS=>NULL (), XALPHAG=>NULL (), XNUG=>NULL (), XSW0=>NULL (), XRHO_CFDC=>NULL (), XGAMMA=&
&>NULL (), XFACTNUC_DEP=>NULL (), XFACTNUC_CON=>NULL (), XNDEBRIS_CIBU=>NULL (), XPSH_MAX_RDSF=>NULL&
& (), XALPHAR=>NULL (), XNUR=>NULL (), XALPHAC=>NULL (), XNUC=>NULL (), XFSOLUB_CCN=>NULL (), XACTEMP_CCN&
&=>NULL (), XAERDIFF=>NULL (), XAERHEIGHT=>NULL (), XVDEPOC=>NULL (), XT0SCAV=>NULL (), XTREF=>NULL&
& (), XNDO=>NULL (), XMUA0=>NULL (), XT_SUTH_A=>NULL (), XMFPA0=>NULL (), XVISCW=>NULL (), XRHO00&
&=>NULL (), XCEXVT=>NULL (), XSIGMOIDE_G=>NULL (), XMVDMIN_G=>NULL ()
REAL, DIMENSION (:), POINTER::XIFN_CONC=>NULL (), XMDIAM_IFN=>NULL (), XSIGMA_IFN=>NULL (), XGINC_IFN&
&=>NULL (), XRHO_IFN=>NULL (), XFRAC_REF=>NULL (), XT0=>NULL (), XDT0=>NULL (), XDSI0=>NULL (), XH=>NULL&
& (), XAREA1=>NULL (), XTX1=>NULL (), XTX2=>NULL (), XABSCISS=>NULL (), XWEIGHT=>NULL (), XCCN_CONC=>NULL&
& (), XR_MEAN_CCN=>NULL (), XLOGSIG_CCN=>NULL (), XRHO_CCN=>NULL (), XKHEN_MULTI=>NULL (), XMUHEN_MULTI&
&=>NULL (), XBETAHEN_MULTI=>NULL (), XLIMIT_FACTOR=>NULL (), XGMULTI=>NULL (), XRTMIN=>NULL (), XCTMIN&
&=>NULL (), XLB=>NULL (), XLBEX=>NULL (), XD=>NULL (), XFSEDR=>NULL (), XFSEDC=>NULL ()
REAL, DIMENSION (:,:), POINTER::XFRAC=>NULL ()
REAL, DIMENSION (:,:,:), POINTER::XCONC_CCN_TOT=>NULL ()
INTEGER, DIMENSION (:), POINTER::NIMM=>NULL (), NINDICE_CCN_IMM=>NULL (), NSPLITSED=>NULL ()
CHARACTER (LEN=8), POINTER::CIFN_SPECIES=>NULL ()
CHARACTER (LEN=8), POINTER::CINT_MIXING=>NULL ()
CHARACTER (LEN=4), POINTER::CPRISTINE_ICE_LIMA=>NULL ()
CHARACTER (LEN=4), POINTER::CHEVRIMED_ICE_LIMA=>NULL ()
CHARACTER (LEN=8), POINTER::CCCN_MODES=>NULL ()
CHARACTER (LEN=3), POINTER::HPARAM_CCN=>NULL ()
CHARACTER (LEN=3), POINTER::HINI_CCN=>NULL ()
CHARACTER (LEN=10), DIMENSION (:), POINTER::HTYPE_CCN
NAMELIST/NAM_PARAM_LIMA/LNUCL, LSEDI, LHHONI, LMEYERS, NMOM_I, NMOM_S, NMOM_G, NMOM_H, NMOD_IFN&
&, XIFN_CONC, LIFN_HOM, CIFN_SPECIES, CINT_MIXING, NMOD_IMM, NIND_SPECIE, LSNOW_T, CPRISTINE_ICE_LIMA&
&, CHEVRIMED_ICE_LIMA, XFACTNUC_DEP, XFACTNUC_CON, NPHILLIPS, LCIBU, XNDEBRIS_CIBU, LRDSF, XPSH_MAX_RDSF&
&, LMURAKAMI, LCRYSTAL_SHAPE, NNB_CRYSTAL_SHAPE, HTYPE_CRYSTAL_SHAPE, LICE_ISC, LACTI, LSEDC,&
& LACTIT, LSPRO, LADJ, LKHKO, LKESSLERAC, NMOM_C, NMOM_R, NMOD_CCN, XCCN_CONC, LCCN_HOM, CCCN_MODES&
&, HINI_CCN, HTYPE_CCN, XALPHAC, XNUC, XALPHAR, XNUR, XFSOLUB_CCN, XACTEMP_CCN, XAERDIFF, XAERHEIGHT&
&, LSCAV, LAERO_MASS, LDEPOC, XVDEPOC, LACTTKE, LPTSPLIT, LFEEDBACKT, NMAXITER, XMRSTEP, XTSTEP_TS&
&, LSIGMOIDE_NG, LSIGMOIDE_G, XSIGMOIDE_G, XMVDMIN_G
CONTAINS




ENDMODULE MODD_PARAM_LIMA
