
MODULE MODEL_PHYSICS_ECMWF_MOD
USE YOEPHY,ONLY:TEPHY
USE YOECLD,ONLY:TECLD
USE YOECLDP,ONLY:TECLDP
USE YOECND,ONLY:TECND
USE YOECUMF,ONLY:TECUMF
USE YOE_CUCONVCA,ONLY:TECUCONVCA
USE YOEGWD,ONLY:TEGWD
USE YOEGWWMS,ONLY:TEGWWMS
USE YOETHF,ONLY:TTHF

IMPLICIT NONE


TYPE MODEL_PHYSICS_ECMWF_TYPE
  TYPE (TEPHY)::YREPHY
  TYPE (TECLD)::YRECLD
  TYPE (TECLDP)::YRECLDP
  TYPE (TECND)::YRECND
  TYPE (TECUMF)::YRECUMF
  TYPE (TECUCONVCA)::YRECUCONVCA
  TYPE (TEGWD)::YREGWD
  TYPE (TEGWWMS)::YREGWWMS
  TYPE (TTHF)::YRTHF
  
ENDTYPE MODEL_PHYSICS_ECMWF_TYPE

CONTAINS

ENDMODULE MODEL_PHYSICS_ECMWF_MOD
