MODULE MODEL_PHYSICS_SCM_MOD

  USE PARKIND1, ONLY: JPIM, JPRB

  IMPLICIT NONE

  INTEGER(KIND=JPIM), PARAMETER :: NPNPST=240

  TYPE MODEL_PHYSICS_SCM_TYPE

    LOGICAL :: LGSCM
    INTEGER(KIND=JPIM) :: NFRSCM
    INTEGER(KIND=JPIM) :: NSCMTS(0:NPNPST)
    INTEGER(KIND=JPIM) :: NSCM_SPACE_S
    REAL(KIND=JPRB) :: GSCM_LON1
    REAL(KIND=JPRB) :: GSCM_LON2
    REAL(KIND=JPRB) :: GSCM_LAT1
    REAL(KIND=JPRB) :: GSCM_LAT2
    REAL(KIND=JPRB) :: GSCM_RADIUS
    INTEGER(KIND=JPIM) :: NSCM_ADD_SAMPL

  END TYPE MODEL_PHYSICS_SCM_TYPE

END MODULE MODEL_PHYSICS_SCM_MOD
