MODULE MODEL_PHYSICS_GENERAL_MOD
USE YOMDPHY,ONLY:TDPHY
USE YOMSLPHY,ONLY:TSLPHY
USE YOEVDF,ONLY:TVDF

IMPLICIT NONE


TYPE MODEL_PHYSICS_GENERAL_TYPE
  TYPE (TDPHY)::YRDPHY
  TYPE (TSLPHY)::YRSLPHY
  TYPE (TVDF)::YRVDF
  
ENDTYPE MODEL_PHYSICS_GENERAL_TYPE

CONTAINS

ENDMODULE MODEL_PHYSICS_GENERAL_MOD
