MODULE MODEL_PHYSICS_SIMPLINEAR_MOD
USE YOEPHLI,ONLY:TEPHLI
USE YOMCUMFS,ONLY:TCUMFS
USE YOEGWDWMS,ONLY:TEGWDWMS
USE YOECUMF2,ONLY:TECUMF2
USE YOPHLC,ONLY:TPHLC
USE YOPHNC,ONLY:TPHNC
USE YOMNCL,ONLY:TNCL
USE YOMSRFTLAD,ONLY:TSRFTLAD
USE YOMSPHYHIST,ONLY:SPHYS_HIST_TYPE

IMPLICIT NONE


TYPE MODEL_PHYSICS_SIMPLINEAR_TYPE
  TYPE (TEPHLI)::YREPHLI
  TYPE (TCUMFS)::YRCUMFS
  TYPE (TEGWDWMS)::YREGWDWMS
  TYPE (TECUMF2)::YRECUMF2
  TYPE (TPHLC)::YRPHLC
  TYPE (TPHNC)::YRPHNC
  TYPE (TNCL)::YRNCL
  TYPE (TSRFTLAD)::YRSRFTLAD
  TYPE (SPHYS_HIST_TYPE), POINTER::GPHIST (:)=>NULL ()
  
ENDTYPE MODEL_PHYSICS_SIMPLINEAR_TYPE

CONTAINS

ENDMODULE MODEL_PHYSICS_SIMPLINEAR_MOD
