MODULE MODEL_CHEM_MOD

!$ACDC methods 

  USE YOMOZO  , ONLY : TOZO
  USE YOMCHEM , ONLY : TCHEM
  USE YOMCOMPO, ONLY : TCOMPO
  USE DRYDEP_PAR, ONLY : TDRYDEP
  IMPLICIT NONE

  TYPE MODEL_CHEM_TYPE

    TYPE(TOZO)   :: YROZO
    TYPE(TCHEM)  :: YRCHEM
    TYPE(TCOMPO) :: YRCOMPO
    TYPE(TDRYDEP) :: YRDRYDEP

    CONTAINS


  END TYPE MODEL_CHEM_TYPE

  !---------------------------------------------------------------------

  CONTAINS 

  SUBROUTINE PRINT_CONFIGURATION(SELF, KDEPTH, KOUTNO)
  IMPLICIT NONE
  CLASS(MODEL_CHEM_TYPE), INTENT(IN) :: SELF
  INTEGER               , INTENT(IN) :: KDEPTH
  INTEGER               , INTENT(IN) :: KOUTNO

  WRITE(KOUTNO,*) REPEAT(' ',KDEPTH) // 'model%yrml_phy_chem : not yet printable'

  END SUBROUTINE PRINT_CONFIGURATION

END MODULE MODEL_CHEM_MOD
