MODULE MODEL_DYNAMICS_MOD
USE YOMDYNA,ONLY:TDYNA
USE YOMDYN,ONLY:TDYN
USE YEMDYN,ONLY:TEDYN
USE SPNG_MOD,ONLY:TSPNG
USE PTRGPPC,ONLY:TPTRGPPC
USE INTDYNSL_MOD,ONLY:TLSCAW, TRSCAW, TSCO, TCCO
USE YOMSLINT,ONLY:TSLINT
USE YOMSLREP,ONLY:TSLREP
USE PTRSLB1,ONLY:TPTRSLB1
USE PTRSLB2,ONLY:TPTRSLB2
USE PTRSLB15,ONLY:TPTRSLB15
USE YOMTNH,ONLY:TTNH
USE EINT_MOD,ONLY:SL_STRUCT
#ifdef WITH_MGRIDS
USE MGRIDS_ADVECTION_MODULE,ONLY:MGRIDS_ADVECTION
#endif

IMPLICIT NONE




TYPE MODEL_DYNAMICS_TYPE
  	
  	TYPE (TDYNA)::YRDYNA
  	TYPE (TDYN)::YRDYN
  	TYPE (TEDYN)::YREDYN
  	TYPE (TSPNG)::YRSPNG
  	
  	TYPE (TPTRGPPC)::YRPTRGPPC
  	
  	TYPE (TLSCAW)::YYTLSCAW, YYTLSCAWH
  	TYPE (TRSCAW)::YYTRSCAW, YYTRSCAWH
  	TYPE (TSCO)::YYTSCO
  	TYPE (TCCO)::YYTCCO
  	TYPE (TSLREP)::YRSLREP
  	TYPE (TSLINT)::YRSLINT
  	TYPE (TPTRSLB1)::YRPTRSLB1
  	TYPE (TPTRSLB2)::YRPTRSLB2
  	TYPE (TPTRSLB15)::YRPTRSLB15
  	TYPE (TTNH)::YRTNH
  	
  	TYPE (SL_STRUCT)::YRSL
  	TYPE (SL_STRUCT)::YRAD
#ifdef WITH_MGRIDS
  TYPE (MGRIDS_ADVECTION)::YR_MGRIDS_ADVECTION
#endif
  
  
ENDTYPE MODEL_DYNAMICS_TYPE

CONTAINS

ENDMODULE MODEL_DYNAMICS_MOD
