
MODULE MODEL_PHYSICS_STOCHAST_MOD
USE STOPH_MIX,ONLY:TSTOPH
USE YOMRANDOM_STREAMS,ONLY:TRANDOM_STREAMS
USE YOMPERTPAR,ONLY:TPERTPAR

IMPLICIT NONE


TYPE MODEL_PHYSICS_STOCHAST_TYPE
  TYPE (TPERTPAR)::YRPERTPAR
  TYPE (TSTOPH)::YRSTOPH
  TYPE (TRANDOM_STREAMS)::YR_RANDOM_STREAMS
  
ENDTYPE MODEL_PHYSICS_STOCHAST_TYPE

CONTAINS

ENDMODULE MODEL_PHYSICS_STOCHAST_MOD
