MODULE MODEL_ATMOS_OCEAN_COUPLING_MOD

!$ACDC methods 

  USE YOMMCC, ONLY : TMCC
  USE YOMCOM, ONLY : TCOM
  USE YOMCOU, ONLY : TCOU
  IMPLICIT NONE

  TYPE MODEL_ATMOS_OCEAN_COUPLING_TYPE

    TYPE(TMCC)  :: YRMCC
    TYPE(TCOM)  :: YRCOM
    TYPE(TCOU)  :: YRCOU

    
  END TYPE MODEL_ATMOS_OCEAN_COUPLING_TYPE

END MODULE MODEL_ATMOS_OCEAN_COUPLING_MOD
