
MODULE MODEL_PHYSICS_AEROSOL_MOD
USE YOEAERLID,ONLY:TEAERLID
USE YOEAERMAP,ONLY:TEAERMAP
USE YOEAERSNK,ONLY:TEAERSNK
USE YOEAERSRC,ONLY:TEAERSRC
USE YOEAERVOL,ONLY:TEAERVOL
USE YOEDBUG,ONLY:TEDBUG

IMPLICIT NONE


TYPE MODEL_PHYSICS_AEROSOL_TYPE
  TYPE (TEAERLID)::YREAERLID
  TYPE (TEAERMAP)::YREAERMAP
  TYPE (TEAERSNK)::YREAERSNK
  TYPE (TEAERSRC)::YREAERSRC
  TYPE (TEAERVOL)::YREAERVOL
  TYPE (TEDBUG)::YREDBUG
  
ENDTYPE MODEL_PHYSICS_AEROSOL_TYPE

CONTAINS

ENDMODULE MODEL_PHYSICS_AEROSOL_MOD
