
MODULE MODEL_GENERAL_CONF_MOD
USE TYPE_GEOMETRY,ONLY:GEOMETRY
USE YOMDIMF,ONLY:TDIMF
USE YOM_YGFL,ONLY:TYPE_GFLD
USE YOMRIP,ONLY:TRIP
USE YOMMODERRMOD,ONLY:TMODERR
USE YOMSPSDT,ONLY:TSPPT_CONFIG
USE SPP_MOD,ONLY:TSPP_CONFIG
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE


TYPE MODEL_GENERAL_CONF_TYPE
  TYPE (GEOMETRY), POINTER::GEOM=>NULL ()
  TYPE (TDIMF)::YRDIMF
  TYPE (TYPE_GFLD)::YGFL
  TYPE (TRIP)::YRRIP
  TYPE (TMODERR)::YRMODERR
  TYPE (TSPPT_CONFIG)::YRSPPT_CONFIG
  TYPE (TSPP_CONFIG)::YRSPP_CONFIG
  
ENDTYPE MODEL_GENERAL_CONF_TYPE

CONTAINS

ENDMODULE MODEL_GENERAL_CONF_MOD
