
MODULE MODEL_PHYSICS_RADIATION_MOD
USE YOERAD,ONLY:TERAD
USE YOESW,ONLY:TESWRT
USE YOEOVLP,ONLY:TEOVLP
USE YOENEUR,ONLY:TENEUR
USE YOELWRAD,ONLY:TELWRAD
USE YOEAERD,ONLY:TEAERD
USE YOEAERATM,ONLY:TEAERATM
USE YOE_UVRAD,ONLY:TEUVRAD
USE YOERDI,ONLY:TERDI
USE YOE_MCICA,ONLY:TEMCICA
USE YOMRCOEF,ONLY:TRCOEF
USE YOMPRAD,ONLY:RADIATION_GRID_STRUCT
USE YOMGSGEOM,ONLY:TGSGEOM
USE YOERIP,ONLY:TERIP
USE YOERADIATION,ONLY:TRADIATION
USE EINT_MOD,ONLY:SL_STRUCT
USE PARKIND1,ONLY:JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE


TYPE MODEL_PHYSICS_RADIATION_TYPE
  TYPE (TERAD)::YRERAD
  TYPE (TESWRT)::YRESWRT
  TYPE (TEOVLP)::YREOVLP
  TYPE (TENEUR)::YRENEUR
  TYPE (TELWRAD)::YRELWRAD
  TYPE (TEAERD)::YREAERD
  TYPE (TEAERATM)::YREAERATM
  TYPE (TEUVRAD)::YREUVRAD
  TYPE (TERDI)::YRERDI
  TYPE (TEMCICA)::YREMCICA
  TYPE (TRCOEF)::YRRCOEF
  TYPE (RADIATION_GRID_STRUCT)::RADGRID
  TYPE (TGSGEOM), POINTER::YRAD_GSGEOM (:)=>NULL ()
  TYPE (TERIP)::YRERIP
  TYPE (TRADIATION)::YRADIATION
  TYPE (SL_STRUCT)::YRRI
  TYPE (SL_STRUCT)::YRRO
  
ENDTYPE MODEL_PHYSICS_RADIATION_TYPE

CONTAINS

ENDMODULE MODEL_PHYSICS_RADIATION_MOD
