MODULE ORDER_INDEPENDENT_SUMMATION_MOD

! Dummy version for single column model

USE PARKIND1  ,ONLY : JPIM     ,JPRB

PUBLIC

!  single column model only needs ORDER_INDEP_GLOBAL_SUM

 CONTAINS

FUNCTION ORDER_INDEP_GLOBAL_SUM(PIN,KNG)

IMPLICIT NONE

REAL(KIND=JPRB) :: ORDER_INDEP_GLOBAL_SUM
REAL(KIND=JPRB), INTENT(IN) :: PIN(:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KNG

PRINT *,'DUMMY ORDER_INDEP_GLOBAL_SUM CALLED'
ORDER_INDEP_GLOBAL_SUM = SUM(PIN)

END FUNCTION

END MODULE
