INTERFACE
SUBROUTINE POSNAME(KULNAM,CDNAML,KSTAT,LDNOREWIND)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KULNAM
CHARACTER(LEN=*)  ,INTENT(IN)    :: CDNAML
INTEGER(KIND=JPIM),INTENT(OUT)   :: KSTAT
LOGICAL,OPTIONAL,  INTENT(IN)    :: LDNOREWIND
END SUBROUTINE POSNAME







END INTERFACE
