
MODULE RADIATION_CONFIG
USE PARKIND1,ONLY:JPRB
USE RADIATION_CLOUD_OPTICS_DATA,ONLY:CLOUD_OPTICS_TYPE
USE RADIATION_GENERAL_CLOUD_OPTICS_DATA,ONLY:GENERAL_CLOUD_OPTICS_TYPE
USE RADIATION_AEROSOL_OPTICS_DATA,ONLY:AEROSOL_OPTICS_TYPE
USE RADIATION_PDF_SAMPLER,ONLY:PDF_SAMPLER_TYPE
USE RADIATION_CLOUD_COVER,ONLY:OVERLAPNAME, IOVERLAPMAXIMUMRANDOM&
&, IOVERLAPEXPONENTIALRANDOM, IOVERLAPEXPONENTIAL
USE RADIATION_ECCKD,ONLY:CKD_MODEL_TYPE

IMPLICIT NONE



ENUM, BIND (C)
  ENUMERATOR ISOLVERCLOUDLESS, ISOLVERHOMOGENEOUS, ISOLVERMCICA, ISOLVERSPARTACUS, ISOLVERTRIPLECLOUDS
ENDENUM

CHARACTER (LEN=*), PARAMETER::SOLVERNAME (0:4)=(/'Cloudless   ',&
&'Homogeneous ','McICA       ','SPARTACUS   ','Tripleclouds'/)

ENUM, BIND (C)
  ENUMERATOR IENTRAPMENTZERO, IENTRAPMENTEDGEONLY, IENTRAPMENTEXPLICIT&
  &, IENTRAPMENTEXPLICITNONFRACTAL, IENTRAPMENTMAXIMUM
ENDENUM

CHARACTER (LEN=*), PARAMETER::ENTRAPMENTNAME (0:4)=['Zero      &
& ','Edge-only  ','Explicit   ','Non-fractal','Maximum    ']
CHARACTER (LEN=*), PARAMETER::ENCROACHMENTNAME (0:4)=['Zero&
&    ','Minimum ','Fractal ','Computed','Maximum ']

ENUM, BIND (C)
  ENUMERATOR IGASMODELMONOCHROMATIC, IGASMODELIFSRRTMG, IGASMODELECCKD
ENDENUM

CHARACTER (LEN=*), PARAMETER::GASMODELNAME (0:2)=(/'Monochromatic','RRTMG-IFS    ','ECCKD        '/)

ENUM, BIND (C)
  ENUMERATOR ILIQUIDMODELMONOCHROMATIC, ILIQUIDMODELSOCRATES, ILIQUIDMODELSLINGO&
  &, ILIQUIDMODELJAHANGIR, ILIQUIDMODELNIELSEN
ENDENUM

CHARACTER (LEN=*), PARAMETER::LIQUIDMODELNAME (0:4)=(/'Monochromatic'&
&,'SOCRATES     ','Slingo       ','Jahangir     ','Nielsen      '/)

ENUM, BIND (C)
  ENUMERATOR IICEMODELMONOCHROMATIC, IICEMODELFU, IICEMODELBARAN&
  &, IICEMODELBARAN2016, IICEMODELBARAN2017, IICEMODELYI
ENDENUM

CHARACTER (LEN=*), PARAMETER::ICEMODELNAME (0:5)=(/'Monochromatic','Fu-IFS  &
&     ','Baran        ','Baran2016    ','Baran2017    ','Yi           '/)

ENUM, BIND (C)
  ENUMERATOR IPDFSHAPELOGNORMAL, IPDFSHAPEGAMMA
ENDENUM

CHARACTER (LEN=*), PARAMETER::PDFSHAPENAME (0:1)=(/'Lognormal','Gamma    '/)
INTEGER, PARAMETER::NMAXAEROSOLTYPES=256
INTEGER, PARAMETER::NMAXCLOUDTYPES=12
INTEGER, PARAMETER::NMAXALBEDOINTERVALS=256
INTEGER, PARAMETER::NPRINTSTRINGLEN=60

TYPE CONFIG_TYPE
  LOGICAL::USE_SPECTRAL_SOLAR_SCALING=.FALSE.
  LOGICAL::USE_SPECTRAL_SOLAR_CYCLE=.FALSE.
  CHARACTER (LEN=511)::DIRECTORY_NAME='.'
  LOGICAL::USE_GENERAL_CLOUD_OPTICS=.TRUE.
  LOGICAL::USE_GENERAL_AEROSOL_OPTICS=.TRUE.
  REAL (JPRB)::CLOUD_FRACTION_THRESHOLD=1.0e-6_JPRB
  REAL (JPRB)::CLOUD_MIXING_RATIO_THRESHOLD=1.0e-9_JPRB
  INTEGER::I_OVERLAP_SCHEME=IOVERLAPEXPONENTIALRANDOM
  LOGICAL::USE_BETA_OVERLAP=.FALSE.
#ifdef __SX__
  LOGICAL::USE_VECTORIZABLE_GENERATOR=.TRUE.
#else
  LOGICAL::USE_VECTORIZABLE_GENERATOR=.FALSE.
#endif
  INTEGER::I_CLOUD_PDF_SHAPE=IPDFSHAPEGAMMA
  REAL (JPRB)::CLOUD_INHOM_DECORR_SCALING=0.5_JPRB
  REAL (JPRB)::CLEAR_TO_THICK_FRACTION=0.0_JPRB
  REAL (JPRB)::OVERHEAD_SUN_FACTOR=0.0_JPRB
  REAL (JPRB)::MIN_GAS_OD_LW=1.0e-15_JPRB
  REAL (JPRB)::MIN_GAS_OD_SW=0.0_JPRB
  REAL (JPRB)::MAX_GAS_OD_3D=8.0_JPRB
  REAL (JPRB)::MAX_CLOUD_OD=16.0_JPRB
  LOGICAL::DO_LW_CLOUD_SCATTERING=.TRUE.
  LOGICAL::DO_LW_AEROSOL_SCATTERING=.TRUE.
  INTEGER::NREGIONS=3
  INTEGER::I_SOLVER_SW=ISOLVERMCICA
  INTEGER::I_SOLVER_LW=ISOLVERMCICA
  LOGICAL::DO_SW_DELTA_SCALING_WITH_GASES=.FALSE.
  INTEGER::I_GAS_MODEL=IGASMODELIFSRRTMG
  REAL (JPRB)::MONO_LW_WAVELENGTH=-1.0_JPRB
  REAL (JPRB)::MONO_LW_TOTAL_OD=0.0_JPRB
  REAL (JPRB)::MONO_SW_TOTAL_OD=0.0_JPRB
  REAL (JPRB)::MONO_SW_SINGLE_SCATTERING_ALBEDO=0.999999_JPRB
  REAL (JPRB)::MONO_SW_ASYMMETRY_FACTOR=0.86_JPRB
  REAL (JPRB)::MONO_LW_SINGLE_SCATTERING_ALBEDO=0.538_JPRB
  REAL (JPRB)::MONO_LW_ASYMMETRY_FACTOR=0.925_JPRB
  INTEGER::I_LIQ_MODEL=ILIQUIDMODELSOCRATES
  INTEGER::I_ICE_MODEL=IICEMODELBARAN
  LOGICAL::DO_NEAREST_SPECTRAL_SW_ALBEDO=.FALSE.
  LOGICAL::DO_NEAREST_SPECTRAL_LW_EMISS=.FALSE.
  REAL (JPRB)::SW_ALBEDO_WAVELENGTH_BOUND (NMAXALBEDOINTERVALS-1)=-1.0_JPRB
  REAL (JPRB)::LW_EMISS_WAVELENGTH_BOUND (NMAXALBEDOINTERVALS-1)=-1.0_JPRB
  INTEGER::I_SW_ALBEDO_INDEX (NMAXALBEDOINTERVALS)=0
  INTEGER::I_LW_EMISS_INDEX (NMAXALBEDOINTERVALS)=0
  LOGICAL::DO_LW=.TRUE.
  LOGICAL::DO_SW=.TRUE.
  LOGICAL::DO_CLEAR=.TRUE.
  LOGICAL::DO_SW_DIRECT=.TRUE.
  LOGICAL::DO_3D_EFFECTS=.TRUE.
  CHARACTER (LEN=511)::CLOUD_TYPE_NAME (NMAXCLOUDTYPES)=["","","","","","","","","","","",""]
  LOGICAL::USE_THICK_CLOUD_SPECTRAL_AVERAGING (NMAXCLOUDTYPES)=[.TRUE.,.TRUE.&
  &,.TRUE.,.TRUE.,.TRUE.,.TRUE.,.TRUE.,.TRUE.,.TRUE.,.TRUE.,.TRUE.,.TRUE.]
  INTEGER::I_3D_SW_ENTRAPMENT=IENTRAPMENTEXPLICIT
  LOGICAL::DO_3D_LW_MULTILAYER_EFFECTS=.FALSE.
  LOGICAL::DO_LW_SIDE_EMISSIVITY=.TRUE.
  REAL (JPRB)::MAX_3D_TRANSFER_RATE=10.0_JPRB
  REAL (JPRB)::MIN_CLOUD_EFFECTIVE_SIZE=100.0_JPRB
  REAL (JPRB)::OVERHANG_FACTOR=0.0_JPRB
  LOGICAL::USE_EXPM_EVERYWHERE=.FALSE.
  LOGICAL::USE_AEROSOLS=.FALSE.
  INTEGER::N_AEROSOL_TYPES=0
  INTEGER::I_AEROSOL_TYPE_MAP (NMAXAEROSOLTYPES)
  LOGICAL::DO_SAVE_RADIATIVE_PROPERTIES=.FALSE.
  LOGICAL::DO_SAVE_SPECTRAL_FLUX=.FALSE.
  LOGICAL::DO_SURFACE_SW_SPECTRAL_FLUX=.TRUE.
  LOGICAL::DO_TOA_SPECTRAL_FLUX=.FALSE.
  LOGICAL::DO_LW_DERIVATIVES=.FALSE.
  LOGICAL::DO_SAVE_GPOINT_FLUX=.FALSE.
  LOGICAL::DO_SETUP_IFSRRTM=.TRUE.
  LOGICAL::DO_FU_LW_ICE_OPTICS_BUG=.FALSE.
  INTEGER::IVERBOSESETUP=2
  INTEGER::IVERBOSE=1
  LOGICAL::DO_CANOPY_FLUXES_SW=.FALSE.
  LOGICAL::DO_CANOPY_FLUXES_LW=.FALSE.
  LOGICAL::USE_CANOPY_FULL_SPECTRUM_SW=.FALSE.
  LOGICAL::USE_CANOPY_FULL_SPECTRUM_LW=.FALSE.
  LOGICAL::DO_CANOPY_GASES_SW=.FALSE.
  LOGICAL::DO_CANOPY_GASES_LW=.FALSE.
  CHARACTER (LEN=511)::ICE_OPTICS_OVERRIDE_FILE_NAME=''
  CHARACTER (LEN=511)::LIQ_OPTICS_OVERRIDE_FILE_NAME=''
  CHARACTER (LEN=511)::AEROSOL_OPTICS_OVERRIDE_FILE_NAME=''
  CHARACTER (LEN=511)::GAS_OPTICS_SW_OVERRIDE_FILE_NAME=''
  CHARACTER (LEN=511)::GAS_OPTICS_LW_OVERRIDE_FILE_NAME=''
  CHARACTER (LEN=511)::SSI_OVERRIDE_FILE_NAME=''
  LOGICAL::USE_UPDATED_SOLAR_SPECTRUM=.FALSE.
  CHARACTER (LEN=511)::CLOUD_PDF_OVERRIDE_FILE_NAME=''
  LOGICAL::DO_CLOUD_AEROSOL_PER_SW_G_POINT=.TRUE.
  LOGICAL::DO_CLOUD_AEROSOL_PER_LW_G_POINT=.TRUE.
  LOGICAL::DO_WEIGHTED_SURFACE_MAPPING=.TRUE.
  LOGICAL::IS_CONSOLIDATED=.FALSE.
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:)::G_FRAC_SW, G_FRAC_LW
  INTEGER, ALLOCATABLE, DIMENSION (:)::I_ALBEDO_FROM_BAND_SW
  INTEGER, ALLOCATABLE, DIMENSION (:)::I_EMISS_FROM_BAND_LW
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:)::SW_ALBEDO_WEIGHTS
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:)::LW_EMISS_WEIGHTS
  INTEGER, ALLOCATABLE, DIMENSION (:)::I_BAND_FROM_G_LW
  INTEGER, ALLOCATABLE, DIMENSION (:)::I_BAND_FROM_G_SW
  INTEGER, ALLOCATABLE, DIMENSION (:)::I_G_FROM_REORDERED_G_LW
  INTEGER, ALLOCATABLE, DIMENSION (:)::I_G_FROM_REORDERED_G_SW
  INTEGER, ALLOCATABLE, DIMENSION (:)::I_BAND_FROM_REORDERED_G_LW
  INTEGER, ALLOCATABLE, DIMENSION (:)::I_BAND_FROM_REORDERED_G_SW
  INTEGER, POINTER, DIMENSION (:)::I_SPEC_FROM_REORDERED_G_LW
  INTEGER, POINTER, DIMENSION (:)::I_SPEC_FROM_REORDERED_G_SW
  INTEGER::N_CANOPY_BANDS_SW=1
  INTEGER::N_CANOPY_BANDS_LW=1
  TYPE (CKD_MODEL_TYPE)::GAS_OPTICS_SW, GAS_OPTICS_LW
  TYPE (CLOUD_OPTICS_TYPE)::CLOUD_OPTICS
  INTEGER::N_CLOUD_TYPES=2
  TYPE (GENERAL_CLOUD_OPTICS_TYPE), ALLOCATABLE::CLOUD_OPTICS_SW (:)
  TYPE (GENERAL_CLOUD_OPTICS_TYPE), ALLOCATABLE::CLOUD_OPTICS_LW (:)
  TYPE (AEROSOL_OPTICS_TYPE)::AEROSOL_OPTICS
  TYPE (PDF_SAMPLER_TYPE)::PDF_SAMPLER
  CHARACTER (LEN=511)::ICE_OPTICS_FILE_NAME, LIQ_OPTICS_FILE_NAME, AEROSOL_OPTICS_FILE_NAME&
  &, GAS_OPTICS_SW_FILE_NAME, GAS_OPTICS_LW_FILE_NAME
  CHARACTER (LEN=511)::SSI_FILE_NAME
  CHARACTER (LEN=511)::CLOUD_PDF_FILE_NAME
  INTEGER::N_G_SW=0, N_G_LW=0
  INTEGER::N_BANDS_SW=0, N_BANDS_LW=0
  INTEGER::N_SPEC_SW=0, N_SPEC_LW=0
  INTEGER::N_WAV_FRAC_SW=0, N_WAV_FRAC_LW=0
  INTEGER::N_G_LW_IF_SCATTERING=0, N_BANDS_LW_IF_SCATTERING=0
  LOGICAL::IS_HOMOGENEOUS=.FALSE.
  LOGICAL::DO_CLOUDS=.TRUE.
  
  
  
  
  
  
  
  
  
  
  
  
ENDTYPE CONFIG_TYPE

CONTAINS
















ENDMODULE RADIATION_CONFIG
