
MODULE RADIATION_SPECTRAL_DEFINITION
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE


REAL (JPRB), PARAMETER::SOLARREFERENCETEMPERATURE=5777.0_JPRB
REAL (JPRB), PARAMETER::TERRESTRIALREFERENCETEMPERATURE=273.15_JPRB

TYPE SPECTRAL_DEFINITION_TYPE
  INTEGER::NWAV=0
  INTEGER::NG=0
  REAL (JPRB), ALLOCATABLE::WAVENUMBER1 (:)
  REAL (JPRB), ALLOCATABLE::WAVENUMBER2 (:)
  REAL (JPRB), ALLOCATABLE::GPOINT_FRACTION (:,:)
  REAL (JPRB)::REFERENCE_TEMPERATURE=-1.0_JPRB
  REAL (JPRB), ALLOCATABLE::SOLAR_SPECTRAL_IRRADIANCE (:)
  INTEGER::NBAND=0
  REAL (JPRB), ALLOCATABLE::WAVENUMBER1_BAND (:)
  REAL (JPRB), ALLOCATABLE::WAVENUMBER2_BAND (:)
  INTEGER, ALLOCATABLE::I_BAND_NUMBER (:)
  
  
  
  
  
  
  
  
  
  
ENDTYPE SPECTRAL_DEFINITION_TYPE

CONTAINS











ENDMODULE RADIATION_SPECTRAL_DEFINITION
