
MODULE RADIATION_AEROSOL_OPTICS_DATA
USE PARKIND1,ONLY:JPRB
USE RADIATION_IO,ONLY:NULERR, RADIATION_ABORT

IMPLICIT NONE




ENUM, BIND (C)
  ENUMERATOR IAEROSOLCLASSUNDEFINED, IAEROSOLCLASSIGNORED&
  &, IAEROSOLCLASSHYDROPHOBIC, IAEROSOLCLASSHYDROPHILIC
ENDENUM

INTEGER, PARAMETER::NMAXSTRINGLENGTH=2000
INTEGER, PARAMETER::NMAXLINELENGTH=200

TYPE AEROSOL_OPTICS_TYPE
  INTEGER, ALLOCATABLE, DIMENSION (:)::ICLASS
  INTEGER, ALLOCATABLE, DIMENSION (:)::ITYPE
  REAL (JPRB), ALLOCATABLE, DIMENSION (:)::WAVENUMBER1_SW, WAVENUMBER2_SW
  REAL (JPRB), ALLOCATABLE, DIMENSION (:)::WAVENUMBER1_LW, WAVENUMBER2_LW
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:)::MASS_EXT_SW_PHOBIC, SSA_SW_PHOBIC&
  &, G_SW_PHOBIC, MASS_EXT_LW_PHOBIC, SSA_LW_PHOBIC, G_LW_PHOBIC
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:,:)::MASS_EXT_SW_PHILIC, SSA_SW_PHILIC&
  &, G_SW_PHILIC, MASS_EXT_LW_PHILIC, SSA_LW_PHILIC, G_LW_PHILIC
  REAL (JPRB), ALLOCATABLE::WAVELENGTH_MONO (:)
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:)::MASS_EXT_MONO_PHOBIC&
  &, SSA_MONO_PHOBIC, G_MONO_PHOBIC, LIDAR_RATIO_MONO_PHOBIC
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:,:)::MASS_EXT_MONO_PHILIC&
  &, SSA_MONO_PHILIC, G_MONO_PHILIC, LIDAR_RATIO_MONO_PHILIC
  REAL (JPRB), ALLOCATABLE, DIMENSION (:)::RH_LOWER
  CHARACTER (LEN=NMAXSTRINGLENGTH)::DESCRIPTION_PHOBIC_STR=' '
  CHARACTER (LEN=NMAXSTRINGLENGTH)::DESCRIPTION_PHILIC_STR=' '
  INTEGER::NTYPE
  INTEGER::N_TYPE_PHOBIC=0
  INTEGER::N_TYPE_PHILIC=0
  INTEGER::NRH=0
  INTEGER::N_BANDS_LW=0, N_BANDS_SW=0, N_MONO_WL=0
  LOGICAL::USE_HYDROPHILIC=.TRUE.
  LOGICAL::USE_MONOCHROMATIC=.FALSE.
  
  
  
  
  
  
  
  
  
  
  
ENDTYPE AEROSOL_OPTICS_TYPE

CONTAINS











ENDMODULE RADIATION_AEROSOL_OPTICS_DATA
