
MODULE RADIATION_CLOUD_OPTICS_DATA
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE



TYPE CLOUD_OPTICS_TYPE
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:)::LIQ_COEFF_LW, LIQ_COEFF_SW, ICE_COEFF_LW, ICE_COEFF_SW
  REAL (JPRB), ALLOCATABLE, DIMENSION (:)::LIQ_COEFF_GEN, ICE_COEFF_GEN
  
  
ENDTYPE CLOUD_OPTICS_TYPE

CONTAINS

ENDMODULE RADIATION_CLOUD_OPTICS_DATA
