
MODULE RADIATION_ECCKD_GAS
USE PARKIND1,ONLY:JPRB
USE RADIATION_GAS_CONSTANTS

IMPLICIT NONE



ENUM, BIND (C)
  ENUMERATOR::ICONCDEPENDENCENONE=0, ICONCDEPENDENCELINEAR&
  &, ICONCDEPENDENCELUT, ICONCDEPENDENCERELATIVELINEAR
ENDENUM


TYPE CKD_GAS_TYPE
  INTEGER::I_GAS_CODE=-1
  INTEGER::I_CONC_DEPENDENCE
  REAL (JPRB), ALLOCATABLE::MOLAR_ABS (:,:,:)
  REAL (JPRB), ALLOCATABLE::MOLAR_ABS_CONC (:,:,:,:)
  REAL (JPRB)::REFERENCE_MOLE_FRAC=0.0_JPRB
  REAL (JPRB)::LOG_MOLE_FRAC1=0.0_JPRB, D_LOG_MOLE_FRAC=1.0_JPRB
  INTEGER::N_MOLE_FRAC=0
  
  
ENDTYPE CKD_GAS_TYPE

CONTAINS

ENDMODULE RADIATION_ECCKD_GAS
