
MODULE RADIATION_ECCKD
USE PARKIND1,ONLY:JPRB
USE RADIATION_GAS_CONSTANTS
USE RADIATION_ECCKD_GAS
USE RADIATION_SPECTRAL_DEFINITION,ONLY:SPECTRAL_DEFINITION_TYPE

IMPLICIT NONE



TYPE CKD_MODEL_TYPE
  INTEGER::NGAS=0
  TYPE (CKD_GAS_TYPE), ALLOCATABLE::SINGLE_GAS (:)
  INTEGER::I_GAS_MAPPING (0:NMAXGASES)
  INTEGER::NPRESS=0
  INTEGER::NTEMP=0
  REAL (JPRB)::LOG_PRESSURE1, D_LOG_PRESSURE
  REAL (JPRB), ALLOCATABLE::TEMPERATURE1 (:)
  REAL (JPRB)::D_TEMPERATURE
  INTEGER::NPLANCK=0
  REAL (JPRB), ALLOCATABLE::TEMPERATURE1_PLANCK
  REAL (JPRB), ALLOCATABLE::D_TEMPERATURE_PLANCK
  REAL (JPRB), ALLOCATABLE::PLANCK_FUNCTION (:,:)
  REAL (JPRB), ALLOCATABLE::NORM_SOLAR_IRRADIANCE (:)
  REAL (JPRB), ALLOCATABLE::NORM_AMPLITUDE_SOLAR_IRRADIANCE (:)
  REAL (JPRB), ALLOCATABLE::RAYLEIGH_MOLAR_SCAT (:)
  INTEGER::NG=0
  TYPE (SPECTRAL_DEFINITION_TYPE)::SPECTRAL_DEF
  LOGICAL::IS_SW
  
  
  
  
  
  
  
ENDTYPE CKD_MODEL_TYPE

CONTAINS






ENDMODULE RADIATION_ECCKD
