
MODULE RADIATION_GENERAL_CLOUD_OPTICS_DATA
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE



TYPE GENERAL_CLOUD_OPTICS_TYPE
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:)::MASS_EXT
  REAL (JPRB), ALLOCATABLE, DIMENSION (:,:)::SSA, ASYMMETRY
  INTEGER::N_EFFECTIVE_RADIUS=0
  REAL (JPRB)::EFFECTIVE_RADIUS_0, D_EFFECTIVE_RADIUS
  CHARACTER (LEN=511)::TYPE_NAME, SCHEME_NAME
  LOGICAL::USE_BANDS=.FALSE.
  
  
  
ENDTYPE GENERAL_CLOUD_OPTICS_TYPE

CONTAINS
#include "radiation_delta_eddington.h"



ENDMODULE RADIATION_GENERAL_CLOUD_OPTICS_DATA
