
MODULE RANDOM_NUMBERS_MIX
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE


INTEGER (KIND=JPIM), PARAMETER::JPP=273, JPQ=607, JPS=105
INTEGER (KIND=JPIM), PARAMETER::JPMM=30
INTEGER (KIND=JPIM), PARAMETER::JPM=2**JPMM
INTEGER (KIND=JPIM), PARAMETER::JPNUMSPLIT=(JPQ-2)/(JPP-1)
INTEGER (KIND=JPIM), PARAMETER::JPLENSPLIT=(JPQ-JPP+JPNUMSPLIT-1)/JPNUMSPLIT
INTEGER (KIND=JPIM), PARAMETER::INITVALUE=12345678

TYPE RANDOMNUMBERSTREAM
  
  INTEGER (KIND=JPIM)::IUSED
  INTEGER (KIND=JPIM)::INITTEST
  INTEGER (KIND=JPIM), DIMENSION (JPQ)::IX
  REAL (KIND=JPRB)::ZRM
ENDTYPE RANDOMNUMBERSTREAM

CONTAINS





ENDMODULE RANDOM_NUMBERS_MIX
