INTERFACE
SUBROUTINE SETRAN (KCONSEED,YD_RANDOM_STREAM,KOUTSEED,LDRESEED,LDABSTIME,PTSTEP)
USE PARKIND1  ,ONLY : JPIM     ,JPRB, JPRD
USE RANDOM_NUMBERS_MIX, ONLY : RANDOMNUMBERSTREAM, INITIALIZE_RANDOM_NUMBERS
IMPLICIT NONE
INTEGER(KIND=JPIM),       INTENT(IN)              :: KCONSEED
LOGICAL,                  INTENT(IN),    OPTIONAL :: LDRESEED
LOGICAL,                  INTENT(IN),    OPTIONAL :: LDABSTIME
REAL(KIND=JPRB),          INTENT(IN),    OPTIONAL :: PTSTEP
TYPE(RANDOMNUMBERSTREAM), INTENT(INOUT), OPTIONAL :: YD_RANDOM_STREAM
INTEGER(KIND=JPIM),       INTENT(OUT),   OPTIONAL :: KOUTSEED
END SUBROUTINE SETRAN







END INTERFACE
