INTERFACE
SUBROUTINE SLCOMM(YDSL,KFIXFLD,KFLDSLB,LDINC,KTYP,PB1A,LDSLCOMM,LDSWITCH,LD_TLEVOL)
USE PARKIND1     , ONLY : JPIM, JPRB
USE EINT_MOD     , ONLY : SL_STRUCT
IMPLICIT NONE
TYPE(SL_STRUCT)   ,INTENT(IN)    :: YDSL
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLDSLB
INTEGER(KIND=JPIM),INTENT(IN)    :: KFIXFLD(2)
LOGICAL           ,INTENT(IN)    :: LDINC
INTEGER(KIND=JPIM),INTENT(IN)    :: KTYP
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB1A(YDSL%NASLB1,KFLDSLB)
LOGICAL,OPTIONAL  ,INTENT(IN)    :: LDSLCOMM(YDSL%NSLPROCS)
LOGICAL,OPTIONAL  ,INTENT(IN)    :: LDSWITCH
LOGICAL,OPTIONAL  ,INTENT(IN)    :: LD_TLEVOL
END SUBROUTINE SLCOMM







END INTERFACE
