MODULE SPECTRAL_ARP_MOD

!dummy!

USE PARKIND1  ,ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SPECTRAL_FIELDS_MOD
USE RANDOM_NUMBERS_MIX

IMPLICIT NONE

PRIVATE
PUBLIC SPECTRAL_ARP, EVOLVE_ARP, ALLOCATE_ARP, SET_ARP2D

TYPE SPECTRAL_ARP
!
  TYPE(SPECTRAL_FIELD) :: SF
  LOGICAL              :: LSUM
  TYPE(SPECTRAL_FIELD) :: SFSUM
  INTEGER(KIND=JPIM)   :: ISEED0
  INTEGER(KIND=JPIM)   :: ISEED0T0
  INTEGER(KIND=JPIM),       DIMENSION(:,:),   POINTER :: ISEED2D
  INTEGER(KIND=JPIM),       DIMENSION(:,:,:), POINTER :: ISEED3D
  TYPE(RANDOMNUMBERSTREAM), DIMENSION(:,:),   POINTER :: RS2D
  TYPE(RANDOMNUMBERSTREAM), DIMENSION(:,:,:), POINTER :: RS3D
  REAL(KIND=JPRB),          DIMENSION(:,:),   POINTER :: SDEV2D
  REAL(KIND=JPRB),          DIMENSION(:,:,:), POINTER :: SDEV3D
  LOGICAL :: LCLIP
  REAL(KIND=JPRB),          DIMENSION(:,:),   POINTER :: ACLIP2D
  REAL(KIND=JPRB),          DIMENSION(:,:,:), POINTER :: ACLIP3D
  REAL(KIND=JPRB),          DIMENSION(:,:),   POINTER :: ACLIPAR2D
  REAL(KIND=JPRB),          DIMENSION(:,:,:), POINTER :: ACLIPAR3D
  REAL(KIND=JPRB),          DIMENSION(:,:),   POINTER :: PHI2D
  REAL(KIND=JPRB),          DIMENSION(:,:,:), POINTER :: PHI3D
END TYPE SPECTRAL_ARP

CONTAINS

SUBROUTINE ALLOCATE_ARP(YDGEOMETRY,YDARP,KS3D,KS2D,KS1D,KGRIB,KSEED,LDCLIP,LDSUM)

TYPE (GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE (SPECTRAL_ARP), INTENT(OUT) :: YDARP
INTEGER(KIND=JPIM), INTENT(IN) :: KS3D, KS2D, KS1D, KGRIB(KS3D+KS2D), KSEED
LOGICAL, OPTIONAL :: LDCLIP, LDSUM

print *, ' ALLOCATE_ARP should be never called'
stop

END SUBROUTINE ALLOCATE_ARP


SUBROUTINE EVOLVE_ARP(YDARP,KARP,LDINIT)

TYPE (SPECTRAL_ARP),          INTENT(INOUT) :: YDARP
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: KARP
LOGICAL, OPTIONAL,            INTENT(IN)    :: LDINIT

print *, ' EVOLVE_ARP should be never called'
stop

END SUBROUTINE EVOLVE_ARP

SUBROUTINE SET_ARP2D(YDARP,SDEV2D,PHI2D,ACLIP2D)

TYPE (SPECTRAL_ARP), INTENT(INOUT) :: YDARP
REAL(KIND=JPRB), DIMENSION(:,:),   INTENT(IN) :: SDEV2D, PHI2D
REAL(KIND=JPRB), DIMENSION(:,:),   OPTIONAL, INTENT(IN) :: ACLIP2D

print *, ' SET_ARP2D should be never called'
stop

END SUBROUTINE SET_ARP2D

END MODULE SPECTRAL_ARP_MOD
