MODULE SPECTRAL_FIELDS_MOD
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE SPECTRAL_VARIABLES_MOD,ONLY:SPECTRAL_VARIABLES
USE SPECTRAL_FIELDS_DATA,ONLY:SPECTRAL_FIELD, NPRTRV, NPRTRW, MYSETV, MYSETW, LELAM, NULOUT, NGRBVO&
&, NGRBD, NGRBT, NGRBQ, NGRBO3, NGRBLNSP, NGRBZ, NGRBCLWC, NGRBCIWC, NGRB118, NGRB119, NGRBNHX

IMPLICIT NONE

REAL (KIND=JPRB), TARGET::SPECTRAL_DUMMY2D (1), SPECTRAL_DUMMY3D (1, 1), SPECTRAL_DUMMY4D (1, 1, 1)
SAVE

TYPE::SPECTRAL_FIELD_CONTAINER
  CLASS (SPECTRAL_FIELD), POINTER::OBJ
ENDTYPE SPECTRAL_FIELD_CONTAINER


ENDMODULE SPECTRAL_FIELDS_MOD
