MODULE SPECTRAL_VARIABLES_MOD

USE PARKIND1, ONLY: JPIM

IMPLICIT NONE

INTEGER(KIND=JPIM), PARAMETER :: JP_MAX_N_SPJB_VARS = 500

TYPE SPECTRAL_VARIABLES
  INTEGER(KIND=JPIM) :: NS3D
  INTEGER(KIND=JPIM) :: NS2D
  INTEGER(KIND=JPIM) :: NS1D
  INTEGER(KIND=JPIM) :: NGRBVAR(JP_MAX_N_SPJB_VARS)
END TYPE SPECTRAL_VARIABLES

END MODULE SPECTRAL_VARIABLES_MOD
