INTERFACE
SUBROUTINE SPINT(PSPEC,KDIM,KSMAXI,KSMAXO)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KDIM
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSPEC(KDIM)
INTEGER(KIND=JPIM),INTENT(IN)    :: KSMAXI
INTEGER(KIND=JPIM),INTENT(IN)    :: KSMAXO
END SUBROUTINE SPINT







END INTERFACE
