MODULE SPP_MOD
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE SPP_GEN_MOD,ONLY:SPP_MODEL
USE SPP_DEF_MOD,ONLY:SPP_PERT_POINTER
USE SPECTRAL_ARP_MOD,ONLY:SPECTRAL_ARP
USE SPECTRAL_SPG_MOD,ONLY:SPECTRAL_SPG
USE GRIDPOINT_FIELDS_MIX,ONLY:GRIDPOINT_FIELD

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::JPSPPLABLEN=16, NWRMAX=255

TYPE TSPP_CONFIG
  LOGICAL::LSPP=.FALSE.
  CHARACTER (LEN=32)::CSPP_MODEL_NAME
  TYPE (SPP_MODEL)::SM
  TYPE (SPP_PERT_POINTER)::PPTR
  LOGICAL::LRAMIDLIMIT1
  LOGICAL::LUSE_SETRAN=.TRUE.
  LOGICAL::LNSEED_OFFS0
  LOGICAL::LRDPATINIT
  LOGICAL::LWRPATTRUN
  INTEGER (KIND=JPIM)::NWRPATTRUN
  INTEGER (KIND=JPIM), DIMENSION (NWRMAX)::NHOUR_PATTRUN
  INTEGER (KIND=JPIM), DIMENSION (NWRMAX)::NSTEP_PATTRUN
  LOGICAL::LRESETSEED
  LOGICAL::LABSTIMSEED
  INTEGER (KIND=JPIM)::RESETSEEDFRQ
  INTEGER (KIND=JPIM)::SHIFTSEED
  CHARACTER (LEN=256)::SPP_RDPATINIT
  CHARACTER (LEN=256)::SPP_WRPATTRUN
  INTEGER (JPIM)::ISEEDFAC
  INTEGER (JPIM)::IEZDIAG_POS
  INTEGER (JPIM)::NPATFR=1
  REAL (KIND=JPRB)::XPRESS_PHR_ST
  LOGICAL::LSPG_SPP=.FALSE.
  REAL (KIND=JPRB)::SPGMU
  REAL (KIND=JPRB)::SPGLAMBDA
  REAL (KIND=JPRB)::SPGSIGMA
  REAL (KIND=JPRB)::SPGQ
  REAL (KIND=JPRB)::SPGADTMIN
  REAL (KIND=JPRB)::SPGADTMAX
  REAL (KIND=JPRB)::SPGTDT
ENDTYPE TSPP_CONFIG


TYPE TSPP_DATA
  INTEGER (JPIM), DIMENSION (:), ALLOCATABLE::IGRIBCODE
  TYPE (SPECTRAL_ARP), DIMENSION (:), POINTER::SP_ARP=>NULL ()
  TYPE (SPECTRAL_SPG), DIMENSION (:), POINTER::SP_SPG=>NULL ()
  TYPE (GRIDPOINT_FIELD), DIMENSION (:), POINTER::GP_ARP=>NULL ()
  TYPE (GRIDPOINT_FIELD), DIMENSION (:), POINTER::GP_ARP0=>NULL ()
  TYPE (GRIDPOINT_FIELD), DIMENSION (:), POINTER::GP_ARP1=>NULL ()
  CHARACTER (LEN=JPSPPLABLEN), DIMENSION (:), POINTER::LAB_ARP=>NULL ()
ENDTYPE TSPP_DATA

#include "abor1.intfb.h"
CONTAINS

ENDMODULE SPP_MOD
