MODULE SPP_DEF_MOD
USE PARKIND1,ONLY:JPIM, JPRB
USE SPP_GEN_MOD,ONLY:SPP_MODEL, ALLOCATE_SPP_MODEL, IMPLEMENT_SPP_PERTN&
&, JP_LAB_LEN, CP_UNDEFINED, JPMXSCALES
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE


TYPE SPP_PERT_POINTER
  INTEGER (KIND=JPIM)::CFM=-1
  INTEGER (KIND=JPIM)::CFM1=-1
  INTEGER (KIND=JPIM)::CFM2=-1
  INTEGER (KIND=JPIM)::CFM3=-1
  INTEGER (KIND=JPIM)::RKAP=-1
  INTEGER (KIND=JPIM)::RKAP1=-1
  INTEGER (KIND=JPIM)::RKAP2=-1
  INTEGER (KIND=JPIM)::RKAP3=-1
  INTEGER (KIND=JPIM)::TOFDC=-1
  INTEGER (KIND=JPIM)::HSDT=-1
  INTEGER (KIND=JPIM)::VDEXC=-1
  INTEGER (KIND=JPIM)::VDSST=-1
  INTEGER (KIND=JPIM)::COLDSKIN=-1
  INTEGER (KIND=JPIM)::ENTRORG=-1
  INTEGER (KIND=JPIM)::ENTSHALP=-1
  INTEGER (KIND=JPIM)::ENTSTPC1=-1
  INTEGER (KIND=JPIM)::DETRPEN=-1
  INTEGER (KIND=JPIM)::RPRCON=-1
  INTEGER (KIND=JPIM)::RTAU=-1
  INTEGER (KIND=JPIM)::CUDUDV=-1
  INTEGER (KIND=JPIM)::CUDUDVS=-1
  INTEGER (KIND=JPIM)::RAMID=-1
  INTEGER (KIND=JPIM)::RCLDIFF=-1
  INTEGER (KIND=JPIM)::RCLCRIT=-1
  INTEGER (KIND=JPIM)::RLCRITSNOW=-1
  INTEGER (KIND=JPIM)::RAINEVAP=-1
  INTEGER (KIND=JPIM)::SNOWSUBLIM=-1
  INTEGER (KIND=JPIM)::CLOUDINHOM=-1
  INTEGER (KIND=JPIM)::QSATVERVEL=-1
  INTEGER (KIND=JPIM)::FALLSPEED=-1
  INTEGER (KIND=JPIM)::ZDECORR=-1
  INTEGER (KIND=JPIM)::ZSIGQCW=-1
  INTEGER (KIND=JPIM)::ZRADEFFL=-1
  INTEGER (KIND=JPIM)::ZRADEFFI=-1
  INTEGER (KIND=JPIM)::PHR=-1
  INTEGER (KIND=JPIM)::AEROSOLMMR=-1
  INTEGER (KIND=JPIM)::ZHS_VDAERO=-1
  INTEGER (KIND=JPIM)::DELTA_AERO=-1
  INTEGER (KIND=JPIM)::PSIGQSAT=-1
  INTEGER (KIND=JPIM)::CLDDPTH=-1
  INTEGER (KIND=JPIM)::CLDDPTHDP=-1
  INTEGER (KIND=JPIM)::ICE_CLD_WGT=-1
  INTEGER (KIND=JPIM)::ICENU=-1
  INTEGER (KIND=JPIM)::RCRIAUTI=-1
  INTEGER (KIND=JPIM)::RCRIAUTC=-1
  INTEGER (KIND=JPIM)::ZRDEPRED=-1
  INTEGER (KIND=JPIM)::KGN_ACON=-1
  INTEGER (KIND=JPIM)::KGN_SBGR=-1
  INTEGER (KIND=JPIM)::RADGR=-1
  INTEGER (KIND=JPIM)::RADSN=-1
  INTEGER (KIND=JPIM)::RFAC_TWOC=-1
  INTEGER (KIND=JPIM)::RZC_H=-1
  INTEGER (KIND=JPIM)::RZL_INF=-1
  INTEGER (KIND=JPIM)::RSWINHF=-1
  INTEGER (KIND=JPIM)::RLWINHF=-1
  INTEGER (KIND=JPIM)::ALPHA=-1
  INTEGER (KIND=JPIM)::RZNUC=-1
  INTEGER (KIND=JPIM)::RZMFDRY=-1
  INTEGER (KIND=JPIM)::RZMBCLOSURE=-1
  INTEGER (KIND=JPIM)::SLWIND=-1
  INTEGER (KIND=JPIM)::XCTP=-1
  INTEGER (KIND=JPIM)::XCEP=-1
  INTEGER (KIND=JPIM)::XCED=-1
  INTEGER (KIND=JPIM)::XCMF=-1
  
  
ENDTYPE SPP_PERT_POINTER

CONTAINS




ENDMODULE SPP_DEF_MOD
