MODULE STOPH_MIX
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TSTOPH
  REAL (KIND=JPRB), ALLOCATABLE::RSTOPHCA (:)
  REAL (KIND=JPRB), ALLOCATABLE::SQRTCORR (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SPSTREAM (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SPVELPOT (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SPSTREAM_FORC (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SPVELPOT_FORC (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SPG_AMP (:)
  REAL (KIND=JPRB), ALLOCATABLE::ALPHA_STO (:)
  REAL (KIND=JPRB), ALLOCATABLE::ONEMINALPHA_NFRSPBS (:)
  REAL (KIND=JPRB), ALLOCATABLE::RSMOOTH (:)
  REAL (KIND=JPRB), ALLOCATABLE::GPSTREAM (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GPVELPOT (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GPTOTDISS (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GPTOTDISS_SMOOTH (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GPVORTGRAD (:,:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MCELL (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RWGHT (:,:)
  INTEGER (KIND=JPIM)::NFRSTOPH_SPBS
  INTEGER (KIND=JPIM)::NFRSTOPH_SPBS_PAT
  INTEGER (KIND=JPIM)::NFRSTOPH_VC
  INTEGER (KIND=JPIM)::NFORCESTART
  INTEGER (KIND=JPIM)::NFORCEEND
  INTEGER (KIND=JPIM)::NSTOCHOPT
  REAL (KIND=JPRB)::ALPHA_DEEP_CONV
  REAL (KIND=JPRB)::ALPHA_SHAL_CONV
  REAL (KIND=JPRB)::SLDISSFAC
  REAL (KIND=JPRB)::RATIO_BACKSCAT
  REAL (KIND=JPRB)::RSPBS_TAU
  REAL (KIND=JPRB)::RATIO_BACKSCAT_CON2NUM
  REAL (KIND=JPRB)::REXPONENT
  REAL (KIND=JPRB)::VC_CON
  REAL (KIND=JPRB)::RFLUX_DET_CLIP
  REAL (KIND=JPRB)::BIHARM
  REAL (KIND=JPRB)::RSMOOTHSCALE
  REAL (KIND=JPRB)::RSIGMA2_EPS
  INTEGER (KIND=JPIM)::INCUT
  REAL (KIND=JPRB)::AMAGSTOPH_CASBS
  REAL (KIND=JPRB)::ADLATSTOPH_CA
  REAL (KIND=JPRB)::ADLONSTOPH_CA
  LOGICAL::LSTOPH_SPBS, LSTOPH_SPBS_FAST, LEXTRAFIELDS, LSTOPH_JBCOR, LSTOPH_UNCORR, LSTOPH_UNIFORM
  LOGICAL::LSTOPH_SPBS_VORT
  LOGICAL::LSTOPH_RVP, LSTOPH_RVPOLD
  LOGICAL::LSTOPH_TAPER
  LOGICAL::LSTOPH_INI
  LOGICAL::LSTOPH_CASBS
  LOGICAL::LVORTCON
  LOGICAL::LFORCENL
  LOGICAL::LSTOPH_VARALPHA
  LOGICAL::LSTOPH_GAUSS
  LOGICAL::LSPBS_DISSGW, LSPBS_DISSNUM, LSPBS_DISSCU
  LOGICAL::LSPBS_DISSNUM_CT
  LOGICAL::LSPBSNORM
  LOGICAL::LSPBSDISS
  REAL (KIND=JPRB), ALLOCATABLE::SPDP (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NIMRAN (:)
  INTEGER (KIND=JPIM)::NSMAXSPBS
  REAL (KIND=JPRB)::RVP_MULMIN
  REAL (KIND=JPRB)::RVP_MULMAX
  REAL (KIND=JPRB)::RVP_MULEXP
  REAL (KIND=JPRB)::RVP_MULNSMAX
  REAL (KIND=JPRB), ALLOCATABLE::RVP_MULFACT (:)
  REAL (KIND=JPRB)::RVP_MUL_A, RVP_MUL_B, RVP_MUL_C, RVP_MUL_D
  REAL (KIND=JPRB)::RVP_MUL_1, RVP_MUL_2
  REAL (KIND=JPRB), ALLOCATABLE::RVP_MUL (:)
  REAL (KIND=JPRB)::TAPER_SIGMATOP, TAPER_SIGMABOT, TAPER0, TAPER1, TAPER2, TAPER3
  REAL (KIND=JPRB), ALLOCATABLE::TAPER_FACT (:)
  LOGICAL::LSTOPH_SPBS_T
  REAL (KIND=JPRB)::REXPONENT_T
  REAL (KIND=JPRB)::RATIO_APE2KE
  REAL (KIND=JPRB), ALLOCATABLE::SPTEMP (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SPTEMP_FORC (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SPG_AMP_T (:)
  REAL (KIND=JPRB), ALLOCATABLE::ALPHA_STO_T (:)
  REAL (KIND=JPRB), ALLOCATABLE::ONEMINALPHA_NFRSPBS_T (:)
  REAL (KIND=JPRB), ALLOCATABLE::GPTEMP (:,:,:)
  REAL (KIND=JPRB)::RVP_MULMIN_T
  REAL (KIND=JPRB)::RVP_MULMAX_T
  REAL (KIND=JPRB)::RVP_MULEXP_T
  REAL (KIND=JPRB)::RVP_MULNSMAX_T
  REAL (KIND=JPRB), ALLOCATABLE::RVP_MULFACT_T (:)
  REAL (KIND=JPRB)::RVP_MUL_A_T, RVP_MUL_B_T, RVP_MUL_C_T, RVP_MUL_D_T
  REAL (KIND=JPRB)::RVP_MUL_1_T, RVP_MUL_2_T
  REAL (KIND=JPRB), ALLOCATABLE::RVP_MUL_T (:)
  
ENDTYPE TSTOPH

CONTAINS












ENDMODULE STOPH_MIX
