
MODULE SURFACE_FIELDS_MIX
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE YOMDIM,ONLY:TDIM
USE YOMLUN,ONLY:NULOUT, NULERR
USE YOMCT0,ONLY:NUNDEFLD

IMPLICIT NONE

SAVE
#include "abor1.intfb.h"
INTEGER (KIND=JPIM), PARAMETER::JPMAXSFLDS=694
INTEGER (KIND=JPIM), PARAMETER::JPMAXSTRAJ=100
INTEGER (KIND=JPIM)::NOFFTRAJ
INTEGER (KIND=JPIM)::NOFFTRAJ_CST
INTEGER (KIND=JPIM)::NSTRAJGRIB (JPMAXSTRAJ)
INTEGER (KIND=JPIM), PRIVATE::NPTRSURF

TYPE TYPE_SURF_MTL
  INTEGER (KIND=JPIM)::MP
  INTEGER (KIND=JPIM)::MP0
  INTEGER (KIND=JPIM)::MP9
  INTEGER (KIND=JPIM)::MP1
  INTEGER (KIND=JPIM)::ITRAJ
  INTEGER (KIND=JPIM)::IBUGFINDER
  LOGICAL::LSET
ENDTYPE TYPE_SURF_MTL


TYPE, EXTENDS (TYPE_SURF_MTL)::TYPE_SURF_MTL_2D
  INTEGER (KIND=JPIM)::IGRBCODE
  CHARACTER (LEN=16)::CNAME='                '
  REAL (KIND=JPRB)::REFVALI
  INTEGER (KIND=JPIM)::NREQIN
ENDTYPE TYPE_SURF_MTL_2D


TYPE, EXTENDS (TYPE_SURF_MTL)::TYPE_SURF_MTL_3D
  INTEGER (KIND=JPIM), ALLOCATABLE::IGRBCODE (:)
  CHARACTER (LEN=16), ALLOCATABLE::CNAME (:)
  REAL (KIND=JPRB), ALLOCATABLE::REFVALI (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NREQIN (:)
ENDTYPE TYPE_SURF_MTL_3D


TYPE TYPE_SURF_GEN
  INTEGER (KIND=JPIM)::NUMFLDS
  INTEGER (KIND=JPIM)::NDIM
  INTEGER (KIND=JPIM)::NLEVS
  INTEGER (KIND=JPIM)::IPTR
  INTEGER (KIND=JPIM)::IPTR5
  INTEGER (KIND=JPIM)::NDIM5
  INTEGER (KIND=JPIM)::NOFFTRAJ
  INTEGER (KIND=JPIM)::NOFFTRAJ_CST
  CHARACTER (LEN=16)::CGRPNAME
  LOGICAL::L3D
  LOGICAL::LMTL
  LOGICAL::FINALISED
ENDTYPE TYPE_SURF_GEN


TYPE TYPE_SFL_COMM
  INTEGER (KIND=JPIM)::IGRBCODE
  LOGICAL::L_OK
  CHARACTER (LEN=16)::CNAME
  INTEGER (KIND=JPIM)::IFLDNUM
  REAL (KIND=JPRB)::VALUE
  INTEGER (KIND=JPIM)::IPTRSURF
  INTEGER (KIND=JPIM)::ICODES (JPMAXSFLDS)
  INTEGER (KIND=JPIM)::ICODESML (JPMAXSFLDS)
  INTEGER (KIND=JPIM)::ICOUNT
  INTEGER (KIND=JPIM)::ICOUNTML
ENDTYPE TYPE_SFL_COMM


TYPE TYPE_SFL_SOILB
  TYPE (TYPE_SURF_MTL_3D), POINTER::YT=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YQ=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YTL=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YSB (:)=>NULL ()
ENDTYPE TYPE_SFL_SOILB


TYPE TYPE_SFL_SNOWG
  TYPE (TYPE_SURF_MTL_3D), POINTER::YF=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YA=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YR=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YT=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YW=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YSG (:)=>NULL ()
ENDTYPE TYPE_SFL_SNOWG


TYPE TYPE_SFL_LAKEB
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLICT=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLMLT=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLTLT=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLBLT=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLSHF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLICD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLMLD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSL (:)=>NULL ()
ENDTYPE TYPE_SFL_LAKEB


TYPE TYPE_SFL_RESVR
  TYPE (TYPE_SURF_MTL_2D), POINTER::YT=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YFC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YIC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YFP1=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YRR (:)=>NULL ()
ENDTYPE TYPE_SFL_RESVR


TYPE TYPE_SFL_CLS
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCLS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YHUCLS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUCLS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVCLS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YNUCLS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YNVCLS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSICLS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCL (:)=>NULL ()
ENDTYPE TYPE_SFL_CLS


TYPE TYPE_SFL_OML
  TYPE (TYPE_SURF_MTL_3D), POINTER::YTO=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YSO=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YUO=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YVO=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YOM (:)=>NULL ()
ENDTYPE TYPE_SFL_OML


TYPE TYPE_SFL_EXTRP
  TYPE (TYPE_SURF_MTL_3D), POINTER::YEP (:)=>NULL ()
ENDTYPE TYPE_SFL_EXTRP


TYPE TYPE_SFL_XTRP2
  TYPE (TYPE_SURF_MTL_2D), POINTER::YX2 (:)=>NULL ()
ENDTYPE TYPE_SFL_XTRP2


TYPE TYPE_SFL_CANRI
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCI (:)=>NULL ()
ENDTYPE TYPE_SFL_CANRI


TYPE TYPE_SFL_VARSF
  TYPE (TYPE_SURF_MTL_2D), POINTER::YZ0F=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALBF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YEMISF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YGETRL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLSM=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVEG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVRLAN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVRLDI=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSIG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALBSF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLAN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSST=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLZ0H=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCVL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCO2TYP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCVH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCUR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTVL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTVH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YFWET=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLAIL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLAIH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSOTY=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCLK=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCI=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUCUR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVCUR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YZ0RLF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCGPP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCREC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSDFOR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALUVP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALUVD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALNIP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALNID=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALUVI=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALNII=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALUVV=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALNIV=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALUVG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALNIG=>NULL ()
  INTEGER (KIND=JPIM)::IALSTART, IALEND
  TYPE (TYPE_SURF_MTL_2D), POINTER::YFP1=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSO2DD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDMSO=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YURBF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YFCA1=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YFCA2=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YAERDEP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YAERLTS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YAERSCC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDSF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDSZ=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCHEMFLXO (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCHEMWDFLX (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCHEMDDFLX (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCHEMDV (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YEMIS2D (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YEMIS2DAUX (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YNUDM=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVF (:)=>NULL ()
ENDTYPE TYPE_SFL_VARSF


TYPE TYPE_SFL_VCLIP
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTPC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YWPC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVP (:)=>NULL ()
ENDTYPE TYPE_SFL_VCLIP


TYPE TYPE_SFL_VCLIV
  TYPE (TYPE_SURF_MTL_2D), POINTER::YARG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSAB=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YD2=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YIVEG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YRSMIN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLAI=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YHV=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YZ0H=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALV=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVV (:)=>NULL ()
ENDTYPE TYPE_SFL_VCLIV


TYPE TYPE_SFL_VCLIN
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTOP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YBAS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YACPR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YACCPR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YACCPR5=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVN (:)=>NULL ()
ENDTYPE TYPE_SFL_VCLIN


TYPE TYPE_SFL_VCLIH
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCCH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSCCH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YBCCH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPBLH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSPSH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YQSH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVH (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPCL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPSL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPCN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPSN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YEVA=>NULL ()
ENDTYPE TYPE_SFL_VCLIH


TYPE TYPE_SFL_VCLIK
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUDGRO=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVK (:)=>NULL ()
ENDTYPE TYPE_SFL_VCLIK


TYPE TYPE_SFL_VCLIA
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSEA=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLAN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSOO=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDES=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSUL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVOL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSS1=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSS2=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSS3=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDD1=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDD2=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDD3=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YOM1=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YOM2=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YBC1=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YBC2=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSU=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVA (:)=>NULL ()
ENDTYPE TYPE_SFL_VCLIA


TYPE TYPE_SFL_VCLIG
  TYPE (TYPE_SURF_MTL_2D), POINTER::YICFR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSOUP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YIRUP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCHSS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YEVAP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTAUX=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTAUY=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVG (:)=>NULL ()
ENDTYPE TYPE_SFL_VCLIG


TYPE TYPE_SFL_VO3ABC
  TYPE (TYPE_SURF_MTL_2D), POINTER::YA=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YB=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVC (:)=>NULL ()
ENDTYPE TYPE_SFL_VO3ABC


TYPE TYPE_SFL_VDIAGO2
  TYPE (TYPE_SURF_MTL_2D), POINTER::YOCDEP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUSTRC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVSTRC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YV2 (:)=>NULL ()
ENDTYPE TYPE_SFL_VDIAGO2


TYPE TYPE_SFL_VDIAGO3
  TYPE (TYPE_SURF_MTL_3D), POINTER::YDIFM=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YDIFT=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YDIFS=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YADVT=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YADVS=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YTRI0=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YTRI1=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YSWDK=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YZO=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YHO=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YDO=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YHO_INV=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YUOC=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YVOC=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YOTKE=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YV3 (:)=>NULL ()
ENDTYPE TYPE_SFL_VDIAGO3


TYPE TYPE_SFL_VDIAG
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLSP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YFZRA=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YBLD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSHF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSLHF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YNEE=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YGPP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YREC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YACH4=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMSL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y10U=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y10V=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y2T=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y2D=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y2SH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSTR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTSR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTTR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YEWSS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YNSSS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YE=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPEV=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCCC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLCC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMCC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YHCC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLGWS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMGWS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YGWD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMX2T=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMN2T=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMX2T6 (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMN2T6 (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YRO=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSRO=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSRO=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YALB=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YIEWSS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YINSSS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YISSHF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YIE=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YINEE=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YIGPP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YIREC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YICH4=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCSF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLSSF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMXTPR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMNTPR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMXTPR6 (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMNTPR6 (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTPR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLSRR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCRR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLSSFR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCSFR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPTYPE=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YILSPF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YZ0F=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLZ0H=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVIWVE=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVIWVN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCWV=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCLW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCIW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCRW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCSW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCSLW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSRD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSTRD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSRDC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSTRDC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YBLH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSUND=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSPAR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSUVB=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSFDIR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSCDIR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSDSRP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCAPE=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMUCAPE=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMLCAPE50=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMLCAPE100=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPDEPL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCAPES=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMXCAP6 (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMXCAPS6 (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTROPOTP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTSRC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTTRC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSRC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSTRC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YES=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSMLT=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y10FG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y10FG6 (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y10FGCV=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YI10FG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLSPF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCO3=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVIMD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSPARC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSTINC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCBASE=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y0DEGL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YM10DEGL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVISIH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCIN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMLCIN50=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMLCIN100=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YKINDEX=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTTINDEX=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCBASEA=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCTOPC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YZTWETB0=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YZTWETB1=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCGHG (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTCCHEM (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YAERODIAG (:,:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YAERO_WVL_DIAG (:,:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y100U=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y100V=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y200U=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y200V=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YZUST=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y10NU=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y10NV=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDNDZN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDNDZA=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YDCTB=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTPLB=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTPLT=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODSS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODDU=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODOM=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODBC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODSU=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODNI=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODAM=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODSOA=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODVFA=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODVSU=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YODTOACC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YAEPM1=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YAEPM25=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YAEPM10=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUVBED=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUVBEDCS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLITOTI=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLICGI=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLITOTA6 (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLICGA6 (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSDSL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVD (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPTYPEOCC6 (:,:)=>NULL ()
ENDTYPE TYPE_SFL_VDIAG


TYPE TYPE_SFL_SATSIM
  TYPE (TYPE_SURF_MTL_3D), POINTER::YCLBT=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YCSBT=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YSM (:)=>NULL ()
ENDTYPE TYPE_SFL_SATSIM


TYPE TYPE_SFL_WAVES
  TYPE (TYPE_SURF_MTL_2D), POINTER::YWS (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCHAR=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCHARHQ=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUSTOKES=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVSTOKES=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTAUOCX=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTAUOCY=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPHIOC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YWSEMEAN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YWSFMEAN=>NULL ()
ENDTYPE TYPE_SFL_WAVES


TYPE TYPE_SFL_WAM
  TYPE (TYPE_SURF_MTL_2D), POINTER::YWW (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YU10N=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YV10N=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YRHO=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YZIL=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCIF=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCLK=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUSTRW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVSTRW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUCURW=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVCURW=>NULL ()
ENDTYPE TYPE_SFL_WAM


TYPE TYPE_SFL_VCLIX
  TYPE (TYPE_SURF_MTL_2D), POINTER::YORO=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTSC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPWS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YPWP=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSNO=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTPC=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSAB=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YXD2=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLSM=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YIVEG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YARG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YRSMIN=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YLAI=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVEG=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVX (:)=>NULL ()
ENDTYPE TYPE_SFL_VCLIX


TYPE TYPE_SFL_VEXTRA
  TYPE (TYPE_SURF_MTL_3D), POINTER::YXA (:)=>NULL ()
ENDTYPE TYPE_SFL_VEXTRA


TYPE TYPE_SFL_VEXTRDI
  TYPE (TYPE_SURF_MTL_3D), POINTER::YXA (:)=>NULL ()
  TYPE (TYPE_SURF_MTL_3D), POINTER::YXEDR=>NULL ()
ENDTYPE TYPE_SFL_VEXTRDI


TYPE TYPE_SFL_VPRECIP
  TYPE (TYPE_SURF_MTL_3D), POINTER::YPRECIP
  TYPE (TYPE_SURF_MTL_3D), POINTER::YXP1 (:)=>NULL ()
ENDTYPE TYPE_SFL_VPRECIP


TYPE TYPE_SFL_VPRECIP2
  TYPE (TYPE_SURF_MTL_3D), POINTER::YPRECIP2
  TYPE (TYPE_SURF_MTL_3D), POINTER::YXP2 (:)=>NULL ()
ENDTYPE TYPE_SFL_VPRECIP2


TYPE TYPE_SFL_VEXTR2
  TYPE (TYPE_SURF_MTL_2D), POINTER::YX2 (:)=>NULL ()
ENDTYPE TYPE_SFL_VEXTR2


TYPE TYPE_SFL_SFLUX
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSFL (:)=>NULL ()
ENDTYPE TYPE_SFL_SFLUX


TYPE TYPE_SFL_SFORC
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSFO (:)=>NULL ()
ENDTYPE TYPE_SFL_SFORC


TYPE TYPE_SFL_OCE
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSTM=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YCIM=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YUCURM=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YVCURM=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YICTH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::Y20D=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSH=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YMLD=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSSS=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YTEM3=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YSAL3=>NULL ()
  TYPE (TYPE_SURF_MTL_2D), POINTER::YOC (:)=>NULL ()
ENDTYPE TYPE_SFL_OCE


TYPE::TSURF
  INTEGER (KIND=JPIM)::NSURF=0
  INTEGER (KIND=JPIM)::NSURFL=0
  INTEGER (KIND=JPIM)::NDIMSURF=0
  INTEGER (KIND=JPIM)::NDIMSURFL=0
  INTEGER (KIND=JPIM)::NPROGSURF=0
  INTEGER (KIND=JPIM)::NPROGSURFL=0
  REAL (KIND=JPRB), ALLOCATABLE::STORE_ARRAY (:,:,:)
  TYPE (TYPE_SFL_COMM)::YDUPD
  REAL (KIND=JPRB), ALLOCATABLE::SP_SB (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSP_SBD
  TYPE (TYPE_SFL_SOILB)::YSP_SB
  REAL (KIND=JPRB), ALLOCATABLE::SP_SG (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSP_SGD
  TYPE (TYPE_SFL_SNOWG)::YSP_SG
  REAL (KIND=JPRB), ALLOCATABLE::SP_SL (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSP_SLD
  TYPE (TYPE_SFL_LAKEB)::YSP_SL
  REAL (KIND=JPRB), ALLOCATABLE::SP_RR (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSP_RRD
  TYPE (TYPE_SFL_RESVR)::YSP_RR
  REAL (KIND=JPRB), ALLOCATABLE::SP_CL (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSP_CLD
  TYPE (TYPE_SFL_CLS)::YSP_CL
  REAL (KIND=JPRB), ALLOCATABLE::SP_OM (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSP_OMD
  TYPE (TYPE_SFL_OML)::YSP_OM
  REAL (KIND=JPRB), ALLOCATABLE::SP_EP (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSP_EPD
  TYPE (TYPE_SFL_EXTRP)::YSP_EP
  REAL (KIND=JPRB), ALLOCATABLE::SP_X2 (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSP_X2D
  TYPE (TYPE_SFL_XTRP2)::YSP_X2
  REAL (KIND=JPRB), ALLOCATABLE::SP_CI (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSP_CID
  TYPE (TYPE_SFL_CANRI)::YSP_CI
  REAL (KIND=JPRB), ALLOCATABLE::SD_XP (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_XPD
  TYPE (TYPE_SFL_VPRECIP)::YSD_XP
  REAL (KIND=JPRB), ALLOCATABLE::SD_XP2 (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_XP2D
  TYPE (TYPE_SFL_VPRECIP2)::YSD_XP2
  REAL (KIND=JPRB), ALLOCATABLE::SD_VF (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VFD
  TYPE (TYPE_SFL_VARSF)::YSD_VF
  REAL (KIND=JPRB), ALLOCATABLE::SD_VP (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VPD
  TYPE (TYPE_SFL_VCLIP)::YSD_VP
  REAL (KIND=JPRB), ALLOCATABLE::SD_VV (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VVD
  TYPE (TYPE_SFL_VCLIV)::YSD_VV
  REAL (KIND=JPRB), ALLOCATABLE::SD_VN (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VND
  TYPE (TYPE_SFL_VCLIN)::YSD_VN
  REAL (KIND=JPRB), ALLOCATABLE::SD_VH (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VHD
  TYPE (TYPE_SFL_VCLIH)::YSD_VH
  REAL (KIND=JPRB), ALLOCATABLE::SD_VK (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VKD
  TYPE (TYPE_SFL_VCLIK)::YSD_VK
  REAL (KIND=JPRB), ALLOCATABLE::SD_VA (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VAD
  TYPE (TYPE_SFL_VCLIA)::YSD_VA
  REAL (KIND=JPRB), ALLOCATABLE::SD_VC (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VCD
  TYPE (TYPE_SFL_VO3ABC)::YSD_VC
  REAL (KIND=JPRB), ALLOCATABLE::SD_V2 (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_V2D
  TYPE (TYPE_SFL_VDIAGO2)::YSD_V2
  REAL (KIND=JPRB), ALLOCATABLE::SD_V3 (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_V3D
  TYPE (TYPE_SFL_VDIAGO3)::YSD_V3
  REAL (KIND=JPRB), ALLOCATABLE::SD_VD (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VDD
  TYPE (TYPE_SFL_VDIAG)::YSD_VD
  REAL (KIND=JPRB), ALLOCATABLE::SD_SM (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_SMD
  TYPE (TYPE_SFL_SATSIM)::YSD_SM
  REAL (KIND=JPRB), ALLOCATABLE::SD_WS (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_WSD
  TYPE (TYPE_SFL_WAVES)::YSD_WS
  REAL (KIND=JPRB), ALLOCATABLE::SD_WW (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_WWD
  TYPE (TYPE_SFL_WAM)::YSD_WW
  REAL (KIND=JPRB), ALLOCATABLE::SD_VX (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_VXD
  TYPE (TYPE_SFL_VCLIX)::YSD_VX
  REAL (KIND=JPRB), ALLOCATABLE::SD_XA (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_XAD
  TYPE (TYPE_SFL_VEXTRA)::YSD_XA
  REAL (KIND=JPRB), ALLOCATABLE::SD_DI (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_DID
  TYPE (TYPE_SFL_VEXTRDI)::YSD_DI
  REAL (KIND=JPRB), ALLOCATABLE::SD_XR (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_XRD
  TYPE (TYPE_SFL_VEXTRA)::YSD_XR
  REAL (KIND=JPRB), ALLOCATABLE::SD_X2 (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_X2D
  TYPE (TYPE_SFL_VEXTR2)::YSD_X2
  REAL (KIND=JPRB), ALLOCATABLE::SD_SFL (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_SFLD
  TYPE (TYPE_SFL_SFLUX)::YSD_SFL
  REAL (KIND=JPRB), ALLOCATABLE::SD_SFO (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_SFOD
  TYPE (TYPE_SFL_SFORC)::YSD_SFO
  REAL (KIND=JPRB), ALLOCATABLE::SD_PF (:,:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_PFD
  TYPE (TYPE_SFL_VEXTRA)::YSD_PF
  REAL (KIND=JPRB), ALLOCATABLE::SD_OC (:,:,:)
  TYPE (TYPE_SURF_GEN)::YSD_OCD
  TYPE (TYPE_SFL_OCE)::YSD_OC
  INTEGER (KIND=JPIM)::NGP5_OOPS
  INTEGER (KIND=JPIM)::NTRAJ_CST_OOPS
ENDTYPE TSURF

CONTAINS






















ENDMODULE SURFACE_FIELDS_MIX
