INTERFACE
SUBROUTINE TRANSFER_CLOUD_FIELDS(YDMODEL, YDVARS, YDCPG_OPTS, YDCPG_BNDS)
USE TYPE_MODEL         , ONLY : MODEL
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE CPG_OPTS_TYPE_MOD  , ONLY : CPG_OPTS_TYPE, CPG_BNDS_TYPE
IMPLICIT NONE
TYPE(MODEL)          , INTENT(IN)    :: YDMODEL
TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
TYPE(CPG_OPTS_TYPE)  , INTENT(IN)    :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE)  , INTENT(IN)    :: YDCPG_BNDS
END SUBROUTINE TRANSFER_CLOUD_FIELDS




SUBROUTINE TRANSFER_CLOUD_FIELDS_PARALLEL (YDMODEL, YDVARS, YDCPG_OPTS, YDCPG_BNDS)
USE TYPE_MODEL,ONLY:MODEL
USE FIELD_VARIABLES_MOD,ONLY:FIELD_VARIABLES
USE CPG_OPTS_TYPE_MOD,ONLY:CPG_OPTS_TYPE, CPG_BNDS_TYPE

IMPLICIT NONE

TYPE (MODEL), INTENT (IN)::YDMODEL
TYPE (FIELD_VARIABLES), INTENT (INOUT)::YDVARS
TYPE (CPG_OPTS_TYPE), INTENT (IN)::YDCPG_OPTS
TYPE (CPG_BNDS_TYPE), INTENT (IN)::YDCPG_BNDS

END SUBROUTINE TRANSFER_CLOUD_FIELDS_PARALLEL




END INTERFACE
