MODULE YEMDYN
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE::TEDYN
  REAL (KIND=JPRB), ALLOCATABLE::RDIVORE (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDIDIVE (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDITE (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDIGFLE (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDIPDE (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDIVDE (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDISPE (:)
  REAL (KIND=JPRB), ALLOCATABLE::RDSVORE (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDSDIVE (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDSVDE (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::REFILV (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::REFILD (:,:)
  LOGICAL::LESIDG
  REAL (KIND=JPRB)::RTHRESIDG
  REAL (KIND=JPRB)::XMALD
  REAL (KIND=JPRB)::TCDIS
ENDTYPE TEDYN

ENDMODULE YEMDYN
