MODULE YEMDIM
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TEDIM
  INTEGER (KIND=JPIM)::NSECPLG
  INTEGER (KIND=JPIM)::NBZONG
  INTEGER (KIND=JPIM)::NBZONL
  INTEGER (KIND=JPIM)::NBZONU
  INTEGER (KIND=JPIM)::NNOEXTZG
  INTEGER (KIND=JPIM)::NNOEXTZL
  INTEGER (KIND=JPIM), POINTER::NISMAX (:)=>NULL ()
  INTEGER (KIND=JPIM), POINTER::NISNAX (:)=>NULL ()
  LOGICAL::LBIPINCI
  INTEGER (KIND=JPIM)::NBIPINCIX
  INTEGER (KIND=JPIM)::NBIPINCIY
  INTEGER (KIND=JPIM)::NEDOM
ENDTYPE TEDIM

ENDMODULE YEMDIM
