MODULE YEMGSL
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE::TEGSL
  REAL (KIND=JPRB)::RIPORE
  REAL (KIND=JPRB)::RJPORE
  REAL (KIND=JPRB)::REGPK
  REAL (KIND=JPRB)::RNOBILE
  REAL (KIND=JPRB)::RHSUD
  REAL (KIND=JPRB)::RMERCAT
  REAL (KIND=JPRB)::RLON0R
  REAL (KIND=JPRB)::RELONC
  REAL (KIND=JPRB)::RELATC
ENDTYPE TEGSL

ENDMODULE YEMGSL
