MODULE YEMGEO
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE::TEGEO
  REAL (KIND=JPRB)::ERPK
  REAL (KIND=JPRB)::ELON1
  REAL (KIND=JPRB)::ELAT1
  REAL (KIND=JPRB)::ELON2
  REAL (KIND=JPRB)::ELAT2
  REAL (KIND=JPRB)::ELON0
  REAL (KIND=JPRB)::ELAT0
  REAL (KIND=JPRB)::ELONC
  REAL (KIND=JPRB)::ELATC
  REAL (KIND=JPRB)::EDELX
  REAL (KIND=JPRB)::EDELY
  REAL (KIND=JPRB)::ELX
  REAL (KIND=JPRB)::ELY
  REAL (KIND=JPRB)::EXWN
  REAL (KIND=JPRB)::EYWN
  REAL (KIND=JPRB)::RCORI_ACAD
  REAL (KIND=JPRB)::RLAT_ACAD
  REAL (KIND=JPRB)::RLON_ACAD
  LOGICAL::LMAP
  LOGICAL::LMRT
  LOGICAL::LREDEL_IN_METRES
ENDTYPE TEGEO

ENDMODULE YEMGEO
