MODULE YEMLBC_GEO
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TELBC_GEO
  INTEGER (KIND=JPIM), ALLOCATABLE::NIND_LIST (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NIND_LEN (:)
  INTEGER (KIND=JPIM)::NCPLBLKS
  INTEGER (KIND=JPIM), ALLOCATABLE::MPTRCPLBLK (:)
ENDTYPE TELBC_GEO

ENDMODULE YEMLBC_GEO
