MODULE YEMLBC_MODEL
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE MODEL_GENERAL_CONF_MOD,ONLY:MODEL_GENERAL_CONF_TYPE
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE YOMDFI,ONLY:NSTDFI, NSTDFIA, RTDFI, RTDFIA
USE YOMCT0,ONLY:LRPLANE, LALLOPR, LCANARI, NCONF, LELAM
USE YOMGMV,ONLY:TGMV
USE YOMINI,ONLY:LDFI
USE YOMLUN,ONLY:NULOUT, NULNAM
USE YOMMP0,ONLY:MYSETB, MYSETV, LOUTPUT

IMPLICIT NONE

SAVE

TYPE TGMVSTENC
  INTEGER (KIND=JPIM)::MSP
  INTEGER (KIND=JPIM)::MSPL
  INTEGER (KIND=JPIM)::MSPM
  INTEGER (KIND=JPIM)::NDIM
  INTEGER (KIND=JPIM)::NDIMT
ENDTYPE TGMVSTENC


TYPE TGMVCPL
  INTEGER (KIND=JPIM)::MU
  INTEGER (KIND=JPIM)::MV
  INTEGER (KIND=JPIM)::MT
  INTEGER (KIND=JPIM)::MSPD
  INTEGER (KIND=JPIM)::MSVD
  INTEGER (KIND=JPIM)::MNHX
  INTEGER (KIND=JPIM)::MDIV
  INTEGER (KIND=JPIM)::MTL
  INTEGER (KIND=JPIM)::MTM
  INTEGER (KIND=JPIM)::MSPDL
  INTEGER (KIND=JPIM)::MSPDM
  INTEGER (KIND=JPIM)::NDIM
  INTEGER (KIND=JPIM)::NDIMT
ENDTYPE TGMVCPL


TYPE TGMVSCPL
  INTEGER (KIND=JPIM)::MSP
  INTEGER (KIND=JPIM)::MSPL
  INTEGER (KIND=JPIM)::MSPM
  INTEGER (KIND=JPIM)::NDIM
  INTEGER (KIND=JPIM)::NDIMT
ENDTYPE TGMVSCPL

INTEGER (KIND=JPIM), PARAMETER::JPLSGT=20
INTEGER (KIND=JPIM), PARAMETER::JPALFNM=31

TYPE::TELBC_MODEL
  LOGICAL::LTENC
  LOGICAL::LALLTC
  LOGICAL::LRFIRST
  INTEGER (KIND=JPIM)::NBICOU
  INTEGER (KIND=JPIM)::NBICOT
  INTEGER (KIND=JPIM)::NBICPD
  INTEGER (KIND=JPIM)::NBICVD
  INTEGER (KIND=JPIM)::NBICNHX
  INTEGER (KIND=JPIM)::NBICOP
  INTEGER (KIND=JPIM)::NECRIPL
  LOGICAL::LQCPL
  LOGICAL::LCCPL
  INTEGER (KIND=JPIM)::NECOTL
  INTEGER (KIND=JPIM)::NECOAD
  LOGICAL::LE0COTA
  LOGICAL::LEREADINI
  INTEGER (KIND=JPIM)::N1LSG
  INTEGER (KIND=JPIM)::NFRLSG
  INTEGER (KIND=JPIM)::NLSGTS (0:JPLSGT)
  LOGICAL::LRDLSG
  LOGICAL::LESPCPL
  LOGICAL::LSPTENC
  LOGICAL::LUNBC
  LOGICAL::LECOBI
  TYPE (TGMVSTENC)::YYTGMVSTENC
  TYPE (TGMVCPL)::YYTGMVCPL
  TYPE (TGMVSCPL)::YYTGMVSCPL
  INTEGER (KIND=JPIM)::NDIMCPL
  INTEGER (KIND=JPIM)::NGALEF
  INTEGER (KIND=JPIM)::NEFRCL
  INTEGER (KIND=JPIM)::NETLS1
  REAL (KIND=JPRB)::TEFRCL
  REAL (KIND=JPRB)::EPA_GMV (JPALFNM)
  REAL (KIND=JPRB)::EPA_GMVS (JPALFNM)
  REAL (KIND=JPRB)::EPA_GFL (JPALFNM)
  REAL (KIND=JPRB), ALLOCATABLE::EALFA_GMV (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EALFA_GMVS (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EALFA_GFL (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EALFA_TENC (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EALFAGT3GMV (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EALFAGT3GMVS (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EALFAGT3GFL (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EALFAU_GMV (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EALFAU_GFL (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GMGT3 (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GMGT4 (:)
  REAL (KIND=JPRB), ALLOCATABLE::EWB (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EWBDFIFW (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::EWBDFIBW (:,:,:,:)
  REAL (KIND=JPRB)::RTENC
  LOGICAL, ALLOCATABLE::LNUDSPGFL (:)
  LOGICAL::LSPNUSPDL
  REAL (KIND=JPRB)::RNUDTFRAC
  INTEGER (KIND=JPIM)::NEFRSPCPL
  INTEGER (KIND=JPIM)::NEK0
  INTEGER (KIND=JPIM)::NEK1
  INTEGER (KIND=JPIM)::NEN1
  INTEGER (KIND=JPIM)::NEN2
  REAL (KIND=JPRB)::SPNUDVOR
  REAL (KIND=JPRB)::SPNUDDIV
  REAL (KIND=JPRB)::SPNUDT
  REAL (KIND=JPRB)::SPNUDQ
  REAL (KIND=JPRB)::SPNUDSP
  REAL (KIND=JPRB)::RNUTENC
ENDTYPE TELBC_MODEL

#include "abor1.intfb.h"
CONTAINS




ENDMODULE YEMLBC_MODEL
