MODULE YEMLAP
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TLEP
  INTEGER (KIND=JPIM), ALLOCATABLE::NCPL2M (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NCPL4M (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NCPLM (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NCPL2N (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NCPL4N (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NCPLN (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLEPDIN (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLEPINN (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLEPDIM (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLEPINM (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NESM0 (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NESPZERO (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NESM0G (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPME (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPNE (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MVALUE (:)
ENDTYPE TLEP

ENDMODULE YEMLAP
