MODULE YEMMP
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TEMMP
  INTEGER (KIND=JPIM), POINTER::NEPROCN (:)=>NULL ()
  INTEGER (KIND=JPIM)::NUEMP
  INTEGER (KIND=JPIM), POINTER::MYENS (:)=>NULL ()
  INTEGER (KIND=JPIM), POINTER::NUEMPP (:)=>NULL ()
  INTEGER (KIND=JPIM), POINTER::NEALLNS (:)=>NULL ()
  INTEGER (KIND=JPIM), POINTER::NEPTRNS (:)=>NULL ()
ENDTYPE TEMMP

ENDMODULE YEMMP
