MODULE YOE_AERODIAG
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::NPAERODIAG=8
INTEGER (KIND=JPIM), PARAMETER::NPAERAOT=3
INTEGER (KIND=JPIM), PARAMETER::NPAERLISI_VAR=6
INTEGER (KIND=JPIM), PARAMETER::NPAERLISI_WVL=3
INTEGER (KIND=JPIM), PARAMETER::NPAERLISI=NPAERLISI_VAR*NPAERLISI_WVL
INTEGER (KIND=JPIM), PARAMETER::JPAERODIAG_SRC=1
INTEGER (KIND=JPIM), PARAMETER::JPAERODIAG_DDP=2
INTEGER (KIND=JPIM), PARAMETER::JPAERODIAG_SDM=3
INTEGER (KIND=JPIM), PARAMETER::JPAERODIAG_WDL=4
INTEGER (KIND=JPIM), PARAMETER::JPAERODIAG_WDC=5
INTEGER (KIND=JPIM), PARAMETER::JPAERODIAG_NGT=6
INTEGER (KIND=JPIM), PARAMETER::JPAERODIAG_OD=7
INTEGER (KIND=JPIM), PARAMETER::JPAERODIAG_MSS=8
CHARACTER (LEN=3), PARAMETER::CPAERODIAG_LABEL (8)=(/&
&'SRC','DDP','SDM','WDL','WDC','NGT','OD.','TC.'/)
INTEGER (KIND=JPIM), PARAMETER::JPAERAOT_TOTAL=1
INTEGER (KIND=JPIM), PARAMETER::JPAERAOT_NATURAL=2
INTEGER (KIND=JPIM), PARAMETER::JPAERAOT_ANTHRO=3
INTEGER (KIND=JPIM), PARAMETER::JPAERLISI_EXT=1
INTEGER (KIND=JPIM), PARAMETER::JPAERLISI_SSA=2
INTEGER (KIND=JPIM), PARAMETER::JPAERLISI_BSTOA=3
INTEGER (KIND=JPIM), PARAMETER::JPAERLISI_BSGND=4
INTEGER (KIND=JPIM), PARAMETER::JPAERLISI_MOLBSC=5
INTEGER (KIND=JPIM), PARAMETER::JPAERLISI_AERBSC=6
INTEGER (KIND=JPIM), PARAMETER::JPAERLISI_355=1
INTEGER (KIND=JPIM), PARAMETER::JPAERLISI_532=2
INTEGER (KIND=JPIM), PARAMETER::JPAERLISI_1064=3
INTEGER (KIND=JPIM), PARAMETER::NPAERO_WVL_DIAG=20
INTEGER (KIND=JPIM), PARAMETER::NPAERO_WVL_DIAG_TYPES=5

TYPE TYPE_AERO_WVL_DIAG
  INTEGER (KIND=JPIM)::IWVL
  INTEGER (KIND=JPIM)::IGRIBDIAG (NPAERO_WVL_DIAG_TYPES)
ENDTYPE TYPE_AERO_WVL_DIAG

INTEGER (KIND=JPIM), PARAMETER::JPAERO_WVL_AOD=1
INTEGER (KIND=JPIM), PARAMETER::JPAERO_WVL_AODABS=2
INTEGER (KIND=JPIM), PARAMETER::JPAERO_WVL_AODFM=3
INTEGER (KIND=JPIM), PARAMETER::JPAERO_WVL_SSA=4
INTEGER (KIND=JPIM), PARAMETER::JPAERO_WVL_ASSIMETRY=5
CHARACTER (LEN=8), PARAMETER::CPAERO_WVL_DIAG_LABEL (5)=(/'OptDepth&
&','AbOptDep','FMOptDep','SScatAlb','Asymmetr'/)
ENDMODULE YOE_AERODIAG
