
MODULE YOE_SPECTRAL_PLANCK
USE PARKIND1,ONLY:JPRB, JPRD, JPIM
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE

TYPE TSPECTRALPLANCK
  INTEGER (KIND=JPIM)::NINTERVALS
  INTEGER (KIND=JPIM)::NTEMPS
  REAL (KIND=JPRB)::TEMP1, DTEMP
  REAL (KIND=JPRB), ALLOCATABLE::PLANCK_LUT (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::WAVLEN_BOUND (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::INTERVAL_MAP (:)
  
  
  
  
  
ENDTYPE TSPECTRALPLANCK

#include "abor1.intfb.h"
CONTAINS




ENDMODULE YOE_SPECTRAL_PLANCK
