MODULE YOE_PHYS_MWAVE
USE PARKIND1,ONLY:JPRB, JPIM
USE FIELD_MODULE

IMPLICIT NONE



TYPE, PUBLIC::TEPHYSMWAVE
  LOGICAL::LPHYS_MWAVE_FILLED_IN=.FALSE.
  REAL (KIND=JPRB), POINTER::PHYS_MWAVE (:,:,:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER::P (:,:,:)=>NULL ()
  CLASS (FIELD_4RB), POINTER::F_PHYS_MWAVE=>NULL ()
  
  
  
  
  
  
ENDTYPE TEPHYSMWAVE

INTEGER (KIND=JPIM), PUBLIC::N_PHYS_MWAVE
CONTAINS





ENDMODULE YOE_PHYS_MWAVE
