MODULE YOE_CUCONVCA
USE PARKIND1,ONLY:JPIM, JPRB
USE RANDOM_NUMBERS_MIX,ONLY:RANDOMNUMBERSTREAM

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM)::NIJH=4
INTEGER (KIND=JPIM), PARAMETER::NBMAX=8

TYPE::TECUCONVCA
  TYPE (RANDOMNUMBERSTREAM)::YD_RANDOM_STREAM_CA
  INTEGER (KIND=JPIM)::NLIVES
  INTEGER (KIND=JPIM)::NFERTYRS
  INTEGER (KIND=JPIM)::NSPINUP
  INTEGER (KIND=JPIM), ALLOCATABLE::NCELLCU (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NFERTCU (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NBLS (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NBSS (:,:,:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NRNBLS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NRNBSS (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NBEW (:,:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NBNS (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RCUCONVCA (:)
  REAL (KIND=JPRB), ALLOCATABLE::RNLCONVCA (:)
  REAL (KIND=JPRB), ALLOCATABLE::RCAPECONVCA (:)
  REAL (KIND=JPRB), ALLOCATABLE::RWASALIVE (:)
  REAL (KIND=JPRB), ALLOCATABLE::RWGHTCU (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLATLONNBLS (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RLATLONNBSS (:,:,:,:)
  REAL (KIND=JPRB)::RPROB_SURVIVE (0:8, 0:8)
  REAL (KIND=JPRB)::RPROB_BIRTH (0:8, 0:8)
  REAL (KIND=JPRB)::RPROB_FUN_FERT_S (0:16)
  REAL (KIND=JPRB)::RPROB_FUN_UW_DW_S (0:16)
  REAL (KIND=JPRB)::RPROB_FUN_FERT_B (0:16)
  REAL (KIND=JPRB)::RPROB_FUN_UW_DW_B (0:16)
  REAL (KIND=JPRB), ALLOCATABLE::RLONDEP (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RLATDEP (:,:,:)
  REAL (KIND=JPRB)::RCA_SEEDPROB
  REAL (KIND=JPRB)::RCADELX
  LOGICAL::LCUCONV_CA
  LOGICAL::LCA_ADVECT
  LOGICAL::LCA_GLOBAL
  LOGICAL::LCA_SMOOTH
  LOGICAL::LCA_TEST, LCA_ADVTEST
  LOGICAL::LCA_RANTROP
  LOGICAL::LCA_NBDEBUG
  LOGICAL::LCA_EXTRACT
  CHARACTER (LEN=10)::CA_FORC
  CHARACTER (LEN=10)::CA_WIND
  CHARACTER (LEN=10)::CA_PROB
  INTEGER (KIND=JPIM)::NFRCASEED
  INTEGER (KIND=JPIM)::NTESTPROC, NTESTGP
  INTEGER (KIND=JPIM)::NDXUNREAL, NDYUNREAL
  REAL (KIND=JPRB), ALLOCATABLE::SLLONG (:), SLLAT (:)
  REAL (KIND=JPRB), ALLOCATABLE::SLDLONG (:), SLDLAT (:), SLDDLAT (:)
  
ENDTYPE TECUCONVCA

CONTAINS










ENDMODULE YOE_CUCONVCA
