MODULE YOEAERSNK
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE

TYPE::TEAERSNK
  INTEGER (KIND=JPIM)::NDRYDEPVEL_DYN
  INTEGER (KIND=JPIM)::NDRYDEP
  REAL (KIND=JPRB)::R_R, R_S
  REAL (KIND=JPRB)::RAERTS (21)
  REAL (KIND=JPRB)::RFRAER
  REAL (KIND=JPRB)::RRHTAB (12)
  REAL (KIND=JPRB)::RRHTAB15 (15)
  REAL (KIND=JPRB)::RSSGROWTH_RHTAB (12)
  REAL (KIND=JPRB)::RMMD_STRATSULF_BACK
  REAL (KIND=JPRB)::RMMD_STRATSULF_VOLC
  REAL (KIND=JPRB)::RSIGMA_STRATSULF_VOLC
  REAL (KIND=JPRB)::RRHO_STRATSULF
  REAL (KIND=JPRB)::RSOAGROWTH_RHTAB (12)
  REAL (KIND=JPRB)::RSO4GROWTH_RHTAB (12)
  REAL (KIND=JPRB)::ROMGROWTH_RHTAB (12)
  REAL (KIND=JPRB)::RNIGROWTH_RHTAB (12)
  REAL (KIND=JPRB)::RAMGROWTH_RHTAB (12)
  REAL (KIND=JPRB)::RSSDENS_RHTAB (12)
  REAL (KIND=JPRB)::RSSGROWTH_RHTAB15 (15)
  REAL (KIND=JPRB)::RSSDENS_RHTAB15 (15)
  REAL (KIND=JPRB)::RRHO_DD (9)
  REAL (KIND=JPRB)::RRHO_SO4
  REAL (KIND=JPRB)::RRHO_SOA
  REAL (KIND=JPRB)::RRHO_OM
  REAL (KIND=JPRB)::RRHO_AM
  REAL (KIND=JPRB)::RRHO_BC
  REAL (KIND=JPRB)::RRHO_ASH
  REAL (KIND=JPRB)::RRHO_NI (2)
  REAL (KIND=JPRB)::RRHO_SS (9)
  REAL (KIND=JPRB)::RMMD_DD (9)
  REAL (KIND=JPRB)::RMMD_SO4
  REAL (KIND=JPRB)::RMMD_SOA
  REAL (KIND=JPRB)::RMMD_OM
  REAL (KIND=JPRB)::RMMD_AM
  REAL (KIND=JPRB)::RMMD_BC
  REAL (KIND=JPRB)::RMMD_ASH
  REAL (KIND=JPRB)::RMMD_NI (2)
  REAL (KIND=JPRB)::RMMD_SS (9)
  REAL (KIND=JPRB)::RHO_WAT, RHO_ICE
  REAL (KIND=JPRB)::RHAMAKER
  REAL (KIND=JPRB)::RSO2CV1, RSO2CV2, RSUCV1, RSUCV2, RVSO2CV1, RVSO2CV2
  
ENDTYPE TEAERSNK

TYPE (TEAERSNK), POINTER::YREAERSNK=>NULL ()
CONTAINS

ENDMODULE YOEAERSNK
