MODULE YOEAERSRC
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TEAERSRC
  INTEGER (KIND=JPIM)::NDDUST, NSSALT, NAERWND, NDMSO, NPIST, NSO4SCHEME
  INTEGER (KIND=JPIM)::ISIZE_DD, INATS_DD, INSOIL_DD, INSOILMODE_DD
  LOGICAL::LEPAERO, LAEROMIN, LOCNDMS
  LOGICAL::LDUST_SFXSOIL
  REAL (KIND=JPRB)::RGELAV, RGEMUV, RDGLAV, RDGMUV
  REAL (KIND=JPRB)::RCLONV, RSLONV, RDCLONV, RDSLONV
  REAL (KIND=JPRB)::RLATVOL, RLONVOL
  REAL (KIND=JPRB)::RFCTDU, RFCTSS, RFCTDUR, RFCTSSR
  REAL (KIND=JPRB)::RAERDUB, RDMSMIN
  REAL (KIND=JPRB)::RCODECA, RSIDECA, RCOVSRA, RSIVSRA
  REAL (KIND=JPRB)::RCOEFDUST
  REAL (KIND=JPRB)::RSSFLX (9)
  REAL (KIND=JPRB)::RDDUSRC (9)
  REAL (KIND=JPRB), DIMENSION (3, 12)::RMMD_SOIL, RPCENT_SOIL, RSIGMA_SOIL
  REAL (KIND=JPRB)::RTRSIZE_DD (10), RAEROSIZE_DD (13)
  REAL (KIND=JPRB)::RZ0SAL, REPSDD
  REAL (KIND=JPRB)::RCV_KOK, RLAMBDA_KOK, RSIGMAS_KOK, RDS_KOK
  
ENDTYPE TEAERSRC

TYPE (TEAERSRC), POINTER::YREAERSRC=>NULL ()
CONTAINS

ENDMODULE YOEAERSRC
