MODULE YOEAERRADDESC
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER, PRIVATE::JPMAX_STRING_LEN=512
INTEGER (KIND=JPIM), PARAMETER::ICLIMATOLOGICAL=0, IPROGNOSTIC=1, IPARAMETRIC=2

TYPE::TAER_RAD_DESC1
  CHARACTER (LEN=JPMAX_STRING_LEN)::NAME
  INTEGER (KIND=JPIM)::NSOURCE=ICLIMATOLOGICAL
  LOGICAL::LHYDROPHILIC=.FALSE.
  REAL (KIND=JPRB)::SCALING=1.0_JPRB
  CHARACTER (2)::AER_TYPE='  '
  CHARACTER (LEN=JPMAX_STRING_LEN)::OPTICS_MODEL=' '
  INTEGER (KIND=JPIM)::SIZE_BIN=0
  INTEGER (KIND=JPIM)::PARAMETRIC_SCHEME=-1
ENDTYPE TAER_RAD_DESC1


TYPE::TAER_RAD_DESC
  TYPE (TAER_RAD_DESC1), DIMENSION (:), ALLOCATABLE::DATA
  INTEGER (KIND=JPIM)::NAEROSOL
  INTEGER (KIND=JPIM)::NDIAGNOSTIC
  INTEGER (KIND=JPIM)::NPROGNOSTIC
  INTEGER (KIND=JPIM)::NPARAMETRIC
  INTEGER (KIND=JPIM)::NCLIMATOLOGICAL
  INTEGER (KIND=JPIM), ALLOCATABLE::PROG_INDEX (:)
  
  
  
  
  
  
  
  
  
  
  
  
  
  
ENDTYPE TAER_RAD_DESC

CONTAINS













ENDMODULE YOEAERRADDESC
