
MODULE YOEAERATM
USE PARKIND1,ONLY:JPIM, JPRB
USE YOE_AERODIAG,ONLY:NPAERODIAG
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::NMAXTAER=10

TYPE::TYPE_AERO_DESC
  CHARACTER (LEN=16)::CNAME
  INTEGER (KIND=JPIM)::IGRBCODE
  INTEGER (KIND=JPIM)::NTYP
  INTEGER (KIND=JPIM)::NBIN
  INTEGER (KIND=JPIM)::IGRIBDIAG (NPAERODIAG)
  REAL (KIND=JPRB)::RDDEPVSEA
  REAL (KIND=JPRB)::RDDEPVLIC
  REAL (KIND=JPRB)::RSEDIMV
  REAL (KIND=JPRB)::RSCAVIN
  REAL (KIND=JPRB)::RSCAVBCR
  REAL (KIND=JPRB)::RSCAVBCS
  CHARACTER (LEN=16)::COPTCLASS
  CHARACTER (LEN=16)::CHYGCLASS
  INTEGER (KIND=JPIM)::IAEROCV
ENDTYPE TYPE_AERO_DESC


TYPE::TEAERATM
  INTEGER (KIND=JPIM)::NAERCONF
  INTEGER (KIND=JPIM)::NAERAGING
  INTEGER (KIND=JPIM)::NINIDAY
  INTEGER (KIND=JPIM)::NXT3DAER
  INTEGER (KIND=JPIM)::NDD1, NSS1
  INTEGER (KIND=JPIM)::NBCOPTP, NDDOPTP, NOMOPTP, NSSOPTP, NSUOPTP
  INTEGER (KIND=JPIM)::NVISWL
  INTEGER (KIND=JPIM)::NTAER
  INTEGER (KIND=JPIM)::NTYPAER (NMAXTAER)
  INTEGER (KIND=JPIM)::NAER_BLNUCL
  INTEGER (KIND=JPIM)::NAERSCAV
  INTEGER (KIND=JPIM)::ITLISTWAVLCPL (14)
  REAL (KIND=JPRB)::RGRATE
  REAL (KIND=JPRB)::REPSCAER
  LOGICAL::LAERCLIMG, LAERCLIMZ, LAERCLIST, LAERDRYDP, LAERHYGRO, LAERLISI
  LOGICAL::LAERNGAT, LAERSEDIM, LAERSURF, LAERELVS, LAER6SDIA, LAERSEDIMSS
  LOGICAL::LAERGTOP, LAERRAD, LAERCCN, LAEROPT (9), LAERINIT, LAERVOL
  LOGICAL::LAERCSTR, LAERDIAG1, LAERDIAG2, LAERRRTM, LAERFILLCLIM, LAERUVP, LPROGAERVIS
  LOGICAL::LAEREXTR, LAERGBUD, LAERPRNT
  LOGICAL::LAERNITRATE
  LOGICAL::LAERRADCPL
  LOGICAL::LSEASALT_RH80
  LOGICAL::LAERDUSTSOURCE
  LOGICAL::LAERDUSTSIZEVAR
  LOGICAL::LAERDUST_NEWBIN
  LOGICAL::LWAVLOUT (14)
  REAL (KIND=JPRB)::RSS_DRY_DIAFAC, RSS_DRY_DENSFAC, RSS_DRY_MASSFAC
  REAL (KIND=JPRB)::RSS_RH80_DIAFAC, RSS_RH80_DENSFAC, RSS_RH80_MASSFAC
  REAL (KIND=JPRB)::RAERDUST_REBOUND
  TYPE (TYPE_AERO_DESC), POINTER::YAERO_DESC (:)=>NULL ()
  
ENDTYPE TEAERATM

TYPE (TEAERATM), POINTER::YREAERATM=>NULL ()
CONTAINS

ENDMODULE YOEAERATM
