MODULE YOEAERLID
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TEAERLID
  INTEGER (KIND=JPIM)::NAELID
  INTEGER (KIND=JPIM)::NWLID, NAERLISI, JWLID (3)
  REAL (KIND=JPRB)::RWLID (3)
  REAL (KIND=JPRB)::RLICO2 (6)
  REAL (KIND=JPRB)::RLIO2 (6)
  REAL (KIND=JPRB)::RLINO2 (5, 3)
  REAL (KIND=JPRB)::RLIO3 (5, 3)
  REAL (KIND=JPRB)::RLICLS, RLIDELT, RLINS, RLIPREF, RLITREF, RLIT0
  REAL (KIND=JPRB)::RLIDDZ
  
ENDTYPE TEAERLID

TYPE (TEAERLID), POINTER::YREAERLID=>NULL ()
CONTAINS

ENDMODULE YOEAERLID
