MODULE YOEAERC
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TEAERC
  REAL (KIND=JPRB), ALLOCATABLE::COLUMN_MASS_MON (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SCALE_HEIGHT_MON (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::COLUMN_MASS (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::CUM_FRACTION (:,:)
  CHARACTER (2), ALLOCATABLE::AER_TYPE (:)
  REAL (KIND=JPRB), ALLOCATABLE, DIMENSION (:,:,:,:)::MMR_MON1
  REAL (KIND=JPRB), ALLOCATABLE, DIMENSION (:,:,:,:)::MMR_MON2
  REAL (KIND=JPRB), POINTER, DIMENSION (:,:,:)::PRESSURE_MON1
  REAL (KIND=JPRB), POINTER, DIMENSION (:,:,:)::PRESSURE_MON2
  REAL (KIND=JPRB), ALLOCATABLE, DIMENSION (:,:,:,:)::MMR
  REAL (KIND=JPRB), ALLOCATABLE, DIMENSION (:,:,:)::PRESSURE
  INTEGER (KIND=JPIM), ALLOCATABLE::EPOCH (:)
  INTEGER (KIND=JPIM)::YEAR1, YEAR2, MON1, MON2
  CHARACTER (LEN=512)::FILE_NAME
  CHARACTER (LEN=128), ALLOCATABLE::VAR_NAME (:)
  LOGICAL, ALLOCATABLE::IS_SPECIES_4D (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::ISPECIES_INDEX (:)
  INTEGER (KIND=JPIM)::NLAT=0, NLON=0, NLEV=0, NMON=0, NAER=0
  REAL (KIND=JPRB)::LAT1=0.0_JPRB, LON1=0.0_JPRB
  REAL (KIND=JPRB)::DLAT=0.0_JPRB, DLON=0.0_JPRB
  LOGICAL::IS_INITIALISED=.FALSE.
  INTEGER (KIND=JPIM)::DIMENSIONALITY=2
  
  
  
  
  
  
  
  
  
ENDTYPE TEAERC

REAL (KIND=JPRB), PARAMETER::RPRESSURE_SCALE_HEIGHT=8434.0_JPRB
#include "abor1.intfb.h"
CONTAINS










ENDMODULE YOEAERC
