MODULE YOEAERD
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE::TEAERD
  REAL (KIND=JPRB), ALLOCATABLE::CVDAES (:)
  REAL (KIND=JPRB), ALLOCATABLE::CVDAEL (:)
  REAL (KIND=JPRB), ALLOCATABLE::CVDAEU (:)
  REAL (KIND=JPRB), ALLOCATABLE::CVDAED (:)
  REAL (KIND=JPRB)::RAESC (66)
  REAL (KIND=JPRB)::RAESS (55)
  REAL (KIND=JPRB)::RAELC (66)
  REAL (KIND=JPRB)::RAELS (55)
  REAL (KIND=JPRB)::RAEUC (66)
  REAL (KIND=JPRB)::RAEUS (55)
  REAL (KIND=JPRB)::RAEDC (66)
  REAL (KIND=JPRB)::RAEDS (55)
  REAL (KIND=JPRB)::RCAEOPS
  REAL (KIND=JPRB)::RCAEOPL
  REAL (KIND=JPRB)::RCAEOPU
  REAL (KIND=JPRB)::RCAEOPD
  REAL (KIND=JPRB)::RCTRBGA
  REAL (KIND=JPRB)::RCVOBGA
  REAL (KIND=JPRB)::RCSTBGA
  REAL (KIND=JPRB)::RCTRPT
  REAL (KIND=JPRB)::RCAEADK (3)
  REAL (KIND=JPRB)::RCAEADM
  REAL (KIND=JPRB)::RCAEROS
  
ENDTYPE TEAERD

CONTAINS

ENDMODULE YOEAERD
