MODULE YOEAERVOL
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TEAERVOL
  INTEGER (KIND=JPIM)::NAERVOLC
  INTEGER (KIND=JPIM)::NAERVOLE
  INTEGER (KIND=JPIM)::NINTERPT
  INTEGER (KIND=JPIM)::NTVOLC
  INTEGER (KIND=JPIM)::NVOLERUP
  INTEGER (KIND=JPIM)::NVOLHOMO
  INTEGER (KIND=JPIM)::NVOLOPTP
  INTEGER (KIND=JPIM)::NVOLERUZ (100)
  INTEGER (KIND=JPIM)::NVOLDATS (100)
  INTEGER (KIND=JPIM)::NVOLDATE (100)
  REAL (KIND=JPRB)::RAERVOLC (100, 8)
  REAL (KIND=JPRB)::RAERVOLE (100, 8)
  REAL (KIND=JPRB)::RVOLERUZ (100)
  REAL (KIND=JPRB)::RVSEDVOL, RVDEPVOL, RWDEPVOL
  
ENDTYPE TEAERVOL

TYPE (TEAERVOL), POINTER::YREAERVOL=>NULL ()
CONTAINS

ENDMODULE YOEAERVOL
