
MODULE YOECLD
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE::TECLD
  REAL (KIND=JPRB), ALLOCATABLE::CETA (:)
  REAL (KIND=JPRB)::RANVA
  REAL (KIND=JPRB)::RANVB
  REAL (KIND=JPRB)::RANVH
  REAL (KIND=JPRB)::RCCA
  REAL (KIND=JPRB)::RCCB
  REAL (KIND=JPRB)::RCCC
  REAL (KIND=JPRB)::RCFCT
  REAL (KIND=JPRB)::RCLWMR
  REAL (KIND=JPRB)::RCSCAL
  REAL (KIND=JPRB)::RDECORR_CF
  REAL (KIND=JPRB)::RDECORR_CW
  REAL (KIND=JPRB)::RETAHB
  REAL (KIND=JPRB)::RETAMB
  REAL (KIND=JPRB)::RLOIA
  REAL (KIND=JPRB)::RLOIB
  REAL (KIND=JPRB)::RLOIC
  REAL (KIND=JPRB)::RLOID
  REAL (KIND=JPRB)::RLONIA
  REAL (KIND=JPRB)::RLONIB
  REAL (KIND=JPRB)::RRHH
  REAL (KIND=JPRB)::RRHL
  REAL (KIND=JPRB)::RGAMMAS
  REAL (KIND=JPRB)::REPSCR
  REAL (KIND=JPRB)::REPSEC
  LOGICAL::LOMEGA
  
ENDTYPE TECLD

CONTAINS

ENDMODULE YOECLD
