MODULE YOECMIP
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER::NLON1_CMIP5=72
INTEGER (KIND=JPIM), PARAMETER::NLAT1_CMIP5=37
INTEGER (KIND=JPIM), PARAMETER::NLV1_CMIP5=24
INTEGER (KIND=JPIM), PARAMETER::NLON1_CMIP6=144
INTEGER (KIND=JPIM), PARAMETER::NLAT1_CMIP6=96
INTEGER (KIND=JPIM), PARAMETER::NLV1_CMIP6=66
INTEGER (KIND=JPIM), PARAMETER::NMONTH1=14

TYPE::TECMIP
  INTEGER (KIND=JPIM)::NRCP
  INTEGER (KIND=JPIM)::NO3CMIP
  INTEGER (KIND=JPIM)::NGHGCMIP
  INTEGER (KIND=JPIM)::NCMIPFIXYR
  INTEGER (KIND=JPIM)::NCURRYR=-1
  CHARACTER (LEN=260)::GHGDATADIR
  CHARACTER (LEN=260)::CSOLARDATA
  CHARACTER (LEN=260)::CO3DATADIR
  CHARACTER (LEN=80)::CO3DATAFIL
  REAL (KIND=JPRB), ALLOCATABLE::ZOZCL (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RSINC1 (:)
  REAL (KIND=JPRB), ALLOCATABLE::RPROC1 (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLATCLI (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLONCLI (:)
  REAL (KIND=JPRB), ALLOCATABLE::ROZT1 (:,:,:)
ENDTYPE TECMIP

ENDMODULE YOECMIP
