MODULE YOECUMF
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TECUMF
  REAL (KIND=JPRB)::ENTRORG
  REAL (KIND=JPRB)::GMOC1
  REAL (KIND=JPRB)::GMOC2
  REAL (KIND=JPRB)::GMOC3
  REAL (KIND=JPRB)::GMOCTAU
  REAL (KIND=JPRB)::GMOEN1
  REAL (KIND=JPRB)::GMOEN2
  REAL (KIND=JPRB)::GMOTAU1
  REAL (KIND=JPRB)::GMOTAU2
  LOGICAL::LGMO
  REAL (KIND=JPRB)::ENTRTEST
  REAL (KIND=JPRB)::ENTR_RH
  REAL (KIND=JPRB)::ENTSHALP
  REAL (KIND=JPRB)::ENTSTPC1
  REAL (KIND=JPRB)::ENTSTPC2
  REAL (KIND=JPRB)::ENTSTPC3
  REAL (KIND=JPRB)::ENTRDD
  REAL (KIND=JPRB)::DETRPEN
  REAL (KIND=JPRB)::RMFCFL
  REAL (KIND=JPRB)::RMFLIA
  REAL (KIND=JPRB)::RMFSOLUV
  REAL (KIND=JPRB)::RMFSOLTQ
  REAL (KIND=JPRB)::RMFSOLCT
  REAL (KIND=JPRB)::RMFSOLRHS
  REAL (KIND=JPRB)::RMFADVW
  REAL (KIND=JPRB)::RMFADVWDD
  REAL (KIND=JPRB)::RMFCMIN
  REAL (KIND=JPRB)::RMFDEPS
  REAL (KIND=JPRB)::RDEPTHS
  REAL (KIND=JPRB)::RPRCON
  REAL (KIND=JPRB)::RTAUA
  REAL (KIND=JPRB)::RCAPDCYCL, RTAU0
  REAL (KIND=JPRB)::RCAPQADV
  REAL (KIND=JPRB)::RMINCAPE
  REAL (KIND=JPRB)::RCPECONS
  REAL (KIND=JPRB)::RCVRFACTOR
  REAL (KIND=JPRB)::RCUCOV
  REAL (KIND=JPRB)::RTAUMEL
  REAL (KIND=JPRB)::RHEBC
  REAL (KIND=JPRB)::RUVPER
  REAL (KIND=JPRB)::RBASE0
  REAL (KIND=JPRB)::RMINCIN
  REAL (KIND=JPRB)::RXMIN
  REAL (KIND=JPRB)::RTAULIM
  REAL (KIND=JPRB)::RTAUFAC
  REAL (KIND=JPRB)::RDXMIN
  REAL (KIND=JPRB)::RDXMAX
  LOGICAL::LMFPEN
  LOGICAL::LMFSCV
  LOGICAL::LMFMID
  LOGICAL::LMFDD
  LOGICAL::LMFDUDV
  LOGICAL::LMFDSNOW
  LOGICAL::LMFWETB
  LOGICAL::LMFGLAC
  LOGICAL::LSCVLIQ
  LOGICAL::LNEWTAU
  LOGICAL::LMFENTHCONS
  LOGICAL::LMFUVDIS
  LOGICAL::LMFSMOOTH
  LOGICAL::LMFWSTAR
  LOGICAL::LMFCUCA
  LOGICAL::LMFPROFP
  INTEGER (KIND=JPIM)::NJKT1, NJKT2, NJKT3, NJKT4, NJKT5, NJKT6, NJKT7, NJKT8
  
ENDTYPE TECUMF

CONTAINS

ENDMODULE YOECUMF
