
MODULE YOECLDP
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::NCLV=5
INTEGER (KIND=JPIM), PARAMETER::NCLDQL=1
INTEGER (KIND=JPIM), PARAMETER::NCLDQI=2
INTEGER (KIND=JPIM), PARAMETER::NCLDQR=3
INTEGER (KIND=JPIM), PARAMETER::NCLDQS=4
INTEGER (KIND=JPIM), PARAMETER::NCLDQV=5
INTEGER (KIND=JPIM), PARAMETER::NPRECTYPES=12

TYPE::TECLDP
  REAL (KIND=JPRB)::RAMID
  REAL (KIND=JPRB)::RCLDIFF
  REAL (KIND=JPRB)::RCLDIFF_CONVI
  REAL (KIND=JPRB)::RCLCRIT
  REAL (KIND=JPRB)::RCLCRIT_SEA
  REAL (KIND=JPRB)::RCLCRIT_LAND
  REAL (KIND=JPRB)::RKCONV
  REAL (KIND=JPRB)::RPRC1
  REAL (KIND=JPRB)::RPRC2
  REAL (KIND=JPRB)::RCLDMAX
  REAL (KIND=JPRB)::RPECONS
  REAL (KIND=JPRB)::RVRFACTOR
  REAL (KIND=JPRB)::RPRECRHMAX
  REAL (KIND=JPRB)::RTAUMEL
  REAL (KIND=JPRB)::RAMIN
  REAL (KIND=JPRB)::RLMIN
  REAL (KIND=JPRB)::RKOOPTAU
  REAL (KIND=JPRB)::RSSICEFACTOR
  REAL (KIND=JPRB)::RCLDTOPP
  REAL (KIND=JPRB)::RLCRITSNOW
  REAL (KIND=JPRB)::RSNOWLIN1
  REAL (KIND=JPRB)::RSNOWLIN2
  REAL (KIND=JPRB)::RICEHI1
  REAL (KIND=JPRB)::RICEHI2
  REAL (KIND=JPRB)::RICEINIT
  REAL (KIND=JPRB)::RVICE
  REAL (KIND=JPRB)::RVRAIN
  REAL (KIND=JPRB)::RVSNOW
  REAL (KIND=JPRB)::RTHOMO
  REAL (KIND=JPRB)::RCOVPMIN
  REAL (KIND=JPRB)::RCCN
  REAL (KIND=JPRB)::RNICE
  REAL (KIND=JPRB)::RCCNOM
  REAL (KIND=JPRB)::RCCNSS
  REAL (KIND=JPRB)::RCCNSU
  REAL (KIND=JPRB)::RCLDTOPCF
  REAL (KIND=JPRB)::RDEPLIQREFRATE
  REAL (KIND=JPRB)::RDEPLIQREFDEPTH
  REAL (KIND=JPRB)::RCL_OVERLAPLIQICE
  REAL (KIND=JPRB)::RCL_EFFRIME
  REAL (KIND=JPRB)::RXFALLSPEEDRAIN
  REAL (KIND=JPRB)::RXFALLSPEEDICE
  REAL (KIND=JPRB)::RTAU_CLD_TLAD
  REAL (KIND=JPRB)::RCL_KKAAC
  REAL (KIND=JPRB)::RCL_KKBAC
  REAL (KIND=JPRB)::RCL_KKAAU
  REAL (KIND=JPRB)::RCL_KKBAUQ
  REAL (KIND=JPRB)::RCL_KKBAUN
  REAL (KIND=JPRB)::RCL_KK_CLOUD_NUM_SEA
  REAL (KIND=JPRB)::RCL_KK_CLOUD_NUM_LAND
  REAL (KIND=JPRB)::RCL_INHOMOGAUT
  REAL (KIND=JPRB)::RCL_INHOMOGACC
  LOGICAL::LCLOUD_INHOMOG
  REAL (KIND=JPRB)::RCL_AI
  REAL (KIND=JPRB)::RCL_BI
  REAL (KIND=JPRB)::RCL_CI
  REAL (KIND=JPRB)::RCL_DI
  REAL (KIND=JPRB)::RCL_X1I
  REAL (KIND=JPRB)::RCL_X2I
  REAL (KIND=JPRB)::RCL_X3I
  REAL (KIND=JPRB)::RCL_X4I
  REAL (KIND=JPRB)::RCL_CONST1I
  REAL (KIND=JPRB)::RCL_CONST2I
  REAL (KIND=JPRB)::RCL_CONST3I
  REAL (KIND=JPRB)::RCL_CONST4I
  REAL (KIND=JPRB)::RCL_CONST5I
  REAL (KIND=JPRB)::RCL_CONST6I
  REAL (KIND=JPRB)::RCL_CONST7I
  REAL (KIND=JPRB)::RCL_LAMBDA1I
  REAL (KIND=JPRB)::RCL_LAMBDA2I
  REAL (KIND=JPRB)::RCL_APB1
  REAL (KIND=JPRB)::RCL_APB2
  REAL (KIND=JPRB)::RCL_APB3
  REAL (KIND=JPRB)::RCL_AS
  REAL (KIND=JPRB)::RCL_BS
  REAL (KIND=JPRB)::RCL_CS
  REAL (KIND=JPRB)::RCL_DS
  REAL (KIND=JPRB)::RCL_X1S
  REAL (KIND=JPRB)::RCL_X2S
  REAL (KIND=JPRB)::RCL_X3S
  REAL (KIND=JPRB)::RCL_X4S
  REAL (KIND=JPRB)::RCL_CONST1S
  REAL (KIND=JPRB)::RCL_CONST2S
  REAL (KIND=JPRB)::RCL_CONST3S
  REAL (KIND=JPRB)::RCL_CONST4S
  REAL (KIND=JPRB)::RCL_CONST5S
  REAL (KIND=JPRB)::RCL_CONST6S
  REAL (KIND=JPRB)::RCL_CONST7S
  REAL (KIND=JPRB)::RCL_CONST8S
  REAL (KIND=JPRB)::RCL_LAM1S
  REAL (KIND=JPRB)::RCL_LAM2S
  REAL (KIND=JPRB)::RDENSWAT
  REAL (KIND=JPRB)::RDENSREF
  REAL (KIND=JPRB)::RCL_AR
  REAL (KIND=JPRB)::RCL_BR
  REAL (KIND=JPRB)::RCL_CR
  REAL (KIND=JPRB)::RCL_DR
  REAL (KIND=JPRB)::RCL_X1R
  REAL (KIND=JPRB)::RCL_X2R
  REAL (KIND=JPRB)::RCL_X4R
  REAL (KIND=JPRB)::RCL_X1R_MP
  REAL (KIND=JPRB)::RCL_X2R_MP
  REAL (KIND=JPRB)::RCL_X4R_MP
  REAL (KIND=JPRB)::RCL_KA273
  REAL (KIND=JPRB)::RCL_CDENOM1
  REAL (KIND=JPRB)::RCL_CDENOM2
  REAL (KIND=JPRB)::RCL_CDENOM3
  REAL (KIND=JPRB)::RCL_SCHMIDT
  REAL (KIND=JPRB)::RCL_DYNVISC
  REAL (KIND=JPRB)::RCL_CONST1R
  REAL (KIND=JPRB)::RCL_CONST2R
  REAL (KIND=JPRB)::RCL_CONST3R
  REAL (KIND=JPRB)::RCL_CONST4R
  REAL (KIND=JPRB)::RCL_CONST7R
  REAL (KIND=JPRB)::RCL_CONST8R
  REAL (KIND=JPRB)::RCL_LAM1R
  REAL (KIND=JPRB)::RCL_LAM2R
  REAL (KIND=JPRB)::RCL_LAM1R_MP
  REAL (KIND=JPRB)::RCL_LAM2R_MP
  REAL (KIND=JPRB)::RCL_CONST5R
  REAL (KIND=JPRB)::RCL_CONST6R
  REAL (KIND=JPRB)::RCL_FZRAB
  REAL (KIND=JPRB)::RCL_FZRBB
  REAL (KIND=JPRB)::RCL_CONST9R
  REAL (KIND=JPRB)::RCL_CONST10R
  REAL (KIND=JPRB)::RCL_EFF_RACW
  INTEGER (KIND=JPIM)::NPTYPE_SEV2WMO (NPRECTYPES)
  LOGICAL::LCLDEXTRA, LCLDBUDGET
  LOGICAL::LCLDBUDC
  LOGICAL::LCLDBUDL
  LOGICAL::LCLDBUDI
  LOGICAL::LCLDBUDT
  LOGICAL::LCLDBUD_TIMEINT
  LOGICAL::LCLDBUD_VERTINT
  INTEGER (KIND=JPIM)::NSSOPT
  INTEGER (KIND=JPIM)::NCLDTOP
  INTEGER (KIND=JPIM)::NAECLBC, NAECLDU, NAECLOM, NAECLSS, NAECLSU
  INTEGER (KIND=JPIM)::NCLDDIAG
  INTEGER (KIND=JPIM)::NAERCLD
  LOGICAL::LAERLIQAUTOLSP
  LOGICAL::LAERLIQAUTOCP
  LOGICAL::LAERLIQAUTOCPB
  LOGICAL::LAERLIQCOLL
  LOGICAL::LAERICESED
  LOGICAL::LAERICEAUTO
  REAL (KIND=JPRB)::NSHAPEP
  REAL (KIND=JPRB)::NSHAPEQ
  INTEGER (KIND=JPIM)::NBETA
  REAL (KIND=JPRB)::RBETA (0:100)
  REAL (KIND=JPRB)::RBETAP1 (0:100)
  
ENDTYPE TECLDP

CONTAINS

ENDMODULE YOECLDP
