MODULE YOECUMF2
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TECUMF2
  REAL (KIND=JPRB)::ENTRORG2
  REAL (KIND=JPRB)::DETRPEN2
  REAL (KIND=JPRB)::ENTSHALP2
  REAL (KIND=JPRB)::ENTSTPC12
  REAL (KIND=JPRB)::ENTSTPC22
  REAL (KIND=JPRB)::ENTSTPC32
  REAL (KIND=JPRB)::ENTRDD2
  REAL (KIND=JPRB)::RMFCMIN2
  REAL (KIND=JPRB)::RMFDEPS2
  REAL (KIND=JPRB)::RDEPTHS2
  REAL (KIND=JPRB)::RPRCON2
  REAL (KIND=JPRB)::RTAU2
  REAL (KIND=JPRB)::RCPECONS2
  REAL (KIND=JPRB)::RCUCOV2
  REAL (KIND=JPRB)::RTAUMEL2
  REAL (KIND=JPRB)::RUVPER2
  REAL (KIND=JPRB)::RMFSOLCT2
  REAL (KIND=JPRB)::RMFSOLTQ2
  REAL (KIND=JPRB)::RMFSOLUV2
  REAL (KIND=JPRB)::RMFSOLRHS2
  REAL (KIND=JPRB)::RMFCFL2
  REAL (KIND=JPRB)::RMFLIA2
  REAL (KIND=JPRB)::RCAPDCYCL2
  REAL (KIND=JPRB)::RTAU02
  LOGICAL::LMFMID2
  LOGICAL::LMFDD2
  LOGICAL::LMFDUDV2
  LOGICAL::LMFUVDIS2
  LOGICAL::LMFWETB2
  LOGICAL::LMFGLAC2
  INTEGER (KIND=JPIM)::NJKT12, NJKT22, NJKT32, NJKT52, NJKT62
  
ENDTYPE TECUMF2

CONTAINS

ENDMODULE YOECUMF2
