MODULE YOEGWD
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TEGWD
  INTEGER (KIND=JPIM)::NKTOPG
  INTEGER (KIND=JPIM)::NGWDLIM
  INTEGER (KIND=JPIM)::NGWDTOP
  INTEGER (KIND=JPIM)::NDIFF_STRATO
  REAL (KIND=JPRB)::GFRCRIT
  REAL (KIND=JPRB)::GRCRIT
  REAL (KIND=JPRB)::GKDRAG
  REAL (KIND=JPRB)::GKWAKE
  REAL (KIND=JPRB)::GSSEC
  REAL (KIND=JPRB)::GTSEC
  REAL (KIND=JPRB)::GVSEC
  REAL (KIND=JPRB)::GTENLIM
  REAL (KIND=JPRB)::GRFPLM
  LOGICAL::LRDIFF_STRATO
  LOGICAL::LDIAG_STRATO
  
ENDTYPE TEGWD

CONTAINS

ENDMODULE YOEGWD
