MODULE YOEGWWMS
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TEGWWMS
  LOGICAL::LOZPR
  LOGICAL::LGACALC
  LOGICAL::LGSATL
  LOGICAL::LGINDL
  INTEGER (KIND=JPIM)::NLAUNCHL (3)
  INTEGER (KIND=JPIM)::NLAUNCHLEV
  INTEGER (KIND=JPIM)::NLAUNCH
  INTEGER (KIND=JPIM)::NSLOPE
  INTEGER (KIND=JPIM)::NGAUSS
  REAL (KIND=JPRB)::GFLUXLAUNL (3)
  REAL (KIND=JPRB)::GFLUXLAUN
  REAL (KIND=JPRB)::GMSTAR_L (3)
  REAL (KIND=JPRB)::GCSTAR
  REAL (KIND=JPRB)::GPTWO
  REAL (KIND=JPRB)::GTPHYGWWMS
  REAL (KIND=JPRB)::GGAUSSA
  REAL (KIND=JPRB)::GGAUSSB (3)
  REAL (KIND=JPRB)::GCOEFF
  
ENDTYPE TEGWWMS

CONTAINS

ENDMODULE YOEGWWMS
