MODULE YOELWRAD
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TELWRAD
  INTEGER (KIND=JPIM)::NLEVLWC
  INTEGER (KIND=JPIM)::NLWFR
  INTEGER (KIND=JPIM)::NLOOPLW
  INTEGER (KIND=JPIM)::NLOOPLWO
  INTEGER (KIND=JPIM)::NPROMALW
  INTEGER (KIND=JPIM)::NLASTLW
  LOGICAL::LOPTLWPR
  LOGICAL::LWLCLHR
  
ENDTYPE TELWRAD

CONTAINS

ENDMODULE YOELWRAD
