MODULE YOEOZOC
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE


TYPE::TEOZOC
  REAL (KIND=JPRB), ALLOCATABLE::ZOZCL (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::ZOZCLAQUA (:,:)
  REAL (KIND=JPRB)::COZQC (21)=-HUGE (1._JPRB)
  REAL (KIND=JPRB)::COZQS (15)=-HUGE (1._JPRB)
  REAL (KIND=JPRB)::COZHC (21)=-HUGE (1._JPRB)
  REAL (KIND=JPRB)::COZHS (15)=-HUGE (1._JPRB)
  REAL (KIND=JPRB)::RSINC (64)=-HUGE (1._JPRB)
  REAL (KIND=JPRB)::ROZT (64, 0:60)=-HUGE (1._JPRB)
  REAL (KIND=JPRB)::RPROC (0:60)=-HUGE (1._JPRB)
ENDTYPE TEOZOC

ENDMODULE YOEOZOC
