
MODULE YOEPHY
USE PARKIND1,ONLY:JPRB, JPIM
USE ISO_C_BINDING

IMPLICIT NONE

SAVE

TYPE::TEPHY
  LOGICAL::LEPHYS
  LOGICAL::LECOND
  LOGICAL::LECUMF
  LOGICAL::LEDCLD
  LOGICAL::LEEVAP
  LOGICAL::LEGWDG
  LOGICAL::LEGWWMS
  LOGICAL::LEOZOC
  LOGICAL::LEQNGT
  LOGICAL::LERADI
  LOGICAL::LERADIMPL
  LOGICAL::LERADS
  LOGICAL::LESICE
  LOGICAL::LESURF
  LOGICAL::LEVDIF
  LOGICAL::LAGPHY
  LOGICAL::LEPCLD
  LOGICAL::LEO3CH
  LOGICAL::LO3CH_SAFE
  LOGICAL::LO3CH_OLDVER
  LOGICAL::LO3CH_BMS
  LOGICAL::LO3CH_HLO
  CHARACTER (LEN=4)::CO3CHEM
  LOGICAL::LNEEONLINE
  LOGICAL::LWETONLINE
  LOGICAL::LBUD23
  LOGICAL::LPPTILES
  LOGICAL::LBUDCYCLE
  LOGICAL::LEXTRATEND
  LOGICAL::LEMETHOX
  LOGICAL::LECURR
  LOGICAL::LESURFTRAJ
  LOGICAL::LVDFTRAC
  LOGICAL::LVDFNEWTRAC
  LOGICAL::LMFTRAC
  LOGICAL::LMFSCAV
  LOGICAL::LEMWAVE
  LOGICAL::LEGBRAD
  LOGICAL::LERAINGG
  LOGICAL::LESMOS
  LOGICAL::LESMAP
  LOGICAL::LEOCWA
  LOGICAL::LEOCCO
  LOGICAL::LEOCSA
  LOGICAL::LEOCLA
  LOGICAL::LEVGEN
  LOGICAL::LESSRO
  LOGICAL::LEFLAKE
  LOGICAL::LEOCML
  LOGICAL::LEOBC
  LOGICAL::LEOBCMAX
  REAL (KIND=JPRB)::REOBCMAX
  LOGICAL::LEOBCICE
  LOGICAL::LEOCLAKE
  LOGICAL::LEOLAKESST
  LOGICAL::LOCMLTKE
  LOGICAL::LECLIPQT0
  LOGICAL::LECLIPCLDT0
  LOGICAL::LDUCTDIA
  LOGICAL::LDIAGTURB_EC
  LOGICAL::LDIAGTURBGRAD_EC
  LOGICAL::LBLEND
  LOGICAL::LSLPHY
  LOGICAL::LESN09
  LOGICAL::LELAIV
  LOGICAL::LECTESSEL
  LOGICAL::LEAGS
  LOGICAL::LEFARQUHAR
  LOGICAL::LEOPTSURF
  LOGICAL::LEC4MAP
  LOGICAL::LEAIRCO2COUP
  LOGICAL::LELIGHT
  LOGICAL::LVEXTRDYNACC
  REAL (KIND=JPRB)::RTHRFRTI
  REAL (KIND=JPRB)::RCIMIN
  REAL (KIND=JPRB)::RLAIINT
  INTEGER (KIND=JPIM)::NPRACCL
  INTEGER (KIND=JPIM)::NLIMODE
  LOGICAL::LGLIGHTCO
  LOGICAL::LECLIM10D
  LOGICAL::LESNML
  LOGICAL::LEURBAN
  INTEGER (KIND=JPIM)::NSNMLWS
  LOGICAL::LBFASCO2
  INTEGER (KIND=JPIM)::NCO2CLIMYY1
  INTEGER (KIND=JPIM)::NCO2CLIMYY2
  INTEGER (KIND=JPIM)::NCO2CLIMN1
  INTEGER (KIND=JPIM)::NCO2CLIMN2
  INTEGER (KIND=JPIM)::NCO2CLIMFRQ
  INTEGER (KIND=JPIM)::NALBEDOSCHEME
  INTEGER (KIND=JPIM)::NEMISSSCHEME
  REAL (KIND=JPRB)::RALFMINPSN
  REAL (KIND=JPRB)::RNORTHML
  REAL (KIND=JPRB)::RSOUTHML
  REAL (KIND=JPRB)::RWESTML
  REAL (KIND=JPRB)::REASTML
  LOGICAL::INVML
  LOGICAL::LFPOS_EC_PHYS=.FALSE.
  LOGICAL::LFPOS_ACC_RESET
  LOGICAL::LRAD_CLOUD_INHOMOG
  TYPE (C_PTR)::YSURF
  
ENDTYPE TEPHY

TYPE (TEPHY), POINTER::YREPHY=>NULL ()
CONTAINS

ENDMODULE YOEPHY
