
MODULE YOERDI
USE PARKIND1,ONLY:JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE

TYPE::TERDI
  REAL (KIND=JPRB)::RRAE
  REAL (KIND=JPRB)::RSUNDUR
  REAL (KIND=JPRB)::RCARDI
  REAL (KIND=JPRB)::RCH4
  REAL (KIND=JPRB)::RN2O
  REAL (KIND=JPRB)::RNO2
  REAL (KIND=JPRB)::RO3
  REAL (KIND=JPRB)::RCCL4
  REAL (KIND=JPRB)::RCFC11
  REAL (KIND=JPRB)::RCFC12
  REAL (KIND=JPRB)::RCFC22
  REAL (KIND=JPRB)::REPCLC
  REAL (KIND=JPRB)::REPH2O
  REAL (KIND=JPRB)::RCCO2, RCCH4, RCN2O, RCNO2, RCCFC11, RCCFC12, RCCFC22, RCCCL4
  REAL (KIND=JPRB)::RSOLINC
  REAL (KIND=JPRB)::RSOLARCYCLEMULT
  
ENDTYPE TERDI

CONTAINS

ENDMODULE YOERDI
