MODULE YOERADGHG
USE PARKIND1,ONLY:JPRB, JPIM

IMPLICIT NONE


TYPE::TRADGHG
  REAL (KIND=JPRB), ALLOCATABLE::SINLAT (:)
  REAL (KIND=JPRB), ALLOCATABLE::PRESSURE_HL (:)
  REAL (KIND=JPRB), ALLOCATABLE::MASS_CH4 (:,:), MASS_CO2 (:,:), MASS_N2O (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::MASS_NO2 (:,:), MASS_CFC11 (:,:), MASS_CFC12 (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::MASS_CCL4 (:,:), MASS_HCFC22 (:,:), MASS_O3 (:,:)
  INTEGER (KIND=JPIM)::NLATITUDE=0, NPRESSURE=0
  
  
ENDTYPE TRADGHG

TYPE (TRADGHG), POINTER::YRADGHG=>NULL ()
CONTAINS

ENDMODULE YOERADGHG
