
MODULE YOERAD
USE PARKIND1,ONLY:JPIM, JPRB
USE YOE_SPECTRAL_PLANCK,ONLY:TSPECTRALPLANCK
USE YOEAERRADDESC,ONLY:TAER_RAD_DESC
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE

TYPE::TERAD
  INTEGER (KIND=JPIM)::NAER
  INTEGER (KIND=JPIM)::NMODE
  INTEGER (KIND=JPIM)::NOZOCL
  INTEGER (KIND=JPIM)::NRADFR
  INTEGER (KIND=JPIM)::NRADPFR
  INTEGER (KIND=JPIM)::NRADPLA
  INTEGER (KIND=JPIM)::NRADINT
  INTEGER (KIND=JPIM)::NRADRES
  INTEGER (KIND=JPIM)::NRADNFR
  INTEGER (KIND=JPIM)::NRADSFR
  INTEGER (KIND=JPIM)::NRADE1H, NRADE3H
  INTEGER (KIND=JPIM)::NRADELG
  INTEGER (KIND=JPIM)::NOVLP
  INTEGER (KIND=JPIM)::NRPROMA
  INTEGER (KIND=JPIM)::NSW
  INTEGER (KIND=JPIM)::NLW
  INTEGER (KIND=JPIM)::NSWNL
  INTEGER (KIND=JPIM)::NSWTL
  INTEGER (KIND=JPIM)::NLWEMISS
  INTEGER (KIND=JPIM)::NLWOUT
  INTEGER (KIND=JPIM)::NTLW
  INTEGER (KIND=JPIM)::NTSW
  INTEGER (KIND=JPIM)::NUV
  INTEGER (KIND=JPIM)::NCSRADF
  INTEGER (KIND=JPIM)::NICEOPT
  INTEGER (KIND=JPIM)::NLIQOPT
  INTEGER (KIND=JPIM)::NSWICEOPT
  INTEGER (KIND=JPIM)::NSWLIQOPT
  INTEGER (KIND=JPIM)::NLWICEOPT
  INTEGER (KIND=JPIM)::NLWLIQOPT
  INTEGER (KIND=JPIM)::NRADIP
  INTEGER (KIND=JPIM)::NRADLP
  INTEGER (KIND=JPIM)::NINHOM
  INTEGER (KIND=JPIM)::NLAYINH
  INTEGER (KIND=JPIM)::NLNGR1H
  INTEGER (KIND=JPIM)::NPERTAER
  INTEGER (KIND=JPIM)::NPERTOZ
  INTEGER (KIND=JPIM)::NSCEN
  INTEGER (KIND=JPIM)::NHINCSOL
  INTEGER (KIND=JPIM)::NMCICA
  INTEGER (KIND=JPIM)::NGHGRAD
  INTEGER (KIND=JPIM)::NDECOLAT
  INTEGER (KIND=JPIM)::NMINICE
  INTEGER (KIND=JPIM)::NVOLCVERT
  INTEGER (KIND=JPIM)::NREDGLW
  INTEGER (KIND=JPIM)::NREDGSW
  INTEGER (KIND=JPIM)::NAERMACC
  INTEGER (KIND=JPIM)::NSPMAPL (16), NSPMAPS (14)
  INTEGER (KIND=JPIM)::NLWSCATTERING
  INTEGER (KIND=JPIM)::NSWSOLVER, NLWSOLVER
  INTEGER (KIND=JPIM)::NSWGASOPTICS, NLWGASOPTICS
  INTEGER (KIND=JPIM)::KMODTS
  INTEGER (KIND=JPIM)::NSOLARSPECTRUM
  INTEGER (KIND=JPIM)::NSWWVCONTINUUM
  INTEGER (KIND=JPIM)::NDUMPBADINPUTS
  INTEGER (KIND=JPIM)::NDUMPINPUTS
  INTEGER (KIND=JPIM)::NCLOUDOVERLAP
  INTEGER (KIND=JPIM)::NRTCALL
  INTEGER (KIND=JPIM)::IRTCALLREF
  INTEGER (KIND=JPIM)::IRTCALLCLN
  REAL (KIND=JPRB)::RCLOUD_FRAC_STD
  REAL (KIND=JPRB)::RCLOUD_SEPARATION_SCALE_TOA, RCLOUD_SEPARATION_SCALE_SURF
  LOGICAL::LFU_LW_ICE_OPTICS_BUG
  LOGICAL::LINTERPINCLOUDMEAN
  LOGICAL::LERAD1H
  LOGICAL::LEPO3RA
  LOGICAL::LONEWSW
  LOGICAL::LECSRAD
  LOGICAL::LRRTM
  LOGICAL::LSRTM
  LOGICAL::LDIFFC
  LOGICAL::LHVOLCA
  LOGICAL::LNOTROAER
  LOGICAL::LRAYL
  LOGICAL::LOPTRPROMA
  LOGICAL::LECO2VAR
  LOGICAL::LHGHG
  LOGICAL::LESO4HIS
  LOGICAL::LETRACGMS
  LOGICAL::LAERCLIM, LAERVISI, LAER3D
  LOGICAL::LVOLCSPEC
  LOGICAL::LVOLCDAMP
  LOGICAL::LDIAGFORCING
  LOGICAL::LAERADCLI
  LOGICAL::LAERADJDU
  LOGICAL::LAPPROXLWUPDATE
  LOGICAL::LAPPROXSWUPDATE
  LOGICAL::LMANNERSSWUPDATE
  LOGICAL::LCENTREDTIMESZA
  LOGICAL::LAVERAGESZA
  LOGICAL::LECOMPGRID
  LOGICAL::LUSEPRE2017RAD
  LOGICAL::LDUSEASON
  LOGICAL::LSPECTRALSOLARCYCLE
  LOGICAL::LCCNL
  LOGICAL::LCCNO
  LOGICAL::LPERPET
  LOGICAL::LCLEAN
  REAL (KIND=JPRB)::RAOVLP, RBOVLP
  REAL (KIND=JPRB)::RCCNLND, RCCNSEA
  LOGICAL::LEDBUG
  REAL (KIND=JPRB)::RPERTOZ, RRE2DE
  REAL (KIND=JPRB)::RLWINHF, RSWINHF
  REAL (KIND=JPRB)::RMINICE
  REAL (KIND=JPRB)::RVOLCSPEC (3)
  REAL (KIND=JPRB)::RNS, RSIGAIR
  REAL (KIND=JPRB)::RAESHSS, RAESHDU, RAESHOM, RAESHBC, RAESHSU
  REAL (KIND=JPRB)::TRBKG
  REAL (KIND=JPRB)::STBKG
  CHARACTER (LEN=256)::CGHGCLIMFILE=' '
  CHARACTER (LEN=256)::CGHGTIMESERIESFILE=' '
  CHARACTER (LEN=256)::CSOLARIRRADIANCEFILE=' '
  CHARACTER (LEN=256)::CAERCLIMFILE=' '
  CHARACTER (LEN=256)::CAEROPTICSMODEL_DD=' '
  CHARACTER (LEN=256)::CAEROPTICSMODEL_SU=' '
  CHARACTER (LEN=256)::CAEROPTICSMODEL_OM=' '
  CHARACTER (LEN=256)::CAEROPTICSMODEL_BC=' '
  REAL (KIND=JPRB)::RRATSEA, RRATLAND, RRATDRI
  REAL (KIND=JPRB)::RCADECOR, RCBDECOR
  REAL (KIND=JPRB)::RFACDICE
  REAL (KIND=JPRB), ALLOCATABLE::CVDAESS (:)
  REAL (KIND=JPRB), ALLOCATABLE::CVDAEDU (:)
  REAL (KIND=JPRB), ALLOCATABLE::CVDAEOM (:)
  REAL (KIND=JPRB), ALLOCATABLE::CVDAEBC (:)
  REAL (KIND=JPRB), ALLOCATABLE::CVDAESU (:)
  TYPE (TSPECTRALPLANCK)::YSPECTPLANCK
  TYPE (TAER_RAD_DESC)::YAER_RAD_DESC
  
ENDTYPE TERAD

TYPE (TERAD), POINTER::YRERAD=>NULL ()
CONTAINS

ENDMODULE YOERAD
