MODULE YOERADIATION
USE PARKIND1,ONLY:JPRB, JPIM
USE RADIATION_CONFIG,ONLY:CONFIG_TYPE

IMPLICIT NONE

SAVE

TYPE::TRADIATION
  TYPE (CONFIG_TYPE)::RAD_CONFIG
  INTEGER (KIND=JPIM)::NWEIGHT_UV
  INTEGER (KIND=JPIM)::IBAND_UV (100)
  REAL (KIND=JPRB)::WEIGHT_UV (100)
  INTEGER (KIND=JPIM)::NWEIGHT_PAR
  INTEGER (KIND=JPIM)::IBAND_PAR (100)
  REAL (KIND=JPRB)::WEIGHT_PAR (100)
  INTEGER (KIND=JPIM)::ITYPE_TROP_BG_AER=0
  INTEGER (KIND=JPIM)::ITYPE_STRAT_BG_AER=0
  REAL (KIND=JPRB)::TROP_BG_AER_MASS_EXT=0.0_JPRB
  REAL (KIND=JPRB)::STRAT_BG_AER_MASS_EXT=0.0_JPRB
  
ENDTYPE TRADIATION

CONTAINS

ENDMODULE YOERADIATION
