MODULE YOERIP
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE::TERIP
  REAL (KIND=JPRB)::RCODECM
  REAL (KIND=JPRB)::RSIDECM
  REAL (KIND=JPRB)::RCOVSRM
  REAL (KIND=JPRB)::RSIVSRM
  REAL (KIND=JPRB)::RSOVRM
  REAL (KIND=JPRB)::RWSOVRM
ENDTYPE TERIP

ENDMODULE YOERIP
