
MODULE YOESW
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE


TYPE TESWRT
  REAL (KIND=JPRB)::APAD (6, 3, 7)
  REAL (KIND=JPRB)::BPAD (6, 3, 7)
  REAL (KIND=JPRB)::RRAY (6, 6)
  REAL (KIND=JPRB), ALLOCATABLE::RSUN (:), RSUN2 (:)
  REAL (KIND=JPRB)::RPDH1
  REAL (KIND=JPRB)::RPDU1
  REAL (KIND=JPRB)::RPNH
  REAL (KIND=JPRB)::RPNU
  REAL (KIND=JPRB)::RSWCE (6)
  REAL (KIND=JPRB)::RSWCP (6)
  REAL (KIND=JPRB)::RTDH2O
  REAL (KIND=JPRB)::RTDUMG
  REAL (KIND=JPRB)::RTH2O
  REAL (KIND=JPRB)::RTUMG
  REAL (KIND=JPRB)::D (6, 3)
  REAL (KIND=JPRB)::REXPO3 (6, 2, 7)
  INTEGER (KIND=JPIM)::NEXPO3 (6)
  REAL (KIND=JPRB)::RYFWCA (6)
  REAL (KIND=JPRB)::RYFWCB (6)
  REAL (KIND=JPRB)::RYFWCC (6)
  REAL (KIND=JPRB)::RYFWCD (6)
  REAL (KIND=JPRB)::RYFWCE (6)
  REAL (KIND=JPRB)::RYFWCF (6)
  REAL (KIND=JPRB)::REBCUA (6)
  REAL (KIND=JPRB)::REBCUB (6)
  REAL (KIND=JPRB)::REBCUC (6)
  REAL (KIND=JPRB)::REBCUD (6)
  REAL (KIND=JPRB)::REBCUE (6)
  REAL (KIND=JPRB)::REBCUF (6)
  REAL (KIND=JPRB)::REBCUG (16)
  REAL (KIND=JPRB)::REBCUH (16)
  REAL (KIND=JPRB)::REBCUI (6)
  REAL (KIND=JPRB)::REBCUJ (6)
  REAL (KIND=JPRB)::RASWCA (6)
  REAL (KIND=JPRB)::RASWCB (6)
  REAL (KIND=JPRB)::RASWCC (6)
  REAL (KIND=JPRB)::RASWCD (6)
  REAL (KIND=JPRB)::RASWCE (6)
  REAL (KIND=JPRB)::RASWCF (6)
  REAL (KIND=JPRB)::RKPNWCA (6)
  REAL (KIND=JPRB)::RKPNWCB (6)
  REAL (KIND=JPRB)::RKPNWCC (6)
  REAL (KIND=JPRB)::RKPNWCD (6)
  REAL (KIND=JPRB)::RKPNWCE (6)
  REAL (KIND=JPRB)::RKPNWCF (6)
  REAL (KIND=JPRB)::RKPNWCG (6)
  REAL (KIND=JPRB)::RKPNWCH (6)
  REAL (KIND=JPRB)::RFUETA (16, 3), RFUETB (16, 4), RFUETC (16, 4)
  REAL (KIND=JPRB)::RFULIO (16, 3)
  REAL (KIND=JPRB)::RHSAVI (16, 3)
  REAL (KIND=JPRB)::RLILIA (16, 5), RLILIB (16, 4)
  REAL (KIND=JPRB)::RKPNLWCA (16, 7)
  REAL (KIND=JPRB)::RFLAA0 (6)
  REAL (KIND=JPRB)::RFLAA1 (6)
  REAL (KIND=JPRB)::RFLBB0 (6)
  REAL (KIND=JPRB)::RFLBB1 (6)
  REAL (KIND=JPRB)::RFLBB2 (6)
  REAL (KIND=JPRB)::RFLBB3 (6)
  REAL (KIND=JPRB)::RFLCC0 (6)
  REAL (KIND=JPRB)::RFLCC1 (6)
  REAL (KIND=JPRB)::RFLCC2 (6)
  REAL (KIND=JPRB)::RFLCC3 (6)
  REAL (KIND=JPRB)::RFUAA0 (6)
  REAL (KIND=JPRB)::RFUAA1 (6)
  REAL (KIND=JPRB)::RFUBB0 (6)
  REAL (KIND=JPRB)::RFUBB1 (6)
  REAL (KIND=JPRB)::RFUBB2 (6)
  REAL (KIND=JPRB)::RFUBB3 (6)
  REAL (KIND=JPRB)::RFUCC0 (6)
  REAL (KIND=JPRB)::RFUCC1 (6)
  REAL (KIND=JPRB)::RFUCC2 (6)
  REAL (KIND=JPRB)::RFUCC3 (6)
  REAL (KIND=JPRB)::RFLDD0 (6)
  REAL (KIND=JPRB)::RFLDD1 (6)
  REAL (KIND=JPRB)::RFLDD2 (6)
  REAL (KIND=JPRB)::RFLDD3 (6)
  REAL (KIND=JPRB)::REFFIA
  REAL (KIND=JPRB)::RTAUA (6, 6)
  REAL (KIND=JPRB)::RPIZA (6, 6)
  REAL (KIND=JPRB)::RCGA (6, 6)
  REAL (KIND=JPRB)::RAER (6, 6)
  INTEGER (KIND=JPIM)::NMPSRTM (14), NTYPS
  REAL (KIND=JPRB)::RADJUST
  
ENDTYPE TESWRT

CONTAINS

ENDMODULE YOESW
