
MODULE YOETHF
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
REAL (KIND=JPRB)::R2ES
REAL (KIND=JPRB)::R3LES
REAL (KIND=JPRB)::R3IES
REAL (KIND=JPRB)::R4LES
REAL (KIND=JPRB)::R4IES
REAL (KIND=JPRB)::R5LES
REAL (KIND=JPRB)::R5IES
REAL (KIND=JPRB)::RVTMP2
REAL (KIND=JPRB)::RHOH2O
REAL (KIND=JPRB)::R5ALVCP
REAL (KIND=JPRB)::R5ALSCP
REAL (KIND=JPRB)::RALVDCP
REAL (KIND=JPRB)::RALSDCP
REAL (KIND=JPRB)::RALFDCP
REAL (KIND=JPRB)::RTWAT
REAL (KIND=JPRB)::RTBER
REAL (KIND=JPRB)::RTBERCU
REAL (KIND=JPRB)::RTICE
REAL (KIND=JPRB)::RTICECU
REAL (KIND=JPRB)::RTWAT_RTICE_R
REAL (KIND=JPRB)::RTWAT_RTICECU_R
REAL (KIND=JPRB)::RKOOP1
REAL (KIND=JPRB)::RKOOP2

TYPE TTHF
  REAL (KIND=JPRB)::R2ES
  REAL (KIND=JPRB)::R3LES
  REAL (KIND=JPRB)::R3IES
  REAL (KIND=JPRB)::R4LES
  REAL (KIND=JPRB)::R4IES
  REAL (KIND=JPRB)::R5LES
  REAL (KIND=JPRB)::R5IES
  REAL (KIND=JPRB)::RVTMP2
  REAL (KIND=JPRB)::RHOH2O
  REAL (KIND=JPRB)::R5ALVCP
  REAL (KIND=JPRB)::R5ALSCP
  REAL (KIND=JPRB)::RALVDCP
  REAL (KIND=JPRB)::RALSDCP
  REAL (KIND=JPRB)::RALFDCP
  REAL (KIND=JPRB)::RTWAT
  REAL (KIND=JPRB)::RTBER
  REAL (KIND=JPRB)::RTBERCU
  REAL (KIND=JPRB)::RTICE
  REAL (KIND=JPRB)::RTICECU
  REAL (KIND=JPRB)::RTWAT_RTICE_R
  REAL (KIND=JPRB)::RTWAT_RTICECU_R
  REAL (KIND=JPRB)::RKOOP1
  REAL (KIND=JPRB)::RKOOP2
ENDTYPE TTHF

TYPE (TTHF), POINTER::YRTHF=>NULL ()
CONTAINS

ENDMODULE YOETHF
