MODULE YOEVDF
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TVDF
  REAL (KIND=JPRB)::RLAM
  REAL (KIND=JPRB)::RVDIFTS
  LOGICAL::LWDS
  REAL (KIND=JPRB)::REPS1WDS
  REAL (KIND=JPRB)::REPS2WDS
  REAL (KIND=JPRB)::RETAWDS
  REAL (KIND=JPRB)::RTOFDALPHA
  REAL (KIND=JPRB)::REISTHSC
  INTEGER (KIND=JPIM)::NSUBST
  REAL (KIND=JPRB)::RFAC_TWO_COEF
  REAL (KIND=JPRB)::RZC_H
  REAL (KIND=JPRB)::RZL_INF
  
ENDTYPE TVDF

CONTAINS

ENDMODULE YOEVDF
