MODULE YOEWCOU
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TEWCOU
  INTEGER (KIND=JPIM)::NATMFLX
  INTEGER (KIND=JPIM)::NGAUSSW
  INTEGER (KIND=JPIM)::NLONW
  INTEGER (KIND=JPIM)::NLATW
  INTEGER (KIND=JPIM)::NLON1W
  INTEGER (KIND=JPIM)::NLAT1W
  INTEGER (KIND=JPIM)::NNORXW
  INTEGER (KIND=JPIM)::NSTPW
  INTEGER (KIND=JPIM)::NGRIB_HANDLE_FOR_WAM
  REAL (KIND=JPRB)::RSOUTW
  REAL (KIND=JPRB)::RNORTW
  REAL (KIND=JPRB)::RDEGREW
  REAL (KIND=JPRB)::RMISSW
  LOGICAL::LWCOU
  LOGICAL::LWCOU2W
  LOGICAL::LWCOUNORMS
  LOGICAL::LWCUR
  LOGICAL::LWCOURNW
  LOGICAL::LWCOUHMF
  LOGICAL::LWSTOKES
  LOGICAL::LWFLUX
  CHARACTER::CBEGDAT*14
  INTEGER (KIND=JPIM), ALLOCATABLE::MASK_WAVE_IN (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MASK_WAVE_OUT (:,:)
  LOGICAL::LWVIN_MASK_NOT_SET
  LOGICAL::LWVOUT_MASK_NOT_SET
  LOGICAL::LWVIN_UNINITIALISED
  INTEGER (KIND=JPIM)::MWVIN_SENDTOT
  INTEGER (KIND=JPIM)::MWVIN_RECVTOT
  INTEGER (KIND=JPIM), ALLOCATABLE::MWVIN_SENDCNT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MWVIN_RECVCNT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MWVIN_SENDOFF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MWVIN_RECVOFF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MWVIN_SENDBUF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MWVIN_RECVBUF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MWVIN_SENDIND (:)
  LOGICAL::LWFRSTIME
  LOGICAL::LWINIT
  INTEGER (KIND=JPIM)::NADV_WAVE
  INTEGER (KIND=JPIM)::NWV_W2IWGHT
  INTEGER (KIND=JPIM), ALLOCATABLE::IWV_LON (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::IWV_LAT (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::WV_W2IWGHT (:,:)
  
ENDTYPE TEWCOU

CONTAINS

ENDMODULE YOEWCOU
