
MODULE YOM_YGFL
USE PARKIND1,ONLY:JPIM, JPRB
USE YOE_AERODIAG,ONLY:NPAERAOT, NPAERLISI_VAR, NPAERLISI_WVL&
&, NPAERLISI, TYPE_AERO_WVL_DIAG, NPAERO_WVL_DIAG
USE PAR_GFL

IMPLICIT NONE

SAVE

TYPE TYPE_GFL_COMP
  CHARACTER (LEN=16)::CNAME=''
  INTEGER (KIND=JPIM)::IGRBCODE=-999
  LOGICAL::LADV=.FALSE.
  LOGICAL::LADV5=.FALSE.
  LOGICAL::LTDIABLIN=.FALSE.
  LOGICAL::LHORTURB=.FALSE.
  INTEGER (KIND=JPIM)::NREQIN=0
  LOGICAL::LREQOUT=.FALSE.
  LOGICAL::LGPINGP=.TRUE.
  LOGICAL::LMGRID=.FALSE.
  LOGICAL::LGP=.FALSE.
  LOGICAL::LSP=.FALSE.
  LOGICAL::LCDERS=.FALSE.
  LOGICAL::LACTIVE=.FALSE.
  LOGICAL::LTHERMACT=.FALSE.
  REAL (KIND=JPRB)::R=0.0_JPRB
  REAL (KIND=JPRB)::RCP=0.0_JPRB
  LOGICAL::LT9=.FALSE.
  LOGICAL::LT1=.FALSE.
  LOGICAL::LT5=.FALSE.
  LOGICAL::LPHY=.FALSE.
  LOGICAL::LPT=.FALSE.
  LOGICAL::LTRAJIO=.FALSE.
  LOGICAL::LDIAG=.FALSE.
  LOGICAL::LPC=.FALSE.
  REAL (KIND=JPRB)::REFVALI=0.0_JPRB
  LOGICAL::LADJUST0=.FALSE.
  LOGICAL::LADJUST1=.FALSE.
  INTEGER (KIND=JPIM)::NCOUPLING=0
  REAL (KIND=JPRB)::REFVALC=0.0_JPRB
  LOGICAL::LBIPER=.FALSE.
  CHARACTER (LEN=12)::CSLINT=''
  INTEGER (KIND=JPIM)::MGFL=-99999999
  INTEGER (KIND=JPIM)::MP=-99999999
  INTEGER (KIND=JPIM)::MPL=-99999999
  INTEGER (KIND=JPIM)::MPM=-99999999
  INTEGER (KIND=JPIM)::MP9=-99999999
  INTEGER (KIND=JPIM)::MP9_PH=-99999999
  INTEGER (KIND=JPIM)::MP1=-99999999
  INTEGER (KIND=JPIM)::MP5=-99999999
  INTEGER (KIND=JPIM)::MP5L=-99999999
  INTEGER (KIND=JPIM)::MP5M=-99999999
  INTEGER (KIND=JPIM)::MPSLP=-99999999
  INTEGER (KIND=JPIM)::MPSP=-99999999
  INTEGER (KIND=JPIM)::MP_SPL=-99999999
  INTEGER (KIND=JPIM)::MP_SL1=-99999999
  INTEGER (KIND=JPIM)::MP_SLX=-99999999
  INTEGER (KIND=JPIM)::MPPT=-99999999
  INTEGER (KIND=JPIM)::MPPC=-99999999
  INTEGER (KIND=JPIM)::MPPC_PH=-99999999
  LOGICAL::LWATER
  LOGICAL::LPRECIP
  REAL (KIND=JPRB)::RLZER
  INTEGER (KIND=JPIM)::NCOUPLO4
  LOGICAL::LASSIM
  INTEGER (KIND=JPIM)::IGRIBDV
  INTEGER (KIND=JPIM)::IGRIBTC
  INTEGER (KIND=JPIM)::IGRBFLXO
  INTEGER (KIND=JPIM)::IGRBWDFLX
  INTEGER (KIND=JPIM)::IGRBDDFLX
  LOGICAL::LDIFF
  LOGICAL::LCONV
  REAL (KIND=JPRB)::RMOLMASS
  REAL (KIND=JPRB)::REFOLD
  REAL (KIND=JPRB)::HENRYA
  REAL (KIND=JPRB)::HENRYB
  LOGICAL::LNEGFIX
  LOGICAL::LCOMAD
  REAL (KIND=JPRB)::WENO_ALPHA
  LOGICAL::LMASSFIX
  REAL (KIND=JPRB)::BETAMFBC
  INTEGER (KIND=JPIM)::IFID=-1
  TYPE (TYPE_GFL_COMP), POINTER::PREVIOUS=>NULL ()
ENDTYPE TYPE_GFL_COMP


TYPE TYPE_GFL_NAML
  CHARACTER (LEN=16)::CNAME
  INTEGER (KIND=JPIM)::IGRBCODE
  INTEGER (KIND=JPIM)::NREQIN
  REAL (KIND=JPRB)::REFVALI
  LOGICAL::LREQOUT=.FALSE.
  LOGICAL::LGPINGP=.FALSE.
  LOGICAL::LMGRID=.FALSE.
  LOGICAL::LGP=.FALSE.
  LOGICAL::LSP=.FALSE.
  LOGICAL::LCDERS=.FALSE.
  LOGICAL::LT9=.FALSE.
  LOGICAL::LT1=.FALSE.
  LOGICAL::LT5=.FALSE.
  LOGICAL::LPHY=.FALSE.
  LOGICAL::LPT=.FALSE.
  LOGICAL::LTRAJIO=.FALSE.
  LOGICAL::LDIAG=.FALSE.
  LOGICAL::LPC=.FALSE.
  LOGICAL::LADV=.FALSE.
  LOGICAL::LADV5=.FALSE.
  LOGICAL::LINTLIN=.FALSE.
  LOGICAL::LTDIABLIN=.FALSE.
  LOGICAL::LHORTURB=.FALSE.
  LOGICAL::LQM=.FALSE.
  LOGICAL::LQMH=.FALSE.
  LOGICAL::LQM3D=.FALSE.
  LOGICAL::LQML3D=.FALSE.
  LOGICAL::LVWENO=.FALSE.
  REAL (KIND=JPRB)::WENO_ALPHA=0.0_JPRB
  LOGICAL::LSLHD=.FALSE.
  LOGICAL::LCOMAD=.FALSE.
  LOGICAL::LHV=.FALSE.
  LOGICAL::LVSPLIP=.FALSE.
  INTEGER (KIND=JPIM)::NCOUPLING
  REAL (KIND=JPRB)::REFVALC
  INTEGER (KIND=JPIM)::NCOUPLO4
  LOGICAL::LASSIM=.FALSE.
  INTEGER (KIND=JPIM)::IGRIBDV
  INTEGER (KIND=JPIM)::IGRIBTC
  INTEGER (KIND=JPIM)::IGRBFLXO
  INTEGER (KIND=JPIM)::IGRBWDFLX
  INTEGER (KIND=JPIM)::IGRBDDFLX
  LOGICAL::LDIFF=.FALSE.
  LOGICAL::LCONV=.FALSE.
  LOGICAL::LNEGFIX=.FALSE.
  LOGICAL::LMASSFIX=.FALSE.
  REAL (KIND=JPRB)::BETAMFBC
  REAL (KIND=JPRB)::RMOLMASS
  REAL (KIND=JPRB)::REFOLD
  REAL (KIND=JPRB)::HENRYA
  REAL (KIND=JPRB)::HENRYB
ENDTYPE TYPE_GFL_NAML


TYPE TYPE_GFLD
  INTEGER (KIND=JPIM)::NUMFLDS=0
  INTEGER (KIND=JPIM)::NDERS=0
  INTEGER (KIND=JPIM)::NUMSPFLDS=0
  INTEGER (KIND=JPIM)::NUMGPFLDS=0
  INTEGER (KIND=JPIM)::NUMFLDS9=0
  INTEGER (KIND=JPIM)::NUMFLDS1=0
  INTEGER (KIND=JPIM)::NUMSPFLDS1=0
  INTEGER (KIND=JPIM)::NUMFLDS5=0
  INTEGER (KIND=JPIM)::NUMFLDSPHY=0
  INTEGER (KIND=JPIM)::NUMFLDS_SPL=0
  INTEGER (KIND=JPIM)::NUMFLDS_SL1=0
  INTEGER (KIND=JPIM)::NUMFLDSPC=0
  INTEGER (KIND=JPIM)::NDIM=0
  INTEGER (KIND=JPIM)::NUMFLDSPT=0
  INTEGER (KIND=JPIM)::NDIM0=0
  INTEGER (KIND=JPIM)::NDIM9=0
  INTEGER (KIND=JPIM)::NDIM1=0
  INTEGER (KIND=JPIM)::NDIM5=0
  INTEGER (KIND=JPIM)::NDIMSLP=0
  INTEGER (KIND=JPIM)::NDIM_SPL=0
  INTEGER (KIND=JPIM)::NDIMPT=0
  INTEGER (KIND=JPIM)::NDIMPC=0
  INTEGER (KIND=JPIM)::NGFL_EXT
  INTEGER (KIND=JPIM)::NGFL_FORC
  INTEGER (KIND=JPIM)::NGFL_EZDIAG
  INTEGER (KIND=JPIM)::NGHG
  INTEGER (KIND=JPIM)::NGHG_ASSIM
  INTEGER (KIND=JPIM)::NAERO
  INTEGER (KIND=JPIM)::NACTAERO
  INTEGER (KIND=JPIM)::NAEROCV
  INTEGER (KIND=JPIM)::NDDHAERO
  INTEGER (KIND=JPIM)::NERA40
  INTEGER (KIND=JPIM)::NNOGW
  INTEGER (KIND=JPIM)::NEDRP
  INTEGER (KIND=JPIM)::NAEROUT
  INTEGER (KIND=JPIM)::NAEROCLIM
  INTEGER (KIND=JPIM)::NUVP
  INTEGER (KIND=JPIM)::NSLDIA
  INTEGER (KIND=JPIM)::NSLDIAGP
  INTEGER (KIND=JPIM)::NFSD
  LOGICAL::LAERCHEM=.FALSE.
  LOGICAL::LTRCMFIX=.FALSE.
  LOGICAL::LTRCMFIX_PS=.FALSE.
  LOGICAL::LTRCMFQM=.FALSE.
  LOGICAL::LAERAOT=.FALSE.
  LOGICAL::LAERLISI=.FALSE.
  LOGICAL::LAEROUT=.FALSE.
  LOGICAL::LAEROCLIM=.FALSE.
  LOGICAL::LUVPOUT=.FALSE.
  LOGICAL::LSPPTGFL=.FALSE.
  INTEGER (KIND=JPIM)::NGEMS
  INTEGER (KIND=JPIM)::NCHEM
  INTEGER (KIND=JPIM)::NCHEM_ASSIM
  INTEGER (KIND=JPIM)::NCHEM_FLXO
  INTEGER (KIND=JPIM)::NCHEM_WDFLX
  INTEGER (KIND=JPIM)::NCHEM_DDFLX
  INTEGER (KIND=JPIM)::NCHEM_DV
  INTEGER (KIND=JPIM)::NCHEM_TC
  INTEGER (KIND=JPIM)::NCHEM_SCV
  INTEGER (KIND=JPIM)::NEMIS2D
  INTEGER (KIND=JPIM)::NEMIS2DAUX
  INTEGER (KIND=JPIM)::NEMIS3D
  INTEGER (KIND=JPIM)::NLIMA
  INTEGER (KIND=JPIM)::NAERO_WVL_DIAG
  INTEGER (KIND=JPIM)::NAERO_WVL_DIAG_TYPES
  INTEGER (KIND=JPIM)::NCHEMSULF1
  INTEGER (KIND=JPIM)::NCHEMHNO3
  INTEGER (KIND=JPIM)::NNEGAFIX
  INTEGER (KIND=JPIM)::NOPTNEGFIX
  LOGICAL::LQM3DCONS=.FALSE.
  LOGICAL::LADVNEGFIX=.FALSE.
  LOGICAL::LTRCMFBC=.FALSE.
  LOGICAL::LTRCMFPR=.FALSE.
  LOGICAL::LTRCMFMG=.FALSE.
  LOGICAL::LTRCMFP=.FALSE.
  LOGICAL::LTRCMFA_DIF=.FALSE.
  LOGICAL::LTRCMFA_LAP=.FALSE.
  LOGICAL::LTRCMFA_VER=.FALSE.
  LOGICAL::LEXTRADF=.FALSE.
  INTEGER (KIND=JPIM)::NFLDSFIX
  INTEGER (KIND=JPIM)::NOPTMFBC
  INTEGER (KIND=JPIM)::NOPTMFPR
  INTEGER (KIND=JPIM)::NOPTVFE
  INTEGER (KIND=JPIM)::NMFDIAGLEV
  INTEGER (KIND=JPIM)::NMFIXFLDS (JPNAMED_GFL+JPGHG+JPCHEM+JPAERO)
  INTEGER (KIND=JPIM)::NNEGFLDS (JPNAMED_GFL+JPGHG+JPCHEM+JPAERO)
  REAL (KIND=JPRB)::ZMFIXEPS
  INTEGER (KIND=JPIM)::NFMG
  INTEGER (KIND=JPIM)::NMGFLDS (JPNAMED_GFL+JPGHG+JPCHEM+JPAERO)
  TYPE (TYPE_GFL_COMP)::YCOMP (JPGFL)
  TYPE (TYPE_GFL_COMP), POINTER::YLASTCOMP=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YQ=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YI=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YL=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YLCONV=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YICONV=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YRCONV=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YSCONV=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YIRAD=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YLRAD=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YS=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YR=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YG=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YH=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YTKE=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YTTE=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YEFB1=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YEFB2=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YEFB3=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YA=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YO3=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YSRC=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YLMF=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YIMF=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YAMF=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YTHRAD=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YWMFC=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YHLMF=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YHLCFMF=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YHIMF=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YHICFMF=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YMXL=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YSHTUR=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YFQTUR=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YFSTUR=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YCPF=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YSPF=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YCVGQ=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YQVA=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YGHG (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YCHEM (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YAERO (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YLRCH4=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YEMIS3D (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YFORC (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YEZDIAG (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YERA40 (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YNOGW (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YEDRP (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YSLDIA (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YAERAOT (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YAERLISI (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YAEROUT (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YAEROCLIM (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YUVP (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YPHYS (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YPHYCTY=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YRSPEC=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YSDSAT=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YCVV=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YRKTH=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YRKTQV=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YRKTQC=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YUOM=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YUAL=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YDOM=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YDAL=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YUEN=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YUNEBH=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YMO=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YLIMA (:)=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YFSD=>NULL ()
  TYPE (TYPE_GFL_COMP), POINTER::YEXT (:)=>NULL ()
  TYPE (TYPE_GFL_NAML)::YQ_NL
  TYPE (TYPE_GFL_NAML)::YI_NL
  TYPE (TYPE_GFL_NAML)::YL_NL
  TYPE (TYPE_GFL_NAML)::YLCONV_NL
  TYPE (TYPE_GFL_NAML)::YICONV_NL
  TYPE (TYPE_GFL_NAML)::YRCONV_NL
  TYPE (TYPE_GFL_NAML)::YSCONV_NL
  TYPE (TYPE_GFL_NAML)::YIRAD_NL
  TYPE (TYPE_GFL_NAML)::YLRAD_NL
  TYPE (TYPE_GFL_NAML)::YS_NL
  TYPE (TYPE_GFL_NAML)::YR_NL
  TYPE (TYPE_GFL_NAML)::YG_NL
  TYPE (TYPE_GFL_NAML)::YH_NL
  TYPE (TYPE_GFL_NAML)::YTKE_NL
  TYPE (TYPE_GFL_NAML)::YTTE_NL
  TYPE (TYPE_GFL_NAML)::YEFB1_NL
  TYPE (TYPE_GFL_NAML)::YEFB2_NL
  TYPE (TYPE_GFL_NAML)::YEFB3_NL
  TYPE (TYPE_GFL_NAML)::YA_NL
  TYPE (TYPE_GFL_NAML)::YO3_NL
  TYPE (TYPE_GFL_NAML)::YSRC_NL
  TYPE (TYPE_GFL_NAML)::YLMF_NL
  TYPE (TYPE_GFL_NAML)::YIMF_NL
  TYPE (TYPE_GFL_NAML)::YAMF_NL
  TYPE (TYPE_GFL_NAML)::YTHRAD_NL
  TYPE (TYPE_GFL_NAML)::YWMFC_NL
  TYPE (TYPE_GFL_NAML)::YHLMF_NL
  TYPE (TYPE_GFL_NAML)::YHLCFMF_NL
  TYPE (TYPE_GFL_NAML)::YHIMF_NL
  TYPE (TYPE_GFL_NAML)::YHICFMF_NL
  TYPE (TYPE_GFL_NAML)::YMXL_NL
  TYPE (TYPE_GFL_NAML)::YSHTUR_NL
  TYPE (TYPE_GFL_NAML)::YFQTUR_NL
  TYPE (TYPE_GFL_NAML)::YFSTUR_NL
  TYPE (TYPE_GFL_NAML)::YCPF_NL
  TYPE (TYPE_GFL_NAML)::YSPF_NL
  TYPE (TYPE_GFL_NAML)::YCVGQ_NL
  TYPE (TYPE_GFL_NAML)::YQVA_NL
  TYPE (TYPE_GFL_NAML)::YGHG_NL (JPGHG)
  TYPE (TYPE_GFL_NAML)::YCHEM_NL (JPCHEM)
  TYPE (TYPE_GFL_NAML)::YAERO_NL (JPAERO)
  TYPE (TYPE_GFL_NAML)::YERA40_NL (JPERA40)
  TYPE (TYPE_GFL_NAML)::YNOGW_NL (JPNOGW)
  TYPE (TYPE_GFL_NAML)::YEDRP_NL (JPEDRP)
  TYPE (TYPE_GFL_NAML)::YSLDIA_NL (JPSLDIA)
  TYPE (TYPE_GFL_NAML)::YLRCH4_NL
  TYPE (TYPE_GFL_NAML)::YAERAOT_NL (NPAERAOT)
  TYPE (TYPE_GFL_NAML)::YAERLISI_NL (NPAERLISI_WVL, NPAERLISI_VAR)
  TYPE (TYPE_GFL_NAML)::YAEROUT_NL (JPAEROUT)
  TYPE (TYPE_GFL_NAML)::YAEROCLIM_NL (JPAEROCLIM)
  TYPE (TYPE_GFL_NAML)::YUVP_NL (JPUVP)
  TYPE (TYPE_GFL_NAML)::YRKTH_NL
  TYPE (TYPE_GFL_NAML)::YRKTQV_NL
  TYPE (TYPE_GFL_NAML)::YRKTQC_NL
  TYPE (TYPE_GFL_NAML)::YPHYCTY_NL
  TYPE (TYPE_GFL_NAML)::YFSD_NL
  TYPE (TYPE_GFL_NAML)::YRSPEC_NL
  TYPE (TYPE_GFL_NAML)::YSDSAT_NL
  TYPE (TYPE_GFL_NAML)::YCVV_NL
  TYPE (TYPE_GFL_NAML)::YFORC_NL (JPFORC)
  TYPE (TYPE_GFL_NAML)::YEZDIAG_NL (JPEZDIAG)
  TYPE (TYPE_GFL_NAML)::YEXT_NL (JPGFL-JPNAMED_GFL-JPGHG-JPFORC-JPEZDIAG-JPAERO-JPERA40-JPNOGW-JPSLDIA&
  &-JPCH4S-JPAEROUT-JPAEROCLIM-NPAERAOT-NPAERLISI-JPUVP-JPCHEM-JPLIMA-JPPHYCTY-JPFSD-JPEDRP)
  TYPE (TYPE_GFL_NAML)::YUOM_NL
  TYPE (TYPE_GFL_NAML)::YUAL_NL
  TYPE (TYPE_GFL_NAML)::YDOM_NL
  TYPE (TYPE_GFL_NAML)::YDAL_NL
  TYPE (TYPE_GFL_NAML)::YUEN_NL
  TYPE (TYPE_GFL_NAML)::YUNEBH_NL
  TYPE (TYPE_GFL_NAML)::YMO_NL
  TYPE (TYPE_AERO_WVL_DIAG)::YAERO_WVL_DIAG_NL (NPAERO_WVL_DIAG)
  TYPE (TYPE_GFL_NAML)::YLIMA_NL (JPLIMA)
ENDTYPE TYPE_GFLD

TYPE (TYPE_GFLD), POINTER::YGFL=>NULL ()
ENDMODULE YOM_YGFL
