MODULE YOMAERO
USE PARKIND1,ONLY:JPIM, JPRB
USE YOM_YGFL,ONLY:JPAERO, JPAEROMASS2D

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::NSW_MAX=14
INTEGER (KIND=JPIM), PARAMETER::NLW_MAX=16

TYPE TAERO
  INTEGER (KIND=JPIM)::NAERO_GFL
  INTEGER (KIND=JPIM)::MAP_AERO_GFL2NC (JPAERO)
  INTEGER (KIND=JPIM)::MAP_AERO_CMS2GFL (JPAEROMASS2D)
  LOGICAL::LAERO_GFL_FROM_CMS (JPAERO)
  INTEGER (KIND=JPIM)::NUMGFL_AERO_OM2
  INTEGER (KIND=JPIM)::NUMGFL_AERO_SU
  REAL (KIND=JPRB)::RBGST_MMR_OM2
  REAL (KIND=JPRB)::RBGTR_MMR_OM2
  REAL (KIND=JPRB)::REXT550_SU
  REAL (KIND=JPRB)::RAERO_HEIGHT_SCALE (JPAEROMASS2D)
  REAL (KIND=JPRB)::RAERO_GAMMA_EXP (JPAEROMASS2D)
  REAL (KIND=JPRB)::RAERO_WEIGHT_SW (NSW_MAX)
  REAL (KIND=JPRB)::RAERO_WEIGHT_LW (NLW_MAX)
  REAL (KIND=JPRB)::RAERO_MASK_SW (NSW_MAX, NSW_MAX)
  REAL (KIND=JPRB)::RAERO_MASK_LW (NLW_MAX, NLW_MAX)
  REAL (KIND=JPRB), ALLOCATABLE::VDAER (:,:)
  CHARACTER (LEN=256)::CFAERO
ENDTYPE TAERO

ENDMODULE YOMAERO
