MODULE YOMARPHY
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TARPHY
  LOGICAL::LMPA
  LOGICAL::LMSE
  LOGICAL::LMICRO
  LOGICAL::LTURB
  LOGICAL::LKFBCONV
  LOGICAL::LKFBD
  LOGICAL::LKFBS
  LOGICAL::LMFSHAL
  LOGICAL::LORILAM
  LOGICAL::LRDUST
  LOGICAL::LRCO2
  LOGICAL::LINITCHEM
  LOGICAL::LINITORILAM
  LOGICAL::LINITDUST
  LOGICAL::LRDEPOS
  LOGICAL::LBUFLUX
  CHARACTER (LEN=1)::CCOUPLING
  LOGICAL::LMDUST
  LOGICAL::LLEONARD
  LOGICAL::LGOGER
ENDTYPE TARPHY

ENDMODULE YOMARPHY
