MODULE YOMCVER
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE YOMLUN,ONLY:NULOUT, NULNAM
USE YOMCT0,ONLY:LR2D, LECMWF, LARPEGEF

IMPLICIT NONE

SAVE

TYPE TCVER
  LOGICAL::LAPRXPK
  INTEGER (KIND=JPIM)::NDLNPR
  REAL (KIND=JPRB)::RHYDR0
  REAL (KIND=JPRB)::REXP_VRAT
  LOGICAL::LREGETA
  LOGICAL::LVFE_REGETA
  INTEGER (KIND=JPIM)::NVFE_TYPE
  INTEGER (KIND=JPIM)::NVFE_ORDER
  INTEGER (KIND=JPIM)::NVFE_INTERNALS
  LOGICAL::LVERTFE
  LOGICAL::LVFE_LAPL_BC
  LOGICAL::LVFE_GW
  LOGICAL::LVFE_GW_HALF
  LOGICAL::LVFE_GWMPA
  LOGICAL::LVFE_CHEB
  LOGICAL::LVFE_ECMWF
  LOGICAL::LVFE_NOBC
  LOGICAL::LVFE_VERBOSE
  LOGICAL::LVFE_NORMALIZE
  LOGICAL::LPERCENTILS
  LOGICAL::LVFE_COMPATIBLE
  LOGICAL::LVFE_FD_MIX
  LOGICAL::LVFE_LAPL_HALF
  LOGICAL::LCOMPATIBLE
  LOGICAL::LREFINE_NHPRE_BBC
  REAL (KIND=JPRB)::RVFE_ALPHA
  REAL (KIND=JPRB)::RVFE_BETA
  REAL (KIND=JPRB)::RVFE_KNOT_STRETCH
  REAL (KIND=JPRB)::RFAC1, RFAC2
  CHARACTER (LEN=8)::CVFE_ETAH
ENDTYPE TCVER

CONTAINS


ENDMODULE YOMCVER
