MODULE YOMCVMNH
USE PARKIND1,ONLY:JPIM, JPRB
USE MODD_NSV,ONLY:NSV_T
USE MODD_CONVPAR,ONLY:CONVPAR_T
USE MODD_CST,ONLY:CST_T
USE MODD_CONVPAREXT,ONLY:CONVPAREXT
USE MODD_CONVPAR_SHAL,ONLY:CONVPAR_SHAL

IMPLICIT NONE

SAVE

TYPE TCVMNH
  LOGICAL::LDEEP, LSHALLOW, LDIAGCONV
  LOGICAL::LSETTADJ, LREFRESH_ALL, LDOWN, LSMOOTH
  REAL (KIND=JPRB)::OTADJD
  REAL (KIND=JPRB)::OTADJS
  INTEGER (KIND=JPIM)::NSETENS, NIICE
  REAL (KIND=JPRB)::XA25
  REAL (KIND=JPRB)::XCRAD
  REAL (KIND=JPRB)::XCDEPTH
  REAL (KIND=JPRB)::XCDEPTH_D
  REAL (KIND=JPRB)::XDTPERT
  REAL (KIND=JPRB)::XENTR
  REAL (KIND=JPRB)::XZLCL
  REAL (KIND=JPRB)::XZPBL
  REAL (KIND=JPRB)::XWTRIG
  REAL (KIND=JPRB)::XNHGAM
  REAL (KIND=JPRB)::XTFRZ1
  REAL (KIND=JPRB)::XTFRZ2
  REAL (KIND=JPRB)::XSTABT
  REAL (KIND=JPRB)::XSTABC
  REAL (KIND=JPRB)::XAW
  REAL (KIND=JPRB)::XBW
  REAL (KIND=JPRB)::XATPERT
  REAL (KIND=JPRB)::XBTPERT
  TYPE (CONVPAREXT)::YRCVPEXT
  TYPE (CONVPAR_SHAL)::YRCVP_SHAL
  TYPE (CST_T)::YRCST_MNH
  TYPE (NSV_T)::YRNSV
  TYPE (CONVPAR_T)::YRCONVPAR
ENDTYPE TCVMNH

ENDMODULE YOMCVMNH
