MODULE YOMCSGEOM
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE DEALLOCATE_IF_ASSOCIATED_MOD,ONLY:DEALLOCATE_IF_ASSOCIATED

IMPLICIT NONE

SAVE

TYPE TCSGEOM
  REAL (KIND=JPRD), POINTER::RCOLON (:)=>NULL ()
  REAL (KIND=JPRD), POINTER::RSILON (:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RINDX (:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RINDY (:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RATATH (:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RATATX (:)=>NULL ()
  
  
  
ENDTYPE TCSGEOM


TYPE TCSGEOM_BLOCKED
  REAL (KIND=JPRD), POINTER::RCOLON (:,:)=>NULL ()
  REAL (KIND=JPRD), POINTER::RSILON (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RINDX (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RINDY (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RATATH (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RATATX (:,:)=>NULL ()
  
  
  
ENDTYPE TCSGEOM_BLOCKED

CONTAINS







ENDMODULE YOMCSGEOM
