MODULE YOMCT1
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM)::N1POS
INTEGER (KIND=JPIM)::N1HIS
INTEGER (KIND=JPIM)::N1GDI
INTEGER (KIND=JPIM)::N1SDI
INTEGER (KIND=JPIM)::N1DHP
INTEGER (KIND=JPIM)::N1RES
INTEGER (KIND=JPIM)::N1XFU
INTEGER (KIND=JPIM)::N1DHFG
INTEGER (KIND=JPIM)::N1DHFZ
INTEGER (KIND=JPIM)::N1DHFD
INTEGER (KIND=JPIM)::N1CFU
INTEGER (KIND=JPIM)::N1SFXHIS
INTEGER (KIND=JPIM)::N1MASSCON
LOGICAL::LRFILAF
LOGICAL::LWRSPEC
LOGICAL::LGPDIAG, LSPDIAG
ENDMODULE YOMCT1
