MODULE YOMCDDH

IMPLICIT NONE

SAVE

TYPE::TCDDH
  CHARACTER, ALLOCATABLE::CADHTLS (:)*12
  CHARACTER, ALLOCATABLE::CADHTSS (:)*12
  CHARACTER, ALLOCATABLE::CADHTTS (:)*12
  CHARACTER, ALLOCATABLE::CADHTIS (:)*12
  CHARACTER, ALLOCATABLE::CADHSSS (:)*12
  CHARACTER, ALLOCATABLE::CADHIIS (:)*12
  CHARACTER, ALLOCATABLE::CADHWLS (:)*12
  CHARACTER, ALLOCATABLE::CADHFSS (:)*12
ENDTYPE TCDDH

ENDMODULE YOMCDDH
