
MODULE YOMCT0
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::JPNPST=960
INTEGER (KIND=JPIM)::NCONF
INTEGER (KIND=JPIM)::NFPOS
LOGICAL::LR3D
LOGICAL::LR2D
LOGICAL::LRSHW
LOGICAL::LRVEQ
INTEGER (KIND=JPIM)::NOPT_MEMORY
INTEGER (KIND=JPIM)::NOPT_MEMORY_AD
LOGICAL::LALLOPR
LOGICAL::LFDBOP
LOGICAL::LECFPOS
LOGICAL::LGRBOP
LOGICAL::LFBDAP
LOGICAL::LARPEGEF
LOGICAL::LARPEGEF_TRAJHR
LOGICAL::LARPEGEF_TRAJBG
LOGICAL::LARPEGEF_RDGP_INIT
LOGICAL::LARPEGEF_RDGP_TRAJHR
LOGICAL::LARPEGEF_RDGP_TRAJBG
CHARACTER (LEN=120)::CNDISPP
CHARACTER (LEN=128)::CFPNCF
CHARACTER (LEN=120)::CFDIRLST
CHARACTER (LEN=120)::CNPPATH
CHARACTER (LEN=120)::CSCRIPT_PPSERVER
CHARACTER (LEN=120)::CSCRIPT_LAMRTC
LOGICAL::LNF
LOGICAL::LSMSSIG
CHARACTER (LEN=25)::CEVENT
CHARACTER (LEN=25)::CMETER
LOGICAL::LOPDIS
CHARACTER (LEN=16)::CNMEXP
LOGICAL::LBACKG
LOGICAL::LSPBSBAL
LOGICAL::LMINIM
LOGICAL::LIOLEVG
INTEGER (KIND=JPIM)::NUNDEFLD
LOGICAL::LREFOUT
LOGICAL::LREFGEN
INTEGER (KIND=JPIM)::NQUAD
INTEGER (KIND=JPIM)::N2DINI
INTEGER (KIND=JPIM)::N3DINI
INTEGER (KIND=JPIM)::NSPPR
INTEGER (KIND=JPIM)::NFRPOS
INTEGER (KIND=JPIM)::NFRCORM
INTEGER (KIND=JPIM)::NFRCO
INTEGER (KIND=JPIM)::NFRHIS
INTEGER (KIND=JPIM)::NFRSFXHIS
INTEGER (KIND=JPIM)::NFRMASSCON
INTEGER (KIND=JPIM)::NFRGDI
INTEGER (KIND=JPIM)::NFRSDI
INTEGER (KIND=JPIM)::NFRDHFG
INTEGER (KIND=JPIM)::NFRDHFZ
INTEGER (KIND=JPIM)::NFRDHFD
INTEGER (KIND=JPIM)::NFRDHP
INTEGER (KIND=JPIM)::N6BINS
INTEGER (KIND=JPIM)::NPOSTS (0:JPNPST)
INTEGER (KIND=JPIM)::NPOSTSMIN (0:JPNPST)
INTEGER (KIND=JPIM)::NHISTS (0:JPNPST)
INTEGER (KIND=JPIM)::NHISTSMIN (0:JPNPST)
INTEGER (KIND=JPIM)::NSFXHISTS (0:JPNPST)
INTEGER (KIND=JPIM)::NSFXHISTSMIN (0:JPNPST)
INTEGER (KIND=JPIM)::NMASSCONS (0:JPNPST)
INTEGER (KIND=JPIM)::NGDITS (0:JPNPST)
INTEGER (KIND=JPIM)::NSDITS (0:JPNPST)
INTEGER (KIND=JPIM)::NDHFGTS (0:JPNPST)
INTEGER (KIND=JPIM)::NDHFZTS (0:JPNPST)
INTEGER (KIND=JPIM)::NDHFDTS (0:JPNPST)
INTEGER (KIND=JPIM)::NDHPTS (0:JPNPST)
LOGICAL::L4DVAR=.FALSE.
LOGICAL::LCANARI
INTEGER (KIND=JPIM)::NTASKS_CANARI
LOGICAL::LGUESS
LOGICAL::LOBS
LOGICAL::LSIMOB
LOGICAL::LOBSC1
LOGICAL::LSCREEN
LOGICAL::LSCREEN_OPENMP
LOGICAL::L_SPLIT_SCREEN
LOGICAL::L_SCREEN_CALL
LOGICAL::LMONITORING
LOGICAL::LOBSREF
LOGICAL::LIFSMIN
LOGICAL::LIFSTRAJ
INTEGER (KIND=JPIM)::NCNTVAR
LOGICAL::LOLDPP
INTEGER (KIND=JPIM)::NSTEPINI
INTEGER (KIND=JPIM)::NINTERPTRAJ
INTEGER (KIND=JPIM)::NINTERPINCR
LOGICAL::LINFLAT
LOGICAL::LINFLP9
LOGICAL::LINFLF1
LOGICAL::L_OOPS
LOGICAL::L_OOPS_VERBOSE_NORMS
LOGICAL::LECMWF
LOGICAL::LELAM
LOGICAL::LRPLANE
LOGICAL::LAROME
LOGICAL::LCALLSFX
LOGICAL::LSFXLSM
LOGICAL::LCONSERV, LCORWAT
LOGICAL::LSFCFLX
REAL (KIND=JPRB)::REXTSHF
REAL (KIND=JPRB)::REXTLHF
LOGICAL::LROUGH
REAL (KIND=JPRB)::REXTZ0M
REAL (KIND=JPRB)::REXTZ0H
LOGICAL::LCOUPLO4
LOGICAL::LCOUPLO4_ENV
LOGICAL::LSFORC
LOGICAL::LSFORCS
LOGICAL::LWRSPECA_GP=.FALSE.
LOGICAL::LSUSPECA_GP=.FALSE.
LOGICAL::LWRSPECA_GP_UV=.FALSE.
LOGICAL::LSUSPECA_GP_UV=.FALSE.
LOGICAL::LGRIB_API=.TRUE.
INTEGER (KIND=JPIM)::NITER_ADTEST
LOGICAL::LREAD_OROGRAPHY_FIRST
ENDMODULE YOMCT0
