
MODULE YOMCHEM
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
REAL (KIND=JPRB), PARAMETER::REPSCHEM=1.0E-25_JPRB
INTEGER (KIND=JPIM), PARAMETER::IEXTR_EM=1, IEXTR_DD=2, IEXTR_WD&
&=3, IEXTR_CH=4, IEXTR_CHTR=5, IEXTR_NG=6, IEXTR_FE=7
INTEGER (KIND=JPIM), PARAMETER::IEXTR_SDM=8, IEXTR_COND=9, IEXTR_NUC=10, IEXTR_RMOD=11
INTEGER (KIND=JPIM), PARAMETER::IEXTR_ROH=12, IEXTR_PH=13, IEXTR_ROH_TROP=14, IEXTR_CHEMX=15

TYPE::TCHEM
  CHARACTER (LEN=20)::CHEM_SCHEME
  LOGICAL::LCHEM_DIAC
  LOGICAL::LCHEM_BASCOE_JON
  LOGICAL::LCHEM_BASCOE_HETCHEM
  LOGICAL::LCHEM_EXTENDJNO2
  LOGICAL::LMOZART_RSF_DUMMY
  LOGICAL::LCHEM_JOUT
  LOGICAL::LCHEM_LIGHT
  REAL (KIND=JPRB)::RCHEM_LINOX_SCALING
  LOGICAL::LCHEM_ACNOX
  INTEGER (KIND=JPIM)::KCHEM_NOXADV
  INTEGER (KIND=JPIM)::KCHEM_WETDEP
  INTEGER (KIND=JPIM)::KCHEM_DRYDEP
  LOGICAL::LCHEM_ANAO3
  REAL (KIND=JPRB)::SMASSCOR (300, 4)
  LOGICAL::LCHEM_ANACH4
  LOGICAL::LCHEM_WEAK_CH4_RELAXATION
  LOGICAL::LCHEM_CONVSCAV
  LOGICAL::LCHEM_CSHAPE
  LOGICAL::LCHEM_CSHAPE98
  LOGICAL::LCHEM_WDFR
  LOGICAL::LCHEM_FIX_CH4
  INTEGER (KIND=JPIM)::KCHEM_YEARPI
  REAL (KIND=JPRB)::RCH4CONST
  INTEGER (KIND=JPIM)::KCHEM_SOLVE
  LOGICAL::LCHEM_O3RAD
  LOGICAL::LCHEM_TL
  LOGICAL::LCHEM_VSO2_COUPLE
  LOGICAL::LCHEM_AEROI
  INTEGER (KIND=JPIM)::IEXTR_FREE (3, 160)
  INTEGER (KIND=JPIM)::NUCOCH1
  INTEGER (KIND=JPIM)::NUCOCH2
  INTEGER (KIND=JPIM)::NCHEM_LCOCOEF
  CHARACTER (LEN=5)::CHEM_LCOVERS
  LOGICAL::LCHEM_LCOMESO
  LOGICAL::LCHEM_LCOCSTCLIM
  REAL (KIND=JPRB)::RCHEM_LCOTAUTOP
  REAL (KIND=JPRB)::RCHEM_LCOCLIMTOP
  LOGICAL::LCHEM_LCOLIMIT
  REAL (KIND=JPRB)::RCHEM_LCOCOEFA1
  CHARACTER (LEN=5)::CSOLMET_ASIS
  INTEGER (KIND=JPIM)::M_SOLITER_ASIS
  REAL (KIND=JPRB)::SOLCV_ASIS
  REAL (KIND=JPRB)::RTOL_ASIS
  REAL (KIND=JPRB)::ATOL_ASIS
  INTEGER (KIND=JPIM)::N_F_RTOL_ASIS
  INTEGER (KIND=JPIM)::N_F_ATOL_ASIS
  REAL (KIND=JPRB), ALLOCATABLE::TCO2DG (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::TCOTOP (:)
  LOGICAL::LCHEM_ARPCLIM
  LOGICAL::LCHEM_EMICH4
ENDTYPE TCHEM

ENDMODULE YOMCHEM
