MODULE YOMCAPE
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TCAPE
  INTEGER (KIND=JPIM)::NCAPEITER
  INTEGER (KIND=JPIM)::NETAPES
  INTEGER (KIND=JPIM)::NCAPEPSD
  REAL (KIND=JPRB)::GCAPERET
  REAL (KIND=JPRB)::GCAPEPSD
  REAL (KIND=JPRB)::GMISCINV
  REAL (KIND=JPRB)::GCAPEMIN
  REAL (KIND=JPRB)::GCINMAX
  REAL (KIND=JPRB)::GCINMIN
  LOGICAL::LADAE
  LOGICAL::LMCAPEA
ENDTYPE

TYPE (TCAPE), TARGET::YRCAPE
ENDMODULE YOMCAPE
