
MODULE YOMCST
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE TCST
  REAL (KIND=JPRB)::RPI
  REAL (KIND=JPRB)::RCLUM
  REAL (KIND=JPRB)::RHPLA
  REAL (KIND=JPRB)::RKBOL
  REAL (KIND=JPRB)::RNAVO
  REAL (KIND=JPRB)::RDAY
  REAL (KIND=JPRB)::RDAYI
  REAL (KIND=JPRB)::RHOUR
  REAL (KIND=JPRB)::REA
  REAL (KIND=JPRB)::REPSM
  REAL (KIND=JPRB)::RSIYEA
  REAL (KIND=JPRB)::RSIDAY
  REAL (KIND=JPRB)::ROMEGA
  REAL (KIND=JPRB)::RA
  REAL (KIND=JPRB)::RG
  REAL (KIND=JPRB)::R1SA
  REAL (KIND=JPRB)::DEG2RAD
  REAL (KIND=JPRB)::RSIGMA
  REAL (KIND=JPRB)::RI0
  REAL (KIND=JPRB)::R
  REAL (KIND=JPRB)::RMD
  REAL (KIND=JPRB)::RMV
  REAL (KIND=JPRB)::RMO3
  REAL (KIND=JPRB)::RD
  REAL (KIND=JPRB)::RV
  REAL (KIND=JPRB)::RCPD
  REAL (KIND=JPRB)::RCPV
  REAL (KIND=JPRB)::RCVD
  REAL (KIND=JPRB)::RCVV
  REAL (KIND=JPRB)::RKAPPA
  REAL (KIND=JPRB)::RETV
  REAL (KIND=JPRB)::RMCO2
  REAL (KIND=JPRB)::RMCH4
  REAL (KIND=JPRB)::RMN2O
  REAL (KIND=JPRB)::RMCO
  REAL (KIND=JPRB)::RMHCHO
  REAL (KIND=JPRB)::RMNO2
  REAL (KIND=JPRB)::RMSO2
  REAL (KIND=JPRB)::RMSO4
  REAL (KIND=JPRB)::RMCFC11
  REAL (KIND=JPRB)::RMCFC12
  REAL (KIND=JPRB)::RMHCFC22
  REAL (KIND=JPRB)::RMCCL4
  REAL (KIND=JPRB)::RCW
  REAL (KIND=JPRB)::RCS
  REAL (KIND=JPRB)::RATM
  REAL (KIND=JPRB)::RTT
  REAL (KIND=JPRB)::RLVTT
  REAL (KIND=JPRB)::RLSTT
  REAL (KIND=JPRB)::RLVZER
  REAL (KIND=JPRB)::RLSZER
  REAL (KIND=JPRB)::RLMLT
  REAL (KIND=JPRB)::RDT
  REAL (KIND=JPRB)::RESTT
  REAL (KIND=JPRB)::RGAMW
  REAL (KIND=JPRB)::RBETW
  REAL (KIND=JPRB)::RALPW
  REAL (KIND=JPRB)::RGAMS
  REAL (KIND=JPRB)::RBETS
  REAL (KIND=JPRB)::RALPS
  REAL (KIND=JPRB)::RALPD
  REAL (KIND=JPRB)::RBETD
  REAL (KIND=JPRB)::RGAMD
  REAL (KIND=JPRB)::RK1
  REAL (KIND=JPRB)::RK2
  REAL (KIND=JPRB)::RK3
  REAL (KIND=JPRB)::RGNSSSAT
  REAL (KIND=JPRB)::RGNSSEAR
  REAL (KIND=JPRB)::RAWGS
  REAL (KIND=JPRB)::REWGS
  REAL (KIND=JPRB)::RFWGS
  REAL (KIND=JPRB)::RGEQU
  REAL (KIND=JPRB)::RGRAT
  REAL (KIND=JPRB)::RKSSOM
ENDTYPE TCST

REAL (KIND=JPRB), PROTECTED::RPI
REAL (KIND=JPRB), PROTECTED::RCLUM
REAL (KIND=JPRB), PROTECTED::RHPLA
REAL (KIND=JPRB), PROTECTED::RKBOL
REAL (KIND=JPRB), PROTECTED::RNAVO
REAL (KIND=JPRB), PROTECTED::RDAY
REAL (KIND=JPRB), PROTECTED::RDAYI
REAL (KIND=JPRB), PROTECTED::RHOUR
REAL (KIND=JPRB), PROTECTED::REA
REAL (KIND=JPRB), PROTECTED::REPSM
REAL (KIND=JPRB), PROTECTED::RSIYEA
REAL (KIND=JPRB), PROTECTED::RSIDAY
REAL (KIND=JPRB), PROTECTED::ROMEGA
REAL (KIND=JPRB), PROTECTED::RA
REAL (KIND=JPRB), PROTECTED::RA_EARTH
REAL (KIND=JPRB), PROTECTED::RG
REAL (KIND=JPRB), PROTECTED::R1SA
REAL (KIND=JPRB), PROTECTED::DEG2RAD
REAL (KIND=JPRB), PROTECTED::RAD2DEG
REAL (KIND=JPRB), PROTECTED::RSIGMA
REAL (KIND=JPRB), PROTECTED::RI0
REAL (KIND=JPRB), PROTECTED::R
REAL (KIND=JPRB), PROTECTED::RMD
REAL (KIND=JPRB), PROTECTED::RMV
REAL (KIND=JPRB), PROTECTED::RMO3
REAL (KIND=JPRB), PROTECTED::RD
REAL (KIND=JPRB), PROTECTED::RV
REAL (KIND=JPRB), PROTECTED::RCPD
REAL (KIND=JPRB), PROTECTED::RCPV
REAL (KIND=JPRB), PROTECTED::RCVD
REAL (KIND=JPRB), PROTECTED::RCVV
REAL (KIND=JPRB), PROTECTED::RKAPPA
REAL (KIND=JPRB), PROTECTED::RETV
REAL (KIND=JPRB), PROTECTED::RMCO2
REAL (KIND=JPRB), PROTECTED::RMCH4
REAL (KIND=JPRB), PROTECTED::RMN2O
REAL (KIND=JPRB), PROTECTED::RMCO
REAL (KIND=JPRB), PROTECTED::RMHCHO
REAL (KIND=JPRB), PROTECTED::RMNO2
REAL (KIND=JPRB), PROTECTED::RMSO2
REAL (KIND=JPRB), PROTECTED::RMSO4
REAL (KIND=JPRB), PROTECTED::RMCFC11
REAL (KIND=JPRB), PROTECTED::RMCFC12
REAL (KIND=JPRB), PROTECTED::RMHCFC22
REAL (KIND=JPRB), PROTECTED::RMCCL4
REAL (KIND=JPRB), PROTECTED::RCW
REAL (KIND=JPRB), PROTECTED::RCS
REAL (KIND=JPRB), PROTECTED::RATM
REAL (KIND=JPRB), PROTECTED::RTT
REAL (KIND=JPRB), PROTECTED::RLVTT
REAL (KIND=JPRB), PROTECTED::RLSTT
REAL (KIND=JPRB), PROTECTED::RLVZER
REAL (KIND=JPRB), PROTECTED::RLSZER
REAL (KIND=JPRB), PROTECTED::RLMLT
REAL (KIND=JPRB), PROTECTED::RDT
REAL (KIND=JPRB), PROTECTED::RESTT
REAL (KIND=JPRB), PROTECTED::RGAMW
REAL (KIND=JPRB), PROTECTED::RBETW
REAL (KIND=JPRB), PROTECTED::RALPW
REAL (KIND=JPRB), PROTECTED::RGAMS
REAL (KIND=JPRB), PROTECTED::RBETS
REAL (KIND=JPRB), PROTECTED::RALPS
REAL (KIND=JPRB), PROTECTED::RALPD
REAL (KIND=JPRB), PROTECTED::RBETD
REAL (KIND=JPRB), PROTECTED::RGAMD
REAL (KIND=JPRB), PROTECTED::RUNDEF2
CHARACTER (LEN=8), PARAMETER::CSNAN=CHAR (0)//CHAR (0)//CHAR &
&(0)//CHAR (0)//CHAR (0)//CHAR (0)//CHAR (244)//CHAR (127)
REAL (KIND=JPRB), PROTECTED::RSNAN
REAL (KIND=JPRB), PROTECTED::RK1
REAL (KIND=JPRB), PROTECTED::RK2
REAL (KIND=JPRB), PROTECTED::RK3
REAL (KIND=JPRB), PROTECTED::RGNSSSAT
REAL (KIND=JPRB), PROTECTED::RGNSSEAR
REAL (KIND=JPRB), PROTECTED::RAWGS
REAL (KIND=JPRB), PROTECTED::REWGS
REAL (KIND=JPRB), PROTECTED::RFWGS
REAL (KIND=JPRB), PROTECTED::RGEQU
REAL (KIND=JPRB), PROTECTED::RGRAT
REAL (KIND=JPRB), PROTECTED::RKSSOM
LOGICAL, PROTECTED::L_HAS_BEEN_SETUP=.FALSE.
TYPE (TCST), TARGET::YRCST
CONTAINS



ENDMODULE YOMCST
