MODULE YOMCLI
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TCLI
  LOGICAL::LIEEE
  LOGICAL::LGLOBE
  LOGICAL::LZ0THER
  INTEGER (KIND=JPIM)::NPINT
  INTEGER (KIND=JPIM)::NDATX
  INTEGER (KIND=JPIM)::NDATY
  INTEGER (KIND=JPIM)::NAEROF
  INTEGER (KIND=JPIM)::NGLOBX
  INTEGER (KIND=JPIM)::NGLOBY
  INTEGER (KIND=JPIM)::NTPMER
  INTEGER (KIND=JPIM)::NTPGLA
  INTEGER (KIND=JPIM)::NTPDES
  INTEGER (KIND=JPIM)::NTPLAC
  INTEGER (KIND=JPIM)::NSLICE
  REAL (KIND=JPRB)::ELONSW
  REAL (KIND=JPRB)::ELATSW
  REAL (KIND=JPRB)::ELONNE
  REAL (KIND=JPRB)::ELATNE
  REAL (KIND=JPRB)::EDLON
  REAL (KIND=JPRB)::EDLAT
  REAL (KIND=JPRB)::SMASK
  REAL (KIND=JPRB)::SMANQ
  REAL (KIND=JPRB)::SVEG
  REAL (KIND=JPRB)::SFCZ0
  REAL (KIND=JPRB)::RSTR
  REAL (KIND=JPRB)::RSWR
  REAL (KIND=JPRB)::STHER
  REAL (KIND=JPRB)::SALBN
  REAL (KIND=JPRB)::SALBX
  REAL (KIND=JPRB)::SALBM
  REAL (KIND=JPRB)::SALBG
  REAL (KIND=JPRB)::SALBB
  REAL (KIND=JPRB)::SALBD
  REAL (KIND=JPRB)::SEMIN
  REAL (KIND=JPRB)::SEMIX
  REAL (KIND=JPRB)::SEMIM
  REAL (KIND=JPRB)::SEMIG
  REAL (KIND=JPRB)::SEMIB
  REAL (KIND=JPRB)::SEMID
  REAL (KIND=JPRB)::SDEPN
  REAL (KIND=JPRB)::SDEPX
  REAL (KIND=JPRB)::SDEPD
  REAL (KIND=JPRB)::SARGN
  REAL (KIND=JPRB)::SARGX
  REAL (KIND=JPRB)::SARGD
  REAL (KIND=JPRB)::SSABN
  REAL (KIND=JPRB)::SSABX
  REAL (KIND=JPRB)::SSABD
  REAL (KIND=JPRB)::SRSMN
  REAL (KIND=JPRB)::SRSMX
  REAL (KIND=JPRB)::SRSMD
  REAL (KIND=JPRB)::SZZ0N
  REAL (KIND=JPRB)::SZZ0M
  REAL (KIND=JPRB)::SZZ0B
  REAL (KIND=JPRB)::SZZ0U
  REAL (KIND=JPRB)::SZZ0D
ENDTYPE TCLI

TYPE (TCLI), TARGET::YRCLI
ENDMODULE YOMCLI
