
MODULE YOMCOMPO
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::NPEMIS2D=500
INTEGER (KIND=JPIM), PARAMETER::NPEMIS2DAUX=10
INTEGER (KIND=JPIM), PARAMETER::NPEMIS3D=10

TYPE::TCOMPO_EMIS
  CHARACTER (LEN=16)::SPECIES=''
  CHARACTER (LEN=20)::SECTOR=''
  INTEGER (KIND=JPIM)::PARAMID=-9999
  INTEGER (KIND=JPIM)::PARAM_INDEX=-9999
  INTEGER (KIND=JPIM)::NREQIN=1
  REAL (KIND=JPRB)::SCALING=1.0_JPRB
  CHARACTER (LEN=16)::DIURNAL_CYCLE_TYPE='Uniform'
  REAL (KIND=JPRB)::DIURNAL_AMPLITUDE=0.0_JPRB
  REAL (KIND=JPRB)::DIURNAL_PEAK_HOUR=12.0_JPRB
  REAL (KIND=JPRB)::DIURNAL_BASELINE=0.0_JPRB
  CHARACTER (LEN=16)::VERTICAL_PROFILE_TYPE='Surface'
  REAL (KIND=JPRB)::VERTICAL_SURFACE_FRACTION=0.0_JPRB
  REAL (KIND=JPRB)::VERTICAL_BASE_HEIGHT=0.0_JPRB
  REAL (KIND=JPRB)::VERTICAL_TOP_HEIGHT=0.0_JPRB
  REAL (KIND=JPRB)::VERTICAL_THRESHOLD=0.0_JPRB
  INTEGER (KIND=JPIM)::VERTICAL_BASE_LEVEL=0
  INTEGER (KIND=JPIM)::VERTICAL_TOP_LEVEL=0
  INTEGER (KIND=JPIM)::VERTICAL_PARAMID=-9999
  INTEGER (KIND=JPIM)::VERTICAL_PARAM_INDEX=-9999
  CHARACTER (LEN=8)::TEMPORALITY='Default'
  INTEGER (KIND=JPIM)::LEGACY_CHEM_OVERRIDE=0
  LOGICAL::NON_SIMPLE_TRACER=.FALSE.
ENDTYPE TCOMPO_EMIS


TYPE::TCOMPO_EMIS_AUX
  INTEGER (KIND=JPIM)::PARAMID=0
  CHARACTER (LEN=8)::TEMPORALITY='Default'
  CHARACTER (LEN=16)::CNAME=''
ENDTYPE TCOMPO_EMIS_AUX


TYPE::TCOMPO
  LOGICAL::LCHEM_DIA
  REAL (KIND=JPRB)::RCHEM_DIA_PERIOD
  LOGICAL::LCHEM_DDFLX
  LOGICAL::LCOMPO_DDFLX_DIR
  LOGICAL::LCHEM_TROPO
  LOGICAL::LAEREQSAM4CLIM
  LOGICAL::LCHEM_EQSAM4CLIMPH
  LOGICAL::LAEROSFC
  LOGICAL::LCOMPO_DCDD
  LOGICAL::LAERNITRATE
  LOGICAL::LAERRESUSPENSION
  LOGICAL::LAERSOA
  LOGICAL::LAERSOA_COUPLED
  INTEGER (KIND=JPIM)::KGHG_CHEMTEND_CH4
  LOGICAL::LAERNUCL
  CHARACTER (LEN=10)::AERO_SCHEME
  INTEGER (KIND=JPIM)::NEMIS2D_DESC
  TYPE (TCOMPO_EMIS), DIMENSION (:), ALLOCATABLE::YEMIS2D_DESC
  INTEGER (KIND=JPIM)::NEMIS3D_DESC
  TYPE (TCOMPO_EMIS), DIMENSION (:), ALLOCATABLE::YEMIS3D_DESC
  TYPE (TCOMPO_EMIS_AUX), DIMENSION (:), ALLOCATABLE::YEMIS2DAUX_DESC
ENDTYPE TCOMPO

CHARACTER (LEN=10)::AERO_SCHEME_OP_OBS
CONTAINS


ENDMODULE YOMCOMPO
