MODULE YOMCFU_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK
USE TYPE_FLUXES,ONLY:FLUXES_DESCRIPTOR
USE PTRGFU,ONLY:TCFUPTR
USE FIELD_MODULE

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::JPFUST=40

TYPE::TCFU_KEYS
  LOGICAL::LCUMFU=.FALSE.
  LOGICAL::LSTRD=.FALSE.
  LOGICAL::LSTRC=.FALSE.
  LOGICAL::LSTRT=.FALSE.
  LOGICAL::LFPLC=.FALSE.
  LOGICAL::LFPLCG=.FALSE.
  LOGICAL::LFPLCH=.FALSE.
  LOGICAL::LFPLS=.FALSE.
  LOGICAL::LFPLSG=.FALSE.
  LOGICAL::LFPLSH=.FALSE.
  LOGICAL::LFR=.FALSE.
  LOGICAL::LAMIP=.FALSE.
  LOGICAL::LRAYS=.FALSE.
  LOGICAL::LRAYD=.FALSE.
  LOGICAL::LNEBTT=.FALSE.
  LOGICAL::LFSF=.FALSE.
  LOGICAL::LFSOIL=.FALSE.
  LOGICAL::LNEBPAR=.FALSE.
  LOGICAL::LTSTRD=.FALSE.
  LOGICAL::LTSTRC=.FALSE.
  LOGICAL::LTSTRT=.FALSE.
  LOGICAL::LTFPLC=.FALSE.
  LOGICAL::LTFPLS=.FALSE.
  LOGICAL::LTFR=.FALSE.
  LOGICAL::LTNEB=.FALSE.
  LOGICAL::LFDUTP=.FALSE.
  LOGICAL::LMOON=.FALSE.
  LOGICAL::LFRRC=.FALSE.
  LOGICAL::LFLASH=.FALSE.
  LOGICAL::LWSNOW=.FALSE.
  LOGICAL::LWFPAC=.FALSE.
ENDTYPE TCFU_KEYS


TYPE, EXTENDS (TCFU_KEYS)::TCFU
  INTEGER (KIND=JPIM)::NCFUTS (0:JPFUST)
  INTEGER (KIND=JPIM)::NFRRC
  INTEGER (KIND=JPIM)::NFRCFU
  INTEGER (KIND=JPIM)::NFDCFU
  INTEGER (KIND=JPIM)::NTYPCFU
  INTEGER (KIND=JPIM)::NMTFLASH
  REAL (KIND=JPRB)::CALFLASH1, CALFLASH2
  REAL (KIND=JPRB)::RBASEMAX
  LOGICAL::LREACFU=.FALSE.
  TYPE (FLUXES_DESCRIPTOR), ALLOCATABLE::TYPE_CFU (:)
  TYPE (TCFUPTR)::YCFUPT
  REAL (KIND=JPRB), POINTER::CFUBUF_B (:,:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER::FCCQL (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FCCQL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCCQL
  REAL (KIND=JPRB), POINTER::FCCQN (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FCCQN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCCQN
  REAL (KIND=JPRB), POINTER::FCHSP (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FCHSP=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCHSP
  REAL (KIND=JPRB), POINTER::FCL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FCL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCL
  REAL (KIND=JPRB), POINTER::FCLL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FCLL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCLL
  REAL (KIND=JPRB), POINTER::FCLN (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FCLN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCLN
  REAL (KIND=JPRB), POINTER::FCSQL (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FCSQL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCSQL
  REAL (KIND=JPRB), POINTER::FCSQN (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FCSQN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCSQN
  REAL (KIND=JPRB), POINTER::FCS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FCS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCS
  REAL (KIND=JPRB), POINTER::FDICQ (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FDICQ=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFDICQ
  REAL (KIND=JPRB), POINTER::FDICS (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FDICS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFDICS
  REAL (KIND=JPRB), POINTER::FDISH (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FDISH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFDISH
  REAL (KIND=JPRB), POINTER::FDITQ (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FDITQ=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFDITQ
  REAL (KIND=JPRB), POINTER::FDITS (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FDITS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFDITS
  REAL (KIND=JPRB), POINTER::FDUTP (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FDUTP=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFDUTP
  REAL (KIND=JPRB), POINTER::FEVL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FEVL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFEVL
  REAL (KIND=JPRB), POINTER::FEVN (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FEVN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFEVN
  REAL (KIND=JPRB), POINTER::FEVV (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FEVV=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFEVV
  REAL (KIND=JPRB), POINTER::FGEL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FGEL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFGEL
  REAL (KIND=JPRB), POINTER::FGELS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FGELS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFGELS
  REAL (KIND=JPRB), POINTER::FLASH (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FLASH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFLASH
  REAL (KIND=JPRB), POINTER::DIAMACCR (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_DIAMACCR=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YDIAMACCR
  REAL (KIND=JPRB), POINTER::LOADICE (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_LOADICE=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YLOADICE
  REAL (KIND=JPRB), POINTER::LOADSNOW (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_LOADSNOW=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YLOADSNOW
  REAL (KIND=JPRB), POINTER::PCPWSNOW (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_PCPWSNOW=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPCPWSNOW
  REAL (KIND=JPRB), POINTER::PCPICE (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_PCPICE=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPCPICE
  REAL (KIND=JPRB), POINTER::FLWSP (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FLWSP=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFLWSP
  REAL (KIND=JPRB), POINTER::FNEB (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FNEB=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFNEB
  REAL (KIND=JPRB), POINTER::FNEBT (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FNEBT=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFNEBT
  REAL (KIND=JPRB), POINTER::FONTE (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FONTE=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFONTE
  REAL (KIND=JPRB), POINTER::FPLCG (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FPLCG=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFPLCG
  REAL (KIND=JPRB), POINTER::FPLCH (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FPLCH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFPLCH
  REAL (KIND=JPRB), POINTER::FPLCL (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FPLCL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFPLCL
  REAL (KIND=JPRB), POINTER::FPLCN (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FPLCN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFPLCN
  REAL (KIND=JPRB), POINTER::FPLSG (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FPLSG=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFPLSG
  REAL (KIND=JPRB), POINTER::FPLSH (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FPLSH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFPLSH
  REAL (KIND=JPRB), POINTER::FPLSL (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FPLSL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFPLSL
  REAL (KIND=JPRB), POINTER::FPLSN (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FPLSN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFPLSN
  REAL (KIND=JPRB), POINTER::FRSDNI (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRSDNI=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRSDNI
  REAL (KIND=JPRB), POINTER::FRSGNI (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRSGNI=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRSGNI
  REAL (KIND=JPRB), POINTER::FRSOC0 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRSOC0=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRSOC0
  REAL (KIND=JPRB), POINTER::FRSOC1 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRSOC1=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRSOC1
  REAL (KIND=JPRB), POINTER::FRSODS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRSODS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRSODS
  REAL (KIND=JPRB), POINTER::FRSOLU (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRSOLU=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRSOLU
  REAL (KIND=JPRB), POINTER::FRSOPS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRSOPS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRSOPS
  REAL (KIND=JPRB), POINTER::FRSOPT (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRSOPT=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRSOPT
  REAL (KIND=JPRB), POINTER::FRSO (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FRSO=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRSO
  REAL (KIND=JPRB), POINTER::FRTHC0 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRTHC0=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRTHC0
  REAL (KIND=JPRB), POINTER::FRTHC1 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRTHC1=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRTHC1
  REAL (KIND=JPRB), POINTER::FRTHDS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FRTHDS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRTHDS
  REAL (KIND=JPRB), POINTER::FRTH (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_FRTH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFRTH
  REAL (KIND=JPRB), POINTER::FTOPH (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FTOPH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFTOPH
  REAL (KIND=JPRB), POINTER::FTR (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FTR=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFTR
  REAL (KIND=JPRB), POINTER::NEBBAS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NEBBAS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNEBBAS
  REAL (KIND=JPRB), POINTER::NEBCON (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NEBCON=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNEBCON
  REAL (KIND=JPRB), POINTER::NEBHAU (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NEBHAU=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNEBHAU
  REAL (KIND=JPRB), POINTER::NEBMOY (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NEBMOY=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNEBMOY
  REAL (KIND=JPRB), POINTER::OZONT (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_OZONT=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YOZONT
  REAL (KIND=JPRB), POINTER::QICE (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_QICE=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YQICE
  REAL (KIND=JPRB), POINTER::QLI (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_QLI=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YQLI
  REAL (KIND=JPRB), POINTER::QTOT (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_QTOT=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YQTOT
  REAL (KIND=JPRB), POINTER::RUISL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RUISL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YRUISL
  REAL (KIND=JPRB), POINTER::RUISP (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RUISP=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YRUISP
  REAL (KIND=JPRB), POINTER::RUISS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RUISS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YRUISS
  REAL (KIND=JPRB), POINTER::SNS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SNS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSNS
  REAL (KIND=JPRB), POINTER::SPRES (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SPRES=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSPRES
  REAL (KIND=JPRB), POINTER::STRCU (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_STRCU=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSTRCU
  REAL (KIND=JPRB), POINTER::STRCV (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_STRCV=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSTRCV
  REAL (KIND=JPRB), POINTER::STRDU (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_STRDU=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSTRDU
  REAL (KIND=JPRB), POINTER::STRDV (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_STRDV=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSTRDV
  REAL (KIND=JPRB), POINTER::STRTU (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_STRTU=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSTRTU
  REAL (KIND=JPRB), POINTER::STRTV (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_STRTV=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSTRTV
  REAL (KIND=JPRB), POINTER::WS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_WS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YWS
  REAL (KIND=JPRB), POINTER::WFPAC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_WFPAC=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YWFPAC
  
  
  
  
  
ENDTYPE TCFU

CONTAINS




ENDMODULE YOMCFU_TYPE
