MODULE YOMCOM
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE

TYPE::TCOM
  INTEGER (KIND=JPIM)::NVCOM
  REAL (KIND=JPRB), ALLOCATABLE::OMLDTH (:)
  REAL (KIND=JPRB), ALLOCATABLE::GTTLIN (:)
  REAL (KIND=JPRB), ALLOCATABLE::SSTPRE (:)
  REAL (KIND=JPRB), ALLOCATABLE::SSTMSK (:)
  LOGICAL::LOMLDTH
  REAL (KIND=JPRB), ALLOCATABLE::TRAFLX (:)
  
ENDTYPE TCOM

CONTAINS

ENDMODULE YOMCOM
