
MODULE YOMDYN
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMSWE,ONLY:TSWE

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::JPSLDIMK=4

TYPE::TDYN
  REAL (KIND=JPRB)::REPS1
  REAL (KIND=JPRB)::REPS2
  REAL (KIND=JPRB)::REPSM1
  REAL (KIND=JPRB)::REPSM2
  REAL (KIND=JPRB)::REPSP1
  REAL (KIND=JPRB)::HDIRVOR
  REAL (KIND=JPRB)::HDIRDIV
  REAL (KIND=JPRB)::HDIRT
  REAL (KIND=JPRB)::HDIRQ
  REAL (KIND=JPRB)::HDIRO3
  REAL (KIND=JPRB)::HDIRPD
  REAL (KIND=JPRB)::HDIRVD
  REAL (KIND=JPRB)::HDIRSP
  REAL (KIND=JPRB)::HRDIRVOR
  REAL (KIND=JPRB)::HRDIRDIV
  REAL (KIND=JPRB)::HRDIRT
  REAL (KIND=JPRB)::HRDIRQ
  REAL (KIND=JPRB)::HRDIRO3
  REAL (KIND=JPRB)::HRDIRPD
  REAL (KIND=JPRB)::HRDIRVD
  REAL (KIND=JPRB)::HRDIRSP
  REAL (KIND=JPRB)::RRDXTAU
  REAL (KIND=JPRB)::RDAMPVOR
  REAL (KIND=JPRB)::RDAMPDIV
  REAL (KIND=JPRB)::RDAMPT
  REAL (KIND=JPRB)::RDAMPQ
  REAL (KIND=JPRB)::RDAMPO3
  REAL (KIND=JPRB)::RDAMPPD
  REAL (KIND=JPRB)::RDAMPVD
  REAL (KIND=JPRB)::RDAMPSP
  LOGICAL::LNEWHD
  REAL (KIND=JPRB)::REXPDH
  REAL (KIND=JPRB)::FRANDH
  REAL (KIND=JPRB)::SLEVDH
  REAL (KIND=JPRB)::SLEVDH1
  REAL (KIND=JPRB)::SLEVDH2
  REAL (KIND=JPRB)::SLEVDH3
  INTEGER (KIND=JPIM)::NSREFDH
  REAL (KIND=JPRB)::RATIO_HDI_TOP
  INTEGER (KIND=JPIM)::NPROFILEHD
  REAL (KIND=JPRB)::RPROFHDBT
  REAL (KIND=JPRB)::RPROFHDTP
  REAL (KIND=JPRB)::RPROFHDMX
  REAL (KIND=JPRB)::RPROFHDEX
  LOGICAL::LRDISPE_EC
  REAL (KIND=JPRB), ALLOCATABLE::RDIVOR (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDIDIV (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDITG (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDIGFL (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDIPD (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDIVD (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDISP (:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHI (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHIVOR (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHIDIV (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHISPD (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHISVD (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHINHX (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHIT (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHIGFL (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHIP (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHSVOR (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHSDIV (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHSSVD (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHSNHX (:,:,:)
  LOGICAL::LSTRHD
  REAL (KIND=JPRB)::HDTIME_STRHD
  REAL (KIND=JPRB)::KLSPONGE
  LOGICAL::LM0DAMP
  REAL (KIND=JPRB)::RBEGSPONGE
  LOGICAL::LTOP_VOR
  INTEGER (KIND=JPIM)::NTOP_VOR_TRUNC
  INTEGER (KIND=JPIM)::NTOP_VOR_BOT
  REAL (KIND=JPRB), ALLOCATABLE::RSAVEDP (:,:,:,:)
  REAL (KIND=JPRB)::SLHDA0
  REAL (KIND=JPRB)::SLHDA0T
  REAL (KIND=JPRB)::SLHDB
  REAL (KIND=JPRB)::SLHDBT
  REAL (KIND=JPRB)::SLHDD00
  REAL (KIND=JPRB)::SLHDD00T
  REAL (KIND=JPRB)::SLHDDIV
  REAL (KIND=JPRB)::SLHDRATDDIV
  REAL (KIND=JPRB)::SLHDHOR
  REAL (KIND=JPRB)::SLHD_P_LOW
  REAL (KIND=JPRB)::SLHD_P_HIGH
  LOGICAL::LSLHDHEAT
  LOGICAL::LSLHDSPONGE
  REAL (KIND=JPRB)::HDSRVOR
  REAL (KIND=JPRB)::HDSRDIV
  REAL (KIND=JPRB)::HDSRVD
  REAL (KIND=JPRB)::HRDSRVOR
  REAL (KIND=JPRB)::HRDSRDIV
  REAL (KIND=JPRB)::HRDSRVD
  REAL (KIND=JPRB)::RDAMPVORS
  REAL (KIND=JPRB)::RDAMPDIVS
  REAL (KIND=JPRB)::RDAMPVDS
  REAL (KIND=JPRB)::RDAMPHDS
  REAL (KIND=JPRB)::REXPDHS
  REAL (KIND=JPRB)::SLEVDHS
  REAL (KIND=JPRB)::SLEVDHS1
  REAL (KIND=JPRB)::SLEVDHS2
  REAL (KIND=JPRB)::SDRED
  REAL (KIND=JPRB), ALLOCATABLE::RDSVOR (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDSDIV (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDSVD (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RDHS (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SLHD_MASK_U (:)
  REAL (KIND=JPRB), ALLOCATABLE::SLHD_MASK_T (:)
  REAL (KIND=JPRB)::ZSLHDP1
  REAL (KIND=JPRB)::ZSLHDP3
  INTEGER (KIND=JPIM)::NLEV_SPONGE
  LOGICAL::LRFRIC
  LOGICAL::LRFRICISOTR
  REAL (KIND=JPRB), ALLOCATABLE::RCORDIT (:)
  REAL (KIND=JPRB), ALLOCATABLE::RCORDIH (:)
  REAL (KIND=JPRB), ALLOCATABLE::RCORDIF (:)
  REAL (KIND=JPRB)::VMAX1
  REAL (KIND=JPRB)::VMAX2
  REAL (KIND=JPRB)::RMAX_D3
  LOGICAL::LBOUND_D3
  REAL (KIND=JPRB), ALLOCATABLE::RKRF (:)
  INTEGER (KIND=JPIM)::NMAXLEVRF
  REAL (KIND=JPRB)::RRFZ1
  REAL (KIND=JPRB)::RRFPLM
  REAL (KIND=JPRB)::RRFTAU
  REAL (KIND=JPRB)::RTEMRB
  INTEGER (KIND=JPIM)::NRUBC
  LOGICAL::LGWFRIC
  INTEGER (KIND=JPIM)::NLEV_GWFRIC
  REAL (KIND=JPRB)::RGWFRIC_MAX
  REAL (KIND=JPRB)::RGWFRIC_PLM
  REAL (KIND=JPRB), ALLOCATABLE::RGWFRIC (:)
  LOGICAL::LSIDG
  LOGICAL::LDYN_STABAN
  LOGICAL::LRHDI_LASTITERPC
  LOGICAL::LSIDYN_VERBOSE
  REAL (KIND=JPRB)::BETADT
  REAL (KIND=JPRB)::RBT
  REAL (KIND=JPRB)::RBTS2
  REAL (KIND=JPRB)::REFGEO
  REAL (KIND=JPRB)::SIPR
  REAL (KIND=JPRB)::SIPRA
  REAL (KIND=JPRB)::SITR
  REAL (KIND=JPRB)::SITRA
  REAL (KIND=JPRB)::SITRUB
  REAL (KIND=JPRB)::SIPRUB
  REAL (KIND=JPRB)::SITIME
  REAL (KIND=JPRB)::SIRPRG
  REAL (KIND=JPRB)::SIRPRN
  REAL (KIND=JPRB)::SISLP
  REAL (KIND=JPRB)::SIFRG
  REAL (KIND=JPRB)::SIFRA
  REAL (KIND=JPRB)::SITVAR
  INTEGER (KIND=JPIM)::NSITER
  INTEGER (KIND=JPIM)::NCURRENT_ITER
  INTEGER (KIND=JPIM)::NITERHELM
  INTEGER (KIND=JPIM)::NOPT_SITR
  INTEGER (KIND=JPIM)::NOPT_SIPR
  INTEGER (KIND=JPIM)::NOPT_SISLP
  INTEGER (KIND=JPIM)::NSZNISNAX
  REAL (KIND=JPRB), ALLOCATABLE::SITRAM (:)
  REAL (KIND=JPRB), ALLOCATABLE::SITRM (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIALPH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SILNPR (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIDELP (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIRDEL (:)
  REAL (KIND=JPRB), ALLOCATABLE::SITLAH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SITLAF (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIDPHI (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIALPH_NH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SILNPR_NH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIDELP_NH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIRDEL_NH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SITLAH_NH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SITLAF_NH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIDPHI_NH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIWF2H (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIWH2F (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIGFL (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIGFM (:)
  REAL (KIND=JPRB), ALLOCATABLE::SITFL (:)
  REAL (KIND=JPRB), ALLOCATABLE::SITFM (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIGHL (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIGHM (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIB (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIMO (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIMI (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIVP (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIVP2 (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIPD (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIPE (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIPF (:)
  LOGICAL::LLONEM
  LOGICAL::LLPARTOP
  LOGICAL::LL_CALL_SPCIMPF
  LOGICAL::LLONEBLOCK_GPUWAY
  INTEGER (KIND=JPIM), ALLOCATABLE::SINISNAX (:)
  REAL (KIND=JPRB), ALLOCATABLE::SILAPDI (:)
  REAL (KIND=JPRB), ALLOCATABLE::SILAPIN (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIHEG (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIHEG2 (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIHEGB (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIHEGB2 (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIFAC (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIFACI (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIBQ (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIMITRA (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIMOTRA (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIFACITRA (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIHEGTRA (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIHEG2TRA (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIHEGBTRA (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIHEGB2TRA (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIHEGIND (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIBQTRA (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SIZA (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIZC (:)
  REAL (KIND=JPRB), ALLOCATABLE::SIPIS (:)
  REAL (KIND=JPRB), ALLOCATABLE::SITGR (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SITAC (:)
  REAL (KIND=JPRB)::VNORM
  REAL (KIND=JPRB)::SLOPE_MAX
  REAL (KIND=JPRB)::PSURF_MAX
  REAL (KIND=JPRB)::PSURF_MIN
  INTEGER (KIND=JPIM)::NVLAG
  INTEGER (KIND=JPIM)::NWLAG
  INTEGER (KIND=JPIM)::NTLAG
  INTEGER (KIND=JPIM)::NSPDLAG
  INTEGER (KIND=JPIM)::NSVDLAG
  INTEGER (KIND=JPIM)::NSPLTHOI
  LOGICAL::LSPLTHOIGFL
  INTEGER (KIND=JPIM)::NSLDIMK
  INTEGER (KIND=JPIM)::NITMP
  REAL (KIND=JPRB)::VETAON
  REAL (KIND=JPRB)::VETAOX
  LOGICAL::LSETTLSVF
  LOGICAL::LSETFSTAT
  LOGICAL::LSETTLSVF_DIFF
  REAL (KIND=JPRB)::RW2TLFF
  REAL (KIND=JPRB)::RALPHA
  REAL (KIND=JPRB)::RALPHA_TOP
  INTEGER (KIND=JPIM)::NLEV_ZALPHA
  INTEGER (KIND=JPIM)::NEDER
  REAL (KIND=JPRB)::RBETAK (1:3, 1:10)
  LOGICAL::LWENOBC
  INTEGER (KIND=JPIM)::NQMHOISLT
  LOGICAL::LSLDP_RK
  LOGICAL::LSLDP_CURV
  LOGICAL::LSLDP_CURV_FIX
  LOGICAL::LRHS_CURV
  LOGICAL::LRHS_CURV_FIX
  LOGICAL::LSLDP_XYZ
  LOGICAL::LSLDP_SAVE
  REAL (KIND=JPRB)::VESL
  REAL (KIND=JPRB)::XIDT
  LOGICAL::LQMW
  LOGICAL::LQMHW
  LOGICAL::LQMT
  LOGICAL::LQMHT
  LOGICAL::LQMP
  LOGICAL::LQMHP
  LOGICAL::LQMPD
  LOGICAL::LQMHPD
  LOGICAL::LQMVD
  LOGICAL::LQMHVD
  LOGICAL::LVWENO_W, LVWENO_T, LVWENO_SP, LVWENO_SPD, LVWENO_SVD
  REAL (KIND=JPRB)::WENO_ALPHA_W, WENO_ALPHA_T, WENO_ALPHA_SP, WENO_ALPHA_SPD, WENO_ALPHA_SVD
  LOGICAL::LADVF
  LOGICAL::LIMPF
  LOGICAL::L2TLFF
  REAL (KIND=JPRB)::RCMSLP0
  INTEGER (KIND=JPIM)::NCOMP_CVGQ
  LOGICAL::LSVTSM
  REAL (KIND=JPRB)::RPRES_SVTSM
  REAL (KIND=JPRB)::RPRES_SETTLSVF
  INTEGER (KIND=JPIM)::NFLEVSF
  REAL (KIND=JPRB)::RSCALE
  REAL (KIND=JPRB)::RSCALEOFF
  REAL (KIND=JPRB)::RINTOPT
  REAL (KIND=JPRB)::RRINTOPT
  LOGICAL::LHDIFFM
  LOGICAL::LSPECVIS
  INTEGER (KIND=JPIM)::NDIFFACT
  LOGICAL::LGPSTRESS
  REAL (KIND=JPRB)::RCLSTRESS
  REAL (KIND=JPRB)::RCLPOLE
  INTEGER (KIND=JPIM)::NVSEPC, NVSEPL
  LOGICAL::LFINDVSEP
  LOGICAL::LMASCOR
  LOGICAL::LMASDRY
  LOGICAL::LGPMASCOR
  INTEGER (KIND=JPIM)::NGPMASCOR
  REAL (KIND=JPRB)::GPMASSI
  REAL (KIND=JPRB)::GMASSI
  REAL (KIND=JPRB)::GMASS0
  REAL (KIND=JPRB)::GMASSINC
  LOGICAL::LNODRYFLX
  REAL (KIND=JPRB), ALLOCATABLE::SIBI (:,:)
  REAL (KIND=JPRB)::RESGP
  REAL (KIND=JPRB)::RESGM
  LOGICAL::LNHHY_SOLVER_GP, LNHHY_SOLVER_SP
  LOGICAL::LNHQE_SOLVER_GP, LNHQE_SOLVER_SP
  LOGICAL::LRESET_BLEND_SI
  INTEGER (KIND=JPIM)::NSTOP_BLEND, NSTART_BLEND
  REAL (KIND=JPRB)::RNHQE_DELTAM
  REAL (KIND=JPRB), ALLOCATABLE::RNHHY_DELTAM (:)
  TYPE (TSWE)::YRSWE
  CHARACTER (LEN=8)::CLAITRI_TYPE='NONE'
  CHARACTER (LEN=8)::CLAITRI_WENO_TYPE='NONE'
  REAL (KIND=JPRB), ALLOCATABLE::RGAMMA_WENO (:,:)
  
ENDTYPE TDYN

CONTAINS

ENDMODULE YOMDYN
