MODULE YOMDFI
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
REAL (KIND=JPRB), ALLOCATABLE::HWOPF (:,:)
REAL (KIND=JPRB), ALLOCATABLE::HWOPFA (:,:)
REAL (KIND=JPRB), ALLOCATABLE::HWF0 (:)
REAL (KIND=JPRB), ALLOCATABLE::HWFA0 (:)
INTEGER (KIND=JPIM)::NTPDFI
INTEGER (KIND=JPIM)::NEDFI
INTEGER (KIND=JPIM)::NSTDFI
INTEGER (KIND=JPIM)::NSTDFIA
INTEGER (KIND=JPIM)::NOFFSETDFI
REAL (KIND=JPRB)::TAUS
REAL (KIND=JPRB)::TAUC
REAL (KIND=JPRB)::RTDFI
REAL (KIND=JPRB)::RTDFIA
REAL (KIND=JPRB)::RDFIS
LOGICAL::LADIFH
ENDMODULE YOMDFI
