MODULE YOMDGRADIENT
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE


TYPE TGRADIENT_PTR
  INTEGER::M_DUDX
  INTEGER::M_DUDY
  INTEGER::M_DVDX
  INTEGER::M_DVDY
  INTEGER::M_DTDX
  INTEGER::M_DTDY
  INTEGER::M_DQVDX
  INTEGER::M_DQVDY
  INTEGER::M_DQLDX
  INTEGER::M_DQLDY
  INTEGER::M_DQIDX
  INTEGER::M_DQIDY
  INTEGER::M_DQRDX
  INTEGER::M_DQRDY
  INTEGER::M_DQSDX
  INTEGER::M_DQSDY
  INTEGER::M_DQGDX
  INTEGER::M_DQGDY
  INTEGER::M_DU2DX2
  INTEGER::M_DU2DY2
  INTEGER::M_DV2DX2
  INTEGER::M_DV2DY2
  INTEGER::M_DUDXZ
  INTEGER::M_DUDYZ
  INTEGER::M_DVDXZ
  INTEGER::M_DVDYZ
  INTEGER::M_DWDXZ
  INTEGER::M_DWDYZ
  INTEGER::M_DRVDXZ
  INTEGER::M_DRVDYZ
  INTEGER::M_DRLDXZ
  INTEGER::M_DRLDYZ
  INTEGER::M_DRIDXZ
  INTEGER::M_DRIDYZ
  INTEGER::M_DTHETADXZ
  INTEGER::M_DTHETADYZ
  INTEGER::NFLDCORE
  INTEGER::NDIM
  INTEGER::NDIMLEO
  INTEGER::NDIMGOG
ENDTYPE


TYPE TGRADIENT
  TYPE (TGRADIENT_PTR)::YPTR
ENDTYPE

CONTAINS

ENDMODULE YOMDGRADIENT
