MODULE YOMDWET
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE TDWET
  REAL (KIND=JPRB)::WBETA
  REAL (KIND=JPRB)::WRHOA
  REAL (KIND=JPRB)::WRHOB
  REAL (KIND=JPRB)::WDIAMWIRE
  REAL (KIND=JPRB)::HWET
  REAL (KIND=JPRB)::WURA
  REAL (KIND=JPRB)::WURB
  REAL (KIND=JPRB)::WFALLSN
  REAL (KIND=JPRB)::WTTA
  REAL (KIND=JPRB)::WTWB
  REAL (KIND=JPRB)::WTWA
  REAL (KIND=JPRB)::WTWDRYB
  REAL (KIND=JPRB)::WUUDRY
  REAL (KIND=JPRB)::WFALLICE
  REAL (KIND=JPRB)::WTWAICE
  REAL (KIND=JPRB)::WTWBICE
  REAL (KIND=JPRB)::WBETAICE
ENDTYPE TDWET

ENDMODULE YOMDWET
