MODULE YOMDIMF
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TDIMF
  INTEGER (KIND=JPIM)::NFTHER
  INTEGER (KIND=JPIM)::NF3D
  INTEGER (KIND=JPIM)::NFD2D
  INTEGER (KIND=JPIM)::NFC2D
  INTEGER (KIND=JPIM)::NS3D
  INTEGER (KIND=JPIM)::NS2D
  INTEGER (KIND=JPIM)::NS1D
  INTEGER (KIND=JPIM), ALLOCATABLE::NGRBSP3 (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NGRBSP2 (:)
  LOGICAL::LVOR
  LOGICAL::LADER
  LOGICAL::LUVDER
  LOGICAL::LSPT
  
ENDTYPE TDIMF

CONTAINS

ENDMODULE YOMDIMF
