
MODULE YOMDIM
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TDIM
  INTEGER (KIND=JPIM)::NDGLG
  INTEGER (KIND=JPIM)::NDGLL
  INTEGER (KIND=JPIM)::NDGNH
  INTEGER (KIND=JPIM)::NDGSUR
  INTEGER (KIND=JPIM)::NDGSAG
  INTEGER (KIND=JPIM)::NDGSAL
  INTEGER (KIND=JPIM)::NDGSAH
  INTEGER (KIND=JPIM)::NDGSAFPH
  INTEGER (KIND=JPIM)::NDGENG
  INTEGER (KIND=JPIM)::NDGENL
  INTEGER (KIND=JPIM)::NDGENH
  INTEGER (KIND=JPIM)::NDGENFPH
  INTEGER (KIND=JPIM)::NDGUNG
  INTEGER (KIND=JPIM)::NDGUXG
  INTEGER (KIND=JPIM)::NDGUNL
  INTEGER (KIND=JPIM)::NDGUXL
  INTEGER (KIND=JPIM)::NDLON
  INTEGER (KIND=JPIM)::NDSUR1
  INTEGER (KIND=JPIM)::NSTENCILWIDE
  INTEGER (KIND=JPIM)::NDLSUR
  INTEGER (KIND=JPIM)::NDLSM
  INTEGER (KIND=JPIM)::NDLUNG
  INTEGER (KIND=JPIM)::NDLUXG
  INTEGER (KIND=JPIM), ALLOCATABLE::NDLUNL (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NDLUXL (:,:)
  INTEGER (KIND=JPIM)::NPROMA
  INTEGER (KIND=JPIM)::NPROMM
  INTEGER (KIND=JPIM)::NPROMM9
  INTEGER (KIND=JPIM)::NPROMNH
  INTEGER (KIND=JPIM)::NGPBLKS
  LOGICAL::LOPTPROMA
  INTEGER (KIND=JPIM)::NRESOL
  INTEGER (KIND=JPIM)::NSMAX
  INTEGER (KIND=JPIM)::NMSMAX
  INTEGER (KIND=JPIM)::NVARMAX
  INTEGER (KIND=JPIM)::NSEFRE
  INTEGER (KIND=JPIM)::NSPECG
  INTEGER (KIND=JPIM)::NSPEC2G
  INTEGER (KIND=JPIM)::NSPEC
  INTEGER (KIND=JPIM)::NSPEC2
  INTEGER (KIND=JPIM)::NSPEC2MX
  INTEGER (KIND=JPIM)::NCMAX
  INTEGER (KIND=JPIM)::NUMP
  INTEGER (KIND=JPIM)::NUMCP
ENDTYPE TDIM

ENDMODULE YOMDIM
