MODULE YOMDPRECIPS
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TDPRECIPS
  REAL (KIND=JPRB)::HDCLWC
  REAL (KIND=JPRB)::RDHAIL1
  REAL (KIND=JPRB)::RDHAIL2
  REAL (KIND=JPRB)::RDSEUIL1
  REAL (KIND=JPRB)::RDSEUIL2
  REAL (KIND=JPRB)::RDSEUIL3
  REAL (KIND=JPRB)::RDSEUIL4
  REAL (KIND=JPRB)::RDSEUIL5
  REAL (KIND=JPRB)::RDCLWC
  REAL (KIND=JPRB)::RPRECSEUIL
  REAL (KIND=JPRB)::RHTOP
  REAL (KIND=JPRB)::RTPW
  REAL (KIND=JPRB)::RAWARM
  REAL (KIND=JPRB)::RAWARM2
  REAL (KIND=JPRB)::RACOLD
  REAL (KIND=JPRB)::RACOLD2
  INTEGER (KIND=JPIM)::NDTPREC=0
  INTEGER (KIND=JPIM)::NDTPREC2=0
ENDTYPE TDPRECIPS

ENDMODULE YOMDPRECIPS
