
MODULE YOMDIMV
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TDIMV
  INTEGER (KIND=JPIM)::NFLEVG
  INTEGER (KIND=JPIM)::NFLEVL
  INTEGER (KIND=JPIM)::NFLEVLMX
  INTEGER (KIND=JPIM)::NFLSUR
  INTEGER (KIND=JPIM)::NFLSUL
  INTEGER (KIND=JPIM)::NFLSA
  INTEGER (KIND=JPIM)::NFLEN
  INTEGER (KIND=JPIM)::NIOLEVG
ENDTYPE TDIMV

ENDMODULE YOMDIMV
