
MODULE YOMDYNCORE
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
LOGICAL::LAQUA, LAPE
LOGICAL::LHELDSUAREZ
LOGICAL::LPPSTEPS
REAL (KIND=JPRB)::RPLRADI, RUSPLRADI
REAL (KIND=JPRB)::RCORIOI, RUSCORIOI
REAL (KIND=JPRB)::RPLRG, RUSPLRG
REAL (KIND=JPRB)::RPLDARE
CHARACTER (LEN=12)::CTEST_FAMILY
INTEGER (KIND=JPIM)::NTESTCASE
REAL (KIND=JPRB)::RAMP
INTEGER (KIND=JPIM)::NOISEVOR
INTEGER (KIND=JPIM)::MSSTSCHEME
REAL (KIND=JPRB)::RCHI
REAL (KIND=JPRB)::RLAMBDA0
REAL (KIND=JPRB)::RLAMBDAD
REAL (KIND=JPRB)::RPHID
REAL (KIND=JPRB)::RT00_DYN
REAL (KIND=JPRB)::RP00_DYN
REAL (KIND=JPRB)::RU00_DYN
REAL (KIND=JPRB)::RST0_DYN
REAL (KIND=JPRB)::RSIGMAB
REAL (KIND=JPRB)::REFERENCE_LEVEL
REAL (KIND=JPRB)::RDELTA_T
REAL (KIND=JPRB)::RDELTA_THETA
REAL (KIND=JPRB)::RPRESSURE_SCALE
REAL (KIND=JPRB)::RHS_KF
REAL (KIND=JPRB)::RHS_KA
REAL (KIND=JPRB)::RHS_KS
REAL (KIND=JPRB)::RHS_KS_KA
REAL (KIND=JPRB)::RHS_KAPPA
LOGICAL::L_HS_WILLIAMSON=.FALSE.
REAL (KIND=JPRB), PARAMETER::RGAMMA_D=2.E-3_JPRB
REAL (KIND=JPRB), PARAMETER::RGAMMA_I=-3.345E-3_JPRB
REAL (KIND=JPRB)::RTHSW_0
REAL (KIND=JPRB)::RPHSW_D
REAL (KIND=JPRB)::RPHSW_EQ
REAL (KIND=JPRB)::RPHSW_PL
REAL (KIND=JPRB)::RPHSW_EQ_PL_HALF
REAL (KIND=JPRB)::RPHSW_D_REV
REAL (KIND=JPRB), PARAMETER::RSAMPLING_START=0.0_JPRB
REAL (KIND=JPRB), PARAMETER::RSAMPLING_INTERVAL=12._JPRB*3600._JPRB
REAL (KIND=JPRB)::RJACSLDIA
REAL (KIND=JPRB)::RLIPSLDIA
ENDMODULE YOMDYNCORE
