MODULE YOMDPHY
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TDPHY
  INTEGER (KIND=JPIM)::NCSS
  INTEGER (KIND=JPIM)::NVXP
  INTEGER (KIND=JPIM)::NVXP2
  INTEGER (KIND=JPIM)::NCXP
  INTEGER (KIND=JPIM)::NCSI
  INTEGER (KIND=JPIM)::NCOM
  INTEGER (KIND=JPIM)::NCSNEC
  INTEGER (KIND=JPIM)::NTILES
  INTEGER (KIND=JPIM)::NVEXTR
  INTEGER (KIND=JPIM)::NVEXTRDI
  INTEGER (KIND=JPIM)::NVEXTRRAD
  INTEGER (KIND=JPIM)::NVEXTRDYN
  INTEGER (KIND=JPIM)::NVXTR2
  INTEGER (KIND=JPIM)::NVECOUT
  INTEGER (KIND=JPIM)::NCEXTR
  INTEGER (KIND=JPIM)::NVCLIS
  INTEGER (KIND=JPIM)::NTOZ1D
  INTEGER (KIND=JPIM)::NTOZ2D
  INTEGER (KIND=JPIM)::NTOZ3D
  INTEGER (KIND=JPIM)::NTSSG
  LOGICAL::LTPROF
  LOGICAL::LDIRCLSMOD
  LOGICAL::LDIRSICMOD
  
ENDTYPE TDPHY

TYPE (TDPHY), POINTER::YRDPHY=>NULL ()
CONTAINS

ENDMODULE YOMDPHY
