MODULE YOMDYNA
USE PARKIND1,ONLY:JPIM, JPRB
USE INTDYN_MOD,ONLY:TTND, TGMVT, TGFLT

IMPLICIT NONE

SAVE

TYPE TDYNA
  LOGICAL::LNHEE
  LOGICAL::LNHQE
  LOGICAL::LNHHY
  LOGICAL::LNHDYN
  LOGICAL::LSACC
  LOGICAL::LSPRT
  LOGICAL::LTWOTL
  LOGICAL::LSLAG
  INTEGER (KIND=JPIM)::NPDVAR
  INTEGER (KIND=JPIM)::NVDVAR
  INTEGER (KIND=JPIM)::NTPVAR
  INTEGER (KIND=JPIM)::ND4SYS
  LOGICAL::LNHX
  LOGICAL::LSPNHX
  LOGICAL::LNHXDER
  LOGICAL::LGWADV
  INTEGER (KIND=JPIM)::NGWADVSI
  LOGICAL::LRDBBC
  LOGICAL::LSI_NHEE
  LOGICAL::LSLHD
  LOGICAL::LSLHD_W
  LOGICAL::LSLHD_T
  LOGICAL::LSLHD_SPD
  LOGICAL::LSLHD_SVD
  LOGICAL::LSLHD_GFL
  LOGICAL::LSLHD_OLD
  LOGICAL::LSLHD_STATIC
  LOGICAL::LSLHDQUAD
  REAL (KIND=JPRB)::SLHDKMIN
  REAL (KIND=JPRB)::SLHDKMAX
  REAL (KIND=JPRB)::SLHDKREF
  REAL (KIND=JPRB)::SLHDEPSH
  REAL (KIND=JPRB)::SLHDEPSV
  LOGICAL::LSLVF
  REAL (KIND=JPRB)::SLVFEPS
  REAL (KIND=JPRB)::P_SLVF_BOT
  REAL (KIND=JPRB)::SLVFMIN
  REAL (KIND=JPRB)::SLVFTR
  REAL (KIND=JPRB)::P_SLVF_TR
  LOGICAL::LGRADSP
  LOGICAL::LPGFSF
  LOGICAL::LPGREUSE
  LOGICAL::LPGFTEST
  LOGICAL::L3DTURB
  LOGICAL::LSLDIA
  LOGICAL::LRPRSLTRJ
  INTEGER (KIND=JPIM)::NQMGMV, NQMGFL
  LOGICAL::LRALTVDISP
  LOGICAL::LVSPLIP
  LOGICAL::LRHSVWENO
  LOGICAL::LCOMAD
  LOGICAL::LCOMADH
  LOGICAL::LCOMADV
  LOGICAL::LCOMAD_W
  LOGICAL::LCOMAD_T
  LOGICAL::LCOMAD_SPD
  LOGICAL::LCOMAD_SVD
  LOGICAL::LCOMAD_SP
  LOGICAL::LCOMAD_GFL
  LOGICAL::LNESCT
  LOGICAL::LNESCV
  LOGICAL::LNESC
  LOGICAL::LSETTLST
  LOGICAL::LSETTLSV
  LOGICAL::LSETTLS
  LOGICAL::LELTRA
  LOGICAL::LSLINLC2
  LOGICAL::LSLINL
  LOGICAL::LHOISLT
  REAL (KIND=JPRB)::HOISLTV
  REAL (KIND=JPRB)::HOISLTH
  LOGICAL::LSLTVWENO
  LOGICAL::LRUBC
  LOGICAL::LBIGW
  LOGICAL::LPC_FULL
  LOGICAL::LPC_CHEAP
  LOGICAL::LPC_CHEAP2
  LOGICAL::LPC_SPHY
  LOGICAL::LMIXETTLS
  LOGICAL::LMIXETTLS_PRINT
  REAL (KIND=JPRB)::RMIXNL_TRH
  LOGICAL::LSI_UPDATE_FULL
  LOGICAL::LSI_UPDATE_CHEAP
  LOGICAL::L_RDRY_VD
  LOGICAL::L_RDRY_NHX
  LOGICAL::LHYQE_BLEND
  REAL (KIND=JPRB)::TSTART_BLEND
  REAL (KIND=JPRB)::TSTOP_BLEND
  LOGICAL::LNHQE_BALANCE
  LOGICAL::LNHQE_LASTSI
  LOGICAL::LNHQE_CSVTRMO
  REAL (KIND=JPRB)::RNHQE_DELTA
  LOGICAL::LNHHY_VERTIC
  LOGICAL::LNHHY_BALANCE
  REAL (KIND=JPRB)::RNHHY_DELTA
  REAL (KIND=JPRB)::RNHHY_TAUD, RNHHY_TAUX
  TYPE (TTND)::YYTTND
  TYPE (TGMVT)::YYTGMVT95
  TYPE (TGFLT)::YYTGFLT95
ENDTYPE TDYNA

ENDMODULE YOMDYNA
