
MODULE YOMEDMF
USE PARKIND1,ONLY:JPIM, JPRB
USE PARPHY,ONLY:RKAP
USE YOMCST,ONLY:TCST

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER::IDIM=40

TYPE TEDMF
  REAL (KIND=JPRB), DIMENSION (IDIM)::ZA
  REAL (KIND=JPRB), DIMENSION (IDIM)::ZBAR
  REAL (KIND=JPRB), DIMENSION (IDIM)::ZX
  REAL (KIND=JPRB), DIMENSION (IDIM)::ZQLFAC
  REAL (KIND=JPRB)::ZWL
  REAL (KIND=JPRB)::ZWT
  REAL (KIND=JPRB)::ZEL
  REAL (KIND=JPRB)::ZET
  REAL (KIND=JPRB)::ZW2THRESH
  REAL (KIND=JPRB)::ZMFDRYCON
  REAL (KIND=JPRB)::ZMBCLOSURECON
  REAL (KIND=JPRB)::ZRG
  REAL (KIND=JPRB)::ZLAT2CP
  REAL (KIND=JPRB)::ZEL2R
  REAL (KIND=JPRB)::ZEI2R
  REAL (KIND=JPRB)::ZCONS13
  REAL (KIND=JPRB)::ZEPS
  REAL (KIND=JPRB)::ZC_0
  REAL (KIND=JPRB)::ZC_D
  REAL (KIND=JPRB)::ZC_N
  REAL (KIND=JPRB)::ZWSTF
  REAL (KIND=JPRB)::ZTKEMIN
  REAL (KIND=JPRB)::ZPRANDT
  REAL (KIND=JPRB)::ZI2
  REAL (KIND=JPRB)::ZALPHA_N
  REAL (KIND=JPRB)::ZALPHA_C
  REAL (KIND=JPRB)::ZB
  REAL (KIND=JPRB)::ZC_M_MAX
  REAL (KIND=JPRB)::ZREPUST
  
  
ENDTYPE TEDMF

CONTAINS

ENDMODULE YOMEDMF
