MODULE YOMGPAR
USE FIELD_MODULE
USE FIELD_ARRAY_MODULE
USE FIELD_REGISTRY_MOD
USE PARKIND1,ONLY:JPRB, JPIM, JPIB

IMPLICIT NONE


TYPE TGPAR
  LOGICAL::LOWNED=.FALSE.
  CLASS (FIELD_3RB), POINTER::F_DATA=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::ZDATA (:,:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::INPRR (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_INPRR=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::INPRS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_INPRS=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::INPRG (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_INPRG=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::ACPRR (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_ACPRR=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::ACPRS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_ACPRS=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::ACPRG (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_ACPRG=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::ALBDIR (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_ALBDIR=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::ALBSCA (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_ALBSCA=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::RAIN (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RAIN=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::SNOW (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SNOW=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GZ0 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GZ0=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GZ0H (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GZ0H=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::VQS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VQS=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::VTS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VTS=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::VEMIS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VEMIS=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::SWDIR (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_SWDIR=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::SWDIF (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_SWDIF=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::LSM (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_LSM=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::CD (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_CD=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::CH (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_CH=>NULL ()
  
  
  
  
  
  
  
ENDTYPE TGPAR

REAL (KIND=JPRB), PRIVATE, SAVE, TARGET::ZDUM1 (1), ZDUM2 (1, 1), ZDUM3 (1, 1, 1)
CONTAINS






ENDMODULE
