MODULE YOMGEM
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TGEM
  INTEGER (KIND=JPIM)::NGPTOT
  INTEGER (KIND=JPIM)::NGPTOT_CAP
  INTEGER (KIND=JPIM)::NGPTOTMX
  INTEGER (KIND=JPIM)::NGPTOTG
  INTEGER (KIND=JPIM), ALLOCATABLE::NGPTOTL (:,:)
  REAL (KIND=JPRB)::RDELXN
  REAL (KIND=JPRB)::SLHDP
  REAL (KIND=JPRB)::RMUCEN
  REAL (KIND=JPRB)::RLOCEN
  REAL (KIND=JPRB)::RSTRET
  INTEGER (KIND=JPIM)::NSTTYP
  INTEGER (KIND=JPIM)::NHTYP
  REAL (KIND=JPRB)::RNLGINC
  REAL (KIND=JPRB)::R4JP
  REAL (KIND=JPRB)::RC2P1
  REAL (KIND=JPRB)::RC2M1
  REAL (KIND=JPRB)::RCOR0
  REAL (KIND=JPRB)::RCOR1
  INTEGER (KIND=JPIM), ALLOCATABLE::NLOEN (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NLOENG (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NMEN (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NMENG (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NDGLU (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSTAGP (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NTSTAGP (:)
ENDTYPE TGEM

ENDMODULE YOMGEM
