MODULE YOMGFL
USE PARKIND1,ONLY:JPRB, JPIM
USE YOM_YGFL,ONLY:TYPE_GFLD

IMPLICIT NONE

SAVE

TYPE::TGFL
  REAL (KIND=JPRB), ALLOCATABLE::GFL (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GFLT1 (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GFLSLP (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GFLPT (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GFLPC (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GFL5 (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GFLSLP5 (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GFL_DEPART (:,:,:,:)
  TYPE (TYPE_GFLD), POINTER::YGFL=>NULL ()
  LOGICAL::LGFLT1_INIT=.FALSE.
ENDTYPE TGFL

REAL (KIND=JPRB), ALLOCATABLE::GFL_LHN (:)
#include "abor1.intfb.h"
CONTAINS







ENDMODULE YOMGFL
