MODULE YOMGEOMVARS
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE FIELD_MODULE

IMPLICIT NONE


TYPE TGEOMVARS
  CLASS (FIELD_2RB), POINTER::F_RCORI=>NULL ()
  REAL (KIND=JPRB), POINTER::RCORI (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RCORIC=>NULL ()
  REAL (KIND=JPRB), POINTER::RCORIC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GEMU=>NULL ()
  REAL (KIND=JPRB), POINTER::GEMU (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GSQM2=>NULL ()
  REAL (KIND=JPRB), POINTER::GSQM2 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GELAM=>NULL ()
  REAL (KIND=JPRB), POINTER::GELAM (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GELAT=>NULL ()
  REAL (KIND=JPRB), POINTER::GELAT (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GECLO=>NULL ()
  REAL (KIND=JPRB), POINTER::GECLO (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GESLO=>NULL ()
  REAL (KIND=JPRB), POINTER::GESLO (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GM=>NULL ()
  REAL (KIND=JPRB), POINTER::GM (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GMAPPA=>NULL ()
  REAL (KIND=JPRB), POINTER::GMAPPA (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GOMVRL=>NULL ()
  REAL (KIND=JPRB), POINTER::GOMVRL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GOMVRM=>NULL ()
  REAL (KIND=JPRB), POINTER::GOMVRM (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GNORDL=>NULL ()
  REAL (KIND=JPRB), POINTER::GNORDL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GNORDM=>NULL ()
  REAL (KIND=JPRB), POINTER::GNORDM (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GNORDLCL=>NULL ()
  REAL (KIND=JPRB), POINTER::GNORDLCL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GNORDMCL=>NULL ()
  REAL (KIND=JPRB), POINTER::GNORDMCL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GNORDMCM=>NULL ()
  REAL (KIND=JPRB), POINTER::GNORDMCM (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GAW=>NULL ()
  REAL (KIND=JPRB), POINTER::GAW (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GEXCO=>NULL ()
  REAL (KIND=JPRB), POINTER::GEXCO (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GEYCO=>NULL ()
  REAL (KIND=JPRB), POINTER::GEYCO (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GEZCO=>NULL ()
  REAL (KIND=JPRB), POINTER::GEZCO (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_OROG=>NULL ()
  REAL (KIND=JPRB), POINTER::OROG (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_OROGL=>NULL ()
  REAL (KIND=JPRB), POINTER::OROGL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_OROGM=>NULL ()
  REAL (KIND=JPRB), POINTER::OROGM (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_OROGLL=>NULL ()
  REAL (KIND=JPRB), POINTER::OROGLL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_OROGMM=>NULL ()
  REAL (KIND=JPRB), POINTER::OROGMM (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_OROGLM=>NULL ()
  REAL (KIND=JPRB), POINTER::OROGLM (:)=>NULL ()
  CLASS (FIELD_2RD), POINTER::F_RCOLON=>NULL ()
  REAL (KIND=JPRD), POINTER::RCOLON (:)=>NULL ()
  CLASS (FIELD_2RD), POINTER::F_RSILON=>NULL ()
  REAL (KIND=JPRD), POINTER::RSILON (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RINDX=>NULL ()
  REAL (KIND=JPRB), POINTER::RINDX (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RINDY=>NULL ()
  REAL (KIND=JPRB), POINTER::RINDY (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RATATH=>NULL ()
  REAL (KIND=JPRB), POINTER::RATATH (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RATATX=>NULL ()
  REAL (KIND=JPRB), POINTER::RATATX (:)=>NULL ()
  
  
  
  
ENDTYPE TGEOMVARS



CONTAINS



ENDMODULE YOMGEOMVARS
