MODULE YOMGMV
USE PARKIND1,ONLY:JPIM, JPRB
USE TYPE_GMVS,ONLY:TYPE_T0, TYPE_T9, TYPE_T1, TYPE_PH9, TYPE_GP
USE YOMLUN,ONLY:NULERR

IMPLICIT NONE

SAVE

TYPE::TGMV
  REAL (KIND=JPRB), ALLOCATABLE::GMV (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GMVS (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GMVT1 (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GMVT1S (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GMV5 (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GMV5S (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GMV_DEPART (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GMVS_DEPART (:,:,:)
  INTEGER (KIND=JPIM)::NDIMGMV
  INTEGER (KIND=JPIM)::NDIMGMVS
  TYPE (TYPE_T0)::YT0
  TYPE (TYPE_T9)::YT9
  TYPE (TYPE_T1)::YT1
  TYPE (TYPE_PH9)::YPH9
  TYPE (TYPE_GP)::YGP
  TYPE (TYPE_T0)::YT5
  LOGICAL::LGMVT1_INIT=.FALSE.
  LOGICAL::LGMVT1S_INIT=.FALSE.
ENDTYPE TGMV

#include "abor1.intfb.h"
CONTAINS







ENDMODULE YOMGMV
