MODULE YOMGSGEOM
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE DEALLOCATE_IF_ASSOCIATED_MOD,ONLY:DEALLOCATE_IF_ASSOCIATED

IMPLICIT NONE

SAVE

TYPE TGSGEOM
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::RCORI (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::RCORIC (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GEMU (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GSQM2 (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAM (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAT (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GECLO (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GESLO (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAMDEG (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAMINF (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAMSUP (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GEXCO (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GEYCO (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GEZCO (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GM (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GMAPPA (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GOMVRL (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GOMVRM (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDL (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDM (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDLCL (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDMCL (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDMCM (:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GAW (:)=>NULL ()
  INTEGER (KIND=JPIM), POINTER, CONTIGUOUS::NGPLAT (:)=>NULL ()
  INTEGER (KIND=JPIM), POINTER, CONTIGUOUS::NUNIQUEGP (:)=>NULL ()
  
  
  
ENDTYPE TGSGEOM


TYPE TGSGEOM_BLOCKED
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::RCORI (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::RCORIC (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GEMU (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GSQM2 (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAM (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAT (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GECLO (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GESLO (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAMDEG (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAMINF (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GELAMSUP (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GEXCO (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GEYCO (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GEZCO (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GM (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GMAPPA (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GOMVRL (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GOMVRM (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDL (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDM (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDLCL (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDMCL (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GNORDMCM (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS::GAW (:,:)=>NULL ()
  INTEGER (KIND=JPIM), POINTER, CONTIGUOUS::NGPLAT (:,:)=>NULL ()
  INTEGER (KIND=JPIM), POINTER, CONTIGUOUS::NUNIQUEGP (:,:)=>NULL ()
  
  
  
ENDTYPE TGSGEOM_BLOCKED

CONTAINS







ENDMODULE YOMGSGEOM
