MODULE YOMGRIB
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::JPNUMLPP=5
INTEGER (KIND=JPIM)::NSTEPLPP (JPNUMLPP, 2)
INTEGER (KIND=JPIM), PARAMETER::JPMAXSFLEVS=12
INTEGER (KIND=JPIM)::NSFLEVS (JPMAXSFLEVS, 3)=-1
INTEGER (KIND=JPIM)::NLOCGRB
INTEGER (KIND=JPIM)::NTOTENS
INTEGER (KIND=JPIM)::NENSFNB
INTEGER (KIND=JPIM)::NWINOFF
INTEGER (KIND=JPIM)::NWINOFF_4V
INTEGER (KIND=JPIM)::NSTREAM
INTEGER (KIND=JPIM)::NSYSTEM
INTEGER (KIND=JPIM)::NMETHOD
INTEGER (KIND=JPIM)::NREFERENCE
INTEGER (KIND=JPIM)::NCONSENSUS
INTEGER (KIND=JPIM)::NDWD
INTEGER (KIND=JPIM)::NMFR
INTEGER (KIND=JPIM)::NNCEP
INTEGER (KIND=JPIM)::NUKM
INTEGER (KIND=JPIM)::NBITSSH
INTEGER (KIND=JPIM)::NJDIAG
INTEGER (KIND=JPIM)::NJDOMAI
INTEGER (KIND=JPIM)::NJITER
INTEGER (KIND=JPIM)::NLEG
INTEGER (KIND=JPIM)::NCYCLE=-100
CHARACTER (LEN=2)::CFCLASS
CHARACTER (LEN=2)::CTYPE
INTEGER (KIND=JPIM)::NBITSSHLNSP
INTEGER (KIND=JPIM)::NBITSEXPR
ENDMODULE YOMGRIB
