MODULE YOMHSLMER
USE PARKIND1,ONLY:JPRB, JPRD

IMPLICIT NONE

SAVE

TYPE THSLMER
  REAL (KIND=JPRD), ALLOCATABLE::RIPI (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RSLD (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RSLDW (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::R3DTW (:,:,:)
ENDTYPE THSLMER

ENDMODULE YOMHSLMER
