MODULE YOMJBECV
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TECV_CONFIG
  CHARACTER (LEN=1)::CFNECVINC='E'
  CHARACTER (LEN=5)::CFNECVFG='ICEGG'
  CHARACTER (LEN=16)::CFNECVHR='TRAJHR00/ecvgrid'
  CHARACTER (LEN=11)::CFNECV4V='ecv4v_ggml_'
ENDTYPE TECV_CONFIG


TYPE TECV_DATA
  CHARACTER (LEN=20), ALLOCATABLE::CSETDESC (:)
  CHARACTER (LEN=40), ALLOCATABLE::CECV_STD_STRINGS (:)
  CHARACTER (LEN=40), ALLOCATABLE::CECV_COR_STRINGS (:)
  INTEGER (KIND=JPIM)::NECV
  INTEGER (KIND=JPIM)::NECV_1D
  INTEGER (KIND=JPIM)::NECV_2D
  INTEGER (KIND=JPIM)::NECV_3D
  INTEGER (KIND=JPIM)::NVIDS_ECV=0
  INTEGER (KIND=JPIM)::NVIDS_ECV_TOTFLDS=0
  INTEGER (KIND=JPIM), ALLOCATABLE::MGRIBS_ECV_FIDS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NFLDS_VIDS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::VIDS_ECV (:)
  LOGICAL, ALLOCATABLE::LECV_1D (:)
  LOGICAL, ALLOCATABLE::LECV_2D (:)
  LOGICAL, ALLOCATABLE::LECV_3D (:)
ENDTYPE TECV_DATA

LOGICAL::LECPHYSPARECV
LOGICAL::LINVERACV
LOGICAL::LJB_ALPHA_CV
LOGICAL::LSKTECV
LOGICAL::LSSHECV
LOGICAL::LTSLECV
INTEGER (KIND=JPIM)::NDIAECV
INTEGER (KIND=JPIM)::NINTERPTRAJ_ECV
INTEGER (KIND=JPIM)::NINTERPINCR_ECV
REAL (KIND=JPRB)::WINDOW_LENGTH=-1.0
TYPE (TECV_DATA)::YRECVDATA
TYPE (TECV_CONFIG)::YRECVCONFIG
CHARACTER (LEN=20), PARAMETER::CKNOWNECV (5)=(/'SOLAR_CONSTANT      ','SKTECV      &
&        ','JB_HYBRID_ALPHACV   ','FLUX_INVER          ','EC_PHYS             '/)
ENDMODULE YOMJBECV
