MODULE YOMLAP
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TLAP
  INTEGER (KIND=JPIM), ALLOCATABLE::NASN0 (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NASM0 (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NASM0G (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NVALUE (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MVALUE (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MYMS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSPZERO (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSE0L (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLAPDI (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLAPIN (:)
ENDTYPE TLAP

ENDMODULE YOMLAP
