MODULE YOMLEG
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE TCSGLEG
  REAL (KIND=JPRB), ALLOCATABLE::RW (:)
  REAL (KIND=JPRB), ALLOCATABLE::RMU (:)
  REAL (KIND=JPRB), ALLOCATABLE::R1MU2 (:)
  REAL (KIND=JPRB), ALLOCATABLE::R1MUI (:)
  REAL (KIND=JPRB), ALLOCATABLE::R1MUA (:)
  REAL (KIND=JPRB), ALLOCATABLE::RSQM2 (:)
  REAL (KIND=JPRB), ALLOCATABLE::R1QM2 (:)
  REAL (KIND=JPRB), ALLOCATABLE::RACTHE (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLATIG (:)
  REAL (KIND=JPRB), ALLOCATABLE::RLATI (:)
ENDTYPE TCSGLEG

ENDMODULE YOMLEG
