
MODULE YOMLUN
USE PARKIND1,ONLY:JPIM
USE YOMLUN_IFSAUX,ONLY:NULOUT, NULERR

IMPLICIT NONE

SAVE


INTEGER (KIND=JPIM), PARAMETER::NULSTAT=1
INTEGER (KIND=JPIM), PARAMETER::NULNAM=4
INTEGER (KIND=JPIM), PARAMETER::NULFP11=7
INTEGER (KIND=JPIM), PARAMETER::NSCRTCH=8
INTEGER (KIND=JPIM), PARAMETER::NULFP10=9
INTEGER (KIND=JPIM), PARAMETER::NULCL1=10
INTEGER (KIND=JPIM), PARAMETER::NULCL2=11
INTEGER (KIND=JPIM), PARAMETER::NULFP09=12
INTEGER (KIND=JPIM), PARAMETER::NULFP08=13
INTEGER (KIND=JPIM), PARAMETER::NULFP07=14
INTEGER (KIND=JPIM), PARAMETER::NULASE=16
INTEGER (KIND=JPIM), PARAMETER::NULASS=17
INTEGER (KIND=JPIM), PARAMETER::NULFP06=18
INTEGER (KIND=JPIM), PARAMETER::NULFP05=19
INTEGER (KIND=JPIM), PARAMETER::NULRAD=25
INTEGER (KIND=JPIM), PARAMETER::NULRTL=26
INTEGER (KIND=JPIM), PARAMETER::NULFP04=30
INTEGER (KIND=JPIM), PARAMETER::NULFP12=32
INTEGER (KIND=JPIM), PARAMETER::NULFP13=33
INTEGER (KIND=JPIM), PARAMETER::NULFP14=34
INTEGER (KIND=JPIM), PARAMETER::NULFP15=35
INTEGER (KIND=JPIM), PARAMETER::NSCATAB=36
INTEGER (KIND=JPIM), PARAMETER::NSCASIG=37
INTEGER (KIND=JPIM), PARAMETER::NSCASPE=38
INTEGER (KIND=JPIM), PARAMETER::NEGASH=39
INTEGER (KIND=JPIM), PARAMETER::NULFP03=43
INTEGER (KIND=JPIM), PARAMETER::NULDILA=46
INTEGER (KIND=JPIM), PARAMETER::NULCONT=47
INTEGER (KIND=JPIM), PARAMETER::NULFP02=50
INTEGER (KIND=JPIM), PARAMETER::NPOSSH=51
INTEGER (KIND=JPIM), PARAMETER::NPODDH=53
INTEGER (KIND=JPIM), PARAMETER::NULFP01=54
INTEGER (KIND=JPIM), PARAMETER::NULCO=55
INTEGER (KIND=JPIM), PARAMETER::NTIDE=56
INTEGER (KIND=JPIM), PARAMETER::NUIO_SERV_LOG=67
INTEGER (KIND=JPIM), PARAMETER::NTRJSH=71
INTEGER (KIND=JPIM)::NULTRAJHR=72
INTEGER (KIND=JPIM)::NEFLSS=73
INTEGER (KIND=JPIM), PARAMETER::NULFPOS=74
INTEGER (KIND=JPIM), PARAMETER::NEFLS=78
INTEGER (KIND=JPIM), PARAMETER::NINMSH=79
INTEGER (KIND=JPIM), PARAMETER::NINISH=81
INTEGER (KIND=JPIM), PARAMETER::NINIGG=82
INTEGER (KIND=JPIM), PARAMETER::NFGISH=83
INTEGER (KIND=JPIM), PARAMETER::NULTRAJBG=NFGISH
INTEGER (KIND=JPIM), PARAMETER::NPRT0=85
INTEGER (KIND=JPIM), PARAMETER::NPRT1=86
INTEGER (KIND=JPIM), PARAMETER::NPRT2=87
INTEGER (KIND=JPIM), PARAMETER::NPRT3=88
INTEGER (KIND=JPIM), PARAMETER::NPRT4=89
INTEGER (KIND=JPIM), PARAMETER::NBIAS=90
INTEGER (KIND=JPIM), PARAMETER::NPPPSH=91
INTEGER (KIND=JPIM), PARAMETER::NPDIRL=92
INTEGER (KIND=JPIM), PARAMETER::NULHWF=93
INTEGER (KIND=JPIM), PARAMETER::NULRCF=94
INTEGER (KIND=JPIM), PARAMETER::NULUSR1=95
INTEGER (KIND=JPIM), PARAMETER::NULUSR2=96
INTEGER (KIND=JPIM), PARAMETER::NULUSR3=97
INTEGER (KIND=JPIM), PARAMETER::NULUSR4=98
INTEGER (KIND=JPIM), PARAMETER::NULUSR5=99
INTEGER (KIND=JPIM), PARAMETER::NULBDEGP=100
INTEGER (KIND=JPIM), PARAMETER::NULBDESH=200
INTEGER (KIND=JPIM), PARAMETER::JP_RESERVE_FIRST=57
INTEGER (KIND=JPIM), PARAMETER::JP_RESERVE_LAST=70
INTEGER (KIND=JPIM)::I
LOGICAL::LRESERVED (JP_RESERVE_FIRST:JP_RESERVE_LAST)=&
&(/(.FALSE., I=JP_RESERVE_FIRST, JP_RESERVE_LAST)/)
CONTAINS



ENDMODULE YOMLUN
