MODULE YOMLDDH

IMPLICIT NONE

SAVE

TYPE::TLDDH
  LOGICAL::LSDDH=.FALSE.
  LOGICAL::LHDGLB=.FALSE.
  LOGICAL::LHDZON=.FALSE.
  LOGICAL::LHDDOP=.FALSE.
  LOGICAL::LHDLFA=.FALSE.
  LOGICAL::LHDHKS=.FALSE.
  LOGICAL::LHDMCI=.FALSE.
  LOGICAL::LHDENT=.FALSE.
  LOGICAL::LHDPRG=.FALSE.
  LOGICAL::LHDPRZ=.FALSE.
  LOGICAL::LHDPRD=.FALSE.
  LOGICAL::LHDPR=.FALSE.
  LOGICAL::LHDEFG=.FALSE.
  LOGICAL::LHDEFZ=.FALSE.
  LOGICAL::LHDEFD=.FALSE.
  LOGICAL::LHDLIST=.FALSE.
  LOGICAL::LHDOUFG=.FALSE.
  LOGICAL::LHDOUFZ=.FALSE.
  LOGICAL::LHDOUFD=.FALSE.
  LOGICAL::LHDOUP=.FALSE.
  LOGICAL::LHDFIL=.FALSE.
  LOGICAL::LONLYVAR=.FALSE.
  LOGICAL::LHDORIGP=.FALSE.
  LOGICAL::LHDCDPI=.FALSE.
  LOGICAL::LFLEXDIA=.FALSE.
  LOGICAL::LRDDHDYN=.FALSE.
  LOGICAL::LRSLDDH=.FALSE.
  LOGICAL::LRSIDDH=.FALSE.
  LOGICAL::LRHDDDH=.FALSE.
  LOGICAL::LDDH_OMP=.FALSE.
ENDTYPE TLDDH

ENDMODULE YOMLDDH
