
MODULE YOMMP0
USE PARKIND1,ONLY:JPIM, JPRD

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), ALLOCATABLE::NPRCIDS (:)
INTEGER (KIND=JPIM), ALLOCATABLE, TARGET::NGPSET2PE (:,:)
INTEGER (KIND=JPIM)::N_REGIONS_NS
INTEGER (KIND=JPIM)::N_REGIONS_EW
INTEGER (KIND=JPIM), TARGET, ALLOCATABLE::N_REGIONS (:)
LOGICAL::LSPLIT
LOGICAL::LEQ_REGIONS
LOGICAL::LSPLITOUT
LOGICAL::LSYNC_SLCOM
LOGICAL::LSYNC_POSTSLCOM2
LOGICAL::LSYNC_TRANS
LOGICAL::LSLDEBUG
LOGICAL::LSLONDEM
LOGICAL::LSLONDEM_SPLIT
LOGICAL::LGPTOT_CAP
INTEGER (KIND=JPIM)::MP_TYPE
INTEGER (KIND=JPIM)::MBX_SIZE
INTEGER (KIND=JPIM)::MYPROC
INTEGER (KIND=JPIM)::MYSETA
INTEGER (KIND=JPIM)::MYSETB
INTEGER (KIND=JPIM)::MYSETW
INTEGER (KIND=JPIM)::MYSETV
INTEGER (KIND=JPIM)::MYSETM
INTEGER (KIND=JPIM)::MYSETN
INTEGER (KIND=JPIM)::MY_REGION_NS
INTEGER (KIND=JPIM)::MY_REGION_EW
INTEGER (KIND=JPIM)::NFLDIN
INTEGER (KIND=JPIM)::NSLPAD
INTEGER (KIND=JPIM)::NOUTTYPE
INTEGER (KIND=JPIM)::NWRTOUT
INTEGER (KIND=JPIM)::NDISTIO (50)
LOGICAL::LUSEWRGRIDALL
INTEGER (KIND=JPIM)::NCOMBFLEN
LOGICAL::LMPOFF
INTEGER (KIND=JPIM)::NSPECRESMIN
LOGICAL::LOUTPUT
INTEGER (KIND=JPIM)::NOUTPUT
INTEGER (KIND=JPIM)::NPRINTLEV
LOGICAL::LMPDIAG
LOGICAL::LOPT_SCALAR
LOGICAL::LVECADIN
LOGICAL::LOPT_RS6K
LOGICAL::LSCMEC
INTEGER (KIND=JPIM)::NTRANS_SYNC_LEVEL=0
INTEGER (KIND=JPIM)::NPROC
INTEGER (KIND=JPIM)::NPRGPNS
INTEGER (KIND=JPIM)::NPRGPEW
INTEGER (KIND=JPIM)::NPRTRNS
INTEGER (KIND=JPIM)::NPRTRN
INTEGER (KIND=JPIM)::NPRTRW
INTEGER (KIND=JPIM)::NPRTRV
INTEGER (KIND=JPIM)::NSTRIN
INTEGER (KIND=JPIM)::NSTROUT
REAL (KIND=JPRD)::SLOWRANKS_DELAY
REAL (KIND=JPRD)::SLOWRANKS_FACTOR
LOGICAL::LSLCOMM3=.FALSE.
LOGICAL::LSLEXTPOL3=.FALSE.
ENDMODULE YOMMP0
