MODULE YOMMODERRMOD
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TMODERR
  LOGICAL::LSCALERR=.FALSE.
  LOGICAL::LTAPERERR=.FALSE.
  INTEGER (KIND=JPIM)::NTYPE_MODERR=0
  INTEGER (KIND=JPIM)::NSTEP_MODERR=0
  INTEGER (KIND=JPIM)::NORDER_MODERR=0
  INTEGER (KIND=JPIM)::NPRTMODERR=0
  INTEGER (KIND=JPIM)::TAPERERR_INI=0
  INTEGER (KIND=JPIM)::TAPERERR_END=0
  REAL (KIND=JPRB)::TSTEP_ERR=0.0
  INTEGER (KIND=JPIM), ALLOCATABLE::MSTEPERR (:)
  REAL (KIND=JPRB), ALLOCATABLE::TSTEPERR (:)
  REAL (KIND=JPRB), ALLOCATABLE::FSTEPERR (:,:)
  
ENDTYPE TMODERR

CONTAINS

ENDMODULE YOMMODERRMOD
