MODULE YOMMDDH
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::JPDHNOX=10000
INTEGER (KIND=JPIM), PARAMETER::JPDHXPU=5

TYPE::TMDDH
  INTEGER (KIND=JPIM)::NDHKD
  INTEGER (KIND=JPIM)::NDHNPU
  INTEGER (KIND=JPIM)::NDHBPU (JPDHXPU)
  INTEGER (KIND=JPIM)::NDHBPX
  INTEGER (KIND=JPIM)::NDHNOM
  INTEGER (KIND=JPIM)::NDHDDX
  INTEGER (KIND=JPIM)::NDHIDH
  INTEGER (KIND=JPIM)::NDHCS
  INTEGER (KIND=JPIM)::NDHCV
  INTEGER (KIND=JPIM)::NDHCVSU
  INTEGER (KIND=JPIM)::NDHCSSU
  INTEGER (KIND=JPIM)::NDHCVSUN
  INTEGER (KIND=JPIM)::NDHCVSUL
  INTEGER (KIND=JPIM)::NDHVV
  INTEGER (KIND=JPIM)::NDHFVD
  INTEGER (KIND=JPIM)::NDHFVP
  INTEGER (KIND=JPIM)::NDHVS
  INTEGER (KIND=JPIM)::NDHFSD
  INTEGER (KIND=JPIM)::NDHFSP
  INTEGER (KIND=JPIM)::NDHFFS
  INTEGER (KIND=JPIM)::NDHVFS
  INTEGER (KIND=JPIM)::NFSVAR_AERO
  INTEGER (KIND=JPIM)::NFSFLX_AERO
  INTEGER (KIND=JPIM)::NDHVTLS
  INTEGER (KIND=JPIM)::NDHFTLS
  INTEGER (KIND=JPIM)::NDHVTSS
  INTEGER (KIND=JPIM)::NDHFTSS
  INTEGER (KIND=JPIM)::NDHVTTS
  INTEGER (KIND=JPIM)::NDHFTTS
  INTEGER (KIND=JPIM)::NDHVTIS
  INTEGER (KIND=JPIM)::NDHFTIS
  INTEGER (KIND=JPIM)::NDHVSSS
  INTEGER (KIND=JPIM)::NDHFSSS
  INTEGER (KIND=JPIM)::NDHVIIS
  INTEGER (KIND=JPIM)::NDHFIIS
  INTEGER (KIND=JPIM)::NDHVWLS
  INTEGER (KIND=JPIM)::NDHFWLS
  INTEGER (KIND=JPIM)::NDHTHK
  INTEGER (KIND=JPIM)::NDHVHK
  INTEGER (KIND=JPIM)::NDHFHKD
  INTEGER (KIND=JPIM)::NDHFHKP
  INTEGER (KIND=JPIM)::NDHTMC
  INTEGER (KIND=JPIM)::NDHVMC
  INTEGER (KIND=JPIM)::NDHFMCD
  INTEGER (KIND=JPIM)::NDHFMCP
  INTEGER (KIND=JPIM)::NDHTEN
  INTEGER (KIND=JPIM)::NDHVEN
  INTEGER (KIND=JPIM)::NDHFEND
  INTEGER (KIND=JPIM)::NDHFENP
  INTEGER (KIND=JPIM)::NDHAVD
  INTEGER (KIND=JPIM)::NDHBVD
  INTEGER (KIND=JPIM)::NDHAVP
  INTEGER (KIND=JPIM)::NDHBVP
  INTEGER (KIND=JPIM)::NDHAHKD
  INTEGER (KIND=JPIM)::NDHBHKD
  INTEGER (KIND=JPIM)::NDHAHKP
  INTEGER (KIND=JPIM)::NDHBHKP
  INTEGER (KIND=JPIM)::NDHAMCD
  INTEGER (KIND=JPIM)::NDHBMCD
  INTEGER (KIND=JPIM)::NDHAMCP
  INTEGER (KIND=JPIM)::NDHBMCP
  INTEGER (KIND=JPIM)::NDHAEND
  INTEGER (KIND=JPIM)::NDHBEND
  INTEGER (KIND=JPIM)::NDHAENP
  INTEGER (KIND=JPIM)::NDHBENP
  INTEGER (KIND=JPIM)::NDHZPR
  REAL (KIND=JPRB)::FNODDH (11, JPDHNOX)
  REAL (KIND=JPRB)::BDEDDH (10, JPDHNOX)
  REAL (KIND=JPRB)::HDSFGL
  INTEGER (KIND=JPIM), ALLOCATABLE::NDDHLA (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NDDHPU (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NDDHI (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NLRDDH (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NURDDH (:,:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NLXDDH (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NUXDDH (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::HDSFLA (:)
  REAL (KIND=JPRB), ALLOCATABLE::HDSFDU (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::HDSF (:)
  INTEGER (KIND=JPIM)::NDIMHDGFL
  INTEGER (KIND=JPIM)::NDIMSIGMV
  INTEGER (KIND=JPIM)::MSIDDH_U1
  INTEGER (KIND=JPIM)::MSIDDH_V1
  INTEGER (KIND=JPIM)::MSIDDH_T1
  INTEGER (KIND=JPIM)::MSIDDH_PD1
  INTEGER (KIND=JPIM)::MSIDDH_VD1
  INTEGER (KIND=JPIM)::MSIDDH_U0
  INTEGER (KIND=JPIM)::MSIDDH_V0
  INTEGER (KIND=JPIM)::MSIDDH_T0
  INTEGER (KIND=JPIM)::MSIDDH_PD0
  INTEGER (KIND=JPIM)::MSIDDH_VD0
  INTEGER (KIND=JPIM)::MSIDDH_U9
  INTEGER (KIND=JPIM)::MSIDDH_V9
  INTEGER (KIND=JPIM)::MSIDDH_T9
  INTEGER (KIND=JPIM)::MSIDDH_PD9
  INTEGER (KIND=JPIM)::MSIDDH_VD9
  INTEGER (KIND=JPIM)::MHDDDH_U
  INTEGER (KIND=JPIM)::MHDDDH_V
  INTEGER (KIND=JPIM)::MHDDDH_T
  INTEGER (KIND=JPIM)::MHDDDH_Q
  INTEGER (KIND=JPIM)::MHDDDH_PD
  INTEGER (KIND=JPIM)::MHDDDH_VD
  INTEGER (KIND=JPIM)::MHDDDH_NHX
  INTEGER (KIND=JPIM)::MSLDDH_U
  INTEGER (KIND=JPIM)::MSLDDH_V
  INTEGER (KIND=JPIM)::MSLDDH_T
  INTEGER (KIND=JPIM)::MSLDDH_PD
  INTEGER (KIND=JPIM)::MSLDDH_VD
  INTEGER (KIND=JPIM)::MSLDDH_NHX
  CHARACTER (LEN=200)::CFPATHDDH
  INTEGER (KIND=JPIM)::NFIELDS3D_AUTO
  INTEGER (KIND=JPIM)::NFIELDS3D_OFFSET
  INTEGER (KIND=JPIM)::NFIELDSMAX
  INTEGER (KIND=JPIM)::NFIELDS2D_AUTO
  INTEGER (KIND=JPIM)::NFIELDS2D_OFFSET
ENDTYPE TMDDH

ENDMODULE YOMMDDH
