MODULE YOMMCC
USE PARKIND1,ONLY:JPRD, JPIM, JPRB
USE CPLNG_TYPES_MOD,ONLY:CPLNG_FLD_TYPE
USE PAR_GFL,ONLY:JPCHEM
USE YOMCOMPO,ONLY:NPEMIS2D, NPEMIS2DAUX
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE

TYPE::TMCC
  INTEGER (KIND=JPIM)::N923
  INTEGER (KIND=JPIM)::NCLIMTOT
  INTEGER (KIND=JPIM)::NCLIMR
  INTEGER (KIND=JPIM)::NCLIGC (19)
  INTEGER (KIND=JPIM)::NCLIGC_COMPO (NPEMIS2D+NPEMIS2DAUX+JPCHEM+2)
  INTEGER (KIND=JPIM)::NYSDMP_COMPO (NPEMIS2D+NPEMIS2DAUX+JPCHEM+2)
  INTEGER (KIND=JPIM)::NCLIMR_COMPO
  INTEGER (KIND=JPIM)::NCLIAER (16)
  INTEGER (KIND=JPIM)::NDIFC
  INTEGER (KIND=JPIM)::NJDCR
  INTEGER (KIND=JPIM)::NJDCR1
  INTEGER (KIND=JPIM)::NDIFC_COMPO
  INTEGER (KIND=JPIM)::NJDCR_COMPO
  INTEGER (KIND=JPIM)::NJDCR1_COMPO
  INTEGER (KIND=JPIM)::NP1
  INTEGER (KIND=JPIM)::NP2
  INTEGER (KIND=JPIM)::NPCO2_1, NPCO2_2
  INTEGER (KIND=JPIM)::NPAER_1, NPAER_2
  INTEGER (KIND=JPIM)::NPCOMPO_1, NPCOMPO_2
  INTEGER (KIND=JPIM)::NUNITC
  INTEGER (KIND=JPIM)::NUNITC1
  INTEGER (KIND=JPIM)::NUNITCM
  INTEGER (KIND=JPIM)::NOACOMM
  INTEGER (KIND=JPIM)::NSSTICEOP
  REAL (KIND=JPRB), ALLOCATABLE::CLIMRCO2 (:,:,:), CLIMRAER (&
  &:,:,:), CLIMRCOMPO (:,:,:), ZLAKE (:,:,:), OCEANBC (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::CLIMR (:,:,:)
  LOGICAL::LFIRSTUPD=.TRUE.
  LOGICAL::LCURR
  LOGICAL::LGELATO
  LOGICAL::LMCC01_MSE
  LOGICAL::LMCC01
  LOGICAL::LMCC02
  LOGICAL::LMCC03
  LOGICAL::LMCC04
  LOGICAL::LMCC05
  LOGICAL::LMCC06
  LOGICAL::LMCCEC
  LOGICAL::LMCCIEC
  LOGICAL::LMCCIEC_COMPO
  LOGICAL::LMCCICEIC
  LOGICAL::LMCCDYNSEAICE
  LOGICAL::LNEMOCOUP
  LOGICAL::LNEMOFLUXNC
  LOGICAL::LNEMOOUTGRB
  LOGICAL::LCOUPINFOUT
  LOGICAL::LNEMO1WAY
  LOGICAL::LNEMOIFSLOG
  LOGICAL::LNEMOSSTFREEZ
  LOGICAL::LNEMOGRIBFLDS
  LOGICAL::LNEMOGRIBMASK
  LOGICAL::L2DECV2NEMO
  LOGICAL::LMULTIYR
  LOGICAL::LMCC_COMPO
  INTEGER (KIND=JPIM)::NFRCPL
  LOGICAL::LNEMOLIMGET=.TRUE.
  LOGICAL::LNEMOLIMPUT=.TRUE.
  LOGICAL::LNEMOLIMALB=.FALSE.
  LOGICAL::LNEMOLIMTEMP=.FALSE.
  LOGICAL::LNEMOLIMTLVL=.FALSE.
  LOGICAL::LNEMOLIMTHK=.FALSE.
  LOGICAL::LNEMOSICOUP=.FALSE.
  LOGICAL::LNEMOATMFLDS=.TRUE.
  LOGICAL::LNEMOOCEICEMIX=.FALSE.
  LOGICAL::LNEMOQNSICEFILT=.FALSE.
  LOGICAL::LNEMOACCUMFLUX=.TRUE.
  LOGICAL::LNEMOGRIB3D
  INTEGER::NNEMO3DLEVS
  REAL (KIND=JPRB), ALLOCATABLE::RNEMOLVLS (:)
  REAL (KIND=JPRD), ALLOCATABLE::RNEMOMASK (:,:)
  LOGICAL::LNEMOPARTCOUP=.FALSE.
  LOGICAL::LNEMOPARTMASK=.FALSE.
  LOGICAL::LNEMOPARTMASKFILE=.FALSE.
  REAL (KIND=JPRB)::RNPARTRAMPSTART=5.0_JPRB
  REAL (KIND=JPRB)::RNPARTRAMPLEN=4.0_JPRB
  REAL (KIND=JPRB)::RNPARTLAT=20.0_JPRB
  REAL (KIND=JPRB)::RNPARTLATSPREAD=5.0_JPRB
  REAL (KIND=JPRB), ALLOCATABLE::PARTSST0 (:)
  REAL (KIND=JPRB), ALLOCATABLE::PARTMASK (:)
  CHARACTER (LEN=128)::CDNPARTMASKFILE='partialmask.grib'
  TYPE (CPLNG_FLD_TYPE), ALLOCATABLE, DIMENSION (:)::CPLNG_FLD
  LOGICAL::CPLNG_ACTIVE=.FALSE.
  INTEGER (KIND=JPIM)::CPLNG_NUM_FIELDS=0
  INTEGER (KIND=JPIM)::IP_A_SST=-1
  INTEGER (KIND=JPIM)::IP_A_ICE_FRAC=-1
  INTEGER (KIND=JPIM)::IP_A_CURR_U=-1
  INTEGER (KIND=JPIM)::IP_A_CURR_V=-1
  INTEGER (KIND=JPIM)::IP_A_TAUX_OCE=-1
  INTEGER (KIND=JPIM)::IP_A_TAUY_OCE=-1
  INTEGER (KIND=JPIM)::IP_A_TAUX_ICE=-1
  INTEGER (KIND=JPIM)::IP_A_TAUY_ICE=-1
  INTEGER (KIND=JPIM)::IP_A_QS_MIX=-1
  INTEGER (KIND=JPIM)::IP_A_QNS_MIX=-1
  INTEGER (KIND=JPIM)::IP_A_QS_OCE=-1
  INTEGER (KIND=JPIM)::IP_A_QNS_OCE=-1
  INTEGER (KIND=JPIM)::IP_A_QS_ICE=-1
  INTEGER (KIND=JPIM)::IP_A_QNS_ICE=-1
  INTEGER (KIND=JPIM)::IP_A_PRECIP_LIQUID=-1
  INTEGER (KIND=JPIM)::IP_A_PRECIP_SOLID=-1
  INTEGER (KIND=JPIM)::IP_A_EVAP_TOTAL=-1
  INTEGER (KIND=JPIM)::IP_A_EVAP_ICE=-1
  INTEGER (KIND=JPIM)::IP_A_DQNS_DT=-1
  INTEGER (KIND=JPIM)::IP_A_RUNOFF=-1
  INTEGER (KIND=JPIM)::IP_A_TOTAL_CC=-1
  INTEGER (KIND=JPIM)::IP_A_LOW_CC=-1
  INTEGER (KIND=JPIM)::IP_A_ICE_TEMP=-1
  INTEGER (KIND=JPIM)::IP_A_ICE_ALBEDO=-1
  INTEGER (KIND=JPIM)::IP_A_ICE_THICKNESS=-1
  INTEGER (KIND=JPIM)::IP_A_SNOW_THICKNESS=-1
  INTEGER (KIND=JPIM)::IP_A_ICE_TEMP_LVLS=-1
  INTEGER (KIND=JPIM)::IP_A_TAUX=-1
  INTEGER (KIND=JPIM)::IP_A_TAUY=-1
  INTEGER (KIND=JPIM)::IP_A_QS=-1
  INTEGER (KIND=JPIM)::IP_A_QNS=-1
  INTEGER (KIND=JPIM)::IP_A_WATER=-1
  INTEGER (KIND=JPIM)::IP_A_SST_ATM=-1
  INTEGER (KIND=JPIM)::IP_A_TSK_ATM=-1
  INTEGER (KIND=JPIM)::IP_A_IST_ATM=-1
  INTEGER (KIND=JPIM)::IP_A_2DECV_SKT=-1
  LOGICAL::LCOUPSIM=.FALSE.
  
ENDTYPE TMCC

CONTAINS

ENDMODULE YOMMCC
