MODULE YOMMP
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TMP
  INTEGER (KIND=JPIM), ALLOCATABLE::NUMPP (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPROCM (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPTRMS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NALLMS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPTRLS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPTRSV (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPTRSVF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPTRMF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSPSTAF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NUMLL (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPTRLL (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MYLEVS (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPSURF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NSTA (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NONL (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPTRFRSTLAT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPTRLSTLAT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NPTRLAT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NFRSTLAT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NLSTLAT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NBSETLEV (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NGLOBALINDEX (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NGLOBALAT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NGLOBALPROC (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NLOCALINDEX (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NLATGPP (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NLONGPP (:,:)
  LOGICAL, ALLOCATABLE::LSPLITLAT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MYLATS (:)
  INTEGER (KIND=JPIM)::NPSP
  INTEGER (KIND=JPIM)::NSPEC2V
  INTEGER (KIND=JPIM)::NSPEC2VF
  INTEGER (KIND=JPIM)::NSPEC2VDDH
  INTEGER (KIND=JPIM)::NSPEC2V_NH
  INTEGER (KIND=JPIM)::NSPEC2V_NHX
  INTEGER (KIND=JPIM)::NSPEC2V_SI
  INTEGER (KIND=JPIM)::NSPEC2V_VOR_SI
  INTEGER (KIND=JPIM)::NSPEC2V_NH_SI
  INTEGER (KIND=JPIM)::NSPEC2V_PA_SI
  INTEGER (KIND=JPIM)::NSPEC2V_DDH_SI
  INTEGER (KIND=JPIM)::NSPEC2V_NH_DDH_SI
  INTEGER (KIND=JPIM)::NSPEC2V_VOR_DDH_SI
  INTEGER (KIND=JPIM)::NBSETSP
  INTEGER (KIND=JPIM)::NFRSTLOFF
  INTEGER (KIND=JPIM)::MYFRSTACTLAT
  INTEGER (KIND=JPIM)::MYLSTACTLAT
  INTEGER (KIND=JPIM)::NPTRFLOFF
  INTEGER (KIND=JPIM), ALLOCATABLE::NPOSSP (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NDIM0G (:)
ENDTYPE TMP

ENDMODULE YOMMP
