
MODULE YOMMPLSTATS
USE EC_PARKIND,ONLY:JPRD, JPIM

IMPLICIT NONE

SAVE


LOGICAL::LMPLSTATS=.FALSE.
REAL (KIND=JPRD), ALLOCATABLE::MPLSENDBYTES (:), MPLRECVBYTES (:)
INTEGER (KIND=JPIM), ALLOCATABLE::MPLSENDNUM (:), MPLRECVNUM (:)
ENDMODULE YOMMPLSTATS
