MODULE YOMNORGWD
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TNORGWD
  CHARACTER (LEN=4)::NORGWD_SCHEME
  REAL (KIND=JPRB)::NORGWD_PRMAX
  REAL (KIND=JPRB)::NORGWD_DZ
  REAL (KIND=JPRB)::NORGWD_PTROPO
  INTEGER (KIND=JPIM)::NORGWD_NTROPO
  REAL (KIND=JPRB)::NORGWD_RUWMAX
  REAL (KIND=JPRB)::NORGWD_SAT
  REAL (KIND=JPRB)::NORGWD_RDISS
  REAL (KIND=JPRB)::NORGWD_DELTAT
  REAL (KIND=JPRB)::NORGWD_KMIN
  REAL (KIND=JPRB)::NORGWD_KMAX
  REAL (KIND=JPRB)::NORGWD_CMIN
  REAL (KIND=JPRB)::NORGWD_CMAX
  REAL (KIND=JPRB)::NORGWD_PLAUNCH
  INTEGER (KIND=JPIM)::NORGWD_NLAUNCH
  REAL (KIND=JPRB)::NORGWD_PNOVERDIF
  INTEGER (KIND=JPIM)::NORGWD_NNOVERDIF
  REAL (KIND=JPRB)::NORGWD_DZFRON
  REAL (KIND=JPRB)::NORGWD_GFRON
  REAL (KIND=JPRB)::NORGWD_GB
ENDTYPE TNORGWD

ENDMODULE YOMNORGWD
