MODULE YOMNRTAER
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE TNRTAER
  LOGICAL::LCAMS_NRT
  LOGICAL::LMOCA_NRT
  LOGICAL::LAEIFN
  LOGICAL::LAERDRDEP
  LOGICAL::LAERSSEM
  LOGICAL::LAECCN2CLDR
  REAL (KIND=JPRB)::SSMINLO
  REAL (KIND=JPRB)::SSMINUP
  REAL (KIND=JPRB)::SSMAX
  REAL (KIND=JPRB)::SSHEIGHT
  REAL (KIND=JPRB)::SSFACVV
  REAL (KIND=JPRB)::SSFACSS
  REAL (KIND=JPRB)::RPANMIN
  REAL (KIND=JPRB)::RCCNMIN
  REAL (KIND=JPRB)::RCLDROPMIN
  REAL (KIND=JPRB)::RIFNMINSIZE
ENDTYPE TNRTAER

ENDMODULE YOMNRTAER
