MODULE YOMNUD
USE PARKIND1,ONLY:JPIM, JPRB
USE PARDIM,ONLY:JPMXLE
USE YOMSNU

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM)::NFNUDG
INTEGER (KIND=JPIM)::NFRNUDG
INTEGER (KIND=JPIM)::NTNUDG
INTEGER (KIND=JPIM)::NTOTFNUDG3
INTEGER (KIND=JPIM)::NTOTFNUDG2
INTEGER (KIND=JPIM)::NSPNU1
INTEGER (KIND=JPIM)::NSPNU2
LOGICAL::LNUDG
LOGICAL::LNUDDI
LOGICAL::LNUDLP
LOGICAL::LNUDRM
LOGICAL::LNUDSD
LOGICAL::LNUDSH
LOGICAL::LNUDSM
LOGICAL::LNUDST
LOGICAL::LNUDSV
LOGICAL::LNUDTE
LOGICAL::LNUDVO
LOGICAL::LNDRIV
LOGICAL::LNUDTG
LOGICAL::LNUDQG
LOGICAL::LNUDUG
LOGICAL::LNUDVG
LOGICAL::LNUDPG
LOGICAL::LWNUDG
REAL (KIND=JPRB)::XNUVERT (1:JPMXLE)
REAL (KIND=JPRB)::XNUDDI
REAL (KIND=JPRB)::XNUDLP
REAL (KIND=JPRB)::XNUDRM
REAL (KIND=JPRB)::XNUDSD
REAL (KIND=JPRB)::XNUDSH
REAL (KIND=JPRB)::XNUDSM
REAL (KIND=JPRB)::XNUDST
REAL (KIND=JPRB)::XNUDSV
REAL (KIND=JPRB)::XNUDTE
REAL (KIND=JPRB)::XNUDVO
REAL (KIND=JPRB)::XNUDTG
REAL (KIND=JPRB)::XNUDQG
REAL (KIND=JPRB)::XNUDUG
REAL (KIND=JPRB)::XNUDVG
REAL (KIND=JPRB)::XNUDPG
REAL (KIND=JPRB), ALLOCATABLE::XVUST (:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::XVUSM (:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::XVURM (:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::XVUSD (:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::XVUTG (:,:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::XVUQG (:,:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::XVUUG (:,:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::XVUVG (:,:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::XVUPG (:,:,:)
CONTAINS




ENDMODULE YOMNUD
