MODULE YOMOZO
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE::TOZO
  REAL (KIND=JPRB), ALLOCATABLE::TOZ2DG (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::TOZ2DL (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::TOZ3DBL (:,:)
  REAL (KIND=JPRB)::TEECL2
ENDTYPE TOZO

ENDMODULE YOMOZO
