MODULE YOMOROG
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE


TYPE TOROG
  REAL (KIND=JPRB), ALLOCATABLE::OROG (:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGL (:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGM (:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGLL (:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGMM (:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGLM (:)
  
  
  
ENDTYPE TOROG


TYPE TOROG_BLOCKED
  REAL (KIND=JPRB), ALLOCATABLE::OROG (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGL (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGM (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGLL (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGMM (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::OROGLM (:,:)
  
  
  
ENDTYPE TOROG_BLOCKED

CONTAINS




ENDMODULE YOMOROG
