MODULE YOMPARAR
USE PARKIND1,ONLY:JPIM, JPRB
USE MODD_PHYEX,ONLY:PHYEX_T
USE YOMTENDRA,ONLY:TTENDRA
USE YOMEDMF,ONLY:TEDMF

IMPLICIT NONE

SAVE

TYPE TPARAR
  CHARACTER (LEN=4)::CMICRO
  CHARACTER (LEN=4)::CTURB
  TYPE (PHYEX_T)::PHYEX
  TYPE (TTENDRA)::YRTENDRA
  TYPE (TEDMF)::YREDMF
  INTEGER (KIND=JPIM)::NRR, NRRL, NRRI
  INTEGER (KIND=JPIM)::NSV
  INTEGER (KIND=JPIM)::NSWB_MNH
  INTEGER (KIND=JPIM)::NGPAR
  INTEGER (KIND=JPIM)::MINPRR
  INTEGER (KIND=JPIM)::MACPRR
  INTEGER (KIND=JPIM)::MINPRS
  INTEGER (KIND=JPIM)::MACPRS
  INTEGER (KIND=JPIM)::MINPRG
  INTEGER (KIND=JPIM)::MACPRG
  INTEGER (KIND=JPIM)::MALBDIR
  INTEGER (KIND=JPIM)::MALBSCA
  INTEGER (KIND=JPIM)::MRAIN
  INTEGER (KIND=JPIM)::MSNOW
  INTEGER (KIND=JPIM)::MGZ0
  INTEGER (KIND=JPIM)::MGZ0H
  INTEGER (KIND=JPIM)::MVQS
  INTEGER (KIND=JPIM)::MVTS
  INTEGER (KIND=JPIM)::MVEMIS
  INTEGER (KIND=JPIM)::MSWDIR
  INTEGER (KIND=JPIM)::MSWDIF
  INTEGER (KIND=JPIM)::MLSM
  INTEGER (KIND=JPIM)::MCD
  INTEGER (KIND=JPIM)::MCH
  REAL (KIND=JPRB), DIMENSION (:), ALLOCATABLE::XSW_BANDS
  LOGICAL::LOLSMC
  LOGICAL::LOTOWNC
  LOGICAL::LICERAD
  REAL (KIND=JPRB)::RADGR
  REAL (KIND=JPRB)::RADSN
  LOGICAL::LLCRIT
  LOGICAL::LTOTPREC
  LOGICAL::LTOTPRECL
  LOGICAL::LDUALMF
  LOGICAL::LSCAWAREMF
  LOGICAL::LWTHRESH
  LOGICAL::LWTHRESHMOIST
  REAL (KIND=JPRB)::XVMAXTHP
  REAL (KIND=JPRB)::XVMAXTHM
  LOGICAL::LSQUALL
  INTEGER (KIND=JPIM)::NREFROI1
  INTEGER (KIND=JPIM)::NREFROI2
  REAL (KIND=JPRB)::VSQUALL
  LOGICAL::LAROBU_ENABLE
  REAL (KIND=JPRB)::XCQVR
  REAL (KIND=JPRB)::GQVPLIM
  REAL (KIND=JPRB)::GQVTOP
  LOGICAL::LQVTOP
  LOGICAL::LIMIT_TENDQ
  REAL (KIND=JPRB)::ZWL
  REAL (KIND=JPRB)::ZWT
  REAL (KIND=JPRB)::ZEL
  REAL (KIND=JPRB)::ZET
  REAL (KIND=JPRB)::ZW2THRESH
  REAL (KIND=JPRB)::ZMFDRYCON
  REAL (KIND=JPRB)::ZMBCLOSURECON
  REAL (KIND=JPRB)::ZRG
  REAL (KIND=JPRB)::ZLAT2CP
  REAL (KIND=JPRB)::ZEL2R
  REAL (KIND=JPRB)::ZEI2R
  REAL (KIND=JPRB)::ZCONS13
  REAL (KIND=JPRB)::ZEPS
  REAL (KIND=JPRB)::ZC_0
  REAL (KIND=JPRB)::ZC_D
  REAL (KIND=JPRB)::ZC_N
  REAL (KIND=JPRB)::ZWSTF
  REAL (KIND=JPRB)::ZTKEMIN
  REAL (KIND=JPRB)::ZPRANDT
  REAL (KIND=JPRB)::ZI2
  REAL (KIND=JPRB)::ZALPHA_N
  REAL (KIND=JPRB)::ZALPHA_C
  REAL (KIND=JPRB)::ZB
  REAL (KIND=JPRB)::ZC_M_MAX
  REAL (KIND=JPRB)::ZREPUST
ENDTYPE TPARAR

ENDMODULE YOMPARAR
