MODULE YOMPRAD
USE PARKIND1,ONLY:JPIM, JPRB, JPRD

IMPLICIT NONE

SAVE

TYPE RADIATION_GRID_STRUCT
  INTEGER (KIND=JPIM)::NRESOL_ID, NGPTOT, NGPTOTG, NGPTOTMX, NSPEC2, NSMAX,&
  & NPTRFLOFF, NUMP, NDLON, NDGSAL, NDGENL, NDGSAH, NDGENH, NDGLG, NDGSAG, NDGENG&
  &, NDLSUR, NFRSTLOFF, NDSUR1, NDGSUR, MYFRSTACTLAT, MYLSTACTLAT
  INTEGER (KIND=JPIM), ALLOCATABLE, DIMENSION (:)::NRGRI,&
  & NLOENG, NPTRFRSTLAT, NFRSTLAT, NLSTLAT, MYMS, NASM0
  INTEGER (KIND=JPIM), ALLOCATABLE, DIMENSION (:,:)::NSTA, NONL
  REAL (KIND=JPRB), ALLOCATABLE, DIMENSION (:)::GELAM, GELAT, GECLO, GESLO, RMU, RSQM2, RLATIG, RLATI
  REAL (KIND=JPRD), ALLOCATABLE, DIMENSION (:)::GEMU
  REAL (KIND=JPRD), ALLOCATABLE, DIMENSION (:,:)::RIPI
  
ENDTYPE RADIATION_GRID_STRUCT

CONTAINS

ENDMODULE YOMPRAD
