MODULE YOMPHY
USE PARKIND1,ONLY:JPIM
USE YOMDPRECIPS,ONLY:TDPRECIPS
USE YOMDVISI,ONLY:TDVISI
USE YOMCAPE,ONLY:TCAPE
USE YOMDWET,ONLY:TDWET
USE YOMRPP,ONLY:TRPP

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::JPHYEC=1
INTEGER (KIND=JPIM), PARAMETER::JPHYMF=2
INTEGER (KIND=JPIM), PARAMETER::JPHYARO=3
INTEGER (KIND=JPIM), PARAMETER::JPBP002=4

TYPE TPHY
  INTEGER (KIND=JPIM)::NBITER
  INTEGER (KIND=JPIM)::NITERFL
  INTEGER (KIND=JPIM)::NDPSFI
  LOGICAL::LMPHYS
  LOGICAL::LREASUR
  LOGICAL::LCAPE
  LOGICAL::LCVGQD
  LOGICAL::LCVGQM
  LOGICAL::LCVGQP
  LOGICAL::LCONDWT
  LOGICAL::LCVDD
  LOGICAL::LCVPGY
  LOGICAL::LCVPP
  LOGICAL::LDIFCEXP
  LOGICAL::LDIFCONS
  LOGICAL::LDIFQL
  LOGICAL::LDISTUR
  LOGICAL::LNEIGE
  LOGICAL::LRNUMX
  LOGICAL::LRNUEXP
  LOGICAL::LRTRUEBBC
  LOGICAL::LRTRUEDIR
  LOGICAL::LACPANMX
  LOGICAL::LCLSATUR
  LOGICAL::LVOIGT
  LOGICAL::LGLACIERS
  LOGICAL::LVFULL
  LOGICAL::LSLC
  LOGICAL::LRAYLU
  LOGICAL::LREWS
  LOGICAL::LRPROX
  LOGICAL::LRMIX
  LOGICAL::LRSTAB
  LOGICAL::LRSTAER
  LOGICAL::LRTPP
  LOGICAL::LRTDL
  LOGICAL::LRAYPL
  LOGICAL::LRRGUST
  LOGICAL::LO3ABC
  LOGICAL::LO3FL
  LOGICAL::LECSHAL
  LOGICAL::LECDEEP
  LOGICAL::LNEBNXR
  LOGICAL::LNEB_FP
  LOGICAL::LQXRTGH
  LOGICAL::LHUCN
  LOGICAL::LFPCOR
  LOGICAL::LNOIAS
  LOGICAL::LGLT
  LOGICAL::LNEWD
  LOGICAL::LPROCLD
  LOGICAL::LEVAPP
  LOGICAL::LCOLLEC
  LOGICAL::LADJCLD
  LOGICAL::LSEDSTA
  LOGICAL::LSEDLAG
  LOGICAL::LSEDCL
  LOGICAL::LFSVAR
  LOGICAL::LFSFIX
  LOGICAL::LA0MPS
  LOGICAL::LARPMPS
  LOGICAL::L3MT
  LOGICAL::LGPCMT
  LOGICAL::LENTCH
  LOGICAL::LCDDEVPRO
  LOGICAL::LAEROSEA
  LOGICAL::LAEROLAN
  LOGICAL::LAEROSOO
  LOGICAL::LAERODES
  LOGICAL::LAEROVOL
  LOGICAL::LAEROSUL
  LOGICAL::LAEROMASS2D
  LOGICAL::LAEROMMR3D
  LOGICAL::LAEROMMR
  LOGICAL::LAERONRT
  LOGICAL::LRELAXT
  LOGICAL::LRELAXW
  LOGICAL::LSSD
  LOGICAL::LPBLE
  LOGICAL::LBLVAR
  LOGICAL::LZ0HSREL
  LOGICAL::LZ0SNOWH
  LOGICAL::LMLH
  LOGICAL::LNODIFQC
  LOGICAL::LNCVPGY
  LOGICAL::LSQRML
  LOGICAL::LAB12
  LOGICAL::LFVGICE3
  LOGICAL::LEVAPLOP
  LOGICAL::LCP06
  LOGICAL::LCVSHCU
  LOGICAL::LCVGQ
  LOGICAL::LPEC
  LOGICAL::LUDEVOL
  LOGICAL::LCDDCSD
  INTEGER (KIND=JPIM)::NCLOMIX
  INTEGER (KIND=JPIM)::NFSIG
  LOGICAL::LHLRADUPD
  INTEGER (KIND=JPIM)::NDPRECPERIOD, NDPRECPERIOD2
  LOGICAL::LDPRECIPS, LDPRECIPS2
  TYPE (TDPRECIPS)::YRDPRECIPS
  TYPE (TDVISI)::YRDVISI
  TYPE (TDWET)::YRDWET
  CHARACTER (LEN=20)::CGMIXLEN
  CHARACTER (LEN=20)::CGTURS
  CHARACTER (LEN=20)::CGTRG
  LOGICAL::LPRGML
  LOGICAL::LCVRA
  LOGICAL::LCVTDK
  LOGICAL::LDAYD
  LOGICAL::LCVPRO
  LOGICAL::LGRAPRO
  LOGICAL::LCDDPRO
  LOGICAL::LCVCSD
  LOGICAL::LUSL
  LOGICAL::LNSDO
  LOGICAL::LECT
  LOGICAL::LEFB
  LOGICAL::LFLUSO
  LOGICAL::LECTQ1
  LOGICAL::LECTREP
  LOGICAL::LPTKE
  LOGICAL::LCOEFKTKE
  LOGICAL::LCOEFKSURF
  LOGICAL::LCOEFK_MSC
  LOGICAL::LCOEFK_F1
  LOGICAL::LCOEFK_TOMS
  LOGICAL::LCOEFK_THS1
  LOGICAL::LCOEFK_RIS
  LOGICAL::LCOEFK_PL
  LOGICAL::LCOEFK_ML
  LOGICAL::LCOEFK_PTTE
  LOGICAL::LCOEFK_FLX
  LOGICAL::LCOEFK_SCQ
  LOGICAL::LAFGD_A
  LOGICAL::LGWD
  LOGICAL::LGWDC
  LOGICAL::LNORGWD
  LOGICAL::LHMTO
  LOGICAL::LNEBCO
  LOGICAL::LNEBN
  LOGICAL::LNEBR
  LOGICAL::LPTOPC
  LOGICAL::LOZONE
  LOGICAL::LRAY
  LOGICAL::LRAYFM
  LOGICAL::LRMU0M
  LOGICAL::LRAYFM15
  LOGICAL::LRRMES
  LOGICAL::LSFHYD
  LOGICAL::LSNV
  LOGICAL::LSOLV
  LOGICAL::LFGEL
  LOGICAL::LSTRA
  LOGICAL::LSTRAS
  LOGICAL::LSTRAPRO
  LOGICAL::LNEWSTAT
  LOGICAL::LTHERMO
  LOGICAL::LVDIF
  LOGICAL::LCVLIS
  LOGICAL::LCVCAS
  LOGICAL::LSCMF
  LOGICAL::LVGSN
  LOGICAL::LPHCDPI
  LOGICAL::LNEBGR
  LOGICAL::LNEBGY
  LOGICAL::LCVRAV3
  LOGICAL::LCVPPKF
  LOGICAL::LCVTURB
  LOGICAL::LNEBRIC
  LOGICAL::LEDKF
  LOGICAL::LEDMFI
  LOGICAL::LEDMFS
  LOGICAL::LECTFL
  LOGICAL::LECTFL0
  LOGICAL::LECTPRODCVP
  INTEGER (KIND=JPIM)::NPHYREP
  LOGICAL::LCAMOD
  LOGICAL::LCOMOD
  LOGICAL::LPHSPSH
  LOGICAL::LSMNIMBT
  LOGICAL::LSMTPS
  LOGICAL::LSMGCDEV
  LOGICAL::LXRCDEV
  LOGICAL::LRKCDEV
  LOGICAL::LSMITH_CDEV
  LOGICAL::LRCVOTT
  LOGICAL::LNEBCV
  LOGICAL::LNEBINS
  INTEGER (KIND=JPIM)::NDIFFNEB
  INTEGER (KIND=JPIM)::NIMELIT
  INTEGER (KIND=JPIM)::NRAY
  INTEGER (KIND=JPIM)::NSORAYFR
  INTEGER (KIND=JPIM)::NTHRAYFR
  INTEGER (KIND=JPIM)::NRAUTOEV
  INTEGER (KIND=JPIM)::NSMTBOT
  INTEGER (KIND=JPIM)::NSMDNEB
  INTEGER (KIND=JPIM)::NPRAC, NPRRI
  INTEGER (KIND=JPIM)::NPHY
  INTEGER (KIND=JPIM)::NCALLRAD
  INTEGER (KIND=JPIM)::NLEND
  INTEGER (KIND=JPIM)::NTEND_DIAG_POS
  INTEGER (KIND=JPIM)::NTEND_DIAG_FREQ_RESET
  LOGICAL::LNEBECT
  LOGICAL::LCVGQKF
  LOGICAL::LACDIFUS
  LOGICAL::L2MICRO
  INTEGER (KIND=JPIM)::NSOLE
  LOGICAL::LAJUCV
  LOGICAL::LSMOOTHMELT
  LOGICAL::LGCHECKMV
  LOGICAL::LCHECKSURF
  LOGICAL::LGCHECKNAN
  LOGICAL::LEDR
  LOGICAL::LWINDFARM
  LOGICAL::LBMRED
  INTEGER (KIND=JPIM)::NPBLH_MXL
  INTEGER (KIND=JPIM)::NPBLH_DIAG
  LOGICAL::LAPL_ARPEGE=.FALSE.
  LOGICAL::LAPL_ALARO=.FALSE.
  TYPE (TCAPE)::YRCAPE
  TYPE (TRPP)::YRRPP
ENDTYPE TPHY

TYPE (TPHY), POINTER::YRPHY=>NULL ()
ENDMODULE YOMPHY
