MODULE YOMPHY1
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TPHY1
  REAL (KIND=JPRB)::GF3 (18)
  REAL (KIND=JPRB)::GF4 (18)
  REAL (KIND=JPRB)::TREF4 (18)
  REAL (KIND=JPRB)::RCTVEG (18)
  REAL (KIND=JPRB)::RGL (18)
  REAL (KIND=JPRB)::SODELX (0:9)
  REAL (KIND=JPRB)::GCZ0H (0:3, 4)
  REAL (KIND=JPRB)::ALBGLA
  REAL (KIND=JPRB)::ALBMAX
  REAL (KIND=JPRB)::ALBMER
  REAL (KIND=JPRB)::ALBMED
  REAL (KIND=JPRB)::ALBMIN
  REAL (KIND=JPRB)::ALCRIN
  REAL (KIND=JPRB)::ALRCN1
  REAL (KIND=JPRB)::ALRCN2
  REAL (KIND=JPRB)::EA
  REAL (KIND=JPRB)::EC2REF
  REAL (KIND=JPRB)::EMCRIN
  REAL (KIND=JPRB)::EMMGLA
  REAL (KIND=JPRB)::EMMMER
  REAL (KIND=JPRB)::EWFC
  REAL (KIND=JPRB)::EWWILT
  REAL (KIND=JPRB)::GA
  REAL (KIND=JPRB)::GC1
  REAL (KIND=JPRB)::GC1S1
  REAL (KIND=JPRB)::GC1S2
  REAL (KIND=JPRB)::GC1S3
  REAL (KIND=JPRB)::GC1S4
  REAL (KIND=JPRB)::GC1Y1
  REAL (KIND=JPRB)::GTSVAP
  REAL (KIND=JPRB)::GVEGMX
  REAL (KIND=JPRB)::GLAIMX
  REAL (KIND=JPRB)::GNEIMX
  REAL (KIND=JPRB)::GWPIMX
  REAL (KIND=JPRB)::GCGEL
  REAL (KIND=JPRB)::GC2
  REAL (KIND=JPRB)::GC2REF
  REAL (KIND=JPRB)::GC3
  REAL (KIND=JPRB)::GC31
  REAL (KIND=JPRB)::GC32
  REAL (KIND=JPRB)::GCONV
  REAL (KIND=JPRB)::GF1
  REAL (KIND=JPRB)::GWFC
  REAL (KIND=JPRB)::GWLEX
  REAL (KIND=JPRB)::GWLMX
  REAL (KIND=JPRB)::GWWILT
  REAL (KIND=JPRB)::G1B
  REAL (KIND=JPRB)::G1CGSAT
  REAL (KIND=JPRB)::G1C1SAT
  REAL (KIND=JPRB)::G1P
  REAL (KIND=JPRB)::G1WSAT
  REAL (KIND=JPRB)::G2B
  REAL (KIND=JPRB)::G2CGSAT
  REAL (KIND=JPRB)::G2C1SAT
  REAL (KIND=JPRB)::G2P
  REAL (KIND=JPRB)::G2WSAT
  REAL (KIND=JPRB)::G3CGSAT
  REAL (KIND=JPRB)::GSNC1
  REAL (KIND=JPRB)::GSNC2
  REAL (KIND=JPRB)::HSOL
  REAL (KIND=JPRB)::HSOLIWR
  REAL (KIND=JPRB)::HSOLIT0
  REAL (KIND=JPRB)::OMTPRO
  REAL (KIND=JPRB)::OMWPRO
  REAL (KIND=JPRB)::RC1MAX
  REAL (KIND=JPRB)::RCTGLA
  REAL (KIND=JPRB)::RCGMAX
  REAL (KIND=JPRB)::RD1
  REAL (KIND=JPRB)::RD2GLA
  REAL (KIND=JPRB)::RD2MER
  REAL (KIND=JPRB)::RHOMAX
  REAL (KIND=JPRB)::RHOMIN
  REAL (KIND=JPRB)::RSMAX
  REAL (KIND=JPRB)::RTINER
  REAL (KIND=JPRB)::RZ0GLA
  REAL (KIND=JPRB)::RZ0MER
  REAL (KIND=JPRB)::RZHZ0G
  REAL (KIND=JPRB)::RZHZ0M
  REAL (KIND=JPRB)::RZ0_TO_HEIGHT
  REAL (KIND=JPRB)::TMERGL
  REAL (KIND=JPRB)::TOEXP
  REAL (KIND=JPRB)::TOLIN
  REAL (KIND=JPRB)::WCRIN
  REAL (KIND=JPRB)::WCRINC
  REAL (KIND=JPRB)::WCRING
  REAL (KIND=JPRB)::WNEW
  REAL (KIND=JPRB)::WPMX
  REAL (KIND=JPRB)::WSMX
  REAL (KIND=JPRB)::XCRINR
  REAL (KIND=JPRB)::XCRINV
  LOGICAL::LALBMERCLIM
  LOGICAL::LIMC
  LOGICAL::LIMW
  LOGICAL::LC1VAP
  LOGICAL::LCLS_HS
  LOGICAL::LCLS_TOUCANS
  INTEGER (KIND=JPIM)::NTVGLA
  INTEGER (KIND=JPIM)::NTVMER
  REAL (KIND=JPRB)::GCGELS
  REAL (KIND=JPRB)::GVEGMXS
  REAL (KIND=JPRB)::GLAIMXS
  REAL (KIND=JPRB)::GNEIMXS
  REAL (KIND=JPRB)::ALB1
  REAL (KIND=JPRB)::ALB2
  REAL (KIND=JPRB)::RLAIMX
  REAL (KIND=JPRB)::RLAI
  REAL (KIND=JPRB)::ACLS_HS
  INTEGER (KIND=JPIM)::NCHSP
ENDTYPE TPHY1

TYPE (TPHY1), POINTER::YRPHY1=>NULL ()
ENDMODULE YOMPHY1
