
MODULE YOMPHY2
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TPHY2
  INTEGER (KIND=JPIM)::NTSHM
  INTEGER (KIND=JPIM)::NTSML
  REAL (KIND=JPRB)::TSPHY
  REAL (KIND=JPRB)::XMUCVPP
  REAL (KIND=JPRB)::XMULAF
  REAL (KIND=JPRB)::XDAMP
  REAL (KIND=JPRB)::HCLP
  REAL (KIND=JPRB)::HTCLS
  REAL (KIND=JPRB)::HVCLS
  REAL (KIND=JPRB)::HTSHM
  REAL (KIND=JPRB)::HTSML
  REAL (KIND=JPRB)::HWMOHIGH
  REAL (KIND=JPRB)::HWMOLOW
  REAL (KIND=JPRB)::GZ0RAF
  REAL (KIND=JPRB)::FACRAF
  REAL (KIND=JPRB)::FACRAFCV
  REAL (KIND=JPRB)::FACRAFDCAPE
  REAL (KIND=JPRB)::GCAPERAF
  REAL (KIND=JPRB)::HTKERAF
  LOGICAL::LRAFTUR
  LOGICAL::LMULAF
  LOGICAL::LWMOCLOUD
  LOGICAL::LRAFTKE
ENDTYPE TPHY2

TYPE (TPHY2), POINTER::YRPHY2=>NULL ()
ENDMODULE YOMPHY2
