MODULE YOMRCOEF
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TRCOEF
  LOGICAL::LRCOEF
  LOGICAL::LTLADDIA
  LOGICAL::LGLOBRAD
  INTEGER (KIND=JPIM)::NG3SR
  INTEGER (KIND=JPIM)::NGMTR
  INTEGER (KIND=JPIM)::NLATWR
  INTEGER (KIND=JPIM)::NLATRD
  INTEGER (KIND=JPIM)::NLENGSRB
  INTEGER (KIND=JPIM)::NLENGTRB
  REAL (KIND=JPRB), ALLOCATABLE::SOLRAD (:)
  REAL (KIND=JPRB), ALLOCATABLE::THERRAD (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::TRWEIGHT (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::TRMATSUM (:,:)
  
ENDTYPE TRCOEF

CONTAINS

ENDMODULE YOMRCOEF
