
MODULE YOMRIP
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOEOZOC,ONLY:TEOZOC
USE YOECMIP,ONLY:TECMIP
USE YOERADGHG,ONLY:TRADGHG
USE YOEAERC_TEGEN,ONLY:TEAERC_TEGEN
USE YOEAERC,ONLY:TEAERC
USE REGLATLON_FIELD_MIX,ONLY:REGLATLON_FIELD

IMPLICIT NONE

SAVE

TYPE::TRIP
  INTEGER (KIND=JPIM)::NSTART
  INTEGER (KIND=JPIM)::NSTOP
  CHARACTER (LEN=8)::CSTOP
  INTEGER (KIND=JPIM)::NSTADD
  INTEGER (KIND=JPIM)::NSTASS
  INTEGER (KIND=JPIM)::NFOST
  REAL (KIND=JPRB)::RSTATI
  REAL (KIND=JPRD)::RTIMTR
  REAL (KIND=JPRB)::RHGMT
  REAL (KIND=JPRB)::REQTIM
  REAL (KIND=JPRB)::RSOVR
  REAL (KIND=JPRB)::RDEASO
  REAL (KIND=JPRB)::RDECLI
  REAL (KIND=JPRB)::RWSOVR
  REAL (KIND=JPRB)::RIP0
  REAL (KIND=JPRB)::RCODEC
  REAL (KIND=JPRB)::RSIDEC
  REAL (KIND=JPRB)::RCOVSR
  REAL (KIND=JPRB)::RSIVSR
  REAL (KIND=JPRB)::RCODECN
  REAL (KIND=JPRB)::RSIDECN
  REAL (KIND=JPRB)::RCOVSRN
  REAL (KIND=JPRB)::RSIVSRN
  REAL (KIND=JPRB)::RCODECF
  REAL (KIND=JPRB)::RSIDECF
  REAL (KIND=JPRB)::RCOVSRF
  REAL (KIND=JPRB)::RSIVSRF
  REAL (KIND=JPRB)::TSTEP
  REAL (KIND=JPRB)::TDT
  REAL (KIND=JPRB)::RDTSA
  REAL (KIND=JPRB)::RDTSA2
  REAL (KIND=JPRB)::RDTS62
  REAL (KIND=JPRB)::RDTS22
  REAL (KIND=JPRB)::RTDT
  REAL (KIND=JPRB)::RDECLU
  REAL (KIND=JPRB)::RTMOLT
  REAL (KIND=JPRD)::RJUSMP
  REAL (KIND=JPRB)::RLUNDI
  REAL (KIND=JPRB)::RIP0LU
  REAL (KIND=JPRB)::RCODECLU
  REAL (KIND=JPRB)::RSIDECLU
  REAL (KIND=JPRB)::RCOVSRLU
  REAL (KIND=JPRB)::RSIVSRLU
  TYPE (TEOZOC)::YREOZOC
  TYPE (TECMIP)::YRECMIP
  TYPE (TRADGHG)::YRERADGHG
  TYPE (TEAERC_TEGEN)::YREAERC_TEGEN
  TYPE (TEAERC)::YREAERC
  TYPE (REGLATLON_FIELD)::RAERSO4
  INTEGER (KIND=JPIM)::JPORDT=11
  REAL (KIND=JPRD)::GCOEFS_ASCENSION_DROITE (7585, 0:10, 2)
  REAL (KIND=JPRD)::GCOEFS_DECLINAISON (7585, 0:10, 2)
  REAL (KIND=JPRD)::GCOEFS_DISTANCE (7585, 0:10, 2)
  REAL (KIND=JPRD)::GTDEBUT (7585, 2)
  REAL (KIND=JPRD)::GTFIN (7585, 2)
  INTEGER (KIND=JPIM)::NINTT_MOON
  INTEGER (KIND=JPIM)::NINTT_SUN
  CHARACTER (LEN=200)::CGSOLEC_SUN
  CHARACTER (LEN=200)::CGSOLEC_MOON
  
  
ENDTYPE TRIP

CONTAINS


ENDMODULE YOMRIP
