MODULE YOMRANDOM_STREAMS
USE RANDOM_NUMBERS_MIX,ONLY:RANDOMNUMBERSTREAM

IMPLICIT NONE

SAVE

TYPE::TRANDOM_STREAMS
  TYPE (RANDOMNUMBERSTREAM)::SCAN2MTL
  TYPE (RANDOMNUMBERSTREAM)::STOCHPHYS_CABS
  TYPE (RANDOMNUMBERSTREAM)::STOCHPHYS_SPBS
  TYPE (RANDOMNUMBERSTREAM)::STOCHPHYS_RVP
  TYPE (RANDOMNUMBERSTREAM)::STOPH_SPBS_T
  TYPE (RANDOMNUMBERSTREAM)::STOPH_RVP_T
ENDTYPE TRANDOM_STREAMS

ENDMODULE YOMRANDOM_STREAMS
