MODULE YOMRPP
USE PARKIND1,ONLY:JPRB, JPIM

IMPLICIT NONE

SAVE

TYPE TRPP
  LOGICAL::LRPP
  LOGICAL::LINFLUENT
  LOGICAL::LUSESETRAN_RPP
  INTEGER (KIND=JPIM)::NSEED_RPP
  LOGICAL::LRCRIAUTI
  REAL (KIND=JPRB)::RCRIAUTI_MIN
  REAL (KIND=JPRB)::RCRIAUTI_MAX
  REAL (KIND=JPRB)::RCRIAUTI_BEST
  REAL (KIND=JPRB)::RCRIAUTI_SIGMA
  INTEGER (KIND=JPIM)::RCRIAUTI_SCHEME
  LOGICAL::LRCRIAUTC
  REAL (KIND=JPRB)::RCRIAUTC_MIN
  REAL (KIND=JPRB)::RCRIAUTC_MAX
  REAL (KIND=JPRB)::RCRIAUTC_BEST
  REAL (KIND=JPRB)::RCRIAUTC_SIGMA
  INTEGER (KIND=JPIM)::RCRIAUTC_SCHEME
  LOGICAL::LVSIGQSAT
  REAL (KIND=JPRB)::VSIGQSAT_MIN
  REAL (KIND=JPRB)::VSIGQSAT_MAX
  REAL (KIND=JPRB)::VSIGQSAT_BEST
  REAL (KIND=JPRB)::VSIGQSAT_SIGMA
  INTEGER (KIND=JPIM)::VSIGQSAT_SCHEME
  LOGICAL::LXLINI
  REAL (KIND=JPRB)::XLINI_MIN
  REAL (KIND=JPRB)::XLINI_MAX
  REAL (KIND=JPRB)::XLINI_BEST
  REAL (KIND=JPRB)::XLINI_SIGMA
  INTEGER (KIND=JPIM)::XLINI_SCHEME
  LOGICAL::LXCTD
  REAL (KIND=JPRB)::XCTD_MIN
  REAL (KIND=JPRB)::XCTD_MAX
  REAL (KIND=JPRB)::XCTD_BEST
  REAL (KIND=JPRB)::XCTD_SIGMA
  INTEGER (KIND=JPIM)::XCTD_SCHEME
  LOGICAL::LXCTP
  REAL (KIND=JPRB)::XCTP_MIN
  REAL (KIND=JPRB)::XCTP_MAX
  REAL (KIND=JPRB)::XCTP_BEST
  REAL (KIND=JPRB)::XCTP_SIGMA
  INTEGER (KIND=JPIM)::XCTP_SCHEME
  LOGICAL::LXCEP
  REAL (KIND=JPRB)::XCEP_MIN
  REAL (KIND=JPRB)::XCEP_MAX
  REAL (KIND=JPRB)::XCEP_BEST
  REAL (KIND=JPRB)::XCEP_SIGMA
  INTEGER (KIND=JPIM)::XCEP_SCHEME
  LOGICAL::LXCED
  REAL (KIND=JPRB)::XCED_MIN
  REAL (KIND=JPRB)::XCED_MAX
  REAL (KIND=JPRB)::XCED_BEST
  REAL (KIND=JPRB)::XCED_SIGMA
  INTEGER (KIND=JPIM)::XCED_SCHEME
  LOGICAL::LXPHI_LIM
  REAL (KIND=JPRB)::XPHI_LIM_MIN
  REAL (KIND=JPRB)::XPHI_LIM_MAX
  REAL (KIND=JPRB)::XPHI_LIM_BEST
  REAL (KIND=JPRB)::XPHI_LIM_SIGMA
  INTEGER (KIND=JPIM)::XPHI_LIM_SCHEME
  LOGICAL::LXCET
  REAL (KIND=JPRB)::XCET_MIN
  REAL (KIND=JPRB)::XCET_MAX
  REAL (KIND=JPRB)::XCET_BEST
  REAL (KIND=JPRB)::XCET_SIGMA
  INTEGER (KIND=JPIM)::XCET_SCHEME
  LOGICAL::LXRIMAX
  REAL (KIND=JPRB)::XRIMAX_MAX
  REAL (KIND=JPRB)::XRIMAX_MIN
  REAL (KIND=JPRB)::XRIMAX_BEST
  REAL (KIND=JPRB)::XRIMAX_SIGMA
  INTEGER (KIND=JPIM)::XRIMAX_SCHEME
  LOGICAL::LXFRACZ0
  REAL (KIND=JPRB)::XFRACZ0_MIN
  REAL (KIND=JPRB)::XFRACZ0_MAX
  REAL (KIND=JPRB)::XFRACZ0_BEST
  REAL (KIND=JPRB)::XFRACZ0_SIGMA
  INTEGER (KIND=JPIM)::XFRACZ0_SCHEME
  LOGICAL::LXCMF
  REAL (KIND=JPRB)::XCMF_MIN
  REAL (KIND=JPRB)::XCMF_MAX
  REAL (KIND=JPRB)::XCMF_BEST
  REAL (KIND=JPRB)::XCMF_SIGMA
  INTEGER (KIND=JPIM)::XCMF_SCHEME
  LOGICAL::LXABUO
  REAL (KIND=JPRB)::XABUO_MIN
  REAL (KIND=JPRB)::XABUO_MAX
  REAL (KIND=JPRB)::XABUO_BEST
  REAL (KIND=JPRB)::XABUO_SIGMA
  INTEGER (KIND=JPIM)::XABUO_SCHEME
  LOGICAL::LXBDETR
  REAL (KIND=JPRB)::XBDETR_MIN
  REAL (KIND=JPRB)::XBDETR_MAX
  REAL (KIND=JPRB)::XBDETR_BEST
  REAL (KIND=JPRB)::XBDETR_SIGMA
  INTEGER (KIND=JPIM)::XBDETR_SCHEME
  LOGICAL::LCLOUD_INHOM_DECORR_SCALING
  REAL (KIND=JPRB)::CLOUD_INHOM_DECORR_SCALING_MIN
  REAL (KIND=JPRB)::CLOUD_INHOM_DECORR_SCALING_MAX
  REAL (KIND=JPRB)::CLOUD_INHOM_DECORR_SCALING_BEST
  REAL (KIND=JPRB)::CLOUD_INHOM_DECORR_SCALING_SIGMA
  INTEGER (KIND=JPIM)::CLOUD_INHOM_DECORR_SCALING_SCHEME
  LOGICAL::LXENTR_DRY
  REAL (KIND=JPRB)::XENTR_DRY_MIN
  REAL (KIND=JPRB)::XENTR_DRY_MAX
  REAL (KIND=JPRB)::XENTR_DRY_BEST
  REAL (KIND=JPRB)::XENTR_DRY_SIGMA
  INTEGER (KIND=JPIM)::XENTR_DRY_SCHEME
  LOGICAL::LRCADECOR
  REAL (KIND=JPRB)::RCADECOR_MIN
  REAL (KIND=JPRB)::RCADECOR_MAX
  REAL (KIND=JPRB)::RCADECOR_BEST
  REAL (KIND=JPRB)::RCADECOR_SIGMA
  INTEGER (KIND=JPIM)::RCADECOR_SCHEME
  LOGICAL::LRCBDECOR
  REAL (KIND=JPRB)::RCBDECOR_MIN
  REAL (KIND=JPRB)::RCBDECOR_MAX
  REAL (KIND=JPRB)::RCBDECOR_BEST
  REAL (KIND=JPRB)::RCBDECOR_SIGMA
  INTEGER (KIND=JPIM)::RCBDECOR_SCHEME
ENDTYPE TRPP

ENDMODULE YOMRPP
