MODULE YOMRADF
USE PARKIND1,ONLY:JPRB, JPIM
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE FIELD_MODULE

IMPLICIT NONE

SAVE

TYPE::TRADF
  CLASS (FIELD_3RB), POINTER::F_DERIVATIVELW=>NULL ()
  REAL (KIND=JPRB), POINTER::DERIVATIVELW (:,:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_EDRO=>NULL ()
  REAL (KIND=JPRB), POINTER::EDRO (:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_EMTC=>NULL ()
  REAL (KIND=JPRB), POINTER::EMTC (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_EMTD=>NULL ()
  REAL (KIND=JPRB), POINTER::EMTD (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_EMTU=>NULL ()
  REAL (KIND=JPRB), POINTER::EMTU (:,:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RMOON=>NULL ()
  REAL (KIND=JPRB), POINTER::RMOON (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRCDIR=>NULL ()
  REAL (KIND=JPRB), POINTER::SRCDIR (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRFDIR=>NULL ()
  REAL (KIND=JPRB), POINTER::SRFDIR (:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_SRLWD=>NULL ()
  REAL (KIND=JPRB), POINTER::SRLWD (:,:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRLWDC=>NULL ()
  REAL (KIND=JPRB), POINTER::SRLWDC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRLWDCS=>NULL ()
  REAL (KIND=JPRB), POINTER::SRLWDCS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSDIR=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSDIR (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSWD=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSWD (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSWDC=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSWDC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSWDCS=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSWDCS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSWDUV=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSWDUV (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSWDV=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSWDV (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSWPAR=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSWPAR (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSWPARC=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSWPARC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSWTINC=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSWTINC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SRSWUVB=>NULL ()
  REAL (KIND=JPRB), POINTER::SRSWUVB (:)=>NULL ()
  CLASS (FIELD_4RB), POINTER::F_TAUAER=>NULL ()
  REAL (KIND=JPRB), POINTER::TAUAER (:,:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_TRSC=>NULL ()
  REAL (KIND=JPRB), POINTER::TRSC (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_TRSW=>NULL ()
  REAL (KIND=JPRB), POINTER::TRSW (:,:)=>NULL ()
  
  
  
  
  
  
  
  
ENDTYPE TRADF

REAL (KIND=JPRB), PRIVATE, SAVE, TARGET::ZDUM1 (1), ZDUM2 (1, 1), ZDUM3 (1, 1, 1)
CONTAINS








ENDMODULE YOMRADF
