MODULE YOMSPHYHIST
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE SPHYS_HIST_TYPE
  REAL (KIND=JPRB), DIMENSION (:,:), POINTER::YA5=>NULL (), YL5=>NULL (), YI5=>NULL ()
  REAL (KIND=JPRB), DIMENSION (:,:), POINTER::RADLWM=>NULL (), RADLWM5=>NULL ()
  REAL (KIND=JPRB), DIMENSION (:,:), POINTER::TGWDWMSU=>NULL (), TGWDWMSU5=>NULL ()
  REAL (KIND=JPRB), DIMENSION (:,:), POINTER::TGWDWMSV=>NULL (), TGWDWMSV5=>NULL ()
  REAL (KIND=JPRB), DIMENSION (:), POINTER::DIFTQ_S=>NULL (), DIFTQ_S5=>NULL ()
  REAL (KIND=JPRB), DIMENSION (:), POINTER::DIFTS_S=>NULL (), DIFTS_S5=>NULL ()
  REAL (KIND=JPRB), DIMENSION (:,:), POINTER::TENU_VD9=>NULL ()&
  &, TENV_VD9=>NULL (), TENT_VD9=>NULL (), TENQ_VD9=>NULL ()
ENDTYPE SPHYS_HIST_TYPE

ENDMODULE YOMSPHYHIST
