MODULE YOMSTA
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
REAL (KIND=JPRB)::RDTDZ1
REAL (KIND=JPRB)::RDTDZ2
REAL (KIND=JPRB)::RDTDZ3
REAL (KIND=JPRB)::RDTDZ4
REAL (KIND=JPRB)::RDTDZ5
REAL (KIND=JPRB)::RDTDZ6
REAL (KIND=JPRB)::RDTDZ7
REAL (KIND=JPRB)::RDTDZ8
REAL (KIND=JPRB)::RDTDZ9
REAL (KIND=JPRB)::RZTROP
REAL (KIND=JPRB)::RZSTRA
REAL (KIND=JPRB)::RZSTR2
REAL (KIND=JPRB)::RZSTPO
REAL (KIND=JPRB)::RZMESO
REAL (KIND=JPRB)::RZMES2
REAL (KIND=JPRB)::RZMEPO
REAL (KIND=JPRB)::RZABOV
REAL (KIND=JPRB)::RTSUR
REAL (KIND=JPRB)::RTTROP
REAL (KIND=JPRB)::RTSTRA
REAL (KIND=JPRB)::RTSTR2
REAL (KIND=JPRB)::RTSTPO
REAL (KIND=JPRB)::RTMESO
REAL (KIND=JPRB)::RTMES2
REAL (KIND=JPRB)::RTMEPO
REAL (KIND=JPRB)::RTABOV
REAL (KIND=JPRB)::RPTROP
REAL (KIND=JPRB)::RPSTRA
REAL (KIND=JPRB)::RPSTR2
REAL (KIND=JPRB)::RPSTPO
REAL (KIND=JPRB)::RPMESO
REAL (KIND=JPRB)::RPMES2
REAL (KIND=JPRB)::RPMEPO
REAL (KIND=JPRB)::RPABOV
REAL (KIND=JPRB)::HEXTRAP
INTEGER (KIND=JPIM)::NLEXTRAP
REAL (KIND=JPRB)::VZTROP
REAL (KIND=JPRB)::VZSTRA
REAL (KIND=JPRB)::VZSTR2
REAL (KIND=JPRB)::VZSTPO
REAL (KIND=JPRB)::VZMESO
REAL (KIND=JPRB)::VZMES2
REAL (KIND=JPRB)::VZMEPO
REAL (KIND=JPRB)::VZABOV
REAL (KIND=JPRB)::VTSUR
REAL (KIND=JPRB)::VTTROP
REAL (KIND=JPRB)::VTSTRA
REAL (KIND=JPRB)::VTSTR2
REAL (KIND=JPRB)::VTSTPO
REAL (KIND=JPRB)::VTMESO
REAL (KIND=JPRB)::VTMES2
REAL (KIND=JPRB)::VTMEPO
REAL (KIND=JPRB)::VTABOV
REAL (KIND=JPRB)::VPTROP
REAL (KIND=JPRB)::VPSTRA
REAL (KIND=JPRB)::VPSTR2
REAL (KIND=JPRB)::VPSTPO
REAL (KIND=JPRB)::VPMESO
REAL (KIND=JPRB)::VPMES2
REAL (KIND=JPRB)::VPMEPO
REAL (KIND=JPRB)::VPABOV
REAL (KIND=JPRB)::VDTDZ1
REAL (KIND=JPRB)::VDTDZ2
REAL (KIND=JPRB)::VDTDZ3
REAL (KIND=JPRB)::VDTDZ4
REAL (KIND=JPRB)::VDTDZ5
REAL (KIND=JPRB)::VDTDZ6
REAL (KIND=JPRB)::VDTDZ7
REAL (KIND=JPRB)::VDTDZ8
REAL (KIND=JPRB)::VDTDZ9

TYPE TSTA
  REAL (KIND=JPRB), ALLOCATABLE::STPREH (:)
  REAL (KIND=JPRB), ALLOCATABLE::STPRE (:)
  REAL (KIND=JPRB), ALLOCATABLE::STPHI (:)
  REAL (KIND=JPRB), ALLOCATABLE::STTEM (:)
  REAL (KIND=JPRB), ALLOCATABLE::STDEN (:)
  REAL (KIND=JPRB), ALLOCATABLE::STZ (:)
  REAL (KIND=JPRB), ALLOCATABLE::SVETAH (:)
  REAL (KIND=JPRB), ALLOCATABLE::SVETAF (:)
  
  
  
ENDTYPE TSTA

CONTAINS


ENDMODULE YOMSTA
