MODULE YOMSPSDT
USE PARKIND1,ONLY:JPIM, JPRB
USE SPECTRAL_ARP_MOD,ONLY:SPECTRAL_ARP
USE GRIDPOINT_FIELDS_MIX,ONLY:GRIDPOINT_FIELD

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::NMAXSCALES_SDT=5
INTEGER (KIND=JPIM), PARAMETER::NMAXINDPAT_SDT=6
INTEGER (KIND=JPIM), PARAMETER::NWRMAX_SDT=20

TYPE TSPPT_CONFIG
  LOGICAL::LSPSDT=.FALSE.
  LOGICAL::LRADCLR_SDT
  LOGICAL::LSATADJ_SDT
  LOGICAL::LSPPT1
  LOGICAL::LSPPTGFIX
  LOGICAL::LCLIP_SPEC_SDT
  LOGICAL::LCLIP_GRID_SDT
  LOGICAL::LQPERTLIMIT2
  LOGICAL::LTAPER_BL0
  LOGICAL, DIMENSION (NMAXINDPAT_SDT)::LTAPER_BLI
  LOGICAL::LTAPER_ST0
  LOGICAL, DIMENSION (NMAXINDPAT_SDT)::LTAPER_STI
  LOGICAL::LUSESETRAN_SDT=.TRUE.
  LOGICAL::LRESETSEED_SDT=.FALSE.
  LOGICAL::LABSTIMSEED_SDT
  LOGICAL::LWRITE_ARP
  LOGICAL::LRDPATINIT_SDT=.FALSE.
  LOGICAL::LWRPATTRUN_SDT=.FALSE.
  LOGICAL, POINTER::LACTIVEQ_SDT=>NULL ()
  LOGICAL, POINTER::LACTIVEO_SDT=>NULL ()
  INTEGER (KIND=JPIM)::NSCALES_SDT=1
  INTEGER (KIND=JPIM)::NPATFR=1
  INTEGER (KIND=JPIM)::RESETSEEDFRQ_SDT
  INTEGER (KIND=JPIM)::NWRPATTRUN_SDT
  INTEGER (KIND=JPIM), DIMENSION (NWRMAX_SDT)::NHOUR_PATTRUN
  INTEGER (KIND=JPIM), DIMENSION (NWRMAX_SDT)::NSTEP_PATTRUN
  INTEGER (KIND=JPIM)::NCLIP_KIND_SDT
  INTEGER (KIND=JPIM)::NQSAT_SDT=3
  INTEGER (KIND=JPIM), DIMENSION (4000)::NWN_TESTSPEC_SDT
  INTEGER (KIND=JPIM)::NWAV_TESTSPEC_SDT
  REAL (KIND=JPRB)::SDEV_SDT (NMAXSCALES_SDT, NMAXINDPAT_SDT)
  REAL (KIND=JPRB), DIMENSION (NMAXSCALES_SDT)::TAU_SDT
  REAL (KIND=JPRB), DIMENSION (NMAXSCALES_SDT)::XLCOR_SDT
  REAL (KIND=JPRB), DIMENSION (NMAXSCALES_SDT)::XWC_KAPPA_T
  REAL (KIND=JPRB)::XCLIPM_SDT (NMAXINDPAT_SDT)
  REAL (KIND=JPRB)::XCLIP_RATIO_SDT (NMAXINDPAT_SDT)
  REAL (KIND=JPRB)::XMEANRED_THICKNESS_SDT
  REAL (KIND=JPRB)::SDEVTOT_SDT (NMAXINDPAT_SDT)
  REAL (KIND=JPRB)::XSIGMATOP
  REAL (KIND=JPRB)::XSIGMABOT
  REAL (KIND=JPRB)::XPRESSTOP_ST0
  REAL (KIND=JPRB)::XPRESSBOT_ST0
  REAL (KIND=JPRB)::XTAPER3, XTAPER2, XTAPER1, XTAPER0
  REAL (KIND=JPRB)::XTAPER3_ST0, XTAPER2_ST0, XTAPER1_ST0, XTAPER0_ST0
  REAL (KIND=JPRB)::XSPPTGFIXRLX
  CHARACTER (LEN=128)::CSPEC_SHAPE_SDT='WeaverCourtier'
  CHARACTER (LEN=256), DIMENSION (:), POINTER::CIPATINIT_SDT=>NULL ()
  CHARACTER (LEN=256), DIMENSION (:), POINTER::COPATTRUN_SDT=>NULL ()
  CHARACTER (LEN=256), DIMENSION (:), POINTER::COPATSP_SDT=>NULL ()
  CHARACTER (LEN=256), DIMENSION (:), POINTER::COPATGP_SDT=>NULL ()
ENDTYPE TSPPT_CONFIG


TYPE TSPPT_DATA
  INTEGER (KIND=JPIM), DIMENSION (NMAXINDPAT_SDT)::MPSDT
  INTEGER (KIND=JPIM)::N2D
  INTEGER (KIND=JPIM), DIMENSION (:), POINTER::NSEED_SDT=>NULL ()
  TYPE (SPECTRAL_ARP), DIMENSION (:), POINTER::YSPSDT_AR1=>NULL ()
  TYPE (GRIDPOINT_FIELD), DIMENSION (:), POINTER::YGPSDT=>NULL ()
  TYPE (GRIDPOINT_FIELD), DIMENSION (:), POINTER::YGPSDT0=>NULL ()
  TYPE (GRIDPOINT_FIELD), DIMENSION (:), POINTER::YGPSDT1=>NULL ()
ENDTYPE TSPPT_DATA

ENDMODULE YOMSPSDT
