MODULE YOMSRFTLAD
USE PARKIND1,ONLY:JPRB, JPIM

IMPLICIT NONE

SAVE

TYPE::TSRFTLAD
  REAL (KIND=JPRB), ALLOCATABLE::GPTSKIN0 (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GPTSKIN9 (:,:,:)
  INTEGER (KIND=JPIM)::NGSKIN
  LOGICAL::LREGSF
  
ENDTYPE TSRFTLAD

CONTAINS

ENDMODULE YOMSRFTLAD
