MODULE YOMSNU
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE
REAL (KIND=JPRB), ALLOCATABLE::XPNUDG (:)
REAL (KIND=JPRB), ALLOCATABLE::TNUDTE (:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::TNUDSH (:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::TNUDDI (:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::TNUDVO (:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::TNUDSV (:,:,:,:)
REAL (KIND=JPRB), ALLOCATABLE::TNUDLP (:,:)
REAL (KIND=JPRB)::XWNUDG
ENDMODULE YOMSNU
