MODULE YOMSIMPHL
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE TSIMPHL
  LOGICAL::LSIMPH
  LOGICAL::LTRAJPS
  LOGICAL::LTRAJPST
  LOGICAL::LSMOOTHD
  LOGICAL::LSMOOTHA
  LOGICAL::LSMOOTHB
  LOGICAL::LCVRASP
  LOGICAL::LGWDSP
  LOGICAL::LRAYSP
  LOGICAL::LSTRASP
  LOGICAL::LVDIFSP
  LOGICAL::LVDIFSPNL
  LOGICAL::LRRMESSP
  LOGICAL::LCLOUDS
  LOGICAL::LGWDSPNL
  LOGICAL::LSTRASPN
  LOGICAL::LPROCLDTL
  LOGICAL::LMELTTL
  LOGICAL::LMELTNL
  LOGICAL::LMICROTL
  LOGICAL::LTRAJRAIN
  LOGICAL::LTRAJCOND
  LOGICAL::LNEBCVPPKF
  LOGICAL::LCOLLECTL
  LOGICAL::LEVAPTL
  LOGICAL::LSMOOTHEVP
  LOGICAL::LIGELREPRO
  LOGICAL::LCVRASBM, LCONSENTH, LAPPROXCONV
  REAL (KIND=JPRB)::RHCRIT1S, RHCRIT2S, TADJ, RMINEVP, DELTAH
  REAL (KIND=JPRB)::RMODULQCPROG
ENDTYPE TSIMPHL

ENDMODULE YOMSIMPHL
