MODULE YOMSDDH
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE

TYPE::TSDDH
  INTEGER (KIND=JPIM)::NHDQLNVA
  INTEGER (KIND=JPIM)::NHDQLNTD
  INTEGER (KIND=JPIM)::NHDQLNFD
  INTEGER (KIND=JPIM)::NHDQLNFP
  INTEGER (KIND=JPIM)::NHDQLNTP
  INTEGER (KIND=JPIM)::NHDPASVA
  INTEGER (KIND=JPIM)::NHDPASTD
  INTEGER (KIND=JPIM)::NHDPASFD
  INTEGER (KIND=JPIM)::NHDPASFP
  INTEGER (KIND=JPIM)::NHDPASTP
  LOGICAL::LHDQLN
  LOGICAL::LHDPAS
ENDTYPE TSDDH

ENDMODULE YOMSDDH
