MODULE YOMSLPHY
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE

TYPE::TSLPHY
  REAL (KIND=JPRB), ALLOCATABLE::RSLWX (:)
  INTEGER (KIND=JPIM)::NVTEND, NVTEND_VD
  REAL (KIND=JPRB), ALLOCATABLE::SAVTEND (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SAVTEND5 (:,:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::SAVTEND_VD (:,:,:,:)
  INTEGER (KIND=JPIM)::MU_SAVTEND, MV_SAVTEND, MT_SAVTEND
  INTEGER (KIND=JPIM)::MUS_SAVTEND, MVS_SAVTEND, MTS_SAVTEND, MQS_SAVTEND, MSPPTCLEAR_SAVTEND
  INTEGER (KIND=JPIM)::MQ_SAVTEND, M_RAD_SW, M_RAD_LW, M_CONV_MFD, M_CONV_MFU, M_CONV_LUDELI (4)
  
ENDTYPE TSLPHY

CONTAINS

ENDMODULE YOMSLPHY
