MODULE YOMSLREP
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE::TSLREP
  INTEGER (KIND=JPIM)::NGPTOTAD
  INTEGER (KIND=JPIM), ALLOCATABLE::NADMAP (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NADCORE (:)
  LOGICAL, ALLOCATABLE::LADCORE (:)
  REAL (KIND=JPRB), ALLOCATABLE::RSASIGN (:,:)
  
ENDTYPE TSLREP

CONTAINS

ENDMODULE YOMSLREP
