MODULE YOMTRC
USE PARKIND1,ONLY:JPRB
USE FIELD_MODULE,ONLY:FIELD_2RB, FIELD_3RB, FIELD_4RB

IMPLICIT NONE

SAVE

TYPE::TTRC
  CLASS (FIELD_4RB), POINTER::F_GDEOSI=>NULL ()
  REAL (KIND=JPRB), POINTER::GDEOSI (:,:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GDEOTI=>NULL ()
  REAL (KIND=JPRB), POINTER::GDEOTI (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GDEOTI2=>NULL ()
  REAL (KIND=JPRB), POINTER::GDEOTI2 (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GEOLT=>NULL ()
  REAL (KIND=JPRB), POINTER::GEOLT (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GEOXT=>NULL ()
  REAL (KIND=JPRB), POINTER::GEOXT (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GFLUXC=>NULL ()
  REAL (KIND=JPRB), POINTER::GFLUXC (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GMIXP=>NULL ()
  REAL (KIND=JPRB), POINTER::GMIXP (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GMU0=>NULL ()
  REAL (KIND=JPRB), POINTER::GMU0 (:,:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GMU0_MAX=>NULL ()
  REAL (KIND=JPRB), POINTER::GMU0_MAX (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GMU0_MIN=>NULL ()
  REAL (KIND=JPRB), POINTER::GMU0_MIN (:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GRPROX=>NULL ()
  REAL (KIND=JPRB), POINTER::GRPROX (:,:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_GRSURF=>NULL ()
  REAL (KIND=JPRB), POINTER::GRSURF (:)=>NULL ()
  CLASS (FIELD_4RB), POINTER::F_GUEOSI=>NULL ()
  REAL (KIND=JPRB), POINTER::GUEOSI (:,:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GUEOTI=>NULL ()
  REAL (KIND=JPRB), POINTER::GUEOTI (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_GUEOTI2=>NULL ()
  REAL (KIND=JPRB), POINTER::GUEOTI2 (:,:)=>NULL ()
  
  
  
  
ENDTYPE TTRC

REAL (KIND=JPRB), PRIVATE, SAVE, TARGET::ZDUM1 (1), ZDUM2 (1, 1), ZDUM3 (1, 1, 1)
CONTAINS




ENDMODULE YOMTRC
