MODULE YOMTDDH
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE::TTDDH
  REAL (KIND=JPRB), ALLOCATABLE::HDCVB0 (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::HDCVB1 (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::HDCS0 (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::HDCS1 (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::PDDHFSVI (:)
  CHARACTER (LEN=128), ALLOCATABLE::CFLDNAMES3D (:)
  CHARACTER (LEN=1), ALLOCATABLE::CFLDTYPES3D (:)
  CHARACTER (LEN=128), ALLOCATABLE::CFLDNAMES2D (:)
  CHARACTER (LEN=1), ALLOCATABLE::CFLDTYPES2D (:)
ENDTYPE TTDDH

ENDMODULE YOMTDDH
