
MODULE YOMTAG
USE PARKIND1,ONLY:JPIM

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::MTAGLM=600
INTEGER (KIND=JPIM), PARAMETER::MTAGMS=1000
INTEGER (KIND=JPIM), PARAMETER::MTAGSM=1200
INTEGER (KIND=JPIM), PARAMETER::MTAGSPNO=2200
INTEGER (KIND=JPIM), PARAMETER::MTAGSLAG=2400
INTEGER (KIND=JPIM), PARAMETER::MTAGRAD=2800
INTEGER (KIND=JPIM), PARAMETER::MTAGPART=3600
INTEGER (KIND=JPIM), PARAMETER::MTAGCAIN=4200
INTEGER (KIND=JPIM), PARAMETER::MTAGCOST=4400
INTEGER (KIND=JPIM), PARAMETER::MTAGGSUM=4600
INTEGER (KIND=JPIM), PARAMETER::MTAGFCE=5000
INTEGER (KIND=JPIM), PARAMETER::MTAGPE=5200
INTEGER (KIND=JPIM), PARAMETER::MTAGGPNORM=5400
INTEGER (KIND=JPIM), PARAMETER::MTAGBRPR=5600
INTEGER (KIND=JPIM), PARAMETER::MTAGLCZ=6000
INTEGER (KIND=JPIM), PARAMETER::MTAGFREQ=6400
INTEGER (KIND=JPIM), PARAMETER::MTAGEIGMD=6700
INTEGER (KIND=JPIM), PARAMETER::MTAGKE=6800
INTEGER (KIND=JPIM), PARAMETER::MTAGSPNORM=7000
INTEGER (KIND=JPIM), PARAMETER::MTAGWAMNORM=7200
INTEGER (KIND=JPIM), PARAMETER::MTAGDISTSP=10000
INTEGER (KIND=JPIM), PARAMETER::MTAGDISTGP=11000
INTEGER (KIND=JPIM), PARAMETER::MTAGDISTGP_DEP=12000
INTEGER (KIND=JPIM), PARAMETER::MTAGGLOBSI=22001
INTEGER (KIND=JPIM), PARAMETER::MTAGGOMMP=23000
INTEGER (KIND=JPIM), PARAMETER::MTAGGOMMPAD=23001
INTEGER (KIND=JPIM), PARAMETER::MTAGDDHRES=24000
INTEGER (KIND=JPIM), PARAMETER::MTAGSIG=26000
INTEGER (KIND=JPIM), PARAMETER::MTAGDDH1=27000
INTEGER (KIND=JPIM), PARAMETER::MTAGDDH2=28000
INTEGER (KIND=JPIM), PARAMETER::MTAGDDH3=29000
INTEGER (KIND=JPIM), PARAMETER::MTAGDDH4=30000
INTEGER (KIND=JPIM), PARAMETER::MTAGGETV=30200
INTEGER (KIND=JPIM), PARAMETER::MT_DISTRIBUTED_VECTOR=32000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRFU=40000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRGRIDA=42000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRGRIDALL=43000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRGRIDUA=44000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRSFX=45000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRSFXS=45500
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRSPECA_GP=46000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRXFU=47000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRSPECA=48000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_FP2SX1FA=49000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_FP2SX2=50000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRHFP=51000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRSFP=52000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_SUSPECA=52000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_SUGRIDUA=53000
INTEGER (KIND=JPIM), PARAMETER::MTAG_MFIO_WRSPECSPA=54000
ENDMODULE YOMTAG
