MODULE YOMTOPH
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TTOPH
  REAL (KIND=JPRB), ALLOCATABLE::RMESOU (:)
  REAL (KIND=JPRB), ALLOCATABLE::RMESOT (:)
  REAL (KIND=JPRB), ALLOCATABLE::RMESOQ (:)
  REAL (KIND=JPRB), ALLOCATABLE::RUREL (:)
  REAL (KIND=JPRB), ALLOCATABLE::RVREL (:)
  REAL (KIND=JPRB), ALLOCATABLE::RTREL (:)
  REAL (KIND=JPRB), ALLOCATABLE::RQREL (:)
  REAL (KIND=JPRB)::RFMESOQ
  INTEGER (KIND=JPIM)::NTQSAT
  INTEGER (KIND=JPIM)::NTDIFU
  INTEGER (KIND=JPIM)::NTCOEF
  INTEGER (KIND=JPIM)::NTDRAG
  INTEGER (KIND=JPIM)::NTCVIM
  INTEGER (KIND=JPIM)::NT850
  INTEGER (KIND=JPIM)::NT950
  INTEGER (KIND=JPIM)::NTPLUI
  INTEGER (KIND=JPIM)::NTRADI
  INTEGER (KIND=JPIM)::NTNEBU
  INTEGER (KIND=JPIM)::NTOZON
  INTEGER (KIND=JPIM)::NTDRME
  INTEGER (KIND=JPIM)::NTCOET
  INTEGER (KIND=JPIM)::NTAJUC
  INTEGER (KIND=JPIM)::NTRELAXT
  INTEGER (KIND=JPIM)::NTRELAXQ
  INTEGER (KIND=JPIM)::NTRELAXU
  INTEGER (KIND=JPIM)::CHEM_HPSC_NTOP
  INTEGER (KIND=JPIM)::CHEM_HPSC_NBOT
  INTEGER (KIND=JPIM)::CHEM_HOXF_NBOT
  INTEGER (KIND=JPIM)::CHEM_ELEM_NTOP
  INTEGER (KIND=JPIM)::CHEM_RELA_NIV
  INTEGER (KIND=JPIM)::CHEM_NO_NIV
  REAL (KIND=JPRB)::ETQSAT
  REAL (KIND=JPRB)::ETDIFU
  REAL (KIND=JPRB)::ETCOEF
  REAL (KIND=JPRB)::ETDRAG
  REAL (KIND=JPRB)::ETCVIM
  REAL (KIND=JPRB)::ET850
  REAL (KIND=JPRB)::ET950
  REAL (KIND=JPRB)::ETPLUI
  REAL (KIND=JPRB)::ETRADI
  REAL (KIND=JPRB)::ETNEBU
  REAL (KIND=JPRB)::ETOZON
  REAL (KIND=JPRB)::ETDRME
  REAL (KIND=JPRB)::ETCOET
  REAL (KIND=JPRB)::ETAJUC
  REAL (KIND=JPRB)::ETRELAXT
  REAL (KIND=JPRB)::ETRELAXQ
  REAL (KIND=JPRB)::ETRELAXU
  REAL (KIND=JPRB)::XDRMUK
  REAL (KIND=JPRB)::XDRMUX
  REAL (KIND=JPRB)::XDRMUP
  REAL (KIND=JPRB)::XDRMTK
  REAL (KIND=JPRB)::XDRMTX
  REAL (KIND=JPRB)::XDRMTP
  REAL (KIND=JPRB)::XDRMQK
  REAL (KIND=JPRB)::XDRMQP
  REAL (KIND=JPRB)::XDRMQX
  REAL (KIND=JPRB)::RCLX
  REAL (KIND=JPRB)::TPSCLIM
  REAL (KIND=JPRB)::ETELEM
  REAL (KIND=JPRB)::ETRELA
  REAL (KIND=JPRB)::ETPSCT
  REAL (KIND=JPRB)::ETPSCB
  REAL (KIND=JPRB)::ETHOXF
  REAL (KIND=JPRB)::ETCHEMNO
ENDTYPE TTOPH

ENDMODULE YOMTOPH
