MODULE YOMVDOZ
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE TVDOZ
  REAL (KIND=JPRB)::VDHJS (99)
  REAL (KIND=JPRB)::VDHJH (99)
  REAL (KIND=JPRB)::VDHNS (99)
  REAL (KIND=JPRB)::VDHNH (99)
  REAL (KIND=JPRB)::VDPJS (99)
  REAL (KIND=JPRB)::VDPJH (99)
  REAL (KIND=JPRB)::VDPNS (99)
  REAL (KIND=JPRB)::VDPNH (99)
  REAL (KIND=JPRB)::VDEJS (99)
  REAL (KIND=JPRB)::VDEJH (99)
  REAL (KIND=JPRB)::VDENS (99)
  REAL (KIND=JPRB)::VDENH (99)
  REAL (KIND=JPRB)::VDAJS (99)
  REAL (KIND=JPRB)::VDAJH (99)
  REAL (KIND=JPRB)::VDANS (99)
  REAL (KIND=JPRB)::VDANH (99)
  REAL (KIND=JPRB)::VDNJS (99)
  REAL (KIND=JPRB)::VDNJH (99)
  REAL (KIND=JPRB)::VDNNS (99)
  REAL (KIND=JPRB)::VDNNH (99)
  REAL (KIND=JPRB)::VOZNJ
  REAL (KIND=JPRB)::VOZHS
  LOGICAL::LRDIFOZ
  LOGICAL::LRDEPOZ
ENDTYPE TVDOZ

ENDMODULE YOMVDOZ
