MODULE YOMVSLETA
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TVSLETA
  REAL (KIND=JPRB), ALLOCATABLE::VCUICO (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::VCUICOH (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::VSLD (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::VSLDH (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::VSLDW (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::VSLDWH (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::VSLVF (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::VSLVFH (:,:,:)
  REAL (KIND=JPRB), ALLOCATABLE::GAMMA_WENO (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::VRDETAR (:)
  INTEGER (KIND=JPIM)::NRLEVX=1
  REAL (KIND=JPRB)::VRLEVX=1.0_JPRB
  INTEGER (KIND=JPIM), ALLOCATABLE::NVAUTF (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::NVAUTH (:)
ENDTYPE TVSLETA

ENDMODULE YOMVSLETA
