MODULE YOMVERT
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE YOMCVER,ONLY:TCVER

IMPLICIT NONE

SAVE
REAL (KIND=JPRB)::VP00
REAL (KIND=JPRB)::TOPPRES

TYPE TVAB
  REAL (KIND=JPRB), ALLOCATABLE::VALH (:)
  REAL (KIND=JPRB), ALLOCATABLE::VBH (:)
  REAL (KIND=JPRB), ALLOCATABLE::VAH (:)
  REAL (KIND=JPRB), ALLOCATABLE::VC (:)
  REAL (KIND=JPRB), ALLOCATABLE::VAF (:)
  REAL (KIND=JPRB), ALLOCATABLE::VBF (:)
  REAL (KIND=JPRB), ALLOCATABLE::VDELA (:)
  REAL (KIND=JPRB), ALLOCATABLE::VDELB (:)
  REAL (KIND=JPRB), ALLOCATABLE::VRATH (:)
  REAL (KIND=JPRB), ALLOCATABLE::VRATF (:)
ENDTYPE TVAB


TYPE TVETA
  REAL (KIND=JPRB), ALLOCATABLE::VETAH (:)
  REAL (KIND=JPRB), ALLOCATABLE::VFE_ETAH (:)
  REAL (KIND=JPRB), ALLOCATABLE::VETAF (:)
  REAL (KIND=JPRB), ALLOCATABLE::VFE_ETAF (:)
  REAL (KIND=JPRB), ALLOCATABLE::VFE_RDETAH (:)
  REAL (KIND=JPRB), ALLOCATABLE::VDETA_RATIO (:)
  REAL (KIND=JPRB), ALLOCATABLE::VRDETAH (:)
  REAL (KIND=JPRB), ALLOCATABLE::VWEI (:)
  REAL (KIND=JPRB), ALLOCATABLE::VETA_H (:)
  REAL (KIND=JPRB), ALLOCATABLE::VETA_LAITRIQM3D (:)
ENDTYPE TVETA


TYPE TVFE
  REAL (KIND=JPRB), ALLOCATABLE::VFE_KNOT (:)
  REAL (KIND=JPRD), ALLOCATABLE::RINTE (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RINTBF00 (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RINTBF11 (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDERI (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDERB (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDERBF00 (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDERBF01 (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDERBF10 (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDERBF11 (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDERBH00 (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDERBH01 (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDDERI (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDDERBF01 (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RINTGW (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RDERGW (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RINTG (:,:)
  REAL (KIND=JPRD), ALLOCATABLE::RINTC (:)
ENDTYPE TVFE


TYPE TVERTICAL_GEOM
  LOGICAL::LNONHYD_GEOM
  TYPE (TVAB)::YRVAB
  TYPE (TVETA)::YRVETA
  TYPE (TVFE)::YRVFE
  TYPE (TCVER)::YRCVER
ENDTYPE TVERTICAL_GEOM

CONTAINS
ENDMODULE YOMVERT
