MODULE YOMVSPLIP
USE PARKIND1,ONLY:JPRB

IMPLICIT NONE

SAVE

TYPE TVSPLIP
  REAL (KIND=JPRB), ALLOCATABLE::RVSPTRI (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::RVSPC (:)
  REAL (KIND=JPRB), ALLOCATABLE::RFVV (:,:,:)
ENDTYPE TVSPLIP

ENDMODULE YOMVSPLIP
