MODULE YOMVAR
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::JPNRFT=40
INTEGER (KIND=JPIM), PROTECTED::NREFTS (0:JPNRFT)
INTEGER (KIND=JPIM), PROTECTED::NANATS (0:JPNRFT)
INTEGER (KIND=JPIM), PROTECTED::NGRATS (0:JPNRFT)
CHARACTER (LEN=80), PROTECTED::CFNSIGB
CHARACTER (LEN=80), PROTECTED::CFNSIGA
CHARACTER (LEN=80), PROTECTED::CFNSIGF
CHARACTER (LEN=80), PROTECTED::CFNPCV
INTEGER (KIND=JPIM), PROTECTED::NITER
INTEGER (KIND=JPIM), PROTECTED::NITER_MIN
INTEGER (KIND=JPIM), PROTECTED::NSIMU
INTEGER (KIND=JPIM)::NINFRA
INTEGER (KIND=JPIM), PROTECTED::NMIMP
INTEGER (KIND=JPIM)::NDIAG
INTEGER (KIND=JPIM), PROTECTED::NFRREF
INTEGER (KIND=JPIM), PROTECTED::NFRANA
INTEGER (KIND=JPIM), PROTECTED::NFRGRA
INTEGER (KIND=JPIM), PROTECTED::NSIM4DL
INTEGER (KIND=JPIM)::MSIME
INTEGER (KIND=JPIM)::NOBSCURE_NUMBER
INTEGER (KIND=JPIM), PROTECTED::MUPTRA
INTEGER (KIND=JPIM)::NPCVECS
INTEGER (KIND=JPIM)::NBGVECS
INTEGER (KIND=JPIM)::NHEVECS
INTEGER (KIND=JPIM)::NSSBGV_COUNT
INTEGER (KIND=JPIM)::NSSHEV_COUNT
INTEGER (KIND=JPIM)::MCGLVEC
INTEGER (KIND=JPIM)::MBGVEC
INTEGER (KIND=JPIM)::NOANEF
INTEGER (KIND=JPIM), PROTECTED::NFGFCLEN
INTEGER (KIND=JPIM), PROTECTED::NBGTRUNC
INTEGER (KIND=JPIM), PROTECTED::NITERGCV
INTEGER (KIND=JPIM), PROTECTED::NWRIEVEC
INTEGER (KIND=JPIM), PROTECTED::N_DIAGS_CONVERGENCE
INTEGER (KIND=JPIM), PROTECTED::N_DIAGS_EIGENVECS
INTEGER (KIND=JPIM), PROTECTED::DATE_TIME_WINDOW_END
REAL (KIND=JPRB), PROTECTED::RDX
REAL (KIND=JPRB), PROTECTED::ALPHAG
REAL (KIND=JPRB), PROTECTED::ALPHAV
REAL (KIND=JPRB), PROTECTED::RXMIN
REAL (KIND=JPRB), PROTECTED::EVBCGL
REAL (KIND=JPRB), PROTECTED::RCVGE
REAL (KIND=JPRB), PROTECTED::R_NORM_REDUCTION_ABORT_LEVEL
REAL (KIND=JPRB)::GCVJO
REAL (KIND=JPRB), PROTECTED::ZEPSNEG
REAL (KIND=JPRB), PROTECTED::R_MAX_CNUM_PC
REAL (KIND=JPRB), PROTECTED::RTOL_CHECK_GRADIENT
REAL (KIND=JPRB), PROTECTED::FILTERFACTOR
REAL (KIND=JPRB), PROTECTED::FILTEREXPO
REAL (KIND=JPRB), PROTECTED::FILTERRESOL
REAL (KIND=JPRB), PROTECTED::CTOPBGE
REAL (KIND=JPRB), PROTECTED::CAMTBGE
REAL (KIND=JPRB), PROTECTED::RCOEFCO2
REAL (KIND=JPRB), PROTECTED::RCOEFCH4
REAL (KIND=JPRB), PROTECTED::DELTA
LOGICAL::LFCOBS
LOGICAL, PROTECTED::LFCOBSTEST
LOGICAL, PROTECTED::LTEST
LOGICAL, PROTECTED::LREPRO4DVAR
LOGICAL, PROTECTED::LSLADREP
LOGICAL, PROTECTED::LVECADIN
LOGICAL::LTRREF
LOGICAL, PROTECTED::LREFINC
LOGICAL, PROTECTED::LZOWA
LOGICAL::LJC
LOGICAL, PROTECTED::LINITCV
LOGICAL, PROTECTED::LMODERR
LOGICAL, PROTECTED::LVARBC
LOGICAL, PROTECTED::LPERTMRPAS
LOGICAL::LTWANA
LOGICAL::LTWGRA
LOGICAL::LTWLCZ
LOGICAL, PROTECTED::LAVCGL
LOGICAL::LMPCGL
LOGICAL::LTWINC
LOGICAL, PROTECTED::LGRASCAL
LOGICAL, PROTECTED::LSKIPMIN
LOGICAL, PROTECTED::L_ABS_CONVERGENCE
LOGICAL, PROTECTED::L_INFO_CONVERGENCE
LOGICAL::LTWBGV
LOGICAL::LTWCGL
LOGICAL, PROTECTED::LWRIBVEC
LOGICAL, PROTECTED::LWRIBVEC_FULL
LOGICAL, PROTECTED::LREABVEC
LOGICAL, PROTECTED::LWRIEVEC
LOGICAL, PROTECTED::LEVECCNTL
LOGICAL, PROTECTED::LEVECGRIB
LOGICAL, PROTECTED::LWRISIGB
LOGICAL, PROTECTED::LWRISIGA
LOGICAL, PROTECTED::LWRISIGF
LOGICAL, PROTECTED::LBGTRUNC
LOGICAL, PROTECTED::LBGOBS
LOGICAL, PROTECTED::LBGM
LOGICAL, PROTECTED::LANOBS
LOGICAL::L_CHECK_CONVERGENCE
LOGICAL, PROTECTED::L_CHECK_GRADIENT
LOGICAL::LJCDFI
LOGICAL, PROTECTED::LUSEJCDFI
LOGICAL, PROTECTED::LTOVSCV
LOGICAL, PROTECTED::LTOVSREP
LOGICAL, PROTECTED::LGCV
LOGICAL::LGCVJO
LOGICAL, PROTECTED::LWREINI
LOGICAL, PROTECTED::LN1CG1
LOGICAL, PROTECTED::LCONGRAD
LOGICAL::L3DFGAT
LOGICAL, PROTECTED::LFDBERR
LOGICAL, PROTECTED::LAMV_REASSIGN_PASSIVE
LOGICAL, PROTECTED::LREO3_BCOR
LOGICAL, PROTECTED::LCH4_BCOR
LOGICAL, PROTECTED::L_INFO_CONTENT
LOGICAL, PROTECTED::LCLDSINK
LOGICAL, PROTECTED::L_GUESS_RUNTIME
LOGICAL, PROTECTED::LPROPTL
LOGICAL, PROTECTED::LAEOLUSAMD
LOGICAL::LBACKGE
LOGICAL, PROTECTED::LBACKGECV
LOGICAL, PROTECTED::LBACKGERENORM
LOGICAL, PROTECTED::LUSEWAVRENORM
LOGICAL, PROTECTED::LCONSTANTZFCE
LOGICAL, PROTECTED::LWRISB_VPROF
LOGICAL::LDIAG_LCT
LOGICAL, PROTECTED::LFAMEMBERS
LOGICAL, PROTECTED::LTOY42
LOGICAL, PROTECTED::LSUSPQLIM
LOGICAL, PROTECTED::LSPINT
LOGICAL, PROTECTED::LJBIMPACT=.FALSE.
LOGICAL, PROTECTED::LJCIMPACT=.FALSE.
LOGICAL::LMONITOR_OBSTATFC=.FALSE.
LOGICAL, PROTECTED::LENDA=.FALSE.
LOGICAL, PROTECTED::LBGPERT=.FALSE.
LOGICAL, PROTECTED::LCHRESINCR
LOGICAL, PROTECTED::LINC_TOVSCV
INTEGER (KIND=JPIM), PROTECTED::NUPTRA_RANGE=0
INTEGER (KIND=JPIM), PROTECTED::N_INFO_CONTENT_METHOD
INTEGER (KIND=JPIM), PROTECTED::N_INFO_CONTENT_SEED
INTEGER (KIND=JPIM), PROTECTED::N1IMP
INTEGER (KIND=JPIM), PROTECTED::NPRECO
INTEGER (KIND=JPIM), PROTECTED::NBFGSB
INTEGER (KIND=JPIM), PROTECTED::NSELECT
INTEGER (KIND=JPIM), PROTECTED::NITER_GUESS_RUNTIME
INTEGER (KIND=JPIM), PROTECTED::NFREQ_GUESS_RUNTIME
INTEGER (KIND=JPIM), PROTECTED::NMEM_GUESS_RUNTIME
ENDMODULE YOMVAR
