MODULE YOMWINDFARM
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

SAVE

TYPE TWFMETA
  INTEGER (KIND=JPIM)::N_WT
  INTEGER (KIND=JPIM), ALLOCATABLE::MWT_TYPE (:), MGPBLK_WT (:), MPROMA_WT (:)
  REAL (KIND=JPRB), ALLOCATABLE::WTT_HUBHEIGHT (:)
  REAL (KIND=JPRB), ALLOCATABLE::WTT_RADIUS (:)
  INTEGER (KIND=JPIM)::MAX_WT_PER_GP
  INTEGER (KIND=JPIM), ALLOCATABLE::N_WT_PER_GP (:,:)
  INTEGER (KIND=JPIM), ALLOCATABLE::WT_PER_GP (:,:,:)
  INTEGER (KIND=JPIM)::N_WT_GLOB
  INTEGER (KIND=JPIM), ALLOCATABLE::MWT_TYPE_GLOB (:)
  REAL (KIND=JPRB), ALLOCATABLE::WT_LAT_GLOB (:), WT_LON_GLOB (:)
  REAL (KIND=JPRB), ALLOCATABLE::WTT_HUBHEIGHT_GLOB (:)
  REAL (KIND=JPRB), ALLOCATABLE::WTT_RADIUS_GLOB (:)
  INTEGER (KIND=JPIM)::N_WT_TYPES, MAX_WT_TYPE
  INTEGER (KIND=JPIM), ALLOCATABLE::N_WTT_WSPEEDS (:)
  REAL (KIND=JPRB), ALLOCATABLE::WTT_CUTIN (:)
  REAL (KIND=JPRB), ALLOCATABLE::WTT_CUTOUT (:)
  REAL (KIND=JPRB), ALLOCATABLE::WTT_CT_CUTIN (:)
  REAL (KIND=JPRB), ALLOCATABLE::WTT_CT_CUTOUT (:)
  INTEGER (KIND=JPIM), ALLOCATABLE::MTYPE_LOOKUP (:)
  REAL (KIND=JPRB), ALLOCATABLE::TBL_WSPEED (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::TBL_CP (:,:)
  REAL (KIND=JPRB), ALLOCATABLE::TBL_CT (:,:)
ENDTYPE TWFMETA

ENDMODULE YOMWINDFARM
