MODULE YOMXFU_TYPE
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, JPHOOK, DR_HOOK
USE TYPE_FLUXES,ONLY:FLUXES_DESCRIPTOR
USE PTRXFU,ONLY:TXFUPTR
USE FIELD_MODULE

IMPLICIT NONE

SAVE
INTEGER (KIND=JPIM), PARAMETER::JPFUXT=250

TYPE::TXFU_KEYS
  LOGICAL::LXFU=.FALSE.
  LOGICAL::LXTRD=.FALSE.
  LOGICAL::LXTRC=.FALSE.
  LOGICAL::LXTRT=.FALSE.
  LOGICAL::LXPLC=.FALSE.
  LOGICAL::LXPLCG=.FALSE.
  LOGICAL::LXPLCH=.FALSE.
  LOGICAL::LXPLS=.FALSE.
  LOGICAL::LXPLSG=.FALSE.
  LOGICAL::LXPLSH=.FALSE.
  LOGICAL::LXR=.FALSE.
  LOGICAL::LXNEBTT=.FALSE.
  LOGICAL::LXNEBPA=.FALSE.
  LOGICAL::LXWFPIN=.FALSE.
  LOGICAL::LXCLS=.FALSE.
  LOGICAL::LXMWINDCLS=.FALSE.
  LOGICAL::LXNUVCLS=.FALSE.
  LOGICAL::LXTTCLS=.FALSE.
  LOGICAL::LXHHCLS=.FALSE.
  LOGICAL::LXTPWCLS=.FALSE.
  LOGICAL::LXSOIL=.FALSE.
  LOGICAL::LTXTRD=.FALSE.
  LOGICAL::LTXTRC=.FALSE.
  LOGICAL::LTXTRT=.FALSE.
  LOGICAL::LTXR=.FALSE.
  LOGICAL::LTXNEB=.FALSE.
  LOGICAL::LTXQICE=.FALSE.
  LOGICAL::LTXQLI=.FALSE.
  LOGICAL::LXICV=.FALSE.
  LOGICAL::LXCTOP=.FALSE.
  LOGICAL::LXCLP=.FALSE.
  LOGICAL::LXCLPMF=.FALSE.
  LOGICAL::LXVMAXTH=.FALSE.
  LOGICAL::LXVEIN=.FALSE.
  LOGICAL::LXTGST=.FALSE.
  LOGICAL::LXXGST=.FALSE.
  LOGICAL::LXXGST2=.FALSE.
  LOGICAL::LXQCLS=.FALSE.
  LOGICAL::LXTHW=.FALSE.
  LOGICAL::LXXDIAGH=.FALSE.
  LOGICAL::LXMRT=.FALSE.
  LOGICAL::LXVISI=.FALSE.
  LOGICAL::LXVISI2=.FALSE.
  LOGICAL::LXPRECIPS1=.FALSE.
  LOGICAL::LXPRECIPS2=.FALSE.
  LOGICAL::LXSNOWDEPTH=.FALSE.
ENDTYPE TXFU_KEYS


TYPE, EXTENDS (TXFU_KEYS)::TXFU
  TYPE (FLUXES_DESCRIPTOR), ALLOCATABLE::TYPE_XFU (:)
  REAL (KIND=JPRB), POINTER::RMWINDCALC_B (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RMWINDCALC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RMWINDCALC=>NULL ()
  REAL (KIND=JPRB), POINTER::RMNWINDCALC_B (:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER::RMNWINDCALC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RMNWINDCALC=>NULL ()
  INTEGER (KIND=JPIM)::MEANPERIOD
  INTEGER (KIND=JPIM)::NMEANSTEPS
  INTEGER (KIND=JPIM)::NXGSTPERIOD
  INTEGER (KIND=JPIM)::NXGSTPERIOD2
  INTEGER (KIND=JPIM)::NVISIPERIOD
  INTEGER (KIND=JPIM)::NVISIPERIOD2
  INTEGER (KIND=JPIM)::NXGSTTS
  INTEGER (KIND=JPIM)::NTYPXFU
  INTEGER (KIND=JPIM)::NXFUTS (0:JPFUXT)
  INTEGER (KIND=JPIM)::NFRXFU
  INTEGER (KIND=JPIM)::NRAZTS (0:JPFUXT)
  INTEGER (KIND=JPIM)::NFRRAZ
  INTEGER (KIND=JPIM)::N1RAZ
  INTEGER (KIND=JPIM)::NFDXFU
  LOGICAL::LRESET
  LOGICAL::LRESET_GST
  LOGICAL::LRESET_GST2
  LOGICAL::LRESET_PRECIP
  LOGICAL::LRESET_PRECIP2
  LOGICAL::LRESET_VISI
  LOGICAL::LRESET_VISI2
  LOGICAL::LREAXFU
  TYPE (TXFUPTR)::YXFUPT
  REAL (KIND=JPRB), POINTER::XFUBUF_B (:,:,:)=>NULL ()
  REAL (KIND=JPRB), POINTER::CAPE (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_CAPE=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YCAPE
  REAL (KIND=JPRB), POINTER::CLPH (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_CLPH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YCLPH
  REAL (KIND=JPRB), POINTER::CLPHMF (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_CLPHMF=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YCLPHMF
  REAL (KIND=JPRB), POINTER::VMAXTH (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VMAXTH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YVMAXTH
  REAL (KIND=JPRB), POINTER::CLWC2 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_CLWC2=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YCLWC2
  REAL (KIND=JPRB), POINTER::CLWC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_CLWC=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YCLWC
  REAL (KIND=JPRB), POINTER::CTOP (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_CTOP=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YCTOP
  REAL (KIND=JPRB), POINTER::DICQ (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_DICQ=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YDICQ
  REAL (KIND=JPRB), POINTER::DICS (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_DICS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YDICS
  REAL (KIND=JPRB), POINTER::DITQ (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_DITQ=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YDITQ
  REAL (KIND=JPRB), POINTER::DITS (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_DITS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YDITS
  REAL (KIND=JPRB), POINTER::FCHSP (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FCHSP=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFCHSP
  REAL (KIND=JPRB), POINTER::FEVL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FEVL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFEVL
  REAL (KIND=JPRB), POINTER::FEVV (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FEVV=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFEVV
  REAL (KIND=JPRB), POINTER::FLWSP (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FLWSP=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFLWSP
  REAL (KIND=JPRB), POINTER::FONTE (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FONTE=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFONTE
  REAL (KIND=JPRB), POINTER::FTR (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_FTR=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YFTR
  REAL (KIND=JPRB), POINTER::HUN (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_HUN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YHUN
  REAL (KIND=JPRB), POINTER::HUX (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_HUX=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YHUX
  REAL (KIND=JPRB), POINTER::MOCON (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_MOCON=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YMOCON
  REAL (KIND=JPRB), POINTER::MRT (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_MRT=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YMRT
  REAL (KIND=JPRB), POINTER::NBBAS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NBBAS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNBBAS
  REAL (KIND=JPRB), POINTER::NBCON (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NBCON=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNBCON
  REAL (KIND=JPRB), POINTER::NBHAU (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NBHAU=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNBHAU
  REAL (KIND=JPRB), POINTER::NBMOY (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NBMOY=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNBMOY
  REAL (KIND=JPRB), POINTER::NEB (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_NEB=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNEB
  REAL (KIND=JPRB), POINTER::NEBT (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NEBT=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNEBT
  REAL (KIND=JPRB), POINTER::NUCLS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NUCLS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNUCLS
  REAL (KIND=JPRB), POINTER::NVCLS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_NVCLS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YNVCLS
  REAL (KIND=JPRB), POINTER::PLCG (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_PLCG=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPLCG
  REAL (KIND=JPRB), POINTER::PLCH (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_PLCH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPLCH
  REAL (KIND=JPRB), POINTER::PLCL (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_PLCL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPLCL
  REAL (KIND=JPRB), POINTER::PLCN (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_PLCN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPLCN
  REAL (KIND=JPRB), POINTER::PLSG (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_PLSG=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPLSG
  REAL (KIND=JPRB), POINTER::PLSH (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_PLSH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPLSH
  REAL (KIND=JPRB), POINTER::PLSL (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_PLSL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPLSL
  REAL (KIND=JPRB), POINTER::PLSN (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_PLSN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPLSN
  REAL (KIND=JPRB), POINTER::PTYPE2 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_PTYPE2=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPTYPE2
  REAL (KIND=JPRB), POINTER::PTYPE (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_PTYPE=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPTYPE
  REAL (KIND=JPRB), POINTER::PTYPESEV2 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_PTYPESEV2=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPTYPESEV2
  REAL (KIND=JPRB), POINTER::PTYPESEV (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_PTYPESEV=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YPTYPESEV
  REAL (KIND=JPRB), POINTER::QCLS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_QCLS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YQCLS
  REAL (KIND=JPRB), POINTER::QICE (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_QICE=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YQICE
  REAL (KIND=JPRB), POINTER::QLI (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_QLI=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YQLI
  REAL (KIND=JPRB), POINTER::RHCLS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RHCLS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YRHCLS
  REAL (KIND=JPRB), POINTER::RSO (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_RSO=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YRSO
  REAL (KIND=JPRB), POINTER::RTH (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_RTH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YRTH
  REAL (KIND=JPRB), POINTER::RUISL (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RUISL=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YRUISL
  REAL (KIND=JPRB), POINTER::RUISP (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RUISP=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YRUISP
  REAL (KIND=JPRB), POINTER::RUISS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_RUISS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YRUISS
  REAL (KIND=JPRB), POINTER::SIC (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SIC=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSIC
  REAL (KIND=JPRB), POINTER::TCLS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_TCLS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTCLS
  REAL (KIND=JPRB), POINTER::THW (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_THW=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTHW
  REAL (KIND=JPRB), POINTER::TN (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_TN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTN
  REAL (KIND=JPRB), POINTER::TPWCLS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_TPWCLS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTPWCLS
  REAL (KIND=JPRB), POINTER::TRCU (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_TRCU=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTRCU
  REAL (KIND=JPRB), POINTER::TRCV (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_TRCV=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTRCV
  REAL (KIND=JPRB), POINTER::TRDU (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_TRDU=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTRDU
  REAL (KIND=JPRB), POINTER::TRDV (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_TRDV=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTRDV
  REAL (KIND=JPRB), POINTER::TRTU (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_TRTU=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTRTU
  REAL (KIND=JPRB), POINTER::TRTV (:,:)=>NULL ()
  CLASS (FIELD_3RB), POINTER::F_TRTV=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTRTV
  REAL (KIND=JPRB), POINTER::TX (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_TX=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YTX
  REAL (KIND=JPRB), POINTER::UCLS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_UCLS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YUCLS
  REAL (KIND=JPRB), POINTER::UGST2 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_UGST2=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YUGST2
  REAL (KIND=JPRB), POINTER::UGST (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_UGST=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YUGST
  REAL (KIND=JPRB), POINTER::VCLS (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VCLS=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YVCLS
  REAL (KIND=JPRB), POINTER::VEIN (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VEIN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YVEIN
  REAL (KIND=JPRB), POINTER::VGST2 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VGST2=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YVGST2
  REAL (KIND=JPRB), POINTER::VGST (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VGST=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YVGST
  REAL (KIND=JPRB), POINTER::VISICLD2 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VISICLD2=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YVISICLD2
  REAL (KIND=JPRB), POINTER::VISICLD (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VISICLD=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YVISICLD
  REAL (KIND=JPRB), POINTER::VISIHYD2 (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VISIHYD2=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YVISIHYD2
  REAL (KIND=JPRB), POINTER::VISIHYD (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_VISIHYD=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YVISIHYD
  REAL (KIND=JPRB), POINTER::XDIAGH (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_XDIAGH=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YXDIAGH
  REAL (KIND=JPRB), POINTER::SNWDE (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_SNWDE=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YSNWDE
  REAL (KIND=JPRB), POINTER::WFPIN (:)=>NULL ()
  CLASS (FIELD_2RB), POINTER::F_WFPIN=>NULL ()
  TYPE (FLUXES_DESCRIPTOR)::YWFPIN
  
  
  
  
  
ENDTYPE TXFU

CONTAINS




ENDMODULE YOMXFU_TYPE
