PROGRAM MASTER


IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8 

NAMELIST/NAMRIP/CSTOP,TSTEP,NFOST

TYPE :: TRIP

INTEGER(KIND=JPIM) :: NSTOP
CHARACTER(LEN=8)   :: CSTOP 
INTEGER(KIND=JPIM) :: NFOST
REAL(KIND=JPRB) :: TSTEP

END TYPE TRIP


TYPE (TRIP), TARGET :: YDRIP
REAL(KIND=JPRB)   , POINTER :: TSTEP
INTEGER(KIND=JPIM), POINTER :: NSTOP
INTEGER(KIND=JPIM), POINTER :: NFOST
CHARACTER(LEN=8),   POINTER :: CSTOP


TSTEP => YDRIP%TSTEP
NSTOP => YDRIP%NSTOP
NFOST => YDRIP%NFOST
CSTOP => YDRIP%CSTOP

TSTEP = 0.0 
CSTOP = 'xx'

OPEN (5, FILE="namelist", FORM="FORMATTED")
READ(5,NAMRIP)
CLOSE (5) 

PRINT *, " TSTEP = ", TSTEP 
PRINT *, " CSTOP = ", CSTOP

END PROGRAM MASTER


