MODULE INV_TRANS_CTL_MOD

  IMPLICIT NONE

  INTERFACE
    SUBROUTINE CUDA_DGEMM_GROUPED(&
        & BLAS_ID, CTA, CTB,      &
        & M, N, K,                &
        & ALPHA,                  &
        & A, LDA, OFFSETA,        &
        & B, LDB, OFFSETB,        &
        & BETA,                   &
        & C, LDC, OFFSETC,        &
        & BATCHCOUNT, STREAM, ALLOC&
    &) BIND(C, NAME='blas_dgemm_wrapper_grouped')
        USE ISO_C_BINDING
        INTEGER(C_INT), VALUE :: BLAS_ID, CTA, CTB, M, N(:), K(:), LDA, LDB, LDC, OFFSETA(:), OFFSETB(:), OFFSETC(:), BATCHCOUNT
        REAL(C_DOUBLE), VALUE  :: ALPHA,BETA
        REAL(C_DOUBLE)         :: A(*), B(*), C(*)
      ATTRIBUTES(DEVICE) :: A,B,C
        INTEGER(KIND=c_size_t) :: STREAM
        TYPE(C_PTR), INTENT(IN), VALUE :: ALLOC
    END SUBROUTINE CUDA_DGEMM_GROUPED
  END INTERFACE

CONTAINS
  SUBROUTINE INV_TRANS_CTL(KF_UV_G,KF_SCALARS_G,KF_GP,KF_FS,KF_OUT_LT,&
    & KF_UV,KF_SCALARS,KF_SCDERS,&
    & PSPVOR,PSPDIV,PSPSCALAR,KVSETUV,KVSETSC,PGP,FSPGL_PROC,&
    & PSPSC3A,PSPSC3B,PSPSC2,KVSETSC3A,KVSETSC3B,KVSETSC2,PGPUV,PGP3A,PGP3B,PGP2)

    IMPLICIT NONE

    INTEGER, PARAMETER :: JPIM = 4, JPRB = 8

    INTEGER(KIND=JPIM), INTENT(IN) :: KF_UV_G
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_SCALARS_G
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_GP
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_FS
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_OUT_LT
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_UV
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_SCALARS
    INTEGER(KIND=JPIM), INTENT(IN) :: KF_SCDERS
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPVOR(:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPDIV(:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPSCALAR(:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPSC3A(:,:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPSC3B(:,:,:)
    REAL(KIND=JPRB)    ,OPTIONAL, INTENT(IN) :: PSPSC2(:,:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETUV(:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETSC(:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETSC3A(:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETSC3B(:)
    INTEGER(KIND=JPIM) ,OPTIONAL, INTENT(IN) :: KVSETSC2(:)
    REAL(KIND=JPRB) ,OPTIONAL   ,INTENT(OUT) :: PGP(:,:,:)
    EXTERNAL  FSPGL_PROC
    OPTIONAL  FSPGL_PROC
    REAL(KIND=JPRB),OPTIONAL    ,INTENT(OUT) :: PGPUV(:,:,:,:)
    REAL(KIND=JPRB),OPTIONAL    ,INTENT(OUT) :: PGP3A(:,:,:,:)
    REAL(KIND=JPRB),OPTIONAL    ,INTENT(OUT) :: PGP3B(:,:,:,:)
    REAL(KIND=JPRB),OPTIONAL    ,INTENT(OUT) :: PGP2(:,:,:)

  END SUBROUTINE INV_TRANS_CTL

  SUBROUTINE CUDA_DGEMM_GROUPED_OVERLOAD1 
    USE ISO_C_BINDING
    USE OPENACC, ONLY: ACC_GET_CUDA_STREAM
    INTEGER :: BLAS_ID
    INTEGER :: TRANSA
    INTEGER :: TRANSB
    INTEGER :: M
    INTEGER :: N(2)
    INTEGER :: K(2)
    REAL(KIND=8) :: ALPHA
    REAL(KIND=8), DIMENSION(2) :: AARRAY
    INTEGER(KIND=4) :: LDA
    INTEGER(KIND=4) :: OFFSETA(2)
    REAL(KIND=8), DIMENSION(2) :: BARRAY
    INTEGER(KIND=4) :: LDB
    INTEGER(KIND=4) :: OFFSETB(2)
    REAL(KIND=8) :: BETA
    REAL(KIND=8), DIMENSION(2) :: CARRAY
    INTEGER(KIND=4) :: LDC
    INTEGER(KIND=4) :: OFFSETC(2)
    INTEGER(KIND=4) :: BATCHCOUNT
    INTEGER(KIND=8) :: STREAM
    
    INTEGER  :: ALLOC

    !$ACC HOST_DATA USE_DEVICE(AARRAY,BARRAY,CARRAY)
    CALL CUDA_DGEMM_GROUPED( &
      & BLAS_ID, TRANSA, TRANSB, &
      & M, N, K, &
      & ALPHA, &
      & AARRAY, LDA, OFFSETA, &
      & BARRAY, LDB, OFFSETB, &
      & BETA, &
      & CARRAY, LDC, OFFSETC, &
      & BATCHCOUNT, ACC_GET_CUDA_STREAM(STREAM), C_LOC(ALLOC))
    !$ACC END HOST_DATA
  END SUBROUTINE CUDA_DGEMM_GROUPED_OVERLOAD1

END MODULE INV_TRANS_CTL_MOD
