SUBROUTINE IO_SERV_SEND_MDL2 (PSEND, KARG)

USE MPL_SEND_MOD

IMPLICIT NONE

#include "mpif.h"

REAL(KIND=8),  POINTER  :: PSEND(:)
INTEGER :: KARG

INTEGER :: IREQUEST, IERR, ISTATUS (MPI_STATUS_SIZE)
REAL(KIND=8),  POINTER  :: ZSEND(:)

ZSEND => PSEND

WRITE (0, '(" ZSEND (1:10) = ",10F12.4)') ZSEND (1:10)

!$acc enter data create (ZSEND)

!$acc update device (ZSEND)

ZSEND = 99999.

IF (KARG == 0) THEN
!$acc host_data use_device (ZSEND)
  CALL MPL_SEND_REAL8_DEVICE (ZSEND, IREQUEST)
!$acc end host_data
ELSE
!$acc host_data use_device (ZSEND)
  CALL MPI_ISEND (ZSEND, SIZE (ZSEND), MPI_REAL8, 1, 1, MPI_COMM_WORLD, IREQUEST, IERR)
  WRITE (0, *) " SEND ERROR = ", IERR
!$acc end host_data
ENDIF


CALL MPI_WAIT (IREQUEST, ISTATUS, IERR)

WRITE (0, *) " WAIT ERROR = ", IERR

END 

