PROGRAM MASTER

IMPLICIT NONE

#include "mpif.h"

INTERFACE
SUBROUTINE IO_SERV_SEND_MDL2 (PSEND)
REAL(KIND=8),    POINTER                  :: PSEND(:)
END SUBROUTINE
END INTERFACE

INTEGER :: IRANK, ISIZE, IERR
REAL*8, POINTER :: ZSEND (:)

REAL*8, ALLOCATABLE :: ZRECV (:)
INTEGER :: ISTAT (MPI_STATUS_SIZE)

CALL MPI_INIT (IERR)

CALL MPI_COMM_RANK (MPI_COMM_WORLD, IRANK, IERR)
CALL MPI_COMM_SIZE (MPI_COMM_WORLD, ISIZE, IERR)

IF (IRANK == 1) THEN

  ALLOCATE (ZRECV (218526))

  ZRECV = 0.

  CALL MPI_RECV (ZRECV, SIZE (ZRECV), MPI_REAL8, 0, 1, MPI_COMM_WORLD, ISTAT, IERR)
  
  WRITE (0, *) " RECV ERROR = ", IERR
  WRITE (0, '(" ZRECV (1:10) = ",10F12.4)') ZRECV (1:10)

  DEALLOCATE (ZRECV)

ELSE

  ALLOCATE (ZSEND (218526))
  ZSEND = 123.
  CALL IO_SERV_SEND_MDL2 (ZSEND)

ENDIF

CALL MPI_FINALIZE (IERR)

END PROGRAM MASTER
