MODULE MPL_SEND_MOD

IMPLICIT NONE

CONTAINS

SUBROUTINE MPL_SEND_REAL8_DEVICE (PSEND, KREQUEST)

#include "mpif.h"

REAL(KIND=8), DEVICE :: PSEND (:)
INTEGER :: KREQUEST

INTEGER(KIND=4) :: IERROR

PRINT *, LOC (PSEND (1))

CALL MPI_ISEND (PSEND, SIZE (PSEND), INT (MPI_REAL8), 1, 1, MPI_COMM_WORLD, KREQUEST, IERROR)

WRITE (0, *) " SEND ERROR = ", IERROR

END SUBROUTINE MPL_SEND_REAL8_DEVICE

END MODULE MPL_SEND_MOD
