SUBROUTINE CUCALLN_MF_OPENACC (&
& PPLDARE, &
& PPLRG, &
& KSTEP, &
& KIDIA, &
& KFDIA, &
& KLON, &
& KSMAX, &
& KLEV, &
& PDX, &
& KSPPN2D, &
& LDMCAPEA, &
& LDLAND, &
& LDSLPHY, &
& PTSPHY, &
& PVDIFTS, &
#if MOREARGUMENTS
& PTM1, &
& PQM1, &
& PUM1, &
& PVM1, &
& PLITOT, &
& PVERVEL, &
& PQHFL, &
& PAHFS, &
& PAPHM1, &
& PAP, &
& PAPH, &
& PGEO, &
& PGEOH, &
& PGAW, &
& PCUCONVCA, &
& PGP2DSPP, &
& PTENT, &
& PTENQ, &
& PTENU, &
& PTENV, &
& PTENTA, &
& PTENQA, &
& PARPRC, &
& KTOPC, &
& KBASEC, &
& KTYPE, &
& KCBOT, &
& KCTOP, &
& KBOTSC, &
& LDCUM, &
& LDSC, &
& KCBOT_LIG, &
& KCTOP_LIG, &
& LDCUM_LIG, &
& LDSHCV, &
& PLCRIT_AER, &
& PLU, &
& PLUDE, &
& PLUDELI, &
& PSNDE, &
& PMFU, &
& PMFD, &
& PLGLAC, &
& PDIFCQ, &
& PDIFCS, &
& PFHPCL, &
& PFHPCN, &
& PFPLCL, &
& PFPLCN, &
& PLRAIN, &
#endif
& PRSUD, &
& PSTRCU, &
& PSTRCV, &
& PFCQLF, &
& PFCQIF, &
& PMFUDE_RATE, &
& PMFDDE_RATE, &
& PCAPE, &
& PWU, &
& PWMEAN, &
& PVDISCU, &
& PDISS)

#ifdef USE_OPENACC
!$ACC ROUTINE SEQ
#endif

#ifdef USE_OPENMP
!$OMP DECLARE TARGET
#endif

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8

REAL (KIND=JPRB), INTENT (IN)::PPLDARE
REAL (KIND=JPRB), INTENT (IN)::PPLRG
INTEGER (KIND=JPIM), INTENT (IN)::KSTEP
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KSMAX
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
REAL (KIND=JPRB), INTENT (IN)::PDX (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KSPPN2D
LOGICAL, INTENT (IN)::LDMCAPEA
LOGICAL, INTENT (IN)::LDLAND (KLON)
LOGICAL, INTENT (IN)::LDSLPHY
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PVDIFTS
#if MOREARGUMENTS
REAL (KIND=JPRB), INTENT (IN)::PTM1 (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQM1 (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PUM1 (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVM1 (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PLITOT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVERVEL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQHFL (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAHFS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAPHM1 (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PGAW (KLON)
REAL (KIND=JPRB), INTENT (IN)::PCUCONVCA (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGP2DSPP (KLON, KSPPN2D)
REAL (KIND=JPRB), INTENT (INOUT)::PTENT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENV (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENTA (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENQA (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PARPRC (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KTOPC (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KBASEC (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KTYPE (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KBOTSC (KLON)
LOGICAL, INTENT (OUT)::LDCUM (KLON)
LOGICAL, INTENT (OUT)::LDSC (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCBOT_LIG (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCTOP_LIG (KLON)
LOGICAL, INTENT (OUT)::LDCUM_LIG (KLON)
LOGICAL, INTENT (IN)::LDSHCV (KLON)
REAL (KIND=JPRB), INTENT (IN)::PLCRIT_AER (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDELI (KLON, KLEV, 4)
REAL (KIND=JPRB), INTENT (OUT)::PSNDE (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (OUT)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLGLAC (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDIFCQ (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PDIFCS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PFHPCL (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PFHPCN (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PFPLCL (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PFPLCN (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PLRAIN (KLON, KLEV)
#endif
REAL (KIND=JPRB), INTENT (OUT)::PRSUD (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (OUT)::PSTRCU (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PSTRCV (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PFCQLF (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PFCQIF (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PMFUDE_RATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFDDE_RATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PCAPE (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PWU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PWMEAN (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PVDISCU (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PDISS (KLON, KLEV)

ENDSUBROUTINE CUCALLN_MF_OPENACC
