SUBROUTINE CPG_DRV1 (YD)

USE TPG_TYPE_MOD1           , ONLY : TPG_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD1, ONLY : MF_PHYS_SURF_TYPE

IMPLICIT NONE

TYPE(MF_PHYS_SURF_TYPE) :: YD

WRITE (0, *) LOC (YD)
WRITE (0, *) __FILE__, ':', __LINE__; CALL FLUSH (0)
WRITE (0, *) " ALLOCATED (YD%GSD_VD%F_AERODIAG) = ", ALLOCATED (YD%GSD_VD%F_AERODIAG)

END SUBROUTINE CPG_DRV1
