MODULE FIELD_MODULE1

USE FIELD_2RD_MODULE, ONLY : &
      & FIELD_2RB      => FIELD_2RD,      &
      & FIELD_2RB_PTR  => FIELD_2RD_PTR,  &
      & FIELD_2RD,                           &
      & FIELD_2RD_PTR
USE FIELD_2RD_MODULE, ONLY : &
      & FIELD_2RB_VIEW => FIELD_2RD_VIEW, &
      & FIELD_2RD_VIEW
USE FIELD_3RD_MODULE, ONLY : &
      & FIELD_3RB      => FIELD_3RD,      &
      & FIELD_3RB_PTR  => FIELD_3RD_PTR,  &
      & FIELD_3RD,                           &
      & FIELD_3RD_PTR
USE FIELD_3RD_MODULE, ONLY : &
      & FIELD_3RB_VIEW => FIELD_3RD_VIEW, &
      & FIELD_3RD_VIEW
USE FIELD_4RD_MODULE, ONLY : &
      & FIELD_4RB      => FIELD_4RD,      &
      & FIELD_4RB_PTR  => FIELD_4RD_PTR,  &
      & FIELD_4RD,                           &
      & FIELD_4RD_PTR
USE FIELD_4RD_MODULE, ONLY : &
      & FIELD_4RB_VIEW => FIELD_4RD_VIEW, &
      & FIELD_4RD_VIEW

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_2RB
PUBLIC :: FIELD_2RB_PTR
PUBLIC :: FIELD_2RB_VIEW
PUBLIC :: FIELD_3RB
PUBLIC :: FIELD_3RB_PTR
PUBLIC :: FIELD_3RB_VIEW
PUBLIC :: FIELD_4RB
PUBLIC :: FIELD_4RB_PTR
PUBLIC :: FIELD_4RB_VIEW
PUBLIC :: FIELD_2RD
PUBLIC :: FIELD_2RD_PTR
PUBLIC :: FIELD_2RD_VIEW
PUBLIC :: FIELD_3RD
PUBLIC :: FIELD_3RD_PTR
PUBLIC :: FIELD_3RD_VIEW
PUBLIC :: FIELD_4RD
PUBLIC :: FIELD_4RD_PTR
PUBLIC :: FIELD_4RD_VIEW

END MODULE FIELD_MODULE1
