MODULE FIELD_GFL_WRAPPER1

USE YOMGFL1            , ONLY : TGFL

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4

TYPE TGFL_MAP_INTERNAL  
INTEGER(KIND=JPIM), POINTER :: MT9_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT1_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT0_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MPC_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MPT_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT0_DL_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT0_DM_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT9_DL_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT9_DM_MAP(:) => NULL()
INTEGER(KIND=JPIM), POINTER :: MT0_SIZE(:) => NULL()
END TYPE TGFL_MAP_INTERNAL

END MODULE FIELD_GFL_WRAPPER1

