
MODULE FIELD_MODULE



#ifdef PARKIND1_SINGLE

USE FIELD_1RM_MODULE, ONLY : &
      & FIELD_1RB      => FIELD_1RM,      &
      & FIELD_1RB_PTR  => FIELD_1RM_PTR,  &
      & FIELD_1RM,                           &
      & FIELD_1RM_PTR
USE FIELD_2RM_MODULE, ONLY : &
      & FIELD_2RB      => FIELD_2RM,      &
      & FIELD_2RB_PTR  => FIELD_2RM_PTR,  &
      & FIELD_2RM,                           &
      & FIELD_2RM_PTR
USE FIELD_2RM_MODULE, ONLY : &
      & FIELD_2RB_VIEW => FIELD_2RM_VIEW, &
      & FIELD_2RM_VIEW
USE FIELD_3RM_MODULE, ONLY : &
      & FIELD_3RB      => FIELD_3RM,      &
      & FIELD_3RB_PTR  => FIELD_3RM_PTR,  &
      & FIELD_3RM,                           &
      & FIELD_3RM_PTR
USE FIELD_3RM_MODULE, ONLY : &
      & FIELD_3RB_VIEW => FIELD_3RM_VIEW, &
      & FIELD_3RM_VIEW
USE FIELD_4RM_MODULE, ONLY : &
      & FIELD_4RB      => FIELD_4RM,      &
      & FIELD_4RB_PTR  => FIELD_4RM_PTR,  &
      & FIELD_4RM,                           &
      & FIELD_4RM_PTR
USE FIELD_4RM_MODULE, ONLY : &
      & FIELD_4RB_VIEW => FIELD_4RM_VIEW, &
      & FIELD_4RM_VIEW
USE FIELD_5RM_MODULE, ONLY : &
      & FIELD_5RB      => FIELD_5RM,      &
      & FIELD_5RB_PTR  => FIELD_5RM_PTR,  &
      & FIELD_5RM,                           &
      & FIELD_5RM_PTR
USE FIELD_5RM_MODULE, ONLY : &
      & FIELD_5RB_VIEW => FIELD_5RM_VIEW, &
      & FIELD_5RM_VIEW

USE FIELD_1RD_MODULE
USE FIELD_2RD_MODULE
USE FIELD_3RD_MODULE
USE FIELD_4RD_MODULE
USE FIELD_5RD_MODULE
USE FIELD_1IM_MODULE
USE FIELD_2IM_MODULE
USE FIELD_3IM_MODULE
USE FIELD_4IM_MODULE
USE FIELD_5IM_MODULE
USE FIELD_1LM_MODULE
USE FIELD_2LM_MODULE
USE FIELD_3LM_MODULE
USE FIELD_4LM_MODULE
USE FIELD_5LM_MODULE

#else

USE FIELD_1RD_MODULE, ONLY : &
      & FIELD_1RB      => FIELD_1RD,      &
      & FIELD_1RB_PTR  => FIELD_1RD_PTR,  &
      & FIELD_1RD,                           &
      & FIELD_1RD_PTR
USE FIELD_2RD_MODULE, ONLY : &
      & FIELD_2RB      => FIELD_2RD,      &
      & FIELD_2RB_PTR  => FIELD_2RD_PTR,  &
      & FIELD_2RD,                           &
      & FIELD_2RD_PTR
USE FIELD_2RD_MODULE, ONLY : &
      & FIELD_2RB_VIEW => FIELD_2RD_VIEW, &
      & FIELD_2RD_VIEW
USE FIELD_3RD_MODULE, ONLY : &
      & FIELD_3RB      => FIELD_3RD,      &
      & FIELD_3RB_PTR  => FIELD_3RD_PTR,  &
      & FIELD_3RD,                           &
      & FIELD_3RD_PTR
USE FIELD_3RD_MODULE, ONLY : &
      & FIELD_3RB_VIEW => FIELD_3RD_VIEW, &
      & FIELD_3RD_VIEW
USE FIELD_4RD_MODULE, ONLY : &
      & FIELD_4RB      => FIELD_4RD,      &
      & FIELD_4RB_PTR  => FIELD_4RD_PTR,  &
      & FIELD_4RD,                           &
      & FIELD_4RD_PTR
USE FIELD_4RD_MODULE, ONLY : &
      & FIELD_4RB_VIEW => FIELD_4RD_VIEW, &
      & FIELD_4RD_VIEW
USE FIELD_5RD_MODULE, ONLY : &
      & FIELD_5RB      => FIELD_5RD,      &
      & FIELD_5RB_PTR  => FIELD_5RD_PTR,  &
      & FIELD_5RD,                           &
      & FIELD_5RD_PTR
USE FIELD_5RD_MODULE, ONLY : &
      & FIELD_5RB_VIEW => FIELD_5RD_VIEW, &
      & FIELD_5RD_VIEW

USE FIELD_1RM_MODULE
USE FIELD_2RM_MODULE
USE FIELD_3RM_MODULE
USE FIELD_4RM_MODULE
USE FIELD_5RM_MODULE
USE FIELD_1IM_MODULE
USE FIELD_2IM_MODULE
USE FIELD_3IM_MODULE
USE FIELD_4IM_MODULE
USE FIELD_5IM_MODULE
USE FIELD_1LM_MODULE
USE FIELD_2LM_MODULE
USE FIELD_3LM_MODULE
USE FIELD_4LM_MODULE
USE FIELD_5LM_MODULE

#endif

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

PUBLIC :: FIELD_1IM
PUBLIC :: FIELD_1IM_PTR
PUBLIC :: FIELD_2IM
PUBLIC :: FIELD_2IM_PTR
PUBLIC :: FIELD_2IM_VIEW
PUBLIC :: FIELD_3IM
PUBLIC :: FIELD_3IM_PTR
PUBLIC :: FIELD_3IM_VIEW
PUBLIC :: FIELD_4IM
PUBLIC :: FIELD_4IM_PTR
PUBLIC :: FIELD_4IM_VIEW
PUBLIC :: FIELD_5IM
PUBLIC :: FIELD_5IM_PTR
PUBLIC :: FIELD_5IM_VIEW
PUBLIC :: FIELD_1LM
PUBLIC :: FIELD_1LM_PTR
PUBLIC :: FIELD_2LM
PUBLIC :: FIELD_2LM_PTR
PUBLIC :: FIELD_2LM_VIEW
PUBLIC :: FIELD_3LM
PUBLIC :: FIELD_3LM_PTR
PUBLIC :: FIELD_3LM_VIEW
PUBLIC :: FIELD_4LM
PUBLIC :: FIELD_4LM_PTR
PUBLIC :: FIELD_4LM_VIEW
PUBLIC :: FIELD_5LM
PUBLIC :: FIELD_5LM_PTR
PUBLIC :: FIELD_5LM_VIEW
PUBLIC :: FIELD_1RM
PUBLIC :: FIELD_1RM_PTR
PUBLIC :: FIELD_2RM
PUBLIC :: FIELD_2RM_PTR
PUBLIC :: FIELD_2RM_VIEW
PUBLIC :: FIELD_3RM
PUBLIC :: FIELD_3RM_PTR
PUBLIC :: FIELD_3RM_VIEW
PUBLIC :: FIELD_4RM
PUBLIC :: FIELD_4RM_PTR
PUBLIC :: FIELD_4RM_VIEW
PUBLIC :: FIELD_5RM
PUBLIC :: FIELD_5RM_PTR
PUBLIC :: FIELD_5RM_VIEW
PUBLIC :: FIELD_1RB
PUBLIC :: FIELD_1RB_PTR
PUBLIC :: FIELD_2RB
PUBLIC :: FIELD_2RB_PTR
PUBLIC :: FIELD_2RB_VIEW
PUBLIC :: FIELD_3RB
PUBLIC :: FIELD_3RB_PTR
PUBLIC :: FIELD_3RB_VIEW
PUBLIC :: FIELD_4RB
PUBLIC :: FIELD_4RB_PTR
PUBLIC :: FIELD_4RB_VIEW
PUBLIC :: FIELD_5RB
PUBLIC :: FIELD_5RB_PTR
PUBLIC :: FIELD_5RB_VIEW
PUBLIC :: FIELD_1RD
PUBLIC :: FIELD_1RD_PTR
PUBLIC :: FIELD_2RD
PUBLIC :: FIELD_2RD_PTR
PUBLIC :: FIELD_2RD_VIEW
PUBLIC :: FIELD_3RD
PUBLIC :: FIELD_3RD_PTR
PUBLIC :: FIELD_3RD_VIEW
PUBLIC :: FIELD_4RD
PUBLIC :: FIELD_4RD_PTR
PUBLIC :: FIELD_4RD_VIEW
PUBLIC :: FIELD_5RD
PUBLIC :: FIELD_5RD_PTR
PUBLIC :: FIELD_5RD_VIEW

END MODULE FIELD_MODULE
