
MODULE FIELD_4RD_FACTORY_MODULE


USE FIELD_BASIC_MODULE
USE FIELD_4RD_MODULE
USE FIELD_3RD_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

PRIVATE

INTERFACE FIELD_NEW
  MODULE PROCEDURE FIELD_4RD_NEW_OWNER
  MODULE PROCEDURE FIELD_4RD_NEW_WRAPPER
  MODULE PROCEDURE FIELD_4RD_NEW_STACK_WRAPPER
  MODULE PROCEDURE FIELD_4RD_NEW_STACK_OWNER
END INTERFACE

INTERFACE

MODULE SUBROUTINE FIELD_4RD_NEW_STACK_WRAPPER (FIELD_PTR, LSTACK, DATA, LBOUNDS, PERSISTENT, SYNC_ON_FINAL, INITIALIZED, &
&                                                MEMBER_LBOUNDS, MEMBER_MAP, MEMBER_RANKS)

CLASS(FIELD_4RD), POINTER :: FIELD_PTR
REAL(KIND=JPRD), TARGET, INTENT (IN) :: DATA (:,:,:,:)
LOGICAL,  INTENT(IN) :: LSTACK
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: SYNC_ON_FINAL
LOGICAL, OPTIONAL,  INTENT(IN) :: INITIALIZED

INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: MEMBER_LBOUNDS(:) ! Overrides for the member lower bounds for ${member_dim}
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: MEMBER_MAP(:) ! A list of tuples containing the range of each member
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: MEMBER_RANKS(:) ! Explicit overrides for the rank of each member

END SUBROUTINE

MODULE SUBROUTINE FIELD_4RD_NEW_STACK_OWNER (FIELD_PTR, LSTACK, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, &
&                                              PINNED, POOLED, MEMBER_LBOUNDS, MEMBER_MAP, MEMBER_RANKS)

CLASS(FIELD_4RD), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
LOGICAL,  INTENT(IN) :: LSTACK
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
REAL(KIND=JPRD), OPTIONAL, INTENT(IN) :: INIT_VALUE
LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
LOGICAL, OPTIONAL,  INTENT(IN) :: POOLED

INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: MEMBER_LBOUNDS(:) ! Overrides for the member lower bounds for ${member_dim}
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: MEMBER_MAP(:) ! A list of tuples containing the range of each member
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: MEMBER_RANKS(:) ! Explicit overrides for the rank of each member

END SUBROUTINE

MODULE SUBROUTINE FIELD_4RD_GET_STACK_MEMBER_0(SELF, IDX, MEMBER)
  CLASS(FIELD_4RD), INTENT(IN) :: SELF
  INTEGER(KIND=JPIM), INTENT(IN) :: IDX
  CLASS(FIELD_3RD), POINTER, INTENT(INOUT) :: MEMBER

END SUBROUTINE FIELD_4RD_GET_STACK_MEMBER_0

MODULE SUBROUTINE FIELD_4RD_GET_STACK_MEMBER_1(SELF, IDX, MEMBER)
  CLASS(FIELD_4RD), INTENT(IN) :: SELF
  INTEGER(KIND=JPIM), INTENT(IN) :: IDX
  CLASS(FIELD_4RD), POINTER, INTENT(INOUT) :: MEMBER

END SUBROUTINE FIELD_4RD_GET_STACK_MEMBER_1


MODULE SUBROUTINE FIELD_4RD_RESIZE (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT)

CLASS(FIELD_4RD), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT

END SUBROUTINE

END INTERFACE

INTERFACE GET_STACK_MEMBER
  MODULE PROCEDURE FIELD_4RD_GET_STACK_MEMBER_0
  MODULE PROCEDURE FIELD_4RD_GET_STACK_MEMBER_1
END INTERFACE GET_STACK_MEMBER

PUBLIC :: GET_STACK_MEMBER

PUBLIC :: FIELD_NEW

INTERFACE FIELD_DELETE
  MODULE PROCEDURE FIELD_4RD_DELETE
END INTERFACE FIELD_DELETE

PUBLIC :: FIELD_DELETE

INTERFACE FIELD_RESIZE
  MODULE PROCEDURE FIELD_4RD_RESIZE
END INTERFACE FIELD_RESIZE

PUBLIC :: FIELD_RESIZE

CONTAINS

SUBROUTINE FIELD_4RD_NEW_OWNER (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR, &
&                                 POOLED)


CLASS(FIELD_4RD), POINTER :: FIELD_PTR
TYPE(FIELD_4RD_OWNER), POINTER :: FIELD_OWNER
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
REAL(KIND=JPRD), OPTIONAL, INTENT(IN) :: INIT_VALUE
LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
LOGICAL, OPTIONAL,  INTENT(IN) :: POOLED

END SUBROUTINE

SUBROUTINE FIELD_4RD_NEW_WRAPPER (FIELD_PTR, LBOUNDS, PERSISTENT, DATA, MAP_DEVPTR, SYNC_ON_FINAL, INITIALIZED)


CLASS(FIELD_4RD), POINTER :: FIELD_PTR
REAL(KIND=JPRD), TARGET, INTENT (IN) :: DATA (:,:,:,:)
TYPE(FIELD_4RD_WRAPPER), POINTER :: FIELD_WRAPPER
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT
LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
LOGICAL, OPTIONAL,  INTENT(IN) :: SYNC_ON_FINAL
LOGICAL, OPTIONAL,  INTENT(IN) :: INITIALIZED

END SUBROUTINE

SUBROUTINE FIELD_4RD_DELETE (FIELD_PTR)


CLASS(FIELD_4RD), POINTER :: FIELD_PTR

END SUBROUTINE


END MODULE

SUBMODULE(FIELD_4RD_FACTORY_MODULE) FIELD_4RD_FACTORY_RESIZE_MODULE

USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM

IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE FIELD_4RD_RESIZE (FIELD_PTR, UBOUNDS, LBOUNDS, PERSISTENT)

CLASS(FIELD_4RD), POINTER :: FIELD_PTR
INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS (4)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS (4)
LOGICAL, OPTIONAL, INTENT(IN) :: PERSISTENT

END SUBROUTINE FIELD_4RD_RESIZE


END SUBMODULE
