
MODULE FIELD_4RD_MODULE


USE IEEE_ARITHMETIC, ONLY: IEEE_SIGNALING_NAN
USE FIELD_BASIC_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM


IMPLICIT NONE

PRIVATE

TYPE, ABSTRACT, EXTENDS (FIELD_BASIC) :: FIELD_4RD
  REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:) => NULL()
#if (defined(_CRAYFTN) || defined(IS_LLVM_FLANG))
  REAL(KIND=JPRD), POINTER :: DEVPTR(:,:,:,:) => NULL()
#else
  REAL(KIND=JPRD), POINTER, CONTIGUOUS :: DEVPTR(:,:,:,:) => NULL()
#endif
  INTEGER(KIND=JPIM) :: LBOUNDS(4), UBOUNDS(4)
CONTAINS

  PROCEDURE :: FINAL => FIELD_4RD_FINAL
  PROCEDURE :: FIELD_4RD_FINAL
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_4RD_DELETE_DEVICE_DATA
  PROCEDURE :: GET_VIEW => FIELD_4RD_GET_VIEW
  PROCEDURE :: GET_DEVICE_DATA_RDONLY => FIELD_4RD_GET_DEVICE_DATA_RDONLY
  PROCEDURE :: GET_DEVICE_DATA_WRONLY => FIELD_4RD_GET_DEVICE_DATA_WRONLY
  PROCEDURE :: GET_DEVICE_DATA_RDWR => FIELD_4RD_GET_DEVICE_DATA_RDWR
  PROCEDURE :: GET_HOST_DATA_RDONLY => FIELD_4RD_GET_HOST_DATA_RDONLY
  PROCEDURE :: GET_HOST_DATA_RDWR => FIELD_4RD_GET_HOST_DATA_RDWR
  PROCEDURE :: SYNC_HOST_RDWR => FIELD_4RD_SYNC_HOST_RDWR
  PROCEDURE :: SYNC_HOST_RDONLY => FIELD_4RD_SYNC_HOST_RDONLY
  PROCEDURE :: SYNC_DEVICE_RDWR => FIELD_4RD_SYNC_DEVICE_RDWR
  PROCEDURE :: SYNC_DEVICE_RDONLY => FIELD_4RD_SYNC_DEVICE_RDONLY
  PROCEDURE :: SYNC_DEVICE_WRONLY => FIELD_4RD_SYNC_DEVICE_WRONLY
  PROCEDURE :: COPY_OBJECT => FIELD_4RD_COPY_OBJECT
  PROCEDURE :: WIPE_OBJECT => FIELD_4RD_WIPE_OBJECT
  PROCEDURE :: GET_DIMS => FIELD_4RD_GET_DIMS
  PROCEDURE(RESIZE), DEFERRED :: RESIZE

  PROCEDURE :: GET_DEVICE_DATA => FIELD_4RD_GET_DEVICE_DATA
  PROCEDURE :: GET_HOST_DATA => FIELD_4RD_GET_HOST_DATA
  PROCEDURE, PRIVATE :: FIELD_4RD_GET_HOST_DATA
  PROCEDURE, PRIVATE :: FIELD_4RD_GET_DEVICE_DATA
  PROCEDURE, PRIVATE :: COPY_DATA =>  FIELD_4RD_COPY_DATA
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_4RD_CREATE_DEVICE_DATA
  PROCEDURE :: CRC64 => FIELD_4RD_CRC64
#ifdef __PGI
  PROCEDURE :: SET_STATUS => FIELD_4RD_SET_STATUS
#endif
END TYPE FIELD_4RD

ABSTRACT INTERFACE
  SUBROUTINE RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
    USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM
    IMPORT ::  FIELD_4RD
    CLASS(FIELD_4RD),               INTENT(IN) :: SELF
    INTEGER(KIND=JPIM),           INTENT(IN) :: UBOUNDS(4)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(4)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT
  END SUBROUTINE RESIZE
END INTERFACE

PUBLIC :: FIELD_4RD

TYPE, EXTENDS(FIELD_4RD) :: FIELD_4RD_WRAPPER
  LOGICAL :: SYNC_ON_FINAL = .TRUE.
CONTAINS
  PROCEDURE :: INIT => FIELD_4RD_WRAPPER_INIT
  PROCEDURE :: FINAL => FIELD_4RD_WRAPPER_FINAL
  PROCEDURE :: RESIZE => FIELD_4RD_WRAPPER_RESIZE
END TYPE FIELD_4RD_WRAPPER

PUBLIC :: FIELD_4RD_WRAPPER

TYPE, EXTENDS(FIELD_4RD) :: FIELD_4RD_OWNER
  LOGICAL :: HAS_INIT_VALUE = .FALSE.
  LOGICAL :: PINNED = .FALSE.
  LOGICAL :: POOLED = .FALSE.
  REAL(KIND=JPRD) :: INIT_VALUE
CONTAINS
  PROCEDURE :: INIT => FIELD_4RD_OWNER_INIT
  PROCEDURE :: FINAL => FIELD_4RD_OWNER_FINAL
  PROCEDURE, PRIVATE :: CREATE_HOST_DATA => FIELD_4RD_OWNER_CREATE_HOST_DATA
  PROCEDURE :: GET_HOST_DATA => FIELD_4RD_OWNER_GET_HOST_DATA
  PROCEDURE :: GET_DEVICE_DATA => FIELD_4RD_OWNER_GET_DEVICE_DATA
  PROCEDURE :: RESIZE => FIELD_4RD_OWNER_RESIZE
END TYPE FIELD_4RD_OWNER

PUBLIC :: FIELD_4RD_OWNER

TYPE FIELD_4RD_PTR
  CLASS(FIELD_4RD), POINTER :: PTR => NULL()
END TYPE FIELD_4RD_PTR

PUBLIC :: FIELD_4RD_PTR

TYPE FIELD_4RD_VIEW
  REAL(KIND=JPRD), POINTER :: P(:,:,:) => NULL()
END TYPE FIELD_4RD_VIEW

PUBLIC :: FIELD_4RD_VIEW


CONTAINS

  SUBROUTINE FIELD_4RD_WRAPPER_INIT(SELF, DATA, PERSISTENT, LBOUNDS, MAP_DEVPTR, SYNC_ON_FINAL, INITIALIZED)

    ! Create FIELD object by wrapping existing data
    CLASS(FIELD_4RD_WRAPPER) :: SELF
    REAL(KIND=JPRD), TARGET, INTENT(IN) :: DATA(:,:,:,:)
    LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
    LOGICAL, INTENT(IN), OPTIONAL :: MAP_DEVPTR
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
    LOGICAL, INTENT(IN), OPTIONAL :: SYNC_ON_FINAL
    LOGICAL, INTENT(IN), OPTIONAL :: INITIALIZED
    
    LOGICAL :: LLPERSISTENT
    LOGICAL :: LLINITIALIZED


  END SUBROUTINE FIELD_4RD_WRAPPER_INIT

  SUBROUTINE FIELD_4RD_OWNER_INIT (SELF, LBOUNDS, UBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR, POOLED)

    CLASS(FIELD_4RD_OWNER) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(4)
    INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(4)
    LOGICAL, OPTIONAL,  INTENT(IN) :: PERSISTENT
    LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
    LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
    LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
    LOGICAL, OPTIONAL,  INTENT(IN) :: POOLED
    REAL(KIND=JPRD), OPTIONAL, INTENT(IN) :: INIT_VALUE

    LOGICAL :: IS_DELAYED
    LOGICAL :: LLPERSISTENT


  END SUBROUTINE FIELD_4RD_OWNER_INIT

  SUBROUTINE FIELD_4RD_OWNER_CREATE_HOST_DATA (SELF)
    ! Create FIELD object by explicitly allocating new data
    CLASS(FIELD_4RD_OWNER) :: SELF

  END SUBROUTINE FIELD_4RD_OWNER_CREATE_HOST_DATA

  FUNCTION FIELD_4RD_GET_VIEW(SELF, BLOCK_INDEX, ZERO) RESULT(VIEW_PTR)

    

    CLASS(FIELD_4RD) :: SELF
    REAL(KIND=JPRD), POINTER :: VIEW_PTR(:,:,:)
    INTEGER(KIND=JPIM), INTENT(IN) :: BLOCK_INDEX
    LOGICAL, OPTIONAL,  INTENT(IN) :: ZERO
    INTEGER(KIND=JPIM) :: IDX
    INTEGER(KIND=JPIM) :: LBOUNDS(4)
    REAL(KIND=JPRD), POINTER :: ZPTR(:,:,:,:)

!When the first thread reach this line it checks if the data are available on cpu.
!If not:
! - if GET_VIEW_ABORT is TRUE then GET_VIEW will abort the program
! - otherwise it then reachs a critical area, and check again in case another
!   thread has moved them meanwhile. And if they are still not, then they are moved.
  END FUNCTION FIELD_4RD_GET_VIEW

  SUBROUTINE FIELD_4RD_DELETE_DEVICE_DATA(SELF)
    ! Delete the copy of this field on GPU device
    CLASS(FIELD_4RD) :: SELF

  END SUBROUTINE FIELD_4RD_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_4RD_FINAL(SELF)
    ! Finalizes field and deallocates owned data
    CLASS(FIELD_4RD) :: SELF
  END SUBROUTINE FIELD_4RD_FINAL

  SUBROUTINE FIELD_4RD_WRAPPER_FINAL(SELF)
    ! Finalizes field and deallocates owned data
    CLASS(FIELD_4RD_WRAPPER) :: SELF
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)
  END SUBROUTINE FIELD_4RD_WRAPPER_FINAL

  SUBROUTINE FIELD_4RD_OWNER_FINAL(SELF)
    ! Finalizes field and deallocates owned data
    CLASS(FIELD_4RD_OWNER) :: SELF

  END SUBROUTINE FIELD_4RD_OWNER_FINAL

  SUBROUTINE FIELD_4RD_COPY_OBJECT (SELF, LDCREATED)


  CLASS(FIELD_4RD) :: SELF
  LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED
  LOGICAL :: LLCREATED

  END SUBROUTINE FIELD_4RD_COPY_OBJECT

  SUBROUTINE FIELD_4RD_WIPE_OBJECT (SELF, LDDELETED)


  CLASS(FIELD_4RD) :: SELF
  LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED
  LOGICAL :: LLDELETED

  END SUBROUTINE FIELD_4RD_WIPE_OBJECT

  SUBROUTINE FIELD_4RD_COPY_DATA (SELF, KDIR, QUEUE)

  CLASS(FIELD_4RD) :: SELF
  INTEGER (KIND=JPIM),           INTENT(IN) :: KDIR
  INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN) :: QUEUE
  REAL :: START, FINISH

  END SUBROUTINE FIELD_4RD_COPY_DATA

  SUBROUTINE FIELD_4RD_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE

    REAL(KIND=JPRD), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

    INTEGER(KIND=JPIM) :: LBOUNDS(4)


  END SUBROUTINE FIELD_4RD_GET_HOST_DATA

  SUBROUTINE FIELD_4RD_OWNER_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_4RD_OWNER) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    REAL(KIND=JPRD), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_4RD_OWNER_GET_HOST_DATA

  SUBROUTINE FIELD_4RD_GET_HOST_DATA_RDONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    REAL(KIND=JPRD), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_4RD_GET_HOST_DATA_RDONLY

  SUBROUTINE FIELD_4RD_SYNC_HOST_RDONLY (SELF, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRD), POINTER                        :: ZPTR(:,:,:,:)

  END SUBROUTINE FIELD_4RD_SYNC_HOST_RDONLY

  SUBROUTINE FIELD_4RD_GET_HOST_DATA_RDWR (SELF, PPTR, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    REAL(KIND=JPRD), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_4RD_GET_HOST_DATA_RDWR

  SUBROUTINE FIELD_4RD_SYNC_HOST_RDWR (SELF, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRD), POINTER                        :: ZPTR(:,:,:,:)

  END SUBROUTINE FIELD_4RD_SYNC_HOST_RDWR

  SUBROUTINE FIELD_4RD_CREATE_DEVICE_DATA (SELF)
    CLASS(FIELD_4RD) :: SELF

  END SUBROUTINE

  SUBROUTINE FIELD_4RD_GET_DEVICE_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    REAL(KIND=JPRD), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    INTEGER(KIND=JPIM)                           :: LBOUNDS(4)


  END SUBROUTINE FIELD_4RD_GET_DEVICE_DATA

  INTEGER*8 FUNCTION FIELD_4RD_CRC64 (SELF) RESULT (ICRC)
    CLASS(FIELD_4RD) :: SELF
    REAL(KIND=JPRD), POINTER :: PTR(:,:,:,:)
    REAL(KIND=JPRD), ALLOCATABLE :: ZZ(:,:,:,:)
    INTEGER*8 :: ILEN
    INTEGER(KIND=JPIM) :: J1,J2,J3,J4
    
  END FUNCTION

  SUBROUTINE FIELD_4RD_OWNER_GET_DEVICE_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_4RD_OWNER) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    REAL(KIND=JPRD), POINTER,          INTENT(INOUT) :: PTR(:,:,:,:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    INTEGER(KIND=JPIM) :: I1
    INTEGER(KIND=JPIM) :: I2
    INTEGER(KIND=JPIM) :: I3
    INTEGER(KIND=JPIM) :: I4

  END SUBROUTINE FIELD_4RD_OWNER_GET_DEVICE_DATA

  SUBROUTINE FIELD_4RD_GET_DEVICE_DATA_RDONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    REAL(KIND=JPRD), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_4RD_GET_DEVICE_DATA_RDONLY

  SUBROUTINE FIELD_4RD_GET_DEVICE_DATA_WRONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    REAL(KIND=JPRD), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_4RD_GET_DEVICE_DATA_WRONLY

  SUBROUTINE FIELD_4RD_SYNC_DEVICE_WRONLY (SELF, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRD), POINTER :: PPTR(:,:,:,:)

  END SUBROUTINE FIELD_4RD_SYNC_DEVICE_WRONLY

  SUBROUTINE FIELD_4RD_SYNC_DEVICE_RDONLY (SELF, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRD), POINTER                        :: ZPTR(:,:,:,:)

  END SUBROUTINE FIELD_4RD_SYNC_DEVICE_RDONLY

  SUBROUTINE FIELD_4RD_GET_DEVICE_DATA_RDWR (SELF, PPTR, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    REAL(KIND=JPRD), POINTER,         INTENT(INOUT) :: PPTR(:,:,:,:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_4RD_GET_DEVICE_DATA_RDWR

  SUBROUTINE FIELD_4RD_SYNC_DEVICE_RDWR (SELF, QUEUE)
    CLASS(FIELD_4RD) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRD), POINTER                        :: ZPTR(:,:,:,:)

  END SUBROUTINE FIELD_4RD_SYNC_DEVICE_RDWR

  SUBROUTINE FIELD_4RD_GET_DIMS (SELF, LBOUNDS, UBOUNDS)
    CLASS(FIELD_4RD), INTENT(IN) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: LBOUNDS(4)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: UBOUNDS(4)
  END SUBROUTINE FIELD_4RD_GET_DIMS

  SUBROUTINE FIELD_4RD_WRAPPER_RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)


    CLASS(FIELD_4RD_WRAPPER),       INTENT(IN) :: SELF
    INTEGER(KIND=JPIM),           INTENT(IN) :: UBOUNDS(4)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(4)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT
  END SUBROUTINE FIELD_4RD_WRAPPER_RESIZE

  SUBROUTINE FIELD_4RD_OWNER_RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
    CLASS(FIELD_4RD_OWNER),         INTENT(IN) :: SELF
    INTEGER(KIND=JPIM),           INTENT(IN) :: UBOUNDS(4)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(4)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT

    LOGICAL :: DELAYED
    REAL(KIND=JPRD) :: INIT_VALUE
    LOGICAL :: LLRESIZE
    INTEGER(KIND=JPIM) :: ILBOUND0(4)
    INTEGER(KIND=JPIM) :: ILBOUNDS(4)
    INTEGER(KIND=JPIM) :: IUBOUNDS(4)

  END SUBROUTINE FIELD_4RD_OWNER_RESIZE

#ifdef __PGI
  SUBROUTINE FIELD_4RD_SET_STATUS (SELF, KSTATUS)

  CLASS (FIELD_4RD) :: SELF
  INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

  END SUBROUTINE FIELD_4RD_SET_STATUS
#endif


END MODULE FIELD_4RD_MODULE
