
MODULE FIELD_1RM_MODULE


USE IEEE_ARITHMETIC, ONLY: IEEE_SIGNALING_NAN
USE FIELD_BASIC_MODULE
USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM


IMPLICIT NONE

PRIVATE

TYPE, ABSTRACT, EXTENDS (FIELD_BASIC) :: FIELD_1RM
  REAL(KIND=JPRM), POINTER :: PTR(:) => NULL()
#if (defined(_CRAYFTN) || defined(IS_LLVM_FLANG))
  REAL(KIND=JPRM), POINTER :: DEVPTR(:) => NULL()
#else
  REAL(KIND=JPRM), POINTER, CONTIGUOUS :: DEVPTR(:) => NULL()
#endif
  INTEGER(KIND=JPIM) :: LBOUNDS(1), UBOUNDS(1)
CONTAINS

  PROCEDURE :: FINAL => FIELD_1RM_FINAL
  PROCEDURE :: FIELD_1RM_FINAL
  PROCEDURE :: DELETE_DEVICE_DATA => FIELD_1RM_DELETE_DEVICE_DATA
  PROCEDURE :: GET_DEVICE_DATA_RDONLY => FIELD_1RM_GET_DEVICE_DATA_RDONLY
  PROCEDURE :: GET_DEVICE_DATA_WRONLY => FIELD_1RM_GET_DEVICE_DATA_WRONLY
  PROCEDURE :: GET_DEVICE_DATA_RDWR => FIELD_1RM_GET_DEVICE_DATA_RDWR
  PROCEDURE :: GET_HOST_DATA_RDONLY => FIELD_1RM_GET_HOST_DATA_RDONLY
  PROCEDURE :: GET_HOST_DATA_RDWR => FIELD_1RM_GET_HOST_DATA_RDWR
  PROCEDURE :: SYNC_HOST_RDWR => FIELD_1RM_SYNC_HOST_RDWR
  PROCEDURE :: SYNC_HOST_RDONLY => FIELD_1RM_SYNC_HOST_RDONLY
  PROCEDURE :: SYNC_DEVICE_RDWR => FIELD_1RM_SYNC_DEVICE_RDWR
  PROCEDURE :: SYNC_DEVICE_RDONLY => FIELD_1RM_SYNC_DEVICE_RDONLY
  PROCEDURE :: SYNC_DEVICE_WRONLY => FIELD_1RM_SYNC_DEVICE_WRONLY
  PROCEDURE :: COPY_OBJECT => FIELD_1RM_COPY_OBJECT
  PROCEDURE :: WIPE_OBJECT => FIELD_1RM_WIPE_OBJECT
  PROCEDURE :: GET_DIMS => FIELD_1RM_GET_DIMS
  PROCEDURE(RESIZE), DEFERRED :: RESIZE

  PROCEDURE :: GET_DEVICE_DATA => FIELD_1RM_GET_DEVICE_DATA
  PROCEDURE :: GET_HOST_DATA => FIELD_1RM_GET_HOST_DATA
  PROCEDURE, PRIVATE :: FIELD_1RM_GET_HOST_DATA
  PROCEDURE, PRIVATE :: FIELD_1RM_GET_DEVICE_DATA
  PROCEDURE, PRIVATE :: COPY_DATA =>  FIELD_1RM_COPY_DATA
  PROCEDURE :: CREATE_DEVICE_DATA => FIELD_1RM_CREATE_DEVICE_DATA
  PROCEDURE :: CRC64 => FIELD_1RM_CRC64
#ifdef __PGI
  PROCEDURE :: SET_STATUS => FIELD_1RM_SET_STATUS
#endif
END TYPE FIELD_1RM

ABSTRACT INTERFACE
  SUBROUTINE RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
    USE PARKIND1, ONLY : JPRM, JPRD, JPIM, JPLM
    IMPORT ::  FIELD_1RM
    CLASS(FIELD_1RM),               INTENT(IN) :: SELF
    INTEGER(KIND=JPIM),           INTENT(IN) :: UBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(1)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT
  END SUBROUTINE RESIZE
END INTERFACE

PUBLIC :: FIELD_1RM

TYPE, EXTENDS(FIELD_1RM) :: FIELD_1RM_WRAPPER
  LOGICAL :: SYNC_ON_FINAL = .TRUE.
CONTAINS
  PROCEDURE :: INIT => FIELD_1RM_WRAPPER_INIT
  PROCEDURE :: FINAL => FIELD_1RM_WRAPPER_FINAL
  PROCEDURE :: RESIZE => FIELD_1RM_WRAPPER_RESIZE
END TYPE FIELD_1RM_WRAPPER

PUBLIC :: FIELD_1RM_WRAPPER

TYPE, EXTENDS(FIELD_1RM) :: FIELD_1RM_OWNER
  LOGICAL :: HAS_INIT_VALUE = .FALSE.
  LOGICAL :: PINNED = .FALSE.
  LOGICAL :: POOLED = .FALSE.
  REAL(KIND=JPRM) :: INIT_VALUE
CONTAINS
  PROCEDURE :: INIT => FIELD_1RM_OWNER_INIT
  PROCEDURE :: FINAL => FIELD_1RM_OWNER_FINAL
  PROCEDURE, PRIVATE :: CREATE_HOST_DATA => FIELD_1RM_OWNER_CREATE_HOST_DATA
  PROCEDURE :: GET_HOST_DATA => FIELD_1RM_OWNER_GET_HOST_DATA
  PROCEDURE :: GET_DEVICE_DATA => FIELD_1RM_OWNER_GET_DEVICE_DATA
  PROCEDURE :: RESIZE => FIELD_1RM_OWNER_RESIZE
END TYPE FIELD_1RM_OWNER

PUBLIC :: FIELD_1RM_OWNER

TYPE FIELD_1RM_PTR
  CLASS(FIELD_1RM), POINTER :: PTR => NULL()
END TYPE FIELD_1RM_PTR

PUBLIC :: FIELD_1RM_PTR



CONTAINS

  SUBROUTINE FIELD_1RM_WRAPPER_INIT(SELF, DATA, PERSISTENT, LBOUNDS, MAP_DEVPTR, SYNC_ON_FINAL, INITIALIZED)

    ! Create FIELD object by wrapping existing data
    CLASS(FIELD_1RM_WRAPPER) :: SELF
    REAL(KIND=JPRM), TARGET, INTENT(IN) :: DATA(:)
    LOGICAL, INTENT(IN), OPTIONAL :: PERSISTENT
    LOGICAL, INTENT(IN), OPTIONAL :: MAP_DEVPTR
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(1)
    LOGICAL, INTENT(IN), OPTIONAL :: SYNC_ON_FINAL
    LOGICAL, INTENT(IN), OPTIONAL :: INITIALIZED
    
    LOGICAL :: LLPERSISTENT
    LOGICAL :: LLINITIALIZED


  END SUBROUTINE FIELD_1RM_WRAPPER_INIT

  SUBROUTINE FIELD_1RM_OWNER_INIT (SELF, LBOUNDS, UBOUNDS, PERSISTENT, DELAYED, INIT_VALUE, PINNED, MAP_DEVPTR, POOLED)

    CLASS(FIELD_1RM_OWNER) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: LBOUNDS(1)
    INTEGER(KIND=JPIM), INTENT(IN) :: UBOUNDS(1)
    LOGICAL, OPTIONAL,  INTENT(IN) :: PERSISTENT
    LOGICAL, OPTIONAL,  INTENT(IN) :: DELAYED
    LOGICAL, OPTIONAL,  INTENT(IN) :: PINNED
    LOGICAL, OPTIONAL,  INTENT(IN) :: MAP_DEVPTR
    LOGICAL, OPTIONAL,  INTENT(IN) :: POOLED
    REAL(KIND=JPRM), OPTIONAL, INTENT(IN) :: INIT_VALUE

    LOGICAL :: IS_DELAYED
    LOGICAL :: LLPERSISTENT


  END SUBROUTINE FIELD_1RM_OWNER_INIT

  SUBROUTINE FIELD_1RM_OWNER_CREATE_HOST_DATA (SELF)
    ! Create FIELD object by explicitly allocating new data
    CLASS(FIELD_1RM_OWNER) :: SELF

  END SUBROUTINE FIELD_1RM_OWNER_CREATE_HOST_DATA


  SUBROUTINE FIELD_1RM_DELETE_DEVICE_DATA(SELF)
    ! Delete the copy of this field on GPU device
    CLASS(FIELD_1RM) :: SELF

  END SUBROUTINE FIELD_1RM_DELETE_DEVICE_DATA

  SUBROUTINE FIELD_1RM_FINAL(SELF)
    ! Finalizes field and deallocates owned data
    CLASS(FIELD_1RM) :: SELF
  END SUBROUTINE FIELD_1RM_FINAL

  SUBROUTINE FIELD_1RM_WRAPPER_FINAL(SELF)
    ! Finalizes field and deallocates owned data
    CLASS(FIELD_1RM_WRAPPER) :: SELF
    REAL(KIND=JPRM), POINTER :: PTR(:)
  END SUBROUTINE FIELD_1RM_WRAPPER_FINAL

  SUBROUTINE FIELD_1RM_OWNER_FINAL(SELF)
    ! Finalizes field and deallocates owned data
    CLASS(FIELD_1RM_OWNER) :: SELF

  END SUBROUTINE FIELD_1RM_OWNER_FINAL

  SUBROUTINE FIELD_1RM_COPY_OBJECT (SELF, LDCREATED)


  CLASS(FIELD_1RM) :: SELF
  LOGICAL, INTENT (IN), OPTIONAL :: LDCREATED
  LOGICAL :: LLCREATED

  END SUBROUTINE FIELD_1RM_COPY_OBJECT

  SUBROUTINE FIELD_1RM_WIPE_OBJECT (SELF, LDDELETED)


  CLASS(FIELD_1RM) :: SELF
  LOGICAL, INTENT (IN), OPTIONAL :: LDDELETED
  LOGICAL :: LLDELETED

  END SUBROUTINE FIELD_1RM_WIPE_OBJECT

  SUBROUTINE FIELD_1RM_COPY_DATA (SELF, KDIR, QUEUE)

  CLASS(FIELD_1RM) :: SELF
  INTEGER (KIND=JPIM),           INTENT(IN) :: KDIR
  INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN) :: QUEUE
  REAL :: START, FINISH

  END SUBROUTINE FIELD_1RM_COPY_DATA

  SUBROUTINE FIELD_1RM_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE

    REAL(KIND=JPRM), POINTER,          INTENT(INOUT) :: PTR(:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

    INTEGER(KIND=JPIM) :: LBOUNDS(1)


  END SUBROUTINE FIELD_1RM_GET_HOST_DATA

  SUBROUTINE FIELD_1RM_OWNER_GET_HOST_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_1RM_OWNER) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    REAL(KIND=JPRM), POINTER,          INTENT(INOUT) :: PTR(:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1RM_OWNER_GET_HOST_DATA

  SUBROUTINE FIELD_1RM_GET_HOST_DATA_RDONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    REAL(KIND=JPRM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1RM_GET_HOST_DATA_RDONLY

  SUBROUTINE FIELD_1RM_SYNC_HOST_RDONLY (SELF, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRM), POINTER                        :: ZPTR(:)

  END SUBROUTINE FIELD_1RM_SYNC_HOST_RDONLY

  SUBROUTINE FIELD_1RM_GET_HOST_DATA_RDWR (SELF, PPTR, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    REAL(KIND=JPRM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1RM_GET_HOST_DATA_RDWR

  SUBROUTINE FIELD_1RM_SYNC_HOST_RDWR (SELF, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRM), POINTER                        :: ZPTR(:)

  END SUBROUTINE FIELD_1RM_SYNC_HOST_RDWR

  SUBROUTINE FIELD_1RM_CREATE_DEVICE_DATA (SELF)
    CLASS(FIELD_1RM) :: SELF

  END SUBROUTINE

  SUBROUTINE FIELD_1RM_GET_DEVICE_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    REAL(KIND=JPRM), POINTER,          INTENT(INOUT) :: PTR(:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    INTEGER(KIND=JPIM)                           :: LBOUNDS(1)


  END SUBROUTINE FIELD_1RM_GET_DEVICE_DATA

  INTEGER*8 FUNCTION FIELD_1RM_CRC64 (SELF) RESULT (ICRC)
    CLASS(FIELD_1RM) :: SELF
    REAL(KIND=JPRM), POINTER :: PTR(:)
    REAL(KIND=JPRM), ALLOCATABLE :: ZZ(:)
    INTEGER*8 :: ILEN
    INTEGER(KIND=JPIM) :: J1
    
  END FUNCTION

  SUBROUTINE FIELD_1RM_OWNER_GET_DEVICE_DATA (SELF, MODE, PTR, QUEUE)
    CLASS(FIELD_1RM_OWNER) :: SELF
    INTEGER (KIND=JPIM),           INTENT(IN)    :: MODE
    REAL(KIND=JPRM), POINTER,          INTENT(INOUT) :: PTR(:)
    INTEGER (KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    INTEGER(KIND=JPIM) :: I1

  END SUBROUTINE FIELD_1RM_OWNER_GET_DEVICE_DATA

  SUBROUTINE FIELD_1RM_GET_DEVICE_DATA_RDONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    REAL(KIND=JPRM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1RM_GET_DEVICE_DATA_RDONLY

  SUBROUTINE FIELD_1RM_GET_DEVICE_DATA_WRONLY (SELF, PPTR, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    REAL(KIND=JPRM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1RM_GET_DEVICE_DATA_WRONLY

  SUBROUTINE FIELD_1RM_SYNC_DEVICE_WRONLY (SELF, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRM), POINTER :: PPTR(:)

  END SUBROUTINE FIELD_1RM_SYNC_DEVICE_WRONLY

  SUBROUTINE FIELD_1RM_SYNC_DEVICE_RDONLY (SELF, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRM), POINTER                        :: ZPTR(:)

  END SUBROUTINE FIELD_1RM_SYNC_DEVICE_RDONLY

  SUBROUTINE FIELD_1RM_GET_DEVICE_DATA_RDWR (SELF, PPTR, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    REAL(KIND=JPRM), POINTER,         INTENT(INOUT) :: PPTR(:)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE

  END SUBROUTINE FIELD_1RM_GET_DEVICE_DATA_RDWR

  SUBROUTINE FIELD_1RM_SYNC_DEVICE_RDWR (SELF, QUEUE)
    CLASS(FIELD_1RM) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)    :: QUEUE
    REAL(KIND=JPRM), POINTER                        :: ZPTR(:)

  END SUBROUTINE FIELD_1RM_SYNC_DEVICE_RDWR

  SUBROUTINE FIELD_1RM_GET_DIMS (SELF, LBOUNDS, UBOUNDS)
    CLASS(FIELD_1RM), INTENT(IN) :: SELF
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: LBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT) :: UBOUNDS(1)
  END SUBROUTINE FIELD_1RM_GET_DIMS

  SUBROUTINE FIELD_1RM_WRAPPER_RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)


    CLASS(FIELD_1RM_WRAPPER),       INTENT(IN) :: SELF
    INTEGER(KIND=JPIM),           INTENT(IN) :: UBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(1)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT
  END SUBROUTINE FIELD_1RM_WRAPPER_RESIZE

  SUBROUTINE FIELD_1RM_OWNER_RESIZE (SELF, UBOUNDS, LBOUNDS, PERSISTENT)
    CLASS(FIELD_1RM_OWNER),         INTENT(IN) :: SELF
    INTEGER(KIND=JPIM),           INTENT(IN) :: UBOUNDS(1)
    INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: LBOUNDS(1)
    LOGICAL, OPTIONAL,            INTENT(IN) :: PERSISTENT

    LOGICAL :: DELAYED
    REAL(KIND=JPRM) :: INIT_VALUE
    LOGICAL :: LLRESIZE
    INTEGER(KIND=JPIM) :: ILBOUND0(1)
    INTEGER(KIND=JPIM) :: ILBOUNDS(1)
    INTEGER(KIND=JPIM) :: IUBOUNDS(1)

  END SUBROUTINE FIELD_1RM_OWNER_RESIZE

#ifdef __PGI
  SUBROUTINE FIELD_1RM_SET_STATUS (SELF, KSTATUS)

  CLASS (FIELD_1RM) :: SELF
  INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

  END SUBROUTINE FIELD_1RM_SET_STATUS
#endif


END MODULE FIELD_1RM_MODULE
