MODULE FIELD_CONTAINER_BASE_MOD1

USE FIELD_GFL_WRAPPER1,      ONLY: TGFL_MAP_INTERNAL

IMPLICIT NONE

TYPE,PUBLIC :: FIELD_CONTAINER_BASE
  LOGICAL            :: LCREATED=.FALSE.
  TYPE(TGFL_MAP_INTERNAL)     :: GFL_MAP_INTERNAL
END TYPE FIELD_CONTAINER_BASE

END MODULE FIELD_CONTAINER_BASE_MOD1
