MODULE FIELDS_MOD1

USE FIELDS_BASE_MOD1,          ONLY : FIELDS_BASE
USE MF_PHYS_SURFACE_TYPE_MOD1, ONLY : MF_PHYS_SURF_TYPE

IMPLICIT NONE
PRIVATE

INTEGER, PARAMETER :: JPRB = 8, JPIM = 4

TYPE TYPE_T1
  INTEGER(KIND=JPIM) :: MGPPCF_GWS = - HUGE(1_JPIM)
END TYPE TYPE_T1

TYPE :: TGMV
  TYPE(TYPE_T1)  :: YT1  
END TYPE TGMV

TYPE, PUBLIC,EXTENDS(FIELDS_BASE) :: FIELDS
  TYPE(TGMV)                   :: YRGMV
  TYPE(MF_PHYS_SURF_TYPE) :: YRMF_PHYS_SURF
CONTAINS
  FINAL :: FIELDS_FINAL
END TYPE FIELDS

CONTAINS

SUBROUTINE FIELDS_FINAL (THIS)
TYPE(FIELDS) :: THIS
END SUBROUTINE FIELDS_FINAL

END MODULE FIELDS_MOD1


