MODULE FIELDS_BASE_MOD1

USE FIELD_CONTAINER_GP_MOD1,  ONLY : FIELD_CONTAINER_GP

IMPLICIT NONE

TYPE, PUBLIC :: FIELDS_BASE
  TYPE(FIELD_CONTAINER_GP)          :: FIELDSTORE
  TYPE(FIELD_CONTAINER_GP)          :: FIELDSTORE_ECV
CONTAINS
  FINAL :: FIELDS_BASE_FINAL
END TYPE FIELDS_BASE

CONTAINS

SUBROUTINE FIELDS_BASE_FINAL(THIS)
  TYPE(FIELDS_BASE) :: THIS
END SUBROUTINE FIELDS_BASE_FINAL

END MODULE FIELDS_BASE_MOD1
