MODULE FIELD_CONTAINER_GP_MOD1

USE FIELD_CONTAINER_BASE_MOD1, ONLY : FIELD_CONTAINER_BASE

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8

TYPE,EXTENDS(FIELD_CONTAINER_BASE) :: FIELD_CONTAINER_GP
  PRIVATE
  INTEGER(KIND=JPIM)             :: ILEN_STORAGE1D
  REAL(KIND=JPRB), ALLOCATABLE   :: STORAGE1D(:)
  LOGICAL :: L_ATTACH_GFL_NPROMA_FIXED  
  REAL(KIND=JPRB), ALLOCATABLE :: STORAGE_LAST_BLOCK(:,:,:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: INDEX_LAST_BLOCK(:)
  REAL(KIND=JPRB), ALLOCATABLE    :: UNASSIGNED_GFL(:,:,:) 
  INTEGER(KIND=JPIM)          :: NHDERS=0
  INTEGER(KIND=JPIM)          :: NBLOCKS
  INTEGER(KIND=JPIM), ALLOCATABLE :: NPOINTS_BLOCK(:) 
  LOGICAL                     :: LHDERS
END TYPE FIELD_CONTAINER_GP

END MODULE FIELD_CONTAINER_GP_MOD1
