PROGRAM MASTER

USE FIELDS_MOD1     , ONLY : FIELDS
USE TYPE_GEOMETRY1  , ONLY : GEOMETRY

IMPLICIT NONE

INTERFACE

SUBROUTINE CPG_DRV1 (YD)

USE MF_PHYS_SURFACE_TYPE_MOD1, ONLY : MF_PHYS_SURF_TYPE

IMPLICIT NONE

TYPE(MF_PHYS_SURF_TYPE) :: YD

END SUBROUTINE

END INTERFACE


TYPE(GEOMETRY)     :: YRGEOMETRY
TYPE(FIELDS)       :: YRFIELDS

INTEGER :: KLEV

KLEV = 15

ALLOCATE(YRGEOMETRY%YRVERT_GEOM%YRVAB%VAH(0:KLEV))
ALLOCATE(YRGEOMETRY%YRVERT_GEOM%YRVAB%VBH(0:KLEV))
ALLOCATE(YRGEOMETRY%YRVERT_GEOM%YRVAB%VALH(0:KLEV))

WRITE (0, *) __FILE__, ':', __LINE__ ; CALL FLUSH (0)
WRITE (0, *) " ALLOCATED (YRFIELDS%YRMF_PHYS_SURF%GSD_VD%F_AERODIAG) = ", &
             & ALLOCATED (YRFIELDS%YRMF_PHYS_SURF%GSD_VD%F_AERODIAG)

WRITE (0, *) __FILE__, ':', __LINE__ ; CALL FLUSH (0)

WRITE (0, *) LOC (YRFIELDS%YRMF_PHYS_SURF)

CALL CPG_DRV1 (YRFIELDS%YRMF_PHYS_SURF)

WRITE (0, *) __FILE__, ':', __LINE__ ; CALL FLUSH (0)
WRITE (0, *) " ALLOCATED (YRFIELDS%YRMF_PHYS_SURF%GSD_VD%F_AERODIAG) = ", &
             & ALLOCATED (YRFIELDS%YRMF_PHYS_SURF%GSD_VD%F_AERODIAG)

WRITE (0, *) __FILE__, ':', __LINE__ ; CALL FLUSH (0)

END PROGRAM MASTER
