MODULE MF_PHYS_SURFACE_TYPE_MOD1

USE SURFACE_VIEWS_DIAGNOSTIC_MODULE1
USE SURFACE_VIEWS_PROGNOSTIC_MODULE1

IMPLICIT NONE

TYPE MF_PHYS_SURF_TYPE
  TYPE(SURFACE_VIEW_GROUP_SOILB) :: GSP_SB
  TYPE(SURFACE_VIEW_GROUP_SNOWG) :: GSP_SG
  TYPE(SURFACE_VIEW_GROUP_LAKEB) :: GSP_SL
  TYPE(SURFACE_VIEW_GROUP_RESVR) :: GSP_RR
  TYPE(SURFACE_VIEW_GROUP_CLS) :: GSP_CL
  TYPE(SURFACE_VIEW_GROUP_OML) :: GSP_OM
  TYPE(SURFACE_VIEW_GROUP_EXTRP) :: GSP_EP
  TYPE(SURFACE_VIEW_GROUP_XTRP2) :: GSP_X2
  TYPE(SURFACE_VIEW_GROUP_CANRI) :: GSP_CI
  TYPE(SURFACE_VIEW_GROUP_VARSF) :: GSD_VF
  TYPE(SURFACE_VIEW_GROUP_VCLIH) :: GSD_VH
  TYPE(SURFACE_VIEW_GROUP_VCLIK) :: GSD_VK
  TYPE(SURFACE_VIEW_GROUP_VCLIP) :: GSD_VP
  TYPE(SURFACE_VIEW_GROUP_VCLIV) :: GSD_VV
  TYPE(SURFACE_VIEW_GROUP_VCLIA) :: GSD_VA
  TYPE(SURFACE_VIEW_GROUP_VCLIN) :: GSD_VN
  TYPE(SURFACE_VIEW_GROUP_VDIAGO2) :: GSD_V2
  TYPE(SURFACE_VIEW_GROUP_VDIAGO3) :: GSD_V3
  TYPE(SURFACE_VIEW_GROUP_VDIAG) :: GSD_VD
END TYPE MF_PHYS_SURF_TYPE

END MODULE MF_PHYS_SURFACE_TYPE_MOD1

