MODULE SURFACE_VARIABLES_MOD1

USE VARIABLE_MODULE1
USE FIELD_MODULE1, ONLY: FIELD_3RB, FIELD_4RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE


TYPE SURFACE_VARIABLE_GROUP_SOILB
  
  TYPE(VARIABLE_3RB) :: VT   
  TYPE(VARIABLE_3RB) :: VQ   
  TYPE(VARIABLE_3RB) :: VTL   

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_SOILB

TYPE SURFACE_VARIABLE_GROUP_SNOWG
  
  TYPE(VARIABLE_3RB) :: VF   
  TYPE(VARIABLE_3RB) :: VA   
  TYPE(VARIABLE_3RB) :: VR   
  TYPE(VARIABLE_3RB) :: VT   
  TYPE(VARIABLE_3RB) :: VW   

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_SNOWG

TYPE SURFACE_VARIABLE_GROUP_LAKEB
  
  TYPE(VARIABLE_2RB) :: VLICT   
  TYPE(VARIABLE_2RB) :: VLMLT   
  TYPE(VARIABLE_2RB) :: VLTLT   
  TYPE(VARIABLE_2RB) :: VLBLT   
  TYPE(VARIABLE_2RB) :: VLSHF   
  TYPE(VARIABLE_2RB) :: VLICD   
  TYPE(VARIABLE_2RB) :: VLMLD   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_LAKEB

TYPE SURFACE_VARIABLE_GROUP_RESVR
  
  TYPE(VARIABLE_2RB) :: VT   
  TYPE(VARIABLE_2RB) :: VW   
  TYPE(VARIABLE_2RB) :: VFC   
  TYPE(VARIABLE_2RB) :: VIC   
  TYPE(VARIABLE_2RB) :: VFP1   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_RESVR

TYPE SURFACE_VARIABLE_GROUP_CLS
  
  TYPE(VARIABLE_2RB) :: VTCLS   
  TYPE(VARIABLE_2RB) :: VHUCLS   
  TYPE(VARIABLE_2RB) :: VUCLS   
  TYPE(VARIABLE_2RB) :: VVCLS   
  TYPE(VARIABLE_2RB) :: VNUCLS   
  TYPE(VARIABLE_2RB) :: VNVCLS   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_CLS

TYPE SURFACE_VARIABLE_GROUP_OML
  
  TYPE(VARIABLE_3RB) :: VTO   
  TYPE(VARIABLE_3RB) :: VSO   
  TYPE(VARIABLE_3RB) :: VUO   
  TYPE(VARIABLE_3RB) :: VVO   

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_OML

TYPE SURFACE_VARIABLE_GROUP_EXTRP
  

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_EXTRP

TYPE SURFACE_VARIABLE_GROUP_XTRP2
  

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_XTRP2

TYPE SURFACE_VARIABLE_GROUP_CANRI
  

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_CANRI



TYPE SURFACE_VARIABLE_GROUP_VARSF
  
  TYPE(VARIABLE_2RB) :: VZ0F   
  TYPE(VARIABLE_2RB) :: VALBF   
  TYPE(VARIABLE_2RB) :: VEMISF   
  TYPE(VARIABLE_2RB) :: VGETRL   
  TYPE(VARIABLE_2RB) :: VLSM   
  TYPE(VARIABLE_2RB) :: VVEG   
  TYPE(VARIABLE_2RB) :: VVRLAN   
  TYPE(VARIABLE_2RB) :: VVRLDI   
  TYPE(VARIABLE_2RB) :: VSIG   
  TYPE(VARIABLE_2RB) :: VALBSF   
  TYPE(VARIABLE_2RB) :: VLAN   
  TYPE(VARIABLE_2RB) :: VSST   
  TYPE(VARIABLE_2RB) :: VSSS   
  TYPE(VARIABLE_2RB) :: VLZ0H   
  TYPE(VARIABLE_2RB) :: VCVL   
  TYPE(VARIABLE_2RB) :: VCO2TYP   
  TYPE(VARIABLE_2RB) :: VCVH   
  TYPE(VARIABLE_2RB) :: VCUR   
  TYPE(VARIABLE_2RB) :: VTVL   
  TYPE(VARIABLE_2RB) :: VTVH   
  TYPE(VARIABLE_2RB) :: VLAIL   
  TYPE(VARIABLE_2RB) :: VLAIH   
  TYPE(VARIABLE_2RB) :: VFWET   
  TYPE(VARIABLE_2RB) :: VSOTY   
  TYPE(VARIABLE_2RB) :: VCLK   
  TYPE(VARIABLE_2RB) :: VDL   
  TYPE(VARIABLE_2RB) :: VCI   
  TYPE(VARIABLE_2RB) :: VUCUR   
  TYPE(VARIABLE_2RB) :: VVCUR   
  TYPE(VARIABLE_2RB) :: VZ0RLF   
  TYPE(VARIABLE_2RB) :: VCGPP   
  TYPE(VARIABLE_2RB) :: VCREC   
  TYPE(VARIABLE_2RB) :: VSDFOR   
  TYPE(VARIABLE_2RB) :: VALUVP   
  TYPE(VARIABLE_2RB) :: VALUVD   
  TYPE(VARIABLE_2RB) :: VALNIP   
  TYPE(VARIABLE_2RB) :: VALNID   
  TYPE(VARIABLE_2RB) :: VFP1   
  TYPE(VARIABLE_2RB) :: VSO2DD   
  TYPE(VARIABLE_2RB) :: VDMSO   
  TYPE(VARIABLE_2RB) :: VURBF   
  TYPE(VARIABLE_2RB) :: VFCA1   
  TYPE(VARIABLE_2RB) :: VFCA2   
  TYPE(VARIABLE_2RB) :: VAERDEP   
  TYPE(VARIABLE_2RB) :: VAERLTS   
  TYPE(VARIABLE_2RB) :: VAERSCC   
  TYPE(VARIABLE_2RB) :: VDSF   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VCHEMFLXO   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VCHEMWDFLX   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VCHEMDDFLX   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VCHEMDV   
  TYPE(VARIABLE_2RB) :: VNUDM   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VEMIS2D   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VEMIS2DAUX   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VARSF

TYPE SURFACE_VARIABLE_GROUP_VCLIH
  
  TYPE(VARIABLE_2RB) :: VTCCH   
  TYPE(VARIABLE_2RB) :: VSCCH   
  TYPE(VARIABLE_2RB) :: VBCCH   
  TYPE(VARIABLE_2RB) :: VPBLH   
  TYPE(VARIABLE_2RB) :: VSPSH   
  TYPE(VARIABLE_2RB) :: VQSH   
  TYPE(VARIABLE_2RB) :: VPCL   
  TYPE(VARIABLE_2RB) :: VPSL   
  TYPE(VARIABLE_2RB) :: VPCN   
  TYPE(VARIABLE_2RB) :: VPSN   
  TYPE(VARIABLE_2RB) :: VEVA   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VCLIH

TYPE SURFACE_VARIABLE_GROUP_VCLIK
  
  TYPE(VARIABLE_2RB) :: VUDGRO   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VCLIK

TYPE SURFACE_VARIABLE_GROUP_VCLIP
  
  TYPE(VARIABLE_2RB) :: VTPC   
  TYPE(VARIABLE_2RB) :: VWPC   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VCLIP

TYPE SURFACE_VARIABLE_GROUP_VCLIV
  
  TYPE(VARIABLE_2RB) :: VARG   
  TYPE(VARIABLE_2RB) :: VSAB   
  TYPE(VARIABLE_2RB) :: VD2   
  TYPE(VARIABLE_2RB) :: VIVEG   
  TYPE(VARIABLE_2RB) :: VRSMIN   
  TYPE(VARIABLE_2RB) :: VLAI   
  TYPE(VARIABLE_2RB) :: VHV   
  TYPE(VARIABLE_2RB) :: VZ0H   
  TYPE(VARIABLE_2RB) :: VALS   
  TYPE(VARIABLE_2RB) :: VALV   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VCLIV

TYPE SURFACE_VARIABLE_GROUP_VCLIA
  
  TYPE(VARIABLE_2RB) :: VSEA   
  TYPE(VARIABLE_2RB) :: VLAN   
  TYPE(VARIABLE_2RB) :: VSOO   
  TYPE(VARIABLE_2RB) :: VDES   
  TYPE(VARIABLE_2RB) :: VSUL   
  TYPE(VARIABLE_2RB) :: VVOL   
  TYPE(VARIABLE_2RB) :: VSS1   
  TYPE(VARIABLE_2RB) :: VSS2   
  TYPE(VARIABLE_2RB) :: VSS3   
  TYPE(VARIABLE_2RB) :: VDD1   
  TYPE(VARIABLE_2RB) :: VDD2   
  TYPE(VARIABLE_2RB) :: VDD3   
  TYPE(VARIABLE_2RB) :: VOM1   
  TYPE(VARIABLE_2RB) :: VOM2   
  TYPE(VARIABLE_2RB) :: VBC1   
  TYPE(VARIABLE_2RB) :: VBC2   
  TYPE(VARIABLE_2RB) :: VSU   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VCLIA

TYPE SURFACE_VARIABLE_GROUP_VCLIN
  
  TYPE(VARIABLE_2RB) :: VTOP   
  TYPE(VARIABLE_2RB) :: VBAS   
  TYPE(VARIABLE_2RB) :: VACPR   
  TYPE(VARIABLE_2RB) :: VACCPR   
  TYPE(VARIABLE_2RB) :: VACCPR5   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VCLIN

TYPE SURFACE_VARIABLE_GROUP_VDIAGO2
  
  TYPE(VARIABLE_2RB) :: VOCDEP   
  TYPE(VARIABLE_2RB) :: VUSTRC   
  TYPE(VARIABLE_2RB) :: VVSTRC   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VDIAGO2

TYPE SURFACE_VARIABLE_GROUP_VDIAGO3
  
  TYPE(VARIABLE_3RB) :: VDIFM   
  TYPE(VARIABLE_3RB) :: VDIFT   
  TYPE(VARIABLE_3RB) :: VDIFS   
  TYPE(VARIABLE_3RB) :: VADVT   
  TYPE(VARIABLE_3RB) :: VADVS   
  TYPE(VARIABLE_3RB) :: VTRI0   
  TYPE(VARIABLE_3RB) :: VTRI1   
  TYPE(VARIABLE_3RB) :: VSWDK   
  TYPE(VARIABLE_3RB) :: VZO   
  TYPE(VARIABLE_3RB) :: VHO   
  TYPE(VARIABLE_3RB) :: VDO   
  TYPE(VARIABLE_3RB) :: VHO_INV   
  TYPE(VARIABLE_3RB) :: VUOC   
  TYPE(VARIABLE_3RB) :: VVOC   
  TYPE(VARIABLE_3RB) :: VOTKE   

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VDIAGO3

TYPE SURFACE_VARIABLE_GROUP_VDIAG
  
  TYPE(VARIABLE_2RB) :: VLSP   
  TYPE(VARIABLE_2RB) :: VCP   
  TYPE(VARIABLE_2RB) :: VSF   
  TYPE(VARIABLE_2RB) :: VFZRA   
  TYPE(VARIABLE_2RB) :: VBLD   
  TYPE(VARIABLE_2RB) :: VSSHF   
  TYPE(VARIABLE_2RB) :: VSLHF   
  TYPE(VARIABLE_2RB) :: VNEE   
  TYPE(VARIABLE_2RB) :: VGPP   
  TYPE(VARIABLE_2RB) :: VREC   
  TYPE(VARIABLE_2RB) :: VMSL   
  TYPE(VARIABLE_2RB) :: VSP   
  TYPE(VARIABLE_2RB) :: VTCC   
  TYPE(VARIABLE_2RB) :: V10U   
  TYPE(VARIABLE_2RB) :: V10V   
  TYPE(VARIABLE_2RB) :: V2T   
  TYPE(VARIABLE_2RB) :: V2D   
  TYPE(VARIABLE_2RB) :: V2SH   
  TYPE(VARIABLE_2RB) :: VSSR   
  TYPE(VARIABLE_2RB) :: VSTR   
  TYPE(VARIABLE_2RB) :: VTSR   
  TYPE(VARIABLE_2RB) :: VTTR   
  TYPE(VARIABLE_2RB) :: VEWSS   
  TYPE(VARIABLE_2RB) :: VNSSS   
  TYPE(VARIABLE_2RB) :: VE   
  TYPE(VARIABLE_2RB) :: VPEV   
  TYPE(VARIABLE_2RB) :: VCCC   
  TYPE(VARIABLE_2RB) :: VLCC   
  TYPE(VARIABLE_2RB) :: VMCC   
  TYPE(VARIABLE_2RB) :: VHCC   
  TYPE(VARIABLE_2RB) :: VLGWS   
  TYPE(VARIABLE_2RB) :: VMGWS   
  TYPE(VARIABLE_2RB) :: VGWD   
  TYPE(VARIABLE_2RB) :: VMX2T   
  TYPE(VARIABLE_2RB) :: VMN2T   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VMX2T6   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VMN2T6   
  TYPE(VARIABLE_2RB) :: VRO   
  TYPE(VARIABLE_2RB) :: VSRO   
  TYPE(VARIABLE_2RB) :: VSSRO   
  TYPE(VARIABLE_2RB) :: VALB   
  TYPE(VARIABLE_2RB) :: VIEWSS   
  TYPE(VARIABLE_2RB) :: VINSSS   
  TYPE(VARIABLE_2RB) :: VISSHF   
  TYPE(VARIABLE_2RB) :: VIE   
  TYPE(VARIABLE_2RB) :: VINEE   
  TYPE(VARIABLE_2RB) :: VIGPP   
  TYPE(VARIABLE_2RB) :: VIREC   
  TYPE(VARIABLE_2RB) :: VICH4   
  TYPE(VARIABLE_2RB) :: VCSF   
  TYPE(VARIABLE_2RB) :: VLSSF   
  TYPE(VARIABLE_2RB) :: VMXTPR   
  TYPE(VARIABLE_2RB) :: VMNTPR   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VMXTPR6   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VMNTPR6   
  TYPE(VARIABLE_2RB) :: VTPR   
  TYPE(VARIABLE_2RB) :: VLSRR   
  TYPE(VARIABLE_2RB) :: VCRR   
  TYPE(VARIABLE_2RB) :: VLSSFR   
  TYPE(VARIABLE_2RB) :: VCSFR   
  TYPE(VARIABLE_2RB) :: VPTYPE   
  TYPE(VARIABLE_2RB) :: VILSPF   
  TYPE(VARIABLE_2RB) :: VZ0F   
  TYPE(VARIABLE_2RB) :: VLZ0H   
  TYPE(VARIABLE_2RB) :: VVIWVE   
  TYPE(VARIABLE_2RB) :: VVIWVN   
  TYPE(VARIABLE_2RB) :: VTCW   
  TYPE(VARIABLE_2RB) :: VTCWV   
  TYPE(VARIABLE_2RB) :: VTCLW   
  TYPE(VARIABLE_2RB) :: VTCIW   
  TYPE(VARIABLE_2RB) :: VTCRW   
  TYPE(VARIABLE_2RB) :: VTCSW   
  TYPE(VARIABLE_2RB) :: VTCSLW   
  TYPE(VARIABLE_2RB) :: VSSRD   
  TYPE(VARIABLE_2RB) :: VSTRD   
  TYPE(VARIABLE_2RB) :: VSSRDC   
  TYPE(VARIABLE_2RB) :: VSTRDC   
  TYPE(VARIABLE_2RB) :: VBLH   
  TYPE(VARIABLE_2RB) :: VSUND   
  TYPE(VARIABLE_2RB) :: VSPAR   
  TYPE(VARIABLE_2RB) :: VSUVB   
  TYPE(VARIABLE_2RB) :: VSFDIR   
  TYPE(VARIABLE_2RB) :: VSCDIR   
  TYPE(VARIABLE_2RB) :: VSDSRP   
  TYPE(VARIABLE_2RB) :: VCAPE   
  TYPE(VARIABLE_2RB) :: VMUCAPE   
  TYPE(VARIABLE_2RB) :: VMLCAPE50   
  TYPE(VARIABLE_2RB) :: VMLCAPE100   
  TYPE(VARIABLE_2RB) :: VPDEPL   
  TYPE(VARIABLE_2RB) :: VCAPES   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VMXCAP6   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VMXCAPS6   
  TYPE(VARIABLE_2RB) :: VTROPOTP   
  TYPE(VARIABLE_2RB) :: VTSRC   
  TYPE(VARIABLE_2RB) :: VTTRC   
  TYPE(VARIABLE_2RB) :: VSSRC   
  TYPE(VARIABLE_2RB) :: VSTRC   
  TYPE(VARIABLE_2RB) :: VES   
  TYPE(VARIABLE_2RB) :: VSMLT   
  TYPE(VARIABLE_2RB) :: V10FG   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: V10FG6   
  TYPE(VARIABLE_2RB) :: V10FGCV   
  TYPE(VARIABLE_2RB) :: VI10FG   
  TYPE(VARIABLE_2RB) :: VLSPF   
  TYPE(VARIABLE_2RB) :: VTCO3   
  TYPE(VARIABLE_2RB) :: VVIMD   
  TYPE(VARIABLE_2RB) :: VSPARC   
  TYPE(VARIABLE_2RB) :: VSTINC   
  TYPE(VARIABLE_2RB) :: VCBASE   
  TYPE(VARIABLE_2RB) :: V0DEGL   
  TYPE(VARIABLE_2RB) :: VM10DEGL   
  TYPE(VARIABLE_2RB) :: VVISIH   
  TYPE(VARIABLE_2RB) :: VCIN   
  TYPE(VARIABLE_2RB) :: VMLCIN50   
  TYPE(VARIABLE_2RB) :: VMLCIN100   
  TYPE(VARIABLE_2RB) :: VKINDEX   
  TYPE(VARIABLE_2RB) :: VTTINDEX   
  TYPE(VARIABLE_2RB) :: VCBASEA   
  TYPE(VARIABLE_2RB) :: VCTOPC   
  TYPE(VARIABLE_2RB) :: VZTWETB0   
  TYPE(VARIABLE_2RB) :: VZTWETB1   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VTCGHG   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VTCCHEM   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:,:) :: VAERODIAG   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:,:) :: VAERO_WVL_DIAG   
  TYPE(VARIABLE_2RB) :: V100U   
  TYPE(VARIABLE_2RB) :: V100V   
  TYPE(VARIABLE_2RB) :: V200U   
  TYPE(VARIABLE_2RB) :: V200V   
  TYPE(VARIABLE_2RB) :: VZUST   
  TYPE(VARIABLE_2RB) :: V10NU   
  TYPE(VARIABLE_2RB) :: V10NV   
  TYPE(VARIABLE_2RB) :: VDNDZN   
  TYPE(VARIABLE_2RB) :: VDNDZA   
  TYPE(VARIABLE_2RB) :: VDCTB   
  TYPE(VARIABLE_2RB) :: VTPLB   
  TYPE(VARIABLE_2RB) :: VTPLT   
  TYPE(VARIABLE_2RB) :: VODSS   
  TYPE(VARIABLE_2RB) :: VODDU   
  TYPE(VARIABLE_2RB) :: VODOM   
  TYPE(VARIABLE_2RB) :: VODBC   
  TYPE(VARIABLE_2RB) :: VODSU   
  TYPE(VARIABLE_2RB) :: VODNI   
  TYPE(VARIABLE_2RB) :: VODAM   
  TYPE(VARIABLE_2RB) :: VODSOA   
  TYPE(VARIABLE_2RB) :: VODVFA   
  TYPE(VARIABLE_2RB) :: VODVSU   
  TYPE(VARIABLE_2RB) :: VODTOACC   
  TYPE(VARIABLE_2RB) :: VAEPM1   
  TYPE(VARIABLE_2RB) :: VAEPM25   
  TYPE(VARIABLE_2RB) :: VAEPM10   
  TYPE(VARIABLE_2RB) :: VUVBED   
  TYPE(VARIABLE_2RB) :: VUVBEDCS   
  TYPE(VARIABLE_2RB) :: VLITOTI   
  TYPE(VARIABLE_2RB) :: VLICGI   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VLITOTA6   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:) :: VLICGA6   
  TYPE(VARIABLE_2RB), ALLOCATABLE, DIMENSION(:,:) :: VPTYPEOCC6   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VDIAG

TYPE SURFACE_VARIABLE_GROUP_SATSIM
  
  TYPE(VARIABLE_3RB) :: VCLBT   
  TYPE(VARIABLE_3RB) :: VCSBT   

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_SATSIM

TYPE SURFACE_VARIABLE_GROUP_WAVES
  
  TYPE(VARIABLE_2RB) :: VCHAR   
  TYPE(VARIABLE_2RB) :: VCHARHQ   
  TYPE(VARIABLE_2RB) :: VUSTOKES   
  TYPE(VARIABLE_2RB) :: VVSTOKES   
  TYPE(VARIABLE_2RB) :: VTAUOCX   
  TYPE(VARIABLE_2RB) :: VTAUOCY   
  TYPE(VARIABLE_2RB) :: VPHIOC   
  TYPE(VARIABLE_2RB) :: VWSEMEAN   
  TYPE(VARIABLE_2RB) :: VWSFMEAN   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_WAVES

TYPE SURFACE_VARIABLE_GROUP_WAM
  
  TYPE(VARIABLE_2RB) :: VU10N   
  TYPE(VARIABLE_2RB) :: VV10N   
  TYPE(VARIABLE_2RB) :: VRHO   
  TYPE(VARIABLE_2RB) :: VZIL   
  TYPE(VARIABLE_2RB) :: VCIF   
  TYPE(VARIABLE_2RB) :: VCLK   
  TYPE(VARIABLE_2RB) :: VUSTRW   
  TYPE(VARIABLE_2RB) :: VVSTRW   
  TYPE(VARIABLE_2RB) :: VUCURW   
  TYPE(VARIABLE_2RB) :: VVCURW   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_WAM

TYPE SURFACE_VARIABLE_GROUP_PRECFRAC
  

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_PRECFRAC

TYPE SURFACE_VARIABLE_GROUP_VEXTRA
  

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VEXTRA

TYPE SURFACE_VARIABLE_GROUP_VEXTRDI
  
  TYPE(VARIABLE_3RB), ALLOCATABLE, DIMENSION(:) :: VXA   
  TYPE(VARIABLE_3RB) :: VXEDR   

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VEXTRDI

TYPE SURFACE_VARIABLE_GROUP_VPRECIP
  
  TYPE(VARIABLE_3RB) :: VPRECIP   

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VPRECIP

TYPE SURFACE_VARIABLE_GROUP_VPRECIP2
  
  TYPE(VARIABLE_3RB) :: VPRECIP2   

  
  CLASS (FIELD_4RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VPRECIP2

TYPE SURFACE_VARIABLE_GROUP_VEXTR2
  

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VEXTR2

TYPE SURFACE_VARIABLE_GROUP_SFORC
  

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_SFORC

TYPE SURFACE_VARIABLE_GROUP_SFLUX
  

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_SFLUX

TYPE SURFACE_VARIABLE_GROUP_VO3ABC
  
  TYPE(VARIABLE_2RB) :: VA   
  TYPE(VARIABLE_2RB) :: VB   
  TYPE(VARIABLE_2RB) :: VC   

  
  CLASS (FIELD_3RB), POINTER :: F_GROUP => NULL ()
CONTAINS

END TYPE SURFACE_VARIABLE_GROUP_VO3ABC

END MODULE SURFACE_VARIABLES_MOD1


