MODULE SURFACE_VIEWS_PROGNOSTIC_MODULE1

USE PARKIND1, ONLY: JPIM, JPRB
USE FIELD_MODULE1, ONLY: FIELD_2RB, FIELD_3RB, FIELD_4RB, FIELD_2RB_PTR, &
 &                      FIELD_3RB_PTR, FIELD_2RB_VIEW, FIELD_3RB_VIEW
USE SURFACE_VARIABLES_MOD1
USE YOMDYN1, ONLY : TDYN

IMPLICIT NONE

TYPE SURFACE_VIEW_GROUP_SOILB
  REAL(KIND=JPRB), POINTER :: PT_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PT_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PT_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PQ_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PQ_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PQ_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PTL_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PTL_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PTL_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_SOILB), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_T_T0=>NULL(), F_T_T1=>NULL(), F_T_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_Q_T0=>NULL(), F_Q_T1=>NULL(), F_Q_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_TL_T0=>NULL(), F_TL_T1=>NULL(), F_TL_T9=>NULL()
  CLASS (FIELD_4RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_SOILB

TYPE SURFACE_VIEW_GROUP_SNOWG
  REAL(KIND=JPRB), POINTER :: PF_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PF_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PF_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PA_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PA_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PA_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PR_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PR_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PR_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PT_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PT_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PT_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PW_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PW_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PW_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_SNOWG), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_F_T0=>NULL(), F_F_T1=>NULL(), F_F_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_A_T0=>NULL(), F_A_T1=>NULL(), F_A_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_R_T0=>NULL(), F_R_T1=>NULL(), F_R_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_T_T0=>NULL(), F_T_T1=>NULL(), F_T_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_W_T0=>NULL(), F_W_T1=>NULL(), F_W_T9=>NULL()
  CLASS (FIELD_4RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_SNOWG

TYPE SURFACE_VIEW_GROUP_LAKEB
  REAL(KIND=JPRB), POINTER :: PLICT_T0(:)   
  REAL(KIND=JPRB), POINTER :: PLICT_T1(:)   
  REAL(KIND=JPRB), POINTER :: PLICT_T9(:)   
  REAL(KIND=JPRB), POINTER :: PLMLT_T0(:)   
  REAL(KIND=JPRB), POINTER :: PLMLT_T1(:)   
  REAL(KIND=JPRB), POINTER :: PLMLT_T9(:)   
  REAL(KIND=JPRB), POINTER :: PLTLT_T0(:)   
  REAL(KIND=JPRB), POINTER :: PLTLT_T1(:)   
  REAL(KIND=JPRB), POINTER :: PLTLT_T9(:)   
  REAL(KIND=JPRB), POINTER :: PLBLT_T0(:)   
  REAL(KIND=JPRB), POINTER :: PLBLT_T1(:)   
  REAL(KIND=JPRB), POINTER :: PLBLT_T9(:)   
  REAL(KIND=JPRB), POINTER :: PLSHF_T0(:)   
  REAL(KIND=JPRB), POINTER :: PLSHF_T1(:)   
  REAL(KIND=JPRB), POINTER :: PLSHF_T9(:)   
  REAL(KIND=JPRB), POINTER :: PLICD_T0(:)   
  REAL(KIND=JPRB), POINTER :: PLICD_T1(:)   
  REAL(KIND=JPRB), POINTER :: PLICD_T9(:)   
  REAL(KIND=JPRB), POINTER :: PLMLD_T0(:)   
  REAL(KIND=JPRB), POINTER :: PLMLD_T1(:)   
  REAL(KIND=JPRB), POINTER :: PLMLD_T9(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_LAKEB), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_LICT_T0=>NULL(), F_LICT_T1=>NULL(), F_LICT_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LMLT_T0=>NULL(), F_LMLT_T1=>NULL(), F_LMLT_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LTLT_T0=>NULL(), F_LTLT_T1=>NULL(), F_LTLT_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LBLT_T0=>NULL(), F_LBLT_T1=>NULL(), F_LBLT_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LSHF_T0=>NULL(), F_LSHF_T1=>NULL(), F_LSHF_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LICD_T0=>NULL(), F_LICD_T1=>NULL(), F_LICD_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LMLD_T0=>NULL(), F_LMLD_T1=>NULL(), F_LMLD_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_LAKEB

TYPE SURFACE_VIEW_GROUP_RESVR
  REAL(KIND=JPRB), POINTER :: PT_T0(:)   
  REAL(KIND=JPRB), POINTER :: PT_T1(:)   
  REAL(KIND=JPRB), POINTER :: PT_T9(:)   
  REAL(KIND=JPRB), POINTER :: PW_T0(:)   
  REAL(KIND=JPRB), POINTER :: PW_T1(:)   
  REAL(KIND=JPRB), POINTER :: PW_T9(:)   
  REAL(KIND=JPRB), POINTER :: PFC_T0(:)   
  REAL(KIND=JPRB), POINTER :: PFC_T1(:)   
  REAL(KIND=JPRB), POINTER :: PFC_T9(:)   
  REAL(KIND=JPRB), POINTER :: PIC_T0(:)   
  REAL(KIND=JPRB), POINTER :: PIC_T1(:)   
  REAL(KIND=JPRB), POINTER :: PIC_T9(:)   
  REAL(KIND=JPRB), POINTER :: PFP1_T0(:)   
  REAL(KIND=JPRB), POINTER :: PFP1_T1(:)   
  REAL(KIND=JPRB), POINTER :: PFP1_T9(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_RESVR), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_T_T0=>NULL(), F_T_T1=>NULL(), F_T_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_W_T0=>NULL(), F_W_T1=>NULL(), F_W_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_FC_T0=>NULL(), F_FC_T1=>NULL(), F_FC_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_IC_T0=>NULL(), F_IC_T1=>NULL(), F_IC_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_FP1_T0=>NULL(), F_FP1_T1=>NULL(), F_FP1_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_RESVR

TYPE SURFACE_VIEW_GROUP_CLS
  REAL(KIND=JPRB), POINTER :: PTCLS_T0(:)   
  REAL(KIND=JPRB), POINTER :: PTCLS_T1(:)   
  REAL(KIND=JPRB), POINTER :: PTCLS_T9(:)   
  REAL(KIND=JPRB), POINTER :: PHUCLS_T0(:)   
  REAL(KIND=JPRB), POINTER :: PHUCLS_T1(:)   
  REAL(KIND=JPRB), POINTER :: PHUCLS_T9(:)   
  REAL(KIND=JPRB), POINTER :: PUCLS_T0(:)   
  REAL(KIND=JPRB), POINTER :: PUCLS_T1(:)   
  REAL(KIND=JPRB), POINTER :: PUCLS_T9(:)   
  REAL(KIND=JPRB), POINTER :: PVCLS_T0(:)   
  REAL(KIND=JPRB), POINTER :: PVCLS_T1(:)   
  REAL(KIND=JPRB), POINTER :: PVCLS_T9(:)   
  REAL(KIND=JPRB), POINTER :: PNUCLS_T0(:)   
  REAL(KIND=JPRB), POINTER :: PNUCLS_T1(:)   
  REAL(KIND=JPRB), POINTER :: PNUCLS_T9(:)   
  REAL(KIND=JPRB), POINTER :: PNVCLS_T0(:)   
  REAL(KIND=JPRB), POINTER :: PNVCLS_T1(:)   
  REAL(KIND=JPRB), POINTER :: PNVCLS_T9(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_CLS), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_TCLS_T0=>NULL(), F_TCLS_T1=>NULL(), F_TCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_HUCLS_T0=>NULL(), F_HUCLS_T1=>NULL(), F_HUCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_UCLS_T0=>NULL(), F_UCLS_T1=>NULL(), F_UCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VCLS_T0=>NULL(), F_VCLS_T1=>NULL(), F_VCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_NUCLS_T0=>NULL(), F_NUCLS_T1=>NULL(), F_NUCLS_T9=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_NVCLS_T0=>NULL(), F_NVCLS_T1=>NULL(), F_NVCLS_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_CLS

TYPE SURFACE_VIEW_GROUP_OML
  REAL(KIND=JPRB), POINTER :: PTO_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PTO_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PTO_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PSO_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PSO_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PSO_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PUO_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PUO_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PUO_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PVO_T0(:,:)   
  REAL(KIND=JPRB), POINTER :: PVO_T1(:,:)   
  REAL(KIND=JPRB), POINTER :: PVO_T9(:,:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_OML), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_TO_T0=>NULL(), F_TO_T1=>NULL(), F_TO_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_SO_T0=>NULL(), F_SO_T1=>NULL(), F_SO_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_UO_T0=>NULL(), F_UO_T1=>NULL(), F_UO_T9=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_VO_T0=>NULL(), F_VO_T1=>NULL(), F_VO_T9=>NULL()
  CLASS (FIELD_4RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_OML

TYPE SURFACE_VIEW_GROUP_EXTRP
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_EXTRP), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_4RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_EXTRP

TYPE SURFACE_VIEW_GROUP_XTRP2
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_XTRP2), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_XTRP2

TYPE SURFACE_VIEW_GROUP_CANRI
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_CANRI), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_CANRI



END MODULE SURFACE_VIEWS_PROGNOSTIC_MODULE1



