MODULE SURFACE_VIEWS_DIAGNOSTIC_MODULE1

USE PARKIND1, ONLY: JPIM, JPRB
USE FIELD_MODULE1, ONLY: FIELD_2RB, FIELD_3RB, FIELD_4RB, FIELD_2RB_PTR, &
 &                      FIELD_3RB_PTR, FIELD_2RB_VIEW, FIELD_3RB_VIEW
USE SURFACE_VARIABLES_MOD1

IMPLICIT NONE

TYPE SURFACE_VIEW_GROUP_VARSF
  REAL(KIND=JPRB), POINTER :: PZ0F(:)   
  REAL(KIND=JPRB), POINTER :: PALBF(:)   
  REAL(KIND=JPRB), POINTER :: PEMISF(:)   
  REAL(KIND=JPRB), POINTER :: PGETRL(:)   
  REAL(KIND=JPRB), POINTER :: PLSM(:)   
  REAL(KIND=JPRB), POINTER :: PVEG(:)   
  REAL(KIND=JPRB), POINTER :: PVRLAN(:)   
  REAL(KIND=JPRB), POINTER :: PVRLDI(:)   
  REAL(KIND=JPRB), POINTER :: PSIG(:)   
  REAL(KIND=JPRB), POINTER :: PALBSF(:)   
  REAL(KIND=JPRB), POINTER :: PLAN(:)   
  REAL(KIND=JPRB), POINTER :: PSST(:)   
  REAL(KIND=JPRB), POINTER :: PSSS(:)   
  REAL(KIND=JPRB), POINTER :: PLZ0H(:)   
  REAL(KIND=JPRB), POINTER :: PCVL(:)   
  REAL(KIND=JPRB), POINTER :: PCO2TYP(:)   
  REAL(KIND=JPRB), POINTER :: PCVH(:)   
  REAL(KIND=JPRB), POINTER :: PCUR(:)   
  REAL(KIND=JPRB), POINTER :: PTVL(:)   
  REAL(KIND=JPRB), POINTER :: PTVH(:)   
  REAL(KIND=JPRB), POINTER :: PLAIL(:)   
  REAL(KIND=JPRB), POINTER :: PLAIH(:)   
  REAL(KIND=JPRB), POINTER :: PFWET(:)   
  REAL(KIND=JPRB), POINTER :: PSOTY(:)   
  REAL(KIND=JPRB), POINTER :: PCLK(:)   
  REAL(KIND=JPRB), POINTER :: PDL(:)   
  REAL(KIND=JPRB), POINTER :: PCI(:)   
  REAL(KIND=JPRB), POINTER :: PUCUR(:)   
  REAL(KIND=JPRB), POINTER :: PVCUR(:)   
  REAL(KIND=JPRB), POINTER :: PZ0RLF(:)   
  REAL(KIND=JPRB), POINTER :: PCGPP(:)   
  REAL(KIND=JPRB), POINTER :: PCREC(:)   
  REAL(KIND=JPRB), POINTER :: PSDFOR(:)   
  REAL(KIND=JPRB), POINTER :: PALUVP(:)   
  REAL(KIND=JPRB), POINTER :: PALUVD(:)   
  REAL(KIND=JPRB), POINTER :: PALNIP(:)   
  REAL(KIND=JPRB), POINTER :: PALNID(:)   
  REAL(KIND=JPRB), POINTER :: PFP1(:)   
  REAL(KIND=JPRB), POINTER :: PSO2DD(:)   
  REAL(KIND=JPRB), POINTER :: PDMSO(:)   
  REAL(KIND=JPRB), POINTER :: PURBF(:)   
  REAL(KIND=JPRB), POINTER :: PFCA1(:)   
  REAL(KIND=JPRB), POINTER :: PFCA2(:)   
  REAL(KIND=JPRB), POINTER :: PAERDEP(:)   
  REAL(KIND=JPRB), POINTER :: PAERLTS(:)   
  REAL(KIND=JPRB), POINTER :: PAERSCC(:)   
  REAL(KIND=JPRB), POINTER :: PDSF(:)   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PCHEMFLXO   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PCHEMWDFLX   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PCHEMDDFLX   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PCHEMDV   
  REAL(KIND=JPRB), POINTER :: PNUDM(:)   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PEMIS2D   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PEMIS2DAUX   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VARSF), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_Z0F=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ALBF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_EMISF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_GETRL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LSM=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VEG=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VRLAN=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VRLDI=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SIG=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ALBSF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LAN=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SST=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SSS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LZ0H=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CVL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CO2TYP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CVH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CUR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TVL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TVH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LAIL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LAIH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_FWET=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SOTY=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CLK=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CI=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_UCUR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VCUR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_Z0RLF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CGPP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CREC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SDFOR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ALUVP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ALUVD=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ALNIP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ALNID=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_FP1=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SO2DD=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DMSO=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_URBF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_FCA1=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_FCA2=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_AERDEP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_AERLTS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_AERSCC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DSF=>NULL()
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_CHEMFLXO
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_CHEMWDFLX
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_CHEMDDFLX
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_CHEMDV
  CLASS (FIELD_2RB), POINTER :: F_NUDM=>NULL()
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_EMIS2D
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_EMIS2DAUX
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VARSF

TYPE SURFACE_VIEW_GROUP_VCLIH
  REAL(KIND=JPRB), POINTER :: PTCCH(:)   
  REAL(KIND=JPRB), POINTER :: PSCCH(:)   
  REAL(KIND=JPRB), POINTER :: PBCCH(:)   
  REAL(KIND=JPRB), POINTER :: PPBLH(:)   
  REAL(KIND=JPRB), POINTER :: PSPSH(:)   
  REAL(KIND=JPRB), POINTER :: PQSH(:)   
  REAL(KIND=JPRB), POINTER :: PPCL(:)   
  REAL(KIND=JPRB), POINTER :: PPSL(:)   
  REAL(KIND=JPRB), POINTER :: PPCN(:)   
  REAL(KIND=JPRB), POINTER :: PPSN(:)   
  REAL(KIND=JPRB), POINTER :: PEVA(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VCLIH), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_TCCH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SCCH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_BCCH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_PBLH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SPSH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_QSH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_PCL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_PSL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_PCN=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_PSN=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_EVA=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VCLIH

TYPE SURFACE_VIEW_GROUP_VCLIK
  REAL(KIND=JPRB), POINTER :: PUDGRO(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VCLIK), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_UDGRO=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VCLIK

TYPE SURFACE_VIEW_GROUP_VCLIP
  REAL(KIND=JPRB), POINTER :: PTPC(:)   
  REAL(KIND=JPRB), POINTER :: PWPC(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VCLIP), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_TPC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_WPC=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VCLIP

TYPE SURFACE_VIEW_GROUP_VCLIV
  REAL(KIND=JPRB), POINTER :: PARG(:)   
  REAL(KIND=JPRB), POINTER :: PSAB(:)   
  REAL(KIND=JPRB), POINTER :: PD2(:)   
  REAL(KIND=JPRB), POINTER :: PIVEG(:)   
  REAL(KIND=JPRB), POINTER :: PRSMIN(:)   
  REAL(KIND=JPRB), POINTER :: PLAI(:)   
  REAL(KIND=JPRB), POINTER :: PHV(:)   
  REAL(KIND=JPRB), POINTER :: PZ0H(:)   
  REAL(KIND=JPRB), POINTER :: PALS(:)   
  REAL(KIND=JPRB), POINTER :: PALV(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VCLIV), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_ARG=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SAB=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_D2=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_IVEG=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_RSMIN=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LAI=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_HV=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_Z0H=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ALS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ALV=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VCLIV

TYPE SURFACE_VIEW_GROUP_VCLIA
  REAL(KIND=JPRB), POINTER :: PSEA(:)   
  REAL(KIND=JPRB), POINTER :: PLAN(:)   
  REAL(KIND=JPRB), POINTER :: PSOO(:)   
  REAL(KIND=JPRB), POINTER :: PDES(:)   
  REAL(KIND=JPRB), POINTER :: PSUL(:)   
  REAL(KIND=JPRB), POINTER :: PVOL(:)   
  REAL(KIND=JPRB), POINTER :: PSS1(:)   
  REAL(KIND=JPRB), POINTER :: PSS2(:)   
  REAL(KIND=JPRB), POINTER :: PSS3(:)   
  REAL(KIND=JPRB), POINTER :: PDD1(:)   
  REAL(KIND=JPRB), POINTER :: PDD2(:)   
  REAL(KIND=JPRB), POINTER :: PDD3(:)   
  REAL(KIND=JPRB), POINTER :: POM1(:)   
  REAL(KIND=JPRB), POINTER :: POM2(:)   
  REAL(KIND=JPRB), POINTER :: PBC1(:)   
  REAL(KIND=JPRB), POINTER :: PBC2(:)   
  REAL(KIND=JPRB), POINTER :: PSU(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VCLIA), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_SEA=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LAN=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SOO=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DES=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SUL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VOL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SS1=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SS2=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SS3=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DD1=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DD2=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DD3=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_OM1=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_OM2=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_BC1=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_BC2=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SU=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VCLIA

TYPE SURFACE_VIEW_GROUP_VCLIN
  REAL(KIND=JPRB), POINTER :: PTOP(:)   
  REAL(KIND=JPRB), POINTER :: PBAS(:)   
  REAL(KIND=JPRB), POINTER :: PACPR(:)   
  REAL(KIND=JPRB), POINTER :: PACCPR(:)   
  REAL(KIND=JPRB), POINTER :: PACCPR5(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VCLIN), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_TOP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_BAS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ACPR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ACCPR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ACCPR5=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VCLIN

TYPE SURFACE_VIEW_GROUP_VDIAGO2
  REAL(KIND=JPRB), POINTER :: POCDEP(:)   
  REAL(KIND=JPRB), POINTER :: PUSTRC(:)   
  REAL(KIND=JPRB), POINTER :: PVSTRC(:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VDIAGO2), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_OCDEP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_USTRC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VSTRC=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VDIAGO2

TYPE SURFACE_VIEW_GROUP_VDIAGO3
  REAL(KIND=JPRB), POINTER :: PDIFM(:,:)   
  REAL(KIND=JPRB), POINTER :: PDIFT(:,:)   
  REAL(KIND=JPRB), POINTER :: PDIFS(:,:)   
  REAL(KIND=JPRB), POINTER :: PADVT(:,:)   
  REAL(KIND=JPRB), POINTER :: PADVS(:,:)   
  REAL(KIND=JPRB), POINTER :: PTRI0(:,:)   
  REAL(KIND=JPRB), POINTER :: PTRI1(:,:)   
  REAL(KIND=JPRB), POINTER :: PSWDK(:,:)   
  REAL(KIND=JPRB), POINTER :: PZO(:,:)   
  REAL(KIND=JPRB), POINTER :: PHO(:,:)   
  REAL(KIND=JPRB), POINTER :: PDO(:,:)   
  REAL(KIND=JPRB), POINTER :: PHO_INV(:,:)   
  REAL(KIND=JPRB), POINTER :: PUOC(:,:)   
  REAL(KIND=JPRB), POINTER :: PVOC(:,:)   
  REAL(KIND=JPRB), POINTER :: POTKE(:,:)   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VDIAGO3), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_3RB), POINTER :: F_DIFM=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_DIFT=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_DIFS=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_ADVT=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_ADVS=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_TRI0=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_TRI1=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_SWDK=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_ZO=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_HO=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_DO=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_HO_INV=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_UOC=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_VOC=>NULL()
  CLASS (FIELD_3RB), POINTER :: F_OTKE=>NULL()
  CLASS (FIELD_4RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VDIAGO3

TYPE SURFACE_VIEW_GROUP_VDIAG
  REAL(KIND=JPRB), POINTER :: PLSP(:)   
  REAL(KIND=JPRB), POINTER :: PCP(:)   
  REAL(KIND=JPRB), POINTER :: PSF(:)   
  REAL(KIND=JPRB), POINTER :: PFZRA(:)   
  REAL(KIND=JPRB), POINTER :: PBLD(:)   
  REAL(KIND=JPRB), POINTER :: PSSHF(:)   
  REAL(KIND=JPRB), POINTER :: PSLHF(:)   
  REAL(KIND=JPRB), POINTER :: PNEE(:)   
  REAL(KIND=JPRB), POINTER :: PGPP(:)   
  REAL(KIND=JPRB), POINTER :: PREC(:)   
  REAL(KIND=JPRB), POINTER :: PMSL(:)   
  REAL(KIND=JPRB), POINTER :: PSP(:)   
  REAL(KIND=JPRB), POINTER :: PTCC(:)   
  REAL(KIND=JPRB), POINTER :: P10U(:)   
  REAL(KIND=JPRB), POINTER :: P10V(:)   
  REAL(KIND=JPRB), POINTER :: P2T(:)   
  REAL(KIND=JPRB), POINTER :: P2D(:)   
  REAL(KIND=JPRB), POINTER :: P2SH(:)   
  REAL(KIND=JPRB), POINTER :: PSSR(:)   
  REAL(KIND=JPRB), POINTER :: PSTR(:)   
  REAL(KIND=JPRB), POINTER :: PTSR(:)   
  REAL(KIND=JPRB), POINTER :: PTTR(:)   
  REAL(KIND=JPRB), POINTER :: PEWSS(:)   
  REAL(KIND=JPRB), POINTER :: PNSSS(:)   
  REAL(KIND=JPRB), POINTER :: PE(:)   
  REAL(KIND=JPRB), POINTER :: PPEV(:)   
  REAL(KIND=JPRB), POINTER :: PCCC(:)   
  REAL(KIND=JPRB), POINTER :: PLCC(:)   
  REAL(KIND=JPRB), POINTER :: PMCC(:)   
  REAL(KIND=JPRB), POINTER :: PHCC(:)   
  REAL(KIND=JPRB), POINTER :: PLGWS(:)   
  REAL(KIND=JPRB), POINTER :: PMGWS(:)   
  REAL(KIND=JPRB), POINTER :: PGWD(:)   
  REAL(KIND=JPRB), POINTER :: PMX2T(:)   
  REAL(KIND=JPRB), POINTER :: PMN2T(:)   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PMX2T6   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PMN2T6   
  REAL(KIND=JPRB), POINTER :: PRO(:)   
  REAL(KIND=JPRB), POINTER :: PSRO(:)   
  REAL(KIND=JPRB), POINTER :: PSSRO(:)   
  REAL(KIND=JPRB), POINTER :: PALB(:)   
  REAL(KIND=JPRB), POINTER :: PIEWSS(:)   
  REAL(KIND=JPRB), POINTER :: PINSSS(:)   
  REAL(KIND=JPRB), POINTER :: PISSHF(:)   
  REAL(KIND=JPRB), POINTER :: PIE(:)   
  REAL(KIND=JPRB), POINTER :: PINEE(:)   
  REAL(KIND=JPRB), POINTER :: PIGPP(:)   
  REAL(KIND=JPRB), POINTER :: PIREC(:)   
  REAL(KIND=JPRB), POINTER :: PICH4(:)   
  REAL(KIND=JPRB), POINTER :: PCSF(:)   
  REAL(KIND=JPRB), POINTER :: PLSSF(:)   
  REAL(KIND=JPRB), POINTER :: PMXTPR(:)   
  REAL(KIND=JPRB), POINTER :: PMNTPR(:)   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PMXTPR6   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PMNTPR6   
  REAL(KIND=JPRB), POINTER :: PTPR(:)   
  REAL(KIND=JPRB), POINTER :: PLSRR(:)   
  REAL(KIND=JPRB), POINTER :: PCRR(:)   
  REAL(KIND=JPRB), POINTER :: PLSSFR(:)   
  REAL(KIND=JPRB), POINTER :: PCSFR(:)   
  REAL(KIND=JPRB), POINTER :: PPTYPE(:)   
  REAL(KIND=JPRB), POINTER :: PILSPF(:)   
  REAL(KIND=JPRB), POINTER :: PZ0F(:)   
  REAL(KIND=JPRB), POINTER :: PLZ0H(:)   
  REAL(KIND=JPRB), POINTER :: PVIWVE(:)   
  REAL(KIND=JPRB), POINTER :: PVIWVN(:)   
  REAL(KIND=JPRB), POINTER :: PTCW(:)   
  REAL(KIND=JPRB), POINTER :: PTCWV(:)   
  REAL(KIND=JPRB), POINTER :: PTCLW(:)   
  REAL(KIND=JPRB), POINTER :: PTCIW(:)   
  REAL(KIND=JPRB), POINTER :: PTCRW(:)   
  REAL(KIND=JPRB), POINTER :: PTCSW(:)   
  REAL(KIND=JPRB), POINTER :: PTCSLW(:)   
  REAL(KIND=JPRB), POINTER :: PSSRD(:)   
  REAL(KIND=JPRB), POINTER :: PSTRD(:)   
  REAL(KIND=JPRB), POINTER :: PSSRDC(:)   
  REAL(KIND=JPRB), POINTER :: PSTRDC(:)   
  REAL(KIND=JPRB), POINTER :: PBLH(:)   
  REAL(KIND=JPRB), POINTER :: PSUND(:)   
  REAL(KIND=JPRB), POINTER :: PSPAR(:)   
  REAL(KIND=JPRB), POINTER :: PSUVB(:)   
  REAL(KIND=JPRB), POINTER :: PSFDIR(:)   
  REAL(KIND=JPRB), POINTER :: PSCDIR(:)   
  REAL(KIND=JPRB), POINTER :: PSDSRP(:)   
  REAL(KIND=JPRB), POINTER :: PCAPE(:)   
  REAL(KIND=JPRB), POINTER :: PMUCAPE(:)   
  REAL(KIND=JPRB), POINTER :: PMLCAPE50(:)   
  REAL(KIND=JPRB), POINTER :: PMLCAPE100(:)   
  REAL(KIND=JPRB), POINTER :: PPDEPL(:)   
  REAL(KIND=JPRB), POINTER :: PCAPES(:)   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PMXCAP6   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PMXCAPS6   
  REAL(KIND=JPRB), POINTER :: PTROPOTP(:)   
  REAL(KIND=JPRB), POINTER :: PTSRC(:)   
  REAL(KIND=JPRB), POINTER :: PTTRC(:)   
  REAL(KIND=JPRB), POINTER :: PSSRC(:)   
  REAL(KIND=JPRB), POINTER :: PSTRC(:)   
  REAL(KIND=JPRB), POINTER :: PES(:)   
  REAL(KIND=JPRB), POINTER :: PSMLT(:)   
  REAL(KIND=JPRB), POINTER :: P10FG(:)   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: P10FG6   
  REAL(KIND=JPRB), POINTER :: P10FGCV(:)   
  REAL(KIND=JPRB), POINTER :: PI10FG(:)   
  REAL(KIND=JPRB), POINTER :: PLSPF(:)   
  REAL(KIND=JPRB), POINTER :: PTCO3(:)   
  REAL(KIND=JPRB), POINTER :: PVIMD(:)   
  REAL(KIND=JPRB), POINTER :: PSPARC(:)   
  REAL(KIND=JPRB), POINTER :: PSTINC(:)   
  REAL(KIND=JPRB), POINTER :: PCBASE(:)   
  REAL(KIND=JPRB), POINTER :: P0DEGL(:)   
  REAL(KIND=JPRB), POINTER :: PM10DEGL(:)   
  REAL(KIND=JPRB), POINTER :: PVISIH(:)   
  REAL(KIND=JPRB), POINTER :: PCIN(:)   
  REAL(KIND=JPRB), POINTER :: PMLCIN50(:)   
  REAL(KIND=JPRB), POINTER :: PMLCIN100(:)   
  REAL(KIND=JPRB), POINTER :: PKINDEX(:)   
  REAL(KIND=JPRB), POINTER :: PTTINDEX(:)   
  REAL(KIND=JPRB), POINTER :: PCBASEA(:)   
  REAL(KIND=JPRB), POINTER :: PCTOPC(:)   
  REAL(KIND=JPRB), POINTER :: PZTWETB0(:)   
  REAL(KIND=JPRB), POINTER :: PZTWETB1(:)   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PTCGHG   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PTCCHEM   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:,:) :: PAERODIAG   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:,:) :: PAERO_WVL_DIAG   
  REAL(KIND=JPRB), POINTER :: P100U(:)   
  REAL(KIND=JPRB), POINTER :: P100V(:)   
  REAL(KIND=JPRB), POINTER :: P200U(:)   
  REAL(KIND=JPRB), POINTER :: P200V(:)   
  REAL(KIND=JPRB), POINTER :: PZUST(:)   
  REAL(KIND=JPRB), POINTER :: P10NU(:)   
  REAL(KIND=JPRB), POINTER :: P10NV(:)   
  REAL(KIND=JPRB), POINTER :: PDNDZN(:)   
  REAL(KIND=JPRB), POINTER :: PDNDZA(:)   
  REAL(KIND=JPRB), POINTER :: PDCTB(:)   
  REAL(KIND=JPRB), POINTER :: PTPLB(:)   
  REAL(KIND=JPRB), POINTER :: PTPLT(:)   
  REAL(KIND=JPRB), POINTER :: PODSS(:)   
  REAL(KIND=JPRB), POINTER :: PODDU(:)   
  REAL(KIND=JPRB), POINTER :: PODOM(:)   
  REAL(KIND=JPRB), POINTER :: PODBC(:)   
  REAL(KIND=JPRB), POINTER :: PODSU(:)   
  REAL(KIND=JPRB), POINTER :: PODNI(:)   
  REAL(KIND=JPRB), POINTER :: PODAM(:)   
  REAL(KIND=JPRB), POINTER :: PODSOA(:)   
  REAL(KIND=JPRB), POINTER :: PODVFA(:)   
  REAL(KIND=JPRB), POINTER :: PODVSU(:)   
  REAL(KIND=JPRB), POINTER :: PODTOACC(:)   
  REAL(KIND=JPRB), POINTER :: PAEPM1(:)   
  REAL(KIND=JPRB), POINTER :: PAEPM25(:)   
  REAL(KIND=JPRB), POINTER :: PAEPM10(:)   
  REAL(KIND=JPRB), POINTER :: PUVBED(:)   
  REAL(KIND=JPRB), POINTER :: PUVBEDCS(:)   
  REAL(KIND=JPRB), POINTER :: PLITOTI(:)   
  REAL(KIND=JPRB), POINTER :: PLICGI(:)   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PLITOTA6   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:) :: PLICGA6   
  TYPE(FIELD_2RB_VIEW), ALLOCATABLE, DIMENSION(:,:) :: PPTYPEOCC6   
  REAL(KIND=JPRB), POINTER :: PGROUP(:,:)

  TYPE(SURFACE_VARIABLE_GROUP_VDIAG), POINTER :: VARIABLE_GROUP
  CLASS (FIELD_2RB), POINTER :: F_LSP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_FZRA=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_BLD=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SSHF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SLHF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_NEE=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_GPP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_REC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MSL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TCC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_10U=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_10V=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_2T=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_2D=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_2SH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SSR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_STR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TSR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TTR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_EWSS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_NSSS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_E=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_PEV=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CCC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LCC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MCC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_HCC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LGWS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MGWS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_GWD=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MX2T=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MN2T=>NULL()
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_MX2T6
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_MN2T6
  CLASS (FIELD_2RB), POINTER :: F_RO=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SRO=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SSRO=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ALB=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_IEWSS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_INSSS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ISSHF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_IE=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_INEE=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_IGPP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_IREC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ICH4=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CSF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LSSF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MXTPR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MNTPR=>NULL()
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_MXTPR6
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_MNTPR6
  CLASS (FIELD_2RB), POINTER :: F_TPR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LSRR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CRR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LSSFR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CSFR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_PTYPE=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ILSPF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_Z0F=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LZ0H=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VIWVE=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VIWVN=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TCW=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TCWV=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TCLW=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TCIW=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TCRW=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TCSW=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TCSLW=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SSRD=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_STRD=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SSRDC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_STRDC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_BLH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SUND=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SPAR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SUVB=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SFDIR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SCDIR=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SDSRP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CAPE=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MUCAPE=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MLCAPE50=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MLCAPE100=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_PDEPL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CAPES=>NULL()
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_MXCAP6
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_MXCAPS6
  CLASS (FIELD_2RB), POINTER :: F_TROPOTP=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TSRC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TTRC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SSRC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_STRC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ES=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SMLT=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_10FG=>NULL()
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_10FG6
  CLASS (FIELD_2RB), POINTER :: F_10FGCV=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_I10FG=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LSPF=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TCO3=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VIMD=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_SPARC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_STINC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CBASE=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_0DEGL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_M10DEGL=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_VISIH=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CIN=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MLCIN50=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_MLCIN100=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_KINDEX=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TTINDEX=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CBASEA=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_CTOPC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ZTWETB0=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ZTWETB1=>NULL()
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_TCGHG
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_TCCHEM
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:,:) :: F_AERODIAG
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:,:) :: F_AERO_WVL_DIAG
  CLASS (FIELD_2RB), POINTER :: F_100U=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_100V=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_200U=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_200V=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ZUST=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_10NU=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_10NV=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DNDZN=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DNDZA=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_DCTB=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TPLB=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_TPLT=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODSS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODDU=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODOM=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODBC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODSU=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODNI=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODAM=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODSOA=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODVFA=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODVSU=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_ODTOACC=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_AEPM1=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_AEPM25=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_AEPM10=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_UVBED=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_UVBEDCS=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LITOTI=>NULL()
  CLASS (FIELD_2RB), POINTER :: F_LICGI=>NULL()
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_LITOTA6
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:) :: F_LICGA6
  TYPE (FIELD_2RB_PTR), ALLOCATABLE, DIMENSION(:,:) :: F_PTYPEOCC6
  CLASS (FIELD_3RB), POINTER :: F_GROUP

CONTAINS
END TYPE SURFACE_VIEW_GROUP_VDIAG

END MODULE SURFACE_VIEWS_DIAGNOSTIC_MODULE1


