MODULE TPG_TYPE_MOD1


USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK1 , ONLY : LHOOK, DR_HOOK, JPHOOK

USE TYPE_GEOMETRY2    , ONLY : GEOMETRY
USE FIELD_MODULE1     , ONLY : FIELD_3RB
USE FIELD_FACTORY_MODULE

IMPLICIT NONE
SAVE


TYPE TPG_TYPE

REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PHI0F(:,:)=>NULL(), PHI0FL(:,:)=>NULL(),PHI0FM(:,:)=>NULL(),&
 & RT0(:,:)=>NULL(),RT0L(:,:)=>NULL(),RT0M(:,:)=>NULL()
CLASS (FIELD_3RB), POINTER :: F_PHI0F=>NULL(), F_PHI0FL=>NULL(), F_PHI0FM=>NULL(), F_RT0=>NULL(), &
 & F_RT0L=>NULL(), F_RT0M=>NULL()

REAL(KIND=JPRB), POINTER :: PHI0H(:,:)=>NULL(), PHI0HL(:,:)=>NULL(), PHI0HM(:,:)=>NULL()
CLASS (FIELD_3RB), POINTER :: F_PHI0H=>NULL(), F_PHI0HL=>NULL(), F_PHI0HM=>NULL()

REAL(KIND=JPRB), POINTER :: PSGRTL(:,:)=>NULL(), PSGRTM(:,:)=>NULL()
CLASS (FIELD_3RB), POINTER :: F_PSGRTL=>NULL(), F_PSGRTM=>NULL()

CONTAINS
  PROCEDURE :: UPDATE_VIEW => TPG_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => TPG_TYPE_FINAL
END TYPE TPG_TYPE

CONTAINS

SUBROUTINE TPG_TYPE_INIT(SELF, LPGFSF, LPGREUSE)

  CLASS(TPG_TYPE)      , INTENT(INOUT) :: SELF
  LOGICAL              , INTENT(IN)    :: LPGFSF    
  LOGICAL              , INTENT(IN)    :: LPGREUSE  

  
    CALL FIELD_NEW (SELF%F_PHI0F  , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 1, 1], PERSISTENT=LPGFSF.AND.LPGREUSE)
    CALL FIELD_NEW (SELF%F_PHI0FL , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 1, 1], PERSISTENT=LPGFSF.AND.LPGREUSE)
    CALL FIELD_NEW (SELF%F_PHI0FM , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 1, 1], PERSISTENT=LPGFSF.AND.LPGREUSE)
    CALL FIELD_NEW (SELF%F_RT0    , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 1, 1], PERSISTENT=LPGFSF.AND.LPGREUSE)
    CALL FIELD_NEW (SELF%F_RT0L   , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 1, 1], PERSISTENT=LPGFSF.AND.LPGREUSE)
    CALL FIELD_NEW (SELF%F_RT0M   , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 1, 1], PERSISTENT=LPGFSF.AND.LPGREUSE)
    CALL FIELD_NEW (SELF%F_PHI0H  , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 0, 1], PERSISTENT=LPGFSF.AND.LPGREUSE)
    CALL FIELD_NEW (SELF%F_PHI0HL , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 0, 1], PERSISTENT=LPGFSF.AND.LPGREUSE)
    CALL FIELD_NEW (SELF%F_PHI0HM , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 0, 1], PERSISTENT=LPGFSF.AND.LPGREUSE)
    CALL FIELD_NEW (SELF%F_PSGRTL , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 1, 1], PERSISTENT=LPGFSF)
    CALL FIELD_NEW (SELF%F_PSGRTM , UBOUNDS=[1, 1, 1], LBOUNDS=[1, 1, 1], PERSISTENT=LPGFSF)

END SUBROUTINE TPG_TYPE_INIT

SUBROUTINE TPG_TYPE_UPDATE_VIEW(SELF, BLOCK_INDEX)
  CLASS(TPG_TYPE)      , INTENT(INOUT) :: SELF
  INTEGER(KIND=JPIM)   , INTENT(IN)    :: BLOCK_INDEX

  IF (ASSOCIATED (SELF%F_PHI0F ))  SELF%PHI0F  => SELF%F_PHI0F%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_PHI0FL))  SELF%PHI0FL => SELF%F_PHI0FL%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_PHI0FM))  SELF%PHI0FM => SELF%F_PHI0FM%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_RT0   ))  SELF%RT0    => SELF%F_RT0%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_RT0L  ))  SELF%RT0L   => SELF%F_RT0L%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_RT0M  ))  SELF%RT0M   => SELF%F_RT0M%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_PHI0H ))  SELF%PHI0H  => SELF%F_PHI0H%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_PHI0HL))  SELF%PHI0HL => SELF%F_PHI0HL%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_PHI0HM))  SELF%PHI0HM => SELF%F_PHI0HM%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_PSGRTL))  SELF%PSGRTL => SELF%F_PSGRTL%GET_VIEW(BLOCK_INDEX)
  IF (ASSOCIATED (SELF%F_PSGRTM))  SELF%PSGRTM => SELF%F_PSGRTM%GET_VIEW(BLOCK_INDEX)

END SUBROUTINE TPG_TYPE_UPDATE_VIEW

SUBROUTINE TPG_TYPE_FINAL(SELF)
  CLASS(TPG_TYPE)      , INTENT(INOUT) :: SELF

  IF (ASSOCIATED(SELF%F_PHI0F))  CALL FIELD_DELETE (SELF%F_PHI0F)
  IF (ASSOCIATED(SELF%F_PHI0FL)) CALL FIELD_DELETE (SELF%F_PHI0FL)
  IF (ASSOCIATED(SELF%F_PHI0FM)) CALL FIELD_DELETE (SELF%F_PHI0FM)
  IF (ASSOCIATED(SELF%F_RT0))    CALL FIELD_DELETE (SELF%F_RT0)
  IF (ASSOCIATED(SELF%F_RT0L))   CALL FIELD_DELETE (SELF%F_RT0L)
  IF (ASSOCIATED(SELF%F_RT0M))   CALL FIELD_DELETE (SELF%F_RT0M)
  IF (ASSOCIATED(SELF%F_PHI0H))  CALL FIELD_DELETE (SELF%F_PHI0H)
  IF (ASSOCIATED(SELF%F_PHI0HL)) CALL FIELD_DELETE (SELF%F_PHI0HL)
  IF (ASSOCIATED(SELF%F_PHI0HM)) CALL FIELD_DELETE (SELF%F_PHI0HM)
  IF (ASSOCIATED(SELF%F_PSGRTL)) CALL FIELD_DELETE (SELF%F_PSGRTL)
  IF (ASSOCIATED(SELF%F_PSGRTM)) CALL FIELD_DELETE (SELF%F_PSGRTM)

END SUBROUTINE TPG_TYPE_FINAL

END MODULE TPG_TYPE_MOD1
