MODULE TYPE_GEOMETRY2

USE YOMVERT2, ONLY : TVERTICAL_GEOM

IMPLICIT NONE 

INTEGER, PARAMETER :: JPRB = 8, JPIM = 4, JPRD = 8

TYPE, PUBLIC :: GEOMETRY
  TYPE(TVERTICAL_GEOM) :: YRVERT_GEOM
CONTAINS
  FINAL :: GEOMETRY_FINAL
END TYPE GEOMETRY

CONTAINS

SUBROUTINE GEOMETRY_FINAL(THIS)
TYPE(GEOMETRY) :: THIS
END SUBROUTINE GEOMETRY_FINAL

END MODULE TYPE_GEOMETRY2

