MODULE TYPE_GEOMETRY1

IMPLICIT NONE 

PRIVATE

INTEGER, PARAMETER :: JPRB = 8, JPIM = 4, JPRD = 8

TYPE TVAB
  REAL(KIND=JPRB), ALLOCATABLE :: VALH(:)
  REAL(KIND=JPRB), ALLOCATABLE :: VBH(:)
  REAL(KIND=JPRB), ALLOCATABLE :: VAH(:)
END TYPE TVAB

TYPE TVERTICAL_GEOM
  TYPE(TVAB) :: YRVAB 
END TYPE TVERTICAL_GEOM

TYPE, PUBLIC :: GEOMETRY
  TYPE(TVERTICAL_GEOM) :: YRVERT_GEOM
END TYPE GEOMETRY

END MODULE TYPE_GEOMETRY1
