MODULE VARIABLE_MODULE1

USE FIELD_MODULE1, ONLY: FIELD_2RB, FIELD_3RB, FIELD_4RB

IMPLICIT NONE

INTEGER, PARAMETER, PRIVATE :: JPIM = 4, JPRB = 8

TYPE, ABSTRACT :: VARIABLE_BASE
  
  

  
  CHARACTER(LEN=16)  :: NAME                  
  CHARACTER(LEN=16)  :: CNAME     = ''        
  INTEGER(KIND=JPIM) :: IGRBCODE  = -999      

  
  LOGICAL            :: LACTIVE   = .FALSE.   
  LOGICAL            :: LT1       = .FALSE.   
  LOGICAL            :: LT9       = .FALSE.   
  LOGICAL            :: LPH9      = .FALSE.   
  LOGICAL            :: LDL       = .FALSE.   
  LOGICAL            :: LDM       = .FALSE.   
  LOGICAL            :: LDL9      = .FALSE.   
  LOGICAL            :: LDM9      = .FALSE.   
  LOGICAL            :: LPC_PH    = .FALSE.   
  LOGICAL            :: LADV      = .FALSE.   
  LOGICAL            :: LGP       = .FALSE.   
  LOGICAL            :: LWATER    = .FALSE.   
  LOGICAL            :: LTHERMACT = .FALSE.   
  LOGICAL            :: LCDERS    = .FALSE.   
  REAL (KIND=JPRB)   :: RCP       = 0._JPRB
  REAL (KIND=JPRB)   :: R         = 0._JPRB
END TYPE VARIABLE_BASE


TYPE, EXTENDS(VARIABLE_BASE) :: VARIABLE_2RB
  
  

  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P(:)  => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: T0(:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: T1(:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: T9(:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PH9(:)=> NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DL(:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DM(:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DL9(:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DM9(:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PC_PH(:) => NULL()  

  
  CLASS (FIELD_2RB), POINTER :: FT0 => NULL()  
  CLASS (FIELD_2RB), POINTER :: FT1 => NULL()  
  CLASS (FIELD_2RB), POINTER :: FT9 => NULL()  
  CLASS (FIELD_2RB), POINTER :: FPH9 => NULL() 
  CLASS (FIELD_2RB), POINTER :: FDL => NULL()  
  CLASS (FIELD_2RB), POINTER :: FDM => NULL()  
  CLASS (FIELD_2RB), POINTER :: FDL9 => NULL() 
  CLASS (FIELD_2RB), POINTER :: FDM9 => NULL() 
  CLASS (FIELD_2RB), POINTER :: FPC_PH => NULL() 

CONTAINS








END TYPE VARIABLE_2RB


TYPE, EXTENDS(VARIABLE_BASE) :: VARIABLE_3RB
  
  

  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P(:,:)  => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: T0(:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: T1(:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: T9(:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PH9(:,:)=> NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DL(:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DM(:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DL9(:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DM9(:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PC_PH(:,:) => NULL()  

  
  CLASS (FIELD_3RB), POINTER :: FT0 => NULL()  
  CLASS (FIELD_3RB), POINTER :: FT1 => NULL()  
  CLASS (FIELD_3RB), POINTER :: FT9 => NULL()  
  CLASS (FIELD_3RB), POINTER :: FPH9 => NULL() 
  CLASS (FIELD_3RB), POINTER :: FDL => NULL()  
  CLASS (FIELD_3RB), POINTER :: FDM => NULL()  
  CLASS (FIELD_3RB), POINTER :: FDL9 => NULL() 
  CLASS (FIELD_3RB), POINTER :: FDM9 => NULL() 
  CLASS (FIELD_3RB), POINTER :: FPC_PH => NULL() 

CONTAINS








END TYPE VARIABLE_3RB


TYPE, EXTENDS(VARIABLE_BASE) :: VARIABLE_4RB
  
  

  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: P(:,:,:)  => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: T0(:,:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: T1(:,:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: T9(:,:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PH9(:,:,:)=> NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DL(:,:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DM(:,:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DL9(:,:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: DM9(:,:,:) => NULL()  
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: PC_PH(:,:,:) => NULL()  

  
  CLASS (FIELD_4RB), POINTER :: FT0 => NULL()  
  CLASS (FIELD_4RB), POINTER :: FT1 => NULL()  
  CLASS (FIELD_4RB), POINTER :: FT9 => NULL()  
  CLASS (FIELD_4RB), POINTER :: FPH9 => NULL() 
  CLASS (FIELD_4RB), POINTER :: FDL => NULL()  
  CLASS (FIELD_4RB), POINTER :: FDM => NULL()  
  CLASS (FIELD_4RB), POINTER :: FDL9 => NULL() 
  CLASS (FIELD_4RB), POINTER :: FDM9 => NULL() 
  CLASS (FIELD_4RB), POINTER :: FPC_PH => NULL() 

CONTAINS








END TYPE VARIABLE_4RB


TYPE VARIABLE_CLONE_OPTS
  LOGICAL :: LT1 = .TRUE.
  LOGICAL :: LT0 = .TRUE.
  LOGICAL :: LT9 = .TRUE.
  LOGICAL :: LDER = .TRUE. 
  LOGICAL :: LACC = .FALSE.
END TYPE


END MODULE VARIABLE_MODULE1



