MODULE YOMGFL1

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8

TYPE :: TGFL

REAL(KIND=JPRB), ALLOCATABLE :: GFL   (:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: GFLT1 (:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: GFLSLP(:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: GFLPT (:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: GFLPC (:,:,:,:)

REAL(KIND=JPRB), ALLOCATABLE :: GFL5       (:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: GFLSLP5    (:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: GFL_DEPART (:,:,:,:)

LOGICAL :: LGFLT1_INIT = .FALSE.

END TYPE TGFL

CONTAINS

SUBROUTINE DOT_PROD_YOMGFL(YDGEOMETRY,FLD1,FLD2,PPROD)

USE TYPE_GEOMETRY2, ONLY : GEOMETRY
IMPLICIT NONE

TYPE(GEOMETRY),  INTENT(IN)  :: YDGEOMETRY
TYPE(TGFL),      INTENT(IN)  :: FLD1
TYPE(TGFL),      INTENT(IN)  :: FLD2
REAL(KIND=JPRB), INTENT(OUT) :: PPROD

END SUBROUTINE DOT_PROD_YOMGFL

END MODULE YOMGFL1

