MODULE YOMVERT2

IMPLICIT NONE

INTEGER, PRIVATE, PARAMETER :: JPIM = 4, JPRB = 8, JPRD = 8

TYPE TVFE
  REAL(KIND=JPRD),ALLOCATABLE :: RDERBH00 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERBH01 (:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDDERI(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDDERBF01(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RINTGW(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RDERGW(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RINTG(:,:)
  REAL(KIND=JPRD),ALLOCATABLE :: RINTC(:) 
END TYPE TVFE

TYPE TVERTICAL_GEOM
  TYPE(TVFE) :: YRVFE 
END TYPE TVERTICAL_GEOM

END MODULE YOMVERT2

