PROGRAM MAIN

TYPE TFPUSERGEO
  CHARACTER(LEN=16) :: CFPDOM = ' '
  CHARACTER(LEN=4) ::  CFPGRID = 'XXXX'
END TYPE


TYPE (TFPUSERGEO) :: YY (5)

YY (1)%CFPDOM = "GLOB25"             
YY (2)%CFPDOM = "GLOB15"
YY (3)%CFPDOM = "GLOB05"
YY (4)%CFPDOM = "EUROC25"
YY (5)%CFPDOM = "EURAT01"

CALL SUFPF (YY)

CONTAINS

SUBROUTINE SUFPF (YD)

TYPE (TFPUSERGEO), INTENT (IN) :: YD (:)

ASSOCIATE (CFPDOM => YY%CFPDOM)
PRINT *, CFPDOM
END ASSOCIATE

END SUBROUTINE

END 
