PROGRAM MAIN

IMPLICIT NONE

INTEGER, PARAMETER :: JPRB = 8, JPIM = 4

INTEGER (KIND=JPIM), PARAMETER :: KLON = 1784, KLEV = 15

REAL (KIND=JPRB) :: PDQSTS(KLON)
REAL (KIND=JPRB) :: PHTR(KLON)
REAL (KIND=JPRB) :: PHV(KLON)
REAL (KIND=JPRB) :: PNEIJ(KLON)
REAL (KIND=JPRB) :: PQ(KLON,KLEV)
REAL (KIND=JPRB) :: PQSATS(KLON)
REAL (KIND=JPRB) :: PTS(KLON)
REAL (KIND=JPRB) :: PVEG(KLON)
REAL (KIND=JPRB) :: ZCHRL(KLON)
REAL (KIND=JPRB) :: ZN2(KLON,KLEV)
REAL (KIND=JPRB) :: ZNTS(KLON)
REAL (KIND=JPRB) :: PFEVV(KLON)
REAL (KIND=JPRB) :: PFTR(KLON)

INTEGER (KIND=JPIM) :: JLON0

JLON0 = 379

PDQSTS(JLON0)   =  0.49964884039612128888E-03_JPRB
PHTR(JLON0)     =  0.38085267891188268052E-01_JPRB
PHV(JLON0)      =  0.76813364703706143999E+00_JPRB
PNEIJ(JLON0)    =  0.00000000000000000000E+00_JPRB
PQ(JLON0,KLEV)  =  0.73855637139086304996E-02_JPRB
PQSATS(JLON0)   =  0.73858277258641294102E-02_JPRB
PTS(JLON0)      =  0.28240313554306339938E+03_JPRB
PVEG(JLON0)     =  0.46245753765106201172E+00_JPRB
ZCHRL(JLON0)    =  0.54928912960451464764E-01_JPRB
ZN2(JLON0,KLEV) =  0.73855641410280762141E-02_JPRB
ZNTS(JLON0)     =  0.28240469748639668524E+03_JPRB

CALL ARP_GROUND_PARAM (JLON0, JLON0, KLON, KLEV, &
& PDQSTS, PHTR, PHV, PNEIJ, PQ, PQSATS, PTS, PVEG, ZCHRL, ZN2, ZNTS, PFEVV, PFTR)

CALL ARP_GROUND_PARAM_OPENACC (JLON0, JLON0, KLON, KLEV, &
& PDQSTS, PHTR, PHV, PNEIJ, PQ, PQSATS, PTS, PVEG, ZCHRL (JLON0), ZN2, ZNTS (JLON0), PFEVV, PFTR)

CONTAINS

SUBROUTINE ARP_GROUND_PARAM (KIDIA, KFDIA, KLON, KLEV, &
& PDQSTS, PHTR, PHV, PNEIJ, PQ, PQSATS, PTS, PVEG, ZCHRL, ZN2, ZNTS, PFEVV, PFTR)

INTEGER :: KIDIA, KFDIA, KLON, KLEV

REAL (KIND=JPRB) :: PDQSTS(KLON)
REAL (KIND=JPRB) :: PHTR(KLON)
REAL (KIND=JPRB) :: PHV(KLON)
REAL (KIND=JPRB) :: PNEIJ(KLON)
REAL (KIND=JPRB) :: PQ(KLON,KLEV)
REAL (KIND=JPRB) :: PQSATS(KLON)
REAL (KIND=JPRB) :: PTS(KLON)
REAL (KIND=JPRB) :: PVEG(KLON)
REAL (KIND=JPRB) :: ZCHRL(KLON)
REAL (KIND=JPRB) :: ZN2(KLON,KLEV)
REAL (KIND=JPRB) :: ZNTS(KLON)
REAL (KIND=JPRB) :: PFEVV(KLON)
REAL (KIND=JPRB) :: PFTR(KLON)

DO JLON = KIDIA, KFDIA

PFEVV(JLON)=ZCHRL(JLON)*PVEG(JLON)*(PHV(JLON)-PNEIJ(JLON))&
 & *(ZN2(JLON,KLEV)-PQSATS(JLON)-PDQSTS(JLON)&
 & *(ZNTS(JLON)-PTS(JLON)))  
PFTR(JLON)=MAX(0.0_JPRB,SIGN(1.0_JPRB,PQSATS(JLON)-PQ(JLON,KLEV)))&
 & *ZCHRL(JLON)*PHTR(JLON)*PVEG(JLON)*(1.0_JPRB-PNEIJ(JLON))&
 & *(ZN2(JLON,KLEV)-PQSATS(JLON)-PDQSTS(JLON)&
 & *(ZNTS(JLON)-PTS(JLON)))  

WRITE (0, '(" PFEVV = ",E30.20," PFTR = ",E30.20)') PFEVV(JLON), PFTR(JLON)

ENDDO

END SUBROUTINE

SUBROUTINE ARP_GROUND_PARAM_OPENACC (KIDIA, KFDIA, KLON, KLEV, &
& PDQSTS, PHTR, PHV, PNEIJ, PQ, PQSATS, PTS, PVEG, ZCHRL, ZN2, ZNTS, PFEVV, PFTR)

INTEGER :: KIDIA, KFDIA, KLON, KLEV

REAL (KIND=JPRB) :: PDQSTS(KLON)
REAL (KIND=JPRB) :: PHTR(KLON)
REAL (KIND=JPRB) :: PHV(KLON)
REAL (KIND=JPRB) :: PNEIJ(KLON)
REAL (KIND=JPRB) :: PQ(KLON,KLEV)
REAL (KIND=JPRB) :: PQSATS(KLON)
REAL (KIND=JPRB) :: PTS(KLON)
REAL (KIND=JPRB) :: PVEG(KLON)
REAL (KIND=JPRB) :: ZCHRL
REAL (KIND=JPRB) :: ZN2(KLON,KLEV)
REAL (KIND=JPRB) :: ZNTS
REAL (KIND=JPRB) :: PFEVV(KLON)
REAL (KIND=JPRB) :: PFTR(KLON)

INTEGER (KIND=JPIM) :: JLON

JLON = KIDIA

PFEVV(JLON)=ZCHRL      *PVEG(JLON)*(PHV(JLON)-PNEIJ(JLON))&
 & *(ZN2(JLON,KLEV)-PQSATS(JLON)-PDQSTS(JLON)&
 & *(ZNTS      -PTS(JLON)))  
PFTR(JLON)=MAX(0.0_JPRB,SIGN(1.0_JPRB,PQSATS(JLON)-PQ(JLON,KLEV)))&
 & *ZCHRL      *PHTR(JLON)*PVEG(JLON)*(1.0_JPRB-PNEIJ(JLON))&
 & *(ZN2(JLON,KLEV)-PQSATS(JLON)-PDQSTS(JLON)&
 & *(ZNTS      -PTS(JLON)))  

WRITE (0, '(" PFEVV = ",E30.20," PFTR = ",E30.20)') PFEVV(JLON), PFTR(JLON)

END SUBROUTINE

END
