PROGRAM MAIN

IMPLICIT NONE

INTEGER, PARAMETER :: JPRB = 8, JPIM = 4

INTEGER (KIND=JPIM), PARAMETER :: KLON = 1784, KLEV = 15

REAL (KIND=JPRB) :: PDQSTS(KLON)
REAL (KIND=JPRB) :: PHTR(KLON)
REAL (KIND=JPRB) :: PHV(KLON)
REAL (KIND=JPRB) :: PNEIJ(KLON)
REAL (KIND=JPRB) :: PQ(KLON,KLEV)
REAL (KIND=JPRB) :: PQSATS(KLON)
REAL (KIND=JPRB) :: PTS(KLON)
REAL (KIND=JPRB) :: PVEG(KLON)
REAL (KIND=JPRB) :: ZCHRL(KLON)
REAL (KIND=JPRB) :: ZN2(KLON,KLEV)
REAL (KIND=JPRB) :: ZNTS(KLON)
REAL (KIND=JPRB) :: PFEVV(KLON)
REAL (KIND=JPRB) :: PFTR(KLON)

INTEGER (KIND=JPIM) :: JLON

JLON = 379

OPEN (77, FORM='UNFORMATTED')
READ (77) PDQSTS(JLON)
READ (77) PHTR(JLON)
READ (77) PHV(JLON)
READ (77) PNEIJ(JLON)
READ (77) PQ(JLON,KLEV)
READ (77) PQSATS(JLON)
READ (77) PTS(JLON)
READ (77) PVEG(JLON)
READ (77) ZCHRL(JLON)
READ (77) ZN2(JLON,KLEV)
READ (77) ZNTS(JLON)
CLOSE (77)

CALL ARP_GROUND_PARAM (379, 379, KLON, KLEV, &
& PDQSTS, PHTR, PHV, PNEIJ, PQ, PQSATS, PTS, PVEG, ZCHRL, ZN2, ZNTS, PFEVV, PFTR)

JLON = 379

OPEN (77, FORM='UNFORMATTED')
READ (77) PDQSTS(JLON)
READ (77) PHTR(JLON)
READ (77) PHV(JLON)
READ (77) PNEIJ(JLON)
READ (77) PQ(JLON,KLEV)
READ (77) PQSATS(JLON)
READ (77) PTS(JLON)
READ (77) PVEG(JLON)
READ (77) ZCHRL(JLON)
READ (77) ZN2(JLON,KLEV)
READ (77) ZNTS(JLON)
CLOSE (77)

CALL ARP_GROUND_PARAM_OPENACC (379, 379, KLON, KLEV, &
& PDQSTS, PHTR, PHV, PNEIJ, PQ, PQSATS, PTS, PVEG, ZCHRL (JLON), ZN2, ZNTS (JLON), PFEVV, PFTR)

CONTAINS

SUBROUTINE ARP_GROUND_PARAM (KIDIA, KFDIA, KLON, KLEV, &
& PDQSTS, PHTR, PHV, PNEIJ, PQ, PQSATS, PTS, PVEG, ZCHRL, ZN2, ZNTS, PFEVV, PFTR)

INTEGER :: KIDIA, KFDIA, KLON, KLEV

REAL (KIND=JPRB) :: PDQSTS(KLON)
REAL (KIND=JPRB) :: PHTR(KLON)
REAL (KIND=JPRB) :: PHV(KLON)
REAL (KIND=JPRB) :: PNEIJ(KLON)
REAL (KIND=JPRB) :: PQ(KLON,KLEV)
REAL (KIND=JPRB) :: PQSATS(KLON)
REAL (KIND=JPRB) :: PTS(KLON)
REAL (KIND=JPRB) :: PVEG(KLON)
REAL (KIND=JPRB) :: ZCHRL(KLON)
REAL (KIND=JPRB) :: ZN2(KLON,KLEV)
REAL (KIND=JPRB) :: ZNTS(KLON)
REAL (KIND=JPRB) :: PFEVV(KLON)
REAL (KIND=JPRB) :: PFTR(KLON)

DO JLON = KIDIA, KFDIA

PFEVV(JLON)=ZCHRL(JLON)*PVEG(JLON)*(PHV(JLON)-PNEIJ(JLON))&
 & *(ZN2(JLON,KLEV)-PQSATS(JLON)-PDQSTS(JLON)&
 & *(ZNTS(JLON)-PTS(JLON)))  
PFTR(JLON)=MAX(0.0_JPRB,SIGN(1.0_JPRB,PQSATS(JLON)-PQ(JLON,KLEV)))&
 & *ZCHRL(JLON)*PHTR(JLON)*PVEG(JLON)*(1.0_JPRB-PNEIJ(JLON))&
 & *(ZN2(JLON,KLEV)-PQSATS(JLON)-PDQSTS(JLON)&
 & *(ZNTS(JLON)-PTS(JLON)))  

IF (JLON == 379) THEN
  WRITE (0, '(" PFEVV = ",E30.20," PFTR = ",E30.20)') PFEVV(JLON), PFTR(JLON)
ENDIF

ENDDO

END SUBROUTINE

SUBROUTINE ARP_GROUND_PARAM_OPENACC (KIDIA, KFDIA, KLON, KLEV, &
& PDQSTS, PHTR, PHV, PNEIJ, PQ, PQSATS, PTS, PVEG, ZCHRL, ZN2, ZNTS, PFEVV, PFTR)

INTEGER :: KIDIA, KFDIA, KLON, KLEV

REAL (KIND=JPRB) :: PDQSTS(KLON)
REAL (KIND=JPRB) :: PHTR(KLON)
REAL (KIND=JPRB) :: PHV(KLON)
REAL (KIND=JPRB) :: PNEIJ(KLON)
REAL (KIND=JPRB) :: PQ(KLON,KLEV)
REAL (KIND=JPRB) :: PQSATS(KLON)
REAL (KIND=JPRB) :: PTS(KLON)
REAL (KIND=JPRB) :: PVEG(KLON)
REAL (KIND=JPRB) :: ZCHRL
REAL (KIND=JPRB) :: ZN2(KLON,KLEV)
REAL (KIND=JPRB) :: ZNTS
REAL (KIND=JPRB) :: PFEVV(KLON)
REAL (KIND=JPRB) :: PFTR(KLON)

INTEGER (KIND=JPIM) :: JLON

JLON = KIDIA

PFEVV (JLON)=ZCHRL *PVEG (JLON)*(PHV (JLON)-PNEIJ (JLON))&
 & *(ZN2 (JLON, KLEV)-PQSATS (JLON)-PDQSTS (JLON)&
 & *(ZNTS -PTS (JLON)))
PFTR (JLON)=MAX (0.0_JPRB, SIGN (1.0_JPRB, PQSATS (JLON)-PQ (JLON, KLEV)))&
 & *ZCHRL *PHTR (JLON)*PVEG (JLON)*(1.0_JPRB-PNEIJ (JLON))&
 & *(ZN2 (JLON, KLEV)-PQSATS (JLON)-PDQSTS (JLON)&
 & *(ZNTS -PTS (JLON)))

WRITE (0, '(" PFEVV = ",E30.20," PFTR = ",E30.20)') PFEVV(JLON), PFTR(JLON)

END SUBROUTINE

END
