PROGRAM MASTER

USE RADIATION_AEROSOL_OPTICS_DATA2, ONLY : AEROSOL_OPTICS_TYPE
USE RADIATION_CONFIG2             , ONLY : config_type

USE PARKIND1

IMPLICIT NONE

TYPE :: MODEL
  type(config_type)  :: rad_config
END TYPE MODEL

TYPE (MODEL) :: YLMODEL

!$ACC ENTER DATA CREATE (YLMODEL)
!$ACC UPDATE DEVICE (YLMODEL)

!$ACC SERIAL DEFAULT(NONE) PRESENT (YLMODEL)
call zut (YLMODEL%rad_config%aerosol_optics)
!$ACC END SERIAL

CONTAINS

SUBROUTINE ZUT(THIS)

!$ACC ROUTINE SEQ

CLASS (AEROSOL_OPTICS_TYPE) :: THIS

END SUBROUTINE ZUT

END PROGRAM MASTER
