SUBROUTINE LARCINB1(PLSCAW)

IMPLICIT NONE

REAL(KIND=8)               ,INTENT(IN)     :: PLSCAW(2:1784+1,3:15+2,4:12+3)

WRITE (0, *) __FILE__, ':', __LINE__, " LOC (PLSCAW (2,3,4)) = ", LOC (PLSCAW (2,3,4))

WRITE (0, *) __FILE__, ':', __LINE__; CALL FLUSH (0)

END SUBROUTINE LARCINB1

