PROGRAM DIR_TRANS_CTL

USE TRLTOM_PACK_UNPACK,     ONLY: TRLTOM_PACK
USE TPM_DISTR,              ONLY: D

IMPLICIT NONE

REAL, POINTER :: PREEL_COMPLEX(:), FOUBUF_IN(:)

ALLOCATE(D%NLOEN(6))
D%NLOEN(:) = (/20,24,28,28,24,20/)
ALLOCATE (D%NMEN(6))
D%NMEN=(/2,2,2,2,2,2/)
ALLOCATE(D%NPNTGTB0(0:2,6))
D%NPNTGTB0=RESHAPE((/0:17:1/),SHAPE(D%NPNTGTB0))
ALLOCATE(D%NSTAGTF(7))
D%NSTAGTF=(/0,22,48,78,108,134,156/)

!$ACC ENTER DATA COPYIN(D,D%NPNTGTB0,D%NSTAGTF,D%NLOEN,D%NMEN) 
!$ACC WAIT(1)

ALLOCATE(PREEL_COMPLEX(31*156))
ALLOCATE(FOUBUF_IN(2*18*31))
PREEL_COMPLEX(:)=1.
FOUBUF_IN(:)=0.

!$ACC DATA COPY(PREEL_COMPLEX,FOUBUF_IN)
CALL TRLTOM_PACK(PREEL_COMPLEX,FOUBUF_IN,31)
!$ACC END DATA

WRITE (0,*) "SUM(ABS(FOUBUF_IN))",SUM(ABS(FOUBUF_IN(:)))

END PROGRAM DIR_TRANS_CTL
