MODULE TPM_DISTR

IMPLICIT NONE

SAVE

TYPE DISTR_TYPE
INTEGER ,ALLOCATABLE  :: NSTAGTF(:)             
INTEGER ,ALLOCATABLE :: NPNTGTB0(:,:)
INTEGER ,ALLOCATABLE :: NLOEN(:) 
INTEGER ,ALLOCATABLE :: NMEN(:) 
END TYPE DISTR_TYPE

TYPE(DISTR_TYPE) :: D

END MODULE TPM_DISTR

