MODULE TRLTOM_PACK_UNPACK
  IMPLICIT NONE

  PRIVATE
  PUBLIC :: TRLTOM_PACK


CONTAINS

  SUBROUTINE TRLTOM_PACK(PREEL_COMPLEX,FOUBUF_IN,KF_FS)
    USE TPM_DISTR,              ONLY: D

    IMPLICIT NONE

    REAL, INTENT(IN), POINTER :: PREEL_COMPLEX(:)
    REAL, POINTER, INTENT(INOUT) :: FOUBUF_IN(:)
    INTEGER,INTENT(IN) :: KF_FS

    INTEGER :: JM,JF,IGLG,OFFSET_VAR,KGL
    INTEGER :: IOFF_LAT,ISTA, NMEN_MAX

    REAL    :: SCAL
    INTEGER  :: D_NDGL_FS=6

    ASSOCIATE(D_NSTAGTF=>D%NSTAGTF, D_NPNTGTB0=>D%NPNTGTB0, &
            & G_NMEN=>D%NMEN, G_NLOEN=>D%NLOEN)

    !$ACC DATA PRESENT(D,G_NMEN,D_NPNTGTB0,FOUBUF_IN,PREEL_COMPLEX,D_NSTAGTF,G_NLOEN) 

    OFFSET_VAR=1
    
    NMEN_MAX=MAXVAL(G_NMEN)

    !$ACC PARALLEL LOOP PRIVATE(IGLG,IOFF_LAT,ISTA,SCAL) FIRSTPRIVATE(KF_FS,OFFSET_VAR) &
    !$ACC& TILE(32,16,1) DEFAULT(NONE) 
    DO KGL=1,D_NDGL_FS
      DO JM=0,NMEN_MAX
        DO JF=1,KF_FS
          IGLG = OFFSET_VAR+KGL-1
          IF (JM <= G_NMEN(IGLG)) THEN
            IOFF_LAT = KF_FS*D_NSTAGTF(KGL)+(JF-1)*(D_NSTAGTF(KGL+1)-D_NSTAGTF(KGL))

            SCAL = 1./REAL(G_NLOEN(IGLG))
            ISTA  = 2*D_NPNTGTB0(JM,KGL)*KF_FS

            FOUBUF_IN(ISTA+2*JF-1) = SCAL * PREEL_COMPLEX(IOFF_LAT+2*JM+1)
            FOUBUF_IN(ISTA+2*JF  ) = SCAL * PREEL_COMPLEX(IOFF_LAT+2*JM+2)
          ENDIF
        ENDDO
      ENDDO
    ENDDO
    !$ACC END DATA

    END ASSOCIATE
  END SUBROUTINE TRLTOM_PACK

END MODULE TRLTOM_PACK_UNPACK

