INTERFACE
SUBROUTINE LARCINB1(PLSCAW, PRSCAW)

IMPLICIT NONE

REAL(KIND=8)               ,INTENT(IN)     :: PLSCAW(1784,15,12)
REAL(KIND=8)               ,INTENT(IN)     :: PRSCAW(1784,15,36)

END SUBROUTINE LARCINB1
END INTERFACE
