PROGRAM MAIN

IMPLICIT NONE

#include "larcinb1.intfb.h"

TYPE FIELD_4RB
  REAL(KIND=8), POINTER :: PTR (:,:,:,:)
END TYPE

TYPE FIELD_4RB_ARRAY
  TYPE (FIELD_4RB) :: F_P
  REAL (KIND=8), POINTER :: P (:,:,:)
END TYPE

TYPE(FIELD_4RB_ARRAY)  :: YLA_PLSCAW1
TYPE(FIELD_4RB_ARRAY)  :: YLA_PRSCAW1

REAL(KIND=8), TARGET :: ZLSCAW1(1784,15,12,1)
REAL(KIND=8), TARGET :: ZRSCAW1(1784,15,36,1)

YLA_PLSCAW1%F_P%PTR => ZLSCAW1
YLA_PRSCAW1%F_P%PTR => ZRSCAW1

WRITE (0, *) __FILE__, ':', __LINE__, " LOC (ZRSCAW1(1,1,1,1)) = ", LOC (ZRSCAW1(1,1,1,1))
WRITE (0, *) __FILE__, ':', __LINE__, " LOC (ZLSCAW1(1,1,1,1)) = ", LOC (ZLSCAW1(1,1,1,1))

YLA_PLSCAW1%P => YLA_PLSCAW1%F_P%PTR (:,:,:,1)
YLA_PRSCAW1%P => YLA_PRSCAW1%F_P%PTR (:,:,:,1)

WRITE (0, *) __FILE__, ':', __LINE__, " LOC (YLA_PLSCAW1%P(1,1,1) = ", LOC (YLA_PLSCAW1%P(1,1,1))
WRITE (0, *) __FILE__, ':', __LINE__, " LOC (YLA_PRSCAW1%P(1,1,1) = ", LOC (YLA_PRSCAW1%P(1,1,1))

CALL LARCINB1(YLA_PLSCAW1%P,YLA_PRSCAW1%P)

YLA_PLSCAW1%P (1:,1:,1:) => YLA_PLSCAW1%F_P%PTR (:,:,:,1)
YLA_PRSCAW1%P (1:,1:,1:) => YLA_PRSCAW1%F_P%PTR (:,:,:,1)

WRITE (0, *) __FILE__, ':', __LINE__, " LOC (YLA_PLSCAW1%P(1,1,1) = ", LOC (YLA_PLSCAW1%P(1,1,1))
WRITE (0, *) __FILE__, ':', __LINE__, " LOC (YLA_PRSCAW1%P(1,1,1) = ", LOC (YLA_PRSCAW1%P(1,1,1))

CALL LARCINB1(YLA_PLSCAW1%P,YLA_PRSCAW1%P)

END 
