PROGRAM MAIN

USE MODD_DIMPHYEX, ONLY : DIMPHYEX_t
use openacc



IMPLICIT NONE

TYPE(DIMPHYEX_t) :: DD,D
INTERFACE
  SUBROUTINE ROUTINE_MANYBLOCKS(D,TAB1,TAB2)
    USE MODD_DIMPHYEX, ONLY : DIMPHYEX_t
    IMPLICIT NONE
    TYPE(DIMPHYEX_t), INTENT(IN) :: D
    REAL, INTENT(INOUT) :: TAB1(:,:)
    REAL, INTENT(INOUT) :: TAB2(:,:)
  END SUBROUTINE ROUTINE_MANYBLOCKS
END INTERFACE
INTERFACE
  SUBROUTINE ROUTINE_OPENACC(D,TAB1,TAB2)
    !$ACC ROUTINE (ROUTINE_OPENACC) SEQ
    USE MODD_DIMPHYEX, ONLY : DIMPHYEX_t
    IMPLICIT NONE
    TYPE(DIMPHYEX_t), INTENT(IN) :: D
    REAL, INTENT(INOUT) :: TAB1(:)
    REAL, INTENT(INOUT) :: TAB2(:)
  END SUBROUTINE ROUTINE_OPENACC
END INTERFACE

INTEGER, PARAMETER :: NFLEVG=105
INTEGER, PARAMETER :: NSPEC=1000
REAL :: TAB1(NSPEC,NFLEVG)
REAL :: TAB2(NSPEC,NFLEVG)
INTEGER :: JLON, JBLK

D%NIT=NFLEVG
D%NIB=1
D%NIE=NSPEC

TAB1=1.
TAB2=2.

!$ACC PARALLEL LOOP GANG COPYIN(D) COPY(TAB1,TAB2) PRIVATE(JBLK)
DO JBLK=1,NFLEVG

  !$ACC LOOP VECTOR PRIVATE(DD,JLON)
  DO JLON=1,NSPEC
    DD=D
    DD%NIB=JLON
    DD%NIE=JLON
    CALL ROUTINE_OPENACC(DD,TAB1(:,JBLK),TAB2(:,JBLK))

  ENDDO
ENDDO

write (0,*) TAB1(1,1)

DD=D

!$ACC DATA COPYIN(DD)
write (0,*) "dd is present",acc_is_present(dd,8)
CALL ROUTINE_MANYBLOCKS(DD,TAB1,TAB2)
!$ACC END DATA

write (0,*) TAB1(1,1)

END PROGRAM MAIN
