SUBROUTINE ROUTINE_OPENACC(D,TAB1,TAB2)
!$ACC ROUTINE (ROUTINE_OPENACC) SEQ

USE MODD_DIMPHYEX, ONLY : DIMPHYEX_t

IMPLICIT NONE

TYPE(DIMPHYEX_t), INTENT(IN) :: D
REAL, INTENT(INOUT) :: TAB1(:)
REAL, INTENT(INOUT) :: TAB2(:)

INTEGER :: JLEV, JSP, JI

JI=D%NIB

TAB1(JI)=TAB2(JI)-2.0


END SUBROUTINE ROUTINE_OPENACC
