SUBROUTINE ROUTINE_MANYBLOCKS(D,TAB1,TAB2)

USE MODD_DIMPHYEX, ONLY : DIMPHYEX_t

IMPLICIT NONE

TYPE(DIMPHYEX_t), INTENT(IN) :: D
REAL, INTENT(INOUT) :: TAB1(:,:)
REAL, INTENT(INOUT) :: TAB2(:,:)

INTEGER :: JLEV, JSP

!$ACC PARALLEL LOOP GANG VECTOR PRESENT(D) COPY(TAB1,TAB2)
DO JSP=D%NIB,D%NIE
  DO JLEV=1,D%NIT
    TAB1(JSP,JLEV)=TAB2(JSP,JLEV)-2.0
  ENDDO
ENDDO
!$ACC END PARALLEL


END SUBROUTINE ROUTINE_MANYBLOCKS
