MODULE FIELD_BASIC_MODULE

USE PARKIND1, ONLY : JPIM

IMPLICIT NONE

TYPE, ABSTRACT :: FIELD_BASIC
  INTEGER(KIND=JPIM) :: ISTATUS = 0
CONTAINS
  PROCEDURE :: SET_STATUS => FIELD_BASIC_SET_STATUS
END TYPE FIELD_BASIC

PUBLIC :: FIELD_BASIC

CONTAINS

SUBROUTINE FIELD_BASIC_SET_STATUS (SELF, KSTATUS)

CLASS (FIELD_BASIC) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

PRINT *, "FIELD_BASIC_SET_STATUS"

END SUBROUTINE FIELD_BASIC_SET_STATUS

END MODULE FIELD_BASIC_MODULE
