MODULE FIELD_4RD_MODULE


USE FIELD_BASIC_MODULE
USE PARKIND1

IMPLICIT NONE

TYPE, ABSTRACT, EXTENDS (FIELD_BASIC) :: FIELD_4RD
CONTAINS
END TYPE FIELD_4RD

TYPE, EXTENDS(FIELD_4RD) :: FIELD_4RD_OWNER
CONTAINS
#ifdef __PGI
  PROCEDURE :: SET_STATUS => FIELD_4RD_OWNER_SET_STATUS
#endif
END TYPE FIELD_4RD_OWNER

CONTAINS

#ifdef __PGI
  SUBROUTINE FIELD_4RD_OWNER_SET_STATUS (SELF, KSTATUS)
    CLASS(FIELD_4RD_OWNER) :: SELF
    INTEGER (KIND=JPIM), INTENT (IN) :: KSTATUS

  END SUBROUTINE
#endif

END MODULE FIELD_4RD_MODULE
