MODULE FIELD_4RD_MODULE


USE FIELD_BASIC_MODULE
USE PARKIND1

IMPLICIT NONE

TYPE, ABSTRACT, EXTENDS (FIELD_BASIC) :: FIELD_4RD
CONTAINS

END TYPE FIELD_4RD

TYPE, EXTENDS(FIELD_4RD) :: FIELD_4RD_OWNER
CONTAINS
END TYPE FIELD_4RD_OWNER

END MODULE FIELD_4RD_MODULE
