SUBROUTINE LIN (KLON, KGPBLKS, PX, PY)

USE NVTX

IMPLICIT NONE

INTEGER, INTENT (IN) :: KLON, KGPBLKS
REAL, INTENT (IN) :: PX (:,:)
REAL, INTENT (INOUT) :: PY (:,:)

INTEGER :: JLON, JBLK

INTERFACE
SUBROUTINE LIN1 (KLON, JLON, PX, PY)
!$ACC ROUTINE SEQ
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLON, JLON
REAL, INTENT (IN) :: PX (KLON)
REAL, INTENT (INOUT) :: PY (KLON)
END SUBROUTINE
END INTERFACE

CALL NVTXSTARTRANGE ("LIN")

!$ACC DATA PRESENT (PX, PY)

CALL NVTXSTARTRANGE ("LIN:LOOP")

!$ACC PARALLEL LOOP GANG VECTOR COLLAPSE (2)
DO JBLK = 1, KGPBLKS
  DO JLON = 1, KLON
    CALL LIN1 (KLON, JLON, PX (:, JBLK), PY (:, JBLK))
!   PY (JLON, JBLK) = 3 * PX (JLON, JBLK)
  ENDDO
ENDDO

CALL NVTXENDRANGE

!$ACC END DATA

CALL NVTXENDRANGE

END SUBROUTINE
