SUBROUTINE LIN1A (KLON, KFLEVG, JLON, PX_A, PY_A)

!$ACC ROUTINE SEQ

IMPLICIT NONE

INTEGER, INTENT (IN) :: KLON, KFLEVG, JLON
REAL, INTENT (IN) :: PX_A
REAL, INTENT (INOUT) :: PY_A

REAL :: PX (KLON,KFLEVG); POINTER (IP_PX, PX)
REAL :: PY (KLON,KFLEVG); POINTER (IP_PY, PY)

INTEGER :: JLEV

IP_PX = LOC (PX_A)
IP_PY = LOC (PY_A)

DO JLEV = 1, KFLEVG
  PY (JLON, JLEV) = 3 * PX (JLON, JLEV)
ENDDO

END SUBROUTINE
