SUBROUTINE LIN1A (KLON, KFLEVG, JLON, PX, PY)

!$ACC ROUTINE SEQ

IMPLICIT NONE

INTEGER, INTENT (IN) :: KLON, KFLEVG, JLON
REAL, INTENT (IN) :: PX (KLON,KFLEVG)
REAL, INTENT (INOUT) :: PY (KLON,KFLEVG)

INTEGER :: JLEV

DO JLEV = 1, KFLEVG
  PY (JLON, JLEV) = 3 * PX (JLON, JLEV)
ENDDO

END SUBROUTINE
