SUBROUTINE LIN1 (KLON, JLON, PX, PY)

!$ACC ROUTINE SEQ

IMPLICIT NONE

INTEGER, INTENT (IN) :: KLON, JLON
REAL, INTENT (IN) :: PX (KLON)
REAL, INTENT (INOUT) :: PY (KLON)

PY (JLON) = 3 * PX (JLON)

END SUBROUTINE
