SUBROUTINE LINA (KLON, KFLEVG, KGPBLKS, PX, PY)

USE NVTX

IMPLICIT NONE

INTEGER, INTENT (IN) :: KLON, KFLEVG, KGPBLKS
REAL, INTENT (IN) :: PX (:,:,:)
REAL, INTENT (INOUT) :: PY (:,:,:)

INTEGER :: JLON, JBLK

INTERFACE
SUBROUTINE LIN1A (KLON, JLON, KFLEVG, PX, PY)
!$ACC ROUTINE SEQ
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLON, KFLEVG, JLON
REAL, INTENT (IN) :: PX (KLON,KFLEVG)
REAL, INTENT (INOUT) :: PY (KLON,KFLEVG)
END SUBROUTINE
END INTERFACE

CALL NVTXSTARTRANGE ("LINA")

!$ACC DATA PRESENT (PX, PY)

CALL NVTXSTARTRANGE ("LINA:LOOP")

!$ACC PARALLEL LOOP GANG VECTOR COLLAPSE (2)
DO JBLK = 1, KGPBLKS
  DO JLON = 1, KLON
    CALL LIN1A (KLON, JLON, KFLEVG, PX (:, :, JBLK), PY (:, :, JBLK))
!   PY (JLON, JBLK) = 3 * PX (JLON, JBLK)
  ENDDO
ENDDO

CALL NVTXENDRANGE

!$ACC END DATA

CALL NVTXENDRANGE

END SUBROUTINE
