SUBROUTINE LINA (KLON, KFLEVG, KGPBLKS, PX, PY)

#ifdef __PGI
USE NVTX
#endif

IMPLICIT NONE

INTEGER, INTENT (IN) :: KLON, KFLEVG, KGPBLKS
REAL, INTENT (IN) :: PX (:,:,:)
REAL, INTENT (INOUT) :: PY (:,:,:)

INTEGER :: JLON, JBLK

INTERFACE
SUBROUTINE LIN1A (KLON, JLON, KFLEVG, PX, PY)
!$ACC ROUTINE SEQ
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLON, KFLEVG, JLON
REAL, INTENT (IN) :: PX (KLON,KFLEVG)
REAL, INTENT (INOUT) :: PY (KLON,KFLEVG)
END SUBROUTINE
END INTERFACE

#ifdef __PGI
CALL NVTXSTARTRANGE ("LINA")
#endif

!$ACC DATA PRESENT (PX, PY)

#ifdef __PGI
CALL NVTXSTARTRANGE ("LINA:LOOP")
#endif

!$ACC PARALLEL LOOP GANG VECTOR COLLAPSE (2)
DO JBLK = 1, KGPBLKS
  DO JLON = 1, KLON
    CALL LIN1A (KLON, JLON, KFLEVG, PX (:, :, JBLK), PY (:, :, JBLK))
!   PY (JLON, JBLK) = 3 * PX (JLON, JBLK)
  ENDDO
ENDDO

#ifdef __PGI
CALL NVTXENDRANGE
#endif

!$ACC END DATA

#ifdef __PGI
CALL NVTXENDRANGE
#endif

END SUBROUTINE
