SUBROUTINE LINA (KLON, KFLEVG, KGPBLKS, PX, PY)

#ifdef __PGI
USE NVTX
#endif

IMPLICIT NONE

INTEGER, INTENT (IN) :: KLON, KFLEVG, KGPBLKS
REAL, INTENT (IN) :: PX (:,:,:)
REAL, INTENT (INOUT) :: PY (:,:,:)

INTEGER :: JLON, JBLK

INTERFACE
SUBROUTINE LIN1A (KLON, KFLEVG, JLON, PX_A, PY_A)
!$ACC ROUTINE SEQ
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLON, KFLEVG, JLON
REAL, INTENT (IN) :: PX_A
REAL, INTENT (INOUT) :: PY_A
END SUBROUTINE
END INTERFACE

#ifdef __PGI
CALL NVTXSTARTRANGE ("LINA")
#endif

!$ACC DATA PRESENT (PX, PY)

#ifdef __PGI
CALL NVTXSTARTRANGE ("LINA:LOOP")
#endif

!$ACC PARALLEL LOOP GANG VECTOR COLLAPSE (2)
DO JBLK = 1, KGPBLKS
  DO JLON = 1, KLON
    CALL LIN1A (KLON, KFLEVG, JLON, PX (1, 1, JBLK), PY (1, 1, JBLK))
  ENDDO
ENDDO

#ifdef __PGI
CALL NVTXENDRANGE
#endif

!$ACC END DATA

#ifdef __PGI
CALL NVTXENDRANGE
#endif

END SUBROUTINE
