PROGRAM MAIN

USE NVTX

IMPLICIT NONE

INTEGER :: NPROMA, NFLEVG, NGPBLKS
INTEGER :: JLON, JLEV, JBLK

REAL, ALLOCATABLE :: X (:,:,:), Y (:,:,:)

INTERFACE
SUBROUTINE LIN (KLON, KGPBLKS, PX, PY)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLON, KGPBLKS
REAL, INTENT (IN) :: PX (:,:)
REAL, INTENT (INOUT) :: PY (:,:)
END SUBROUTINE
END INTERFACE


CALL NVTXSTARTRANGE ("MAIN")

NPROMA = 32
NFLEVG = 4
NGPBLKS = 10

ALLOCATE (X (NPROMA, NFLEVG, NGPBLKS), Y (NPROMA, NFLEVG, NGPBLKS))

Y = 0

DO JBLK = 1, NGPBLKS
  DO JLEV = 1, NFLEVG
    DO JLON = 1, NPROMA 
      X (JLON, JLEV, JBLK) = JLON + 100 * JLEV + 10000 * JBLK
    ENDDO
  ENDDO
ENDDO

!$ACC DATA COPY (X, Y)

CALL LIN (NPROMA, NGPBLKS, X (:,1,:), Y (:,1,:))
CALL LIN (NPROMA, NGPBLKS, X (:,1,:), Y (:,1,:))
CALL LIN (NPROMA, NGPBLKS, X (:,1,:), Y (:,1,:))

!$ACC END DATA

CALL NVTXENDRANGE

END
