PROGRAM MAIN

#ifdef __PGI
USE NVTX
#endif

IMPLICIT NONE

INTEGER :: NPROMA, NFLEVG, NDIM, NGPBLKS
INTEGER :: JLON, JLEV, JBLK

REAL, ALLOCATABLE :: X (:,:,:), Y (:,:,:)
REAL, ALLOCATABLE :: XA (:,:,:,:), YA (:,:,:,:)

INTERFACE
SUBROUTINE LIN (KLON, KGPBLKS, PX, PY)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLON, KGPBLKS
REAL, INTENT (IN) :: PX (:,:)
REAL, INTENT (INOUT) :: PY (:,:)
END SUBROUTINE
SUBROUTINE LINA (KLON, KFLEVG, KGPBLKS, PX, PY)
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLON, KFLEVG, KGPBLKS
REAL, INTENT (IN) :: PX (:,:,:)
REAL, INTENT (INOUT) :: PY (:,:,:)
END SUBROUTINE
END INTERFACE


#ifdef __PGI
CALL NVTXSTARTRANGE ("MAIN")
#endif

NPROMA = 32
NFLEVG = 4
NDIM = 5
NGPBLKS = 10

ALLOCATE (X (NPROMA, NFLEVG, NGPBLKS), Y (NPROMA, NFLEVG, NGPBLKS))

Y = 0

DO JBLK = 1, NGPBLKS
  DO JLEV = 1, NFLEVG
    DO JLON = 1, NPROMA 
      X (JLON, JLEV, JBLK) = JLON + 100 * JLEV + 10000 * JBLK
    ENDDO
  ENDDO
ENDDO

ALLOCATE (XA (NPROMA, NFLEVG, NDIM, NGPBLKS), YA (NPROMA, NFLEVG, NDIM, NGPBLKS))

YA = 0

DO JBLK = 1, NGPBLKS
  DO JLEV = 1, NFLEVG
    DO JLON = 1, NPROMA 
      XA (JLON, JLEV, :, JBLK) = JLON + 100 * JLEV + 10000 * JBLK
    ENDDO
  ENDDO
ENDDO

!$ACC DATA COPY (X, Y, XA, YA)

CALL LIN (NPROMA, NGPBLKS, X (:,1,:), Y (:,1,:))
CALL LIN (NPROMA, NGPBLKS, X (:,1,:), Y (:,1,:))
CALL LIN (NPROMA, NGPBLKS, X (:,1,:), Y (:,1,:))

CALL LINA (NPROMA, NFLEVG, NGPBLKS, XA (:,:,1,:), YA (:,:,1,:))
CALL LINA (NPROMA, NFLEVG, NGPBLKS, XA (:,:,1,:), YA (:,:,1,:))
CALL LINA (NPROMA, NFLEVG, NGPBLKS, XA (:,:,1,:), YA (:,:,1,:))

!$ACC END DATA

#ifdef __PGI
CALL NVTXENDRANGE
#endif

END
