!OPTIONS XOPT(NOEVAL)
SUBROUTINE CHECKNAN(YDRIP,YDPHY0,YDPHY2,KIDIA,KFDIA,KLON,KLEV,KSTEP,PAPHI,PAPHIF &
& ,PAPRS,PAPRSF,PGELAM,PGEMU,PMU0,PLSM,PT,PQ,PQSAT,PTS,PDIFCQLC,PDIFCQIC,PFIMCC,PFEDQLC,PFEDQIC &
& ,PFEDQRC,PFEDQSC,PFCNEGQLC,PFCNEGQIC,PFCNEGQRC,PFCNEGQSC,PFPLCH,PDIFCQ,PDIFCQI &
& ,PDIFCQL,PDIFCS,PDIFTQ,PDIFTQI,PDIFTQL,PDIFTS,PFCCQL,PFCCQN,PFCSQL,PFCSQN,PFCQVNG &
& ,PFCQING,PFCQLNG,PFCQRNG,PFCQSNG,PFPLCL,PFPLCN,PFPLCG,PFPLSL,PFPLSN,PFPLSG &
& ,PSTRCU,PSTRCV,PSTRDU,PSTRDV,PSTRTU,PSTRTV,PSTRMU,PSTRMV,PFRMH,PFRMQ,PFCHOZ,PFPFPSL &
& ,PFPFPSN,PFPFPCL,PFPFPCN,PFPEVPSL,PFPEVPSN,PFPEVPCL,PFPEVPCN)

!**** *CHECKNAN * - Check if fluxes are different from NaN.

!**   Interface.
!     ----------
!        *CALL* *CHECKNAN*

!-----------------------------------------------------------------------
! -   ARGUMENTS D'ENTREE.
! -   INPUT ARGUMENTS.
!     -------------------

! - DIMENSIONS.

! KIDIA, KFDIA : START/END OF HORIZONTAL LOOP  (IST,IEND IN *CPG*).
! KLON : HORIZONTAL DIMENSION                  (NPROMA IN *CPG*).
! KLEV : END OF VERTICAL LOOP AND VERTICAL DIMENSION(NFLEVG IN *CPG*).

! - 2D (0:KLEV) .

! PAPHI      : GEOPOTENTIAL ON HALF-LEVELS.
! PAPRS      : PRESSURE ON HALF-LEVELS.

! - 2D (1:KLEV) .

! PAPHIF     : GEOPOTENTIAL ON FULL LEVELS.
! PAPRSF     : PRESSURE ON FULL LEVELS.
! PT         : TEMPERATURE.
! PQ         : SPECIFIC HUMIDITY OF WATER VAPOUR.
! PQSAT      : SATURATION SPECIFIC HUMIDITY OF WATER VAPOUR.

! - 1D .
! PLSM       : LAND/SEA MASK.
! PTS        : SURFACE LAYER TEMPERATURE.
!-----------------------------------------------------------------------

! -   IMPLICIT ARGUMENTS.
!     ---------------------

!-----------------------------------------------------------------------

!     Externals.
!     ----------

!     Method.
!     -------

!     Author.
!     -------
!     2021-06-23, J.M. Piriou. 

!     Modifications.
!     --------------

!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK
USE YOMPHY0  , ONLY : TPHY0
USE YOMPHY2  , ONLY : TPHY2
USE YOMLUN_IFSAUX, ONLY : NULERR
USE YOMRIP0  , ONLY : NINDAT
USE YOMRIP   , ONLY : TRIP
USE IEEE_ARITHMETIC, ONLY : ISNAN => IEEE_IS_NAN

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TPHY0)       ,INTENT(INOUT) :: YDPHY0
TYPE(TPHY2)       ,INTENT(INOUT) :: YDPHY2
TYPE(TRIP)        ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTEP
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGELAM(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGEMU(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMU0(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLSM(KLON)
REAL(KIND=JPRB)   ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN) :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN) :: PTS(KLON)

REAL(KIND=JPRB)   ,INTENT(IN), DIMENSION (KLON,0:KLEV) :: PDIFCQLC,PDIFCQIC,PFIMCC,PFEDQLC,PFEDQIC &
& ,PFEDQRC,PFEDQSC,PFCNEGQLC,PFCNEGQIC,PFCNEGQRC,PFCNEGQSC,PFPLCH,PDIFCQ,PDIFCQI &
& ,PDIFCQL,PDIFCS,PDIFTQ,PDIFTQI,PDIFTQL,PDIFTS,PFCCQL,PFCCQN,PFCSQL,PFCSQN,PFCQVNG &
& ,PFCQING,PFCQLNG,PFCQRNG,PFCQSNG,PFPLCL,PFPLCN,PFPLCG,PFPLSL,PFPLSN,PFPLSG &
& ,PSTRCU,PSTRCV,PSTRDU,PSTRDV,PSTRTU,PSTRTV,PSTRMU,PSTRMV,PFRMH,PFRMQ,PFCHOZ,PFPFPSL &
& ,PFPFPSN,PFPFPCL,PFPFPCN,PFPEVPSL,PFPEVPSN,PFPEVPCL,PFPEVPCN

REAL(KIND=JPRB), DIMENSION (KLON,0:KLEV) :: ZSUM

LOGICAL :: LLPDIFCQLC,LLPDIFCQIC,LLPFIMCC,LLPFEDQLC,LLPFEDQIC &
& ,LLPFEDQRC,LLPFEDQSC,LLPFCNEGQLC,LLPFCNEGQIC,LLPFCNEGQRC,LLPFCNEGQSC,LLPFPLCH,LLPDIFCQ,LLPDIFCQI &
& ,LLPDIFCQL,LLPDIFCS,LLPDIFTQ,LLPDIFTQI,LLPDIFTQL,LLPDIFTS,LLPFCCQL,LLPFCCQN,LLPFCSQL,LLPFCSQN,LLPFCQVNG &
& ,LLPFCQING,LLPFCQLNG,LLPFCQRNG,LLPFCQSNG,LLPFPLCL,LLPFPLCN,LLPFPLCG,LLPFPLSL,LLPFPLSN,LLPFPLSG &
& ,LLPSTRCU,LLPSTRCV,LLPSTRDU,LLPSTRDV,LLPSTRTU,LLPSTRTV,LLPSTRMU,LLPSTRMV,LLPFRMH,LLPFRMQ,LLPFCHOZ,LLPFPFPSL &
& ,LLPFPFPSN,LLPFPFPCL,LLPFPFPCN,LLPFPEVPSL,LLPFPEVPSN,LLPFPEVPCL,LLPFPEVPCN

REAL(KIND=JPRB) :: ZLOCST,ZCONRD,ZLON,ZLAT,ZHR
INTEGER(KIND=JPIM), PARAMETER :: JPERRN=100
INTEGER(KIND=JPIM) :: ILEV(JPERRN),ILON(JPERRN),JLEV,JLON,IERRN,JERRN
CHARACTER(LEN=200) :: CLVAR(JPERRN)
LOGICAL :: LLOK

REAL(KIND=JPRB) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('CHECKNAN',0,ZHOOK_HANDLE)
ASSOCIATE(RSTATI=>YDRIP%RSTATI,RHGMT=>YDRIP%RHGMT)

!-------------------------------------------------
! Sum all fluxes: the sum vectorises (fast computation).
! The ISNAN test will be performed on the sum, and will performed on the
! individuals only if the sum contains NaN.
! This approach optimizes the computation time.
!-------------------------------------------------
DO JLEV=0,KLEV
  DO JLON=KIDIA,KFDIA
    ZSUM(JLON,JLEV)=0._JPRB
  ENDDO
ENDDO
DO JLEV=0,KLEV
  DO JLON=KIDIA,KFDIA
    ZSUM(JLON,JLEV)=ZSUM(JLON,JLEV)+ &
    & PDIFCQLC(JLON,JLEV)+PDIFCQIC(JLON,JLEV)+PFIMCC(JLON,JLEV)+PFEDQLC(JLON,JLEV)+PFEDQIC(JLON,JLEV)+ &
    & PFEDQRC(JLON,JLEV)+PFEDQSC(JLON,JLEV)+PFCNEGQLC(JLON,JLEV)+PFCNEGQIC(JLON,JLEV)+ &
    & PFCNEGQRC(JLON,JLEV)+PFCNEGQSC(JLON,JLEV)+PFPLCH(JLON,JLEV)+PDIFCQ(JLON,JLEV)+PDIFCQI(JLON,JLEV)+ &
    & PDIFCQL(JLON,JLEV)+PDIFCS(JLON,JLEV)+PDIFTQ(JLON,JLEV)+PDIFTQI(JLON,JLEV)+PDIFTQL(JLON,JLEV)+ &
    & PDIFTS(JLON,JLEV)+PFCCQL(JLON,JLEV)+PFCCQN(JLON,JLEV)+PFCSQL(JLON,JLEV)+PFCSQN(JLON,JLEV)+ &
    & PFCQVNG(JLON,JLEV)+PFCQING(JLON,JLEV)+PFCQLNG(JLON,JLEV)+PFCQRNG(JLON,JLEV)+PFCQSNG(JLON,JLEV)+ &
    & PFPLCL(JLON,JLEV)+PFPLCN(JLON,JLEV)+PFPLCG(JLON,JLEV)+PFPLSL(JLON,JLEV)+PFPLSN(JLON,JLEV)+ &
    & PFPLSG(JLON,JLEV)+PSTRCU(JLON,JLEV)+PSTRCV(JLON,JLEV)+PSTRDU(JLON,JLEV)+PSTRDV(JLON,JLEV)+PSTRTU(JLON,JLEV)+ &
    & PSTRTV(JLON,JLEV)+PSTRMU(JLON,JLEV)+PSTRMV(JLON,JLEV)+PFRMH(JLON,JLEV)+PFRMQ(JLON,JLEV)+PFCHOZ(JLON,JLEV)+ &
    & PFPFPSL(JLON,JLEV)+PFPFPSN(JLON,JLEV)+PFPFPCL(JLON,JLEV)+PFPFPCN(JLON,JLEV)+PFPEVPSL(JLON,JLEV)+ &
    & PFPEVPSN(JLON,JLEV)+PFPEVPCL(JLON,JLEV)+PFPEVPCN(JLON,JLEV)
  ENDDO
ENDDO
LLOK=.TRUE.
DO JLEV=0,KLEV
  DO JLON=KIDIA,KFDIA
    IF(ISNAN(ZSUM(JLON,JLEV))) LLOK=.FALSE.
  ENDDO
ENDDO
IF(.NOT.LLOK) THEN
  !-------------------------------------------------
  ! Test fluxes individually.
  !-------------------------------------------------
  LLPDIFCQLC=.TRUE. ; LLPDIFCQIC=.TRUE. ; LLPFIMCC=.TRUE. ; LLPFEDQLC=.TRUE. ; LLPFEDQIC=.TRUE. 
  LLPFEDQRC=.TRUE. ; LLPFEDQSC=.TRUE. ; LLPFCNEGQLC=.TRUE. ; LLPFCNEGQIC=.TRUE.
  LLPFCNEGQRC=.TRUE. ; LLPFCNEGQSC=.TRUE. ; LLPFPLCH=.TRUE. ; LLPDIFCQ=.TRUE. ; LLPDIFCQI=.TRUE. 
  LLPDIFCQL=.TRUE. ; LLPDIFCS=.TRUE. ; LLPDIFTQ=.TRUE. ; LLPDIFTQI=.TRUE. ; LLPDIFTQL=.TRUE. 
  LLPDIFTS=.TRUE. ; LLPFCCQL=.TRUE. ; LLPFCCQN=.TRUE. ; LLPFCSQL=.TRUE. ; LLPFCSQN=.TRUE.
  LLPFCQVNG=.TRUE. ; LLPFCQING=.TRUE. ; LLPFCQLNG=.TRUE. ; LLPFCQRNG=.TRUE. ; LLPFCQSNG=.TRUE. 
  LLPFPLCL=.TRUE. ; LLPFPLCN=.TRUE. ; LLPFPLCG=.TRUE. ; LLPFPLSL=.TRUE. ; LLPFPLSN=.TRUE. ; LLPFPLSG=.TRUE.
  LLPSTRCU=.TRUE. ; LLPSTRCV=.TRUE. ; LLPSTRDU=.TRUE. ; LLPSTRDV=.TRUE. ; LLPSTRTU=.TRUE. ; LLPSTRTV=.TRUE.
  LLPSTRMU=.TRUE. ; LLPSTRMV=.TRUE. ; LLPFRMH=.TRUE. ; LLPFRMQ=.TRUE. ; LLPFCHOZ=.TRUE.
  LLPFPFPSL=.TRUE. ; LLPFPFPSN=.TRUE. ; LLPFPFPCL=.TRUE. ; LLPFPFPCN=.TRUE. ; LLPFPEVPSL=.TRUE.
  LLPFPEVPSN=.TRUE. ; LLPFPEVPCL=.TRUE. ; LLPFPEVPCN=.TRUE.
  
  ILEV(:)=0
  ILON(:)=0
  CLVAR(:)=' '
  IERRN=0
  
  DO JLEV=0,KLEV
    DO JLON=KIDIA,KFDIA
      IF(ISNAN(PDIFCQLC(JLON,JLEV)).AND.LLPDIFCQLC.AND.IERRN < JPERRN) THEN
        LLPDIFCQLC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFCQLC'
      ENDIF
      IF(ISNAN(PDIFCQIC(JLON,JLEV)).AND.LLPDIFCQIC.AND.IERRN < JPERRN) THEN
        LLPDIFCQIC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFCQIC'
      ENDIF
      IF(ISNAN(PFIMCC(JLON,JLEV)).AND.LLPFIMCC.AND.IERRN < JPERRN) THEN
        LLPFIMCC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFIMCC'
      ENDIF
      IF(ISNAN(PFEDQLC(JLON,JLEV)).AND.LLPFEDQLC.AND.IERRN < JPERRN) THEN
        LLPFEDQLC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFEDQLC'
      ENDIF
      IF(ISNAN(PFEDQIC(JLON,JLEV)).AND.LLPFEDQIC.AND.IERRN < JPERRN) THEN
        LLPFEDQIC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFEDQIC'
      ENDIF
      IF(ISNAN(PFEDQRC(JLON,JLEV)).AND.LLPFEDQRC.AND.IERRN < JPERRN) THEN
        LLPFEDQRC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFEDQRC'
      ENDIF
      IF(ISNAN(PFEDQSC(JLON,JLEV)).AND.LLPFEDQSC.AND.IERRN < JPERRN) THEN
        LLPFEDQSC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFEDQSC'
      ENDIF
      IF(ISNAN(PFCNEGQLC(JLON,JLEV)).AND.LLPFCNEGQLC.AND.IERRN < JPERRN) THEN
        LLPFCNEGQLC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCNEGQLC'
      ENDIF
      IF(ISNAN(PFCNEGQIC(JLON,JLEV)).AND.LLPFCNEGQIC.AND.IERRN < JPERRN) THEN
        LLPFCNEGQIC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCNEGQIC'
      ENDIF
      IF(ISNAN(PFCNEGQRC(JLON,JLEV)).AND.LLPFCNEGQRC.AND.IERRN < JPERRN) THEN
        LLPFCNEGQRC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCNEGQRC'
      ENDIF
      IF(ISNAN(PFCNEGQSC(JLON,JLEV)).AND.LLPFCNEGQSC.AND.IERRN < JPERRN) THEN
        LLPFCNEGQSC=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCNEGQSC'
      ENDIF
      IF(ISNAN(PFPLCH(JLON,JLEV)).AND.LLPFPLCH.AND.IERRN < JPERRN) THEN
        LLPFPLCH=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPLCH'
      ENDIF
      IF(ISNAN(PDIFCQ(JLON,JLEV)).AND.LLPDIFCQ.AND.IERRN < JPERRN) THEN
        LLPDIFCQ=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFCQ'
      ENDIF
      IF(ISNAN(PDIFCQI(JLON,JLEV)).AND.LLPDIFCQI.AND.IERRN < JPERRN) THEN
        LLPDIFCQI=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFCQI'
      ENDIF
      IF(ISNAN(PDIFCQL(JLON,JLEV)).AND.LLPDIFCQL.AND.IERRN < JPERRN) THEN
        LLPDIFCQL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFCQL'
      ENDIF
      IF(ISNAN(PDIFCS(JLON,JLEV)).AND.LLPDIFCS.AND.IERRN < JPERRN) THEN
        LLPDIFCS=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFCS'
      ENDIF
      IF(ISNAN(PDIFTQ(JLON,JLEV)).AND.LLPDIFTQ.AND.IERRN < JPERRN) THEN
        LLPDIFTQ=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFTQ'
      ENDIF
      IF(ISNAN(PDIFTQI(JLON,JLEV)).AND.LLPDIFTQI.AND.IERRN < JPERRN) THEN
        LLPDIFTQI=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFTQI'
      ENDIF
      IF(ISNAN(PDIFTQL(JLON,JLEV)).AND.LLPDIFTQL.AND.IERRN < JPERRN) THEN
        LLPDIFTQL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFTQL'
      ENDIF
      IF(ISNAN(PDIFTS(JLON,JLEV)).AND.LLPDIFTS.AND.IERRN < JPERRN) THEN
        LLPDIFTS=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PDIFTS'
      ENDIF
      IF(ISNAN(PFCCQL(JLON,JLEV)).AND.LLPFCCQL.AND.IERRN < JPERRN) THEN
        LLPFCCQL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCCQL'
      ENDIF
      IF(ISNAN(PFCCQN(JLON,JLEV)).AND.LLPFCCQN.AND.IERRN < JPERRN) THEN
        LLPFCCQN=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCCQN'
      ENDIF
      IF(ISNAN(PFCSQL(JLON,JLEV)).AND.LLPFCSQL.AND.IERRN < JPERRN) THEN
        LLPFCSQL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCSQL'
      ENDIF
      IF(ISNAN(PFCSQN(JLON,JLEV)).AND.LLPFCSQN.AND.IERRN < JPERRN) THEN
        LLPFCSQN=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCSQN'
      ENDIF
      IF(ISNAN(PFCQVNG(JLON,JLEV)).AND.LLPFCQVNG.AND.IERRN < JPERRN) THEN
        LLPFCQVNG=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCQVNG'
      ENDIF
      IF(ISNAN(PFCQING(JLON,JLEV)).AND.LLPFCQING.AND.IERRN < JPERRN) THEN
        LLPFCQING=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCQING'
      ENDIF
      IF(ISNAN(PFCQLNG(JLON,JLEV)).AND.LLPFCQLNG.AND.IERRN < JPERRN) THEN
        LLPFCQLNG=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCQLNG'
      ENDIF
      IF(ISNAN(PFCQRNG(JLON,JLEV)).AND.LLPFCQRNG.AND.IERRN < JPERRN) THEN
        LLPFCQRNG=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCQRNG'
      ENDIF
      IF(ISNAN(PFCQSNG(JLON,JLEV)).AND.LLPFCQSNG.AND.IERRN < JPERRN) THEN
        LLPFCQSNG=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCQSNG'
      ENDIF
      IF(ISNAN(PFPLCL(JLON,JLEV)).AND.LLPFPLCL.AND.IERRN < JPERRN) THEN
        LLPFPLCL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPLCL'
      ENDIF
      IF(ISNAN(PFPLCN(JLON,JLEV)).AND.LLPFPLCN.AND.IERRN < JPERRN) THEN
        LLPFPLCN=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPLCN'
      ENDIF
      IF(ISNAN(PFPLCG(JLON,JLEV)).AND.LLPFPLCG.AND.IERRN < JPERRN) THEN
        LLPFPLCG=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPLCG'
      ENDIF
      IF(ISNAN(PFPLSL(JLON,JLEV)).AND.LLPFPLSL.AND.IERRN < JPERRN) THEN
        LLPFPLSL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPLSL'
      ENDIF
      IF(ISNAN(PFPLSN(JLON,JLEV)).AND.LLPFPLSN.AND.IERRN < JPERRN) THEN
        LLPFPLSN=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPLSN'
      ENDIF
      IF(ISNAN(PFPLSG(JLON,JLEV)).AND.LLPFPLSG.AND.IERRN < JPERRN) THEN
        LLPFPLSG=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPLSG'
      ENDIF
      IF(ISNAN(PSTRCU(JLON,JLEV)).AND.LLPSTRCU.AND.IERRN < JPERRN) THEN
        LLPSTRCU=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PSTRCU'
      ENDIF
      IF(ISNAN(PSTRCV(JLON,JLEV)).AND.LLPSTRCV.AND.IERRN < JPERRN) THEN
        LLPSTRCV=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PSTRCV'
      ENDIF
      IF(ISNAN(PSTRDU(JLON,JLEV)).AND.LLPSTRDU.AND.IERRN < JPERRN) THEN
        LLPSTRDU=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PSTRDU'
      ENDIF
      IF(ISNAN(PSTRDV(JLON,JLEV)).AND.LLPSTRDV.AND.IERRN < JPERRN) THEN
        LLPSTRDV=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PSTRDV'
      ENDIF
      IF(ISNAN(PSTRTU(JLON,JLEV)).AND.LLPSTRTU.AND.IERRN < JPERRN) THEN
        LLPSTRTU=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PSTRTU'
      ENDIF
      IF(ISNAN(PSTRTV(JLON,JLEV)).AND.LLPSTRTV.AND.IERRN < JPERRN) THEN
        LLPSTRTV=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PSTRTV'
      ENDIF
      IF(ISNAN(PSTRMU(JLON,JLEV)).AND.LLPSTRMU.AND.IERRN < JPERRN) THEN
        LLPSTRMU=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PSTRMU'
      ENDIF
      IF(ISNAN(PSTRMV(JLON,JLEV)).AND.LLPSTRMV.AND.IERRN < JPERRN) THEN
        LLPSTRMV=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PSTRMV'
      ENDIF
      IF(ISNAN(PFRMH(JLON,JLEV)).AND.LLPFRMH.AND.IERRN < JPERRN) THEN
        LLPFRMH=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFRMH'
      ENDIF
      IF(ISNAN(PFRMQ(JLON,JLEV)).AND.LLPFRMQ.AND.IERRN < JPERRN) THEN
        LLPFRMQ=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFRMQ'
      ENDIF
      IF(ISNAN(PFCHOZ(JLON,JLEV)).AND.LLPFCHOZ.AND.IERRN < JPERRN) THEN
        LLPFCHOZ=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFCHOZ'
      ENDIF
      IF(ISNAN(PFPFPSL(JLON,JLEV)).AND.LLPFPFPSL.AND.IERRN < JPERRN) THEN
        LLPFPFPSL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPFPSL'
      ENDIF
      IF(ISNAN(PFPFPSN(JLON,JLEV)).AND.LLPFPFPSN.AND.IERRN < JPERRN) THEN
        LLPFPFPSN=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPFPSN'
      ENDIF
      IF(ISNAN(PFPFPCL(JLON,JLEV)).AND.LLPFPFPCL.AND.IERRN < JPERRN) THEN
        LLPFPFPCL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPFPCL'
      ENDIF
      IF(ISNAN(PFPFPCN(JLON,JLEV)).AND.LLPFPFPCN.AND.IERRN < JPERRN) THEN
        LLPFPFPCN=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPFPCN'
      ENDIF
      IF(ISNAN(PFPEVPSL(JLON,JLEV)).AND.LLPFPEVPSL.AND.IERRN < JPERRN) THEN
        LLPFPEVPSL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPEVPSL'
      ENDIF
      IF(ISNAN(PFPEVPSN(JLON,JLEV)).AND.LLPFPEVPSN.AND.IERRN < JPERRN) THEN
        LLPFPEVPSN=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPEVPSN'
      ENDIF
      IF(ISNAN(PFPEVPCL(JLON,JLEV)).AND.LLPFPEVPCL.AND.IERRN < JPERRN) THEN
        LLPFPEVPCL=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPEVPCL'
      ENDIF
      IF(ISNAN(PFPEVPCN(JLON,JLEV)).AND.LLPFPEVPCN.AND.IERRN < JPERRN) THEN
        LLPFPEVPCN=.FALSE.
        IERRN=IERRN+1
        ILEV(IERRN)=JLEV
        ILON(IERRN)=JLON
        CLVAR(IERRN)='PFPEVPCN'
      ENDIF
    ENDDO
  ENDDO
  
  DO JERRN=1,IERRN
    !
    !-------------------------------------------------
    ! A NaN has been found.
    !-------------------------------------------------
    !
    WRITE(NULERR,*) ' '
    WRITE(NULERR,*) 'CHECKNAN/ERROR : ',TRIM(CLVAR(JERRN)),' contains NaN value at ILEV=',ILEV(JERRN),' ILON=',ILON(JERRN)
    WRITE(NULERR,*) ' '
    WRITE(NULERR,*) 'Time of error: '
    WRITE(NULERR,*) '  NINDAT=',NINDAT
    WRITE(NULERR,*) '  KSTEP=',KSTEP
    WRITE(NULERR,*) '  TSPHY (physical time step)=',YDPHY2%TSPHY
    WRITE(NULERR,*) '  RSTATI (time in seconds since model integration start)=',RSTATI
    WRITE(NULERR,*) '  RHGMT (GMT time in seconds between 0 and 86400)=',RHGMT
    WRITE(NULERR,*) '  GMT time (in hours)=',RHGMT/3600._JPRB
    !
    !-------------------------------------------------
    ! ZLOCST : local solar time in hours.
    ! The constant 0.261799387 rad is 15 degrees (the Earth rotates 15 degrees per hour).
    !-------------------------------------------------
    !
    ZLOCST=MODULO(RHGMT,86400._JPRB)/3600.+PGELAM(ILON(JERRN))/0.261799387_JPRB
    WRITE(NULERR,*) '  Local solar time (in hours)=',ZLOCST
    !
    !-------------------------------------------------
    ! Location of error.
    !-------------------------------------------------
    !
    WRITE(NULERR,*) ' '
    WRITE(NULERR,*) 'Vertical location of error: '
    WRITE(NULERR,*) '  ILEV=',ILEV(JERRN)
    WRITE(NULERR,*) '  KLEV=',KLEV
    WRITE(NULERR,*) '  PAPHIF(',ILON(JERRN),',',ILEV(JERRN),')=',PAPHIF(ILON(JERRN),ILEV(JERRN))
    WRITE(NULERR,*) '  Geopotential at surface : PAPHI(',ILON(JERRN),',KLEV)=',PAPHIF(ILON(JERRN),KLEV)
    WRITE(NULERR,*) '  Land-sea mask PLSM=',PLSM(ILON(JERRN))
    WRITE(NULERR,*) ' '
    WRITE(NULERR,*) 'Horizontal location of error: '
    WRITE(NULERR,*) '  KIDIA=',KIDIA
    WRITE(NULERR,*) '  KFDIA=',KFDIA
    WRITE(NULERR,*) '  ILON(JERRN)=',ILON(JERRN)
    ZCONRD=45._JPRB/ATAN(1._JPRB)
    ZLON=PGELAM(ILON(JERRN))*ZCONRD
    IF(ZLON > 180._JPRB) ZLON=ZLON-360._JPRB
    ZLAT=ZCONRD*ASIN(PGEMU(ILON(JERRN)))
    WRITE(NULERR,fmt='(2(A,F11.5))') '  Latitude, Longitude (in degrees) : ',ZLAT,' , ',ZLON
    WRITE(NULERR,*) '  PMU0 (cosine of Sun zenithal angle)=',PMU0(ILON(JERRN))
    !
    !-------------------------------------------------
    ! Vertical profile.
    !-------------------------------------------------
    !
    WRITE(NULERR,*) ' '
    WRITE(NULERR,*) 'Vertical profile of p, T and relative humidity : '
    DO JLEV=1,KLEV
      ZHR=PQ(ILON(JERRN),JLEV)/MAX(1.E-6_JPRB,PQSAT(ILON(JERRN),JLEV))
      WRITE(NULERR,FMT=*) PAPRSF(ILON(JERRN),JLEV),PT(ILON(JERRN),JLEV),ZHR
    ENDDO
    !
    !-------------------------------------------------
    ! Surface temperature.
    !-------------------------------------------------
    !
    WRITE(NULERR,*) ' '
    WRITE(NULERR,*) 'Surface temperature : ',PTS(ILON(JERRN))
  ENDDO
  !
  !-------------------------------------------------
  ! Generates abort.
  !-------------------------------------------------
  !
  CALL ABOR1('CHECKNAN : a NaN found in physical fluxes !')
ENDIF ! LLOK

!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CHECKNAN',1,ZHOOK_HANDLE)
END SUBROUTINE CHECKNAN
