MODULE EC_PARKIND
!
!     *** Define usual kinds for strong typing ***
!
USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_INTPTR_T
IMPLICIT NONE
PRIVATE :: C_INTPTR_T
SAVE
!
!     Integer Kinds
!     -------------
!
INTEGER, PARAMETER :: JPIM = SELECTED_INT_KIND(9)
INTEGER, PARAMETER :: JPIB = SELECTED_INT_KIND(12)
INTEGER, PARAMETER :: JPIA = C_INTPTR_T

!
!     Real Kinds
!     ----------
!
INTEGER, PARAMETER :: JPRM = SELECTED_REAL_KIND(6,37)
INTEGER, PARAMETER :: JPRD = SELECTED_REAL_KIND(13,300)


END MODULE EC_PARKIND
